### ISSUE TITLE
streamSettings配置导致无法启动

### ISSUE THREAD

**Issue by leang521** [v2ray/discussion#101]
我的配置如下，但是只要配置了streamSettings项目端口就无法启动，如果不配置streamSettings项目则系统工作正常。
{
    "log": {
      "access": "/var/log/v2ray/access.log",
      "error": "/var/log/v2ray/error.log",
      "loglevel": "warning"
    },
    "policy": {
      "levels": {
        "0": {
          "handshake": 4,
          "connIdle": 300,
          "uplinkOnly": 2,
          "downlinkOnly": 5,
          "statsUserUplink": false,
          "statsUserDownlink": false,
          "bufferSize": 1024
        }
      },
      "system": {
        "statsInboundUplink": false,
        "statsInboundDownlink": false
      }
    },
    "routing": {
      "strategy": "rules",
      "settings": {
        "domainStrategy": "AsIs",
        "rules": [
          {
            "type": "field",
            "outboundTag": "outbound_slave_block",
            "protocol": [
              "bittorrent"
            ]
          }
        ]
      }
    },
    "inbound": {
      "port": ,
      "listen": "0.0.0.0",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "",
            "level": 0,
            "alterId": 64,
            "email": ""
          }
        ],
        "default": {
          "level": 0,
          "alterId": 32
        },
        "disableInsecureEncryption": true
      },
      "streamSettings": {//删除这个条目系统就可以正常运行
        "network": "mkcp",
        "security": "none",
        "kcpSettings": {
          "uplinkCapacity": 5,
          "downlinkCapacity": 100,
          "congestion": true,
          "header": {
            "type": "none"
          }
        }
      },
      "tag": "inbound_master_vmess",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "detour": {
        "to": "inbound_slave_vmess"
      }
    },
    "inboundDetour": [
      {
        "protocol": "vmess",
        "port": "",
        "tag": "inbound_slave_vmess",
        "settings": {
          "clients": [
            {
              "id": "",
              "level": 0,
              "alterId": 64,
              "email": ""
            }
          ],
          "default": {
            "level": 0,
            "alterId": 32
          },
          "disableInsecureEncryption": true
        },
        "streamSettings": {
          "network": "mkcp",
          "security": "none",
          "kcpSettings": {
            "uplinkCapacity": 5,
            "downlinkCapacity": 100,
            "congestion": true,
            "header": {
              "type": "none"
            }
          }
        },
        "allocate": {
          "strategy": "random",
          "concurrency": 2,
          "refresh": 5
        }
      },
      {
        "protocol": "shadowsocks",
        "port": ,
        "tag": "inbound_slave_shadowsocks",
        "settings": {
          "email": "",
          "method": "",
          "password": "",
          "level": 0,
          "ota": true,
          "network": "tcp,udp"
        }
      }
    ],
    "outbound": {
      "sendThrough": "0.0.0.0",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "AsIs"
      },
      "tag": "outbound_master_freedom",
    },
    "outboundDetour": [
      {
        "protocol": "blackhole",
        "settings": {},
        "tag": "outbound_slave_block"
      }
    ]
  }
端口无法启动时程序看不到问题
:~# service v2ray status
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-12-26 06:53:57 UTC; 3s ago
 Main PID: 31330 (v2ray)
    Tasks: 7 (limit: 502)
   CGroup: /system.slice/v2ray.service
           └─31330 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

Dec 26 06:53:57 leang1 systemd[1]: Started V2Ray Service.
Dec 26 06:53:57 leang1 v2ray[31330]: V2Ray 4.9.0 (Po) 20181212
Dec 26 06:53:57 leang1 v2ray[31330]: A unified platform for anti-censorship.
日志中显示
2018/12/26 07:16:53 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/26 07:17:26 121.10.143.92:26382 rejected  v2ray.com/core/proxy/shadowsocks: failed to read IV > EOF

**Comment by youwei5683** [comment]
个人建议去www.json.cn检查一下你的配置文件，我去检查了一下根本通过不了，何谈好用
