### ISSUE TITLE
V2RAY的SS可以支持一下混淆吗?

### ISSUE THREAD

**Issue by yuhuan21** [v2ray/discussion#107]
V2RAY4.1 FOR WINDOWS
请问Shadowsocks能不能支持一下http_simple和tls1.2_ticket_fastauth?因为我这里的运营商对Shadowsocks进行了限速,只有1兆的速度,SSR可以跑满百兆,谢谢

**Comment by tjLEIIQM3** [comment]
我反而觉得v2ray应该砍掉ss支持。

v2ray的很多设计都和ss不同，硬去支持既不稳定也不全面，同时给客户端设计添加麻烦。
另一方面ss(r)从服务端、客户端到面板已经很发展得很成熟，
既然用ss(r)直接用他们官方的客户端是更好的选择。

嫌多开个程序不舒服（不顺眼）的，先把右下的图标删到只剩一个再来辩。

**Comment by Cavolo** [comment]
ss自己已经砍掉obfs了

**Comment by CodeCrazy-guy** [comment]
用v2ray不用tls毫无意义。

ss可以被当作替补，但绝不推荐使用。
