### ISSUE TITLE
关于反向代理的安全性问题

### ISSUE THREAD

**Issue by viphant** [v2ray/discussion#110]
设置了反向代理后是不是任何人都可以连接进来了？比如为了能在家里控制办公室的电脑设置了WINDOWS的3389端口的远程桌面反向代理，那样就把办公室电脑给暴露出来，任何人知道了密码都可以访问了？
看了“白话文教程”的反向代理2安全性是有了，可是不能实现反墙和代理同时运行了，有好的解决方法吗？

**Comment by tjLEIIQM3** [comment]
我觉得安全问题应该由被反代理的软件自己解决，
不安全的软件本来就不应该在公网中开放出来。

然后需要同时使用多个功能，可以在服务器端多开放几端口，多写几个inbounds。
如果非要在同一个端口使用多个功能，我目前想到的是通过nginx的ws分流。
（如果哪位大佬有更好的方法，恳请分享出来）

下面只提供一些思路，具体配置请认真看手册，自行编写。

一、普通访问google需求
```js
client -> v2ray(in:socks, out:vmess.ws) -> nginx(http://test.com/v2ray) -> v2ray(in:vmess.ws, out:freedom)
```

二、开放ssh(好难表示，下面附加说明)
```js
ssh服务器 -> v2ray(bridge[out:freedom@22, out:vmess.ws]) -> nginx(http://test.com/sshserver) -> v2ray服务端
```
```js
ssh客户端 -> v2ray(in:dokodemo-door@2222 out:vmess.ws) -> nginx(http://test.com/sshclient) -> v2ray服务端
```

其中`v2ray服务端`配置是`v2ray(portal[in:vmess.ws, in:vmess.ws])`

上面用到的符号说明：
@表示端口。
in/out表示inbounds/outbounds。
nginx(...)表示nginx接收到这个地址的请求时直接转发出去。
bridge[...]表示通过配置v2ray的bridge功能，把两个outbounds绑起来发给远端portal。
portal[...]表示通过配置v2ray的portal功能，把两个inbounds绑起互相通信。

**Comment by viphant** [comment]
谢谢

**Comment by CodeCrazy-guy** [comment]
> 我觉得安全问题应该由被反代理的软件自己解决，
> 不安全的软件本来就不应该在公网中开放出来。
> 
> 然后需要同时使用多个功能，可以在服务器端多开放几端口，多写几个inbounds。
> 如果非要在同一个端口使用多个功能，我目前想到的是通过nginx的ws分流。
> （如果哪位大佬有更好的方法，恳请分享出来）
> 
> 下面只提供一些思路，具体配置请认真看手册，自行编写。
> 
> 一、普通访问google需求
> 
> ```js
> client -> v2ray(in:socks, out:vmess.ws) -> nginx(http://test.com/v2ray) -> v2ray(in:vmess.ws, out:freedom)
> ```
> 
> 二、开放ssh(好难表示，下面附加说明)
> 
> ```js
> ssh服务器 -> v2ray(bridge[out:freedom@22, out:vmess.ws]) -> nginx(http://test.com/sshserver) -> v2ray服务端
> ```
> 
> ```js
> ssh客户端 -> v2ray(in:dokodemo-door@2222, out:vmess.ws) -> nginx(http://test.com/sshclient) -> v2ray服务端
> ```
> 
> 其中`v2ray服务端`配置是`v2ray(portal[in:vmess.ws, in:vmess.ws])`
> 
> 上面用到的符号说明：
> @表示端口。
> in/out表示inbounds/outbounds。
> nginx(...)表示nginx接收到这个地址的请求时直接转发出去。
> bridge[...]表示通过配置v2ray的bridge功能，把两个outbounds绑起来发给远端portal。
> portal[...]表示通过配置v2ray的portal功能，把两个inbounds绑起互相通信。
> 
> 漏了说远程发起ssh访问时大概这样：
> `ssh -p 2222 user@127.0.0.1`

dalao，可否问你一下。

你知道v2ray支持socks5的前置代理吗？

因为我想在v2ray之前配置一个socks5的服务器作为中转。

它是纯socks5协议，而不包含shadowsocks和v2ray的协议。

可以实现吗?

我的配置贴在了这里：

https://github.com/v2ray/discussion/issues/129#issue-404018438

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
