### ISSUE TITLE
请问能提供一些常用配置文件的示例吗？

### ISSUE THREAD

**Issue by qingfengshi** [v2ray/discussion#111]
在V2ray改为新的配置文件格式之前，官方网站上有一些常用配置文件示例，比如动态端口，tcp伪装连接等等。现在配置文件格式更改，尽管看了配置说明，但是书写新的配置文件还是需要很多次试错。如果官方能提供一些示例文件，能够节省很多配置时间。对于新手可以直接修改对应的配置文件完成配置。

**Comment by kslr** [comment]
在文档中有一些工具，另外你可以选择一键安装。
