### ISSUE TITLE
V2Ray搭配Proxifier使用疑问

### ISSUE THREAD

**Issue by backup-tic-toc** [v2ray/discussion#117]
在直接设置系统代理为v2ray对应端口时, 是可以根据config.json的路由设置进行分流的, 但在使用Proxifier后, 所有流量都走了服务器, 没有在v2ray处进行分流, 请问有人知道原因么? 有没有什么方法可以使用Proxifier做系统代理+v2ray分流?

**Comment by youwei5683** [comment]
不能分流了。因为 Proxifier 是分应用代理的。
