### ISSUE TITLE
指定https://toutyrater.github.io/域名走代理

### ISSUE THREAD

**Issue by An0nymous0** [v2ray/discussion#119]
https://toutyrater.github.io/ 没有经过代理无法访问。 如何配置指定这个域名走代理。 配置了pac文件没有效果

**Comment by supersndqd** [comment]
个人怀疑你是dns被污染

**Comment by ToutyRater** [comment]
@An0nymous0 如果你是使用 V2RayN，在设置项中路由的要代理的域名中新增一行 toutyrater.github.io

**Comment by ToutyRater** [comment]
@supersndqd 白话文教程已经被 GFW 认证了

**Comment by supersndqd** [comment]
他已经要用pac走代理了,没有成功而已,所以要分析原因,我分析是dns

**Comment by iochen** [comment]
> @supersndqd 白话文教程已经被 GFW 认证了

疑似只是DNS污染，我这边（仅开启DoH）：
![image](https://user-images.githubusercontent.com/28243989/52164937-808cbb00-2734-11e9-9a7a-4ee7f2f7b770.png)

**Comment by An0nymous0** [comment]
V2Rayx版本问题。更新了解决了
