### ISSUE TITLE
geosite和geoip配置文件的生成方法能不能整理成独立程序？

### ISSUE THREAD

**Issue by Cwek** [v2ray/discussion#12]
如题。

**Comment by VictoriaRaymond** [comment]
基本就是输入一段protobuf，主程序很简单，没有必要特别分离出来。用其它语言重写一遍也很方便。

https://github.com/v2ray/ext/blob/master/tools/geosites/main/main.go

https://github.com/v2ray/ext/blob/master/tools/geoip/main/main.go
