### ISSUE TITLE
freebsd mac下脚本问题

### ISSUE THREAD

**Issue by supersndqd** [v2ray/discussion#120]
我在freebsd和mac下,v2ray &,然后都需要按一下回车键,本人技术有限,写的脚本都会卡,请教一下怎么解决这个问题

**Comment by kslr** [comment]
你能进一步补充这个问题吗？

**Comment by supersndqd** [comment]
在v2ray目录下./v2ray &
让他进后台，但是他显示了正常运行的信息，然后就挂在那，需要敲回车，我才能看到shell提示符
在脚本里，如果后面还有命令，比如
#！/bin/sh
/v2ray/v2ray &
/chengxu/chengxu
这种情况，就卡在v2ray这里，脚本运行不下去，本人比较白，求帮助

**Comment by supersndqd** [comment]
mac下brew已经解决

**Comment by kslr** [comment]
```nohup v2ray > v.log &
```
