### ISSUE TITLE
是否考虑增加更多的 balancer 筛选策略

### ISSUE THREAD

**Issue by persevereVon** [v2ray/discussion#122]
我的代理 IP 时不时会被禁，但是过段时间又会好。所以我准备了好几个 IP，想通过 balances 配置筛选出当前最好的出口，但是目前的筛选策略只有随即筛选，想问大大是否考虑增加更多筛选策略比如说检查最优的网络进行通讯？
感谢大大给社会的贡献。

**Comment by persevereVon** [comment]
@VictoriaRaymond

**Comment by kslr** [comment]
https://github.com/v2ray/v2ray-core/issues/1378
