### ISSUE TITLE
tls

### ISSUE THREAD

**Issue by hzlmy2002** [v2ray/discussion#128]

**Comment by VictoriaRaymond** [comment]
Moving to discussion, unless there is strong evidence of TLS fingerprint.

**Comment by liberal-boy** [comment]
@hzlmy2002 如上面教主所言。此外昨晚我们讨论了性能问题，考虑各个平台，chacha20 是比较好的选择。因此目前不考虑在配置文件中提供选项。如果您仍然希望修改 cipher 顺序，可以修改[这里的源代码](https://github.com/v2ray/v2ray-core/blob/master/transport/internet/tls/config.go#L159)重新编译（仅在 allowInsecureCiphers == false 时有效）。

**Comment by klzgrad** [comment]
基于TLS参数的指纹检测的实例（Tor）和商业产品（思科Stealthwatch）参见这里的[文献综述](https://gist.github.com/klzgrad/73a6365c895e02d0e5d879cad1ffb691#%E6%B5%81%E9%87%8F%E6%B7%B7%E6%B7%86%E7%9A%84%E6%96%B9%E6%B3%95)。一个更加极端的例子见[这里](https://groups.google.com/forum/#!topic/traffic-obf/fwAN-WWz2Bk)和[这里](https://groups.google.com/forum/#!topic/traffic-obf/BpFSCVgi5rs)（“模仿老版Firefox指纹？我直接把老版Firefox全封了”）。这些应该可以回答TLS参数指纹检测的技术可行性的问题。

> 和主流客户端（chrome，Firefox）看齐（上策）

正好，我做了一个跟Chrome指纹一模一样的客户端。见：https://github.com/klzgrad/naiveproxy

**Comment by hzlmy2002** [comment]
不过如果v2ray直接用go官方的tls库的而没有改过的话问题倒也不大。墙总不能识别出go客户端就block，这也太草率了

**Comment by koolwiki** [comment]
> 
> 
> 基于TLS参数的指纹检测的实例（Tor）和商业产品（思科Stealthwatch）参见这里的[文献综述](https://gist.github.com/klzgrad/73a6365c895e02d0e5d879cad1ffb691#%E6%B5%81%E9%87%8F%E6%B7%B7%E6%B7%86%E7%9A%84%E6%96%B9%E6%B3%95)。一个更加极端的例子见[这里](https://groups.google.com/forum/#!topic/traffic-obf/fwAN-WWz2Bk)和[这里](https://groups.google.com/forum/#!topic/traffic-obf/BpFSCVgi5rs)（“模仿老版Firefox指纹？我直接把老版Firefox全封了”）。这些应该可以回答TLS参数指纹检测的技术可行性的问题。
> 
> > 和主流客户端（chrome，Firefox）看齐（上策）
> 
> 正好，我做了一个跟Chrome指纹一模一样的客户端。见：https://github.com/klzgrad/naiveproxy

请问你这个支持websocks吗？

**Comment by skywfan** [comment]
最近一个月我连续两个域名被污染了，不知道有没有关系

**Comment by hzlmy2002** [comment]
你上面是不是放了什么不好的东西？
