### ISSUE TITLE
Docker 镜像链接的 git 仓库 404 了

### ISSUE THREAD

**Issue by shynome** [v2ray/discussion#13]
地址: https://github.com/v2ray/install

**Comment by VictoriaRaymond** [comment]
移到了 ext 下：https://github.com/v2ray/ext/blob/master/docker/dev/Dockerfile

Docker hub 的说明已更新。Docker hub 不允许直接修改 dockerfile 地址，目前 docker image 是由 docker cloud 编译并发布的。
