### ISSUE TITLE
我最近使用V2RAY被準確識別???

### ISSUE THREAD

**Issue by JimmyChangJY** [v2ray/discussion#131]
座標 深圳 + 電信 
Server 放在 台灣家中，跳動IP，300M上傳
4.12到4.13版本
使用一個月下來，沒有任何問題 mKCP + wechat-video or mKCP + utp 改來改去 
port 試過 8080 試過 11111
但是上個禮拜發現，常常在深圳電腦開機之後無法連線後
我馬上電腦關掉V2ray ，改成使用SSR，連向同一個SERVER
又可以翻牆了，表示我的 V2ray 被準確識別了嗎??

**Comment by tjLEIIQM3** [comment]
单凭这一个结果很难判断是不是被准确识别。
可以试下连网上别人分享的v2ray节点，看是不是所有节点都不可用。

同时组网方式多种多样，系统环境也千差万别，
所以就算所有v2ray节点都连不上，也不一定是墙的影响。
这个真得靠你自己多尝试排查原因。

**Comment by JimmyChangJY** [comment]
對不起，我沒有表達清楚，是連續兩個server
都是一樣情況，不是單一server，所以我很緊張，我要是沒有v2ray可以用，我會瘋掉

**Comment by freesilent** [comment]
我也遇到了类似的问题，我的vps部署了v2ray和ss，最近v2ray连不上了，换了协议和端口都失败，但是原先部署的ss却没有问题。通过v2rayN测试服务器速度，一段时间后会提示“远程服务器返回错误: (500) 内部服务器错误。”

**Comment by skyrockgz** [comment]
500错误请检查服务器时间和本地是不是差距大过2分钟

**Comment by freesilent** [comment]
> 
> 
> 500错误请检查服务器时间和本地是不是差距大过2分钟

后来换了端口和协议就正常了。
