### ISSUE TITLE
近几天突然无法使用了，ip没有被封

### ISSUE THREAD

**Issue by ZeronoFreya** [v2ray/discussion#133]
服务端使用的最新的docker版v2ray，
系统是centos7
客户端返回
`[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp ip: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed`

xshell能连上，服务器上布置的网站也能打开，就是v2ray上不了网，服务器商是Vultr，

重新创建一个服务器是可以连接的，

请问该怎么解决？

**Comment by wolgy** [comment]
试过修改协议吗。比如改成mkcp之类的

**Comment by ZeronoFreya** [comment]
> 
> 
> 试过修改协议吗。比如改成mkcp之类的

改了，没用，试着重新创建了服务器就可以连上，但旧服务器上配置了很多东西，不太想迁移

**Comment by kslr** [comment]
重新部署更换协议
