### ISSUE TITLE
DNS分流失败

### ISSUE THREAD

**Issue by ccboxes** [v2ray/discussion#135]
我希望通过V2ray客户端自带的路由功能实现DNS分流——国内域名走114，国外走1.1.1.1 ，但尝试数遍均无法成功，请问我的配置文件哪里有问题？
"routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": [
          "geoip:cn"
        ],
        "outboundTag": "direct"
      }
    ]
  },
  "dns": {
    "servers": [
      {
        "address": "114.114.114.114",
        "port": 53,
        "domains": [
          "geosite:cn"
        ]
      },
      "1.1.1.1",
      "8.8.8.8",
      "localhost"
    ]
  }

**Comment by Platway** [comment]
我遇到同樣的問題
