### ISSUE TITLE
Can I configure tlsSettings globally  in the "transport" section?

### ISSUE THREAD

**Issue by octopusthu** [v2ray/discussion#136]
Can I configure tlsSettings globally  in the "transport" section, like:

```
{
  ...
  "transport": {
    "tlsSettings": {
      "certificates": [
        ...
      ]
    }
  }
  ...
}
```

The [doc](https://www.v2ray.com/chapter_02/05_transport.html) does not mention this.

**Comment by VictoriaRaymond** [comment]
No. It is not supported. You have to configure TLS in individual stream settings.

**Comment by octopusthu** [comment]
> No. It is not supported. You have to configure TLS in individual stream settings.

Any plan to add this as a feature?

**Comment by VictoriaRaymond** [comment]
We don't have plan for this right now. You may submit a feature request to the core/ repo.
