### ISSUE TITLE
基于apache2实现tls+ws中遇到的问题

### ISSUE THREAD

**Issue by qingfengshi** [v2ray/discussion#138]
因为服务器上有别的服务需要apache，想使用apache来实现tls+ws，apache版本为2.4.7，v2ray为4.15版本。

主要参考白话文教程的方法来进行配置，https://toutyrater.github.io/advanced/wss_and_web.html。发现使用其中介绍的基于wstunnel的apache配置，apache无法重启，提示语句“ProxyPass ws://127.0.0.1:10000/ray/ upgrade=WebSocket”语法错误。但是使用rewrite方法可以实现apache代理，https://ferrummagnus.com/2017/12/22/v2ray-websocket-tls-apache/

但是，使用rewrite的配置后，发现ssl测试结果从A变为C，想测试一下wstunnel的配置，但是看了apache的官方文件，也看了网上关于apache配置的讨论（https://www.bountysource.com/issues/56270847-ws-tls-webserver-http-https-404），也没能找出上面那一句的语法错误在哪里，有哪位大神能帮忙看一下不。

**Comment by pwrliang** [comment]
你缺少相关的module
sudo a2enmod ssl
sudo a2enmod proxy
sudo a2enmod proxy_wstunnel
sudo a2enmod proxy_http
sudo a2enmod rewrite
sudo a2enmod headers

**Comment by kslr** [comment]
问题解决了吗，现在可以关闭issue吗

**Comment by litanid** [comment]
我也遇到这个问题了，上面的Module也加载了，问题依旧，怎么破？大神

**Comment by litanid** [comment]
> 因为服务器上有别的服务需要apache，想使用apache来实现tls+ws，apache版本为2.4.7，v2ray为4.15版本。
> 
> 主要参考白话文教程的方法来进行配置，[https://toutyrater.github.io/advanced/wss_and_web.html。发现使用其中介绍的基于wstunnel的apache配置，apache无法重启，提示语句“ProxyPass](https://toutyrater.github.io/advanced/wss_and_web.html%E3%80%82%E5%8F%91%E7%8E%B0%E4%BD%BF%E7%94%A8%E5%85%B6%E4%B8%AD%E4%BB%8B%E7%BB%8D%E7%9A%84%E5%9F%BA%E4%BA%8Ewstunnel%E7%9A%84apache%E9%85%8D%E7%BD%AE%EF%BC%8Capache%E6%97%A0%E6%B3%95%E9%87%8D%E5%90%AF%EF%BC%8C%E6%8F%90%E7%A4%BA%E8%AF%AD%E5%8F%A5%E2%80%9CProxyPass) ws://127.0.0.1:10000/ray/ upgrade=WebSocket”语法错误。但是使用rewrite方法可以实现apache代理，https://ferrummagnus.com/2017/12/22/v2ray-websocket-tls-apache/
> 
> 但是，使用rewrite的配置后，发现ssl测试结果从A变为C，想测试一下wstunnel的配置，但是看了apache的官方文件，也看了网上关于apache配置的讨论（[https://www.bountysource.com/issues/56270847-ws-tls-webserver-http-https-404），也没能找出上面那一句的语法错误在哪里，有哪位大神能帮忙看一下不。](https://www.bountysource.com/issues/56270847-ws-tls-webserver-http-https-404%EF%BC%89%EF%BC%8C%E4%B9%9F%E6%B2%A1%E8%83%BD%E6%89%BE%E5%87%BA%E4%B8%8A%E9%9D%A2%E9%82%A3%E4%B8%80%E5%8F%A5%E7%9A%84%E8%AF%AD%E6%B3%95%E9%94%99%E8%AF%AF%E5%9C%A8%E5%93%AA%E9%87%8C%EF%BC%8C%E6%9C%89%E5%93%AA%E4%BD%8D%E5%A4%A7%E7%A5%9E%E8%83%BD%E5%B8%AE%E5%BF%99%E7%9C%8B%E4%B8%80%E4%B8%8B%E4%B8%8D%E3%80%82)

请问你的问题解决了吗?

**Comment by qingfengshi** [comment]
可以试试这个，我在白话文教程的基础上修改的。
<VirtualHost *:443>
  ServerName mydomain.com
  SSLEngine On
  SSLCertificateFile /etc/v2ray.crt
  SSLCertificateKeyFile /etc/v2ray/v2ray.key

  SSLProtocol -All +TLSv1 +TLSv1.1 +TLSv1.2
  SSLCipherSuite HIGH:!aNULL

  <LocationMatch "/ray/">
    ProxyPass ws://127.0.0.1:1051/ray/
    ProxyAddHeaders Off
    ProxyPreserveHost On
    RequestHeader set Host %{HTTP_HOST}s
    RequestHeader set X-Forwarded-For %{REMOTE_ADDR}s
  </LocationMatch>
</VirtualHost>

**Comment by litanid** [comment]
多谢，这个启动Apache2倒不会产生错误。但是V2ray还是没成功连上上网，有待查实。

**Comment by qingfengshi** [comment]
你检查一下v2ray的路径，端口什么的设置是不是和apache一致了，我跑着没有问题。
