### ISSUE TITLE
用V2ray内置DNS服务器，解析大陆地区CDN网站到国外IP。

### ISSUE THREAD

**Issue by 5high** [v2ray/discussion#147]
下面配置可以实现用v2ray作为DNS服务器用，但是下面配置无法让taobao等国内cdn加速网址实现自动分流。

```javascript
{
    "log": {
        "loglevel": "access"
    },
    "inbounds": [
        {
            "port": 1080,
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "accounts": [
                    {
                        "user": "v2ray",
                        "pass": "v2ray"
                    }
                ],
                "udp": true
            }
        },
        {
            "port": 8080,
            "protocol": "http"
        },
        {
            "domainOverride": [
                "tls",
                "http"
            ],
            "listen": "0.0.0.0",
            "port": 12345,
            "protocol": "dokodemo-door",
            "settings": {
                "followRedirect": true
            },
            "streamSettings": {
                "sockopt": {
                    "mark": 100,
                    "tcpFastOpen": true,
                    "tproxy": "tproxy"
                }
            }
        },
        {
            "port": 53,
            "tag": "dns-in",
            "protocol": "dokodemo-door",
            "settings": {
                "address": "1.1.1.1",
                "port": 53,
                "network": "tcp,udp"
            }
        }
    ],
    "outbounds": [
        {
            "mux": {
                "enabled": true
            },
            "tag": "proxy",
            "protocol": "vmess",
            "settings": {
                "vnext": [
                    {
                        "address": "address",
                        "port": 55665,
                        "users": [
                            {
                                "id": "",
                                "alterId": 64
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "kcp",
                "kcpSettings": {
                    "header": {
                        "type": "utp"
                    }
                }
            }
        },
        {
            "tag": "direct",
            "protocol": "freedom",
            "settings": {
                "response": null
            }
        },
        {
            "tag": "blockout",
            "protocol": "blackhole",
            "settings": {
                "response": {
                    "type": "http"
                }
            }
        },
        {
            "protocol": "dns",
            "tag": "dns-out"
        }
    ],
    "routing": {
        "rules": [
            {
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "domain": [
                    "geosite:cn"
                ],
                "type": "field",
                "port": null,
                "outboundTag": "direct"
            }
        ],
        "domainStrategy": "IPIfNonMatch"
    },
    "dns": {
        "servers": [
            {
                "address": "114.114.114.114",
                "port": 53,
                "domains": [
                    "geosite:cn"
                ]
            },
            "localhost"
        ]
    }
}
```

**Comment by VictoriaRaymond** [comment]
你的dns-in和dns-out没有用路由连起来

**Comment by 5high** [comment]
能否给个连起来的例子呢？

**Comment by VictoriaRaymond** [comment]
https://steemit.com/cn/@v2ray/dns 最下面

**Comment by 5high** [comment]
我加过这个到路由里，一样没效果，而且还解析很慢

**Comment by 5high** [comment]
"routing": {
        "rules": [
            {
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "domain": [
                    "geosite:cn"
                ],
                "type": "field",
                "port": null,
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "inboundTag": "dns-in",
                "outboundTag": "dns-out"
            }
        ],
        "domainStrategy": "IPIfNonMatch"
    },l

如果配置成上面这样的路由查询回出问题

C:\WINDOWS\system32>nslookup www.taobao.cn 172.xxx
DNS request timed out.
    timeout was 2 seconds.
服务器:  UnKnown
Address:  172

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
非权威应答:
DNS request timed out.
    timeout was 2 seconds.
名称:    www.taobao.cn
Addresses:  66.198.178.111
          66.198.178.121

**Comment by VictoriaRaymond** [comment]
ip 和 domain 需要拆分成两个 rule

**Comment by 5high** [comment]
拆分成2个rule确实正常了，但是请看下面总是请求第三次才返回记录，包括解析国内域名。

C:\WINDOWS\system32>nslookup www.sohu.com 172.xx.xx.xx
DNS request timed out.
    timeout was 2 seconds.
服务器:  UnKnown
Address:  172.xx.xx.xx

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
非权威应答:
DNS request timed out.
    timeout was 2 seconds.
名称:    www.sohu.com
Addresses:  118.244.253.70
          118.244.253.69
          118.244.253.68


C:\WINDOWS\system32>nslookup www.facebook.com 172.xx.xx.xx
DNS request timed out.
    timeout was 2 seconds.
服务器:  UnKnown
Address:  172.xx.xx.xx

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
非权威应答:
名称:    www.facebook.com
Addresses:  200:2:f3b9:bb27::
          31.13.75.17

**Comment by VictoriaRaymond** [comment]
这是一个已知问题，目前还不清楚为什么Windows的nslookup会有这样的问题，在其它平台上无法重现。

**Comment by 5high** [comment]
如果我不增加json路由里面的内容，在Windows下面可以正常lookup，只是不能分流，你可以试试看我说的，也许可以帮你定位问题。

**Comment by kingwilliam** [comment]
大约情况:
如果客户是windows, 如果用fixed ip就会正常.
如果客户是windows, 如果用DCHP就会出现异常.

以下是client config(已简略)
`{

	"dns": {
		"servers": [
			"1.1.1.1",
			{
				"address": "114.114.114.114",
				"port": 53,
				"domains": ["geosite:cn"]
			}
		]
	},

	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
			{
				"type": "field",
				"inboundTag": "dns-in",
				"outboundTag": "dns-out"
			},
		]
	},

	"inbounds": [
		// dokodemo-door:53
		{
			"protocol": "dokodemo-door",
			"port": 53,
			"tag": "dns-in",
			"settings": {
				"address": "8.8.8.8",
				"port": 53,
				"network": "udp,tcp"
				// "timeout": 0,
				// "followredirect": false
			}
		}
	],

	"outbounds": [
		// dns
		{
			"tag": "dns-out",
			"protocol": "dns"
		},
	],
}
`

**Comment by eycorsican** [comment]
@VictoriaRaymond 看起来也是跟 https://github.com/v2ray/v2ray-core/issues/1565 有关。

@5high 的情况，nslookup 会有一个 AAAA 查询，如果查的是没有 AAAA 记录的域名，V2Ray 要等超时，而且没有返回，估计是因为这个而做了几次重复请求，出现了几次超时（不太清楚细节

@kingwilliam 的情况，有时候系统做 DNS 解析时是会先发 AAAA 查询的，但如果也是查到没 AAAA 记录的域名，[V2Ray 不返回任何数据](https://github.com/v2ray/v2ray-core/blob/da8efb4afec3132360bf8ad522944e2f93f49b65/proxy/dns/dns.go#L227)（正确处理方法是返回空 answer 加 NOERROR），系统就继续把 DNS search domain 的后缀加上继续做 AAAA 查询，这时 DNS 服务器那么返回的应该是 NXDOMAIN 了，V2Ray 依然没能正确处理，如果有多个 search domain 的话估计会轮番去查然后接着超时。

参考：https://tools.ietf.org/html/rfc4074#section-3

**Comment by sunraywii** [comment]
> 拆分成2个rule确实正常了，但是请看下面总是请求第三次才返回记录，包括解析国内域名。
> 
> C:\WINDOWS\system32>nslookup [www.sohu.com](http://www.sohu.com) 172.xx.xx.xx
> DNS request timed out.
> timeout was 2 seconds.
> 服务器: UnKnown
> Address: 172.xx.xx.xx
> 
> DNS request timed out.
> timeout was 2 seconds.
> DNS request timed out.
> timeout was 2 seconds.
> 非权威应答:
> DNS request timed out.
> timeout was 2 seconds.
> 名称: [www.sohu.com](http://www.sohu.com)
> Addresses: 118.244.253.70
> 118.244.253.69
> 118.244.253.68
> 
> C:\WINDOWS\system32>nslookup [www.facebook.com](http://www.facebook.com) 172.xx.xx.xx
> DNS request timed out.
> timeout was 2 seconds.
> 服务器: UnKnown
> Address: 172.xx.xx.xx
> 
> DNS request timed out.
> timeout was 2 seconds.
> DNS request timed out.
> timeout was 2 seconds.
> 非权威应答:
> 名称: [www.facebook.com](http://www.facebook.com)
> Addresses: 200:2:f3b9:bb27::
> 31.13.75.17

你好，请问你的IPTABLES 是怎么设置呢？我按照网上资料尝试，始终无法转发UDP
