### ISSUE TITLE
How can I provide my own dat file ?

### ISSUE THREAD

**Issue by itshaadi** [v2ray/discussion#148]
there is a service run by Iran gov which provides monthly records of new websites that are hosted in Iran. and used bandwidth while visiting these websites is 50% off.

 so I was wondering how can I provide my own dat file? more specifically how can I create the right file for v2ray to recognize since it should contain a tag!?

> IPs from file: Such as "ext:file:tag". The value must begin with ext: (lowercase), and followed by filename and tag. The file is placed in resource directory, and has the same format of geoip.dat. **The tag must exist in the file**.

**Comment by VictoriaRaymond** [comment]
There are two dat files used by V2Ray: geosite.dat and geoip.dat. They are produced via [domain-list-community](https://github.com/v2ray/domain-list-community) and [geoip](https://github.com/v2ray/geoip) respectively. 

I believe you are talking about geosite.dat. The file is generated through a series of domain lists (in the data/ directory). You have two options for your Iran websites. 1) Submit all these website into domian-list-community. They can be put under a new file named 'geolocation-ir' I suppose. 2) Create your own data file. You may follow this [main.go](https://github.com/v2ray/domain-list-community/blob/master/main.go). The content of geosite.dat is a serialization of [GeoSiteList proto](https://github.com/v2ray/v2ray-core/blob/master/app/router/config.proto#L68).

**Comment by itshaadi** [comment]
@VictoriaRaymond 
should I follow the same procedure for IP? I can do both the service provides them in XLS format (ugh!).
is there some way that doesn't involve Golang (besides community list) I'm not skilled enough to use Go.

**Comment by VictoriaRaymond** [comment]
For domain-list-community, the easiest way, as I mentioned above, is to add a new file in the [data/](https://github.com/v2ray/domain-list-community/tree/master/data) directory. For example, if the file is named 'geolocation-ir', it will be available via 'geoste:geolocation-ir' in V2Ray configuration. The file content is plain text. You can create and update that file directly on Github. Your changes will be automatically included in the next release of V2Ray. In this way, all Iran users can benefit from your changes through our official release.

As for Geoip, it is generated based on [MaxMind country IP database](https://dev.maxmind.com/geoip/geoip2/geolite2/). It should already contain IP ranges for Iran ('geoip:ir'). However, If you really want to add a new tag, you have to modify the main.go, similar to the [private IP list](https://github.com/v2ray/geoip/blob/master/main.go#L118).

**Comment by hadifarnoud** [comment]
I have issues with `geoip:ir` it doesn't seem to work. This is how I tested:

I created an invalid proxy which does not work
I set `geoip:ir` and `domain:ir` in rules
I went to a few website that I'm sure their server is inside Iran.

In this scenario, every site with .ir domain works and loads fine but any website that is hosted in Iran but does not have .ir domain does not work. that only means one thing, `geoip:ir` not working. (btw I set IPIfNonMatch)

am I missing anything here?

**Comment by NightMachinery** [comment]
[**@itshaadi**](https://github.com/itshaadi) commented on [Feb 18, 2019, 11:09 PM GMT+3:30](https://github.com/v2ray/discussion/issues/148#issue-411619293 "2019-02-18T19:39:45Z - Replied by Github Reply Comments"):
> there is a service run by Iran gov which provides monthly records of new websites that are hosted in Iran. and used bandwidth while visiting these websites is 50% off.
> 
> so I was wondering how can I provide my own dat file? more specifically how can I create the right file for v2ray to recognize since it should contain a tag!?
> 
> > IPs from file: Such as "ext:file:tag". The value must begin with ext: (lowercase), and followed by filename and tag. The file is placed in resource directory, and has the same format of geoip.dat. **The tag must exist in the file**.

What's the URL of that service?

**Comment by itshaadi** [comment]
> What's the URL of that service?

https://g2b.ito.gov.ir/index.php/site/page/view/list_ip

and you can download the list as spreadsheet here:
https://g2b.ito.gov.ir/index.php/site/page/view/download

note that this list contains a lot of dead websites and/or duplicates.

**Comment by DuckSoft** [comment]
> I have issues with `geoip:ir` it doesn't seem to work. This is how I tested:
> 
> I created an invalid proxy which does not work
> I set `geoip:ir` and `domain:ir` in rules
> I went to a few website that I'm sure their server is inside Iran.
> 
> In this scenario, every site with .ir domain works and loads fine but any website that is hosted in Iran but does not have .ir domain does not work. that only means one thing, `geoip:ir` not working. (btw I set IPIfNonMatch)
> 
> am I missing anything here?

If you put `geoip:ir` and `domain:ir` together in a single route, like:
```json
{"domain":["domain:ir"], "ip": ["geoip:ir"]}
```
Then you will get the intersection, not the union, thus not working. This is already stated in V2Ray documentation.

What you should have done is to split it up to two rules, like:
```json
{"domain":["domain:ir"]}
{"ip":["geoip:ir"]}
```
Then you will get the result of union instead of intersection.

**Comment by hadifarnoud** [comment]
@ducksoft

this did not work either
```JSON
      "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": ["geosite:ir"]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:ir",
          "geoip:private"
        ]
      }
    ]
  }
```
