### ISSUE TITLE
Vmess WS works over VPN, does not work without VPN

### ISSUE THREAD

**Issue by Doc-Saintly** [v2ray/discussion#150]
First off - this seems great and I'm looking forward to it working fully! Thanks for all your work!

When I test using VPN, I am able to connect to my v2ray server using VMess and WS. Once I try to connect directly (behind great firewall), I get this error:

> 2019/02/18 07:32:51 [Warning] v2ray.com/core: V2Ray 4.15.0 started
2019/02/18 07:32:57 tcp:127.0.0.1:59414 accepted tcp:ww.xx.yy.zz:20481
2019/02/18 07:32:57 tcp:127.0.0.1:59417 accepted tcp:ww.xx.yy.zz:20481
2019/02/18 07:33:01 [Warning] [811916710] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://xxx.yyy/zzz): 502 Bad Gateway > websocket: bad handshake v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://xxx.yyy/zzz):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2019/02/18 07:33:04 [Warning] [456182281] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://xxx.yyy/zzz): 502 Bad Gateway > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed

On the server, I see these issues:
> 2019/02/19 05:14:16 127.0.0.1:51006 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user

The client config is below. I tried commenting out the special routing and it did not make a difference, because the issue seems to be with the initial handshake.
> {
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false
    }
  },
  "inboundDetour": [
    {
        "port": 8123,
        "listen": "127.0.0.1",
        "protocol": "http",
        "settings": {}
    }
  ],
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [{
        "address": "xxx.yyy.zzz",
        "port": 443,
        "users": [{ 
            "id": "00000-1111...",
            "level": 1,
            "alterId": 64,
            "security": "aes-128-gcm"
        }]
      }]
    },
    "streamSettings":{
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
            "serverName": "",
			"allowInsecure": false
        },
        "wsSettings": {
			"connectionReuse": true,
            "path": "/zzz"
        }
    },
    "tag": "forgin"
  },
  "outboundDetour": [
    {
        "protocol": "freedom",
        "settings": {},
        "tag": "direct"
    }
  ],
  /* "routing": { 
    "strategy": "rules",
    "settings": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "chinaip",
                "outboundTag": "direct"
            },
            {
                "type": "chinasites",
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "ip": [
                    "0.0.0.0/8",
                    "10.0.0.0/8",
                    "100.64.0.0/10",
                    "127.0.0.0/8",
                    "169.254.0.0/16",
                    "172.16.0.0/12",
                    "192.0.0.0/24",
                    "192.0.2.0/24",
                    "192.168.0.0/16",
                    "198.18.0.0/15",
                    "198.51.100.0/24",
                    "203.0.113.0/24",
                    "::1/128",
                    "fc00::/7",
                    "fe80::/10"
                ],
                "outboundTag": "direct"
            }
        ]
    }
  },*/
  "policy": {
    "levels": {
      "0": {"uplinkOnly": 0}
    }
  }
}

**Comment by kslr** [comment]
502 Bad Gateway > websocket: bad handshake

**Comment by Doc-Saintly** [comment]
> 
> 
> 502 Bad Gateway > websocket: bad handshake

Thanks - I noticed that too. But why would that not happen on VPN? Where can I debug the handshake?

**Comment by kslr** [comment]
Is your time correct?
