### ISSUE TITLE
不明BUG，开起代理后不能进入国内一些正常网站。

### ISSUE THREAD

**Issue by 12956** [v2ray/discussion#153]
开起代理后有时会不定时不能进入像B站这些，或者op.gg  报500 或502  关掉代理，或者开直连。或者关闭win网络设置里面的代理下的脚本也不能解决，有时又会突然能进，多数不能进，开启或关闭V2ray开机启动都试了，用的google浏览器，win10自带也有这种，外网正常能访问。

**Comment by kslr** [comment]
你需要提供进一步配置信息，5**属于服务端错误。
