### ISSUE TITLE
V2RayW V2RayN V2RayN V2RayS 有哪些区别

### ISSUE THREAD

**Issue by ivanlee93** [v2ray/discussion#154]
V2RayW V2RayN V2RayN V2RayS 
这四个那个稳定好用一些。选择综合征表示好纠结。官方其实可以统一一个完善的版本

**Comment by tjLEIIQM3** [comment]
这些都是个人开发者无私分享出来的软件，
官方不应该因为开发者的水平不同或者每个软件设计理念或者用户数量不同而差别对待。
所以像现在这样全部列出来让使用者自己选择是最合适的做法。

综合各平台来猜，官方大概推荐手动编辑config.json

**Comment by tauyyy** [comment]
同感，这种客户端太多了，看得眼花缭乱
