### ISSUE TITLE
v2ray 怎么支持链路聚合加速？同时使用多个服务器

### ISSUE THREAD

**Issue by QGB** [v2ray/discussion#156]

**Comment by kslr** [comment]
1. 多个outbound
2. routing balancers

**Comment by QGB** [comment]
@kslr  有文档可以参考吗， 多个outbound怎么设定权重，可以实现自动测速选择最优路线吗

**Comment by kslr** [comment]
现在不行，4X版本会实现

**Comment by Super-Ivan** [comment]
> 现在不行，4X版本会实现
冒昧问下，有无可能实现类似mptcp的功能，下载大文件时自动拆分一条tcp长连接为多个连接，多个outbound同时下载再合并呢？

**Comment by Super-Ivan** [comment]
> 现在不行，4X版本会实现

冒昧问下，有无可能实现类似mptcp的功能，下载大文件时自动拆分一条tcp长连接为多个连接，多个outbound同时下载再合并呢？

**Comment by QGB** [comment]
> > 现在不行，4X版本会实现
> 
> 冒昧问下，有无可能实现类似mptcp的功能，下载大文件时自动拆分一条tcp长连接为多个连接，多个outbound同时下载再合并呢？

这个只能应用层 http去实现吧，直接拆tcp对方服务器不认

**Comment by HaoweiCh** [comment]
客户端连接多个服务器，网络出口从一个口出去，网络在服务端聚合多个连接出口在一个tcp 请求
