### ISSUE TITLE
一个避免DNS污染的实验

### ISSUE THREAD

**Issue by VictoriaRaymond** [v2ray/discussion#159]
V2Ray 自 4.15 起开放了 DNS 服务，可以做为一个 DNS 中继来使用。同时我们提出了一种避免 DNS 污染的方法。这种方法的好处是 1) 可以配合任何现有的 DNS 服务器来使用，比如使用 114 DNS 也能获得正确的 IP 地址。2) 比起 hosts 文件的方式，V2Ray 的方式在配置完成后不需要在客户端维护 IP 地址。当然，缺点是会产生一些费用。

简单来说，这个方法是在查询时重写了被查询的域名，比如浏览器需要查询`www.v2ray.com`的 IP 地址，V2Ray 收到查询之后，转写为 `www.vicemc.net`。以新的域名发出的查询，不会遭到拦截，也就不会被污染。

当然这种情况仅适用于一个服务器有多个域名的情况，那如果一个域名没有同站的其它域名怎么办？比如这个：`www.discuss.com.hk`。答案很简单，自己买一个域名，自己做别名解析。比如我们做了一个`d03.d.mux.cool`与之对应。由于`mux.cool`不是一个被污染域名，所以用它来做别名，就不会被污染。

以下我们公开一个列表，由 V2Ray 维护的被污染域名。直接贴到 V2Ray 配置中就可以避开 DNS 污染。

```javascript
"hosts": {
  "domain:v2ray.com": "www.vicemc.net",

  "domain:bbc.co.uk": "b01.d.mux.cool",
  "domain:bloomberg.com": "b02.d.mux.cool",
  "domain:conoha.jp": "c01.d.mux.cool",
  "domain:dropbox.com": "d01.d.mux.cool",
  "domain:duckduckgo.com": "d02.d.mux.cool",
  "domain:discuss.com.hk": "d03.d.mux.cool"
}
```

如果你需要映射其它的域名，请留言，我们会追加到上述列表中。

**Comment by xjasonlyu** [comment]
有幾個問題（也有可能是我理解問題？）。

1. 用的人多了以後，諸如mux.cool的域名會不會被牆投毒
2. 像domain:discuss.com.hk -> d03.d.mux.cool這樣，如果discuss.com.hk的子域名對應的ip都是不同的，但 d03.d.mux.cool 對應的ip卻是唯一的，那不就解析出問題了嗎？
3. 理論上如果能維護一個很長的紀錄，比如 a.bc.de -> a.bc.de.example.com, 就可以無限獲得乾淨的dns紀錄了。（但感覺這個工作量有點大）
4. 對於有cdn的域名來說，這樣獲得的ip可能不是最佳ip？

**Comment by VictoriaRaymond** [comment]
>  用的人多了以後，諸如`mux.cool`的域名會不會被GFW列入污染名單。

会的。所以这不是一个通用型的工具。它更适合小范围的使用，比如朋友间共同维护一个域名，减少被污染的风险。

> 像`domain:discuss.com.hk -> d03.d.mux.cool`這樣，如果`discuss.com.hk`的子域名對應的IP都是不同的，但 `d03.d.mux.cool` 對應的IP卻是唯一的，那不就解析出問題了嗎？

和你说的 3 类似，不同IP的子域做不同的映射。

> 對於有cdn的域名來說，這樣獲得的IP可能不是最佳IP？

取决于上游的解析策略，理论上可以获取最优 IP，但需要测试一下。

**Comment by xjasonlyu** [comment]
而且，如果這種方式在應用較廣泛的時候，GFW完全可以通過檢查DNS返回A/AAAA記的IP是否在黑名單裡而進行對數據包修改達到再次污染的目的。

**Comment by wzc0x0** [comment]
我觉得 应该往dns加密传输查询方向靠

**Comment by VictoriaRaymond** [comment]
这种IP是不会有黑名单的，否则DNS污染就没有意义了。

**Comment by tefiszx** [comment]
感觉这个科技没那么黑，有点萌

**Comment by cpdyj** [comment]
个人感觉还是实现下dns over tls比较好

**Comment by wzc0x0** [comment]
我觉得即使解析出来的正确ip地址 在墙内运营商绕路 依然访问缓慢 用户体验不佳

**Comment by cherrot** [comment]
一旦公用，流量大了就被针对，是一个跟时间赛跑的方法。 

不过可以提供个小工具，将污染域名列表用指定的域名建立CNAME并更新到目标DNS服务商（比如cloudflare），这样任何一个拥有自己域名的人都可以方便使用，避免树大招风。

**Comment by kkkgo** [comment]
推荐下dnscrypt重写的go版本，很好用，能自动找到链接最快的dns服务器，负载均衡等等，配置非常简单
另外我觉得维护一个gfw.dat来DNS分流比较省事
还有想要这个项目的功能，不知道有没有兴趣实现：
https://github.com/pymumu/smartdns

**Comment by kkkgo** [comment]
https://github.com/jedisct1/dnscrypt-proxy
Supports DNS-over-HTTPS (DoH) using TLS 1.3, and DNSCrypt.
Load balancing: pick a set of resolvers, dnscrypt-proxy will automatically measure and keep track of their speed, and balance the traffic across the fastest available ones.
Automatic background updates of resolvers lists.

**Comment by sunsan05** [comment]
你可以安装1.1.1.1的DoH服务到机器上，然后使用127.0.0.1#53来取得正确的DNS。
