### ISSUE TITLE
v2ray +caddy + http2 + tls 无法连接

### ISSUE THREAD

**Issue by CodeCrazy-guy** [v2ray/discussion#160]
v2ray 版本4.16

以下是v2ray配置：
`{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "info"
  },
  "inbounds": [
    {
      "port": 10000,
"listen":"127.0.0.1",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "96947595-8993-4aed-824d-05b417543921",
            "alterId": 16
          }
	]
      },
      "streamSettings": {
        "network": "h2",
        "security": "tls",
        "tlsSettings": {
"serverName":"xxxx.com",
          "certificates": [
            {
              "certificateFile": "/opt/caddyserver/.caddy/acme/acme-v02.api.letsencrypt.org/sites/xxxx.com/xxxx.com.crt",
              "keyFile": "/opt/caddyserver/.caddy/acme/acme-v02.api.letsencrypt.org/sites/xxxx.com/xxxx.com.key"
            }
          ]
	},
	"tcpSettings": {},
        "httpSettings": {
          "path": "/Dgj149xP/",
"host":"2.planv.ga"
        },
	"kcpSettings": {},
        "wsSettings": {},
        "quicSettings": {}
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"`

以下是caddy 配置：

`https://xxxx.com:443 {
log /var/log/caddy.log
root /data/www
proxy /Dgj149xP/ https://127.0.0.1:10000 {
       insecure_skip_verify
       header_upstream X-Forwarded-Proto "https"
       header_upstream Host "xxxx.com"
    }
}`

防火墙配置：

‘:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 10000 -j ACCEPT
-A INPUT -p udp -m state --state NEW -m udp --dport 10000 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited’

v2rayN客户端报错：
'[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: unexpected status421] > v2ray.com/core/common/retry: all retry attempts failed'

服务器端使用centos7 

客户端使用v2rayN

没有加CDN

实在不知道这个failed to find an available destination  unexpected status421是什么意思

google半天也没什么结果。

请问这里有人知道吗？

**Comment by CodeCrazy-guy** [comment]
服务端没有报错，但是客户端连不上。

**Comment by kslr** [comment]
failed to find an available destination

**Comment by CodeCrazy-guy** [comment]
不知道这个找不到可用的目标是哪个目标呢？

我的配置有错误吗..

**Comment by CodeCrazy-guy** [comment]
> failed to find an available destination

不知道这个找不到目标是哪个目标呢。

我的配置有错误吗？

**Comment by CodeCrazy-guy** [comment]
> failed to find an available destination

    {
      "configVersion": 2,
      "address": "xxx.com",
      "port": 443,
      "id": "96947595-8993-4aed-824d-05b417543921",
      "alterId": 16,
      "security": "aes-128-gcm",
      "network": "h2",
      "remarks": "",
      "headerType": "none",
      "requestHost": "",
      "path": "/Dgj149xP/",
      "streamSecurity": "tls",
      "allowInsecure": "",
      "configType": 1,
      "testResult": "",
      "subid": ""
    }

这是v2rayN客户端的配置

**Comment by kslr** [comment]
建议你从官方手册重新配置，可能是https方面的问题。

**Comment by aeroxy** [comment]
Caddy (1.0.4 / 2-beta) doesn't support v2ray http/2 protocol. It considers v2ray's response invalid.
