### ISSUE TITLE
域名和正则与ip规则同时用的时候匹配策略的问题

### ISSUE THREAD

**Issue by kkkgo** [v2ray/discussion#161]
想实现正则匹配优先级比域名匹配高，于是把正则写在了前面，但测试发现如果后面的规则匹配到域名的话正则就失效，后面的规则是dat里面的

**Comment by VictoriaRaymond** [comment]
请给出你的测试用例和结果。

**Comment by kkkgo** [comment]
测试用例1：
```javascript
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [

      {
        "type": "field",
        "port": null,
        "outboundTag": "v6proxy",
        "domain": [
          "regexp:ipv6"
        ],
        "ip": [
          "2404::/8"
        ]
      },
      {
        "type": "field",
        "port": null,
        "outboundTag": "block",
        "domain": [
          "domain:ipv6.google.com"
        ]
      }

    ]
  }

``` 

注：ipv6.baidu.com为2400:da00:2::29，ipv6.google.com为2404:6800:4005:806::200e
预期结果：
按照预期，ipv6.baidu.com应该无法访问（因为正则匹配了ipv6但不匹配ip段且默认出口非v6），Ipv6.google.com可以被访问（因为优先级排在前面，并且正则和ip段同时被匹配）
实际测试结果
ipv6.baidu.com正常匹配到规则v6，正常访问
ipv6.google.com被block

测试用例2：
```javascript
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [

      {
        "type": "field",
        "port": null,
        "outboundTag": "block",
        "domain": [
          "regexp:ipv6"
        ],
        "ip": [
          "2404::/8"
        ]
      },
      {
        "type": "field",
        "port": null,
        "outboundTag": "v6proxy",
        "domain": [
          "domain:ipv6.google.com"
        ]
      }

    ]
  }

``` 

注：ipv6.baidu.com为2400:da00:2::29，ipv6.google.com为2404:6800:4005:806::200e
预期结果：
按照预期，ipv6.baidu.com应该无法访问（因为默认出口非v6），Ipv6.google.com无法被访问（因为优先级排在前面，并且正则和ip段同时被匹配）
实际测试结果
ipv6.baidu.com正常访问
ipv6.google.com正常访问

**Comment by kkkgo** [comment]
日志显示connection to tcp:ipv6.google.com:443 > v2ray.com/core/common/retry: [dial tcp: lookup ipv6.google.com: no such host] > v2ray.com/core/common/retry: all retry attempts failed
但是本地nslookup可以正常查到v6地址

**Comment by kkkgo** [comment]
似乎不是正则和域名的优先级问题，而是【domain和ip】优先级比domain低

测试用例3：
```javascript
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [

      {
        "type": "field",
        "port": null,
        "outboundTag": "v6proxy",
        "domain": [
          "domain:ipv6.ip.sb"
        ],
        "ip": [
          "2001:470:19:66:6666:6666:6666:6666"

        ]
      },
      {
        "type": "field",
        "port": null,
        "outboundTag": "block",
        "domain": [
          "domain:ipv6.ip.sb"
        ]
      }

    ]
  }
```
测试结果：访问ipv6.ip.sb失败
注：默认出口不支持v6

测试用例4：
```javascript
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [

      {
        "type": "field",
        "port": null,
        "outboundTag": "v6proxy",
        "domain": [
          "domain:ipv6.ip.sb"
        ],
        "ip": [
          "2001:470:19:66:6666:6666:6666:6666"

        ]
      },
      {
        "type": "field",
        "port": null,
        "outboundTag": "block",
        "domain": [
          "domain:ipv6.baidu.com"
        ]
      }

    ]
  }
```
测试结果：访问ipv6.ip.sb成功
注：默认出口不支持v6

**Comment by VictoriaRaymond** [comment]
https://v2ray.com/chapter_02/03_routing.html#routingobject

domainStrategy: "AsIs" | "IPIfNonMatch" | "IPOnDemand"

域名解析策略，根据不同的设置使用不同的策略。

* "AsIs": 只使用域名进行路由选择。默认值。
* "IPIfNonMatch": 当域名没有匹配任何规则时，将域名解析成 IP（A 记录或 AAAA 记录）再次进行匹配；
  * 当一个域名有多个 A 记录时，会尝试匹配所有的 A 记录，直到其中一个与某个规则匹配为止
  * 解析后的 IP 仅在路由选择时起作用，转发的数据包中依然使用原始域名；
* "IPOnDemand": 当匹配时碰到任何基于 IP 的规则，将域名立即解析为 IP 进行匹配；

**Comment by kkkgo** [comment]
> https://v2ray.com/chapter_02/03_routing.html#routingobject
> 
> domainStrategy: "AsIs" | "IPIfNonMatch" | "IPOnDemand"
> 
> 域名解析策略，根据不同的设置使用不同的策略。
> 
> * "AsIs": 只使用域名进行路由选择。默认值。
> * "IPIfNonMatch": 当域名没有匹配任何规则时，将域名解析成 IP（A 记录或 AAAA 记录）再次进行匹配；
>   
>   * 当一个域名有多个 A 记录时，会尝试匹配所有的 A 记录，直到其中一个与某个规则匹配为止
>   * 解析后的 IP 仅在路由选择时起作用，转发的数据包中依然使用原始域名；
> * "IPOnDemand": 当匹配时碰到任何基于 IP 的规则，将域名立即解析为 IP 进行匹配；

按我的理解，我以上的测试使用了IPIfNonMatch，并且是"当域名匹配了规则（见测试用例4和5）"，应该是符合要求的，
并且根据https://v2ray.com/chapter_02/03_routing.html#routingobject中的说法，
>"当多个属性同时指定时，这些属性需要同时满足，才可以使当前规则生效。“

也就是说我可以同时指定domain和ip数组，因此我觉得我的操作应该是符合文档要求的

**Comment by VictoriaRaymond** [comment]
你可以看一下v2ray的log。

**Comment by kkkgo** [comment]
对于测试用例5的log：
>2019/02/26 22:35:25 tcp:127.0.0.1:14768 accepted tcp:ipv6.ip.sb:443
2019/02/26 22:35:25 [Info] [799344317] v2ray.com/core/proxy/socks: TCP Connect request to tcp:ipv6.ip.sb:443
2019/02/26 22:35:25 [Info] [799344317] v2ray.com/core/app/dispatcher: sniffed domain: ipv6.ip.sb
2019/02/26 22:35:25 [Info] [799344317] v2ray.com/core/app/dispatcher: taking detour [block] for [tcp:ipv6.ip.sb:443]
对于测试用例4的log：
>2019/02/26 22:33:15 [Info] [216155082] v2ray.com/core/proxy/socks: TCP Connect request to tcp:ipv6.ip.sb:443
2019/02/26 22:33:15 [Info] [216155082] v2ray.com/core/app/dispatcher: sniffed domain: ipv6.ip.sb
2019/02/26 22:33:15 tcp:127.0.0.1:14472 accepted tcp:ipv6.ip.sb:443
2019/02/26 22:33:16 [Info] [216155082] v2ray.com/core/app/dispatcher: taking detour [v6proxy] for [tcp:ipv6.ip.sb:443]
2019/02/26 22:33:16 [Info] [216155082] v2ray.com/core/common/mux: dispatching request to tcp:ipv6.ip.sb:443

log表现和以上所描述情况相符合。

**Comment by VictoriaRaymond** [comment]
所以路由部分没有问题，是吗

**Comment by kkkgo** [comment]
> 所以路由部分没有问题，是吗

log表现和以上所描述情况相符合是指日志和我描述一样选择了错误（非预期）的路由

**Comment by VictoriaRaymond** [comment]
测试4 选择了 "block"。第一个规则因为包含IP，而目标域名不包含IP，所以跳过了。第二个规则匹配。

测试5 选择了 "v6proxy"。和上面一样，但是第二个规则也不匹配，所以查询了 IP 之后重新走一遍规则，匹配了第一个。

两个都是正常表现。

**Comment by kkkgo** [comment]
> 目标域名不包含IP

不太理解，目标域名不包含IP是什么意思？目标域名ipv6.sb.ip的ip地址确实是2001:470:19:66:6666:6666:6666:6666，
而且根据文档的说法，
> "当多个属性同时指定时，这些属性需要同时满足，才可以使当前规则生效。“

也就是说，测试用例5，同时指定了域名和IP，这条规则被应用就说明了目标域名同时符合域名和IP的要求。

**Comment by kkkgo** [comment]
如果是说使用了IPIfNonMatch去匹配域名的时候没有解析ip的行为导致匹配ip属性始终为假的话，我认为这是一个bug，理想预期应该是匹配域名后还有ip属性的话就再解析域名去检查是否匹配，满足文档所说的“当多个属性同时指定时，这些属性需要同时满足，才可以使当前规则生效。”

**Comment by VictoriaRaymond** [comment]
IPIfNonMatch的设定就是这样，你描述的行为是 IPOnDemand。

**Comment by kkkgo** [comment]
如果我用IPOnDemand，那么我其他规则就需要考虑顺序降低维护路由的复杂性，按我的理解，我认为IPIfNonMatch的存在意义是无需考虑“domain和ip规则哪个顺序优先“而是让包含域名的规则优先匹配，否则的话所有使用IPIfNonMatch的路由都可以用调整顺序后的IPOnDemand来解决，那么IPIfNonMatch就没有存在的意义。

**Comment by VictoriaRaymond** [comment]
你的理解是错的。IPIfNonMatch和IPOnDemand的区别只是在于IP查询的时机。路由的优先级始终是从上到下的，不存在优先级变化的情况。无论哪种情况，你都需要按需求调整路由顺序。

**Comment by kkkgo** [comment]
> 你的理解是错的。IPIfNonMatch和IPOnDemand的区别只是在于IP查询的时机。路由的优先级始终是从上到下的，不存在优先级变化的情况。无论哪种情况，你都需要按需求调整路由顺序。


路由器的优先级是从上到下没错，但使用IPIfNonMatch的话，就算把IP规则放在前面，只要后面能匹配到域名，IP规则就会被跳过，因此逻辑上是“域名和IP规则之间谁的优先高”的话是域名优先级高一些，对于IPIfNonMatch也需要根据需要调整路由也没错，但那应该是域名与域名规则之间、IP规则与IP规则之间的顺序。除了优先级的问题，使用IPIfNonMatch的目的也希望减少不必要的解析时间和避免DNS污染的域名匹配到错误的IP规则，所以这是不使用IPOnDemand的理由，因此如果我要写”domain和ip属性同时满足“的规则的话，无论哪一种方案都不能完美。
因此我提出一个Feature，对于某一条规则，可以单独指定domainStrategy属性，没指定的按全局的domainStrategy属性处理。

**Comment by VictoriaRaymond** [comment]
你当然可以提一个这样的feature request，但是我很怀疑具体的使用场景。你可以例举一个目前的配置做不到的场景吗？

**Comment by kkkgo** [comment]
> 你当然可以提一个这样的feature request，但是我很怀疑具体的使用场景。你可以例举一个目前的配置做不到的场景吗？

比如我使用一个正则去匹配一个域名，但正则匹配还不够，我还希望他是同时满足某个IP段，而这条规则的后面的dat文件或者后面的正则里面可能会匹配到前面的域名，这样就会导致我前面的这条规则失效。

**Comment by kkkgo** [comment]
一个举例，某服务的域名非常多 ，但他会包含abc，但正则匹配还不够，我还知道该服务满足某个ip段，这是我就可以写这样的规则。

**Comment by VictoriaRaymond** [comment]
IPOnDemand不能满足你的需求的情况，只有在你的这条规则之前出现了纯IP匹配的规则。这种情况下，把这条规则提前到所有纯IP规则之前即可。

**Comment by kkkgo** [comment]
> IPOnDemand不能满足你的需求的情况，只有在你的这条规则之前出现了纯IP匹配的规则。这种情况下，把这条规则提前到所有纯IP规则之前即可。

https://github.com/v2ray/discussion/issues/161#issuecomment-467515266
如上楼所述，使用IPIfNonMatch的目的也希望减少不必要的解析时间和避免DNS污染的域名匹配到错误的IP规则，所以这是不使用IPOnDemand的理由

**Comment by VictoriaRaymond** [comment]
那你提一个feature request吧
