### ISSUE TITLE
新建的V2Ray，只要一看youtube就会断线，正常吗？

### ISSUE THREAD

**Issue by dasonchan** [v2ray/discussion#163]
新人一个，首先要感谢各位的贡献。

前阵子我的ISP将我的SS线路给封了，换了几个服务器后也没办法持续使用。
几天前我建了一个V2Ray服务器，除了偶尔会断线以外一直没有什么问题，只要重新连接一下就可以了。
但是从今天开始只要我看youtube视频，我的VPS就会断线，而且修改端口和协议后同样的事情会继续发生。
请问各位遇到过类似的问题吗？

以下是我的config.json：
{
  "outbounds" : [
    {
      "sendThrough" : "0.0.0.0",
      "mux" : {
        "enabled" : false,
        "concurrency" : 8
      },
      "protocol" : "vmess",
      "settings" : {
        "vnext" : [
          {
            "address" : "**.**.**.**",
            "users" : [
              {
                "id" : "********",
                "alterId" : 64,
                "security" : "auto",
                "level" : 0
              }
            ],
            "port" : ****
          }
        ]
      },
      "tag" : "test",
      "streamSettings" : {
        "wsSettings" : {
          "path" : "",
          "headers" : {

          }
        },
        "quicSettings" : {
          "key" : "",
          "header" : {
            "type" : "none"
          },
          "security" : "none"
        },
        "tlsSettings" : {
          "allowInsecure" : false,
          "alpn" : [
            "http\/1.1"
          ],
          "serverName" : "server.cc",
          "allowInsecureCiphers" : false
        },
        "httpSettings" : {
          "path" : ""
        },
        "kcpSettings" : {
          "header" : {
            "type" : "none"
          },
          "mtu" : 1350,
          "congestion" : false,
          "tti" : 20,
          "uplinkCapacity" : 5,
          "writeBufferSize" : 1,
          "readBufferSize" : 1,
          "downlinkCapacity" : 20
        },
        "tcpSettings" : {
          "header" : {
            "type" : "none"
          }
        },
        "security" : "none",
        "network" : "kcp"
      }
    }
  ],
  "routings" : [
    {
      "name" : "all_to_main",
      "domainStrategy" : "AsIs",
      "rules" : [
        {
          "type" : "field",
          "outboundTag" : "main",
          "port" : "0-65535"
        }
      ]
    },
    {
      "name" : "bypasscn_private_apple",
      "domainStrategy" : "IPIfNonMatch",
      "rules" : [
        {
          "type" : "field",
          "outboundTag" : "direct",
          "domain" : [
            "localhost",
            "domain:me.com",
            "domain:lookup-api.apple.com",
            "domain:icloud-content.com",
            "domain:icloud.com",
            "domain:cdn-apple.com",
            "domain:apple-cloudkit.com",
            "domain:apple.com",
            "domain:apple.co",
            "domain:aaplimg.com",
            "domain:guzzoni.apple.com",
            "geosite:cn"
          ]
        },
        {
          "type" : "field",
          "outboundTag" : "direct",
          "ip" : [
            "geoip:private",
            "geoip:cn"
          ]
        },
        {
          "type" : "field",
          "outboundTag" : "main",
          "port" : "0-65535"
        }
      ]
    },
    {
      "name" : "all_to_direct",
      "domainStrategy" : "AsIs",
      "rules" : [
        {
          "type" : "field",
          "outboundTag" : "direct",
          "port" : "0-65535"
        }
      ]
    }
  ]
}

**Comment by kkkgo** [comment]
换WebSocket+TLS+Web试试

**Comment by dasonchan** [comment]
> 换WebSocket+TLS+Web试试

谢谢你的建议 我用了ws+tls+caddy之后一段时间确实很不错。
但是今天开始Wi-Fi情况下无论是手机还是电脑都会不稳定，并频繁出现：
019/03/07 23:55:06 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://xxx.xxx.xxx/):  > read tcp ********->*******: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://xxx.xxx.xxx/):  > dial tcp ***.***.****:443: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://abc.topdianfeng.top/):  > read tcp ****.***.****:50278->****.***.***:443: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://xxx.xxx.xxxp/):  > read tcp *******->*********:443: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
2019/03/07 23:55:06 [Info] v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/03/07 23:55:07 [Info] [3648160756] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2019/03/07 23:55:07 [Info] [425229488] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/03/07 23:55:07 [Info] [4240366619] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled

请问这是被宽带运营商干扰了吗？

**Comment by kslr** [comment]
连接超时了，你可以在故障时手动测试

**Comment by DaedalusT** [comment]
被你的ISP的QoS给阻断了

**Comment by Schnappi-02** [comment]
> 被你的ISP的QoS给阻断了

老哥，QoS阻断是什么原理？？经常听说但不清楚具体是说什么。

**Comment by kslr** [comment]
https://en.wikipedia.org/wiki/Quality_of_service
