### ISSUE TITLE
有美术好的可以给做个v2ray的图标吗？

### ISSUE THREAD

**Issue by 0312birdzhang** [v2ray/discussion#168]
像下面这样风格的（第一个是原图，白色背景下看不清😂）

![icon-settings-v2ray](https://user-images.githubusercontent.com/1762041/53538291-10613180-3b48-11e9-91d8-d96129c1ac47.png)
> 上面是原图

![image](https://user-images.githubusercontent.com/1762041/53538325-2cfd6980-3b48-11e9-97f6-c26f1ebe85dd.png)

**Comment by tjLEIIQM3** [comment]
单颜色的图标只在特定的主题下才好看，
比如你选的这张在任务管理器里面就会变成白茫茫一片什么都没有。浅颜色背景下也很难看清。
反而v2ray.com里面那个图在各种系统下表现都不错，
可惜只有一张大图，没有16x16, 128x128等多种尺寸的ico文件，不方便在程序中使用。

**Comment by 0312birdzhang** [comment]
我是要放到你说的那种场景下的（SailfishOS），如下图。现在暂时用了个小飞机的图标代替吧

![_20190228_001](https://user-images.githubusercontent.com/1762041/53544121-f16e9980-3b5f-11e9-8a45-5e0c769ab87c.png)

**Comment by 0312birdzhang** [comment]
已使用 https://www.iconfont.cn/collections/detail?cid=503 中的 V2
