### ISSUE TITLE
在服务端access日志里发现了奇怪的东西

### ISSUE THREAD

**Issue by qwer133245** [v2ray/discussion#169]
2019/02/28 08:37:05 xxx.xxx.xx.xx:xxxxx rejected  v2ray.com/core/proxy/vmess/encoding: invalid user

IP地址已经打码了， 请问这是what？

**Comment by 0312birdzhang** [comment]
`invalid user` 大概是扫端口的或者uuid不对的吧

**Comment by kslr** [comment]
可能的原因：

    客户端和服务器端的用户 ID 不匹配；
    客户端和服务器端的用户 alterId 不匹配；
    客户端与服务器的时间不匹配，误差不能超过90秒钟；
