### ISSUE TITLE
关于流量统计的使用方法

### ISSUE THREAD

**Issue by NonXZhu** [v2ray/discussion#17]
按照官方文档上的理解，我认为是：
"stats": {
    "user>>>[email]>>>traffic>>>uplink": "xxxx@yyy.com"    //clients里面也加上email这项
}
如果是这样的话，那我应该用什么命令查询这个统计？

**Comment by nobody3u** [comment]
仅供参考,请根据你的情况修改参数
```
# 查询命令
# Linux
v2ctl api --server="127.0.0.1:1090" StatsService.GetStats 'name: "inbound>>>statin>>>traffic>>>downlink" reset: false'

# Windows
v2ctl api --server="127.0.0.1:1090" StatsService.GetStats "name: """"inbound>>>statin>>>traffic>>>downlink"""" reset: false"
```

**Comment by missyea** [comment]
按照楼上提供的方法还是不行...

**Comment by nobody3u** [comment]
@missyea 
查询命令和config.json是密切相关的，所以要根据配置修改查询命令的参数。
我给出的查询命令要加入下面的配置（源代码附在下方，以免影响阅读）。
注意是在你的配置基础上加入下面的配置，不是直接运行下面的配置。
还要注意下面的routing.settings.rules里的内容要放前面，
不然查询数据有可能被"geoip:private"之类的配置拐走。
很麻烦对吧？这时我就要安利下。。。算了还是不打广告了。

```
https://github.com/nobody3u/VGCTpl/blob/master/Template/Misc/stat.json
-----------------------------------------------------
{
  "inbound": {
    "tag": "statin"
  },
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  },
  "stats": {},
  "api": {
    "tag": "api",
    "services": [
      "StatsService"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "inboundTag": [
            "api"
          ],
          "outboundTag": "api",
          "type": "field"
        }
      ]
    }
  },
  "inboundDetour": [
    {
      "listen": "127.0.0.1",
      "port": 1090,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ]
}
```

**Comment by thanksshu** [comment]
@nobody3u 请问这些使用方法在哪里可以找到呢？v2ray.com并没有提供呀？还是我没有找到呢？

**Comment by nobody3u** [comment]
@thanksshu  
配置在v2ray.com有写，只是分散在各个部分的说明中，没综合在一起。
查询命令是看v2ctl那个可执行文件的帮助，然后也参考了下搜索出来的博客内容。
windows版的查询命令是我试了好多次才试出来4个引号。

**Comment by thanksshu** [comment]
@nobody3u 十分感谢！

**Comment by spencer404** [comment]
"stats": {} 空配置也不能省啊……没注意到文档里的“stats: 当此项存在时，开启统计信息。”，磨了些时间😭😭。

**Comment by idroot** [comment]
> @missyea
> 查询命令和config.json是密切相关的，所以要根据配置修改查询命令的参数。
> 我给出的查询命令要加入下面的配置（源代码附在下方，以免影响阅读）。
> 注意是在你的配置基础上加入下面的配置，不是直接运行下面的配置。
> 还要注意下面的routing.settings.rules里的内容要放前面，
> 不然查询数据有可能被"geoip:private"之类的配置拐走。
> 很麻烦对吧？这时我就要安利下。。。算了还是不打广告了。
> 
> ```
> https://github.com/nobody3u/VGCTpl/blob/master/Template/Misc/stat.json
> -----------------------------------------------------
> {
>   "inbound": {
>     "tag": "statin"
>   },
>   "policy": {
>     "levels": {
>       "0": {
>         "statsUserUplink": true,
>         "statsUserDownlink": true
>       }
>     },
>     "system": {
>       "statsInboundUplink": true,
>       "statsInboundDownlink": true
>     }
>   },
>   "stats": {},
>   "api": {
>     "tag": "api",
>     "services": [
>       "StatsService"
>     ]
>   },
>   "routing": {
>     "strategy": "rules",
>     "settings": {
>       "rules": [
>         {
>           "inboundTag": [
>             "api"
>           ],
>           "outboundTag": "api",
>           "type": "field"
>         }
>       ]
>     }
>   },
>   "inboundDetour": [
>     {
>       "listen": "127.0.0.1",
>       "port": 1090,
>       "protocol": "dokodemo-door",
>       "settings": {
>         "address": "127.0.0.1"
>       },
>       "tag": "api"
>     }
>   ]
> }
> ```

### 其他配置和你的一样，但是我的路由下面增加了屏蔽局域网段，按照你说的把 **api** 放在路由最前面
#### Linux server V2也可以正常工作 就是不能查看统计流量这些
```shell
    "routing":
    {
        "strategy": "rules",
        "settings":
        {
            "rules": [
            {
                "type":"field",
                "inboundTag": [
                    "api"
                ],
                "outboundTag": "api"
            },
            {
                "type": "field",
                "ip": [
                    "0.0.0.0/8",
                    "10.0.0.0/8",
                    "100.64.0.0/10",
                    "127.0.0.0/8",
                    "169.254.0.0/16",
```
直接执行你的命令和另一个在网上 [传送门](https://medium.com/@TachyonDevel/%E8%B0%83%E7%94%A8-v2ray-%E6%8F%90%E4%BE%9B%E7%9A%84-api-%E6%8E%A5%E5%8F%A3%E8%BF%9B%E8%A1%8C%E7%94%A8%E6%88%B7%E5%A2%9E%E5%88%A0%E6%93%8D%E4%BD%9C-adf9ff972973) 看到的命令都会出现如下错误，**client** 里面也配置了邮箱的
```shell
root@ubuntu:~# /usr/bin/v2ray/v2ctl api --server=127.0.0.1:1088  StatsService.GetStats 'name: "user>>>test@test.ml>>>traffic>>>downlink" reset: false'
v2ray.com/core/infra/control: failed to call service StatsService.GetStats > rpc error: code = Unknown desc = v2ray.com/core/app/stats/command: user>>>test@test.ml>>>traffic>>>downlink not found.
```
请问这个怎么解决？

**Comment by boypt** [comment]
陪着相关的 看这里吧：  https://gist.github.com/boypt/80d9ecaaa7f3c799c525e91f3c0b35d1

建议先测试QueryStats

**Comment by RavenKong** [comment]
> 
> 
> 配置相关的 看这里吧： https://gist.github.com/boypt/80d9ecaaa7f3c799c525e91f3c0b35d1
> 建议先测试QueryStats

多谢！解决了我两天以来的困扰。
