### ISSUE TITLE
对于4.18DNS服务器中静态域名列表的疑问

### ISSUE THREAD

**Issue by ccboxes** [v2ray/discussion#170]
在4.18+，可以在DNS的host配置中，将查询的域名替换。比如一个对aaa.bbb的DNS查询，可以通过：
` "hosts": {
"aaa.bbb": "aaa.ccc"
 }`
使得V2Ray返回对aaa.ccc查询的结果.

现在问题来了，如果我在DNS配置中指定aaa.bbb向8.8.8.8查询，aaa.ccc向1.1.1.1查询，最后返回的结果来自那个DNS服务器呢？

**Comment by kslr** [comment]
这取决你设定域名还是 IP匹配
