### ISSUE TITLE
对DNS机理的一些疑问

### ISSUE THREAD

**Issue by davidfromtheeast** [v2ray/discussion#174]
本小白对V2ray的DNS机理有一些疑问，想请教懂的人。

I 现在v2ray自带dns了，我观察只要是路由出口走vmess协议的，都是由远端服务器代解析dns的，是这样的吧。也就是说一般是不存在dns污染的问题了，路由策略选asis的话，就完全没问题吧。如果选其它两个，碰到要判断是否国内ip的时候，这个判断交给哪里解析呢，应该是本地吧。

II 远程解析dns的情况下，一般情况下解析结果返回吗？我知道dokodemo-door模式下，远端是要返回dns解析结果的，这个具体是什么流程呢，是dns请求先通过vmess传到远端，解析完再返回，然后再传递网络请求，这样往返两次吗？还是dns请求和网络请求一起走，只往返一次？或者是我理解有什么问题，完全跑偏了？  (￣▽￣") 

III 我感觉可能我有一点跑偏，因为我对官网里的dns配置不是很理解。我的理解是dns配置是用在客户端的对吧。默认情况下除了host以外翻墙dns都是由远端服务器的本地dns设置解析的，如果在dns配置里具体设置了，就由远端再转发到具体设置的那个server上，是这样吗?
还有clientIP是做什么用的，是用做edns的吗？
最后dns配置说明中的“tag可在路由使用inboundTag进行匹配”，也是用在客户端的吧，具体有什么用呢？

**Comment by kslr** [comment]
1. 不是，取决于配置，不是本地;
2. 先DNS后，不然哪有IP呢
3. 是，比如白名单某些交给国内DNS

**Comment by davidfromtheeast** [comment]
看了小薇姐写的东西，这个dns好像是服务端的，前面我的问题都不适用，我大概都理解了。
