### ISSUE TITLE
Difference between v2ray and v2ray_armv7

### ISSUE THREAD

**Issue by Eintler** [v2ray/discussion#175]
I try to upgrade V2Ray manually for my asus router,The cpu is armv7.
When I extract the zip (linux arm 32), I find there are 4 files v2ray ,v2ray_armv7,v2ctl and v2ctl_armv7.
I wonder which 2 files I should use? 

BTW,what is difference between one and one with suffix?

Thanks

**Comment by kdrx** [comment]
I think that the files with a 'armv7' suffix should be built for newly armv7 architecture, and the others should be built for armv5 or armv7l architecture, which are used for older devices(e.g., asus rt-ac56u, asus rt-ac68u).

**Comment by Eintler** [comment]
@kdrx Thanks :)
