### ISSUE TITLE
Please support v2ray server over http proxy 

### ISSUE THREAD

**Issue by netroby** [v2ray/discussion#176]
Would you please support http proxy for v2ray server outgoing?

I want to using v2ray  for mobile development pack capture .

```
Mobile phone -> v2ray mobile app -> intranet v2ray server -> mitmproxy -> target api host
```

**Comment by aketr** [comment]
https://github.com/v2ray/v2ray-core/issues/450

**Comment by kslr** [comment]
https://github.com/v2ray/v2ray-core/issues/663
