### ISSUE TITLE
求救，输入v2ray显示命令未找到

### ISSUE THREAD

**Issue by no-name2017** [v2ray/discussion#177]
v2ray已经平稳用了许久，突然想起客户端没有更新，想看看服务端什么版本，结果在vps上输入v2ray -version 提示命令未找到，单独输入v2ray一样，我的v2ray目录所在：v2ray: /usr/bin/v2ray   /etc/v2ray

求救大佬们，用的是debian9

**Comment by kslr** [comment]
检查一下环境变量或者重新安装
