### ISSUE TITLE
服务端配置了多ip，但配置v2ray后，只能用服务器默认ip

### ISSUE THREAD

**Issue by AgonyLei** [v2ray/discussion#179]
服务端配置了多ip，但配置v2ray后，只能用服务器默认ip正常使用v2ray，我想用一个服务器上多个ip使用v2ray，求解，谢谢

**Comment by kslr** [comment]
你有尝试过负载均衡出口吗？通过sendThrough参数

**Comment by supersndqd** [comment]
你不贴配置，怎么回答呢

**Comment by kslr** [comment]
不活跃而关闭
