### ISSUE TITLE
有关Linux下环境变量设置的问题

### ISSUE THREAD

**Issue by FrostbiteXSW** [v2ray/discussion#182]
官方文档中的描述如下：
        当-config没有指定时，V2Ray 将先后尝试从以下路径加载config.json:
            工作目录（Working Directory）
            环境变量中v2ray.location.asset所指定的路径

v2ray.location.asset名称中带点不能用作Linux环境变量名，请问应该如何设置？

**Comment by kslr** [comment]
使用绝对地址
