### ISSUE TITLE
V2Ray支持TCP Fast Open吗？

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [v2ray/discussion#183]
如题

**Comment by KyonLi** [comment]
https://www.v2ray.com/chapter_02/05_transport.html#sockoptobject

**Comment by ShoukakuChuuCC** [comment]
感谢帮助
 "sockopt": {
          "tcpFastOpen": true
  },
服务端这样设置就可以打开TFO了吧？
客户端我用的是V2RayN 请问是默认开启的吗 是否需要额外配置？

**Comment by ShoukakuChuuCC** [comment]
Win10我已经开启TFO了
服务端的/etc/sysctl.conf也添加了net.ipv4.tcp_fastopen = 3
但是使用grep '^TcpExt:' /proc/net/netstat | cut -d ' ' -f 87-92 | column -t
TFO就没看出生效

**Comment by sunsan05** [comment]
> Win10我已经开启TFO了
> 服务端的/etc/sysctl.conf也添加了net.ipv4.tcp_fastopen = 3
> 但是使用grep '^TcpExt:' /proc/net/netstat | cut -d ' ' -f 87-92 | column -t
> TFO就没看出生效

你的linux内核版本多少？

**Comment by ShoukakuChuuCC** [comment]
CentOS 7.6.1810 64bit KVM

**Comment by ShoukakuChuuCC** [comment]
OS                   : CentOS 7.6.1810 (64 Bit) KVM
 Kernel               : 4.14.91-bbrplus

**Comment by ShoukakuChuuCC** [comment]
SS的TFO测试是有效的，V2Ray我搞不明白，小白一个，水平有限

**Comment by jellycsc** [comment]
同样的问题，TPO 不工作，试了下 Trojan 可以

**Comment by wanzhiyu** [comment]
TFO确实不工作，原因未知

**Comment by VivinLancelot** [comment]
感觉可能是这里：
https://github.com/v2ray/v2ray-core/blob/master/transport/internet/sockopt_linux.go#L86
最后一个参数取值太小了。

https://lwn.net/Articles/508865/ 里面指出

> The option value, qlen, specifies this server's limit on the size of the queue of TFO requests that have not yet completed the three-way handshake

另外是 https://dnsprivacy.org/wiki/display/DP/TCP+Fast+Open

> Server side code changes
> The server must simply set the TCP_FASTOPEN flag using setsockopt() on the listening socket. On linux/FreeBSD the qlen value passed in to the function limits the number of outstanding TFO requests as a simple defense against IP spoofing attacks (see RFC7413).
> Note on OS X the socket MUST be listening already for this flag to be set, and the qlen MUST be 1 (the actual value is set via the net.inet.tcp.fastopen_backlog kernel parameter.
> On linux this call can be done after bind() is called.

ss-libev取5，https://github.com/shadowsocks/shadowsocks-libev/blob/6f7a6fd7e312beb8d6e17a3f83797d15ab9081c9/src/server.c#L293-L297

我没有看tcp的实现，不确定取1会不会导致第一个tfo链接建立不起来
