### ISSUE TITLE
统计信息里似乎没有包含UDP流量

### ISSUE THREAD

**Issue by joysteed** [v2ray/discussion#184]
我有一个inbound是专给udp流量的，可是stat api出来的结果，无论是uplink或者downlink都始终是0。我不是很懂go语言，只能半读半猜着看了看代码，似乎app/proxyman/inbound/worker.go中tcpWorker的callback里有写统计信息，如下：
func (w *tcpWorker) callback(conn internet.Connection) {
...
	conn = &internet.StatCouterConnection{
			Connection: conn,
			Uplink:     w.uplinkCounter,
			Downlink:   w.downlinkCounter,
		}
...
}
而对应的udpWorker的callback中则好像没有，不知道是不是这个问题？

**Comment by kslr** [comment]
请重试
