### ISSUE TITLE
[功能请求]无视loglevel设置，在core准备好时打印一行日志

### ISSUE THREAD

**Issue by tjLEIIQM3** [v2ray/discussion#185]
#### 当前行为（v4.18.0）：
core准备好接收链接请求时，如果loglevel设置为warning会打印一行
`[Warning] v2ray.com/core: V2Ray 4.18.0 started`
但是如果loglevel设置为none则不打印任何信息

#### 期望行为：
忽略loglevel设置，core准备好后都打印一行信息，最好是和版本无关的恒定不变的信息。

#### 原因：
因系统忙等多种因素影响，在core启动到准备好接受链接之间通常会有几秒延迟。
对于普通用户来说，这几秒延迟并没什么影响，但是在测试服务器速度时就影响很大。
通过读取warning ... started可以知道core什么时候准备好，得到稍微准确一点的测速结果。
但是如果配置里面的loglevel设为none时则没有这行信息，所以无法得知core是否准备好。
当然这可以在测速前强行改写loglevel来绕过，但还是觉得打印一行信息会更好些。
这也有利于更准确的判断core运行状态。

**Comment by kslr** [comment]
为什么要通过读取日志判断工作转化？

**Comment by tjLEIIQM3** [comment]
因为这是我唯一想到的，通过程序方式获取core信息的途径。
你有其他的建议吗？

注：
不自行改core是为了同一调用程序可使用多个官方core版本。（其实我也不懂golang，不会改）
不改config.json是因为我只能控制我自己的config，别人用这个程序的时候我控制不了他们的配置。
同上，grpc也要改config，也不在我控制范围。不过从文档来看当前的grpc也没这功能。

**Comment by kslr** [comment]
你有考虑过查找进程吗

**Comment by tjLEIIQM3** [comment]
查找进程具体是怎么得到这个信息？
我需要知道的是core是否准备好接收连接请求。

**Comment by kslr** [comment]
就是程序已经启动，自然会有进程，比如Linux下 ps -ef | v2ray
或者读取pid文件

**Comment by tjLEIIQM3** [comment]
这个在一开始的原因部分已经说了。这样测出来的时间不准确。
程序启动后还要点准备时间才可以开始接受接入请求，特别是并发开多个core的时候需要的时间会增多。
从打印V2Ray 4.18.0 (Po) 20190228 A unified platform for anti-censorship，也就是程序启动。
到[Warning] v2ray.com/core: V2Ray 4.18.0 started（真正可以接受请求）
有时会有几秒延迟。

**Comment by kslr** [comment]
你能不能把要做什么说一下，也许有更好的办法
如果None拥有输出，我觉得是违反语义。

**Comment by tjLEIIQM3** [comment]
目的：
让调用v2ray-core的程序知道core已经准备好接收连接请求。

作用：
1.可以更准确的记录测速开始时间，得到较为准确的测速结果，而无需修改日志级别配置。
2.可以知道core状态是刚启动还是已经准备好接收连接，从而更准确的显示core状态信息。
