### ISSUE TITLE
QUIC configurations, their effects and consequences (questions from a non-programmer user)

### ISSUE THREAD

**Issue by arolano** [v2ray/discussion#187]
Hello!

First and foremost I'm not a programmer so I can't "go and read the source" but I need some software that would take SOCKS5 TCP+UDP traffic and convert it into heavily obfuscated UDP 

thus v2ray + QUIC attracted my attention.

This issue is somewhat related to https://github.com/v2ray/discussion/issues/113 but IMHO deserves a separate discussion)

So, my questions are:

1) 
Do I understand correctly that v2Ray QUIC *always* uses TLS even if the [security] option is activated?

2) 
If so, how do I go about using a custom TLS certificate to make it use the chacha-based ciphersuite for TLS part (so it's chacha over chacha, not chacha over AES, the platform I plan to work on is very performance constrained)?

As a suggestion, disabling TLS part if [security] is not none would be a reasonable feature, maybe :)

3)
SNI being unencrypted is a big problem for me.
Is the SNI part encrypted if the [security] parameter is active (set to say "chacha20-poly1305") ?

4)
I would like to know more about how HeaderObject obfuscation works, and how it interacts with "security" parameter, since the obfuscation does not seem to require key.

4a
What would happen if I configure QUIC with [security] set to "none" but HeaderObject set to "dtls"?
Would, say, SNI still be "sniffable"?

4b
What would happen if I configure QUIC with [security] set to "none" but HeaderObject set to "srtp"?
Would, say, SNI still be "sniffable"?

4c
What would happen if I configure QUIC with activated [security] (set to "chacha20-poly1305") and  HeaderObject set to "srtp"?

**Comment by RachelHendy** [comment]
While I do dare considering myself a tiny bit of a programmer, figuring out v2ray's internals just from sources is above my ability, so I too am very interested in answers to @arolano 's questions (and will probably then ask my own)

**Comment by arolano** [comment]
I hope I'm not being too annoying by humbly tagging @VictoriaRaymond here  

Please pardon me for disturbance
