### ISSUE TITLE
请教个问题，如何确认路由设置正确，如何追踪路由路径

### ISSUE THREAD

**Issue by George-taoqi** [v2ray/discussion#188]
请教一个问题，将router设置国内网站直连，国外走v2ray代理，客户端是v2ray字符界面，用windows10，chrome设置socks5连接127.0.0.1. 
请教如何查找chrome的数据包是否安装路由规则转发，用什么工具可以最终？router配置如下：
"routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": ["geosite:cn"] // 中国大陆主流网站的域名
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:cn", // 中国大陆的 IP
          "geoip:private" // 私有地址 IP，如路由器等
        ]
      }
    ]
  }

**Comment by tjLEIIQM3** [comment]
方法一，将loglevel设为info
方法二，开2个v2ray一个作为client一个作为server看什么时候client有数据传给server.

**Comment by kslr** [comment]
也通过IP查询网站

**Comment by George-taoqi** [comment]
非常感谢

**Comment by George-taoqi** [comment]
刚才将loglevel改成info，发现如下信息，我看不懂，能否指教一下。貌似不能直连。我分别连接project v官网和163主页。
[Info] [2529335665] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
[Info] [2529335665] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
配置文件如下：
{
  "log": {
        "access":"C:\\v2ray\\logfile\\access.log",
		"error":"C:\\v2ray\\logfile\\error.log",
        "loglevel": "info"
    },
  "inbounds": [
  	{
        "listen": "0.0.0.0",
		"port": 1080,
        "protocol": "socks",
        "settings": {
            "auth": "noauth",
            "udp": true,
            "userLevel": 0
        },
	   "sniffing": {
                             "enabled": false,
                              "destOverride": ["http", "tls"]
                            }
    }
	],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "0bd.org",
            "port": 443,
            "users": [
              {
                "id": "ID",
                "alterId": 64,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "tcp",
        "security": "",
        "tlsSettings": null,
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": null,
        "httpSettings": null
      },
      "mux": {
        "enabled": true
      }
    } ,
	{
      "protocol": "freedom",
      "settings": {},
	  "tag": "direct" 
    },
    {
      "protocol": "blackhole",
      "settings": {}
    }
  ],
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": ["geosite:cn"] // 中国大陆主流网站的域名
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:cn", // 中国大陆的 IP
          "geoip:private" // 私有地址 IP，如路由器等
        ]
      }
    ]
  }
  }
