### ISSUE TITLE
http 代理的流量检测现在能提取出相关特征么？ How to identify a HTTP connection is for common website or http proxy?

### ISSUE THREAD

**Issue by xiangjoaodej** [v2ray/discussion#190]
服务器又被和谐了，本来想写一个精修仿 http 协议的 vmess 配置文件，突然想起来仿 http 的话是不是就和 http 代理有相似的特征了，现在对于 http 代理流量识别特征点在哪里啊，是不是通过发送同一 ip 有不同的 host 这一点呢？如果我把协议的 request 和 response 伪装的 host 都写成固定的一个，能不能避免被识别呢？

I’m in China and we have the great firewall to avoid us to visit some websites. I use vmess to build a proxy to over the wall. But my server is always banned by the firewall. I wanna to write a refine vmess config to imitate common http protocol. But what’s the traffic characteristic difference between common http flow and http proxy? Will my server be recognized as a http proxy server? Is it identified by the same IP receive headers which have different host website? If I set the host of request and response to the same domain, can I avoid to be recognized?

**Comment by Xyncgas** [comment]
怕什么，政府花几千万来不让你玩lol日服么
