### ISSUE TITLE
v2ray下支持多用户ss吗

### ISSUE THREAD

**Issue by BhnxoRclg** [v2ray/discussion#191]
用了好长时间，有朋友找我借着用。然后我就想给他单独开一个ss，也方便管理。但是网上的教程都不教怎么添加多用户ss,希望大佬们能告诉我。

**Comment by njusilvaz** [comment]
网上一搜大把。。。
https://teddysun.com/532.html

**Comment by kslr** [comment]
inbound再添加一个

**Comment by BhnxoRclg** [comment]
> inbound再添加一个

inbound再加一个用户?然后ss怎么设置呢？

**Comment by kslr** [comment]
```
"inboundDetour": [
        {
            "protocol": "shadowsocks",
            ...
        },
        {
            "protocol": "shadowsocks",
            ...
        },
    ],
```

**Comment by BhnxoRclg** [comment]
> ```
> "inboundDetour": [
>         {
>             "protocol": "shadowsocks",
>             ...
>         },
>         {
>             "protocol": "shadowsocks",
>             ...
>         },
>     ],
> ```

ok了，原来是我设置第二个inbound下alterID不是64
