### ISSUE TITLE
openwrt配置问题,求大神指点。

### ISSUE THREAD

**Issue by sebastianchuk** [v2ray/discussion#193]
我在pc上运行正常，但在openwrt上配置总是失败，请求指点。
iptables配置：
iptables -t nat -N V2RAY
iptables -t nat -A V2RAY -d x.x.x.x -j RETURN
iptables -t nat -A V2RAY -d 192.168.0.0/16 -j RETURN
iptables -t nat -A V2RAY -p tcp -j RETURN -m mark --mark 0xff
iptables -t nat -A V2RAY -p tcp -j REDIRECT --to-ports 12345
iptables -t nat -A PREROUTING -p tcp -j V2RAY
iptables -t nat -A OUTPUT -p tcp -j V2RAY
ip rule add fwmark 1 table 100
ip route add local 0.0.0.0/0 dev lo table 100
iptables -t mangle -N V2RAY_MASK
iptables -t mangle -A V2RAY_MASK -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A V2RAY_MASK -p udp -j TPROXY --on-port 12345 --tproxy-mark 1
iptables -t mangle -A PREROUTING -p udp -j V2RAY_MASK

openwrt客户端配置：
{
    "log": {
        "loglevel": "warning"
    }, 
    "inbounds": [
        { 
            "port": 12345, 
            "protocol": "dokodemo-door", 
            "settings": {
				"network": "tcp,udp",
                "followRedirect": true
            },
			"sniffing": {
				"enabled": true,
				"destOverride": ["http", "tls"]
			}
        }
    ], 
    "outbounds": [
        {
            "protocol": "vmess", 
            "settings": {
				"vnext": [
					{
						"address": "x.x.x.x", 
						"port": 443, 
						"users": [
							{
								"id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 
								"alterId": 64
							}
						]
					}
				]
            },         
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			}
        }, 
        {
            "protocol": "freedom", 
            "settings": { }, 
            "tag": "direct"
        }
    ], 
    "routing": {
        "domainStrategy": "IPOnDemand", 
        "rules": [
            {
                "type": "field", 
                "outboundTag": "direct", 
                "domain": [
                    "geosite:cn"
                ]
            }, 
            {
                "type": "field", 
                "outboundTag": "direct", 
                "ip": [
                    "geoip:cn", 
                    "geoip:private"
                ]
            }
        ]
    }
}

**Comment by sylarjiang** [comment]
同求,我也是一样的问题,测试好多次了,是不是需要iptables-mod-tproxy,kmod-ipt-tproxy以外的什么组件啊?老哥弄好了来回一下啊

**Comment by kslr** [comment]
先不要设置UDP尝试一下

**Comment by YLaido** [comment]
> 1、看你服务器用了443端口，那么你使用的是TLS传输协议吗？如果用的是TLS协议，客户端会参照本地信任证书验证服务器根证书，而openwrt上是没有安装信任证书列表的，导致证书验证失败。表现为相同的配置文件在PC上可用，在opwnwrt上就不行了。处理方法可以在客户端配置不进行证书认证，或者在opwnwrt上安装相应根证书。
> 不进行证书认证：
> {
> "serverName": "你的服务器域名", //address使用的是IP地址时这里不能留空
> "allowInsecure": true //允许使用不安全连接，既不对证书有效性进行验证
> }
> 
> openwrt 安装证书
> 安装ca-bundle和ca-certificates两个软件包
> 
> 2、你的防火墙规则配置是有隐患的。这样的防火墙配置来自于shadowsocks，用于v2ray会存在问题。原因在于v2ray自身除了向服务器发送数据外还会直接发送（freedom 出口的数据是直接发送的，路由配置情况决定是否有数据走freedom出口），而防火墙只是跳过了向服务器发送的数据，从freedom发出的数据却被防火墙转回v2ray, 造成数据回环。
> 
> 3、openwrt 处理DNS数据需安装iptables-mod-tproxy这个软件包，不知你安了没。

你好，想问下我openwrt装了上述两个软件包之后也不行？这两个包都已经显示是最新的20190110版本，但还是不能取消勾选allowInsecure，证明证书还是有问题，请问是还有其他原因吗？
