### ISSUE TITLE
首次访问外网很慢

### ISSUE THREAD

**Issue by shangming-wang** [v2ray/discussion#195]
现在连接学校的校园网，发现首次访问google，youtube，reddit等国外网站时非常慢，浏览器会出现took too long to respond，然后刷新两三遍才能进去。猜测应该是建立连接耗时很长，如下图，访问youtube刷新三遍才能成功。
![image](https://user-images.githubusercontent.com/33543682/55468924-021a9f80-5637-11e9-92e2-c11b470d12a9.png)

如果过几分钟内不访问，然后又继续访问的话，就又要重新建立连接，然后再刷新刷新。。。

之前连接别的网络时虽然首次访问也慢，但是不明显。连接校园网后这样子，对于时不时用google搜索的人来说，太难受了。

所以想问下各位大佬，**有没有什么方法可以改善这种情况？或者有什么办法可以一直维持长连接？**

谢谢：)

**Comment by kslr** [comment]
和服务器直接沟通存在这种情况吗

**Comment by shangming-wang** [comment]
@kslr 现在解决了，是配置的问题。之前不懂v2ray的配置，本地解析dns，从而导致建立连接慢
