### ISSUE TITLE
有关官方网站里面的推广链接

### ISSUE THREAD

**Issue by YangtseSu** [v2ray/discussion#196]
https://www.v2ray.com/awesome/ads.html

v2ray.com的文档里面有一些广告，或者推广。这些链接里面的服务不知道购买了，开发者会不会有收益。用户购买这些推广的服务，是对于开发团队的信任。有些无良的骗子滥用了这份信任。
里面的
vProxy
由 V2Ray 驱动的网络加速器。专属优惠码：v2ray.cool
已经跑路几个月了，链接仍然在。

真诚地希望开发团队在提供这些推广，广告的时候，能更审慎一些。

**Comment by kslr** [comment]
> 以下服务均由第三方提供，和 Project V 没有利益关系，但它们可能会帮助你更好地使用 Project V。

这些VPN是由第三方提交的，理论上正常工作就可以被接受。
我已经提交了更新，但是好像需要一点时间发布

**Comment by niconode** [comment]
@kslr 您好，我司域名看到PR里请求更新为.co 结尾.. 但是被直接去列表了
但是我司还没有跑路呀，是不是手误了（
因为.net在大陆被DNS污染了，所以更换了域名TLD，原域名也301过去了）
已经重新提交PR望批准～感谢
