### ISSUE TITLE
关于v2ray负载均衡的路由规则

### ISSUE THREAD

**Issue by DaedalusT** [v2ray/discussion#197]
<s>s因为有多台代理服务器同时进行工作，在balancer中进行分类，希望访问dmm此类网站时，通过jp组的节点进行访问，在routing中添加了如下规则，可惜没有作用，请问有无成功的负载均衡案例供参考。
       {
          "type": "field",
          "balancerTag": "jp",
          "domain": ["dmm.com","dmm.co.jp"]
        },
</s> <br/>
已经生效了

**Comment by kslr** [comment]
你要看看是域名还是IP匹配，就是文档写的那些。
https://v2ray.com/chapter_02/03_routing.html
https://v2ray.com/chapter_02/04_dns.html

**Comment by DaedalusT** [comment]
> 你要看看是域名还是IP匹配，就是文档写的那些。
> https://v2ray.com/chapter_02/03_routing.html
> https://v2ray.com/chapter_02/04_dns.html

你好，谢谢解答，现在唯一不确定的是，是否v2rayN之类的软件内置的routing rule会把我自定义文件的规则覆盖，看了下我写的规则貌似没有问题，domainStrategy用的是AsIs，domain里面添加了dmm.com和dmm.co.jp，source写了dmm的ip（从日本服务器ping得到的ip一致，貌似没有用cdn），访问dmm的时候并没有通过jp节点，而是通过随机节点进行访问。
