### ISSUE TITLE
如何在树莓派上的OpenWrt里安装v2ray

### ISSUE THREAD

**Issue by bobwang3** [v2ray/discussion#203]
我在树莓派3上安装了一个OpenWrt系统，不知道应该如何安装上v2ray的功能。
我运行
bash <(curl -L -s https://install.direct/go.sh) 
会提示
-ash: syntax error: unexpected "("
用命令直接运行下载下来的sh文件：
./go.sh
会提示
-ash: ./go.sh: not found
运行uname -m显示arm64，我不大会弄这个。求助。

**Comment by kslr** [comment]
先搜索：OpenWrt V2ray 按照一些指南尝试

**Comment by bobwang3** [comment]
> 先搜索：OpenWrt V2ray 按照一些指南尝试

我知道搜索这个能找到一大堆资料，但平台和我不一样，大多都是选择在软路由上运行。我自己的v2ray在x86_64的平台上运行的很好。

**Comment by kslr** [comment]
你把v2ray arm拷贝到路由器，其他都是一样的

**Comment by DaedalusT** [comment]
可以去koolshare论坛看看，他们自制的固件

**Comment by johnrosen1** [comment]
https://www.johnrosen1.com/pi4/ 仅供参考

**Comment by johnrosen1** [comment]
另外,树莓派不建议openwrt,驱动问题可以搞死人
