### ISSUE TITLE
关于v2ray的配置文件书写问题？

### ISSUE THREAD

**Issue by zegzag** [v2ray/discussion#204]
萌新小白跪求。我在vultr上购买了一个服务器并且安装了v2ray. 然后我在本地也安装了v2ray
均是一键命令行安装 `bash <(curl -s -L https://git.io/go.sh).
v2ray官网现在登不上去，想请问一下v2ray客户端配置.json文件该怎么书写才能登上服务器，连上自由之网T.T
跪求大佬们解答，不胜感激！！！

**Comment by kslr** [comment]
你可以使用 https://htfy96.github.io/v2ray-config-gen/ 来生成服务器和客户端配置文件。
如果你觉得麻烦，还可以在github搜索下一键安装。

**Comment by zegzag** [comment]
万分感谢～。然后又遇到了一个问题。。。。。我root权限下用文本编辑器手动方式更改了/etc/v2ray/config.json文件后（把outbounds的ip, 端口号 还有UUID改成和服务器端安装的一样的格式）。为啥重启v2ray后，v2ray的配置信息还是不变啊T。T。。。。。。
没法通过手动更改config.json信息来更新v2ray的配置

**Comment by zegzag** [comment]
我重启了一下v2ray，发现配置文件又改回来了orz。。。

**Comment by kslr** [comment]
请自己先检查一下操作
