### ISSUE TITLE
/etc/v2ray 下的两个配置文件的疑问 config.json 和233blog_v2ray_config.json

### ISSUE THREAD

**Issue by zegzag** [v2ray/discussion#206]
如果要修改配置文件v2ray生效的话，是更改哪一个配置文件呢？
这两个json文件不一样。config.json的inbounds好像就是233blog_v2ray_config.json的outbounds但是又不完全一样。
还有服务器端也有两个一模一样的文件。好晕T。T
该更改两个文件的内容是指可以连接呢？
config.json下的inbounds里面没有对本地ip的监听内容
233blog_v2ray_config.json里面有相应的内容。

跪求大佬～～～～～～～～

**Comment by kslr** [comment]
你这样询问没有效率可言，看不懂说什么也不可能猜出来你是怎么做的。
所以，试试把这个看完 https://toutyrater.github.io/

**Comment by DaedalusT** [comment]
修改config.json，你用的是v2rayN么，所有的配置在guiNConfig中，他会读取outpound，然后自动生成config.json（内含客户端自带的routing rule）。
