### ISSUE TITLE
使用 Go 1.12及以上版本编译时的问题

### ISSUE THREAD

**Issue by ccdsapgs** [v2ray/discussion#207]
使用Go 1.12及以上版本编译时，在macOS和Linux下总是出错，提示"build cache is required, but could not be located: GOCACHE is not an absolute path". 换用Go 1.11.9版本后就可以了。应该是由于Go 1.12版本开始加入了对build cache 的强制要求导致的。https://github.com/v2ray/v2ray-core/issues/1437#issuecomment-453234037 提到使用Go 1.14beta 版本编译也会出错，看错误信息应该也是cache导致的。

**Comment by kslr** [comment]
你有什么修复建议吗

**Comment by ccdsapgs** [comment]
> 这个问题的确存在，你有什么修复建议吗

并没有…… google一番也没找到什么解决方案

**Comment by kslr** [comment]
```
>> infra/bazel/build.bzl

"GOCACHE=/tmp/.gocache"
```

**Comment by ccdsapgs** [comment]
> >> infra/bazel/build.bzl
> 
> "GOCACHE=/tmp/.gocache"

之前尝试过改成绝对路径，然而还是出错，我再尝试一下
