### ISSUE TITLE
Linux桌面用户如何使用订阅功能

### ISSUE THREAD

**Issue by Howard-00** [v2ray/discussion#208]
如题，一直没找到类似electron-ssr的Linux客户端

**Comment by kslr** [comment]
core没有订阅功能，可能各个机场会自己修改有吧。

**Comment by DaedalusT** [comment]
v2ray没有标准的订阅格式，现阶段使用最广的订阅格式应该是参照Windows端的v2rayN，获取到URL以后，再使用base64转码，可以发布到GitHub上或者是你自己的网页上

**Comment by Dr-Incognito** [comment]
Consider the new V2Ray GUI client [V2Ray Desktop](https://github.com/Dr-Incognito/V2Ray-Desktop), which are able to subscribe servers from URLs.
