### ISSUE TITLE
如何配置v2ray只处理特定域名？

### ISSUE THREAD

**Issue by Clive1990** [v2ray/discussion#209]
小白，刚刚接触，想请教一下，不需要所有屏蔽的域名都处理，希望v2ray服务器只处理特定的域名，应该如何编写配置文件？
比如，希望所有google域名，外加xx.com，yy.com，这些域名服务器可以处理，其他的全部不予处理，应该如何配置服务端和客户端？

**Comment by DaedalusT** [comment]
https://www.v2ray.com/chapter_02/03_routing.html

"domain": [
    "geosite:google",
    "domain:xx.com",
    "domain:yy.com"
  ],

**Comment by nobita215** [comment]
> https://www.v2ray.com/chapter_02/03_routing.html
> 
> "domain": [ "geosite:google", "domain:xx.com", "domain:yy.com" ],

请问这是放在服务器端的配置吗？客户端无法篡改此配置吧？
