### ISSUE TITLE
请问前置代理有负载均衡吗

### ISSUE THREAD

**Issue by denniscan** [v2ray/discussion#210]
应用场景如下：
　　一个私有v2ray host作为最终出口，用免费机场作前置代理，机场有多个且配置各不相同（shadowsocks、v2ray），希望通过前置机场时实现均衡负载。
　　请问相关配置，谢谢。

**Comment by DaedalusT** [comment]
https://www.v2ray.com/
https://toutyrater.github.io/
看完这两个你就会了，当初我也是参考这个
