### ISSUE TITLE
YouTube QUIC + Shadowsocks UDP 速度比 V2Ray 的 QUIC 快很多

### ISSUE THREAD

**Issue by zmz125000** [v2ray/discussion#211]
Shadowsocks 透明代理 UDP 流量 + YouTube 开启 QUIC 速度 20Mbps
V2Ray 的 QUIC 模式速度 2Mbps
抓包显示同样走 UDP，为什么会有速度差异？

**Comment by DaedalusT** [comment]
v2ray的QUIC的确很慢，不知道是不是被ISP的QoS限制了

**Comment by kxmp** [comment]
quic没问题 我自己还测了.
就是怕丢包 其他没什么.
可能u2b的他们quic版本不一样 重传机制不一样 所以就速度快.

**Comment by moralrebuild** [comment]
@zmz125000  问题的本质是为什么V2ray的性能如此糟糕，答案应该是Developer的水平问题。V2ray tls+websocket的实现就很差。有水平的人对这个领域不感兴趣，很遗憾。

**Comment by jellycsc** [comment]
@moralrebuild 我用v2+nginx+tls+ws的组合跑出了300Mbps的速度，go的性能还是可以的，应该是你配置问题

**Comment by johnrosen1** [comment]
> Shadowsocks 透明代理 UDP 流量 + YouTube 开启 QUIC 速度 20Mbps
> V2Ray 的 QUIC 模式速度 2Mbps
> 抓包显示同样走 UDP，为什么会有速度差异？

世界加钱可及 另外v2ray的quic不推荐使用

**Comment by k79e** [comment]
对不起 google全站quic是开bbr的

**Comment by johnrosen1** [comment]
> 对不起 google全站quic是开bbr的

你这话前后矛盾，quic走udp,bbr只对tcp有效

**Comment by Leo-Mu** [comment]
> @zmz125000 问题的本质是为什么V2ray的性能如此糟糕，答案应该是Developer的水平问题。V2ray tls+websocket的实现就很差。有水平的人对这个领域不感兴趣，很遗憾。

高水准的人估计都是肉翻，不需要。。。

**Comment by Leo-Mu** [comment]
> > 对不起 google全站quic是开bbr的
> 
> 你这话前后矛盾，quic走udp,bbr只对tcp有效

[Google 的 bbr repository](https://github.com/google/bbr) 里面就有官方的 quic 版本 bbr 实现。
[这篇文章](https://blog.csdn.net/dog250/article/details/80629551)也说明了 quic 版本的 bbr 实现与 tcp bbr 之间的关系及其先导性。
