### ISSUE TITLE
v2ray是如何处理TCP三次握手的？

### ISSUE THREAD

**Issue by wangyufeng0615** [v2ray/discussion#212]
感谢阅读。我在使用v2ray的过程中遇到一个问题。场景是v2ray透明代理路由器。

打开代理的情况下，在客户端抓包，发现但凡有程序发出 SYN 包，**v2ray 的“客户端”都会马上回一个 SYN,ACK**，客户端再回 ACK。客户端会认为发生了三次握手。

但考虑到下面这种情况：**telnet 一个存活的服务器上并不存在的端口**。

不使用代理情况下的正常情况：发出SYN，收到RST，telnet 判定该端口上没东西。

使用v2ray时的情况：发出SYN，收到SYN,ACK，发出ACK。此时，客户端会认为进行了一次正常的三次握手，所以 telnet 会认为这个端口是存活的，但实际上端口上什么程序都没有。虽然马上客户端就会收到一次四次挥手，但是会存在这种“虚假三次握手”的情况，会对程序造成误判。

我的疑惑是，这种“假三次握手”，是客户端程序和v2ray客户端进行了三次握手吗？还是说，这是某种特殊的设计，即无条件让程序发出的SYN包成功三次握手？有没有可能让被代理的程序和最终目标进行真正的三次握手？

**Comment by eycorsican** [comment]
> 是客户端程序和v2ray客户端进行了三次握手吗？

是（准确点来说是操作系统进行的三次握手）


> 这是某种特殊的设计，即无条件让程序发出的SYN包成功三次握手？

透明代理原理上是用 iptables 对数据包进行重定向到 dokodemo-door 的监听端口上（包括[SYN],[ACK] 这些数据包），dokodemo-door 只要有监听着，握手就会成功，这应该算是一个“限制”


> 有没有可能让被代理的程序和最终目标进行真正的三次握手？

不太可行。因为实际上是操作系统进行的三次握手，v2ray 程序没办法控制，三次握手的数据包 [SYN], [SYN, ACK], [ACK] 都不是 TCP/UDP 数据（是 TCP 的协议包，不带数据），所以 v2ray 不能代理

**Comment by 8x8-64** [comment]
因为代理是在应用层的，不是传输层协议，透明是指在更高层级。v2ray连接不到远程服务器就断开本地连接不就可以了吗？就像是连接好了遇到网络中断又断开了。

**Comment by threatexpert** [comment]
透明代理环境下一直存在连接任何tcp目的地址都能立马完成连接的问题。telnet或nc工具在这些环境中将无法获得目的地址可达性的真实感知。
经过摸索，先通过截获syn包可以解决tcp端口可达性的真实感知问题，
这是一种synhack的方法，思路如下：
1、在tcp被重定向(-t nat PREROUTING  -j REDIRECT)前截获SYN包
      基于iptables -t mangle PREROUTING --syn -m ttl ! --ttl-eq 3对syn包实现拦截，这里规则需要加入一个特征，例如ttl值不是3的SYN包。
      基于NFLOG或tcpdump抓包捕获被DROP掉的SYN包，从中解析获得目的地
2、使用代理去连接目的地址，代理协议必须支持回复远程地址是否可达才有意义，例如HTTP、socks5这种就支持，无状态协议的例如shadowsocks这种就不支持。
3、代理协议如果告知远程地址连接成功，则将SYN包的ttl设置为3后重放，触发系统第二次握手，否则可以基于SYN包构建RST包回复客户端

demo项目https://github.com/threatexpert/tproxy
