### ISSUE TITLE
访问日志 能设置为 none 吗

### ISSUE THREAD

**Issue by maxchendt** [v2ray/discussion#217]
自己用，想取消 server 端的 访问日志， 减少资源占用 。
发现 `loglevel` 设置的是 错误日志，非 访问日志

```
{
  "log": {
	"loglevel": "error",
	"access": "/dev/null",
	"error": "/var/log/v2ray/error.log"
  },

```

当前用 `/dev/null` 只是不保存访问日志，能否设定 完全取消 访问日志 （v2ray程序本身就取消输出）

**Comment by kslr** [comment]
https://v2ray.com/chapter_02/01_overview.html#logobject

**Comment by maxchendt** [comment]
发现 **loglevel 设置的是 错误日志，非 访问日志**
是看了那个文档了。我要的是 禁止访问日志，如果 `"loglevel": "none",` 还是有访问日志。
`"access": "/dev/null"` 只是不让它保存到硬盘而已

**Comment by kslr** [comment]
Core none 不会有任何日志显示

塔哥 (CHEN Deng-Ta) <notifications@github.com> 于 2019年4月26日周五 11:18写道：

**Comment by maxchendt** [comment]
Sorry, 可能当时设置成none 时，没有 重启服务。设置 `"loglevel": "none"` 确实没有 访问日志 了。

另外，我可能潜意识认为  访问日志 是 "info" | "warning" 级别的，到 "error" 级别就应该停止了
