### ISSUE TITLE
V2ray官方镜像部署在microk8s中不能正常工作

### ISSUE THREAD

**Issue by ywg663** [v2ray/discussion#219]
最近折腾k8s,就以v2ray实验，以v2ray官方镜像，镜像内v2ray为4.18版本，部署在microk8s的pod中，外加一个k8s服务，以nodePort方式公开后面为v2ray的pod服务端口，同样的v2ray配置，同样的GCE,单纯以docker方式部署工作正常，部署在microk8s就不工作,GCE外防火墙等己配置正确.同样的方法如果镜像是nginx
，则nginx工作正常.

有无遇到类似问题的探讨一下，谢谢！

**Comment by mack-a** [comment]
请问你的现在 可以正常访问了吗
