### ISSUE TITLE
关于v4.18.1版本tls1.3无法使用的问题

### ISSUE THREAD

**Issue by random755882** [v2ray/discussion#221]
客户端：v4.18.1     服务器端：v4.18.0

使用WebSocket+TLS+Web方式，在服务器端的nginx只启用TLS1.3时无法连接（原有配置文件未更改）。
```
[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.xxx.com/xxxxxxxxxxx/):  > remote error: tls: error decoding message] >v2ray.com/core/common/retry: all retry attempts failed
```

**在v4.18.0的基础上，做了如下更改：**
1.在v2ray-core/main/main.go 的func main()中加入
`os.Setenv("GODEBUG", os.Getenv("GODEBUG")+",tls13=1")`

2.在 /go_master/gopath/src/v2ray.com/core/transport/internet/tls/config.go   config.CipherSuites = []uint16{}中添加
tls.TLS_CHACHA20_POLY1305_SHA256,
tls.TLS_AES_256_GCM_SHA384,
tls.TLS_AES_128_GCM_SHA256,

3.修改/go_master/gopath/src/v2ray.com/core/infra/bazel/build.bzl 
GOCACHE=/tmp

bazel build --action_env=GOPATH=$GOPATH --action_env=PATH=$PATH //release:v2ray_linux_amd64_package
编译安装后，tls1.3仍无法使用，报同样的错误。

当只启用`tls.TLS_CHACHA20_POLY1305_SHA256,tls.TLS_AES_256_GCM_SHA384,tls.TLS_AES_128_GCM_SHA256,`
时，tls1.3可以正常使用。

编译环境
$ uname -a
Linux manjaro-pc 4.19.34-1-MANJARO

$ go version
go version go1.12.3 linux/amd64

$ bazel version 
Build label: 0.22.0

**Comment by kslr** [comment]
https://github.com/v2fly/v2ray-core/commit/15c0e975ca66cc8ce3fb96e2943d04fb8b7a42de
https://github.com/v2fly/v2ray-core/commit/1a7b2337f81cbdbe7da06d5cf5c916de899ef372

**Comment by atrandys** [comment]
https://www.atrandys.com/2019/1880.html
