### ISSUE TITLE
为什么DNS入站代理必须指定转发地址和端口？

### ISSUE THREAD

**Issue by forever8938** [v2ray/discussion#222]
根据这篇文章
https://steemit.com/cn/@v2ray/dns

这是DNS入站代理
{
  "port": 53,
  "tag": "dns-in",
  "protocol": "dokodemo-door",
  "settings": {
    "address": "1.1.1.1",
    "port": 53,
    "network": "tcp,udp" // 是的，同时支持 TCP 和 UDP 流量，加了 TLS 之后还可以支持 DoT
  }
}

我的理解：用v2ray做DNS服务器的目的是根据域名分流，被墙的域名通过代理向国外DNS查询，其他直接向国内DNS查询，达到防污染和隐藏DNS查询的效果。

- DNS入站代理进来，不是要进过内置DNS分流吗，为什么一进来就要指定一个转发地址，而且是必填的？

- 发往1.1.1.1的DNS请求是否走代理？走了哪一个出站代理？

- 代理DNS请求的出站协议是否有要求，比如ss可以吗？

**Comment by eycorsican** [comment]
>DNS入站代理进来，不是要进过内置DNS分流吗，为什么一进来就要指定一个转发地址，而且是必填的？

内建的 DNS 只能处理 A/AAAA 类型的 DNS 请求，非 A/AAAA 请求会被直接发送到“原来”的目的地址，这个“转发地址”可以改写“原来”的地址，另外这个“转发地址”不是必填的，而且在 dns 出站协议配置里还有一次改写的机会

> 发往1.1.1.1的DNS请求是否走代理？走了哪一个出站代理？

如果是非 A/AAAA 请求发往了 1.1.1.1，就目前的实现来看，是肯定不走代理的（不走任何一个出站，包括 freedom）

> 代理DNS请求的出站协议是否有要求，比如ss可以吗？

没什么特殊要求，理应是一个代理出站，可以是 SS

**Comment by forever8938** [comment]
> > 发往1.1.1.1的DNS请求是否走代理？走了哪一个出站代理？
> 
> 如果是非 A/AAAA 请求发往了 1.1.1.1，就目前的实现来看，是肯定不走代理的（不走任何一个出站，包括 freedom）
经过内置DNS分流过的DNS请求，默认是否走代理呢？还是说需要添加路由规则，代理发往某个DNS服务器的请求？
> 
> > 代理DNS请求的出站协议是否有要求，比如ss可以吗？
> 
> 没什么特殊要求，理应是一个代理出站，可以是 SS
应该要求代理服务器支持udp转发吧？

**Comment by eycorsican** [comment]
就SS来说，它用UDP来传UDP，所以需要。如果是VMess，则可以用TCP代理连接来传DNS的UDP数据

**Comment by forever8938** [comment]
> 就SS来说，它用UDP来传UDP，所以需要。如果是VMess，则可以用TCP代理连接来传DNS的UDP数据

Vmess的streamSetting设置为websocket或者mkcp，还能代理DNS请求吗？

**Comment by eycorsican** [comment]
支不支持UDP流量代理是代理协议层面的东西，跟传输配置无关

**Comment by eycorsican** [comment]
> 发往1.1.1.1的DNS请求是否走代理？走了哪一个出站代理？

其实想让非 A/AAAA 的 DNS 请求流量经过 DNS 出站过滤后，继续通过代理服务器去连 1.1.1.1 也应该是可以的，但需要些额外配置，简单来说就是把 dns-in 的 dokodemo-door 转发地址配置为 127.0.0.1，端转发口为 5353，然后再配置另一个 dokodemo-door 监听 5353，转发地址配置为 1.1.1.1，路由里面再把进入 5353 dokodemo-door 的流量路由到一个代理出站。

dns-in (dokodemo 53) -> 路由 -> dns 出站 -> dokodemo 5353 -> 路由 -> 代理出站

但我也没试过这么配置，有兴趣可以试一下（不然非 A/AAAA 的 DNS 请求就全部裸奔了）

**Comment by kxmp** [comment]
不对 你这个不是什么代理不代理 你这个是端口映射啊.
我也有疑问 怎么保护dns流量呢.

**Comment by kxmp** [comment]
dot测试不支持 只填tls连都连不上 端口也没监听.
