### ISSUE TITLE
bash: ./v2ray: Permission denied

### ISSUE THREAD

**Issue by dx0eu** [v2ray/discussion#224]
~ $ curl -LO https://github.com/v2ray/v2ray-core/releases/download/v4.18.1/v2ray-linux-64.zip

~ $ unzip v2ray-linux-64.zip

~ $ ./v2ray
bash: ./v2ray: Permission denied

~ $ ld ./v2ray
ld: warning: cannot find entry symbol _start; defaulting to 0000000000401000

~ $ arch
x86_64

~ $ uname -a
Linux localhost 3.18.0-19030-g15d00031737b #1 SMP PREEMPT Sun Apr 14 18:59:51 PDT 2019 x86_64 Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz GenuineIntel GNU/Linux

**Comment by iochen** [comment]
try `chmod +x ./v2ray ./v2ctl`
