### ISSUE TITLE
Guide for setting up on OpenWRT router?

### ISSUE THREAD

**Issue by sysk** [v2ray/discussion#226]
Hi, total noob here! Is there a guide somewhere for setting it up on a OpenWRT router (GL-AR750)? That would avoid me having to setup the client on all my devices.

Thanks.

**Comment by forever8938** [comment]
check this out, it's very straightforward.
https://toutyrater.github.io/app/transparent_proxy.html

**Comment by johnrosen1** [comment]
https://www.johnrosen1.com/ubuntu-router/

**Comment by johnrosen1** [comment]
try this
