### ISSUE TITLE
[Question] 请问内置 DNS 对于 TTL 的处理

### ISSUE THREAD

**Issue by wi1dcard** [v2ray/discussion#229]
V2ray 项目组成员你们好：

我对于 V2ray 提供的内置 DNS 服务的行为有一些疑惑。经过测试发现，内置 DNS 服务输出的响应，会将 TTL 强制重设为 600s，例如：

```
; <<>> DiG 9.10.6 <<>> www.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24783
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.google.com.			IN	A

;; ANSWER SECTION:
www.google.com.		600	IN	A	216.58.200.4

;; Query time: 560 msec
;; SERVER: <MANUALLY HIDDEN>
;; WHEN: Tue May 14 19:22:20 CST 2019
;; MSG SIZE  rcvd: 48
```

但是，V2ray 内部对于 DNS 记录的缓存过期时间，处理逻辑如下：

1. 若该记录的 TTL 小于 600s，则以 TTL 为准；
2. 若该记录的 TTL 大于 600s，则以 600s 为准。

经过调试，找到疑似相关代码：

<https://github.com/v2ray/v2ray-core/blob/d66c3896ed692142f7d7d513c84bffafc916cab9/app/dns/udpns.go#L160-L181>

请问：

1. 这样设计的目的是什么？
2. 是有经过慎重考虑和斟酌的结果吗？
3. 如果是，是否应当在文档的 [DNS 配置](https://www.v2ray.com/chapter_02/04_dns.html) 小节注明呢？

若能给予些许指点，不胜感谢。

**Comment by kslr** [comment]
这可能因为10分钟是大多数DNS服务商的默认TTL


Wi1dcard <notifications@github.com> 于 2019年5月14日周二 19:38写道：

**Comment by wi1dcard** [comment]
@kslr 但这个行为我觉得不合适，如果每次都响应 600s 的 TTL，在刚开始查询和记录过期前一秒，得到的都是 600s，客户端等 600s 之后才会再次查询，虽然在 HTTP 浏览时影响不大，但这个「行为」似乎不合理。

**Comment by kslr** [comment]
你说的对，也许我们可以按照标准行为实现，欢迎提交PR

**Comment by eycorsican** [comment]
正如大多数 DNS 服务提供商都不会遵从 TTL 值，600s 单纯是 v2ray 内部对记录的缓存时间，实践上的问题，没什么不妥

**Comment by wi1dcard** [comment]
> 正如大多数 DNS 服务提供商都不会遵从 TTL 值，600s 单纯是 v2ray 内部对记录的缓存时间，实践上的问题，没什么不妥

不知道你说的「大多数」是特指哪些 DNS 服务商？据我所知，Google Public DNS 和 Cloudflare DNS 都是严格遵循上游 TTL 下发给客户端的。如果不遵循该值，那么使用诸如 AWS Route53 Failover 的站点，如果切换到 Backup，那么生效时间将会晚很多。

另外，根据源码，600s 并不是 V2ray 内部对记录的缓存时间。V2ray 内部的缓存过期时间是在「上游 TTL」和 「600s」之间取最小值，以最小值为准。

请不要误导严谨的人。谢谢。

**Comment by eycorsican** [comment]
@wi1dcard 那可真抱歉，不知你是如此严谨的人，欢迎提交 PR。
