### ISSUE TITLE
双网卡PC连上V2ray后能透过热点分享吗?

### ISSUE THREAD

**Issue by miyake99** [v2ray/discussion#232]
各位大神,

我有一部PC配置有线和无线网卡各一,我透过有线网络让V2rayN成功科学上网后能否将无线网卡设成热点让其他设备也能直接科学上网?

目前有线设成热点后手机连上热点,连外取得的IP还是原本宽带的IP,想请问这方法是否可行?

谢谢

**Comment by johnrosen1** [comment]
https://www.johnrosen1.com/ubuntu-router/ 试试这个

**Comment by miyake99** [comment]
> https://www.johnrosen1.com/ubuntu-router/ 试试这个

太感谢了
