### ISSUE TITLE
！！！我想要国外直连国内代理客户端配置效果

### ISSUE THREAD

**Issue by sg7ye** [v2ray/discussion#233]
{    //请大佬帮我看看我这个客户端配置国外直连国内代理写法对不对我koolshare使用不了。
  "inbounds": [
    {
      "port": 1080,
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
    },
      "settings": {
        "auth": "noauth"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom", // 本来这里是 vmess因为在墙外使用回国模式要做到墙外直连墙内代理这个效果
      "settings": {},
  "outboundDetour": [
    {
      "protocol": "vmess", // 本来这里是 freedom
      "settings": 
        "vnext": [
          {
            "address": "XXX.XXX.XXX.XXX",
            "port": 5201,
            "users": [
              {
                "id": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
                "alterId": 64,
				"security": "auto"
              }
            ]
          },
          {
            "address": "XXX.XXX.XXX.XXX",
            "port": 5202,
            "users": [
              {
                "id": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
                "alterId": 64,
				"security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "mkcp",  //需要kcp模式降低延时
        "kcpSettings": {
          "uplinkCapacity": 100,    //我墙外宽带千兆，墙内有30兆，不知道这个数值对不对！
          "downlinkCapacity": 100,
          "congestion": true,
          "header": {
            "type": "none"
                }
            }
        },
        "mux": {
            "enabled": true
        },
      "tag": "Proxy" //如果要使用路由，这个 tag 是一定要有的，在这里 Proxy 就是 freedom 的一个标号，在路由中说 Proxy V2Ray 就知道是这里的 freedom 了
    }    
  ],
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "outboundTag": "Proxy",
        "domain": ["geosite:cn"] // 中国大陆主流网站的域名
      },
      {
        "type": "field",
        "outboundTag": "Proxy",
        "ip": [
          "geoip:cn", // 中国大陆的 IP
          "geoip:private" // 私有地址 IP，如路由器等
        ]
      }
    ]
  }
}                        //DNS配置不知道要不要写

**Comment by kingwilliam** [comment]
假定你的客户端在国外

`	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
			{
				"type": "field",
				"outboundTag": "kcp_china",
				"domain": ["geosite:cn"] // 中国大陆主流网站的域名
			},
			{
				"type": "field",
				"outboundTag": "kcp_china",
				"ip": [
					"geoip:cn", // 中国大陆的 IP
				]
			}
		]
	}

	"outbounds": [
		{
			"tag": "direct",
			"protocol": "freedom",
			"settings": {}
		}
		{
			"tag": "kcp_china",
			"settings": {
				...
			}

		}
	],`

**Comment by kingwilliam** [comment]
`	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
			{
				"type": "field",
				"outboundTag": "kcp_china",
				"domain": ["geosite:cn"] // 中国大陆主流网站的域名
			},
			{
				"type": "field",
				"outboundTag": "kcp_china",
				"ip": [
					"geoip:cn", // 中国大陆的 IP
				]
			}
		]
	},
	"outbounds": [
		{
			"tag": "direct",
			"protocol": "freedom",
			"settings": {}
		}
		{
			"tag": "kcp_china",
			"settings": {
				...
			}
		}
	},`

**Comment by Yamazaki-wu** [comment]
@kingwilliam 
请教一下，我搭建了一台境内带验证的普通socks5，家里使用SSR填写了这个S5作为前置代理可以正常工作。
v2配置应该怎么写才能实现：家里v2客户端——境内S5——境外v2服务器（公益节点改不了配置）
目前上网使用chrome+SwitchyOmega方式，有SSR和v2rayN。
浏览器访问受限站点——发送请求给本机客户端——转发给境内socks5——境外v2服务器，不知道这样实现是否需要在中转的S5上也配置v2服务端？不能像SSR那样直接使用普通的S5么？
如果有没描述清楚的请指出，谢谢！
