### ISSUE TITLE
Can't add Shadowsocks server with salsa20 encryption method

### ISSUE THREAD

**Issue by yshalsager** [v2ray/discussion#235]
There's no option for using salsa20 as an encryption method.
I guess this is a feature request rather than a bug. 
Anyway, I've encountered this problem using BifrostV Android app and reported it to the developer, he said
> BifrostV support Shadowsocks by using V2Ray-Core implementation. Maybe you can report this there.

**Comment by forever8938** [comment]
不支持的加密多得是，你是不是要一个个发issue？

**Comment by yshalsager** [comment]
@forever8938 I used translation to understand the reply. If you're asking if I want to report an issue then yes.
