### ISSUE TITLE
紧急求助！！！

### ISSUE THREAD

**Issue by bruce2k** [v2ray/discussion#236]
因为需要下载训练数据，这些数据保存在google drive上，被迫找到这里。。。

由于第一次使用v2ray工具，不知道怎么用，请各位大佬指点迷津！我使用的ubuntu 17.10操作系统。问题如下：
1.由于我只在安装了v2ray的机器上使用，是否需要配置客户端？是否只配置服务端就可以了？
2.如果不需要配置客户端，安装完成后默认配置是不是就可以了？如果需要配置客户端，安装在同一台机器上？怎么配置？
3.是否需要在firfox中安装switchyOmega?怎么配置？
4.是否需要购买VPN？

万分感谢提供这个工具的组织！让我看到了下载数据的希望，万分感谢哪位大佬来指点迷津！！！

BTW：我安装的版本是4.18.2，从service v2ray status看是正常启动了的，congfig.json用的是默认的没有更改，也配置了switchyOmega，可就是不能正常翻！

**Comment by kslr** [comment]
1,2 都需要双向配置
3 Firefox本身支持代理

bruce2k <notifications@github.com> 于 2019年6月3日周一 10:25写道：

**Comment by bruce2k** [comment]
客户端和服务端在一台机器上的配置怎么配？可以给个例子吗？

需要购买VPN吗？

**Comment by bruce2k** [comment]
我尝试了在一个congfig文件中同时配置客户端和服务端，配置和报错如下：

{
  "log":{
    "loglevel": "warning",
    "error":"/media/bruce/overWall/error.log"
  },
  "inbounds": [{
     "port": 1080, //客户端inbound端口
     "protocol": "socks",
     "sniffing": {
       "enabled": true,
       "destOverride": ["http", "tls"]
     },
     "settings": {
       "auth": "noauth"  
     }
  },
  {
    "port": 12500,//服务端inbound端口
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "XXXX-XXXX-XXX...",
          "level": 1,
          "alterId": 64
        }
      ]
    }
  }],
  "outbounds": [{
      "protocol": "vmess",//客户端outbound
      "settings": {
        "vnext": [
          {
            "address": "XX.XX.XX.XX",//本机IP (服务端IP)
            "port": 12500,  
            "users": [
              {
                "id": "e1560bd3-922c-4272-b3a6-3525cb7ed7c5", 
                "alterId": 64 
              }
            ]
          }
        ]
      }
    },
{
    "protocol": "freedom",//服务端outbound
    "settings": {}
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      }
    ]
  }
}

报错日志如下：
2019/06/03 17:08:54 [Warning] [1531599980] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 192.168.1.104:12500: socket: too many open files] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/03 17:08:54 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:08:55 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:08:55 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:08:56 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:08:56 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:08:56 [Warning] [1492645187] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 192.168.1.104:12500: socket: too many open files] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/03 17:08:56 [Warning] [3499039562] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 192.168.1.104:12500: socket: too many open files] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/03 17:08:56 [Warning] [3993638737] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 192.168.1.104:12500: socket: too many open files] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/03 17:08:56 [Warning] [3966499630] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 192.168.1.104:12500: socket: too many open files] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/03 17:08:56 [Warning] [1840026119] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 192.168.1.104:12500: socket: too many open files] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/03 17:08:57 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:08:57 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:08:58 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:08:58 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:08:59 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:08:59 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:08:59 [Warning] [2876823040] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 192.168.1.104:12500: socket: too many open files] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/03 17:09:00 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:09:01 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:09:01 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:09:02 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:09:02 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:09:03 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:09:03 [Warning] [1681600000] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 192.168.1.104:12500: socket: too many open files] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/03 17:09:04 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:09:04 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:09:05 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:09:05 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:09:06 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:09:06 [Warning] [1044003185] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 192.168.1.104:12500: socket: too many open files] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by kslr** [comment]
我建议你从白话文教程开始，直接搜索即可。
