### ISSUE TITLE
如何直接使用v2ray架设vpn服务器从而转发到vmess上?

### ISSUE THREAD

**Issue by euloanty** [v2ray/discussion#237]
很多操作系统例如win10，例如ubuntu直接提供预装的vpn客户端。是否有办法能直接连接vpn到v2ray客户端上，从而转发到v2ray客户端？

**Comment by euloanty** [comment]
为何只提供"dokodemo-door"协议而不直接提供"vpn"协议呢？既然v2ray支持shadowsocks，就应该有办法支持vpn吧。

**Comment by kslr** [comment]
什么是vpn呢

**Comment by euloanty** [comment]
![image](https://user-images.githubusercontent.com/8005905/58804104-9ad39880-8643-11e9-86f3-12af936e74c0.png)
如果能让v2ray直接支持vpn，就不需要很多透明代理了，让操作系统直接处理这些屁事。

**Comment by kslr** [comment]
没有这方面计划
