### ISSUE TITLE
紧急求助！！！

### ISSUE THREAD

**Issue by bruce2k** [v2ray/discussion#238]
由于需要从google drive下载训练数据，项目进度十分紧张。求助大佬指点：
1.仅一台PC安装ubantu 17.10是否可以通过v2ray 翻出去（无VPS）;
2.如果仅一台PC可以翻，请大佬告知如何配置config.json。如果不能翻必须要VPS大佬指示需要满足什么条件的VPS才能翻？

万分感谢大佬的回复！万分感谢project V提供的工具！

我尝试了在一个congifg里面配置客户端和服务器的inbound&outbound结果失败了。配置和失败信息如下：
congfig.json配置：
{
"log":{
"loglevel": "warning",
"error":"/media/bruce/overWall/error.log"
},
"inbounds": [{
"port": 1080, //客户端inbound端口
"protocol": "socks",
"sniffing": {
"enabled": true,
"destOverride": ["http", "tls"]
},
"settings": {
"auth": "noauth"
}
},
{
"port": 12500,//服务端inbound端口
"protocol": "vmess",
"settings": {
"clients": [
{
"id": "XXXX-XXXX-XXX...",
"level": 1,
"alterId": 64
}
]
}
}],
"outbounds": [{
"protocol": "vmess",//客户端outbound
"settings": {
"vnext": [
{
"address": "XX.XX.XX.XX",//本机IP (服务端IP)
"port": 12500,
"users": [
{
"id": "e1560bd3-922c-4272-b3a6-3525cb7ed7c5",
"alterId": 64
}
]
}
]
}
},
{
"protocol": "freedom",//服务端outbound
"settings": {}
},{
"protocol": "blackhole",
"settings": {},
"tag": "blocked"
}],
"routing": {
"rules": [
{
"type": "field",
"ip": ["geoip:private"],
"outboundTag": "blocked"
}
]
}
}

出错日志：

2019/06/03 17:08:54 [Warning] [1531599980] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 192.168.1.104:12500: socket: too many open files] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/03 17:08:54 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:08:55 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:08:55 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:08:56 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:08:56 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12500: accept4: too many open files
2019/06/03 17:08:56 [Warning] [1492645187] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 192.168.1.104:12500: socket: too many open files] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/03 17:08:56 [Warning] [3499039562] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 192.168.1.104:12500: socket: too many open files] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/03 17:08:56 [Warning] [3993638737] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 192.168.1.104:12500: socket: too many open files] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/03 17:08:56 [Warning] [3966499630] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 192.168.1.104:12500: socket: too many open files] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/03 17:08:56 [Warning] [1840026119] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 192.168.1.104:12500: socket: too many open files] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by kslr** [comment]
重复
