### ISSUE TITLE
请求将 DNS 服务开放给外部程序使用

### ISSUE THREAD

**Issue by ToutyRater** [v2ray/discussion#24]
在手机或者路由器等需要透明代理的设备上，几乎都要先将域名解析成 IP 才发送连接请求，而不能像 socks 协议那样将目标服务器的域名连同连接请求发给代理服务器，所以透明代理另外需要解决的问题是如何**快速**且**无污染**地进行 DNS 解析。无污染这个问题可以通过外部软件（如 DNSMASQ）解决，或者利用 dokodemo-door 由代理服务器转发解析，也可以利用 V2Ray 的 sniffing 功能，就目前来说污染问题算是解决了，但是这几种方式都需要多消耗一个 RTT，实在谈不上快速。另外在这几种方法中，我比较倾向与使用 sniffing，因为它和 V2Ray 的路由功能搭配得最好，但是 sniffing 还有一个问题是只对 HTTP 和 TLS 有效( TLS1.3 的 SNI 字段会被加密，等到 TLS1.3 普及之后连 TLS 也不能探测了 )。所以我希望 V2Ray 能够开放 DNS 服务并添加一些功能，以解决现有的透明代理方案关于 DNS 解析的问题。

构思如下：
1. V2Ray 开放 DNS，透明代理的设备将 V2Ray 设为 DNS 服务器；
2. 某一时刻设备打算访问一个服务器，假设是 github.com，那么它首先查询 DNS 将 github.com 解析成 IP；
3. V2Ray 接收到 DNS 请求时，暂不转发 DNS 查询请求到墙外的服务器，而是伪造一个 IP (假设是 11.22.33.44)进行应答，并且将查询的域名 github.com 对应伪造的 IP 11.22.33.44 关联起来；
4.  设备接收到响应后，对目标 IP(伪造的 11.22.33.44) 发起连接请求；
5. 由于透明代理，V2Ray 接收到目标是 11.22.33.44 的连接请求，查到关联的域名是 github.com，然后将目标地址重置为域名 github.com；
6. V2Ray 将重置了目标地址的数据包发往 Dispatcher 进行路由；
7. 路由及 Freedom 的 domainStrategy 沿用现在的方式。

在透明代理中快速且无污染进行 DNS 解析，还要与 V2Ray 的路由功能无缝配合，这是我能想到的最好的方案了，假如上述的设想具有可行性，还请加入此功能。

**Comment by VictoriaRaymond** [comment]
由于DNS服务器的功能过于复杂，而且已有同类产品，比如[overtune](https://github.com/shawn1m/overture)，所以暂时不会将这个功能列为高优先级。

关于你的提案，之前有过类似的。它的本质是制造一个DNS污染。当后续的连接请求都能被截获时，这个方法应该没有问题。但如果后续的连接没有被截获，比如用户突然关闭了VPN，可能会造成一定的影响。具体的DNS的内容我不太熟悉，无法全面评估这样做的风险。

**Comment by ToutyRater** [comment]
表示理解

**Comment by VictoriaRaymond** [comment]
已在 4.15 中加入 DNS outbound。

**Comment by VictoriaRaymond** [comment]
原issue中提到了伪造IP地址，这个功能还要再等等。

**Comment by kdrx** [comment]
@ToutyRater 你说的这个构想其实v2ray 早就实现了，那就是 destOverride, 我一直是这么用的。
配合dnsmasq 设置主要解析server 为国内dns server，其他将所有gfwlist域名解析到1.2.3.4这个伪造ip： address=/packagecontrol.io/1.2.3.4
.......
然后iptable 转发所有目标地址为1.2.3.4 的数据包到 透明代理-> v2ray inbound dokodemo-door, 开启destOverride，这样就重置了http(s)链接的dest domain，再通过outbound发送到vps，实现了远端dns解析和数据访问。
这样就实现了域名分流。用了近半年了，相当可靠。

**Comment by VictoriaRaymond** [comment]
感谢 @kdrx 的确是一个可行的方案。

**Comment by eycorsican** [comment]
@VictoriaRaymond DNS 中的 hosts 域名匹配为什么不把 regexp 也支持了呢？这样的话就可以把所有域名都指向一个 fake IP，再配合 DNS outbound 以及 sniffing，单独 V2Ray 就能够实现所谓的 Fake DNS。

当然目前也可以的，但 hosts 的配置就比较尴尬了，可能会需要一个比很长的列表。

**Comment by VictoriaRaymond** [comment]
@eycorsican  支持的吧，hosts中的域名格式和路由中一样。

**Comment by eycorsican** [comment]
@VictoriaRaymond  我测了一下不行，看代码发现只对 "domain:" 和 "geosite:" 做了处理：https://github.com/v2ray/v2ray-core/blob/950e226293c0a02318f26a9209b686efff16d1e5/infra/conf/dns.go#L145

**Comment by xjasonlyu** [comment]
@eycorsican 话说v2ray的dns outbound怎么用啊？按官网doc配置好像没啥反应，有demo吗。。

**Comment by eycorsican** [comment]
https://steemit.com/cn/@v2ray/dns

**Comment by VictoriaRaymond** [comment]
@eycorsican 好吧，一会修

**Comment by xjasonlyu** [comment]
@eycorsican 
按照这样配置好inbound，dns outbound，rule理论上应该是一个53端口的dns服务器了
```json
{
  "port": 53,
  "tag": "dns-in",
  "protocol": "dokodemo-door",
  "settings": {
    "address": "1.1.1.1",
    "port": 53,
    "network": "tcp,udp"
  }
}
```
但我把dns设置成v2ray所监听ip，`dig google.com`是超时的，哪里配置有问题吗？

v2 output 如下
```
2019/02/14 19:45:24 [Debug] [1649500774] v2ray.com/core/proxy/dokodemo: processing connection from: 10.0.0.2:55262
2019/02/14 19:45:24 [Info] [1649500774] v2ray.com/core/app/dispatcher: taking detour [DNS-OUT] for [udp:1.1.1.1:53]
2019/02/14 19:45:24 [Debug] v2ray.com/core/app/dns: querying DNS for: time-ios.apple.com.
2019/02/14 19:45:24 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:1.1.1.1:53
2019/02/14 19:45:24 [Info] v2ray.com/core/transport/internet/udp: establishing new connection for udp:1.1.1.1:53
2019/02/14 19:45:24 [Info] v2ray.com/core/app/dispatcher: default route for udp:1.1.1.1:53
2019/02/14 19:45:24 [Info] v2ray.com/core/common/mux: dispatching request to udp:1.1.1.1:53
2019/02/14 19:45:24 [Debug] v2ray.com/core/app/dns: updating IP records for domain:time-ios.apple.com.
```

**Comment by eycorsican** [comment]
我看不到你的outbound和rule

**Comment by xjasonlyu** [comment]
@eycorsican 
```json
{
  "log": {
    "loglevel": "debug"
  },
  "dns": {
    "hosts": {
      "localhost": "127.0.0.1"
    },
    "servers": [
      {
        "address": "223.5.5.5",
        "port": 53,
        "domains": [
          "geosite:cn"
        ]
      },
      {
        "address": "1.1.1.1",
        "port": 53,
        "domains": [
          "geosite:geolocation-!cn"
        ]
      },
      "localhost"
    ]
  },
  "inbounds": [
    {
      "port": 1090,
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "ip": "10.0.0.5",
        "udp": true
      },
      "tag": "SOCKS"
    },
    {
      "port": 53,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "1.1.1.1",
        "port": 53,
        "network": "tcp,udp"
      },
      "tag": "DNS-IN"
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": null
          }
        ]
      },
      "mux": {
        "enabled": true
      },
      "tag": "PROXY"
    },
    {
      "protocol": "freedom",
      "tag": "DIRECT"
    },
    {
      "protocol": "blackhole",
      "tag": "REJECT"
    },
    {
      "protocol": "dns",
      "tag": "DNS-OUT"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "inboundTag": ["DNS-IN"],
          "outboundTag": "DNS-OUT"
        },
        {
          "type": "field",
          "domain": [
            "geosite:geolocation-!cn"
          ],
          "outboundTag": "PROXY"
        },
        {
          "type": "field",
          "domain": [
            "geosite:speedtest"
          ],
          "outboundTag": "PROXY"
        },
        {
          "type": "field",
          "domain": [
            "geosite:cn"
          ],
          "outboundTag": "DIRECT"
        },
        {
          "type": "field",
          "ip": [
            "geoip:cn"
          ],
          "outboundTag": "DIRECT"
        },
        {
          "type": "field",
          "ip": [
            "geoip:private"
          ],
          "outboundTag": "DIRECT"
        }
      ]
    }
  }
}
```

**Comment by eycorsican** [comment]
看起来没问题，你试试 dig @127.0.0.1 google.com

**Comment by xjasonlyu** [comment]
@eycorsican 
dig好像没有问题了
```
root@ubuntu-server:~# dig @10.0.0.5 google.com

; <<>> DiG 9.11.3-1ubuntu1.3-Ubuntu <<>> @10.0.0.5 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5491
;; flags: qr; QUERY: 0, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; ANSWER SECTION:
google.com.             600     IN      A       172.217.5.206

;; Query time: 0 msec
;; SERVER: 10.0.0.5#53(10.0.0.5)
;; WHEN: Thu Feb 14 12:28:44 UTC 2019
;; MSG SIZE  rcvd: 38
```
但是`curl google.com`出毛病了...
```
root@ubuntu-server:~# curl google.com
curl: (6) Could not resolve host: google.com
```

**Comment by eycorsican** [comment]
系统DNS设置成 127.0.0.1 了？

**Comment by xjasonlyu** [comment]
emmmm，应该是dnsmasq配置错了，直接dig google是不通的。。

**Comment by ToutyRater** [comment]
@kdrx 你这个方案我早用过了，教程里也写了，我还是觉得 V2Ray 内部实现更好。原因一是为了应对将来的 sni 头部加密；二是这种方法我测试的时候会在某些特殊情况下会出现问题。

**Comment by VictoriaRaymond** [comment]
@xjasonlyu dnsmasq 的兼容性问题在 4.15.1 里修了。

**Comment by xjasonlyu** [comment]
@VictoriaRaymond >_>我debug了半个多小时的dnsmasq log，原来是v2的问题？？大神能简单解释一下吗？（PS：为啥v2的v4.15.1是pre-release状态？）

**Comment by VictoriaRaymond** [comment]
嗯，简单来说是v2ray的bug。但是bug的重要程度没有达到需要发布正式版本。

**Comment by xjasonlyu** [comment]
@VictoriaRaymond 那为什么就dnsmasq把v2 dns outbound作为upstream dns会有兼容性问题？

**Comment by beyondkmp** [comment]
> @ToutyRater 你说的这个构想其实v2ray 早就实现了，那就是 destOverride, 我一直是这么用的:
> 配合dnsmasq 设置主dns server 为国内dns server，其他将所有gfwlist域名解析到1.2.3.4这个伪造ip：
> server=114.114.114.114 #非污染域名解析
> address=/google.com/1.2.3.4 #污染域名解析
> address=/twitter.com/1.2.3.4
> .......
> 然后iptable 转发所有目标地址为 1.2.3.4 的数据包到 透明代理-> v2ray inbound dokodemo-door, 开启destOverride，这样就重置了http(s)链接的dest domain，再通过outbound发送到vps，实现了远端dns解析和数据访问。
> 这样就实现了域名分流。用了近半年了，相当可靠。
> 这样的配置很精简，不需要设置dns和routing，v2ray仅对污染域名全部转发。巧妙的利用构造虚假ip地址，实现了iptable类似域名分流的功能。也比v2ray应用层实现分流更可靠，即使是v2ray 客户端或vps服务出现故障不能访问，也不会影响非污染域名的网站访问。

这个我也用的很爽，不过有一点不好，比如github和gitlab同时用的ssh协议，这种方法就失效了！

**Comment by bxwllzz** [comment]
不一定要对某个域名返回虚假 IP ，再将虚假 IP 翻译为原始域名。

另一种方式，类似于路由器上使用dnsmasq+ipset+iptables进行透明代理
1. 通过 DNS Outbound 拦截DNS请求，并使用内部DNS解析，以真实IP响应DNS请求
2. 将解析得到的真实IP及其关联域名记录下来，（路由器上是由dnsmasq将指定域名的IP保存到ipset）
3. 在后续接收到指向该IP的连接时，将其翻译为关联域名，并根据域名规则进行处理（路由器上是iptable匹配到ipset中的IP后，将流量转发到按照该域名所属的规则组进行处理）

这种方式的
优点：不使用虚假IP，当用户关闭V2Ray后，仍然可以正常向正确IP地址发送请求
缺点：多个域名指向同一个IP时，无法区分该连接的关联域名是哪一个，若这些域名属于不同的规则组，则无法准确判断使用哪个Outbound

为了部分解决多个域名对应同一个IP的问题，可以考虑综合Fake DNS方式与上述方式：第一次将某个IP关联到某个域名时，返回真实IP，后续其他域名若关联到同一个IP，则返回虚假IP。

**Comment by fbion** [comment]
提供一种电脑做网关的思路

可以的
https://github.com/FlowerWrong/tun2socks
https://github.com/xjasonlyu/tun2socks
这两个已经实现fake dns
surge增强模式也是这样
有两种方式
google.com -> 192.18.0.1
google.com.hk -> 192.18.0.2

google.com -> 192.18.0.1:1111
google.com.hk -> 192.18.0.2:1112

通过这种关联即可

个人系统192.168.1.2开启
net.inet.ip.forwarding=1
开启tun2socks
sudo route add 198.18.0.2/24 240.0.0.1(tun网关)

手机设置网关192.168.1.2
所有流量走192.168.1.2了吧
192.168.1.2开启fake dns
手机dns服务器也设置为1.2
手机访问google.com 得到ip 192.18.0.1
手机连接192.18.0.1经过192.168.1.2
192.18.0.1走tun接口
tun2socks检测到访问192.18.0.1->google.com

此时tun2socks->v2ray inbounds
由v2ray来识别国外国内 google facebook twitter等域名

假如手机访问baidu,v2ray直接识别为geosite:cn ip 流量直接国内走


tun2socks只需要提供fake dns和代理功能
分流交给v2ray来做
这样
