### ISSUE TITLE
怎么配置国外IP禁止链接到V2ray

### ISSUE THREAD

**Issue by yl332332** [v2ray/discussion#240]
最近代理泄露，被一些国外的IP发送了很多垃圾邮件，导致服务器被封停。所以我想v2ray能不能屏蔽国外IP连进来？
```
"source": [
    "geoip:cn"
  ],
"outboundTag": "blocked"
```
上面路由设置只能把国内IP连进来的禁掉。

**Comment by kxmp** [comment]
那你把cn改成所有外国的简称 有多少个国家就写多少行 应该就可以了

**Comment by kslr** [comment]
使用iptables是更简单的办法
