### ISSUE TITLE
2天就被封IP了正常吗  

### ISSUE THREAD

**Issue by umrwifi** [v2ray/discussion#241]
用的kagoya的vps  
安装脚本https://www.atrandys.com/2018/216.html

**Comment by umrwifi** [comment]
还好kagoya可以无限开instance  现在基本上每隔2天就要重新开个vps

**Comment by e2ge** [comment]
kcp没有混淆，tcp没有tls，就是裸奔咯。

**Comment by umrwifi** [comment]
> kcp没有伪装，tcp没有tls，就是裸奔咯。

明白了

**Comment by johnrosen1** [comment]
> 用的kagoya的vps
> 安装脚本https://www.atrandys.com/2018/216.html

要安全，上三件套有请 https://www.johnrosen1.com/v2ray-cdn/ cloudflare cdn仅建议作为备用
