### ISSUE TITLE
能否实现80走ws，而443走ws+tls？

### ISSUE THREAD

**Issue by soundghost** [v2ray/discussion#242]
目前，在443端口上基于websokes+tls+nginx的方式可以正常使用。

但还想实现在80端口上用websocks+nginx的方法来实现域名混淆的功能。

也就是说当希望在客户端上实现混淆（免流）的时候，切换到80端口；如果不用混淆，切换到443端口。

如果可行的话，请问v2ray的config.json文件、nginx的虚拟主机配置文件分别应该怎么配置？

请大家不吝赐教。谢谢！

**Comment by soundghost** [comment]
当然我知道客户端是两个不同的配置文件的，可是最近一直受困于服务器端的配置。

**Comment by e2ge** [comment]
nginx不配置ssl不就行了，v2是一样的。

**Comment by soundghost** [comment]
谢谢你的回复，意思是443不加SSL？那不相当于开了两个不加密的端口？
v2里也只用ws，而不是ws+tls？

**Comment by e2ge** [comment]
nginx开两个端口，一个tls，一个普通的，后面v2用同一个后端websocket，v2不用tls。

**Comment by forever8938** [comment]
客户端不开tls不就行了

**Comment by soundghost** [comment]
谢谢大家的回复，走80是想免流，走443是为了加密。
但我还是没有找对方法，没成功。

**Comment by fengyeblade** [comment]
很简单。  nginx 里 location 到ws 就行了。  至于上部上tls 就看是访问nginx的80 还是4443而已
