### ISSUE TITLE
只把域名解析到IP而不实装web服务端，让v2ray接管443，是否可行？

### ISSUE THREAD

**Issue by Lantrancy** [v2ray/discussion#243]
我尝试用certbot签发Stand alone证书然后把v2ray配置为h2模式，直接使用443端口，发现通过域名还是无法访问。是不是一定要装个web服务做h2反代才行？
之所以想要这样配置是因为试过nginx+ws速度非常慢

**Comment by kxmp** [comment]
可以. 刚才跑了下测试 确定可以的. (这下我可不会记错了.... ;-)

**Comment by johnrosen1** [comment]
> 我尝试用certbot签发Stand alone证书然后把v2ray配置为h2模式，直接使用443端口，发现通过域名还是无法访问。是不是一定要装个web服务做h2反代才行？
> 之所以想要这样配置是因为试过nginx+ws速度非常慢

v2直接监听443不能抗主动探测
