### ISSUE TITLE
v2ray的官网被墙了，还有哪些途径可以获得v2ray的白皮书？

### ISSUE THREAD

**Issue by vainquit** [v2ray/discussion#247]
网上有很多手把手教的例子，一键安装脚本，然而我照着做了几个都没成功，而且SSH的连接很不稳定，每次都安装到一半就断线，再重新安装就出现各种莫名其妙的错误。于是想弄明白原理自己配置，然而v2ray的官网被墙了，下载的压缩包中的README也看了，都没办法获得更详细的资料。我只能对比不同的教程中的config.json的配置，然而它们的配置要么只有服务端，要么只有客户端，即便两个都有，可每个教程中保留的参数都大不一样。这几天折腾了很久实在没办法，只能在这里求一份官方的技术文档，谢谢了

**Comment by iochen** [comment]
[https://htmlpreview.github.io/?https://github.com/v2ray/v2ray.github.io/blob/master/index.html](https://htmlpreview.github.io/?https://github.com/v2ray/v2ray.github.io/blob/master/index.html)
或到
[https://github.com/v2ray/v2ray.github.io](https://github.com/v2ray/v2ray.github.io) 下到本地看

**Comment by iochen** [comment]
[https://htmlpreview.github.io/?https://github.com/v2ray/v2ray.github.io/blob/master/index.html](https://htmlpreview.github.io/?https://github.com/v2ray/v2ray.github.io/blob/master/index.html)
或到
[https://github.com/v2ray/v2ray.github.io](https://github.com/v2ray/v2ray.github.io) 下到本地看

**Comment by vainquit** [comment]
> https://htmlpreview.github.io/?https://github.com/v2ray/v2ray.github.io/blob/master/index.html
> 或到
> https://github.com/v2ray/v2ray.github.io 下到本地看

十分感谢！上面那个网站已打开，把每个页面都另存为了，再也不用饱受自己瞎摸索之苦了，哈哈~~

顺便有点好奇，下面那个该怎么下载到本地看呢，是直接下载整个zip压缩包、解压、然后打开html文件吗？我那样做后发现它还是要跳转到v2ray去，断网情况下压缩包里面的所有html文件都连接失败了。感觉这和我平时在chrome右键另存为网页的不太一样。

**Comment by iochen** [comment]
> > https://htmlpreview.github.io/?https://github.com/v2ray/v2ray.github.io/blob/master/index.html
> > 或到
> > https://github.com/v2ray/v2ray.github.io 下到本地看
> 
> 十分感谢！上面那个网站已打开，把每个页面都另存为了，再也不用饱受自己瞎摸索之苦了，哈哈~~
> 
> 顺便有点好奇，下面那个该怎么下载到本地看呢，是直接下载整个zip压缩包、解压、然后打开html文件吗？我那样做后发现它还是要跳转到v2ray去，断网情况下压缩包里面的所有html文件都连接失败了。感觉这和我平时在chrome右键另存为网页的不太一样。

我没注意，里面有JS防嵌套，抱歉

或者你也可以下载我生成的PDF版本，离线看 [https://github.com/iochen/books/blob/master/V2Ray/V2Ray.pdf](https://github.com/iochen/books/blob/master/V2Ray/V2Ray.pdf)

**Comment by vainquit** [comment]
> > > https://htmlpreview.github.io/?https://github.com/v2ray/v2ray.github.io/blob/master/index.html
> > > 或到
> > > https://github.com/v2ray/v2ray.github.io 下到本地看
> > 
> > 
> > 十分感谢！上面那个网站已打开，把每个页面都另存为了，再也不用饱受自己瞎摸索之苦了，哈哈~~
> > 顺便有点好奇，下面那个该怎么下载到本地看呢，是直接下载整个zip压缩包、解压、然后打开html文件吗？我那样做后发现它还是要跳转到v2ray去，断网情况下压缩包里面的所有html文件都连接失败了。感觉这和我平时在chrome右键另存为网页的不太一样。
> 
> 我没注意，里面有JS防嵌套，抱歉
> 
> 或者你也可以下载我生成的PDF版本，离线看 https://github.com/iochen/books/blob/master/V2Ray/V2Ray.pdf

喔喔感激不尽！！！！这个PDF版本就比我一个个下载的好看多了 :p

**Comment by forever8938** [comment]
大部分内容官网的文档里都没有，还得看白话文教程。更有些内容是根本没有文档，只能脑补。

**Comment by kslr** [comment]
http://guide.v2fly.org/
