### ISSUE TITLE
貌似版本发布与更新日志不太同步

### ISSUE THREAD

**Issue by funray** [v2ray/discussion#25]
https://github.com/v2ray/v2ray-core/releases
https://www.v2ray.com/chapter_00/01_versions.html
请给我个合理的解释

**Comment by nicholascw** [comment]
一个合理的解释是你看不见tag.

**Comment by funray** [comment]
没懂你的意思，不过 请原谅我的鲁莽，我只是好奇。

**Comment by funray** [comment]
好吧，我明白了，省略的版本一般是Bug fixes的。
