### ISSUE TITLE
关于用户等级 (level) 的生效范围

### ISSUE THREAD

**Issue by sjdhome** [v2ray/discussion#251]
虽然文档中写了入站出站代理均可使用用户等级，但是用户等级需要填写在哪里才能生效？举例子说，Android 上 Google 的 FCM 消息推送系统需要隔一段时间发送一个心跳包，在 Shadowsocks 里只需要修改 timeout 即可实现延长超时时间，v2ray 中的用户等级中也有相应的 connIdle，但在 v2ray 里是设定服务端的入站代理的用户等级还是设定出站代理的？客户端也需要设定用户等级么？

**Comment by zx3777** [comment]
虽然这么多年了。
只要服务端设置了用户等级的connldle，客户端可以不设置就生效。
不用管入站出站。直接在服务端的配置文件中添加一段这个fcm就不会断了，conniIdle值只要超过fcm的最大心跳间隔时间就行。

"policy": {
    "levels": {
      "0": {
        "connIdle": 3600
      }
    }
}

426里每隔599 899 1199 600 900 1200秒就断开，都是这个原因，因为默认connIdle时间是300，fcm心跳有时候是500多。
