### ISSUE TITLE
关于路由功能的疑问，为每个inbound指定outbound

### ISSUE THREAD

**Issue by Kurobac** [v2ray/discussion#254]
我现在需要将v2ray同时作为vmess和shadowsocks客户端使用，想法是多配置几个inbound，给每个inbound指定outbound，在需要fq的设备上进行切换。看文档感觉需要用路由功能，但是不知道为什么使用路由后就无法连接ss了（跑vmess的机子已经挂了也没法测试……）
配置文件
`
{

    "log": {
        "access": "D://v2ray.log",
        "error": "D://v2ray_error.log",
        "loglevel": "warning"
    },
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "type": "field",
                "inboundTag": [
                    "ss2socks"
                ],
                "outboundTag": "ssout"
            },
            {
                "type": "field",
                "inboundTag": [
                    "vmess2socks"
                ],
                "outboundTag": "vmessout"
            }
        ]
    },
    "outbounds": [
        {
            "sendThrough": "0.0.0.0",
            "protocol": "vmess",
            "settings": {
                "vnext": [
                    {
                        "address": "...",
                        "port": ...,
                        "users": [
                            {
                                "id": "...",
                                "alterId": 64,
                                "security": "auto"
                            }
                        ]
                    }
                ],
                "streamSettings": {
                    "network": "mkcp",
                    "kcpSettings": {
                        "uplinkCapacity": 20,
                        "downlinkCapacity": 100,
                        "congestion": true,
                        "header": {
                            "type": "none"
                        }
                    }
                },
                "mux": {
                    "enabled": true
                },
                "tag": "vmessout"
            }
        },
        {
            "sendThrough": "0.0.0.0",
            "protocol": "shadowsocks",
            "settings": {
                "servers": [
                    {
                        "address": "...",
                        "port": ...,
                        "method": "aes-256-gcm",
                        "password": "...",
                        "ota": false
                    }
                ]
            },
            "tag": "ssout"
        }
    ],
    "inbounds": [
        {
            "port": 1080,
            "listen": "0.0.0.0",
            "protocol": "socks",
            "settings": {
                "udp": true,
                "ip": "127.0.0.1",
                "timeout": 0,
                "userLevel": 0
            },
            "tag": "vmess2socks"
        },
        {
            "port": 1081,
            "listen": "0.0.0.0",
            "protocol": "socks",
            "settings": {
                "udp": true,
                "ip": "127.0.0.1",
                "timeout": 0,
                "userLevel": 0
            },
            "tag": "ss2socks"
        }
    ]}
我预期的结果是从1081接口的流量会根据路由规则走shadowsocks的出口，但是如此配置之后使用1081端口的代理无法加载任何网页。我尝试用了一下wireshark，能发现确实有数据包发往SS服务器的IP了，但是没有回复。另外我试过最小化配置，是可以正常工作的。
`{

    "log": {
        "access": "D://v2ray.log",
        "error": "D://v2ray_error.log",
        "loglevel": "warning"
    },
    "outbounds": [
        {
            "sendThrough": "0.0.0.0",
            "protocol": "shadowsocks",
            "settings": {
                "servers": [
                    {
                        "address": "...",
                        "port":...,
                        "method": "...",
                        "password": "...",
                        "ota": false,
                        "level": 0
                    }
                ]
            },
            "tag": "ssout"
        }
    ],
    "inbounds": [
        {
            "port": 1081,
            "listen": "0.0.0.0",
            "protocol": "socks",
            "settings": {
            },
            "tag": "ss2socks"
        }
    ]
}`
是我对这个路由功能理解的不对么？
日志（好像没有有意义的内容）
access log

2019/06/11 12:23:25 tcp:127.0.0.1:65043 accepted tcp:www.google.com:443 
2019/06/11 12:23:26 tcp:127.0.0.1:65046 accepted tcp:www.google.com:443 
2019/06/11 12:23:26 tcp:127.0.0.1:65048 accepted tcp:www.google.com:443 
2019/06/11 12:23:26 tcp:127.0.0.1:65050 accepted tcp:clients4.google.com:443 
2019/06/11 12:23:27 tcp:127.0.0.1:65052 accepted tcp:www.google.com:443 
2019/06/11 12:23:27 tcp:127.0.0.1:65054 accepted tcp:clients4.google.com:443 
2019/06/11 12:23:28 tcp:127.0.0.1:65057 accepted tcp:www.google.com:443 
2019/06/11 12:23:56 tcp:127.0.0.1:65073 accepted tcp:www.v2ray.com:443 
2019/06/11 12:23:56 tcp:127.0.0.1:65076 accepted tcp:www.v2ray.com:443 
2019/06/11 12:23:57 tcp:127.0.0.1:65078 accepted tcp:www.v2ray.com:443 
2019/06/11 12:23:57 tcp:127.0.0.1:65080 accepted tcp:www.v2ray.com:443 
2019/06/11 12:24:03 tcp:127.0.0.1:65088 accepted tcp:www.v2ray.com:443 
2019/06/11 12:24:03 tcp:127.0.0.1:65090 accepted tcp:www.v2ray.com:443 
2019/06/11 12:27:28 tcp:127.0.0.1:65254 accepted tcp:www.google.com:443 
2019/06/11 12:27:28 tcp:127.0.0.1:65256 accepted tcp:www.google.com:443 
2019/06/11 12:27:29 tcp:127.0.0.1:65259 accepted tcp:www.google.com:443 
2019/06/11 12:27:29 tcp:127.0.0.1:65261 accepted tcp:clients4.google.com:443 
2019/06/11 12:27:29 tcp:127.0.0.1:65264 accepted tcp:www.google.com:443 
2019/06/11 12:27:29 tcp:127.0.0.1:65266 accepted tcp:clients4.google.com:443 
2019/06/11 12:27:30 tcp:127.0.0.1:65268 accepted tcp:www.google.com:443 
2019/06/11 12:27:30 tcp:127.0.0.1:65270 accepted tcp:www.google.com:443 
2019/06/11 12:27:36 tcp:127.0.0.1:65275 accepted tcp:www.google.com:443 
2019/06/11 12:37:54 tcp:127.0.0.1:49371 accepted tcp:www.google.com:443 
2019/06/11 12:37:54 tcp:127.0.0.1:49373 accepted tcp:www.google.com:443 
2019/06/11 12:37:55 tcp:127.0.0.1:49375 accepted tcp:www.google.com:443 
2019/06/11 12:37:55 tcp:127.0.0.1:49377 accepted tcp:clients4.google.com:443 
2019/06/11 12:37:55 tcp:127.0.0.1:49379 accepted tcp:www.google.com:443 
2019/06/11 12:37:55 tcp:127.0.0.1:49381 accepted tcp:clients4.google.com:443 
2019/06/11 12:38:34 tcp:127.0.0.1:49404 accepted tcp:mtalk.google.com:443 
2019/06/11 12:38:34 tcp:127.0.0.1:49407 accepted tcp:74.125.203.188:443 
2019/06/11 12:38:41 tcp:127.0.0.1:49412 accepted tcp:clients4.google.com:443 
2019/06/11 12:38:41 tcp:127.0.0.1:49414 accepted tcp:clients4.google.com:443 
2019/06/11 12:39:57 tcp:127.0.0.1:49460 accepted tcp:www.googleapis.com:443 
2019/06/11 12:39:57 tcp:127.0.0.1:49461 accepted tcp:www.google.com:443 
2019/06/11 12:39:58 tcp:127.0.0.1:49464 accepted tcp:www.google.com:443 
2019/06/11 12:39:58 tcp:127.0.0.1:49466 accepted tcp:www.googleapis.com:443 
2019/06/11 12:39:58 tcp:127.0.0.1:49468 accepted tcp:www.google.com:443 
2019/06/11 12:39:59 tcp:127.0.0.1:49475 accepted tcp:www.googleapis.com:443 
2019/06/11 12:40:00 tcp:127.0.0.1:49479 accepted tcp:www.googleapis.com:443 
2019/06/11 12:40:03 tcp:127.0.0.1:49488 accepted tcp:www.googleapis.com:443 
2019/06/11 12:40:03 tcp:127.0.0.1:49491 accepted tcp:www.googleapis.com:443 
2019/06/11 12:40:08 tcp:127.0.0.1:49505 accepted tcp:www.googleapis.com:443 
2019/06/11 12:40:08 tcp:127.0.0.1:49510 accepted tcp:www.googleapis.com:443 
2019/06/11 12:40:17 tcp:127.0.0.1:49518 accepted tcp:www.googleapis.com:443 
2019/06/11 12:40:18 tcp:127.0.0.1:49520 accepted tcp:www.googleapis.com:443 
2019/06/11 12:40:33 tcp:127.0.0.1:49531 accepted tcp:clients4.google.com:443 
2019/06/11 12:40:34 tcp:127.0.0.1:49533 accepted tcp:clients4.google.com:443 
2019/06/11 12:40:35 tcp:127.0.0.1:49536 accepted tcp:www.googleapis.com:443 
2019/06/11 12:40:35 tcp:127.0.0.1:49538 accepted tcp:www.googleapis.com:443 
2019/06/11 12:41:11 tcp:127.0.0.1:49561 accepted tcp:mtalk.google.com:443 
2019/06/11 12:41:11 tcp:127.0.0.1:49564 accepted tcp:74.125.203.188:443 
2019/06/11 12:41:38 tcp:127.0.0.1:49581 accepted tcp:clients4.google.com:443 
2019/06/11 12:41:39 tcp:127.0.0.1:49583 accepted tcp:clients4.google.com:443 

error log是空的

**Comment by johnrosen1** [comment]
{
				"type": "field",
				"inboundTag": [
					"in"
				],
				"outboundTag": "out"
			},
