### ISSUE TITLE
nginx想通过unix socket来传数据给v2ray，但v2ray的dsSettings无效

### ISSUE THREAD

**Issue by xiebruce** [v2ray/discussion#255]
在[DomainSocket 传输方式](https://www.v2ray.com/chapter_02/transport/domainsocket.html)中看到可以监听本地socket，我就这么写了，`/var/tmp/`目录肯定是存在的，Linux都有这个目录，而`/var/tmp/v2ray-ws.sock`是不存在的，我修改配置后重启，能正常重启，说明这个配置是没问题的，但是却没有生成`/var/tmp/v2ray-ws.sock`文件，我用root启动的v2ray，所以不存在没有权限的问题吧？请问是我哪里弄的有问题还是这是bug？有人用过这个吗？理论上unix socket比环回网卡(127.0.0.1)+端口的方式会快那么一点的，所以我想用这种方式来接收nginx转发过来的请求：
```
"streamSettings": {
    "network": "ws",
    "wsSettings": {
        "path": "/youcannotfindme"
    },
    "dsSettings": {
        "path": "/var/tmp/v2ray-ws.sock"
    }
}
```

**Comment by tjLEIIQM3** [comment]
ds是流协议，所以"network"应该设置为"domainsocket"而不是"ws"。

顺带回答你将要问的另一个问题：不能。

**Comment by xiebruce** [comment]
@tjLEIIQM3 试了改成domainsocket，已经生成`v2ray-ws.sock`文件了，nginx用以下方式，果然不行哈哈，因为感觉能监听ip的就能监听unix socket的呀，像mysql、redis什么的，都可以通过unix socket来连接的，所以以为这个也可以，是这个“network”指定为`domainsocket`后，就无法指定传过来的请求是`websocket`，所以不能正确解析请求对吗？也不会按ws协议的格式返回数据咯？可是这样的话，domainsocket有什么用呢？tcp的时候就可以是吗？“network”指定为`domainsocket`后，虽然也无法再指定tcp，但会默认为tcp对吗？

```
upstream v2ray_ws {
    server unix:/var/tmp/v2ray-ws.sock;
}

server {
    ……

    location /abcd {
        ……
        proxy_pass http://v2ray_ws;
        ……
    }

    ……
}
```

**Comment by tjLEIIQM3** [comment]
[v2ray-core issue 1204](https://github.com/v2ray/v2ray-core/issues/1204)
我也搞不懂为什么domain socket这样设计，明明是in(out)bound层的东西，却放到了流协议。
这个要开发者才能回答你的问题了。

**Comment by xiebruce** [comment]
@tjLEIIQM3 没事，至少我已经知道了，是没有这个功能而不是我配置有问题

**Comment by cpdyj** [comment]
环路地址这个东西应该都有fastpath吧，怕不是unix socket提高了一点点性能，配置麻烦了一大堆

**Comment by xiebruce** [comment]
@cpdyj 不知道啊，你知道怎么用吗？文档里没提到过fastpath，或者是我没找到？

**Comment by cpdyj** [comment]
@xiebruce 我那意思是Linux似乎会针对127.0.0.1这个特殊地址特殊处理，性能不会差太多

**Comment by xiebruce** [comment]
@cpdyj 哦，到底差多少我也不知道，但肯定有差的，因为一直以来都听说是unix domain socket比较快，除非不在一台机上

**Comment by 70599** [comment]
@xiebruce 
你这个地方不是应该这样写？
```
upstream v2ray_ws {
    server unix:/var/tmp/v2ray-ws.sock;
}

server {
    ……
    location /abcd {
        ……
        proxy_pass v2ray_ws;
        ……
    }
    ……
}

```

个人没有在用domainsocket，所以就不做测试了。
（不过还是期待你测试完回复）

**Comment by xiebruce** [comment]
@70599 nginx是可以这样写，但需要v2ray那边支持啊，但现在就是不支持这种方式，所以nginx无法通过sock文件传数据的方式传过去，只能走环回网卡(127.0.0.1)，即nginx里用`proxy_pass http://127.0.0.1:32858;`这种方式来反代过去

**Comment by madobet** [comment]
> @xiebruce
> 你这个地方不是应该这样写？
> 
> ```
> upstream v2ray_ws {
>     server unix:/var/tmp/v2ray-ws.sock;
> }
> 
> server {
>     ……
>     location /abcd {
>         ……
>         proxy_pass v2ray_ws;
>         ……
>     }
>     ……
> }
> ```
> 
> 个人没有在用domainsocket，所以就不做测试了。
> （不过还是期待你测试完回复）

你这样写可以运行，但因为像前几层说的，ds 和 websocket 被设计在同一层，导致 ds 和 nginx 通信传输的只是没有包装过的 raw vmess 数据，客户端如果 network 是 ws，那么 nginx 给你的这个 raw 数据没法用，如果是 ds 那根本没法直接接收数据。

所以要么有某种办法把服务端 inbound 的 ds 再内部转给 inbound 的 ws，要么客户端接收数据前要套一层 Nginx？

**Comment by 70599** [comment]
@madobet 感谢解释，大致意思明白了。
感觉好复杂啊。

**Comment by aszswaz** [comment]
我有一个猜测，可能不是v2ray不支持unix domian socket，而是ningx发送到socket文件的内容不符合http代理协议。
标准的HTTP协议起始行：GET / HTTP/1.1
HTTP代理的协议起始行：GET http://example.com:8080/ HTTP/1.1
example.com为目标服务器域名
如果是HTTPS的流量代理：CONNECT example.com:443 HTTP/1.1
不过我只是会ningx的常用配置，这方面的功能没有用过，我的建议是自己手动写个程序，看看nginx发送的协议报头是什么。然后再根据这个去配置nginx
