### ISSUE TITLE
caddy ws代理

### ISSUE THREAD

**Issue by chummumm** [v2ray/discussion#256]
为什么我用caddy搭配ws代理v2ray以后service caddy status有很多error: use of closed network connection.

**Comment by beckball** [comment]
贴上caddy配置文件

**Comment by chummumm** [comment]
my domain
{
  root /var/WebPage
  timeouts 5m
  gzip
  index index
  log /var/log/caddy.log
  tls myemailaddress@qq.com
  proxy /pan  localhost:port1 localhost:port2 {
    websocket
    header_upstream -Origin
 }
}

**Comment by gorquan** [comment]
同样 我也遇到了这个问题

**Comment by lniwn** [comment]
我的配置跟你的差不多，也是报同样的错误。

> Jul 27 16:17:50 izj6c0sfak5abm6jb80xj7z caddy[1037]: 2019/07/27 16:17:50 [ERROR] failed to copy buffer:  read tcp 127.0.0.1:38562->127.0.0.1:5281: use of closed network connection
Jul 27 16:19:54 izj6c0sfak5abm6jb80xj7z caddy[1037]: 2019/07/27 16:19:54 [ERROR] failed to copy buffer:  readfrom tcp 127.0.0.1:38546->127.0.0.1:5281: read tcp 172.17.45.134:443->x.x.x.x:49979: read: connection reset by peer
Jul 27 16:19:54 izj6c0sfak5abm6jb80xj7z caddy[1037]: 2019/07/27 16:19:54 [ERROR] failed to copy buffer:  read tcp 127.0.0.1:38546->127.0.0.1:5281: use of closed network connection

**Comment by fcying** [comment]
我也有很多127.0.0.1的这种.....配置里面已经把127.0.0.1 设成直连了啊?

**Comment by coaens** [comment]
我这里也是，出现很多这样的 error 提示，有没有大佬知道怎么解决

**Comment by MatcherAny** [comment]
同样有着问题

**Comment by lyq1996** [comment]
+1 同样问题

**Comment by sonifly** [comment]
+1

**Comment by cudaying** [comment]
+1

**Comment by chamboin** [comment]
有人知道吗？虽然不影响用

**Comment by oceanchang** [comment]
+1

**Comment by i-love-tadpole** [comment]
++++++++1

**Comment by i-love-tadpole** [comment]
> 贴上caddy配置文件

有后续吗

**Comment by chummumm** [comment]
> 贴上caddy配置文件

没了，我已经换nginx了，没这问题

**Comment by fcying** [comment]
> > 贴上caddy配置文件
> 
> 没了，我已经换nginx了，没这问题

换nginx会更稳吗? 差不多就懒得换了.....这个log 看起来也没影响功能...

**Comment by willww64** [comment]
> > > 贴上caddy配置文件
> > 
> > 
> > 没了，我已经换nginx了，没这问题
> 
> 换nginx会更稳吗?

我换 nginx 后稳了很多，暂时没这个报错了。

**Comment by befantasy** [comment]
也遇到了这个问题。。。折腾了好久解决不了。
影响主要是速度上不去。

**Comment by chacha20** [comment]
我的也是这个问题，每分钟出来好多。
caddy[14184]: [ERROR] failed to copy buffer:  read tcp 127.0.0.1:43904->127.0.0.1:65200: use of closed network connection

**Comment by befantasy** [comment]
搜到一个类似的，是说添加一个timeout来解决这个问题。

{
  log ./caddy.log
  proxy /ws 172.17.0.2:80 {
    websocket
    header_upstream -Origin
    timeout 10m # to increase this time
  }
}
https://github.com/caddyserver/caddy/issues/2783

**Comment by fcying** [comment]
> 搜到一个类似的，是说添加一个timeout来解决这个问题。
> 
> {
> log ./caddy.log
> proxy /ws 172.17.0.2:80 {
> websocket
> header_upstream -Origin
> timeout 10m # to increase this time
> }
> }
> [caddyserver/caddy#2783](https://github.com/caddyserver/caddy/issues/2783)

试了改到30m 了, 还是不行....还是有挺多的....

**Comment by befantasy** [comment]
我在另外一台服务器上用nginx确实没看到类似的报错。但因为是不同设备，不同网络，也不好得出结论。

猜测这个会不会和MTU或者GFW有关？

**Comment by phlinhng** [comment]
我設置`timeouts none`之後，報錯還是存在，但是速度的確提升了
原本設置`timeouts {idle 5m}`時，同樣客戶端的下載速度在20Mbps左右；設置為`none`時下載速度提升到35Mbps

**Comment by fcying** [comment]
> 
> 
> 我設置`timeouts none`之後，報錯還是存在，但是速度的確提升了
> 原本設置`timeouts {idle 5m}`時，同樣客戶端的下載速度在20Mbps左右；設置為`none`時下載速度提升到35Mbps

这个是设置在哪的? 和前面说的timeout 看着不一样?

**Comment by phlinhng** [comment]
> > 我設置`timeouts none`之後，報錯還是存在，但是速度的確提升了
> > 原本設置`timeouts {idle 5m}`時，同樣客戶端的下載速度在20Mbps左右；設置為`none`時下載速度提升到35Mbps
> 
> 这个是设置在哪的? 和前面说的timeout 看着不一样?

設置在Caddyfile裡
```golang
yourdomain {
    gzip
    timeouts none
    proxy /path localhost:23333 {
        websocket
    }
    tls abc@example.com
}
```

**Comment by befantasy** [comment]
> > 我設置`timeouts none`之後，報錯還是存在，但是速度的確提升了
> > 原本設置`timeouts {idle 5m}`時，同樣客戶端的下載速度在20Mbps左右；設置為`none`時下載速度提升到35Mbps
> 
> 这个是设置在哪的? 和前面说的timeout 看着不一样?

前面我引用的那个issue里好像写错了。正确的应该是楼上说的timeouts而不是timeout

You can also configure each timeout individually:

```
timeouts {
	read   val
	header val
	write  val
	idle   val
}
```
https://caddyserver.com/v1/docs/timeouts

**Comment by befantasy** [comment]
> 我設置`timeouts none`之後，報錯還是存在，但是速度的確提升了
> 原本設置`timeouts {idle 5m}`時，同樣客戶端的下載速度在20Mbps左右；設置為`none`時下載速度提升到35Mbps

确定吗？ 回头我也试试。

**Comment by phlinhng** [comment]
> > 我設置`timeouts none`之後，報錯還是存在，但是速度的確提升了
> > 原本設置`timeouts {idle 5m}`時，同樣客戶端的下載速度在20Mbps左右；設置為`none`時下載速度提升到35Mbps
> 
> 确定吗？ 回头我也试试。

確定的 我用的客戶端是Shadowrocket + Wifi + 70M家寬
試過不同的寬帶，在這個組合下ws+tls+web的最高speedtest速度都是寬帶最高速的一半左右，這是手機客戶端的限制，實際提升效果可能更大
`timeouts none`用電腦clash+ Wifi + 70M家寬的話可以跑到60M（調整前忘了測，這是調整後）

雖然沒有嚴謹比對調整前後，但是設了`timeouts none`的節點在電腦上可以發揮家寬接近九成的速度，代表這樣設置對速度提升有利無害。

**Comment by befantasy** [comment]
> > > 我設置`timeouts none`之後，報錯還是存在，但是速度的確提升了
> > > 原本設置`timeouts {idle 5m}`時，同樣客戶端的下載速度在20Mbps左右；設置為`none`時下載速度提升到35Mbps
> > 
> > 
> > 确定吗？ 回头我也试试。
> 
> 確定的 我用的客戶端是Shadowrocket + Wifi + 70M家寬
> 試過不同的寬帶，在這個組合下ws+tls+web的最高speedtest速度都是寬帶最高速的一半左右，這是手機客戶端的限制，實際提升效果可能更大
> `timeouts none`用電腦clash+ Wifi + 70M家寬的話可以跑到60M（調整前忘了測電腦，這是調整後）
> 
> 雖然沒有嚴謹比對調整前後，但是設了`timeouts none`的節點在電腦上可以發揮家寬接近九成的速度，代表這樣設置對速度提升有利無害。

可是从理论上来说，这个timeouts如果原来默认是秒级的，改成none或者改大能提升速率可以理解。
可原来是5分钟，speedtest的测试过程都到不了5分钟。按说不应该会有影响的。

而且还有一个问题，如果改成none了，那是不是永远不会timeout？时间长了，会不会有很多无用连接活动着，占用系统资源？导致内存占满等情况呀？

**Comment by phlinhng** [comment]
> > > > 我設置`timeouts none`之後，報錯還是存在，但是速度的確提升了
> > > > 原本設置`timeouts {idle 5m}`時，同樣客戶端的下載速度在20Mbps左右；設置為`none`時下載速度提升到35Mbps
> > > 
> > > 
> > > 确定吗？ 回头我也试试。
> > 
> > 
> > 確定的 我用的客戶端是Shadowrocket + Wifi + 70M家寬
> > 試過不同的寬帶，在這個組合下ws+tls+web的最高speedtest速度都是寬帶最高速的一半左右，這是手機客戶端的限制，實際提升效果可能更大
> > `timeouts none`用電腦clash+ Wifi + 70M家寬的話可以跑到60M（調整前忘了測電腦，這是調整後）
> > 雖然沒有嚴謹比對調整前後，但是設了`timeouts none`的節點在電腦上可以發揮家寬接近九成的速度，代表這樣設置對速度提升有利無害。
> 
> 可是从理论上来说，这个timeouts如果原来默认是秒级的，改成none或者改大能提升速率可以理解。
> 可原来是5分钟，speedtest的测试过程都到不了5分钟。按说不应该会有影响的。
> 
> 而且还有一个问题，如果改成none了，那是不是永远不会timeout？时间长了，会不会有很多无用连接活动着，占用系统资源？导致内存占满等情况呀？

我原來的`timeouts {idle 5m}`只是為了防止cloudflare一直與我服務器建立連接而浪費太多Caddy內存，和`timeouts 5m`不一樣，也和v2Ray無關。在`timeouts {idle 5m}`時，read、header和write的timeout時間仍然是默認的值。我的猜測是，v2Ray會複用一個session好幾次，如果timeouts太短的話，會造成session過早被Caddy關閉而無法複用，這樣吞吐量就會降低，速度也會被限制。如果session用完了，v2Ray會主動關閉無用連接並釋放內存，所以不會造成無用連接占滿內存的情形。

**Comment by befantasy** [comment]
> > > > > 我設置`timeouts none`之後，報錯還是存在，但是速度的確提升了
> > > > > 原本設置`timeouts {idle 5m}`時，同樣客戶端的下載速度在20Mbps左右；設置為`none`時下載速度提升到35Mbps
> > > > 
> > > > 
> > > > 确定吗？ 回头我也试试。
> > > 
> > > 
> > > 確定的 我用的客戶端是Shadowrocket + Wifi + 70M家寬
> > > 試過不同的寬帶，在這個組合下ws+tls+web的最高speedtest速度都是寬帶最高速的一半左右，這是手機客戶端的限制，實際提升效果可能更大
> > > `timeouts none`用電腦clash+ Wifi + 70M家寬的話可以跑到60M（調整前忘了測電腦，這是調整後）
> > > 雖然沒有嚴謹比對調整前後，但是設了`timeouts none`的節點在電腦上可以發揮家寬接近九成的速度，代表這樣設置對速度提升有利無害。
> > 
> > 
> > 可是从理论上来说，这个timeouts如果原来默认是秒级的，改成none或者改大能提升速率可以理解。
> > 可原来是5分钟，speedtest的测试过程都到不了5分钟。按说不应该会有影响的。
> > 而且还有一个问题，如果改成none了，那是不是永远不会timeout？时间长了，会不会有很多无用连接活动着，占用系统资源？导致内存占满等情况呀？
> 
> 我原來的`timeouts {idle 5m}`只是為了防止cloudflare一直與我服務器建立連接而浪費太多Caddy內存，和`timeouts 5m`不一樣，也和v2Ray無關。在`timeouts {idle 5m}`時，read、header和write的timeout時間仍然是默認的值。我的猜測是，v2Ray會複用一個session好幾次，如果timeouts太短的話，會造成session過早被Caddy關閉而無法複用，這樣吞吐量就會降低，速度也會被限制。如果session用完了，v2Ray會主動關閉無用連接並釋放內存，所以不會造成無用連接占滿內存的情形。

这么解释就非常清楚了，谢谢楼主。我现在是4G上网，带宽不足，不具备测试条件，回头有条件了测试一下再来汇报。

**Comment by joyoner** [comment]
同样的问题。

**Comment by fcying** [comment]
caddy 2 有人测试过吗? 有这个问题吗?

**Comment by phlinhng** [comment]
> caddy 2 有人测试过吗? 有这个问题吗?

沒有建站需求的話，可以直接用 [TLS分流器](https://github.com/liberal-boy/tls-shunt-proxy)來實現 WSS+WEB，應該是目前性能最好的方案。

**Comment by GleenJi** [comment]
一样的问题，不知道有大佬知道怎么回事么，[ERROR] Failed to cpoy buffer: readfrom tcp 127.0.0.1:端口号->127.0.0.1:端口号 use of closed network connection
虽然出现这些并不影响正常使用，不过不知道这是什么原因造成的

**Comment by GleenJi** [comment]
> 
> 
> 一样的问题，不知道有大佬知道怎么回事么，[ERROR] Failed to cpoy buffer: readfrom tcp 127.0.0.1:端口号->127.0.0.1:端口号 use of closed network connection
> 虽然出现这些并不影响正常使用，不过不知道这是什么原因造成的

好像解决了，我后来把caddy用root用户和root组来运行，caddy.service中的user和group都改成root，然后就没有这种现象了

**Comment by GleenJi** [comment]
> 
> 
> > 一样的问题，不知道有大佬知道怎么回事么，[ERROR] Failed to cpoy buffer: readfrom tcp 127.0.0.1:端口号->127.0.0.1:端口号 use of closed network connection
> > 虽然出现这些并不影响正常使用，不过不知道这是什么原因造成的
> 
> 好像解决了，我后来把caddy用root用户和root组来运行，caddy.service中的user和group都改成root，然后就没有这种现象了

不是没有这种现象，只是当我真的上不了gg或者ytb才会出现这种[ERROR]，不像以前即使能上gg或者ytb也会出现这种现象

**Comment by WenponWoo** [comment]
mark
