### ISSUE TITLE
V2ray在ubuntu14.04下编译失败

### ISSUE THREAD

**Issue by dinglingling4427** [v2ray/discussion#257]
按照https://www.v2ray.com/developer/intro/compile.html的指导
在执行bazel build --action_env=GOPATH=$GOPATH --action_env=PATH=$PATH //release:v2ray_linux_amd64_package时候提示错误

ERROR: /home/eyas/go/src/v2ray.com/core/release/BUILD:150:1: in pkg_zip rule //release:v2ray_linux_amd64_package: 
Traceback (most recent call last):
	File "/home/newuser/go/src/v2ray.com/core/release/BUILD", line 150
		pkg_zip(name = 'v2ray_linux_amd64_package')
	File "/home/newuser/go/src/v2ray.com/core/infra/bazel/zip.bzl", line 51, in _zip_file
		srcs += ctx.files.srcs
`+` operator on a depset is forbidden. See https://docs.bazel.build/versions/master/skylark/depsets.html for recommendations. Use --incompatible_depset_union=false to temporarily disable this check.
ERROR: Analysis of target '//release:v2ray_linux_amd64_package' failed; build aborted: Analysis of target '//release:v2ray_linux_amd64_package' failed; build aborted
INFO: Elapsed time: 0.521s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (6 packages loaded, 35 targets configured)

**Comment by kslr** [comment]
后来修复了这个问题
