### ISSUE TITLE
quic 的两个疑问

### ISSUE THREAD

**Issue by choicky** [v2ray/discussion#258]
疑问1：如何关闭 VMess的加密？

官网提到 在使用 QUIC 传输时，可以关闭 VMess 的加密，那么，如何关闭 VMess的加密呢？

疑问2：已经 tls 了还需要加密吗？

官网提到 为了避免被探测，建议加密或伪装至少开启一项，但是，官网有已经提到 QUIC 强制要求开启 TLS，为什么已经启用了 tls 还需要 quic 加密或者伪装呢？

**Comment by kxmp** [comment]
客户端配置加密none就行了
开加密是因为如果被中间人的话 看到明文那样就不好了.
