### ISSUE TITLE
bind: address already in use

### ISSUE THREAD

**Issue by MonsterEdward** [v2ray/discussion#259]
全新vps(ubuntu 16.04，Linux vds-342752 4.15.0-51-generic)，使用wget https://install.direct/go.sh脚本安装(v2ray版本为 4.19.1 )，并按官方配置(https://toutyrater.github.io/advanced/wss_and_web.html)，配好server，并/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json检测，

root@vds-342752:/etc/v2ray# /usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json
V2Ray 4.19.1 (Let's Fly) Custom
A unified platform for anti-censorship.
Configuration OK.

server正常运行，日志(debug模式)：
2019/06/15 07:45:37 [Debug] v2ray.com/core/app/log: Logger started
2019/06/15 07:45:37 [Warning] v2ray.com/core: V2Ray 4.19.1 started

service v2ray status显示：

v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-06-15 07:45:37 CEST; 8min ago
 Main PID: 2092 (v2ray)
    Tasks: 7 (limit: 1130)
   CGroup: /system.slice/v2ray.service
           `-2092 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

但，实际v2ray未正常运行。

/usr/bin/v2ray/v2ray log或/usr/bin/v2ray/v2ray info：

V2Ray 4.19.1 (Let's Fly) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 10086 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:10086 > v2ray.com/core/transport/internet/websocket: failed to listen TCP on127.0.0.1:10086 > listen tcp 127.0.0.1:10086: bind: address already in use

但其实，只有v2ray在用此端口：

root@vds-342752:/etc/v2ray# lsof -i:10086
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
v2ray   2092 root    3u  IPv4 606720      0t0  TCP localhost:10086 (LISTEN)

没有其他进程使用此端口。但v2ray就是无法正常运行。

**Comment by beckball** [comment]
ps -A. 查看进程

**Comment by MonsterEdward** [comment]
root@vds-342752:~# ps -ef | grep v2ray
root      2092     1  0 07:45 ?        00:00:13 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
root      3915  3876  0 12:17 pts/0    00:00:00 grep --color=auto v2ray


root@vds-342752:~# ps -A
  PID TTY          TIME CMD
    1 ?        00:00:35 systemd
    2 ?        00:00:00 kthreadd
    4 ?        00:00:00 kworker/0:0H
    6 ?        00:00:00 mm_percpu_wq
    7 ?        00:22:06 ksoftirqd/0
    8 ?        00:20:42 rcu_sched
    9 ?        00:00:00 rcu_bh
   10 ?        00:00:00 migration/0
   11 ?        00:00:01 watchdog/0
   12 ?        00:00:00 cpuhp/0
   13 ?        00:00:00 kdevtmpfs
   14 ?        00:00:00 netns
   15 ?        00:00:00 rcu_tasks_kthre
   16 ?        00:00:00 kauditd
   17 ?        00:00:00 khungtaskd
   18 ?        00:00:00 oom_reaper
   19 ?        00:00:00 writeback
   20 ?        00:00:00 kcompactd0
   21 ?        00:00:00 ksmd
   22 ?        00:00:00 khugepaged
   23 ?        00:00:00 crypto
   24 ?        00:00:00 kintegrityd
   25 ?        00:00:00 kblockd
   26 ?        00:00:00 ata_sff
   27 ?        00:00:00 md
   28 ?        00:00:00 edac-poller
   29 ?        00:00:00 devfreq_wq
   30 ?        00:00:00 watchdogd
   34 ?        00:00:00 kswapd0
   35 ?        00:00:00 kworker/u3:0
   36 ?        00:00:00 ecryptfs-kthrea
   78 ?        00:00:00 kthrotld
   79 ?        00:00:00 acpi_thermal_pm
   80 ?        00:00:00 scsi_eh_0
   81 ?        00:00:00 scsi_tmf_0
   82 ?        00:00:00 scsi_eh_1
   83 ?        00:00:00 scsi_tmf_1
   89 ?        00:00:00 ipv6_addrconf
   98 ?        00:00:00 kstrp
  115 ?        00:00:00 charger_manager
  138 ?        00:00:00 kworker/0:2
  152 ?        00:00:08 kworker/0:1H
  172 ?        00:00:06 jbd2/vda2-8
  173 ?        00:00:00 ext4-rsv-conver
  210 ?        00:01:20 systemd-journal
  227 ?        00:00:00 systemd-udevd
  292 ?        00:00:01 systemd-resolve
  294 ?        00:00:00 systemd-timesyn
  299 ?        00:00:15 rsyslogd
  302 ?        00:00:23 dbus-daemon
  308 ?        00:00:01 systemd-logind
  310 ?        00:00:24 accounts-daemon
  311 ?        00:00:00 networkd-dispat
  312 ?        00:00:00 cron
  333 ?        00:00:00 ttm_swap
  437 tty1     00:00:00 agetty
  438 ?        00:00:13 sshd
 2016 ?        00:00:00 nginx
 2018 ?        00:00:00 nginx
 2092 ?        00:00:13 v2ray
 3765 ?        00:00:00 kworker/u2:1
 3808 ?        00:00:00 kworker/u2:0
 3832 ?        00:00:00 sshd
 3834 ?        00:00:00 systemd
 3835 ?        00:00:00 (sd-pam)
 3876 pts/0    00:00:00 bash
 3899 ?        00:00:00 sshd
 3900 ?        00:00:00 sshd
 3903 pts/0    00:00:00 ps
21095 ?        00:00:05 kworker/0:0


root@vds-342752:~# service v2ray status
* v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-06-15 07:45:37 CEST; 4h 34min ago
 Main PID: 2092 (v2ray)
    Tasks: 8 (limit: 1130)
   CGroup: /system.slice/v2ray.service
           `-2092 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

Jun 15 07:45:37 vds-342752 systemd[1]: Started V2Ray Service.
Jun 15 07:45:37 vds-342752 v2ray[2092]: V2Ray 4.19.1 (Let's Fly) Custom
Jun 15 07:45:37 vds-342752 v2ray[2092]: A unified platform for anti-censorship.


root@vds-342752:/etc/v2ray# /usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json
V2Ray 4.19.1 (Let's Fly) Custom
A unified platform for anti-censorship.
Configuration OK.


root@vds-342752:/etc/v2ray# /usr/bin/v2ray/v2ray log
V2Ray 4.19.1 (Let's Fly) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 10086 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:10086 > v2ray.com/core/transport/internet/websocket: failed to listen TCP on127.0.0.1:10086 > listen tcp 127.0.0.1:10086: bind: address already in use


server无法运作，client的配置就不贴了(还没用client去连)：
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "port": 10086,
      "listen":"127.0.0.1",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "8c7d3772-0894-4044-ab6e-e56f2c3902cb",
            "alterId": 64
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
        "path": "/var/www/ray"
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}

**Comment by MonsterEdward** [comment]
nginx配置：

server {
	listen  443 ssl http2;
	ssl on;

	ssl_certificate       /etc/xx/www.abc.com.pem;
	ssl_certificate_key   /etc/xx/www.abc.com.key;
	ssl_protocols         TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers           HIGH:!aNULL:!MD5;

	server_name           www.abc.com;

    access_log  /var/log/nginx/ws.access.log;
    error_log /var/log/nginx/ws.error.log;

    proxy_set_header Host $host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  
	location /var/www/ray {
		proxy_redirect off;
		proxy_pass http://127.0.0.1:10086;
		proxy_http_version 1.1;

		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		#proxy_set_header Host $http_host;

		# Show realip in v2ray access.log
#		proxy_set_header X-Real-IP $remote_addr;
#		proxy_set_header Host $host:$server_port;
#		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}

**Comment by MonsterEdward** [comment]
nginx配置：
server {
	listen  443 ssl http2;
	ssl on;

	ssl_certificate       /etc/xx/www.abc.com.pem;
	ssl_certificate_key   /etc/xx/www.abc.com.key;
	ssl_protocols         TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers           HIGH:!aNULL:!MD5;

	server_name           www.abc.com;

    access_log  /var/log/nginx/ws.access.log;
    error_log /var/log/nginx/ws.error.log;

    proxy_set_header Host $host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  
	location /var/www/ray {
		proxy_redirect off;
		proxy_pass http://127.0.0.1:10086;
		proxy_http_version 1.1;

		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		#proxy_set_header Host $http_host;

		# Show realip in v2ray access.log
		#proxy_set_header X-Real-IP $remote_addr;
		#proxy_set_header Host $host:$server_port;
		#proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}

**Comment by beckball** [comment]
root@vds-342752:/etc/v2ray# /usr/bin/v2ray/v2ray log
V2Ray 4.19.1 (Let's Fly) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 10086 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:10086 > v2ray.com/core/transport/internet/websocket: failed to listen TCP on127.0.0.1:10086 > listen tcp 127.0.0.1:10086: bind: address already in use

从这里看出10086已经被使用 尝试其他端口并在serve做相应更改
Nginx处根据白话文的转发配置会有问题 有一行多余 自行搜索删除
location处的path过于长 只需要一个即可 例如/qwerty serve同步修改 并不需要填写前端网页的绝对路径

**Comment by MonsterEdward** [comment]
root@vds-342752:/etc/v2ray# /usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json
V2Ray 4.19.1 (Let's Fly) Custom
A unified platform for anti-censorship.
Configuration OK.

root@vds-342752:/etc/v2ray# service v2ray start

root@vds-342752:/etc/v2ray# /usr/bin/v2ray/v2ray log
V2Ray 4.19.1 (Let's Fly) Custom
A unified platform for anti-censorship.
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 9510 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:9510 > v2ray.com/core/transport/internet/websocket: failed to listen TCP on127.0.0.1:9510 > listen tcp 127.0.0.1:9510: bind: address already in use


问题是，每新选一个未使用也未被其他进程占用的端口v2ray启动后都是这样的，/usr/bin/v2ray/v2ray log就会显示已bind。在/var/log/v2ray内的log无价值，/var/log/nginx内的log也无价值。卸载干净，按官方安装脚本重安装，仍是相同错误：bind: address already in use。但使用lsof -i:port，除v2ray并无其他进制占用此端口。实质上，v2ray server根本没用正常运行。

server配置：
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "port": 9510,
      "listen":"127.0.0.1",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "8c7d3772-0894-4044-ab6e-e56f2c3902cb",
            "alterId": 64
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
        "path": "/ray"
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}

**Comment by beckball** [comment]
netstat  -lntup查看一下端口
既然status已显示running 为何不尝试在客户端配置后从客户端查看log？

**Comment by MonsterEdward** [comment]
因为client的二进制程序一运行(在firefox设置好代理，并尝试访问website)，就会记log(debug模式)，而且即使kill了server(client此时无法连上server)，记的log的内容，前后，未有实质变化，所以认为v2ray server根本未运行，虽service v2ray status显示其active，ps -A能看到v2ray的进程。但，应该没正常运作。


2019/06/15 20:58:39 [Info] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 37 but actually 180
2019/06/15 20:58:39 [Info] v2ray.com/core/transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe

**Comment by MonsterEdward** [comment]
root@vds-342752:/etc/nginx/sites-available# netstat -lntup     
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      4947/nginx: master  
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      292/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      438/sshd            
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      3832/sshd: root@pts 
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      4947/nginx: master  
tcp        0      0 127.0.0.1:6011          0.0.0.0:*               LISTEN      4667/sshd: root@pts 
tcp        0      0 127.0.0.1:9510          0.0.0.0:*               LISTEN      4874/v2ray          
tcp6       0      0 :::80                   :::*                    LISTEN      4947/nginx: master  
tcp6       0      0 :::22                   :::*                    LISTEN      438/sshd            
tcp6       0      0 ::1:6010                :::*                    LISTEN      3832/sshd: root@pts 
tcp6       0      0 ::1:6011                :::*                    LISTEN      4667/sshd: root@pts 
udp        0      0 127.0.0.53:53           0.0.0.0:*                           292/systemd-resolve 
root@vds-342752:/etc/nginx/sites-available# netstat -lntup | grep 9510
tcp        0      0 127.0.0.1:9510          0.0.0.0:*               LISTEN      4874/v2ray

**Comment by beckball** [comment]
从lsmod看出v2已正常运行
至于客户端为何两种没有区别不得而知 没有使用过二进制客户端 无法帮助判断 建议使用带ui客户端 方便配置 同时log也会显示并且报错

**Comment by MonsterEdward** [comment]
thanks a lot，目前无法获取到GUI client(无法fq)，希望可以发我(edwardvewen@163.com)一个GUI client (win 10专业版)。万分感谢！

**Comment by beckball** [comment]
https://send.firefox.com/download/d8cbc5d98d543f1e/#fZiQhhNPNxRT_pNjGbVHAQ
使用参考https://github.com/2dust/v2rayN

**Comment by MonsterEdward** [comment]
2019/06/15 22:07:53 [Info] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 51 but actually 211
2019/06/15 22:07:53 [Info] v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/06/15 22:07:54 [Info] [631303511] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2019/06/15 22:07:54 [Info] [631303511] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe

**Comment by beckball** [comment]
贴上你的客户端配置图

**Comment by MonsterEdward** [comment]
![image](https://user-images.githubusercontent.com/22072869/59552542-fe05e900-8fba-11e9-8317-16958110d8c1.png)

**Comment by beckball** [comment]
Camouflage domain留空
Path填写客户端path

**Comment by MonsterEdward** [comment]
server端无有效log，
下面是client(v2rayN)的配置，此时v2rayN也无log

![image](https://user-images.githubusercontent.com/22072869/59552638-34903380-8fbc-11e9-8bc8-a57045dc9d2b.png)

**Comment by beckball** [comment]
。。
Path是服务端设置的path 不是客户端所在位置
由此看来您对ws+tls理解并不够深 建议您更改其他链接方式 或者 寻找相关一键脚本
就如同白话文所说 步子太大容易扯到x

**Comment by MonsterEdward** [comment]
OK，我来找个一键安装脚本吧，没研究过ws/tls，只是用。

**Comment by beckball** [comment]
参考这里的nginx配置 和 客户端配置填写
https://lala.im/4647.html

**Comment by yuehanwali** [comment]
> 参考这里的nginx配置 和 客户端配置填写
> https://lala.im/4647.html
> 尤其是注意内容
你好，很感谢你的nginx教程，我按你写的成功了，不过端口用的是444，不是443，因为我上面有一个真实的网站，用了443，可能会冲突？不太懂这个。

另外，我想我问下apache2怎么配置tls+websocket上网，我上面也有一个真实的网站，我想同时能打打开网页并用Ttls+websocket上网。

**Comment by yuehanwali** [comment]
> 参考这里的nginx配置 和 客户端配置填写
> https://lala.im/4647.html
> 尤其是注意内容
非常感谢
另外，我想我问下apache2怎么配置tls+websocket上网，我上面也有一个真实的网站，我想同时能打打开网页并用Ttls+websocket上网
