### ISSUE TITLE
v2ray漏dns啊

### ISSUE THREAD

**Issue by k79e** [v2ray/discussion#261]
一句话就是走远程dns查询的时候同时走了客户端的系统dns. 应该所有版本都这样的.)
访问不存在的域名 也会漏一下.
设置下自定义dns 又不漏了.
不设置就开始漏.  这是不是bug啊!!?

只有用路由模式的时候才会这样. 全局不会.
路由我配置的是v2rayn里面的ipifnonmatch 模式是绕过局域网及大陆.

**Comment by kingwilliam** [comment]
`不知这个答案能否解答您的问题, geosite:cn 就问114, 其馀就问1.1.1.1

	"dns": {
		"servers": [
			"1.1.1.1",
			{
				"address": "114.114.114.114",
				"port": 53,
				"domains": ["geosite:cn"]
			}
		]
	},`

**Comment by kxmp** [comment]
@kingwilliam 当然是不能的. 设定dns之后本身就不漏了.
我说的是不配置自定义的时候会漏.

配置自定义之后不按你这样写 实际用起来也是国内的会自动走系统dns.

**Comment by linusdrop** [comment]
可以试试配合AdGuard来用，不过我想知道你是怎么知道又查了一次本地dns的？
https://lala.im/5916.html

**Comment by kxmp** [comment]
我抓包了还能看错不成.
