### ISSUE TITLE
按照新手上路的配置 上不了网

### ISSUE THREAD

**Issue by onhao** [v2ray/discussion#263]
按照 https://www.v2ray.com/chapter_00/start.html 这里的 配置 
客户端 
`{
  "inbounds": [{
    "port": 1080,  // SOCKS 代理端口，在浏览器中需配置代理并指向这个端口
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "udp": true
    }
  }],
  "outbounds": [{
    "protocol": "vmess",
    "settings": {
      "vnext": [{
        "address": "server", // 服务器地址，请修改为你自己的服务器 ip 或域名
        "port": 10086,  // 服务器端口
        "users": [{ "id": "b831381d-6324-4d53-ad4f-8cda48b30811" }]
      }]
    }
  },{
    "protocol": "freedom",
    "tag": "direct",
    "settings": {}
  }],
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [{
      "type": "field",
      "ip": ["geoip:private"],
      "outboundTag": "direct"
    }]
  }
}`
服务端
`{
  "inbounds": [{
    "port": 10086, // 服务器监听端口，必须和上面的一样
    "protocol": "vmess",
    "settings": {
      "clients": [{ "id": "b831381d-6324-4d53-ad4f-8cda48b30811" }]
    }
  }],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  }]
}
`
上不了网
service v2ray status  信息如下：
v2ray[18898]: 2019/06/17 17:30:15 [Warning] [118791836] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 199.193.253.34:10086: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed

2019/06/17 17:30:20 [Warning] [1967898617] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 199.193.253.34:10086: i/o timeout dial tcp 199.193.253.34:10086: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by onhao** [comment]
系统是   ubuntu  18.04

**Comment by onhao** [comment]
服务端 客户端 的版本 都是  V2Ray 4.19.1 (Let's Fly) Custom

**Comment by kslr** [comment]
i/o timeout 检查防火墙

**Comment by Yuhehe** [comment]
把注释都删了试试
