### ISSUE TITLE
gcp 中nginx/caddy反代无法传给v2ray，求大神帮忙看下

### ISSUE THREAD

**Issue by dangelization** [v2ray/discussion#268]
整体配置是一个vmess+ws+真tls+nginx反代+cdn的配置

具体问题是，v2ray客户端可以连接上nginx/caddy，查询nginx的access.log正常，但是反代传到v2ray的端口就没反应了，查询v2ray的access.log就什么都没有。
我这个配置在搬瓦工上就没问题，就是上了google cloud platform就不好使了。
使用浏览器浏览网站页面没有问题，就是说nginx安装运行没问题（除了反代？？）。

v2ray服务端配置：/etc/v2ray/conf.json

{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "debug"
  },
  "inbounds": [
    {
        "port": 58762,
	"listen":"127.0.0.1",
        "protocol": "vmess",
        "settings": {
          "clients": [
            {
              "id": "**********",
              "level": 1,
              "alterId": 64,
              "email": "************"
            }
          ],
		  "disableInsecureEncryption": true
        },
        "streamSettings": {
          "network": "ws",
          "security": "tls",
          "tlsSettings": {
               "serverName": "abc.xy",
               "certificates": [
                   {
                       "usage": "encipherment",
                       "certificateFile": "/etc/v2ray/v2ray.crt",
                       "keyFile": "/etc/v2ray/v2ray.key"
                   }
               ]
           },
          "wsSettings": {
            "path": "/vms"
          }
        }
    }
  ],
  "outbounds": [
    {
        "protocol": "freedom",
        "settings": {}
    },
    {
        "protocol": "blackhole",
        "settings": {},
        "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}

nginx的conf：/etc/nginx/conf.d/mysite.conf

server {
        listen 443 ssl http2;
        ssl on;
        ssl_certificate       /etc/v2ray/v2ray.crt;
        ssl_certificate_key   /etc/v2ray/v2ray.key;
        ssl_protocols         TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers           HIGH:!aNULL:!MD5;
        server_name           abc.xy;
        index index.html index.htm;
        root  /www/;
        error_page 400 = /400.html;
        location /vms
        {
            proxy_redirect off;
            proxy_pass http://127.0.0.1:58762;
            proxy_http_version 1.1;
            proxy_set_header Upgrade \$http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host \$http_host;
        }
}

server {
        listen 80;
        server_name abc.xy www.abc.xy;
        return 301 https://$server_name$request_uri;
}

v2ray的access.log：内容为空
v2ray的error.log：
2019/06/24 20:11:51 [Debug] v2ray.com/core/app/log: Logger started
2019/06/24 20:11:51 [Warning] v2ray.com/core: V2Ray 4.19.1 started

nginx的access.log：
************** - - [24/Jun/2019:20:12:50 +0800] "GET /vms HTTP/1.1" 301 185 "-" "Go-http-client/1.1"
************** - - [24/Jun/2019:20:12:50 +0800] "GET /vms HTTP/1.1" 301 185 "-" "Go-http-client/1.1"
************** - - [24/Jun/2019:20:12:50 +0800] "GET /vms HTTP/1.1" 301 185 "-" "Go-http-client/1.1"
************** - - [24/Jun/2019:20:12:51 +0800] "GET /vms HTTP/1.1" 301 185 "-" "Go-http-client/1.1"
************** - - [24/Jun/2019:20:12:52 +0800] "GET /vms HTTP/1.1" 301 185 "-" "Go-http-client/1.1"
************** - - [24/Jun/2019:20:12:54 +0800] "GET /vms HTTP/1.1" 301 185 "-" "Go-http-client/1.1"

nginx的error.log：空

root@instance-3:/var/log/nginx# iptables -L -n
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

GCP的防火墙rules：
<img width="606" alt="捕获" src="https://user-images.githubusercontent.com/13503950/60020057-ccc7a000-96c1-11e9-8235-0b58a530423f.PNG">

**Comment by kxmp** [comment]
wss的话nginx要改https
proxy_pass **https**://127.0.0.1:58762;

**Comment by kxmp** [comment]
你这个东西配置的自相矛盾
nginx反代走http
v2服务确实wss. 
nginx日志是301 (你在走80访问!!? 跳回443?? 你在搞什么!!)

v2客户端应该直接访问443才对 否则就80 不走tls.

**Comment by dangelization** [comment]
我贴的是v2服务端的config
客户端当然走443

**Comment by kxmp** [comment]
你web日志显示的301跳转 不像是走443

**Comment by dangelization** [comment]
我改成proxy_pass https://127.0.0.1:58762还是一样的问题。

**Comment by kxmp** [comment]
那是因为你问题不止一个.

**Comment by kxmp** [comment]
管他怎样你直接浏览器访问下那个vms不就知道了. 报400就说明接上了
然后v2会有错误日志.

**Comment by dangelization** [comment]
用浏览器 还是301 185，而且v2没有log

2019年6月28日 下午4:31，kxmp <notifications@github.com>写道：

管他怎样你直接浏览器访问下那个vms不就知道了. 报400就说明接上了
然后v2会有错误日志.

**Comment by kxmp** [comment]
浏览器是白页面么 还是什么样的.
浏览器走https 日志还是301的话 而且浏览器看不到400 
那301必须关掉.

**Comment by kingwilliam** [comment]
试试以下设定

参考
https://github.com/v2ray/v2ray-core/issues/1796

Nginx
保留原来设定
proxy_pass http://127.0.0.1:58762;

V2ray
删除 tls, 只保留websocket

**Comment by kxmp** [comment]
tls是没问题的 设定错误服务端会报错 他这个根本接不到流量. nginx显示被跳转 我看他是自己把自己给跳死了吧...

**Comment by fengyeblade** [comment]
V2的配置太复杂了。  既然有nginx  V2 就配置一个最简单的 ws 就行了。 证书  TLS 完全不要。 由NGINX实现完整HTTPS 再通过 location 分流给V2

**Comment by jellycsc** [comment]
@fengyeblade 同意，这样一可以架设个网站，分流做代理；二也减少了V2和nginx之间的ssl证书验证过程，同在一个vps里也不需要流量加密

**Comment by johnrosen1** [comment]
> 整体配置是一个vmess+ws+真tls+nginx反代+cdn的配置
> 
> 具体问题是，v2ray客户端可以连接上nginx/caddy，查询nginx的access.log正常，但是反代传到v2ray的端口就没反应了，查询v2ray的access.log就什么都没有。
> 我这个配置在搬瓦工上就没问题，就是上了google cloud platform就不好使了。
> 使用浏览器浏览网站页面没有问题，就是说nginx安装运行没问题（除了反代？？）。
> 
> v2ray服务端配置：/etc/v2ray/conf.json
> 
> {
> "log" : {
> "access": "/var/log/v2ray/access.log",
> "error": "/var/log/v2ray/error.log",
> "loglevel": "debug"
> },
> "inbounds": [
> {
> "port": 58762,
> "listen":"127.0.0.1",
> "protocol": "vmess",
> "settings": {
> "clients": [
> {
> "id": "**********", "level": 1, "alterId": 64, "email": "************"
> }
> ],
> "disableInsecureEncryption": true
> },
> "streamSettings": {
> "network": "ws",
> "security": "tls",
> "tlsSettings": {
> "serverName": "abc.xy",
> "certificates": [
> {
> "usage": "encipherment",
> "certificateFile": "/etc/v2ray/v2ray.crt",
> "keyFile": "/etc/v2ray/v2ray.key"
> }
> ]
> },
> "wsSettings": {
> "path": "/vms"
> }
> }
> }
> ],
> "outbounds": [
> {
> "protocol": "freedom",
> "settings": {}
> },
> {
> "protocol": "blackhole",
> "settings": {},
> "tag": "blocked"
> }
> ],
> "routing": {
> "strategy": "rules",
> "settings": {
> "rules": [
> {
> "type": "field",
> "ip": [
> "0.0.0.0/8",
> "10.0.0.0/8",
> "100.64.0.0/10",
> "127.0.0.0/8",
> "169.254.0.0/16",
> "172.16.0.0/12",
> "192.0.0.0/24",
> "192.0.2.0/24",
> "192.168.0.0/16",
> "198.18.0.0/15",
> "198.51.100.0/24",
> "203.0.113.0/24",
> "::1/128",
> "fc00::/7",
> "fe80::/10"
> ],
> "outboundTag": "blocked"
> }
> ]
> }
> }
> }
> 
> nginx的conf：/etc/nginx/conf.d/mysite.conf
> 
> server {
> listen 443 ssl http2;
> ssl on;
> ssl_certificate /etc/v2ray/v2ray.crt;
> ssl_certificate_key /etc/v2ray/v2ray.key;
> ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
> ssl_ciphers HIGH:!aNULL:!MD5;
> server_name abc.xy;
> index index.html index.htm;
> root /www/;
> error_page 400 = /400.html;
> location /vms
> {
> proxy_redirect off;
> proxy_pass http://127.0.0.1:58762;
> proxy_http_version 1.1;
> proxy_set_header Upgrade $http_upgrade;
> proxy_set_header Connection "upgrade";
> proxy_set_header Host $http_host;
> }
> }
> 
> server {
> listen 80;
> server_name abc.xy [www.abc.xy](http://www.abc.xy);
> return 301 https://$server_name$request_uri;
> }
> 
> v2ray的access.log：内容为空
> v2ray的error.log：
> 2019/06/24 20:11:51 [Debug] v2ray.com/core/app/log: Logger started
> 2019/06/24 20:11:51 [Warning] v2ray.com/core: V2Ray 4.19.1 started
> 
> nginx的access.log：
> ************** - - [24/Jun/2019:20:12:50 +0800] "GET /vms HTTP/1.1" 301 185 "-" "Go-http-client/1.1"
> ************** - - [24/Jun/2019:20:12:50 +0800] "GET /vms HTTP/1.1" 301 185 "-" "Go-http-client/1.1"
> ************** - - [24/Jun/2019:20:12:50 +0800] "GET /vms HTTP/1.1" 301 185 "-" "Go-http-client/1.1"
> ************** - - [24/Jun/2019:20:12:51 +0800] "GET /vms HTTP/1.1" 301 185 "-" "Go-http-client/1.1"
> ************** - - [24/Jun/2019:20:12:52 +0800] "GET /vms HTTP/1.1" 301 185 "-" "Go-http-client/1.1"
> ************** - - [24/Jun/2019:20:12:54 +0800] "GET /vms HTTP/1.1" 301 185 "-" "Go-http-client/1.1"
> 
> nginx的error.log：空
> 
> root@instance-3:/var/log/nginx# iptables -L -n
> Chain INPUT (policy ACCEPT)
> target prot opt source destination
> 
> Chain FORWARD (policy ACCEPT)
> target prot opt source destination
> ACCEPT all -- 0.0.0.0/0 0.0.0.0/0
> ACCEPT all -- 0.0.0.0/0 0.0.0.0/0
> 
> Chain OUTPUT (policy ACCEPT)
> target prot opt source destination
> 
> GCP的防火墙rules：
> <img alt="捕获" width="606" src="https://user-images.githubusercontent.com/13503950/60020057-ccc7a000-96c1-11e9-8235-0b58a530423f.PNG">

nginx反代tls交给nginx处理，v2不能开tls，请关闭
