### ISSUE TITLE
如何生成二维码

### ISSUE THREAD

**Issue by zhiai0yueru** [v2ray/discussion#269]
安卓端使用v2rayNG, 如何将配置文件生成二维码供手机使用?
v2rayNG 导入config.json 端口识别错误, 并且不能纠正, 于是考虑用二维码

**Comment by bafflingbug** [comment]
v2rayNG用的二维码内容就是分享链接直接保存成二维码。
分享链接的构造参见 [这里](https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2))
