### ISSUE TITLE
使用tls作为传输加密时vmess是否还需要设置加密？

### ISSUE THREAD

**Issue by starP-W** [v2ray/discussion#270]
现在使用caddy+tls+ws的方式作为传输手段，由于路由器性能比较弱，故想减少加密解密时带来的性能损耗，而且在官方的QUIC教程中提到
>在使用 QUIC 传输时，可以关闭 VMess 的加密。

 这是否意味着在使用TLS作为传输加密时可以关闭vmess本身的加密？

**Comment by nicholascw** [comment]
原理上来说是这样的。
