### ISSUE TITLE
多路复用容量没满就建立新连接

### ISSUE THREAD

**Issue by k79e** [v2ray/discussion#272]
你们有那个情况么.
设定50. 然后开几个页面发现连接变2个了.
netstat过滤浏览器到v2的连接 看了下根本没到50.
(真说夸张了 程序连接到本地v2的连接数直接x2 都没把容量打满)

反正设定多少都是会那样. 比如默认的8.

请问timewait也算占用的连接么? 这个算的话那估计是满了.

**Comment by kxmp** [comment]
我设定的80并发又被打满了... 
发现的时候目前包括closewait只有50多个. (x2才50个)

**Comment by kslr** [comment]
disable mux
