### ISSUE TITLE
疑似bug 多路复用老连接非常慢

### ISSUE THREAD

**Issue by k79e** [v2ray/discussion#277]
测试丢包没什么问题. 服务器就是不发包. 但是载入同服务器其他资源却速度飞快. 证明丢包没什么问题.

测试具体过程就是 最好让测速图(大小适中 根据每个人网速不同 大小也不同 这个图最好是不可以秒开 或者仅仅在网络极其好的情况下才能秒开)
这个测速图建立了第一个连接 然后干些其他事情 让这个连接始终不断.
比如浏览器chrome有书签同步 而且他还有病 总喜欢访问mtalk那个域名. 这样多路复用的第一个连接绝对不会断开 长时间挂浏览器可以保证这个 多路复用的连接 是长连接 非常老.
然后后面测试会发现速度极慢. 我的确定性是100% 绝对不是丢包问题. 就是服务器不发包. 
访问同服务器资源 速度飞快 但是很麻烦 因为这个资源还可能走老连接.
我用了其他办法确定了网络层决无丢包. 于是我想到了这个多路复用. 然后其他人好像也提到过这个有时候会让网速非常慢??
我concurrency配置的是8. 也不大. 看起来跟大小没什么关系. 使用的是tcp模式.
我记得有人说他200 然后怎么怎么样 速度变卡了 我现在也遇到问题 但是是8. 所以这可能是多路复用的问题. 

我的连接时间是5-6小时. 3小时的时候 速度还很快. 
现在又不卡了 不知道是不是那个连接关闭了. 刚才测试的时候可是各种刷都速度很慢.

**Comment by kslr** [comment]
disable mux
