### ISSUE TITLE
linux上的文件位置不合理

### ISSUE THREAD

**Issue by veekxt** [v2ray/discussion#28]
我觉得，把v2ray和v2ctl放入/usr/bin，dat文件放入/usr/share 什么的更好一些。

主要问题在于v2ray安装完之后不在path里。

**Comment by InoriHeart** [comment]
https://www.archlinux.org/packages/community/x86_64/v2ray/files/

Arch 这边是这样的

usr/bin/v2ctl
etc/v2ray/geoip.dat

**Comment by VictoriaRaymond** [comment]
没什么动力修改，也无法评估修改之后会有什么影响。

**Comment by v2raycc** [comment]
使用环境变量配置
