### ISSUE TITLE
安卓客户端成功连接v2ray服务器后，网络连接异常

### ISSUE THREAD

**Issue by BalaTiger** [v2ray/discussion#281]
【服务端】
Bandwagon的VPS，系统为Centos7，使用官方一键脚本安装。

【客户端】
最早出现问题的为朋友手机，只知道App为BifrostV。后来自己在测试机上复现。
测试机为华为mate9，系统Android8，先后测试BifrostV、v2rayNG、Kitsunebi均出现问题。
测试机尝试过重置网络连接、重启等修复方式，并测试了连接公司wifi、连接另一台iPhone的热点两种情况。

【问题表现】
客户端App：可建立连接，但v2rayNG测试连接失败，报错为Connection closed by peer或SSL handshake time out其中一种。
客户端操作系统：无论路由模式为全局还是代理，均呈现网络连接异常状态，不仅无法访问Google等屏蔽网站，也无法访问未受屏蔽的国内网站，其他App也失去连接。关闭v2ray连接后即恢复正常。
服务端v2ray日志：能看到测试机ip正常连接服务端、访问Google的日志，日志内容为：61.130.11.178:39833 accepted tcp:www.google.com:80。偶尔夹杂duplicated session id, possibly under replay attack的报错，但ip不同于测试机，且时间上与测试机访问操作无关联性。

【已经排除的原因】
1.系统时间与服务端时间不一致：测试机与PC时间一致，而PC能够正常访问屏蔽网站。
2.客户端vmess配置错误：相同的url在PC、iOS上可正常使用（iOS就是提供热点的那台iPhone）。
3.服务端防火墙拦截：指令查询得知Centos7防火墙未开启。
4.端口被封：使用国内外端口检测网址检测服务端ip与端口，均为成功开启状态。
5.局域网环境影响：朋友手机与测试机分处两个省。

【期望】
消除网络连接异常，并正常访问屏蔽网站

**Comment by Origami404** [comment]
朋友手机出现同样问题, 希望能解决.
EMUI版本: 5.1.3
Android版本: 7.0
VPS为Vultr的机子,  官方一键脚本安装, 系统为Ubuntu. 在自己的电脑跟手机测试良好. 手机客户端为v2rayNG

**Comment by kslr** [comment]
请需要按照模板填写配置和日志

**Comment by LiBinX** [comment]
我最近也是这个问题
手机：google pixel3
安卓版本 ：10
解决方法：时间，可以看一下时间是不是标准北京时间，我使用网络时间比北京快两分钟，调成北京时间就可以连接成功
