### ISSUE TITLE
v2ray+ws+nginx+tls+cdn 为何无法配置多个端口？

### ISSUE THREAD

**Issue by rainbowshine521** [v2ray/discussion#282]
1.你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.19.1

2.你的使用场景是什么？
使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频
通过Cloudflare中转，修复被ban的服务器
服务端设置了多个端口和协议，希望都可以使用cloudflare中转

3.你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
在不开启cf的cdn和http proxy的情况下（status处小云朵图标为灰色的时候），每个端口的协议可正常连接，但是开启以后（变橙色）只有第一个端口配置起作用，剩余的无法连接

4.你期待看到的正确表现是怎样的？
正常连接

5.请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）
服务器端配置:
{
        "routing":{
                "domainStrategy":"AsIs",
                "rules":[
                        {
                                "inboundTag":[
                                        "api"
                                ],
                                "type":"field",
                                "outboundTag":"api"
                        },
                        {
                                "inboundTag":[
                                        "vmess-in"
                                ],
                                "type":"field",
                                "outboundTag":"direct"
                        }
                ]
        },
        "outbounds":[
                {
                        "settings":{},
                        "protocol":"freedom",
                        "tag":"direct"
                },
                {
                        "settings":{},
                        "protocol":"blackhole",
                        "tag":"blocked"
                }
        ],
        "stats":{},
        "log":{
                "access":"/var/log/v2ray/access.log",
                "loglevel":"debug",
                "error":"/var/log/v2ray/error.log"
        },
        "api":{
                "tag":"api",
                "services":[
                        "HandlerService",
                        "LoggerService",
                        "StatsService"
                ]
        },
        "inbounds":[
                {
                        "settings":{
                                "address":"127.0.0.1"
                        },
                        "protocol":"dokodemo-door",
                        "port":34725,
                        "tag":"api",
                        "listen":"127.0.0.1"
                },
                {
                        "settings":{
                                "clients":[
                                        {
                                                "id":"394cee20-1ffd-4f8c-9f29-170be261f231",
                                                "alterId":64
                                        }
                                ]
                        },
                        "protocol":"vmess",
                        "port":10406,
                        "enable":false,
                        "streamSettings":{
                                "wsSettings":{
                                        "path":"/dfad82bb/",
                                        "headers":{}
                                },
                                "security":"none",
                                "network":"ws"
                        },
                        "remark":"",
                        "tag":"vmess-in",
                        "listen":"127.0.0.1"
                },
                {
                        "settings":{
                                "clients":[
                                        {
                                                "id":"97f96eee-c22d-47a7-cc42-71634ad5c54e",
                                                "alterId":63
                                        }
                                ]
                        },
                        "protocol":"vmess",
                        "port":55042,
                        "streamSettings":{
                                "wsSettings":{
                                        "path":"/help/",
                                        "headers":{}
                                },
                                "security":"none",
                                "network":"ws"
                        },
                        "remark":"",
                        "tag":"inbound-55042",
                        "listen":"127.0.0.1"
                }
        ],
        "policy":{
                "system":{
                        "statsInboundUplink":true,
                        "statsInboundDownlink":true
                }
        }
}                                                
        
客户端配置:
{
  "log": {
    "access": "C:\\Vaccess.log",
    "error": "C:\\Verror.log",
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "port": 1080,
      "listen": "0.0.0.0",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "www.mydomain.com",
            "port": 444,
            "users": [
              {
                "id": "97f96eee-c22d-47a7-cc42-71634ad5c54e",
                "alterId": 63,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": null
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/help/",
          "headers": null
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": []
  }
}
这个客户端配置是无法连接的

6.请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 /var/log/v2ray/error.log 文件中。

服务端错误日志:
2019/07/03 09:07:22 [Debug] [1051214633] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:41872
2019/07/03 09:07:22 [Info] [1051214633] v2ray.com/core/app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]
2019/07/03 09:08:22 [Debug] [3679518096] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:41878
2019/07/03 09:08:22 [Info] [3679518096] v2ray.com/core/app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]
2019/07/03 09:09:22 [Debug] [1442976610] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:41882
2019/07/03 09:09:22 [Info] [1442976610] v2ray.com/core/app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]
2019/07/03 09:10:22 [Debug] [2841625478] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:41884
2019/07/03 09:10:22 [Info] [2841625478] v2ray.com/core/app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]
2019/07/03 09:11:22 [Debug] [1376168553] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:41888
2019/07/03 09:11:22 [Info] [1376168553] v2ray.com/core/app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]

**客户端错误日志:**
--------------------------------info[16:54:03]--------------------------------
System.Exception: Webserver Stop 127.0.0.1

 
--------------------------------info[16:54:03]--------------------------------
System.Exception: Webserver Stop 192.168.1.188

 
--------------------------------info[16:54:03]--------------------------------
System.Exception: Webserver Stop 无法访问已释放的对象。
对象名:“System.Net.HttpListener”。

 
--------------------------------info[16:54:03]--------------------------------
System.Exception: Webserver prefixes http://127.0.0.1:1082/pac/

 
--------------------------------在前缀“http://127.0.0.1:1082/pac/”上侦听失败，因为它与计算机上的现有注册冲突。[16:54:03]--------------------------------
System.Net.HttpListenerException (0x80004005): 在前缀“http://127.0.0.1:1082/pac/”上侦听失败，因为它与计算机上的现有注册冲突。
   在 System.Net.HttpListener.AddAllPrefixes()
   在 System.Net.HttpListener.Start()
   在 v2rayN.HttpProxyHandler.HttpWebServer..ctor(String[] prefixes, Func`2 method)

 
--------------------------------info[16:54:03]--------------------------------
System.Exception: Webserver running...

 
--------------------------------info[16:54:03]--------------------------------
System.Exception: Webserver prefixes http://192.168.1.188:1082/pac/

 
--------------------------------拒绝访问。[16:54:03]--------------------------------
System.Net.HttpListenerException (0x80004005): 拒绝访问。
   在 System.Net.HttpListener.AddAllPrefixes()
   在 System.Net.HttpListener.Start()
   在 v2rayN.HttpProxyHandler.HttpWebServer..ctor(String[] prefixes, Func`2 method)

 
--------------------------------info[16:54:03]--------------------------------
System.Exception: Webserver running...

 
--------------------------------info[17:06:18]--------------------------------
System.Exception: Webserver Stop 127.0.0.1

 
--------------------------------info[17:06:18]--------------------------------
System.Exception: Webserver Stop 192.168.1.188

 
--------------------------------info[17:06:18]--------------------------------
System.Exception: Webserver Stop 无法访问已释放的对象。
对象名:“System.Net.HttpListener”。

 
--------------------------------info[17:06:18]--------------------------------
System.Exception: Webserver prefixes http://127.0.0.1:1082/pac/

 
--------------------------------在前缀“http://127.0.0.1:1082/pac/”上侦听失败，因为它与计算机上的现有注册冲突。[17:06:18]--------------------------------
System.Net.HttpListenerException (0x80004005): 在前缀“http://127.0.0.1:1082/pac/”上侦听失败，因为它与计算机上的现有注册冲突。
   在 System.Net.HttpListener.AddAllPrefixes()
   在 System.Net.HttpListener.Start()
   在 v2rayN.HttpProxyHandler.HttpWebServer..ctor(String[] prefixes, Func`2 method)

 
--------------------------------info[17:06:18]--------------------------------
System.Exception: Webserver running...

 
--------------------------------info[17:06:18]--------------------------------
System.Exception: Webserver prefixes http://192.168.1.188:1082/pac/

 
--------------------------------拒绝访问。[17:06:18]--------------------------------
System.Net.HttpListenerException (0x80004005): 拒绝访问。
   在 System.Net.HttpListener.AddAllPrefixes()
   在 System.Net.HttpListener.Start()
   在 v2rayN.HttpProxyHandler.HttpWebServer..ctor(String[] prefixes, Func`2 method)

 
--------------------------------info[17:06:18]--------------------------------
System.Exception: Webserver running...

 7.请附上访问日志。在 Linux 中，日志通常在 /var/log/v2ray/access.log 文件中。
服务器端没有访问日志
无

8.其它相关的配置文件（如 Nginx）和相关日志。
/etc/nginx/conf.d/v2ray.conf

root@instance-1:/etc/nginx/conf.d# more v2ray.conf 
    server {
        listen 443 ssl;
        ssl_certificate       /etc/v2ray/v2ray.crt;
        ssl_certificate_key   /etc/v2ray/v2ray.key;
        ssl_protocols         TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers           HIGH:!aNULL:!MD5;
        server_name www.mydomain.com;
        index index.html index.htm;
        root  /home/wwwroot/sCalc;
        error_page 400 = /400.html;
        location /dfad82bb/
        {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:10406;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        }
}
    server {
        listen 444 ssl;
        ssl_certificate       /etc/v2ray/v2ray.crt;
        ssl_certificate_key   /etc/v2ray/v2ray.key;
        ssl_protocols         TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers           HIGH:!aNULL:!MD5;
        server_name www.mydomain.com;
        index index.html index.htm;
        root  /home/wwwroot/sCalc;
        error_page 400 = /400.html;
        location /help/
        {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:55042;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        }
}
    server {
        listen 80;
        server_name www.mydomain.com;
        return 301 https://www.mydomain.com$request_uri;
    }

日志：无

**Comment by bafflingbug** [comment]
如果没理解错的话，cloudflare只能解决配置为ws或者h2，且最终暴露端口为443的链接。
那个任意门协议的配置估计没办法，剩下的话，把nginx配置中444端口下面的location放到443下面的话，应该可以。

**Comment by rainbowshine521** [comment]
> 如果没理解错的话，cloudflare只能解决配置为ws或者h2，且最终暴露端口为443的链接。
> 那个任意门协议的配置估计没办法，剩下的话，把nginx配置中444端口下面的location放到443下面的话，应该可以。或者都用443端口，但是用不同域名也应该可以。

但是把两个location内容放在443下面无法实现连接呢
我试过以下这种配置，都连不上。。。不知道您是否还有啥妙招指导没？
root@instance-1:/etc/nginx/conf.d# more v2ray.conf 
    server {
        listen 443 ssl;
        ssl_certificate       /etc/v2ray/v2ray.crt;
        ssl_certificate_key   /etc/v2ray/v2ray.key;
        ssl_protocols         TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers           HIGH:!aNULL:!MD5;
        server_name www.mydomain.com;
        index index.html index.htm;
        root  /home/wwwroot/sCalc;
        error_page 400 = /400.html;
        location /dfad82bb/
        {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:10406;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        }
        location /help/
        {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:55042;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        }        
}

    server {
        listen 80;
        server_name www.mydomain.com;
        return 301 https://www.mydomain.com$request_uri;
    }
