### ISSUE TITLE
匪夷所思 为什么kcp发包间隔设定大了反而速度更快!!?

### ISSUE THREAD

**Issue by k79e** [v2ray/discussion#283]
没法想啊 为什么会这样.

**Comment by iochen** [comment]
Qos?

**Comment by Kylejustknows** [comment]
发包太快，一个包还没确认，就被重复发送，一直到它被确认了，下一个数据包才发过来，中间重复发包好几次，浪费了带宽。在服务器上行受限的环境，影响很多速度。

加大间隔，降低了重复发包率，减少了网络浪费，经常会导致最终整体网速更快，这情况很正常。

“最优的发包率”，是个玄学，间隔和限流等变化参数太多，只有尝试摸索。

**Comment by k79e** [comment]
是么 但是kcptun没这问题
