### ISSUE TITLE
我弄明白出站dns怎么用了

### ISSUE THREAD

**Issue by k79e** [v2ray/discussion#286]
原来要加个路由啊. 可以反着来.
别人绑定任意门然后绕路的 就是暴露端口做加密dns隧道的 是把任意门流量劫持到 内置dns

然后还可以反着来. 把内置dns流量 弹回出站dns.
这样好处就是可以用tcp查询了.

样例. 
出站里面加出站dns
{
"tag":"d1",
"protocol": "dns",
"settings": {
"network": "tcp",
"address": "1.1.1.1",  //根据自己需求修改地址
"port": 53 }
}

出站外面 也就是配置文件的最外面的大括号 里面 加一个独立的大括号.
就是跟 出站入站都一样的大括号. 不可以写其他里面.
  "dns": {
	"tag":"d2",
    "servers": [
	{ "network":"tcp",
      "address":"xxxxxxx",   //随便写 作废的地址应该都可以
		"port":53 }
    ]
},

然后路由就照样写就成
	  	  {
  "type": "field",
  "inboundTag": "d2",
  "outboundTag": "d1"
}

参考
---------------------
{
  "log": {},
  "api": {},
  "dns": {},     <------- 这个是内置dns
  "stats": {},
  "routing": {},
  "policy": {},
  "reverse": {},
  "inbounds": [],
  "outbounds": [],  <--------- 出站dns写这里
  "transport": {}
}

**Comment by kxmp** [comment]
用出就是做tcp查询用的.

**Comment by kxmp** [comment]
无论是指定ip让他走代理(废话啊 默认就是其他ip走代理不是么??)
还是让出站路由走代理
{
  "type": "field",
  "inboundTag": "dnsout",
  "outboundTag": "proxy"
}
都不起效果啊

不知道为什么.
但是我想起了任意门 这样就好办了 随便一个任意门 然后出站给他写任意门的地址不就行了.

**Comment by kxmp** [comment]
好了多说一句 这个是任意门任意门任意门 就是他不是内置代理
他可以查询*任何*dns记录

**Comment by kxmp** [comment]
疑问又来了 内置dns填了就能用
出站dns填了没法用 还得加路由 让那个内置dns弹回去 弹回出站............
这是为什么 是不是这个用法不标准!!?

**Comment by kuoruan** [comment]
最近也在看内置的DNS，但是你这个配置没看出来监听 53 端口啊，全部的配置文件是怎么样的？

**Comment by kxmp** [comment]
出站当然不监听 除非绕回任意门
没啥用的 出站是客户机发请求 不太适合做那种代理......

**Comment by kuoruan** [comment]
官方的配置是加了个入站的任意门，监听的 53
```
{
  "port": 53,
  "tag": "dns-in",
  "protocol": "dokodemo-door",
  "settings": {
    "address": "1.1.1.1",
    "port": 53,
    "network": "tcp,udp"
  }
}
```
tag 是在这个入站上的，而你的配置里边将 tag 放在了内置 DNS 的配置上，路由还是从入站 tag 转发到出站 tag
V2Ray 如何 获取到 DNS 解析的请求？

**Comment by kuoruan** [comment]
你的全部配置是怎么样的，能发上来我研究吗

**Comment by kxmp** [comment]
出站默认是转到内置dns的.
你想要什么效果啊. 普通vmess只用内置就够了 除非你用他接入其他代理. 才需要我这个配置.
我就是反着来的 内置dns直接走回出站dns. 出站因为有拦截功能所以把流量改为tcp了. 解决了s5 udp烦人问题.
然后出站目前走不了代理 我又加了个任意门. 直接出站1.1.1.1那里填任意门的地址就行了.
这么清楚你还不明白么....
那个配置我就少写个任意门啊!!!!

**Comment by kuoruan** [comment]
我想实现的效果是，透明代理局域网内的所有 DNS 请求。
我在路由器上将所有的 53 udp 流量和全部的 tcp 流量都转发到了一个入站的任意门端口上。
发现 DNS 请求不经过内置 DNS，直接通过代理出去了。

**Comment by kxmp** [comment]
正常啊 任意门就是隧道的. 当然直接就出去了
让他走代理要发回去代理啊.

除非指定让他走出站代理
出站写个空的 然后任意门走出站就行了

**Comment by kxmp** [comment]
我还试了下 直接用内置dns的标签
试了下竟然不行 还必须走出站dns.... 看来出站会自动把流量丢给内置.

内置dns默认就是走代理.

**Comment by kuoruan** [comment]
官方的文档里边，有两个出站协议会调用内置DNS：
https://www.v2ray.com/chapter_02/protocols/dns.html
https://www.v2ray.com/chapter_02/protocols/freedom.html
其他的应该都不行
