### ISSUE TITLE
mkcp发包失控啊 不受限速

### ISSUE THREAD

**Issue by kxmp** [v2ray/discussion#288]
rx:     6.68 Mbit/s   646 p/s          tx:   107.96 Mbit/s  9401 p/s

                           rx         |       tx
--------------------------------------+------------------
  bytes                    52.45 MiB  |      506.49 MiB
--------------------------------------+------------------

而且开个imgur竟然10倍发包 其他网页没这情况啊.

我限速写在transport全局设置里面的
   "uplinkCapacity": 12,

不对 是受控的. 
但是我客户端配置限速是8M
就是郁闷这发包为什么这么打 kcptun也没那么大啊.

**Comment by kxmp** [comment]
开imgur主页的时候 滚动下 流量就跑的特大.
开这个也特大https://imgur.com/gallery/YX5j857

**Comment by kxmp** [comment]
kcptun客户端配置接受最大13M差不多 服务器还不发包了. 最高才发了7.6MBps
而且打开同页面 发包也没那么异常.
                           rx         |       tx
--------------------------------------+------------------
  bytes                   264.24 MiB  |      357.28 MiB
--------------------------------------+------------------
          max           66.86 Mbit/s  |    61.02 Mbit/s
      average           14.06 Mbit/s  |    19.01 Mbit/s
          min             269 kbit/s  |        0 kbit/s
--------------------------------------+------------------
  packets                     106265  |          263781
--------------------------------------+------------------
          max               1172 p/s  |        5494 p/s
      average                690 p/s  |        1712 p/s
          min                445 p/s  |           0 p/s
--------------------------------------+------------------
  time                  2.57 minutes

**Comment by xujwoo** [comment]
同感
