### ISSUE TITLE
客户端 outbound 可否加入类似"动态端口"的功能?

### ISSUE THREAD

**Issue by kingwilliam** [v2ray/discussion#291]
现有问题
- 因“反向代理”成功建立连线後客户端的port口会一直用到中断。就是这一长时间连线会引起“墙”的注意，“墙”会主动断开这个连接，但v2ray会发现连接断开後会用一个新的port口再发起连接，就是这样不断循环最终引至“墙”封锁server side listening port{ 以上是我正在面对的问题 }
- 就算不是"反向代理"，如客户端用例如openvpn over dokodemo. 也会出现同一情况{ 以上是我正在面对的问题 }
- 如在“墙”的位置看，有一个连接长时间连接不断，“墙”主动断开，但好快又再连接，再断再连接，结论就是“有一不知名服务在运作”
{ 以上纯是个人推测 }

可否加入 客户端 outbound 动态端口的功能？
- server side  可以用单一端口如 443，但client side 可否以每隔如5分钟转一次端口.
- 当然如每5分钟强行关闭port口也会出现问题，可否在断开前v2ray先建位一个新连线样原先的服务如"反向代理"或"openvpn over dokodemo"转到新连线才关闭旧连线.

**Comment by 8x8-64** [comment]
墙应该不会经常断开连接，这会严重影响网络质量。客户端每发起一个新连接就会用新端口连接服务器，不会用同一个端口。就算连接被中间人破坏了，也会用新端口发起连接，因为旧端口没那么快被系统释放。服务器多开几个端口，然后客户端用负载均衡实现切换？

**Comment by kingwilliam** [comment]
其实我就是一个server有多个ip, 我只用了其中2个做load balancer, 最初2个ip都运作正常, 但运作了1-2星期就发觉其中一个ip开始不能连接,在client side做测试, 先做ping test是没问题, 但一有连接如https就会不能连接有问题那个ip, 就连ping 也不能, 有点似被'罚'咁觉. 但过了一阵就可以再ping, 但再有上网也会不能ping, 但同时另一个ip就完全正常. 如在这时在config内不用load balancer, 只直连另一个正常ip, 完全停用有问题的ip, 我试过大约停了一星期, 再用回load balancer, 就完全正常。

但个人觉得'墙'好像不似是block ip, 感觉像似block service side mac address. 但还要再测试.
我指的'似block service side mac address' 不是全国不能连接, 只是我这个client mac address不能连接这个server mac address.
