### ISSUE TITLE
当路由规则含有 geoip:cn 时客户端无法连接

### ISSUE THREAD

**Issue by 4553733** [v2ray/discussion#293]
花了3天时间排查才找到，因为对json配置完全0基础。发现此配置在Windows下正常，但是换到Debian系统上就无法正常应用配置。

```json
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 20719,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "3c7dce68-4aa6-4e03-ad3c-d6f3a627dd72",
            "level": 1,
            "alterId": 233
          }
        ]
      },
      "streamSettings": {
        "network": "tcp"
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    },
    {
      "protocol": "shadowsocks",
      "port": 34838,
      "settings": {
        "method": "chacha20-ietf-poly1305",
        "password": "233blog.com",
        "network": "tcp,udp",
        "level": 1,
        "ota": false
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "mtproto",
      "settings": {},
      "tag": "tg-out"
    }
  ],
  "dns": {
    "server": [
      "1.1.1.1",
      "1.0.0.1",
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "geosite:cn"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:cn"
        ]
      }
    ]
  },
  "transport": {
    "kcpSettings": {
      "uplinkCapacity": 100,
      "downlinkCapacity": 100,
      "congestion": true
    },
    "sockopt": {
      "tcpFastOpen": true
    }
  }
}

```

具体情况表现如下，当没有配置路由时，一切都正常，当规则里面包含了geoip:cn后，手机上的客户端就会无法使用，测试失败，并且无法浏览任何网页，这个代码用在Windows的客户端V2rayN下完全正常。想问下原因？

附上日志：
```
cat /var/log/v2ray/access.log

2019/07/11 22:49:21 *.*.216.175:49424 rejected  v2ray.com/core/proxy/shadowsocks: failed to read IV > EOF

2019/07/11 22:49:22 *.*.216.175:49427 rejected  v2ray.com/core/proxy/shadowsocks: failed to read IV > EOF

2019/07/11 22:49:22 *.*.216.175:49428 rejected  v2ray.com/core/proxy/shadowsocks: failed to read IV > EOF

2019/07/11 22:49:22 *.*.216.175:49430 rejected  v2ray.com/core/proxy/shadowsocks: failed to read IV > EOF
```

```
cat /var/log/v2ray/error.log
2019/07/11 22:46:06 [Warning] v2ray.com/core: V2Ray 4.19.1 started
```

**下面提供配置文件，当去掉routing部分的代码或者routing部分代码不包含 geoip:cn 规则时，客户端都是可以正常连接的。提供客户端界面的对比图，无论是vemss协议还是shadosocks协议都无法正常连接，各位大大可以试试把配置文件上传到vps上测试。**

![替换配置前后](https://user-images.githubusercontent.com/7725643/61099242-3a324980-a494-11e9-9704-fd53e527b7c6.JPG)
[配置文件.json.txt](https://github.com/v2ray/discussion/files/3384814/json.txt)

**Comment by kslr** [comment]
使用```包裹配置，然后添加日志

**Comment by 4553733** [comment]
[0.json.txt](https://github.com/v2ray/discussion/files/3382547/0.json.txt)
![IMG_4341](https://user-images.githubusercontent.com/7725643/61060197-c14bd700-a42c-11e9-9ca1-77737458088b.JPG)
![IMG_4340](https://user-images.githubusercontent.com/7725643/61060199-c14bd700-a42c-11e9-8b61-64a2d65f5c20.JPG)

**Comment by kingwilliam** [comment]
有点不明白，看您的config.json应该是server side，同时应该在境外。

您的geoip.cn应该是放在客户端。

同时 试试删除sniffing设定。

**Comment by 4553733** [comment]
> 有点不明白，看您的config.json应该是server side，同时估计应该在境外。
> 
> 您的geoip.cn应该是放在客户端，对吧？
> 
> 同时 试试删除sniffing设定。
> 
> 或可否提供多点伺服器和客户端两边的资讯。

补充一下服务器具体假设情况：
**抱歉，刚刚重新检查的时候发现少贴了路由代码。**

我尝试使用过国内VPS和境外日本的VPS来假设，脚本是233blog的一键搭建脚本，手机使用的是Shadowrockt，我试过了逐行逐行代码的排查发现：只要当路由规则里面出现geoip:cn的规则，就会出现无法连接的情况，无论最后的 outboudTag 是 直连 还是 走代理。客户端都无法连接，就像上面截图显示的一样，超时。

如果把路由代码删除，就可以正常连接。

**Comment by kingwilliam** [comment]
如果您的VPS在国内 rules加入 geoip.cn非常合理，但国内是去不到您设定的4个dns, 上不到网也是合理。

如果您的VPS在境外，您设定的4个dns就非常合理，但相反geoip.cn又不应在境外server 出现。

**Comment by 4553733** [comment]
> 如果您的VPS在国内 rules加入 geoip.cn非常合理，但国内是去不到您设定的4个dns, 上不到网也是合理。
> 
> 如果您的VPS在境外，您设定的4个dns就非常合理，但相反geoip.cn又不应在境外server 出现。

DNS里面有5条，除了前4条外第五条是localhost，利用本地DNS解析，这个DNS是默认生成的代码，即使我不手动设定DNS，把DNS部分代码去掉，也依然会出现我上述的情况，最后定位到geoip.cn的问题是我逐行逐行代码测试，并且在测试过程中并没有添加DNS解析。

上面代码包含还是因为前面说的这是一个新部署的V2ray，在其他任何代码不改动的情况下单纯在路由加入geoip.cn规则，就会出现无法连接的情况，我在国内阿里云和国外Vultr日本服务器上已经反复验证过（全新部署，云盾卸载，Vultr也是国内可用IP段）。

**Comment by nicholascw** [comment]
> 说明一下我目前的架构：我-{SS}-国内中转VPS-{V2ray}-海外VPS。
这段代码是在国内中转的VPS上部署的。

那国内中转的VPS上不是应该部署一个vmess的outbound吗？配置文件没体现啊。

**Comment by 4553733** [comment]
> > 说明一下我目前的架构：我-{SS}-国内中转VPS-{V2ray}-海外VPS。
> > 这段代码是在国内中转的VPS上部署的。
> 
> 那国内中转的VPS上不是应该部署一个vmess的outbound吗？配置文件没体现啊。

因为现在问题出在geo:ip 的路由规则上面，在没有此条路由规则下配置是正常的，上面的配置是用一键脚本安装后生成的默认配置。只要加上含有geoip的规则就会无法使用。

**Comment by nicholascw** [comment]
给个例子吧，放在中转服务器上实测通过。
```json
{
  "log": {},
  "dns": {},
  "inbound": {
    "protocol": "shadowsocks",
    "port": 2333,
    "settings": {
      "method": "aes-128-gcm",
      "password": "23333333",
      "udp": true,
      "level": 1,
      "ota": false
    }
  },
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "Abroad Server IP",
            "port": 6666,
            "users": [
              {
                "id": "66666666-6666-6666-6666-666666666666",
                "alterId": 64,
                "security": "auto",
                "level": 0
              }
            ]
          }
        ]
      }
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        },
        {
          "type": "field",
          "outboundTag": "direct",
          "domain": [
            "geosite:cn"
          ]
        },
        {
          "type": "field",
          "outboundTag": "direct",
          "ip": [
            "geoip:cn"
          ]
        }
      ]
    }
  }
}
```

**Comment by nicholascw** [comment]
> 只要加上含有geoip的规则就会无法使用。

提供一下 `v2ray -test -config [config_file]` 的运行结果，以及确认一下你有没有 `geosite.dat` 和 `geoip.dat`。

**Comment by 4553733** [comment]
> > 只要加上含有geoip的规则就会无法使用。
> 
> 提供一下 `v2ray -test -config [config_file]` 的运行结果，以及确认一下你有没有 `geosite.dat` 和 `geoip.dat`。


想问一下v2ray -test -config [config_file] 这个命令是官方的命令还是哪里的命令？我是用的是233blog的一键安装脚本，测试了很多次并没成功执行上面的命令。     我并没有geosite.dat和geoip.dat这个文件，geoip不是一个在线解析服务吗？

**Comment by 4553733** [comment]
> ```json
> {
>   "log": {},
>   "dns": {},
>   "inbound": {
>     "protocol": "shadowsocks",
>     "port": 2333,
>     "settings": {
>       "method": "aes-128-gcm",
>       "password": "23333333",
>       "udp": true,
>       "level": 1,
>       "ota": false
>     }
>   },
>   "outbounds": [
>     {
>       "protocol": "vmess",
>       "settings": {
>         "vnext": [
>           {
>             "address": "Abroad Server IP",
>             "port": 6666,
>             "users": [
>               {
>                 "id": "66666666-6666-6666-6666-666666666666",
>                 "alterId": 64,
>                 "security": "auto",
>                 "level": 0
>               }
>             ]
>           }
>         ]
>       }
>     },
>     {
>       "protocol": "freedom",
>       "settings": {},
>       "tag": "direct"
>     },
>     {
>       "protocol": "blackhole",
>       "settings": {},
>       "tag": "blocked"
>     }
>   ],
>   "routing": {
>     "strategy": "rules",
>     "settings": {
>       "domainStrategy": "IPIfNonMatch",
>       "rules": [
>         {
>           "type": "field",
>           "ip": [
>             "0.0.0.0/8",
>             "10.0.0.0/8",
>             "100.64.0.0/10",
>             "127.0.0.0/8",
>             "169.254.0.0/16",
>             "172.16.0.0/12",
>             "192.0.0.0/24",
>             "192.0.2.0/24",
>             "192.168.0.0/16",
>             "198.18.0.0/15",
>             "198.51.100.0/24",
>             "203.0.113.0/24",
>             "::1/128",
>             "fc00::/7",
>             "fe80::/10"
>           ],
>           "outboundTag": "blocked"
>         },
>         {
>           "type": "field",
>           "outboundTag": "direct",
>           "domain": [
>             "geosite:cn"
>           ]
>         },
>         {
>           "type": "field",
>           "outboundTag": "direct",
>           "ip": [
>             "geoip:cn"
>           ]
>         }
>       ]
>     }
>   }
> }
> ```

想问一下上面实测通过的代码你使用的是233blog的一键安装吗？还是官方教程一步一步安装？

**Comment by nicholascw** [comment]
使用geoip和geosite必须依赖对应数据文件。

**Comment by 4553733** [comment]
> 使用geoip和geosite必须依赖对应数据文件。

感谢，我先去试试。

**Comment by 4553733** [comment]
问题解决了，原因是因为一键安装的脚本里面没有geoip.dat的数据库文件。
