### ISSUE TITLE
V2Ray 让 cmd 中也可以使用的办法

### ISSUE THREAD

**Issue by fbens** [v2ray/discussion#295]
电脑已经安装了V2Ray，浏览器可以用了。但是如何在 cmd 中也用上V2Ray。
开启了全局模式，但CMD中依然是国内IP。
```shell
C:\Users\Administrator>curl -I http://www.facebook.com
curl: (56) Recv failure: Connection was reset

C:\Users\Administrator>curl https://api.myip.com
{"ip":"129.29.213.34","country":"China","cc":"CN"}
C:\Users\Administrator>

```

如何实现让cmd中也可以使用

**Comment by fbens** [comment]
> 电脑已经安装了V2Ray，浏览器可以用了。但是如何在 cmd 中也用上V2Ray。
> 开启了全局模式，但CMD中依然是国内IP。
> 
> ```shell
> C:\Users\Administrator>curl -I http://www.facebook.com
> curl: (56) Recv failure: Connection was reset
> 
> C:\Users\Administrator>curl https://api.myip.com
> {"ip":"129.29.213.34","country":"China","cc":"CN"}
> C:\Users\Administrator>
> ```
> 
> 如何实现让cmd中也可以使用


找到方法了，原来windows CMD也可以执行 `set HTTP_PROXY=http://127.0.0.1:3333`
```shell
C:\Users\Administrator>set http_proxy=http://127.0.0.1:2334

C:\Users\Administrator>set https_proxy=http://127.0.0.1:2334

C:\Users\Administrator>curl https://api.myip.com
{"ip":"186.22.235.206","country":"United States","cc":"US"}
C:\Users\Administrator>
```

搞定

**Comment by kxmp** [comment]
curl -x http://x.x.x.x:xxxx
curl -x socks5://
curl --socks5 xxxxx:xxx

**Comment by xuhuihao** [comment]
set http_proxy=http://127.0.0.1:2334
