### ISSUE TITLE
新手求问，v2ray的多用户设置有什么用

### ISSUE THREAD

**Issue by lijiaqi213** [v2ray/discussion#298]
我看很多人设置了多用户，就是修改config文件添加多个uuid

萌新求问，为什么不能多个人使用一个uuid？这样有什么弊端吗？
还是说不同人分开使用不同的账户，不同的uuid有什么优势。。。

还有，电脑和手机同时使用的时候还用不用分开uuid？

**Comment by kxmp** [comment]
可以用一个uuid的

**Comment by fbens** [comment]
可以多个不同路径 ~ 域名绑定
