### ISSUE TITLE
V2RayN客户端直连设置不生效，域名依旧走了代理

### ISSUE THREAD

**Issue by fbens** [v2ray/discussion#300]
客户端已在【参数设置】>【路由设置】的“直连的Domain或IP”中加入了域名。
可依旧走了代理。域名 mail.qq.com，加入了 mail.qq.com 和 *.mail.qq.com 依旧走代理。
```
2019/07/15 09:15:25 [Info] [506906211] v2ray.com/core/app/dispatcher: sniffed domain: stockweb.mail.qq.com
2019/07/15 09:15:25 [Info] [506906211] v2ray.com/core/app/dispatcher: taking detour [direct] for [tcp:stockweb.mail.qq.com:443]
2019/07/15 09:15:25 [Info] [506906211] v2ray.com/core/proxy/freedom: opening connection to tcp:stockweb.mail.qq.com:443
2019/07/15 09:15:25 [Info] [506906211] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:stockweb.mail.qq.com:443
2019/07/15 09:15:25 [Info] [3722839708] v2ray.com/core/proxy/socks: TCP Connect request to tcp:219.133.61.29:443
2019/07/15 09:15:25 tcp:127.0.0.1:56146 accepted tcp:219.133.61.29:443 
2019/07/15 09:15:25 [Info] [3722839708] v2ray.com/core/app/dispatcher: sniffed domain: wp.mail.qq.com
2019/07/15 09:15:25 [Info] [3722839708] v2ray.com/core/app/dispatcher: taking detour [direct] for [tcp:wp.mail.qq.com:443]
2019/07/15 09:15:25 [Info] [3722839708] v2ray.com/core/proxy/freedom: opening connection to tcp:wp.mail.qq.com:443
2019/07/15 09:15:25 [Info] [3722839708] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:wp.mail.qq.com:443

```

版本：V2RayN v2.29
配置如下图：
![QQ截图20190715092729](https://user-images.githubusercontent.com/1414939/61191952-d81b5380-a6e2-11e9-950f-c8ee18417a9f.png)

**Comment by gonnalee** [comment]
尝试用这样的写法试试
![image](https://user-images.githubusercontent.com/24651612/61515413-1f804780-aa35-11e9-854c-b92049140d65.png)
v2rayN客户端有自己的pac规则，如果这样不行你在看客户端pac文件，浏览器访问需要先经过pac分流，然后决定一部分流量直连，一部分流向v2ray，v2ray会再根据你这个配置再次进行分流，决定一部分流量直连，一部分代理，一部分阻止。

**Comment by fbens** [comment]
> 尝试用这样的写法试试

非常感谢，我是在CMD中代理使用。
不过我如果直接设置 baidu.com，在baidu里面查询IP是直接当前国内IP。
如只设置`domain:qq.com`，那 qq.com 下面所有子域名都会直连吗。还是需要输入正则`domain:*.qq.com`

**Comment by gonnalee** [comment]
@fbens 
我测试了下,domain模式子域名也可以匹配上。不需要*号通配符

**Comment by fbens** [comment]
@gonnalee 
有点古怪，我有的时候不能。刚刚找到了一个[配置文档](https://www.v2ray.com/chapter_02/03_routing.html)  按照上面测试却又全部都无法访问 ~ 

![屏幕快照 2019-07-19 21 52 11](https://user-images.githubusercontent.com/1414939/61540236-d7324b00-aa6f-11e9-8dc8-bdbf1d2d33f0.png)


```json
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules":[
      {
        "type": "field",
        "ip": [
          "0.0.0.0/8",
          "10.0.0.0/8",
          "fc00::/7",
          "fe80::/10",
          "geoip:private"
        ],
        "domain": [
          "baidu.com",
          "qq.com",
          "aliyun.com",
          "csdn.net",
          "firefox.com",
          "firefox.com.cn",
          "firefoxchina.cn"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": ["geosite:category-ads"],
        "outboundTag": "blocked"
      }
    ]
  }
```

**Comment by fbens** [comment]
> @gonnalee
> 非常古怪，完全不生效的感觉。
> 刚刚找到了一个[配置文档](https://www.v2ray.com/chapter_02/03_routing.html) 按照上面测试却又全部都还是走的代理。给人感觉像完全都不起作用一样
> 
> ![屏幕快照 2019-07-19 21 52 11](https://user-images.githubusercontent.com/1414939/61540236-d7324b00-aa6f-11e9-8dc8-bdbf1d2d33f0.png)
> 

测试了很多次，完全就不生效！感觉这个过滤配置完全就不起作用啊！！
```shell
bb:~ ss$ curl https://api.myip.com
{"ip":"113.65.13.61","country":"China","cc":"CN"}

bb:~ ss$ export http_proxy=http://127.0.0.1:10800
bb:~ ss$ export https_proxy=http://127.0.0.1:10800
bb:~ ss$ curl https://api.myip.com
{"ip":"176.122.15.26","country":"United States","cc":"US"}
```

**Comment by gonnalee** [comment]
@fbens 我这边测试是没有问题的 。
我看了下你的配置,api.myip.com这个域名，当你export http proxy后，显示ip是你的代理ip。说明走了代理。而你上面v2ray配置rules中，并没有出现api.myip.com这个域名，如果域名并不在rule策略中，会默认走第一个outbound出口。你的第一个出个应该是代理出口，所有myip.com走了代理属于正常情况

**Comment by qcnhy** [comment]
完全没用
adobe.com这个域名
![image](https://user-images.githubusercontent.com/42377311/77819530-7555d500-7116-11ea-85d9-ede1272cbedb.png)
![image](https://user-images.githubusercontent.com/42377311/77819545-8c94c280-7116-11ea-8097-47bb5a9d7af4.png)

**Comment by liangpu597** [comment]
我的跟上面的是相反的，我使用的pac规则，但是有些域名还是无法走代理。我手动设置：

![TIM截图20200602101940](https://user-images.githubusercontent.com/23580110/83472895-e620c100-a4ba-11ea-8621-7716c385ff13.png)

没有走代理

**Comment by ileeoyo** [comment]
@liangpu597 流量先经过了pac过滤一遍，然后再v2ray过滤一遍。你这个域名**btbtt.co**已经被pac放行了，就不会再流入v2ray。所以在这里设置没生效，你可以尝试把域名写到最新v2rayN客户端的**用户pac设置**里。先理解`浏览器-->pac过滤->v2ray路由`这样一个管道流向

**Comment by liangpu597** [comment]
@ileeoyo  好的，我写进pac了。 现在有一点不明，既然这样的话，那么软件的这里设置的直连和代理的域名干什么？ 是适用于哪种情况下？软件的http代理不是有几种模式吗？

**Comment by ileeoyo** [comment]
@liangpu597 首先pac并不是v2ray-core的功能，pac只是v2rayN客户端加上，方便浏览器等支持自动pac代理的软件使用的。很多软件是没法支持pac的，那些软件需要设置http代理或者sock5代理为v2ray-core的代理端口，这样就有个问题，这些软件的流量全部被代理了，国内流量被代理就很慢。所以v2ray-core自己实现了路由规则，我们可以自己设置灵活的路由规则，甚至可以选择ban到bt流量。如果你仅仅需要浏览器分流的话，pac+用户自定义pac足够了，v2ray-core这里的路由规则可以无需修改

**Comment by liangpu597** [comment]
@ileeoyo  好的，谢谢。在下面找到了config.json 这个了。有inbound , outbound,这些。里面有各种各样的路由配置。

**Comment by digdig** [comment]
这软件挺反直觉的。。。
正常搞一个白名单/黑名单不行么。。。
真不知道上面的设置到底有什么用，没用干脆去掉得了。。。
我是在设置“代理的domain或IP”中添加网址，添加了完全没有任何效果，根本就不走代理。。。
所以我说搞这个选项有啥作用？？？添加一个白名单就这么难吗？

**Comment by qcnhy** [comment]
> 

上一下配置看看是不是配置错误 一般都是配置错误导致的 或者前面有优先级更高的规则匹配到了 所以不走代理了 例如:geo:cn

**Comment by digdig** [comment]
![image](https://user-images.githubusercontent.com/5459093/156349666-a5e8ef33-a54a-4a64-a796-f5f450186ed1.png)
我也不太懂，总之我觉得应该就是这么设置的，我在最后面加了两行我想要通过代理的网址，无效。

**Comment by digdig** [comment]
```
geosite:google,

geosite:github,

geosite:netflix,

geosite:steam,

geosite:telegram,

geosite:tumblr,

geosite:speedtest,

geosite:bbc,

domain:gvt1.com,

domain:textnow.com,

domain:twitch.tv,

domain:wikileaks.org,

domain:naver.com,

91.108.4.0/22,

91.108.8.0/22,

91.108.12.0/22,

91.108.20.0/22,

91.108.36.0/23,

91.108.38.0/23,

91.108.56.0/22,

149.154.160.0/20,

149.154.164.0/22,

149.154.172.0/22,

74.125.0.0/16,

173.194.0.0/16,

172.217.0.0/16,

216.58.200.0/24,

216.58.220.0/24,
13.107.42.12,
13.107.136.9,
52.114.158.92,
13.107.42.12,
13.107.136.9,
52.114.158.92,
*live.com*,
*live.net*,
*microsoft.com*,
*office.com*,
*office.net*,
*windows.com*,
*windows.net*,
*sharepoint.com*,
*office365.com*,
*officeppe.net*,
*skype.com*,
*onedrive.com*,
*msocsp.com*,
*msauthimages.net*,
*msauth.net*,
*microsoftonline.com*,
*msn.com*,
*onenote.com*,
*onenote.net*,
*1drv.com*,
*wikipedia.org*,
*wikimedia.org*,
*inoreader.com*,
domain:www.inoreader.com

整个配置地址
```

**Comment by ynmc** [comment]
学习到了。
一直有一个域名不愿意走代理，need2proxy.com，在Core:路由 里面设置了domain:need2proxy.com，没有效果。
只能每次访问这个域名的时候把代理模式改成全局，非常不方便。
根据上面的理解，PAC可能先把这个域名放行到直连了，所以在 用户PAC设置 中将need2proxy.com加入。这个设置起作用了，need2proxy.com能够在pac模式下也能被代理了。
感谢大家的讨论内容。

**Comment by joyol** [comment]
哎,搞了半天都不走代理,所见非所得
最终在浏览器用SwitchyOmega做规则,再建个trojan直连

**Comment by mesotescode** [comment]
我试了V6.23和6.28，在白名单里添加的代理域名都没有生效，用了四种写法：forum.xxxx.com;“forum.xxxx.com";domain:forum.xxxx.com;domain:“forum.xxxx.com"
都没有生效，pac里添加域名也是不生效，一直都是直连。
clash貌似浏览器标签页开多了 节点就会断连一阵，现在V2rayN添加域名不生效也是恼火。
