### ISSUE TITLE
如何查看路由或出站相关的日志信息 How to get logging of outbound or route?

### ISSUE THREAD

**Issue by mo-han** [v2ray/discussion#302]
配置了多个outbound并且根据域名做了路由，希望在日志中查看各个请求分别走了哪个outbound，以便了解路由工作状况，该怎么实现。
Having multiple outbounds and route configured, how to get logging of which outbound being used by every connection?

**Comment by JellalLeonhardt** [comment]
可以参考下我的实现，OutboundDetourConfig和OutboundHandlerConfig增加个配置项判断是否打印日志，改下outbound的Handler，加个接口用于判断是否要打印日志，然后在分流器里，PickRoute并GetHandler后，用接口判断一下，为true的话，用handler的tag加上destination打一条日志（AccessMessage在这用有点奇怪，我就顺手增加了个ProxyMessage）
