### ISSUE TITLE
求教使用官方脚本在本地Ubuntu上安装因releases地址被Q无法安装怎么破？

### ISSUE THREAD

**Issue by qqlovekerry** [v2ray/discussion#305]
如题，使用官方的方法在本地的Ubuntu上安装，直接使用`bash <(curl -L -s https://install.direct/go.sh)`不行。尝试了用`wget https://install.direct/go.sh`下载脚本后，用`sudo bash go.sh`来安装。但是发现因为releases地址已经被Q，终端里会始终停留在
```
Installing V2Ray v4.20.0 on x86_64
Downloading V2Ray: https://github.com/v2ray/v2ray-core/releases/download/v4.20.0/v2ray-linux-64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   608    0   608    0     0    460      0 --:--:--  0:00:01 --:--:--   460
  0 11.3M    0     0    0     0      0      0 --:--:--  0:03:16 --:--:--     0
```
然后报错退出，请教下这个应该怎么破？谢谢！

**Comment by linsui** [comment]
> go.sh 参数
> 
> go.sh 支持如下参数，可在手动安装时根据实际情况调整：
> 
>     -p 或 --proxy: 使用代理服务器来下载 V2Ray 的文件，格式与 curl 接受的参数一致，比如 "socks5://127.0.0.1:1080" 或 "http://127.0.0.1:3128"。
>  -   -f 或 --force: 强制安装。在默认情况下，如果当前系统中已有最新版本的 V2Ray，go.sh 会在检测之后就退出。如果需要强制重装一遍，则需要指定该参数。
>  -   --version: 指定需要安装的版本，比如 "v1.13"。默认值为最新版本。
>  -   --local: 使用一个本地文件进行安装。如果你已经下载了某个版本的 V2Ray，则可通过这个参数指定一个文件路径来进行安装。

https://www.v2ray.com/chapter_00/install.html

**Comment by qqlovekerry** [comment]
谢谢！我已经安装成功了，非常有帮助！

**Comment by qqlovekerry** [comment]
@linsui 您好！有一个问题再请教一下，我是使用`--local`参数安装的，因为我已经将zip下载到了本地。但是我在已经设置了代理的情况下，使用`./go.sh -p socks5://127.0.0.1:1080`安装的话还是会失败，还是网络连接有问题，提示`Failed to download! Please check your network or try again.`
请问下这是为什么呢？

**Comment by linsui** [comment]
@qqlovekerry 抱歉，我并不知道 :joy: 我也只安装过一次

**Comment by qqlovekerry** [comment]
@linsui 好的，没关系。还是非常感谢你！我就用`--local`参数好了
