### ISSUE TITLE
请问如何配置v2ray令所有流量走tls1.3？

### ISSUE THREAD

**Issue by i553041** [v2ray/discussion#306]
现在使用的是V2ray+WS+TLS+NGINX+CDN (CF)

平时大多以ios的shadowrocket去看「平时无法看到的网站。」

Nginx版本为1.15.8，已用ssllab test测试网站支持TLS 1.3，但nginx的设定档一定要设为：
ssl_protocols TLSv1.2 TLSv1.3;

若将之设为ssl_protocols TLSv1.3;
shadowrocket㑹连不上，在浏览器打网站地址㑹显示CF的报错页525 handshake fail

CF的crypto，Minimum TLS Version亦要设为1.2，若设为1.3，shadowrocket所有连接㑹全都死亡。

现在在CF的Security上看流量，百分之99的流量都是走TLS 1.3，既然V2ray、Nginx、CF都支持TLS1.3，那肯定是希望shadowrocket将所有流量都能走TLS 1.3，这样科学上网才㑹更安全，更隐闭。

我Mac用V2RayU，有TLS 1.3的流量，(在CF能看到。)，唯独IOS那边完全没有1.3流量。有没有甚么办法让ios客户端的所有流量都走TLS1.3？是否现在的ios客户端例如shadowrocket不支持TLS 1.3？

我用的是iPhone X，最新ios 12及Shadowrocket已更新为最新版本。

谢谢。

**Comment by kslr** [comment]
我建议你咨询shadowrocket作者

**Comment by cudaying** [comment]
实测也是如此，shadowrocket 对v2ray alterid 支持也是个谜
