### ISSUE TITLE
如何转发服务器的本地端口

### ISSUE THREAD

**Issue by wicast** [v2ray/discussion#309]
类似 ssh -L 1521:127.0.0.1:1521 root@1.1.1.1 的效果
服务器本地端口不能在公网直接访问

v2ray 配置生成
   
选择协议
 监听IP
0.0.0.0
 端口
1521
转发地址
127.0.0.1
 转发端口
1521
 转发协议
 
inbound 配置
```
{
  "port": 1521,
  "listen": "0.0.0.0",
  "protocol": "dokodemo-door",
  "settings": {
    "address": "127.0.0.1",
    "port": 1521,
    "network": "tcp,udp"
  }
}
```

并不能起作用

**Comment by kslr** [comment]
我建议你使用frp
