### ISSUE TITLE
Is VMess protocol will be recognized as TLS/HTTPS by DPI?

### ISSUE THREAD

**Issue by imortkz** [v2ray/discussion#312]
Hello,

Let me explain why I'm asking that: I live in the KZ and our authorities as intend to do MITM in the national scale using custom CA for that.

I wonder if I may use VMess to avoid that, if all TLS traffic except deciphered one may be blocked?

**Comment by kslr** [comment]
this will not affect vmess, but can't use tls*

**Comment by imortkz** [comment]
> this will not affect vmess, but can't use tls*

Do you mean that all TLS traffic inside the Vmess tunnel may be recognized by DPI ?

**Comment by kslr** [comment]
Tls refers to websocket, http2 etc.

**Comment by 8x8-64** [comment]
It's easier to use a portable browser and don't use fake CA
