### ISSUE TITLE
编译的时候 这个报错是怎么回事，有能看懂的大神吗 ？

### ISSUE THREAD

**Issue by Uhtred009** [v2ray/discussion#313]
ERROR: Skipping '//release:v2ray_darwin_amd64_package': error loading package 'release': Encountered error while reading extension file 'bazel/zip.bzl': no such package '@v2ray_ext//bazel': /private/var/tmp/_bazel_maqiduo/303cd2c5a30ce2000b49b06582d3e110/external/v2ray_ext must be an existing directory

**Comment by kslr** [comment]
你好，其他人不是全知全能的，请提供足够的复现条件。
