### ISSUE TITLE
多ip server，用了sprov ui添加新的账户但是都显示同一个ip

### ISSUE THREAD

**Issue by today000000** [v2ray/discussion#318]
vps上面有多个ip，本想用sprov ui直接添加账户比较简单。
但是添加好之后发现多个ip其实访问的时候显示的还是同个ip。
然后就看大神有说通过"sendThrough"来指定，没搞明白怎么玩。
我把服务器配置文件附上来，跪求大神们帮忙指点下。
                {
                        "settings":{},
                        "protocol":"blackhole",
                        "tag":"blocked"
                }
        ],
        "stats":{},
        "api":{
                "tag":"api",
                "services":[
                        "HandlerService",
                        "LoggerService",
                        "StatsService"
                ]
        },
        "inbounds":[
                {
                        "settings":{
                                "clients":[
                                        {
                                                "level":1,
                                                "id":"7739690b-d7b5-4575-a1cf-ef45041c4d29",
                                                "alterId":64
                                        }
{
        "routing":{
                "rules":[
                        {
                                "inboundTag":[
                                        "api"
                                ],
                                "type":"field",
                                "outboundTag":"api"
                        },
                        {
                                "ip":[
                                        "geoip:private"
                                ],
                                "type":"field",
                                "outboundTag":"blocked"
                        }
                ]
        },
        "outbounds":[
                {
                        "settings":{},
                        "protocol":"freedom"
                },
                {
                        "settings":{},
                        "protocol":"blackhole",
                        "tag":"blocked"
                }
        ],
        "stats":{},
        "api":{
                "tag":"api",
                "services":[
                        "HandlerService",
                        "LoggerService",
                        "StatsService"
                ]
        },
        "inbounds":[
                {
                        "settings":{
                                "clients":[
                                        {
                                                "level":1,
                                                "id":"77396923-d7b5-4575-a1cf-ef45041c4d29",
                                                "alterId":64
                                        }
                                ]
                        },
                        "protocol":"vmess",
                        "port":19059
                },
                {
                        "settings":{
                                "address":"127.0.0.1"
                        },
                        "protocol":"dokodemo-door",
                        "port":19582,
                        "tag":"api",
                        "listen":"127.0.0.1"
                },
                {
                        "settings":{
                                "clients":[
                                        {
                                                "id":"ee1e0511-2978-4f68-9d93-b9cdd7c58fb1",
                                                "alterId":65
                                        }
                                ]
                        },
                        "protocol":"vmess",
                        "port":32628,
                        "streamSettings":{
                                "security":"none",
                                "network":"tcp"
                        },
                        "remark":"",
                        "tag":"inbound-32628",
                        "listen":"118.xx.xx.67"
                }
        ],
        "policy":{
                "system":{
                        "statsInboundUplink":true,
                        "statsInboundDownlink":true
                }
        }
}

**Comment by kingwilliam** [comment]
先要清晰您的問題
1。您的vps同時有多ip可用(如2個ip)? 
2。您的v2ray server設定了多用戶(如3個用戶) ？
3。您想 用戶一 用server ip1, 用戶二三用server ip2 ?

**Comment by today000000** [comment]
1 我同时有16个ip可以用
2 我的v2ray server也设定了16个用户
3我是想每个用户独立一个ip出口

**Comment by kingwilliam** [comment]
您的问题已离开了v2ray范围，已是网络层的问题。

1。因tcp/ip只能有1个default gateway.
2。如您user1去Google.com, 同时user2也去Google.com, 系统不能同时2个ip 去同1个ip地址。

**Comment by BlackMask007** [comment]
@kingwilliam 大佬，我的环境如下，我仿照了你的方法，但是不行。

V2Ray version： 4.21.3
运行环境环境： ws + tls1.3
问题：
v2ray服务器有三个外网ip地址，一直没搞懂如何使用api动态添加用户，并指定该用户的出口ip。
例如，A、B用户连接v2ray服务，A、B用户默认从10.10.10.100出，此时通过api添加了一位E用户，
想让E用户的流量从10.10.10.101出，如何能实现呢？请大神指点指点...

```json

{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "incoming01",
      "port": 11234,
      "listen": "10.10.10.100",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "4a494949-ae9a-4b6a-8f0f-49d3f567f5c1",
            "level": 1,
            "alterId": 64,
            "email": "akcp1234@gmail.com"
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/88d3"
        }
      }
    },
    {
      "tag": "incoming02",
      "port": 11234,
      "listen": "10.10.10.101",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "4a494949-ae9a-4b6a-8f0f-49d3f567f5c1",
            "level": 1,
            "alterId": 64,
            "email": "akcp1234@gmail.com"
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/88d3"
        }
      }
    },
    {
      "tag": "incoming03",
      "port": 11234,
      "listen": "10.10.10.102",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "4a494949-ae9a-4b6a-8f0f-49d3f567f5c1",
            "level": 1,
            "alterId": 64,
            "email": "akcp1234@gmail.com"
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/88d3"
        }
      }
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "incoming01"
        ],
        "outboundTag": "gateway01"
      },
      {
        "type": "field",
        "inboundTag": [
          "incoming02"
        ],
        "outboundTag": "gateway02"
      },
      {
        "type": "field",
        "inboundTag": [
          "incoming03"
        ],
        "outboundTag": "gateway03"
      }
    ]
  },
  "outbounds": [
    {
      "tag": "gateway01",
      "protocol": "freedom",
      "sendThrough": "10.10.10.100"
    },
    {
      "tag": "gateway02",
      "protocol": "freedom",
      "sendThrough": "10.10.10.101"
    },
    {
      "tag": "gateway03",
      "protocol": "freedom",
      "sendThrough": "10.10.10.102"
    }
  ]
}

```

**Comment by SilurianYang** [comment]
### 让 routing 自己去匹配
```json
{
	"inbounds": [
		{
			"port": 24680,
			"protocol": "vmess",
			"tag": "in-1",
			"listen": "27.xx.xx.24",
			"settings": {
				"clients": [
					{
						"id": "880e768c-xxx-xxx--xxx-xxxx-201db4fce8ff",
						"level": 1,
						"alterId": 66
					}
				]
			}
		},
		{
			"port": 24680,
			"protocol": "vmess",
			"tag": "in-2",
			"listen": "27.xx.xx.25",
			"settings": {
				"clients": [
                    {
						"id": "880e768c-xxx-xxx--xxx-xxxx-201db4fce8ff",
						"level": 1,
						"alterId": 66
					}
				]
			}
		},
		{
			"port": 24680,
			"protocol": "vmess",
			"tag": "in-3",
			"listen": "27.xx.xx.29",
			"settings": {
				"clients": [
                    {
						"id": "880e768c-xxx-xxx--xxx-xxxx-201db4fce8ff",
						"level": 1,
						"alterId": 66
					}
				]
			}
		}
	],
	"outbounds": [
		{"protocol": "freedom", "sendThrough": "27.xx.xx.24", "tag": "out-1"},
		{"protocol": "freedom", "sendThrough": "27.xx.xx.25", "tag": "out-2"},
		{"protocol": "freedom", "sendThrough": "27.xx.xx.29", "tag": "out-3"}
	],
	"routing": {
		"rules": [
			{"type": "field", "outboundTag": "out-1", "inboundTag": "in-1"},
			{"type": "field", "outboundTag": "out-2", "inboundTag": "in-2"},
			{"type": "field", "outboundTag": "out-3", "inboundTag": "in-3"}
		]
	}
}
```
