### ISSUE TITLE
希望监视TLS证书文件变动

### ISSUE THREAD

**Issue by cherrot** [v2ray/discussion#32]
最近突然用不了，发现v2ray抱怨证书过期拒绝连接。检查后发现证书已经正常更新过了，但v2ray应该只在启动后即加载，因此需要重启一下v2ray进程。

可否监视key file的变动，如果更新自动reload证书？

**Comment by VictoriaRaymond** [comment]
V2Ray 实际上没有文件的概念，所有文件系统相关的依赖，比如解析配置文件，是在 v2ctl 里完成的。V2Ray 并不知道配置的来源是文件还是其它的字节流，所以类似reload的功能都是不做的。

**Comment by cherrot** [comment]
有道理 :)
给别人提供点参考，如果通过systemd timer设定证书更新的话，可以在执行更新操作后重启v2ray达到刷新证书的目的。

`/lib/systemd/system/certbot-renew.service`:

```
[Unit]
Description=Renew certificates from Let's Encrypt

[Service]
Type=oneshot
ExecStart=/usr/bin/certbot renew
ExecStart=/usr/bin/systemctl restart v2ray
```
