### ISSUE TITLE
V2RAY 是否能自定义内网(LAN)IP访问代理转发控制功能

### ISSUE THREAD

**Issue by yuchenshuize** [v2ray/discussion#323]
个人有PC,PS4,NS，通过路由连接，已在路由上开启v2ray
希望PC走GFWLIST
PS4,NS走全局代理
如何实现？

**Comment by kingwilliam** [comment]
个人有PC,PS4,NS，通过路由连接，已在路由上开启v2ray

Q1:希望PC走GFWLIST
A1:你提议的思维是GFWLIST走v2ray, 馀下的走直连. 下面的思维就 国内domain或国内ip就直连, 馀下的走v2ray.
`	"routing": {
		"rules": [
			{
				"type": "field",
				"domain": [
					"geosite:cn"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"ip": [
					"geoip:cn"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"network": "tcp,udp",
				"outboundTag": "vmess_out"
			}
		],
	},
	"outbounds": [
		{
			"tag": "vmess_out",
			"protocol": "vmess",
			"settings": {
				...
			}
		},
		{
			"tag": "direct",
			"protocol": "freedom",
			"settings": {}
		},

	]	
`

Q2:PS4,NS走全局代理
A2:全局代理是要在linux base执行iptables, 以下是网上一般的ip tables scripts用作参考

**Comment by yuchenshuize** [comment]
多谢回答，我好好研究下
