### ISSUE TITLE
cdn模式越用越慢，被识别了？

### ISSUE THREAD

**Issue by archongum** [v2ray/discussion#324]
需要伪装？

**Comment by kingwilliam** [comment]
被识别就不能上,是不会慢. cdn也不是万能,晚上也会塞的.

**Comment by archongum** [comment]
我换个ip，然后再用同一个cdn（Cloudflare）可以变快。。。所以我觉得识别了某些流量然后做限制（猜

**Comment by mo-han** [comment]
大陆的出口带宽有多窄你不知道吗？
三大运营商再不搞qos这网还能用？
