### ISSUE TITLE
反向代理和fq功能共存的问题

### ISSUE THREAD

**Issue by patchper** [v2ray/discussion#327]
我现在在树梅派上运行v2ray，为内网提供socks和http的代理，一切OK。但是我尝试设置反向代理把树梅派的某个端口映射出去时就连fq也不行了。
有人尝试过这两个功能共存么？要怎么设置呢？

**Comment by kingwilliam** [comment]
要看您两边的config.json先可协助

**Comment by excing** [comment]
正在折腾这个东西，我也遇到了你这个问题，只应用一个功能就没问题，两个同时存在，就必然有一个服务不能用。

请问您最后解决了这个问题吗，是怎么配置的呢？

**Comment by excing** [comment]
@kingwilliam 的确如你所说，是 config.json 配置的问题，v2 支持这种共存操作

**Comment by blackkcold** [comment]
@excing 您好，想咨询一下你是怎么配置文件的？
