### ISSUE TITLE
新白话文-高级-流量统计中的脚本运行出现错误

### ISSUE THREAD

**Issue by xianren78** [v2ray/discussion#328]
https://guide.v2fly.org/advanced/traffic.html 中的脚本，在debian9中开始用没有问题。后来出现错误，无法统计总的down流量，错误如截图。重启v2ray服务可以解决，但是会丢失之前的流量记录。

![20190807110546](https://user-images.githubusercontent.com/26913311/62591789-5abeb980-b903-11e9-8454-128df8016c50.jpg)

**Comment by kslr** [comment]
@boypt

**Comment by vcptr** [comment]
hmmm  当数值大于一定时候v2ctl输出的数字是科学记数法，这个在bash内真不好处理。。
麻烦提供一份v2ctl的原始输出以便调试，自用的机器还没出现过科学计数法的情况

**Comment by xianren78** [comment]
#/usr/bin/v2ray/v2ctl api --server=127.0.0.1:10010 StatsService.QueryStats ''
stat: <
  name: "inbound>>>h2>>>traffic>>>uplink"
>
stat: <
  name: "user>>>wj@mail.com>>>traffic>>>uplink"
  value: 1874303
>
stat: <
  name: "user>>>wj@mail.com>>>traffic>>>downlink"
  value: 284798659
>
stat: <
  name: "inbound>>>api>>>traffic>>>uplink"
  value: 1716
>
stat: <
  name: "inbound>>>api>>>traffic>>>downlink"
  value: 6351
>
stat: <
  name: "inbound>>>ws>>>traffic>>>uplink"
  value: 52106110
>
stat: <
  name: "inbound>>>h2>>>traffic>>>downlink"
>
stat: <
  name: "user>>>qg@mail.com>>>traffic>>>uplink"
  value: 46614506
>
stat: <
  name: "user>>>qg@mail.com>>>traffic>>>downlink"
  value: 4031924226
>
stat: <
  name: "inbound>>>wsdoko>>>traffic>>>uplink"
>
stat: <
  name: "inbound>>>wsdoko>>>traffic>>>downlink"
>
stat: <
  name: "inbound>>>ws>>>traffic>>>downlink"
  value: 4360992106
>


> hmmm 当数值大于一定时候v2ctl输出的数字是科学记数法，这个在bash内真不好处理。。
> 麻烦提供一份v2ctl的原始输出以便调试，自用的机器还没出现过科学计数法的情况

**Comment by vcptr** [comment]
嗯 其实是因为awk的输出是科学计数法，v2ctl不会；
只需要强制awk输出普通数据就好了；

修正版本在仓库里： https://github.com/v2fly/v2ray-step-by-step/blob/transifex/zh_CN/advanced/traffic.md

**Comment by kslr** [comment]
@nicholascw 部署一下新的更新吧

**Comment by xianren78** [comment]
> 嗯 其实是因为awk的输出是科学计数法，v2ctl不会；
> 只需要强制awk输出普通数据就好了；
> 
> 修正版本在仓库里： https://github.com/v2fly/v2ray-step-by-step/blob/transifex/zh_CN/advanced/traffic.md
Thanks. All work well.
