### ISSUE TITLE
v2ray正常，但是在koolshare配置无法使用

### ISSUE THREAD

**Issue by yelvlab** [v2ray/discussion#332]
自建v2ray，手机电脑连接正常，速度稳定，但是在koolshare里面的v2ray插件设置没报错，启动正常，同时状态提示连接OK，然后马上就断掉，只有提交的几秒后能用，我用老毛子固件的另一台应路由测试稳定，可以排除服务器问题，

**Comment by kingwilliam** [comment]
您的资料不详,很难帮您, 断线原因有很好.

1. 您是否用mkcp/quic? 您的网路供应商有否udp qos?
2. 您的vps ip已被墙.

如可以请提供多点资料.

**Comment by yelvlab** [comment]
> 您的资料不详,不好判断, 断线原因有很好.
> 
> 1. 您是否用mkcp/quic? 您的网路供应商有否udp qos?
> 2. 您的vps ip已被墙.
> 
> 如可以请提供多点资料.

十分感谢您的解答，我已经找到了问题的关键，上面您提到的我都有确认，没问题，我主要疑惑在配置导入路由的问题，后来经过发现，我朋友在里面开了其他ss服务，导致代理都没法正常连接，十分感谢，我关闭了这个issue
