### ISSUE TITLE
h2+tls 可用 cf(cdn)吗?

### ISSUE THREAD

**Issue by kingwilliam** [v2ray/discussion#335]
ws+tls+cf(cdn) 已运作正常,
但 h2+tls 可用 cf(cdn)吗? 要如何设定? 因已试了很多不同组合,但还是没成功.

**Comment by daiaji** [comment]
不能 CF对HTTP/2和HTTP/3都是伪支持
CF会把H2转成WS

**Comment by kingwilliam** [comment]
原来是这样 谢谢师兄

**Comment by imkylechang** [comment]
我的也是   换成h2+cdn 能用几分钟 然后就挂了
