### ISSUE TITLE
ss加入chacha20-ietf-poly1305支持

### ISSUE THREAD

**Issue by nulx8874** [v2ray/discussion#34]
ss能加入chacha20-ietf-poly1305支持吗？

**Comment by VictoriaRaymond** [comment]
???

![t](https://user-images.githubusercontent.com/26386597/46994168-9047ab80-d113-11e8-8bae-aba2d5ef0d4c.png)

**Comment by nulx8874** [comment]
抱歉 打错了  是xchacha20-ietf-poly1305 它比chacha20-ietf-poly1305更加安全

**Comment by nulx8874** [comment]
https://wuyanteng.github.io/2018/05/16/%E5%B8%A6%E6%9C%89%E9%99%84%E5%8A%A0%E6%95%B0%E6%8D%AE%E7%9A%84%E8%AE%A4%E8%AF%81%E5%8A%A0%E5%AF%86-libsodium/
关于xchacha20-ietf-poly1305与chacha20-ietf-poly1305的对比分析

**Comment by VictoriaRaymond** [comment]
兴趣一般

**Comment by nulx8874** [comment]
提个意见 大佬有兴趣了再弄
