### ISSUE TITLE
用haproxy做负载均衡碰到的一个问题

### ISSUE THREAD

**Issue by teraStars** [v2ray/discussion#343]
3台服务器，全部是tcp协议，由于v2ray本身的负载均衡一直没出来。
所以我现在用haproxy做负载均衡。也能正常使用。
但在v2ray服务器的日志里总能看到错误。
rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header >
经检查，我发现是因为haproxy的tcp健康度检查功能导致的。   
我现在设的是每10秒检查一次，于是每10秒就会出这么一条，如果不检查就没这个错误。
据说haproxy是通过tcp握手的方式来检查。是不是这原因导致的？

**Comment by kslr** [comment]
很可能
