### ISSUE TITLE
长城宽带能识别ws+tls了？

### ISSUE THREAD

**Issue by shenfu1991** [v2ray/discussion#345]
上海长城宽带，这两天u2b看电视剧，用的是vmess+tls+ws，电视剧看的好好的，突然就连不上了，此时能打开我的网站 https://abc.com, 用来伪装的也是这个网站，过几分钟后又能打开了。理论上vmess+tls+ws应该是最安全的模式了吧？网站能打开，自然也就能代理成功才对，所以猜测，是不是这种模式也被识别了？

**Comment by daiaji** [comment]
不走CF安全个毛

**Comment by kingwilliam** [comment]
墙 封锁你 不等如 墙 看见你在看甚麽，也不等如墙知识你用甚麽工具 用大数据 分析流量和分析你上网习惯 就可决定封不封你
