### ISSUE TITLE
求教：ws+tls+nginx 如何伪装

### ISSUE THREAD

**Issue by shenfu1991** [v2ray/discussion#346]
目前使用 ws+tls+nginx，联通app上查到的上网记录会识别成自己的域名，有没有办法让他识别成特定网站，比如，优酷、腾讯视频、爱奇艺视频。求各位大佬指教。设置header好像不行，还是我没配置对。

**Comment by kingwilliam** [comment]
被识别 只因今天去到tls1.3还有一个SNI参数是普通文字没有加密的。 SNI 内就是你vps的FQDN或ip, 要等 Esni 即是encrypted sni正式落实 到时才可不被识别(FQDN不被识别 不等於不知你去那个ip)

**Comment by sndnnlfhvk** [comment]
![2](https://user-images.githubusercontent.com/10768704/65384109-e58f3280-dd50-11e9-88a5-dd941b4468bf.png)
既然有了tls,为何还需要伪装呢？官方已经不建议伪装了。
