### ISSUE TITLE
v2ray win10 客户端报错信息 Router settings is not specified

### ISSUE THREAD

**Issue by sjx782392329** [v2ray/discussion#351]
启动服务(2019/9/1 16:09:36)......
V2Ray v3.32 (die Commanderin) 20180726
A unified platform for anti-censorship.
Main: failed to read config file: E:\Google Download\niubi\v2ray-windows-64\v2ray-v3.32-windows-64\config.json > Main|Json: failed to execute v2ctl to convert config file. > Command|Platform|CtlCmd: failed to execute v2ctl: Ext|Tools|Conf|Command: failed to parse json config > Ext|Tools|Conf|Serial: failed to parse json config > Ext|Tools|Conf: Router settings is not specified.
 > exit status 4294967295
![image](https://user-images.githubusercontent.com/33451661/64073734-6d46cb80-ccd4-11e9-8f53-2dde1d59b982.png)
我的操作步骤是下载了 v2ray 的 win 客户端，然后扫描二维码，将配置导入，（同样的配置在android 端可以正常使用），启动客户端的时候，在终端报了上述的错误，不知道是哪里出了问题

**Comment by kslr** [comment]
请使用最新客户端尝试
