### ISSUE TITLE
怎么编译得到iOS正确的framework

### ISSUE THREAD

**Issue by qxc122** [v2ray/discussion#352]
go version
go version go1.12.9 darwin/amd64

环境
go env
GOARCH="amd64"
GOBIN="/Users/lanyao/mygo/bin"
GOCACHE="/Users/lanyao/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/lanyao/mygo"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.9/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.9/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/f6/rdgfzjrj7zs8j03m4ykl1tvm0000gn/T/go-build080265506=/tmp/go-build -gno-record-gcc-switches -fno-common"

xgo --targets=ios-7.0/* v2ray.com/core/main
使用该命令得到库Main.framework 没有头文件

clone v2ray-core 放到自己go的src目录下 /Users/lanyao/mygo/src/
cd  /Users/lanyao/mygo/src/v2ray-core
命令 ：gomobile bind -target=ios .
得到   Core.framework
但是该库的头文件中有大量的
// skipped method Config.Descriptor with unsupported parameter or return types

// skipped method Config.GetApp with unsupported parameter or return types

// skipped method Config.GetExtension with unsupported parameter or return types

// skipped method Config.GetInbound with unsupported parameter or return types

// skipped method Config.GetOutbound with unsupported parameter or return types

// skipped method Config.GetTransport with unsupported parameter or return types
这种信息，这是说Go的某些方法没有编译出iOS可以用的方法吗，类型或者返回值不支持，那么我该怎么做。是我的编译命令错误，还是我可能要去修改 v2ray-core 里面的一些代码

**Comment by MyNanyh** [comment]
解决了吗
