### ISSUE TITLE
ws+tls+cdn无法访问

### ISSUE THREAD

**Issue by 148i** [v2ray/discussion#356]
使用233boy的一键脚本，系统为centos7 64位。
安装一切正常，但是所有需要fq的网页均无法打开。
**客户端提示：**
System.Net.WebException: 远程服务器返回错误: (500) 内部服务器错误。
   在 v2rayN.Handler.V2rayUpdateHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)
**服务器的日记：**
 v2ray.com/core/transport/internet/websocket: failed to serve http for WebSocket > accept tcp [::]:31575: use of closed network connction
2019/09/03 21:52:20 [Warning] v2ray.com/core: V2Ray 4.20.0 started
感觉就像是服务器不接受连接，握手失败，之前使用一键脚本没问题，这次就不行了。尝试过关闭防火墙和iptables，都没用。是不是caddy配置错误啊？

**Comment by 148i** [comment]
另外就是我发现iohone可以打开一秒钟，大概一个页面，然后就再也不行了。重新连接又可以。看了一下服务器监听端口，没有80。

**Comment by lichaojingming** [comment]
服务器看下v2ray状态，看下服务器端口开放没有

**Comment by 148i** [comment]
> 服务器看下v2ray状态，看下服务器端口开放没有

服务器显示v2ray运行，caddy没有运行。防火墙已经关了，iptables也没问题。目前找到了是caddy的问题。ss可以正常使用，协议选择除了tls+ws之外的都可以正常使用。
