### ISSUE TITLE
请求在openwrt防止域名解析泄露的最佳方案

### ISSUE THREAD

**Issue by moralrebuild** [v2ray/discussion#358]
最近尝试从SS切换到V2RAY以紧跟潮流。但发现用sniffing方式会导致敏感域名泄露 ，请问大家在这方面都采用什么方案安全出海的？

**Comment by daiaji** [comment]
openwrt DNS中转 上游直接DNS-over-HTTPS加密

**Comment by moralrebuild** [comment]
国内域名（包括CDN）也通过DNS-over-HTTPS显然不合适，请推荐具体软件（有参考配置更佳）。

**Comment by daiaji** [comment]
https://www.rubyfish.cn/ 国内DNS提供商，看你相不相信他们的节操，教程我相信你已经猜到关键词了
然后我记得走路由表的话，v2ray会接管路由表内域名的dns解析

**Comment by ttimasdf** [comment]
在v2路由里dokodemo透明代理把流量全收进来，将53端口udp额外转发到一个dns outbound即可，dns里配置分流dns，比如geosite或[h2y里](https://raw.githubusercontent.com/ToutyRater/V2Ray-SiteDAT/master/geofiles/h2y.dat)的gfwlist，将出站vmess address写成一个死IP（否则解析不了dns-无法获得出站代理ip-解析不了dns，就死循环了），如果需要SNI的话额外在传输层配置一下即可。
