### ISSUE TITLE
使用v2ray官方脚本搭建，除了VIMEO网站现在老提示IP被封锁，其它网站都正常使用

### ISSUE THREAD

**Issue by carli0215** [v2ray/discussion#359]
使用v2ray官方脚本搭建，除了VIMEO网站现在老提示IP被封锁，[https://vimeo.com/](https://vimeo.com/)
其它网站都正常使用，求高手解答，平时看视频都在VIMEO网站，这下彻底郁闷了

开始以为是ip被封锁了，我更换了IP，并且在服务端又新建几个不同国家的服务器，有美国、日本、悉尼、加拿大等国家的IP地址，并且都搭建了v2ray官方脚本，其它像google、youtube、ins等网站都可以正常访问，只有vimeo这个网站看不了（经测试我使用花钱购买的ExpressVPN可以正常访问vimeo,就是没有自己搭建的v2ray访问速度快）。vimeo不可能封锁不同国家的ip地址路，每天看vimeo视频比较多，所以在此立贴求助各路大神了

**Comment by daiaji** [comment]
不奇怪 某个网站以前直接把所有idc全锁了

**Comment by carli0215** [comment]
我用的google云的免费服务器，google云的IDC可以更换吗？

**Comment by carli0215** [comment]
给vimeo写邮件解决了，(前提是你得有一个可以正常访问vimeo的VPN服务，我是还有ExpressVPN,可以正常访问vimeo,只是没有自建的v2ray速度快)，需要将google云中的ip地址设置为静态地址，将静态IP地址发给vimeo网络安全团队，他们会将这个IP地址设置为白名单。就可以正常访问了，心病终于解决了。开心.

**Comment by daiaji** [comment]
你还好 那个破网站锁idc的时候 要你发tk去找idc客服 让他们找那破网站 结果客服说他们压根没义务搞这事 然后一年后那个破网站自己解锁了一部分idc

**Comment by kslr** [comment]
vimeo封锁了非常多机房
