### ISSUE TITLE
希望在 Freedom 中加入配置规则，IPv4 优先/ IPv6 优先

### ISSUE THREAD

**Issue by zw373** [v2ray/discussion#36]
本来以为这是一个 bug, 所以按 bug 提交格式写的，后经查阅文档，这不属于 bug. 但依旧按 bug 提交的格式在此开 issue 讨论。此需求可通过在 Freedom 中加入配置规则："IPv4 优先/ IPv6 优先" 解决。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

客户端：iptables 转发
服务端：V2ray 3.47, v2ray-linux-mips.zip 编译版，运行于 Openwrt 18.06 上。

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

使用路由器透明代理。

3) 你看到的现象是什么？

我所使用的 DNS 可同时解析 ipv4 和 ipv6 地址。对传入包使用 sniffing 功能重写地址。在路由配置中将所有 ipv6 地址经 Freedom Outbound （使用 UseIP）发出，其他地址经默认 Outbound 发出。

但是，我发现会有 ipv4 地址经 Freedom Outbound 发出。

4) 你期待看到的表现是怎样的？

在使用 Outbound UseIP 发出时，应当选择和路由选择中符合匹配要求的地址发出。或者允许用户在 Freedom 中选择 "IPv4 优先/ IPv6 优先"。

5) 请附上你的配置。

服务器端配置(和 issue 相关的部分):

```javascript
    "inboundDetour":[{
        "port":1083,
        "protocol":"dokodemo-door",
        "sniffing": {"enabled": true,"destOverride": ["http", "tls"]
    }],
    "outboundDetour":[{
        "settings":{"domainStrategy":"UseIP"},
        "protocol":"freedom",
        "tag":"dns"
      }],
     "routing":{"settings":{"rules":[{"ip":["2000::/3"],"outboundTag":"dns","type":"field"}],"domainStrategy":"IPOnDemand"},
     "dns":{"servers":  ["xxx.xxx.x.xx"]}
```

客户端配置:

```
    iptables -p tcp -j REDIRECT --to-ports 1083
```

6)  请附上软件运行时的相关日志。

目标部分的日志：
```
2018/10/19 16:28:48 [Info] [4165645465] v2ray.com/core/app/dispatcher: sniffed domain: m.analytics.126.net
2018/10/19 16:28:48 [Info] v2ray.com/core/app/router: looking for IP for domain: m.analytics.126.net
2018/10/19 16:28:48 [Info] [4165645465] v2ray.com/core/app/dispatcher: taking detour [dns] for [tcp:m.analytics.126.net:80]
2018/10/19 16:28:48 [Info] [4165645465] v2ray.com/core/proxy/freedom: opening connection to tcp:m.analytics.126.net:80
2018/10/19 16:28:48 [Info] [4165645465] v2ray.com/core/proxy/freedom: dialing to to tcp:222.20.147.174:80
2018/10/19 16:28:48 [Info] [4165645465] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:222.20.147.174:80
```

日志中 DNS 的解析结果
```
m.analytics.126.net	canonical name = m.analytics.126.net.wsglb0.com
Name:      m.analytics.126.net.wsglb0.com
Address 1: 222.24.122.79
Address 2: 222.20.147.174
m.analytics.126.net	canonical name = m.analytics.126.net.wsglb0.com
Address 3: 2001:da8:2032:1001::6
```

此段日志中，可以看出路由选择了 [dns] detour, 因为解析地址中有 dns, 但是当实际发送时，却使用了 ipv4 的地址。

**Comment by zw373** [comment]
根据我的使用来看，UseIP 的 Freedom 会随机选解析的地址发出。而在我的配置中，iptables 会将所有的 ipv4 访问发送至 V2ray (我没有写任何避免死循环的规则)，所以实际还是能访问的，但是会增加延迟。

在国内高校普遍实行 ipv4 收费 ipv6 免费的现状下，对两种流量分别处理是个需求。

**Comment by zw373** [comment]
是否可以考虑，在 Freedom 中加入配置规则，IPv4 优先/ IPv6 优先

**Comment by jolestar** [comment]
期待这个功能呀
