### ISSUE TITLE
只针对游戏的加速器居然加速了v2ray流量

### ISSUE THREAD

**Issue by EzioAu** [v2ray/discussion#361]
我最近才发现的，我用的ws+cloudflare，套了CDN之后速度是不足以看HD视频的，不过我最近在用某款游戏加速器加速某国际服游戏的时候，它居然代理了v2ray流量，之后看1080视频都完全不是问题，而且我选择其他游戏加速后完全无效，只有加速我玩的那款游戏才有效，这也太神奇了，关键是这个加速器只能加速游戏，可是却代理了v2ray流量，这是为啥

**Comment by sndnnlfhvk** [comment]
v2ray可以加速游戏的，我目前就是用来玩ps4联机。
至于只能加速游戏，服务端设置"outboundTag": "block"来屏蔽游戏以外的地址即可。

**Comment by forever8938** [comment]
> v2ray可以加速游戏的，我目前就是用来玩ps4联机。
> 至于只能加速游戏，服务端设置"outboundTag": "block"来屏蔽游戏以外的地址即可。

iptables和v2ray的配置能发一下吗，我没成功过UDP代理

**Comment by sndnnlfhvk** [comment]
> > v2ray可以加速游戏的，我目前就是用来玩ps4联机。
> > 至于只能加速游戏，服务端设置"outboundTag": "block"来屏蔽游戏以外的地址即可。
> 
> iptables和v2ray的配置能发一下吗，我没成功过UDP代理

代理流量是按照条件(大陆白名单模式、全局模式、GFW模式、游戏模式等)，不是根据协议来的，本地v2ray inbound配置一般是socks,而socks是支持UDP的，只要游戏能进inbound就行。

**Comment by forever8938** [comment]
> > > v2ray可以加速游戏的，我目前就是用来玩ps4联机。
> > > 至于只能加速游戏，服务端设置"outboundTag": "block"来屏蔽游戏以外的地址即可。
> > 
> > 
> > iptables和v2ray的配置能发一下吗，我没成功过UDP代理
> 
> 代理流量是按照条件(大陆白名单模式、全局模式、GFW模式、游戏模式等)，不是根据协议来的，本地v2ray inbound配置一般是socks,而socks是支持UDP的，只要游戏能进inbound就行。

PS4还能设置socks代理？

**Comment by sndnnlfhvk** [comment]
> > > > v2ray可以加速游戏的，我目前就是用来玩ps4联机。
> > > > 至于只能加速游戏，服务端设置"outboundTag": "block"来屏蔽游戏以外的地址即可。
> > > 
> > > 
> > > iptables和v2ray的配置能发一下吗，我没成功过UDP代理
> > 
> > 
> > 代理流量是按照条件(大陆白名单模式、全局模式、GFW模式、游戏模式等)，不是根据协议来的，本地v2ray inbound配置一般是socks,而socks是支持UDP的，只要游戏能进inbound就行。
> 
> PS4还能设置socks代理？

我是把v2ray安装在路由器里面。ps4就自动代理了。
![4](https://user-images.githubusercontent.com/10768704/65384342-d1990000-dd53-11e9-84b6-9cb328322a0e.png)

**Comment by ntgeralt** [comment]
@sndnnlfhvk  请问你用koolshare的v2ray，PS4能从nat3变为nat2吗？

**Comment by fbion** [comment]
> 我最近才发现的，我用的ws+cloudflare，套了CDN之后速度是不足以看HD视频的，不过我最近在用某款游戏加速器加速某国际服游戏的时候，它居然代理了v2ray流量，之后看1080视频都完全不是问题，而且我选择其他游戏加速后完全无效，只有加速我玩的那款游戏才有效，这也太神奇了，关键是这个加速器只能加速游戏，可是却代理了v2ray流量，这是为啥

哪款？什么游戏？
看v2ray服务端日志

**Comment by sndnnlfhvk** [comment]
> @sndnnlfhvk 请问你用koolshare的v2ray，PS4能从nat3变为nat2吗？

正常NAT2，能联机和开派对。
