### ISSUE TITLE
最新版本默认的配置文件中没有一个示例，对新手不太友好

### ISSUE THREAD

**Issue by ybbswc** [v2ray/discussion#370]
`{
  "inbounds": [{
    "port": 1080,  // SOCKS 代理端口，在浏览器中需配置代理并指向这个端口
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "udp": true
    }
  }],
  "outbounds": [{
    "protocol": "vmess",
    "settings": {
      "vnext": [{
        "address": "server", // 服务器地址，请修改为你自己的服务器 ip 或域名
        "port": 10086,  // 服务器端口
        "users": [{ "id": "b831381d-6324-4d53-ad4f-8cda48b30811" }]
      }]
    }
  }`

以上是https://www.v2ray.com/chapter_00/start.html 中的示例，在之前的版本中存在一个示例的，但是最新版本中，没有这样的示例，需要手工输入。
还请在后续版本中予以增加。

**Comment by kslr** [comment]
如果增加了这样的例子，可以预想到很多人的配置将会一摸一样。
