### ISSUE TITLE
简单的iOS客户端 A simple free v2ray client for iOS ?

### ISSUE THREAD

**Issue by higherdim** [v2ray/discussion#371]
iOS上一直都没有可用的免费客户端，是个痛点；特别是最近临近某帮派登基70周年，SS被封的很厉害基本没法用，急需v2ray来拯救。外国区App Store虽有收费客户端，但需要国外信用卡购买， 连国内的带visa/mastercard的信用卡都不行， 想购买很困难

也许有必要开发一个简单的iOS客户端？

**Comment by forever8938** [comment]
谁那么有空

**Comment by shenlijun** [comment]
> 谁那么有空

朋友，人与人是不同的
整个github上开源工具这么多，这不是有空没空的问题

**Comment by higherdim** [comment]
> 新注册一个美区的账号，宝上买充值卡，完美

已解决，谢谢！
也谢谢各位
