### ISSUE TITLE
这里适合讨论Linux安装脚本吗？

### ISSUE THREAD

**Issue by OneQuid** [v2ray/discussion#385]
`install.direct/go.sh` 应该就是 [v2ray-core/release/install-release.sh](https://github.com/v2ray/v2ray-core/blob/master/release/install-release.sh)？除master上最新的，没有另外更新的话，有几个点想讨论下。

**2019/10/05 EDITED**: 是不是可以用`cron`或`crontab`做自启动？语法中有`@reboot`可以开机自动执行，应该比较多的发行版都支持吧？

### 文件的位置
`v2ray`、`v2ctl`、`geoip.dat`和`geosite.date`四个文件的位置根据教程和脚本应该是在：
- /usr/bin/v2ray/v2ray：V2Ray 程序；
- /usr/bin/v2ray/v2ctl：V2Ray 工具；
- /usr/bin/v2ray/geoip.dat：IP 数据文件；
- /usr/bin/v2ray/geosite.dat：域名数据文件；

**这样的放置`v2ray`和`v2ctl`是不会作为command的，即不会在任意位置可执行（至少我这不会）
这四个文件放在`/usr/lib/v2ray/`下，然后 link `v2ray`和`v2ctl`到`usr/bin`，这样会不会比较好？**

~~(或者现在`geoip.dat`和`geosite.dat`是必须放在这个位置的？因为没有看过源码，不是特别清楚，如果知道的同学请告诉我一下~~

**10/04 17:12** :看了下源码是从执行位置加载开始的, `ln -s`就不行了，不知道有没有别的方法? 或者修改源码，比如添加配置文件、或者命令行参数？

### ~~自启动~~
~~现在理解下来选择`systemd`、`systemV`的主要原因是自启动，发现还有一种自启动是创建`.desktop`文件，就是开始栏中用的格式，比如`v2ray.desktop`~~

~~把`v2ray.desktop`放在`~/.config/autostart`或/etc/xdg/autostart`下也可以自启动
**现在这个方法只知道ubuntu 18以后支持，别的发行版不是很清楚**~~**(不适用大多数情况)**

~~如果`v2ray` `v2ctl`可以加载同目录下的`geoip.dat`和`geosite.date`（所以这两个到底是做什么的？
是不是就可以不用systemd/systemV了？~~**(从执行程序的目录中加载的)**
改`~/.profile`或`/etc/profile`是不是也可以？
不过好像修改配置后的重启会麻烦点？

### log
如果`config.json`中没有`log`这一段的话就直接输出到stdout, 不会输出日志到文件？**(confirmed)**
~~因为有`/etc/systemd/system/v2ray.service` systemd自启动好像就看不到了？~~

这样修改v2ray.service，不知道会不会把日志输出到`var/log/v2ray/`目录下？
好吧，另外问题在service里，这样有用吗？
```
...
ExecStart=/opt/share/v2ray/v2ray -config /opt/share/v2ray/config.json
...
```
改成
```
...
ExecStart=/opt/share/v2ray/v2ray -config /opt/share/v2ray/config.json >/var/log/v2ray/std.log 2>/var/log/v2ray/err.log
...
```

**Comment by iochen** [comment]
## 自启动
V2Ray is a CLI program，not a GUI program
NOT ALL Linux systems require GUI
`.desktop` file only works on GUI

## geoip.dat, geosite.date
See here https://v2ray.com/chapter_02/03_routing.html#ruleobject

## log
See
https://v2ray.com/chapter_02/01_overview.html#logobject

**Comment by OneQuid** [comment]
That was kind. ty @iochen. 

I guess the doc has already answered some of my questions clearly.
I reckon this project literally one day ago, hadn't spent time on the details so far.
Thank you again for digging those up.

I guess you were not into the idea of changing the `ExecStart` part either?
here it is:
```
ExecStart=/opt/share/v2ray/v2ray -config /opt/share/v2ray/config.json >/var/log/v2ray/std.log 2>/var/log/v2ray/err.log
```
Just curious about if it would work as expected, any ideas?

**Comment by iochen** [comment]
> That was kind. ty @iochen.
> 
> I guess the doc has already answered some of my questions clearly.
> I reckon this project literally one day ago, hadn't spent time on the details so far.
> Thank you again for digging those up.
> 
> I guess you were not into the idea of changing the `ExecStart` part either?
> What I mean is the change in `v2ray.service`:
> 
> ```
> ExecStart=/opt/share/v2ray/v2ray -config /opt/share/v2ray/config.json >/var/log/v2ray/std.log 2>/var/log/v2ray/err.log
> ```
> 
> After a second thought, it was not that necessary as the application already had the log config itself.
> 
> Just curious about if it would work as expected, any ideas?

If you really want to save log without using the log system in the program,I suggest using `StandardOutput`

See more here:
https://stackoverflow.com/questions/37585758/how-to-redirect-output-of-systemd-service-to-a-file

**Comment by kslr** [comment]
geosite可以通过在路由中使用ext:my 定义
geoip可以通过geoip
https://github.com/v2ray/v2ray-core/blob/3deb5f26c9dfc39831dd202a3e19d5c83dee1b61/infra/conf/router.go#L303

**Comment by OneQuid** [comment]
> geosite可以通过在路由中使用ext:my 定义
> geoip可以通过geoip
> https://github.com/v2ray/v2ray-core/blob/3deb5f26c9dfc39831dd202a3e19d5c83dee1b61/infra/conf/router.go#L303

藏的这么深，那看来可以直接改了。这个还是用systemd做吗？考虑cron吗？
cron做的话可能可以支持更多平台，systemd的话可以用`service`和`systemctl`重启方便一些，各有利弊。

**Comment by kslr** [comment]
不懂你在说什么，我在说自定义数据文件路径

**Comment by OneQuid** [comment]
请问是哪里表述的不清楚？请你联系上下文再看一下

**Comment by OneQuid** [comment]
@kslr  恕我才疏学浅，见识浅薄。还没有见过在/usr/bin里放directory的

**Comment by OneQuid** [comment]
@kslr 简单改了下脚本。
protobuf不知道你们怎么处理的，protoc 报错，知道了再该源码吧
#https://github.com/v2ray/v2ray-core/pull/1934#issue-326221770
