### ISSUE TITLE
websocket+tls+cdn是否能使用？

### ISSUE THREAD

**Issue by Dark-Kite** [v2ray/discussion#393]
当我只有一个域名（如www.masterqlg.com）时，是否能够ws、tls、cdn都使用该域名进行伪装？
同时，tls能够和cdn一起使用吗？我以前并没有接触过相关知识，关于V2ray的搭建都是由我个人进行摸索。如果这个问题很蠢，请不要嘲笑我

**Comment by Lightmani** [comment]
可以。服务器配置好websocket和tls后，再打开cdn就可以了。而且这三者一起用域名不是必须相同么。。
