### ISSUE TITLE
使用 v2rayNG APP 点击下方 测试连接 两次后，v2ray -v3.49 服务器端的进程崩溃退出

### ISSUE THREAD

**Issue by rosebe** [v2ray/discussion#40]
验证复现方法 : 使用 v2rayNG APP 点击下方 测试连接 两次后，服务器端进程会崩溃退出，后续无法连接，是 BUG?

uname -a
Linux 4.10.8-1.el6.elrepo.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux

使用 v2ray 方式：websocket+Nginx+TLS

退回 v2ray-v3.47 无以上现象(正常状态，进程未退出），v2ray-v3.48 未测试。

**Comment by FatChou** [comment]
你好，v2ray通过gomobile编译成framework或者aar。看到之前issue说要自己写个什么函数，你会吗？

**Comment by rosebe** [comment]
v2ray-v3.48 测试正常，进程未退出。

**Comment by rosebe** [comment]
测试 v2ray-v3.48 正常，进程未退出。

**Comment by rosebe** [comment]
Close Issues #40

Commits on Oct 27, 2018
fix #1338
https://github.com/v2ray/v2ray-core/commit/6c89940e655079b1912b86e8df4f10a7861052bc
