### ISSUE TITLE
可以新增对多配置文件的支持

### ISSUE THREAD

**Issue by wattic** [v2ray/discussion#401]
v2ray功能越来越强大，config文件也越来越长。能否增加多配置文件读取的功能，可以把各个object(routing/outbound)放在单独的文件里，方便配置/自动化和debug呢？

**Comment by ZLplLQc** [comment]
简而言之，就是把多个config合并成一个config呗。
实际操作中会出现合并顺序和什么时候用覆盖什么时候用追加等烦人的问题。
拿routing.rules来举例吧。

#### 顺序问题：
假设有A/B/C三份配置，合并时新配置追加到原配置的尾部。于是将B合并入A得出AB，然后C合并进AB得出ABC最终配置。这样C中的rules是有可能被A中的rules屏蔽掉的。如果合并时新配置插到原配置头部，那么A的rules就有可能被C的rules屏蔽掉。这个查起来其实也是比较费劲的。
再考虑到outbound[0]是默认outbound，合并时routing和outbounds究竟是都插头还是都插尾还是区别对待好呢？这其实有点复杂。

#### 覆盖和追加问题：
假设有三份routing如下：
```js
{
  "domainStrategy": "AsIs",
  "rules":[
     ...
  ]
}
```
```js
{
  "domainStratgy": "IPOnDemand", // 和配置一不同
  "rules":[
    ...
  ]
}
```
```js
{
  "domainStrategy": "AsIs", // 和配置一相同
  "rules":[
     ...
  ]
}
```
合并这三份routing的时候，domainStrategy应该选哪个？他们的rules应该怎么合并？


其实还有其他奇怪的问题，真正去实现这功能的时候就会发现很头疼。

**Comment by wattic** [comment]
原意是允许各个不同的功能块的合并（不同功能有不同的配置文件），不是相同功能块之间的合并，因为后者的确会在数组对象中产生问题。
我自己写了个配置，目前routing部分是这么实现的，对$$xxx$$就对应去读config_xxxx.json替换，里面也允许一样的配置，递归下去。最后调用 -test。短时间内还没想好怎么处理各种tag造成的冲突。（或许可以写成$$tag_proxy_1$$这样的格式？）
不过的确还是要写config的人要为最后的正确性把关,感觉意义有限。
`{
    "stats": {},
    "api": $$api$$,
    "policy": $$policy$$,
    "log": $$log$$,
    "inbounds": [
        $$s1080$$,
        $$vmess_wstls4433$$,
        $$vmess_with_dyn688$$,
        $$ss_163x$$,
        $$doku_6008_stats_api$$
    ],
    "outbounds": [
        $$outbounds_server$$
    ],
    "dns": $$dns$$,
    "routing": {
        "domainStrategy": "Asis",
        "rules": [
            $$rr_api_server$$,
            $$rr_block_localaddr_server$$,
            $$rr_block_lz_server$$,
            $$rr_block_torrent$$
        ]
    },
    "transport": $$transport$$
}`

**Comment by ZLplLQc** [comment]
在一些特殊场合，分割/合并config的功能还是需要的。比如把某个PAC转成v2ray的routing差不多有一千行，这时就很有必要把routing踢出主配置。
我写的那些只是提醒一下这个功能并不像看上去那么简单，实现之前需要多考虑各种情况，定出合理的合并规则。这个功能做好了其实还是很有用的。

**Comment by kslr** [comment]
如果需要更灵活的方案，不如直接修改源码
