### ISSUE TITLE
我想基于vmess开发一个iPhone的手机客户端，需要怎么入手呢？

### ISSUE THREAD

**Issue by wfkbyni** [v2ray/discussion#402]
不知道怎么入手，也没有iPhone开发相关的资料，希望各路大神能指点一二！！

**Comment by kslr** [comment]
https://v2ray.com/developer/protocols/vmess.html

**Comment by lovelyJason** [comment]
我也想,楼主有答案了吗,文档里似乎没有安装手机端2ray的教程

**Comment by TangDynasty1218** [comment]
请问现在仍在坚持开发基于vmess协议的iPhone客户端吗？如果是请回复留言或者联系我的邮箱地址。tangdynasty1218@163.com

**Comment by ZTzhaotian** [comment]
同问楼主，我有一个这样诉求，能否联系下

**Comment by SincereXing** [comment]
> 不知道怎么入手，也没有iPhone开发相关的资料，希望各路大神能指点一二！！

不知道楼主有没有开发了，我正在研究，希望分享一下经验

**Comment by hecanlin** [comment]
您好，您找到学习资料了么，我也正在研究这个

**Comment by hecanlin** [comment]
> > 不知道怎么入手，也没有iPhone开发相关的资料，希望各路大神能指点一二！！
> 
> 不知道楼主有没有开发了，我正在研究，希望分享一下经验

楼主你好，我正在研究，你找到学习资料了么，希望分享下经验呢

**Comment by hecanlin** [comment]
> 我也想,楼主有答案了吗,文档里似乎没有安装手机端2ray的教程

你好，我最近也在研究这个，希望分享下经验呢，非常感谢

**Comment by hecanlin** [comment]
求iPhone端Vmess协议开发经验分享，非常感谢，hecanlin0731@163.com
