### ISSUE TITLE
有办法访问内网吗

### ISSUE THREAD

**Issue by 2427237507** [v2ray/discussion#407]
由于某些原因，我需要用到CDN去从家里访问学校内网
V2配置是ws协议
客户端配置全局访问并用Proxifer去辅助访问
然后用Proxifer中的代理检测工具检测内网地址，结果提示访问不了，而访问其他网页如ip111，能正确显示家里的地址，说明已经代理成功，但是内网却死活连不上，怎么办？（浏览器中也没连得上，但是v2ranN的信息框里有内网地址的连接记录）

**Comment by kingwilliam** [comment]
提供 服务器 和 客户端 config.json会容易处理

**Comment by happyTonakai** [comment]
是需要反向代理吗？
[https://toutyrater.github.io/app/reverse2.html](url)

**Comment by 2427237507** [comment]
> 是需要反向代理吗？
> [https://toutyrater.github.io/app/reverse2.html](url)

普通的代理是不行的吗？（就是可以通过学校的IP上网，内网却访问不了）
