### ISSUE TITLE
v2ray作为55r的前置代理的话会被混淆参数影响

### ISSUE THREAD

**Issue by Her0R0cket** [v2ray/discussion#408]
如题,55r的混淆设http_simple的话,最后v2连接的地址会被这个混淆的地址所覆盖,
比如说55r的连接地址是A,混淆地址是B,
v2在连接的时候会去检测B地址,然后连接B地址,最终导致后面的55r无法连接服务器

**Comment by kslr** [comment]
不支持混淆
