### ISSUE TITLE
请问v2ray为什么要用protobuf作为配置文件？

### ISSUE THREAD

**Issue by aegsea** [v2ray/discussion#409]
直接用json不好么，还把json转成protobuf，似乎把简单的程序复杂化了，代码弄的反倒很不清晰。

**Comment by kslr** [comment]
Google protobuf vs json

**Comment by aegsea** [comment]
最后给用户去使用的不都是json格式么？为何不直接用json，而要用json转protobuf，这样的系统设计不知道是为什么考虑的。
