### ISSUE TITLE
错误的Id也可以连接成功， 这是怎么回事

### ISSUE THREAD

**Issue by xkrumeng** [v2ray/discussion#414]
就是客户端配置在正确的ID后面再加上其它的字符，也可以连接成功， 
不知道这是不是Bug?  还是我的设置不正确导致的

v2ray服务器版本： 4.20.0
v2ray客户端版本： 2.41

我的服务器配置

![{3AAF12B5-F54E-4963-8598-1F1E076B7076}](https://user-images.githubusercontent.com/1468735/67559267-32e53200-f74b-11e9-865a-a043bb482091.png)
 
客户端配置如下：
![{D353E160-E5A6-4CD7-A611-C371808EEA99}](https://user-images.githubusercontent.com/1468735/67559344-57d9a500-f74b-11e9-8805-fc68a225bb96.png)

如上图的配置可以正常连接。 这没问题。然而，
如果我们将客户端的Id最后再加一个字符，使客户端的ID和服务器端的不一样。
比如 xxxxxx7b**1**, 比服务器设置的ID多了个1.再连接依旧可以连接上。 
但是如果把b改成c，而不是添加字符，则会报连接失败。

**Comment by kslr** [comment]
因为只取了固定长度

**Comment by xkrumeng** [comment]
@kslr 啥意思？ 没看懂， 是要通过哪个属性来设置就可以了吗？ 
还是它的ID验证机制就是截取固定长度的前面的字符来验证，超出长度的就不管了？

**Comment by xkrumeng** [comment]
> 因为只取了固定长度

@kslr 啥意思？ 没看懂， 是要通过哪个属性来设置就可以了吗？
还是它的ID验证机制就是截取固定长度的前面的字符来验证，超出长度的就不管了？

**Comment by Rucc1** [comment]
请参阅 UUID 标准格式：https://tools.ietf.org/html/rfc4122#section-4.1

**Comment by iochen** [comment]
> > 因为只取了固定长度
> 
> @kslr 啥意思？ 没看懂， 是要通过哪个属性来设置就可以了吗？
> 还是它的ID验证机制就是截取固定长度的前面的字符来验证，超出长度的就不管了？

See here
https://github.com/v2ray/v2ray-core/blob/9cfb2bfd51172059f1aa4c84642e79e56088ebe4/common/uuid/uuid.go#L66-L90
