### ISSUE TITLE
希望能优化高网速下CPU负载能力

### ISSUE THREAD

**Issue by mnihyc** [v2ray/discussion#415]
RT，跑上 70Mbps 后 CPU 就是 80%+

**Comment by mnihyc** [comment]
默认参数，限频 3299.99MHz
![](https://ftp.bmp.ovh/imgs/2019/10/30195184693d8d40.png)
![](https://ftp.bmp.ovh/imgs/2019/10/c79a379652f463df.png)
![](https://ftp.bmp.ovh/imgs/2019/10/6c81b7bdacb30cf3.png)

**Comment by kslr** [comment]
型号是什么 什么平台

**Comment by mnihyc** [comment]
~$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz
stepping        : 11
microcode       : 0x1
cpu MHz         : 3499.996
cache size      : 4096 KB

KVM 限一核

**Comment by johnrosen1** [comment]
> ~$ cat /proc/cpuinfo
> processor : 0
> vendor_id : GenuineIntel
> cpu family : 6
> model : 15
> model name : Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz
> stepping : 11
> microcode : 0x1
> cpu MHz : 3499.996
> cache size : 4096 KB
> 
> KVM 限一核

世界加钱可及

**Comment by mnihyc** [comment]
> > ~$ cat /proc/cpuinfo
> > processor : 0
> > vendor_id : GenuineIntel
> > cpu family : 6
> > model : 15
> > model name : Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz
> > stepping : 11
> > microcode : 0x1
> > cpu MHz : 3499.996
> > cache size : 4096 KB
> > KVM 限一核
> 
> 世界加钱可及

穷是原罪。

**Comment by johnrosen1** [comment]
> > > ~$ cat /proc/cpuinfo
> > > processor : 0
> > > vendor_id : GenuineIntel
> > > cpu family : 6
> > > model : 15
> > > model name : Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz
> > > stepping : 11
> > > microcode : 0x1
> > > cpu MHz : 3499.996
> > > cache size : 4096 KB
> > > KVM 限一核
> > 
> > 
> > 世界加钱可及
> 
> 穷是原罪。

nginx优化好，别用apache了，我nginx跑满1gbps cpu占用也只有10% https://www.johnrosen1.com/v2ray-cdn/

**Comment by JMDRSAT** [comment]
> > > > ~$ cat /proc/cpuinfo
> > > > processor : 0
> > > > vendor_id : GenuineIntel
> > > > cpu family : 6
> > > > model : 15
> > > > model name : Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz
> > > > stepping : 11
> > > > microcode : 0x1
> > > > cpu MHz : 3499.996
> > > > cache size : 4096 KB
> > > > KVM 限一核
> > > 
> > > 
> > > 世界加钱可及
> > 
> > 
> > 穷是原罪。
> 
> nginx优化好，别用apache了，我nginx跑满1gbps cpu占用也只有10% https://www.johnrosen1.com/v2ray-cdn/

主要是还有挂反代啥的，apache2 的 headers remoteip 等插件我比较熟悉，nginx 还要重新写配置，感觉很麻烦。

**Comment by mnihyc** [comment]
> > > > ~$ cat /proc/cpuinfo
> > > > processor : 0
> > > > vendor_id : GenuineIntel
> > > > cpu family : 6
> > > > model : 15
> > > > model name : Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz
> > > > stepping : 11
> > > > microcode : 0x1
> > > > cpu MHz : 3499.996
> > > > cache size : 4096 KB
> > > > KVM 限一核
> > > 
> > > 
> > > 世界加钱可及
> > 
> > 
> > 穷是原罪。
> 
> nginx优化好，别用apache了，我nginx跑满1gbps cpu占用也只有10% https://www.johnrosen1.com/v2ray-cdn/

主要是还有挂反代啥的，apache2 的 headers remoteip 等插件我比较熟悉，nginx 还要重新写配置，感觉很麻烦。

**Comment by johnrosen1** [comment]
> > > > > ~$ cat /proc/cpuinfo
> > > > > processor : 0
> > > > > vendor_id : GenuineIntel
> > > > > cpu family : 6
> > > > > model : 15
> > > > > model name : Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz
> > > > > stepping : 11
> > > > > microcode : 0x1
> > > > > cpu MHz : 3499.996
> > > > > cache size : 4096 KB
> > > > > KVM 限一核
> > > > 
> > > > 
> > > > 世界加钱可及
> > > 
> > > 
> > > 穷是原罪。
> > 
> > 
> > nginx优化好，别用apache了，我nginx跑满1gbps cpu占用也只有10% https://www.johnrosen1.com/v2ray-cdn/
> 
> 主要是还有挂反代啥的，apache2 的 headers remoteip 等插件我比较熟悉，nginx 还要重新写配置，感觉很麻烦。

那这样你就只能怪你自己，不能怪v2了咯

**Comment by kslr** [comment]
nginx 短短几行就可以解决apache的长篇大论，并且性能也更好

**Comment by mnihyc** [comment]
> > > > > > ~$ cat /proc/cpuinfo
> > > > > > processor : 0
> > > > > > vendor_id : GenuineIntel
> > > > > > cpu family : 6
> > > > > > model : 15
> > > > > > model name : Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz
> > > > > > stepping : 11
> > > > > > microcode : 0x1
> > > > > > cpu MHz : 3499.996
> > > > > > cache size : 4096 KB
> > > > > > KVM 限一核
> > > > > 
> > > > > 
> > > > > 世界加钱可及
> > > > 
> > > > 
> > > > 穷是原罪。
> > > 
> > > 
> > > nginx优化好，别用apache了，我nginx跑满1gbps cpu占用也只有10% https://www.johnrosen1.com/v2ray-cdn/
> > 
> > 
> > 主要是还有挂反代啥的，apache2 的 headers remoteip 等插件我比较熟悉，nginx 还要重新写配置，感觉很麻烦。
> 
> 那这样你就只能怪你自己，不能怪v2了咯

但是 htop 来看主要是 v2 占 CPU。。。。。。算了，到时候换成 nginx 吧）

**Comment by kslr** [comment]
你这个属于无头问题，没有日志没有配置，我都忘记这个issue了
