### ISSUE TITLE
能否实现进一步的线路分流

### ISSUE THREAD

**Issue by yiren11** [v2ray/discussion#42]
比如我想用某个特定代理看netflix,然后用其他代理做普通翻墙用途

**Comment by nobody3u** [comment]
这有点复杂，关键配置大概这样：
```
{
  "outbound": {
    "tag": "普通代理"
  },
  "outboundDetour": [
    {
      "tag": "netflix代理"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "AsIs",
      "rules": [
        {
          "type": "field",
          "outboundTag": "netflix代理",
          "domain": [
            "netflix.com"
          ]
        }
      ]
    }
  }
}
```
还是开2个v2ray-core，用两个浏览器会简单很多。

**Comment by yiren11** [comment]
这个是服务端还是客户端用的，能否给个模板，菜鸟不好意思

**Comment by yiren11** [comment]
{
	"log": {
		"loglevel": "error"
	},

	"inbound": {
		"protocol": "dokodemo-door",
		"port": 7913,
		"settings": {
			"address": "8.8.8.8",
			"port": 53,
			"network": "udp",
			"timeout": 0,
			"followRedirect": false
		}
	},
	"inboundDetour": [{
		"listen": "0.0.0.0",

		"port": 1280,
		"protocol": "dokodemo-door",
		"settings": {
			"network": "tcp,udp",
			"followRedirect": true
		}
	}],
	"outbound": {
		"tag": "fq",
		"protocol": "vmess",
		"settings": {
			"vnext": [{
				"address": "*",
				"port": 443,
				"users": [{
					"id": "e3a33655-a26d-4aee-b1ad-69a7f0a314ec",
					"alterId": 64,
					"security": "auto"
				}]
			}]
		},
		"streamSettings": {
			"network": "ws",
			"security": "tls",
			"tlsSettings": {
				"allowInsecure": false,
				"serverName": "*"
			},
			"wsSettings": {
				"connectionReuse": true,
				"path": "/",
				"headers": {
					"Host": "*"
				}
			}
		},
		"mux": {
			"enabled": true
		}
	},
	"outboundDetour": [{
		"tag": "netflix",

		"protocol": "vmess",
		"settings": {
			"vnext": [{
				"address": "*",
				"port": 443,
				"users": [{
					"id": "e3a33655-a26d-4aee-b1ad-69a7f0a314ec",
					"alterId": 64,
					"security": "auto"
				}]
			}]
		},
		"streamSettings": {
			"network": "ws",
			"security": "tls",
			"tlsSettings": {
				"allowInsecure": false,
				"serverName": "*"
			},
			"wsSettings": {
				"connectionReuse": true,
				"path": "/",
				"headers": {
					"Host": "*"
				}
			}
		},
		"mux": {
			"enabled": true
		}

	}],
	"routing": {
		"strategy": "rules",
		"settings": {
			"domainStrategy": "AsIs",
			"rules": [{
				"type": "field",
				"outboundTag": "netflix",
				"domain": [
					"netflix.com",
     "nflxext.com",
"rawgit.com",
"nflxso.net",
"gstatic.com",
"ip138.com"
   
				]
			}]
		}
	}
}

检验通过，普通代理有效果，但netflix的代理并未起效，能看下这个对吗（2个代理用了一样的ID）

**Comment by nobody3u** [comment]
inboundDetour那里有点看不明白，protocol应该是socks或者http吧？相应的setting也改下。
然后其他配置没问题，我本地测试了一下，已经有分流效果。
你把log改成info看是不是有什么其他因素影响。

**Comment by yiren11** [comment]
忘记说了，我是在软路由上用的，测试过了，用V2+omega就可以分流。用koolshare的lede X64的插件或者用V2+SSTAP这类自带翻墙模式的就不行

**Comment by nobody3u** [comment]
后面两个我都没用过，不知道什么原因。

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
