### ISSUE TITLE
咨询两个反向代理的配置问题

### ISSUE THREAD

**Issue by UJX6N** [v2ray/discussion#421]
反向代理我已经用起来了，现咨询两个配置相关的问题：

1、现我的反向代理是一对一，即一台内网v2ray跑bridge、一台外网v2ray跑portal。如果要实现一对多，即一台bridge、多台portal，场景是一台内网服务器需要被多个相距遥远的不同地点的外网访问。那么，bridge这台机器是应该在bridges下配多个bridge呢？还是可以在一个bridge下配多个domain，用domain来区隔适配多个portal的流量？看了主站上的反向代理说明，但没提及一个bridge下是否可以配置多个domain，如果一个bridge能配置多domain，貌似配置文件会简单些。

2、关于反向代理中mux，主站上的反向代理说明，提及在反向代理中，mux是自动启用的，不需要在outbound里再启用。但由于我不喜欢mux，在outbound里我又关掉了，从我的使用看，好像不影响反向代理的使用。请问反向代理默认启用mux的考虑是什么？

**Comment by ToutyRater** [comment]
1. 在bridges下配多个bridge，每一个bridge对应一个唯一的domain

2. 不清楚开发者的想法，猜测可能是为了达到长连接的效果吧

**Comment by UJX6N** [comment]
> 1. 在bridges下配多个bridge，每一个bridge对应一个唯一的domain
> 2. 不清楚开发者的想法，猜测可能是为了达到长连接的效果吧

感谢😄

看来要把配置文件做得非常简单的话，只有分成几个docker容器了
