### ISSUE TITLE
无法访问 浏览器报 500

### ISSUE THREAD

**Issue by ChokW** [v2ray/discussion#427]
![IMG_6174](https://user-images.githubusercontent.com/17397658/68538674-79759600-03b3-11ea-9df6-8f0625fea337.PNG)
Win 10 可以正常使用  同样的配置  同样的客户端 (v2.47)  Win 7 打开网页就报这个错误  是为啥....

**Comment by ChokW** [comment]
20191116.txt
`--------------------------------info[22:50:48]--------------------------------
System.Exception: Webserver Request 127.0.0.1

 
--------------------------------info[22:50:48]--------------------------------
System.Exception: Webserver Request 127.0.0.1

 
--------------------------------info[22:50:49]--------------------------------
System.Exception: Webserver Request 127.0.0.1

 
--------------------------------info[22:50:49]--------------------------------
System.Exception: Webserver Request 127.0.0.1

 
--------------------------------info[22:50:54]--------------------------------
System.Exception: Webserver Request 127.0.0.1

 
--------------------------------info[22:50:54]--------------------------------
System.Exception: Webserver Request 127.0.0.1

 
--------------------------------info[22:51:00]--------------------------------
System.Exception: Webserver Request 127.0.0.1

 
--------------------------------info[22:51:02]--------------------------------
System.Exception: Webserver Request 127.0.0.1

 
--------------------------------info[22:51:31]--------------------------------
System.Exception: Webserver Request 127.0.0.1

 
--------------------------------info[22:51:33]--------------------------------
System.Exception: Webserver Request 127.0.0.1

 
--------------------------------info[22:51:36]--------------------------------
System.Exception: Webserver Request 127.0.0.1

 
`

**Comment by ChokW** [comment]
![WechatIMG2](https://user-images.githubusercontent.com/17397658/69021531-0a232600-09f3-11ea-89b1-fd39e1c7348d.jpg)

**Comment by ChokW** [comment]
@kslr

**Comment by kslr** [comment]
10809 这个端口你检查一下其他服务设置
