### ISSUE TITLE
可以用v2ray transit 去 ssh嗎?

### ISSUE THREAD

**Issue by holahapi** [v2ray/discussion#428]
我是用 GCP VPS 裝v2ray。
我在香港有個router 裝了 DD WRT, 開啓了SSH

我現在是國內連 GCP v2ray沒問題

但以SSH 連 DDWRT 速度很慢, 如.  (某些原因，要用這個ip)
**國內電腦 Dynamic ports 轉 port22()SSH)** > **DDWRT(SSH)** > **外網**

請問可以用 v2 ray 做 transit 嗎? 如下
**國內電腦v2ray** > **GCP v2ray** > **DDWRT(SSH)** > **外網**
另外我需要在VPS裝其他軟件嗎?

**Comment by akiirui** [comment]
`ssh -o ProxyCommand='nc -x IP:PORT -X 5 %h %p' user@server`

Requirement: netcat (OpenBSD variant)

**Comment by holahapi** [comment]
謝謝你的回答 akiirui，我有些地方不太明白。
是要在 GCP VPS SSH 上輸入嗎？
我對linux 不太熟悉, "CentOS Linux 7 (Core)" 的VPS能用嗎? 

下面的field有沒有問題? server這個要填什麼?
IP> (DDWRT IP)
PORT > 22
user>	root 
server> ?

**Comment by akiirui** [comment]
@holahapi Google "SSH through a proxy" or "通過代理SSH"
