### ISSUE TITLE
传输层TLS有没有可能遭受中间人攻击？

### ISSUE THREAD

**Issue by 7dmail** [v2ray/discussion#430]
v2ray采用wss://传输层协议，如果中间人采用国内某根证书机构伪造签发服务端TLS证书，当前v2ray的传输层是否会被攻击解密？

**Comment by Kawasaki443** [comment]
赞同，如果能在客户端加入对CA证书的校验，可以避免这种问题。

**Comment by Rucc1** [comment]
@Kawasaki443 

![image](https://user-images.githubusercontent.com/42707745/69135573-44c0b780-0af4-11ea-8f85-063372d3ef9d.png)

**Comment by MN2yFii** [comment]
禁用某证书反而有点此地无银的感觉，数据安全还是交给加密算法来处理吧。

**Comment by Kawasaki443** [comment]
经过验证，发现v2ray已经具有C/S证书双向认证的功能了（具体见“tlsSettings”）。客户端和服务端任何一方的证书没有通过校验都无法建立代理连接，可以解决MITM的问题，一旦有人使用伪造证书都无法建立连接。
