### ISSUE TITLE
我这是被GFW盯上了

### ISSUE THREAD

**Issue by yadex** [v2ray/discussion#436]
很奇怪，我只要一运行v2ray或者ss, 一分钟内与服务器自动断开，并且ping不通了，ssh连不上，搬瓦工vultr和阿里云皆是如此。把程序关了，大概过了五分钟又好了，重复如此，已经进入一个死循环。

**Comment by klever1988** [comment]
一样

**Comment by fo2w** [comment]
虽然标题比较戏谑, 但是确实从昨天开始大面积出现了这种情况
