### ISSUE TITLE
server stops working for 1-2 minutes every once in a while

### ISSUE THREAD

**Issue by buter-brod** [v2ray/discussion#438]
Hello there!
I'm encountering a very strange problem (Android v2RayNG and v2ray.exe on Windows10).

Everything works well, but just for 5-10 minutes, then it stops both on PC and mobile.
After 1-2 minutes, it just works again.
Then, after 10 minutes, again stops working for 1-2 minutes. Then it works again.

Do you have any ideas what I should check? 

protocol - vmess, port 443, alterID=72 on all the clients and server.
I'm in China, VPS is in Hong Kong.

Thanks in advance.

**Comment by buter-brod** [comment]
I tried: 
- looking in top/htop logs to ensure CPU/Memory resources are sufficient during the 'irresponsive' state
- moving VPS to different physical locations (London, Hong Kong)
- thying another hosting provider
- trying different versions of ubuntu distributions
- playing with different alterId
- changing ports
- pinging my VPS from windows cmd 'ping' command during the 'irresponsive' stage - 100% packet loss.

still no luck.

**Comment by kslr** [comment]
You isp ?

**Comment by buter-brod** [comment]
> You isp ?

China Telecom.

**Comment by buter-brod** [comment]
also tried:
- manually restart v2ray just after 'irresponsive' time begins (via "systemctl restart v2ray" in server console) - doesn't help much, but probably irresponsive stage ends sooner (in 20-30 seconds after service restart)
- changing server's v2ray loglevel to 'info' and looking for errors (cannot find anything that looks suspicious when 'irresponsive' period starts)
- checking top/htop on server (again), now to look at cpu/memory percentage used by v2ray during 'irresponsive' state. It looks like v2ray either disappears from running processes or just too low on using resources that I can't find it. During 'normal' time I see 4-5 processes started with 'v2ray' command at the very top of the list with 5-6% CPU usage.

**Comment by kslr** [comment]
If you only provide "diagnostic information", then I can't help you.

**Comment by buter-brod** [comment]
[serverConfig.json.txt](https://github.com/v2ray/discussion/files/3882259/serverConfig.json.txt)
[clientConfig.json.txt](https://github.com/v2ray/discussion/files/3882260/clientConfig.json.txt)
[client_cannot_connect_log.txt](https://github.com/v2ray/discussion/files/3882265/client_cannot_connect_log.txt)
[servererrorLogs.txt](https://github.com/v2ray/discussion/files/3882269/servererrorLogs.txt)

> If you only provide "diagnostic information", then I can't help you.

I'm attaching server config, client config, server logs and client logs. 
If any other info I need to provide, let me know.

**Comment by kslr** [comment]
Server
1. Stop using mtproto
2. remove transport

Client
1. remove dns

**Comment by buter-brod** [comment]
2klsr, thanks for trying to help.
Here's what I tried after your suggestion:
-removed 'transport' section from server config
-removed mtproto section from server config
-removed 'dns' section from client config.
-changed uuids on client & server.

problem still persists, unfortunately.

**Comment by kslr** [comment]
Try https://guide.v2fly.org/advanced/wss_and_web.html

**Comment by buter-brod** [comment]
![Newfirewall_feature](https://user-images.githubusercontent.com/2940992/69477554-7dc59880-0e22-11ea-9a8c-19031caae5f1.jpg)

I found this message in one of telegram group chats, this behavior looks very similar to my problem... Anyway, I'm still open to any suggestions on what to do, is there any workaround.

**Comment by linxucc** [comment]
@buter-brod That's the problem, same to me, the wall has been upgraded, ordinary google search is fine under this protocol, but heavy traffic like watching video will get banned frequently. Try TLS, my problem just solved.

**Comment by whoisltd** [comment]
i have the same problem

**Comment by whoisltd** [comment]
did you fix it yet? @buter-brod
