### ISSUE TITLE
有没有APP上的使用文档啊？

### ISSUE THREAD

**Issue by FatChou** [v2ray/discussion#44]
有些东西没有注释，不知道怎么启动。
有些有注释，但不清楚怎么使用，比如：
GoSeqRef中的initWithRefnum:(int32_t)refnum obj:(id)obj;的注释中写明refnum必须有go side提供，怎么拿到这个呢？

**Comment by VictoriaRaymond** [comment]
不明白你在说什么，有没有上下文？

**Comment by FatChou** [comment]
不好意思，可能说的模糊不清。重新表述一下，对go这边的逻辑不熟悉
v2ray-core编译成.aar和.framework后，注释有点少。对于APP开发人员来说，没有参考的使用文档。
比如怎样启动读取配置，传递配置，然后启动core。
以下是我的尝试：
我尝试了只调用StartInstance编译后的方法，没有加载任何配置（不知道server是什么，协议是什么）就能使用，感觉还能分流。这样使用有默认配置吗？
我的主要目的是想知道APP如何正确的调用编译后库的api。
