### ISSUE TITLE
v2ray tls ws 正常工作，套上腾讯云CDN失败。

### ISSUE THREAD

**Issue by matianhe** [v2ray/discussion#443]

**Comment by matianhe** [comment]
不用CDN 正常翻，nginx日志121.69.235.22 - - [25/Nov/2019:14:04:24 +0800] "GET /goout HTTP/1.1" 101 270 "-" "Go-http-client/1.1"
加上腾讯云域名的CDN就失败。nginx日志：123.151.124.111 - - [25/Nov/2019:00:18:05 +0800] "GET /goout HTTP/1.1" 404 169 "-" "Go-http-client/1.1"

**Comment by kslr** [comment]
404 检查你的腾讯云配置

**Comment by matianhe** [comment]
-
