### ISSUE TITLE
Quick Question: Is the websocket just for CDN or there are some other advantages? If I don't use CDN, is TCP+TLS good enough?

### ISSUE THREAD

**Issue by linxucc** [v2ray/discussion#444]
Hi everyone,

I have been using vmess protocol with TCP direct connection in the past few months, and it works pretty well for me. 

But since last week, it seems the Wall is upgraded, just like other folks reported, if there are some heavy traffic on it like watching a youtube video, after a minute or two the connection will be blocked for about 3 minutes, then it will be back after several minutes, then blocked again, it just repeats. So I think I have to make a configuration upgrade to solve this problem. After some research I think make it a TLS connection could be good enough to trick the wall to believe it's a valid App connection.

After a quick search, I have a question now: 

**It seems all the tutorials are telling people to use websocket + TLS, so, is the use of websocket with TLS a necessity? Besides the support for CDN traffic forwarding, is there any extra advantage of using websocket+TLS over TCP+TLS ?** 

Because the direct connection to my server is so good so if it can connect it directly I will not use a CDN, but if the websocket does have some other advantages even if I don't use CDN, I'll use it.

I don't see much talks about it, nobody explains what exactly is the advantage of websocket, most articles are all about how to setup things, so I come here to ask you pro guys hope to find some answer.

Thanks.

**Comment by kslr** [comment]
1. websocket can be processed as normal traffic (nginx, ), Hiding behind the website
2. cdn is not required

**Comment by linxucc** [comment]
@kslr 
Thank you, clear answer I get it... besides CDN It's mostly about to have a valid (or fake) website and a v2ray service on the same machine same port... 

Another question: If my server is dedicated for proxy use, no website on it, and TCP+TLS on 443 works fine, for now, does this setup have some vulnerability? or it's more likely to be detected if you run TLS without a fake or valid website on the same host?

**Comment by kslr** [comment]
There is no data indicating that this must be done

**Comment by linxucc** [comment]
OK, thank you so much for answering these questions, I think I'll stick with the TCP+TLS, no need for websocket at this time. 
Thanks again for your time. Hope this discussion could help others with the same hesitation.
