### ISSUE TITLE
v2ray是否支持通过代理连接网络？

### ISSUE THREAD

**Issue by Donny8611** [v2ray/discussion#445]
公司网络环境是大内网，必须通过设置指定的HTTP代理才可以上外网。v2ray是否支持通过代理链接服务器呢？

**Comment by kslr** [comment]
支持

**Comment by Donny8611** [comment]
额。那个……怎么直接就关闭了。
我这么问显然就是不会啊。能否说下怎么设置。。

**Comment by Donny8611** [comment]
虽然大佬事务繁忙，但……这回复也太扎心了。

就好像以前一个段子说，发电报问：你有某某某的地址吗？回复：有

**Comment by kslr** [comment]
https://v2ray.com/chapter_02/protocols/http.html
将其作为出站协议

**Comment by Donny8611** [comment]
不好意思。。教程只给出了片段。实在不知道放在哪里？
尝试了一下午。不是依然直连vnext就是配置错误不能启动。
能否给个config示例。。。。

**Comment by kslr** [comment]
@xuebaxi

**Comment by xuebaxi** [comment]
你可以参考这一篇
https://guide.v2fly.org/app/parent.html

**Comment by Donny8611** [comment]
非常感谢。已经了解了。就是另外新建一个http出口，然后在原vmess出口内设置proxySettings为那个HTTP。
