### ISSUE TITLE
support for IP HASH load balancing

### ISSUE THREAD

**Issue by itshaadi** [v2ray/discussion#446]
![ip-hash](https://user-images.githubusercontent.com/10201704/69724764-cf776700-1131-11ea-8f1a-8d1c0ea414c1.jpeg)

A little background to why this is urgent, On Friday, 15 November Iran began to shutdown The internet and disruptions progressed to a total internet blackout on Saturday, cutting off Iranians from the rest of the world.

meanwhile, Iranian data centers had access to WAN, during those days I managed to setup a bridge between my network and a server in Iran, and that server connected to outside world. (using vmess+ws+tls for first-hop and vmess+ws+tls+cf for second-hop).

unfortunately, Uplink and Downlink speed is limited by data centers, basically you can't provide internet for even 15 people with just one first-hop server.

so, if v2ray would support ip-hash load balancing we could buy a bunch of low spec servers and balance the traffic evenly.

the problem Is, client MUST balance it's requests in using a round-robin (or random) scheduling (which v2ray already supports this type of balancing)

BUT, first-hop servers MUST know which client, went through what second-hop server before, so that their IP wouldn't change constantly.

**Comment by StoneMoe** [comment]
This is a important feature for real world application.
Many server verifying IP address during a sequence of request for one transaction, client's egress needs to be consistent.

**Comment by kslr** [comment]
domain is more reliable

**Comment by StoneMoe** [comment]
> domain is more reliable

Thanks for your quick response!

Do you mean configure consistent egress per domain(or ip) in routing config? That'll be painful for configuring...
And considering we are talking about the underlying connection selection mechanism, domain is not available anytime(e.g. transparent proxy), so domain seems not that reliable for this case for load balancing.

Similar discussion:
https://github.com/v2ray/v2ray-core/issues/2469

**Comment by kslr** [comment]
You are right, we need multiple strategies.
