### ISSUE TITLE
如何针对不同用户给不同的访问权限？

### ISSUE THREAD

**Issue by Clive1990** [v2ray/discussion#447]
不太会用V2RAY，根据别人的教程可以正常使用，但是，想问问能不能实现2个用户，利用不同的端口使用vmess协议，服务器根据端口来判断，针对特定端口不予访问特定网页呢？
这样写要怎么改？还是说这个没办法实现？

`{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": [
{
    "port": 10080,
    "protocol": "vmess",
    "tag":"inbound10080",
    "settings": {
      "clients": [
        {
          "id": "b831381d-6324-4d53-ad4f-8cda48b30811",
          "level": 1,
          "alterId": 64
        }
      ]
    }
  }

],
  "inboundDetour": [
{
    "port": 10087,
    "protocol": "vmess",
    "tag":"inbound10087",
    "settings": {
      "clients": [
        {
          "id": "b831381d-6324-4d53-ad4f-8cda4efg0811",
          "level": 1,
          "alterId": 64
        }
      ]
    }
  }
  ],
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        },
        {
          "type": "field",
          "domain": [
            "geosite:facebook",
            "domain:youtube.com"
          ],
          "inboundTag":"inbound10080",
          "outboundTag": "blocked"
        }
      ]
    }
  }
}`

**Comment by lelandyang** [comment]
V2Ray开发的初衷应该是给一个人使用的，可以通过共享GUID给多个用户。你这个功能应该是没有的。不过可以在服务器增加一层反向代理，客户端连接到的不是V2Ray的服务器，而是你的反代程序，之后流量传送到不同的V2Ray实例可以实现管控。
