### ISSUE TITLE
ss-tunnel 功能的替代

### ISSUE THREAD

**Issue by xixixihaha** [v2ray/discussion#449]
之前一直使用ss的三个模块，现在开始使用V2RAY来替代SS。
ss-local 测试可以完美替换，甚至可以兼容。
但是ss-tunnel 该如何实现呢？没找到相关的办法。
期望大侠释疑 感谢🙏

**Comment by kslr** [comment]
https://v2ray.com/chapter_02/protocols/dokodemo.html

**Comment by xixixihaha** [comment]
您说的好像不对： 虽然 Dokodemo door写了可以监听一个本地端口，并把所有进入此端口的数据发送至指定服务器的一个端口，从而达到端口映射的效果
但是它的参数里面没有本地端口，只有远端服务器和端口的选项， 只可以做到 ss-tunnel 的-L 选项 
ss-tunnel 有一个入站端口的 选项 -l  没有对应的设置啊 @kslr

**Comment by xixixihaha** [comment]
@kslr 我仔细阅读了文档 好像明白了 我去试下 感谢！
