### ISSUE TITLE
在linux Bridge server上配合netfilter来实现透明翻墙

### ISSUE THREAD

**Issue by necokeine** [v2ray/discussion#450]
您好，v2ray开发者

我现在在使用一种比较特别的v2ray透明翻墙使用方式，但是遇到了一些特别的问题。我想在这里拿出来讨论下，顺便看看能不能整理一个文档出来。
我试着在一个局域网中部署了一个bridge server，然后所有要翻墙的设备全部挂在这个bridge server下面，这样所有需要翻墙的设备和不需要翻墙的设备全都处于一个网段当中，互相可以访问，也不需要自己搭建dhcp服务器，只需要forward一下dhcp包就可以搞定。
我的配置之前都工作的满正常的，但是最近我试图修改下配置来强化我的环境（从redirect转移到tproxy），但是遇到了一些问题。为了解决这些问题，我似乎需要更多的知识。
我有一些问题希望在这里讨论
1. 我这样的用法有着什么先天性的缺陷或者不合理的地方么？
2. TProxy只允许出现在mangle表当中，我有办法把forwarding的流量拿过来到这个表当中么？

**Comment by xuebaxi** [comment]
你是如何实现转发的。

**Comment by necokeine** [comment]
> 你是如何实现转发的。

我之前是在nat表的prerouting当中截取了流量，然后转发出去，我现在遇到的问题就是bridge流量貌似没经过mangle表，然后不工作了。。。
