### ISSUE TITLE
如何伪装/隐藏 v2ray服务器的ip？求助

### ISSUE THREAD

**Issue by a9964281667** [v2ray/discussion#451]
有一些网站(Netflix等)屏蔽了一些热门数据中心/机房的ip，导致我即使能翻墙，也上不了netfilx。我实在不想换另一个vps

请问 如果我在自己服务器上使用vpn（PPTP/Openvpn），即把服务器作为vpn的客户端，v2ray还能正常工作吗？还有别的办法吗？

**Comment by kslr** [comment]
可以
