### ISSUE TITLE
Amazon Lightsail 主机，Apache WebSocket不成功，哪里配置不对？

### ISSUE THREAD

**Issue by jj8431** [v2ray/discussion#453]
使用V2RAY自生成的证书，用TCP+TLS没问题，证书用在apache上也没问题，除了提示证书不安全外，浏览器https可正常工作。现在v2ray想设置成WS方式，无法使用，请帮我看一下是哪里设置有问题？

服务器设置：
{
	"log": 
  	{
		"loglevel": "info",
		"access": "/var/log/v2ray/access.log",
		"error": "/var/log/v2ray/error.log"
  	},
  	"inbounds": 
	[
		{
    			//"port": 443,
			"port": 20000,
			"listen": "127.0.0.1",
    			"protocol": "vmess",
    			"settings": 
			{
      				"clients": 
				[
        				{
          					"id": "053d44c5-b8c2-46cc-8ffd-ba6002a7b51c",
          					"level": 1,
          					"alterId": 64
        				}
      				]
    			},
    			"streamSettings": 
			{
				//"network": "tcp",
				//"security": "tls",
				//"tlsSettings": 
				//{
	    			//	"certificates": 
				//	[
				//		{
				//			"certificateFile": "/etc/v2ray/stream_cert.pem",
				//			"keyFile": "/etc/v2ray/stream_key.pem"
				//		}
	    			//	]
				//}
				"network": "ws",
				"wsSettings":
				{
					"path": "/ray"
				}
    			}
		}
  	],
  	"outbounds": 
	[
		{
    			"protocol": "freedom",
    			"settings": 
			{
			}
  		},
		{
    			"protocol": "blackhole",
    			"settings": 
			{
			},
    			"tag": "blocked"
  		}
	],
  	"routing": 
	{
    		"rules": 
		[
      			{
        			"type": "field",
        			"ip": ["geoip:private"],
        			"outboundTag": "blocked"
      			}
    		]
  	}
}
使用 "//" 注释掉的部分设置，客户端 BifrostV 使用 TCP+TLS+Allow Insecure的模式，可以正常工作。

Apache VirtualHost 部分基本照抄官网上的设置指南，但有些原本设置没有删除，设置内容如下(隐去主机名部分）：

<VirtualHost _default_:443>
  SSLEngine on
ServerName stream.******.*****
SSLCertificateFile "/etc/v2ray/stream_cert.pem"
SSLCertificateKeyFile "/etc/v2ray/stream_key.pem"

  <Location "/ray">
    ProxyPass ws://127.0.0.1/20000/ray/ upgrade=WebSocket
    ProxyAddHeaders Off
    ProxyPreserveHost On
    RequestHeader append X-Forwarded-For %{REMOTE_ADDR}s
  </Location>
            
  <Directory "/opt/bitnami/apache2/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride All
    <IfVersion < 2.3 >
      Order allow,deny                          
      Allow from all
    </IfVersion>
    <IfVersion >= 2.3 >
      Require all granted
    </IfVersion>
  </Directory>

  # Error Documents
  ErrorDocument 503 /503.html
        
  # Bitnami applications installed with a prefix URL (default)
  Include "/opt/bitnami/apache2/conf/bitnami/bitnami-apps-prefix.conf"
</VirtualHost>

安卓BifrostV客户端配置如下（隐去主机名部分）
{
  "log": {
    "loglevel": "none"
  },
  "inbounds": [],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "stream.******.*****",
            "port": 443,
            "users": [
              {
                "id": "053d44c5-b8c2-46cc-8ffd-ba6002a7b51c",
                "alterId": 64,
                "security": "auto",
                "level": 1
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "serverName": "stream.******.******",
          "allowInsecure": true
        },
        "wsSettings": {
          "path": "\/ray",
          "headers": {
            "Host": "stream.******.******"
          }
        }
      },
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "block"
    }
  ],
  "policy": {
    "levels": {
      "1": {
        "handshake": 6,
        "connIdle": 300,
        "uplinkOnly": 2,
        "downlinkOnly": 5,
        "bufferSize": 2
      }
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private",
          "geoip:cn"
        ],
        "outboundTag": "direct"
      }
    ]
  }
}

问题现象是无法连接，手机上只能看到有上行的数据，下行数据始终为0.
V2ray 的log内容为空， apache的 access_log 文件中有大量类似这样的错误(已隐去本人IP，用***代替）：
127.0.0.1 - - [04/Dec/2019:06:17:40 +0000] "GET /20000/ray/ HTTP/1.1" 404 208
127.0.0.1 - - [04/Dec/2019:06:17:40 +0000] "GET /20000/ray/ HTTP/1.1" 404 208
***.***.***.*** - - [04/Dec/2019:06:17:40 +0000] "GET /ray HTTP/1.1" 200 -
***.***.***.*** - - [04/Dec/2019:06:17:40 +0000] "GET /ray HTTP/1.1" 200 -
127.0.0.1 - - [04/Dec/2019:06:17:41 +0000] "GET /20000/ray/ HTTP/1.1" 404 208
127.0.0.1 - - [04/Dec/2019:06:17:41 +0000] "GET /20000/ray/ HTTP/1.1" 404 208
***.***.***.*** - - [04/Dec/2019:06:17:41 +0000] "GET /ray HTTP/1.1" 200 -
***.***.***.*** - - [04/Dec/2019:06:17:41 +0000] "GET /ray HTTP/1.1" 200 -
127.0.0.1 - - [04/Dec/2019:06:17:41 +0000] "GET /20000/ray/ HTTP/1.1" 404 208
127.0.0.1 - - [04/Dec/2019:06:17:41 +0000] "GET /20000/ray/ HTTP/1.1" 404 208
***.***.***.*** - - [04/Dec/2019:06:17:41 +0000] "GET /ray HTTP/1.1" 200 -
***.***.***.*** - - [04/Dec/2019:06:17:41 +0000] "GET /ray HTTP/1.1" 200 -

请问这是哪里出了问题？

**Comment by kslr** [comment]
404 路径错误

**Comment by jj8431** [comment]
> 404 路径错误

能进一步解释一下吗？是说 /20000/ray/ 这个路径不存在？  20000是我设置的端口号，那应该怎么修改呢？

**Comment by kslr** [comment]
你这个排版看得我头疼
Guide.v2fly.org

**Comment by jj8431** [comment]
> 你这个排版看得我头疼，照着对比一下
> Guide.v2fly.org

非常非常抱歉，没怎么用过github, 不知道为什么帖过来的代码在编辑时还有缩进，发出来以后前面的tab全都没有显示，所以每行都变成顶头了，还请 kslr 和今后的观众原谅。

问题我已经找到了，最根本的问题，是我不小心把apache配置中的一句写错了
ProxyPass ws://127.0.0.1/20000/ray/ upgrade=WebSocket
应该是
ProxyPass ws://127.0.0.1:20000/ray upgrade=WebSocket

非常感谢 kslr 的帮助！
