### ISSUE TITLE
求助，使用 Nginx+tls+h2  过程中遇到问题。（非 Nginx 反代 http2 问题）

### ISSUE THREAD

**Issue by palejohn** [v2ray/discussion#455]
我是小白。
之前一直用 Nginx+ws+tls 用的挺好的，最近想尝试 tls1.3 + http2 的配置，于是我弄完后出现了一个问题，我不知道如何配置客户端用 h2的传输方式与服务器的 Nginx 进行通信。
具体情况是：
在服务器端的 Nginx 和 V2ray 都配置完后，反代的别人的网站正常，chrome 里 f12 打开可以看到访问网页已经是 tls1.3 和 h2 了，但是 v2ray 客户端的配置我不知道该怎么做才能正常用 h2 的方式与服务器端正常连上，当我在客户端用 ws 配置可以正常连接，一旦改成 h2 就无法连接服务器。
服务器端 V2ray 4.21.3
客户端 V2ray 为 V2rayN v2.53+V2ray core 4.21.3
Nginx  1.16.1
所有配置除了 go.sh 脚本外未使用任何脚本，均为参考中英文网贴后自行配置。

下面贴出我的配置： （我的主机域名已用 www.myhost.com代替）

Nginx 配置：

server {
  listen  80;
  listen  443 ssl http2 ; 
  server_name    www.myhost.com;
  if ($scheme = http) {
        return 301 https://$server_name$request_uri; 
                                }

  ssl_certificate /etc/v2ray/fullchain.pem;
  ssl_certificate_key /etc/v2ray/privkey.pem;
  ssl_session_cache shared:SSL:10m;
  ssl_session_timeout 10m;
  ssl_session_tickets off;

  ssl_protocols TLSv1.3;
  ssl_prefer_server_ciphers off;  
  
  

  if ($request_method  !~ ^(POST|GET)$) {
        return  444;
                  }

   add_header X-Frame-Options DENY;
   add_header X-XSS-Protection "1; mode=block";
   add_header X-Content-Type-Options nosniff;
   add_header Strict-Transport-Security max-age=63072000 always;

        location /mypath {                      
        proxy_redirect off; 
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        if ($http_upgrade = "websocket" ) {
            proxy_pass http://127.0.0.1:10001;
                                                                       }
                                 }

        location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Accept-Encoding "";
        proxy_pass https://反代目标网站.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Accept-Language "zh-CN";
        sub_filter 反代目标网站.com www.myhost.com;
        sub_filter_once off;
        proxy_redirect off;
        proxy_set_header Host 反代目标网站.com;
                           }
}

服务器端 V2ray 配置：

{
  "inbounds": [
    {
      "port": 10001,
      "listen":"127.0.0.1",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "my UUID", 
            "level": 1,
            "alterId": 4
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
        "path": "/mypath"
        }
      }
    }
  ],
  "outbounds": [
      {
      "protocol": "freedom",
      "settings":  {}
                           },
      {
       "protocol": "blackhole",
       "settings": {},
        "tag": "blocked"
      }
                            ],
    "routing": {
         "rules":  [
              {
                  "type": "field",
                  "ip":  ["geoip:private"],
                  "outboundTag": "blocked"
             }
          ]
      }
}

客户端 V2ray 配置： 
我仅列出可以正常与服务端通讯的传输协议为 ws 的完整配置，而无法正常使用的 h2 协议我仅仅列出 streamSettings 部分。

{
  "policy": null,
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "proxy",
      "port": 10086,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": false,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": false,
        "ip": null,
        "address": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "www.myhost.com",
            "port": 443,
            "users": [
              {
                "id": "my UUID",
                "alterId": 4,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": null
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/mypath",
          "headers": null
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": false
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "stats": null,
  "api": null,
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "ip": null,
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "block",
        "ip": null,
        "domain": []
      },
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "direct",
        "ip": [
          "geoip:private"
        ],
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "direct",
        "ip": [
          "geoip:cn"
        ],
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "direct",
        "ip": null,
        "domain": [
          "geosite:cn"
        ]
      }
    ]
  }
}

如果将以上客户端配置  streamSettings 改成 h2 则会无法连接且报错，此时，反代的目标网页还是好的，唯独客户端 V2ray 无法与服务端连接。
配置如下：

  "streamSettings": {
        "network": "h2",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": null
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": null,
        "httpSettings": {
          "path": "/mypath",
          "host": null
        },
        "quicSettings": null
      },
       "mux": {
        "enabled": false

客户端提示信息如下：

配置成功
Vmess-GIEE(www.myhost.com:443)
启动服务(12/8/2019 12:58:02 AM)......
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
2019/12/08 00:58:03 [Debug] v2ray.com/core/app/log: Logger started
2019/12/08 00:58:03 [Warning] v2ray.com/core: V2Ray 4.21.3 started
2019/12/08 00:58:08 [Info] [2047447540] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.startpage.com:443
2019/12/08 00:58:08 [Info] [2047447540] v2ray.com/core/app/dispatcher: default route for tcp:www.startpage.com:443
2019/12/08 00:58:08 tcp:127.0.0.1:52471 accepted tcp:www.startpage.com:443 [proxy] 
2019/12/08 00:58:11 [Warning] [2047447540] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/http: failed to dial to tcp:www.myhost.com:443 > Put https://www.myhost.com:443/mypath: stream error: stream ID 1; PROTOCOL_ERROR v2ray.com/core/transport/internet/http: failed to dial to tcp:www.myhost.com:443 > Put https://www.myhost.com:443/mypath: stream error: stream ID 3; PROTOCOL_ERROR v2ray.com/core/transport/internet/http: failed to dial to tcp:www.myhost.com:443 > Put https://www.myhost.com:443/mypath: stream error: stream ID 5; PROTOCOL_ERROR v2ray.com/core/transport/internet/http: failed to dial to tcp:www.myhost.com:443 > Put https://www.myhost.com.one:443/mypath: stream error: stream ID 7; PROTOCOL_ERROR v2ray.com/core/transport/internet/http: failed to dial to tcp:www.myhost.com:443 > Put https://www.myhost.com:443/pen: stream error: stream ID 9; PROTOCOL_ERROR] > v2ray.com/core/common/retry: all retry attempts failed
2019/12/08 00:58:11 [Info] [2047447540] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

麻烦对小弟的配置进行指导，我是小白，打扰了~
谢谢！

**Comment by johnrosen1** [comment]
nginx不支持h2反代

**Comment by palejohn** [comment]
> nginx不支持h2反代

是的，我明白，我现在不需要 Nginx 反代 h2 给后面的 V2ray，我只想要 Nginx 能“接到”来自客户端的 h2，然后打包成 websocket 给后方的 V2ray 就可以了，我不知道该怎么配置，我是小白，希望我这么说能您能明白。

**Comment by kirin10000** [comment]
nginx反代不支持http2，我也在研究这个东西，我还想尝试web+http3(quic)呢
参考https://trac.nginx.org/nginx/ticket/923

**Comment by palejohn** [comment]
> nginx反代不支持http2，我也在研究这个东西，我还想尝试web+http3(quic)呢
> 参考https://trac.nginx.org/nginx/ticket/923

谢谢，这个我也看过了，所以我就没往反代 http2 哪方面去想了，小白如我仅仅是想要客户端与 Nginx 之间用 http2 连上，至于后面反代给 V2ray 的话，websocket 就够了。

**Comment by kirin10000** [comment]
> > nginx反代不支持http2，我也在研究这个东西，我还想尝试web+http3(quic)呢
> > 参考https://trac.nginx.org/nginx/ticket/923
> 
> 谢谢，这个我也看过了，所以我就没往反代 http2 哪方面去想了，小白如我仅仅是想要客户端与 Nginx 之间用 http2 连上，至于后面反代给 V2ray 的话，websocket 就够了。

使用nginx的log文件查看，当客户端选择http2时，客户端与服务端建立的时http2连接

**Comment by palejohn** [comment]
> > > nginx反代不支持http2，我也在研究这个东西，我还想尝试web+http3(quic)呢
> > > 参考https://trac.nginx.org/nginx/ticket/923
> > 
> > 
> > 谢谢，这个我也看过了，所以我就没往反代 http2 哪方面去想了，小白如我仅仅是想要客户端与 Nginx 之间用 http2 连上，至于后面反代给 V2ray 的话，websocket 就够了。
> 
> 使用nginx的log文件查看，当客户端选择http2时，客户端与服务端建立的时http2连接

谢谢，我也不知道我能不能看懂，但先按您说的看看 log。

**Comment by palejohn** [comment]
> > > nginx反代不支持http2，我也在研究这个东西，我还想尝试web+http3(quic)呢
> > > 参考https://trac.nginx.org/nginx/ticket/923
> > 
> > 
> > 谢谢，这个我也看过了，所以我就没往反代 http2 哪方面去想了，小白如我仅仅是想要客户端与 Nginx 之间用 http2 连上，至于后面反代给 V2ray 的话，websocket 就够了。
> 
> 使用nginx的log文件查看，当客户端选择http2时，客户端与服务端建立的时http2连接

我不知道这么做对不对，把那个error log level 设置为 debug 后，查看位于 /var/log/nginx/error.log，可以看到刚刚出现的日志，因为我不懂复制，只能看着手打出来，基本就是重复以下信息：
事件时间 +  "^(POST|GET)$" does not match "PUT", client: 我的客户端ip, server: 我的服务器域名, request: "PUT /mypath HTTP/2.0", host: "www.example.com"
不知道这个日志有没有用？能看出问题吗？

**Comment by bigbugcc** [comment]
> 谢谢，我也不知道我能不能看懂，但先按您说的看看 log。



> 



> > nginx不支持h2反代
> 
> 是的，我明白，我现在不需要 Nginx 反代 h2 给后面的 V2ray，我只想要 Nginx 能“接到”来自客户端的 h2 就行，至于 Nginx 跟后方的 V2ray 沟通，用 websocket 就可以了，但我不知道该怎么配置，我是小白，希望我这么说能您能明白。

这个理论在可行性上就是矛盾的，http2就是websocks的升级版，其次在nginx这里 怎么把http2流量转成ws这还是个问题，那都已经使用http2就没有必要在用ws了。
