### ISSUE TITLE
NAT Traversal有什么好办法？

### ISSUE THREAD

**Issue by okudayukiko** [v2ray/discussion#456]
准备出国，以后想通过V2Ray访问大陆网站。
我的想法是在国内设台V2Ray+NAT Traversal的电脑（比如Linux路由器），用SSH进行NAT Traversal。申请静态IP比较麻烦而且Open port不安全。
但我设置的V2Ray端口范围很大，手动一条条敲以下命令很麻烦：
ssh -L localhost:80:remote-vps-server:80 root@remote-vps-server
ssh -L localhost:81:remote-vps-server:81 root@remote-vps-server
...
ssh -L localhost:200:remote-vps-server:200 root@remote-vps-server

**Comment by johnrosen1** [comment]
ddns了解一下  https://www.johnrosen1.com/ubuntu-router/ nat的话直接端口映射就行
