### ISSUE TITLE
v2ray win端断流

### ISSUE THREAD

**Issue by jason-odd** [v2ray/discussion#464]
v2ray版本:2.22+4.18内核 用的别人的2个机场 pac和全局都断流 改了v2和win的 dns无效 没办法了
希望正常看youtube 

]帮忙看看吧

- 

 v2客户端配置
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "port": 1080,
      "listen": "0.0.0.0",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "119.x.x53.xxx",
            "port": 589,
            "users": [
              {
                "id": "B34B64B4-E118-ECF4-58x1-7D14A362BEC7",
                "alterId": 1,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": null
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/",
          "headers": {
            "Host": "play.itunes.apple.com"
          }
        },
        "httpSettings": null
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "dns": {
    "servers": [
      "119.29.29.29",
      "8.8.8.8"
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "outboundTag": "proxy",
        "ip": null,
        "domain": [

**Comment by kslr** [comment]
你先排个版，添加上日志

**Comment by jason-odd** [comment]
一瞬间就断流了 然后刷新就好了 一会再次断流  不知怎么回事
### 期望的过程
v2ray和核都是最新的

1.不再断流
`{
  "policy": null,
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "proxy",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "address": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "xxx.x.xxx.106",
            "port": xx9,
            "users": [
              {
                "id": "B34B64xx-E118-ECF4-5841-7D14A362BEC7",
                "alterId": 1,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": null,
        "tlsSettings": null,
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/",
          "headers": {
            "Host": "play.itunes.apple.com"
          }
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "stats": null,
  "api": null,
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "ip": null,
        "domain": ###null2019/12/13 13:57:42 tcp:127.0.0.1:60442 accepted tcp:graph.instagram.com:443 [proxy] 
2019/12/13 13:57:51 tcp:127.0.0.1:60444 accepted tcp:graph.instagram.com:443 [proxy] 
2019/12/13 13:58:45 tcp:127.0.0.1:60448 accepted tcp:clients4.google.com:443 [proxy] 
2019/12/13 13:59:01 tcp:127.0.0.1:60451 accepted tcp:clients1.google.com:443 [proxy] 
2019/12/13 13:59:30 tcp:127.0.0.1:60454 accepted tcp:5-edge-chat.facebook.com:443 [proxy] 
2019/12/13 13:59:30 tcp:127.0.0.1:60456 accepted tcp:www.facebook.com:443 [proxy] 
2019/12/13 14:01:14 tcp:127.0.0.1:60465 accepted tcp:translate.google.com:443 [proxy] 
2019/12/13 14:01:14 tcp:127.0.0.1:60467 accepted tcp:www.gstatic.com:443 [proxy] 
2019/12/13 14:02:19 tcp:127.0.0.1:60472 accepted tcp:scontent-hkg3-1.xx.fbcdn.net:443 [proxy] 
2019/12/13 14:02:25 tcp:127.0.0.1:60474 accepted tcp:mtalk.google.com:5228 [proxy] 
2019/12/13 14:02:28 tcp:127.0.0.1:60476 accepted tcp:scontent.xx.fbcdn.net:443 [proxy] `

**Comment by jason-odd** [comment]
### {
  "policy": null,
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "proxy",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "address": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "x.x.x.x",
            "port": 589,
            "users": [
              {
                "id": "xx4B64B4-E118-ECF4-5841-7D14A362BEC7",
                "alterId": 1,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": null,
        "tlsSettings": null,
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/",
          "headers": {
            "Host": "play.itunes.apple.com"
          }
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "stats": null,
  "api": null,
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "ip": null,
        "domain": null

**Comment by jason-odd** [comment]
您正在使用哪个版本的V2Ray？（如果服务器和客户端使用了不同版本，请注明）
客户端v.2.53 无服务端用的机场  core最新
使用Chrome通过Socks / VMess代理观看YouTube视频。
你看到的不正常的现象是什么？（请描述具体现象，某些访问超时，TLS证书错误等）
刚打开工具不断流 用一段时间断流
你期待看到的正确表现是怎样的？
不断流打开网页流畅看视频
 请附上你的配置（提交问题前请隐藏服务器端IP地址）。
### {
  "policy": null,
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "proxy",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "address": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "xxxxxx",
            "port": 589,
            "users": [
              {
                "id": "xxxxxx-xxxx-ECF4-5841-7D14A362BEC7",
                "alterId": 1,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": null,
        "tlsSettings": null,
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/",
          "headers": {
            "Host": "play.itunes.apple.com"
          }
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "stats": null,
  "api": null,
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "ip": null,
        "domain": null
### 断流的一瞬间v2日志没响应
2019/12/14 14:37:25 tcp:127.0.0.1:58514 accepted tcp:r4---sn-i3b7kn7r.googlevideo.com:443 [proxy] 
2019/12/14 14:37:25 tcp:127.0.0.1:58515 accepted tcp:r4---sn-i3b7kn7r.googlevideo.com:443 [proxy]

**Comment by jason-odd** [comment]
@kslr 小白  排版不清楚 能凑合看看吗？...

**Comment by kslr** [comment]
play.itunes.apple.com 这个是你的机场要求写的吗，从你日志里什么也没有

**Comment by jason-odd** [comment]
> play.itunes.apple.com 这个是你的机场要求写的吗，从你日志里什么也没有

不是 这是默认的文本 我没动 这是断流原因吗？应该写什么？还请指点 如果配置没问题有什么其他的可能

**Comment by jason-odd** [comment]
@kslr 有时间麻烦回复

**Comment by kslr** [comment]
没有日志我没有要说的，要不然换一家机场

**Comment by jason-odd** [comment]
我日志设置为了debug了 有日志了 帮忙看看吧

2019/12/14 18:57:38 tcp:127.0.0.1:53226 accepted tcp:ct.pinterest.com:443 [proxy] 
2019/12/14 18:57:49 [Info] [3883899784] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2019/12/14 18:57:49 [Info] [3883899784] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/12/14 18:57:52 [Info] [1148511439] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2019/12/14 18:57:52 [Info] [1148511439] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/12/14 18:57:56 [Info] [3789018827] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2019/12/14 18:57:56 [Info] [3789018827] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/12/14 18:58:31 [Info] [1885299936] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2019/12/14 18:58:31 [Info] [1885299936] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/12/14 18:58:31 [Info] [569527311] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2019/12/14 18:58:31 [Info] [569527311] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/12/14 18:58:31 [Info] [2112722808] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2019/12/14 18:58:31 [Info] [2112722808] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/12/14 18:58:31 [Info] [2784979272] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2019/12/14 18:58:31 [Info] [1235711569] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2019/12/14 18:58:31 [Info] [2784979272] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/12/14 18:58:31 [Info] [1235711569] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/12/14 18:58:31 [Info] [2695888128] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2019/12/14 18:58:31 [Info] [2695888128] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/12/14 18:58:38 [Info] [2004711825] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2019/12/14 18:58:38 [Info] [2004711825] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/12/14 18:58:39 [Info] [3542051707] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2019/12/14 18:58:39 [Info] [3542051707] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/12/14 18:58:41 [Info] [84411810] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2019/12/14 18:58:41 [Info] [84411810] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/12/14 18:58:50 [Info] v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/12/14 18:58:50 [Info] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > websocket: close 1000 (normal)
2019/12/14 19:00:09 [Info] [1396943696] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP request > read tcp 127.0.0.1:10808->127.0.0.1:53220: wsarecv: An existing connection was forcibly closed by the remote host.
2019/12/14 19:00:09 [Info] [1396943696] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/12/14 19:00:09 [Info] [2720511072] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP request > read tcp 127.0.0.1:10808->127.0.0.1:53169: wsarecv: An existing connection was forcibly closed by the remote host.
2019/12/14 19:00:09 [Info] [2720511072] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/12/14 19:00:09 [Info] [120943020] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP request > read tcp 127.0.0.1:10808->127.0.0.1:53224: wsarecv: An existing connection was forcibly closed by the remote host.
2019/12/14 19:00:09 [Info] [120943020] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/12/14 19:00:09 [Info] [4277506975] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP request > read tcp 127.0.0.1:10808->127.0.0.1:53155: wsarecv: An existing connection was forcibly closed by the remote host.
2019/12/14 19:00:09 [Info] [4277506975] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/12/14 19:00:09 [Info] [2456028456] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP request > read tcp 127.0.0.1:10808->127.0.0.1:53167: wsarecv: An existing connection was forcibly closed by the remote host.
2019/12/14 19:00:09 [Info] [2456028456] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/12/14 19:00:09 [Info] [1216024312] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP request > read tcp 127.0.0.1:10808->127.0.0.1:53165: wsarecv: An existing connection was forcibly closed by the remote host.
2019/12/14 19:00:09 [Info] [1216024312] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/12/14 19:00:09 [Info] [1164727247] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP request > read tcp 127.0.0.1:10808->127.0.0.1:53175: wsarecv: An existing connection was forcibly closed by the remote host.
2019/12/14 19:00:09 [Info] [1164727247] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/12/14 19:00:09 [Info] [2290751682] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP request > read tcp 127.0.0.1:10808->127.0.0.1:53148: wsarecv: An existing connection was forcibly closed by the remote host.
2019/12/14 19:00:09 [Info] [2290751682] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2019/12/14 19:00:09 [Info] [1553153950] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP request > read tcp 127.0.0.1:10808->127.0.0.1:53217: wsarecv: An existing connection was forcibly closed by the remote host.
2019/12/14 19:00:11 [Info] v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/12/14 19:00:11 [Info] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > websocket: close 1000 (normal)
2019/12/14 19:00:14 [Info] v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/12/14 19:00:14 [Info] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > websocket: close 1000 (normal)
2019/12/14 19:00:18 [Info] v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/12/14 19:00:18 [Info] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > websocket: close 1000 (normal)

**Comment by jason-odd** [comment]
@kslr 麻烦了 还是没有排版

**Comment by kslr** [comment]
1. 关闭mux
2. 加大 alterId
3. 使用其他host

**Comment by jason-odd** [comment]
mux已关闭
alterid怎么修改
host怎么修改

**Comment by DolorHunter** [comment]
> 
> 
> mux已关闭
> alterid怎么修改
> host怎么修改

三个都是在 `config.json` 里面改, 或者用三方有图形界面的软件改, 看你用的软件里面有没有地方改. alterID 要跟服务器上的 alterID 保持一致.
