### ISSUE TITLE
请问为什么帖子被封啊？

### ISSUE THREAD

**Issue by Samcall** [v2ray/discussion#467]
https://github.com/v2ray/discussion/issues/466

是否触犯了什么规定？

**Comment by xuebaxi** [comment]
禁止廣告
順便說幾點
1.V2Ray 的的開發是在數百位程序員大佬的協作下完成的，您所謂的軟件據我所知開發人員只有一位。誰是閉門造車大家心裡清楚。
2.V2Ray  完全開源歡迎您來查看我們“閉們造車出來的協議”，然而您所謂的軟件的服務端是閉源的。
3. 關于被GFW發現，因為V2Ray用戶量巨大，為GFW重點關照對象之一，GFW 投入大量資源仍然不能完全封殺。但您所謂的軟件只是一個毫無名氣的軟件，別人甚至不知道你們的存在，當然不會關照了。

**Comment by johnrosen1** [comment]
什么垃圾玩意，没听说过

**Comment by Samcall** [comment]
> 禁止廣告
> 順便說幾點
> 1.V2Ray 的的開發是在數百位程序員大佬的協作下完成的，您所謂的軟件據我所知開發人員只有一位。誰是閉門造車大家心裡清楚。
> 2.V2Ray 完全開源歡迎您來查看我們“閉們造車出來的協議”，然而您所謂的軟件的服務端是閉源的。
> 3. 關于被GFW發現，因為V2Ray用戶量巨大，為GFW重點關照對象之一，GFW 投入大量資源仍然不能完全封殺。但您所謂的軟件只是一個毫無名氣的軟件，別人甚至不知道你們的存在，當然不會關照了。

谢谢回答！
1. 我在 https://github.com/v2ray/v2ray-core/ 页面中看到“53 contributors”，请问“數百位程序員”是怎么统计出来的？
2. 这个软件的开发者也是把代码托管在github上的，请问为什么说“服務端是閉源的”？我对软件开发不太了解，还请不吝指教。
3. 我本人用的是V2Ray，只是看到那位作者帖子中攻击别人“闭门造车”后感觉不爽（而且作者把软件分为限速免费版和收费版，显然就是为了卖钱的），所以想多找些论据来反驳一下，没想到帖子直接被封了。看到不同的观点就封禁，这种手段等同于墙内的网络管制，建议管理者们不妨胸怀更宽大一些。所以请不要用“你們”这个词把我和那个商人混为一类。

**Comment by Samcall** [comment]
> 你说的是什么垃圾玩意，没听说过

我就是怀疑是垃圾，才来这里找论据支持的。

**Comment by kslr** [comment]
这种事情是浪费彼此的时间，把精力用在有意义的事情上吧。

**Comment by Samcall** [comment]
> 这种事情是浪费彼此的时间，把精力用在有意义的事情上吧。

谢谢回复！

或许我的问题对你来说是没有意义的，但对我来说还是有些意义的。大家求同存异好不好？

另外这里 https://github.com/v2ray/discussion/issues 不就是讨论用的吗，没必要这么着急关闭帖子吧？

**Comment by kslr** [comment]
这里不鼓励对其他人的攻击，也不需要划分阵营。

**Comment by Samcall** [comment]
> 这里不鼓励对其他人的攻击，也不需要划分阵营。

攻击他人、划分阵营？这从何说起呀？

难道您是处女座，小名“见到issue不关闭不舒服斯基“？（好吧，这句涉嫌攻击，帖子莫名被关有些激动，还请见谅）

**Comment by kslr** [comment]
迷雾通说什么是他们自己的自由，事实是不会改变的。

我指的是不同的用户划分为不同的阵营（trojan shadowsocks 等等所有的软件） 用户互相歧视，互相攻击，并试图挑起纷争。这显然违反了最初的精神，因此这种事情在这里是坚决抵制的。

**Comment by Samcall** [comment]
谢谢你的详细说明。建议明确一下版规，免得类似我这种，因不清楚这里的规矩而浪费大家的时间。

真理不辩不明，我另外找地方讨论我的疑问吧。
