### ISSUE TITLE
how to vmess + h2c + tls?

### ISSUE THREAD

**Issue by choicky** [v2ray/discussion#468]
Currently I'm using `caddy` as web server and using `vmess + h2 + tls`.

In my opinions it would be faster to use `h2c` rather than `h2`.  However, h2c is not support by caddy.

Is there anyone using `vmess + h2 + tls`? Please share your solution.  Thank you very much.

**Comment by aeroxy** [comment]
I don't even know how to configure v2ray to support h2c to begin with...

**Comment by eMeab** [comment]
apache support  h2c.
