### ISSUE TITLE
nginx+websocket+http抗封锁能力如何？

### ISSUE THREAD

**Issue by kirin10000** [v2ray/discussion#469]
就是使用nginx反代，但是不用tls加密，走80端口。
服务端配置如下：
`server {
    listen 80;
    listen [::]:80;
    server_name *********;
    root /etc/nginx/html;
    index index.html;
    location /***** {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:27887;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
    }
}`
v2配置文件与v2+websocket+tls相同。
客户端配置如下：
![image](https://user-images.githubusercontent.com/57820613/70850139-e48a1f00-1ec1-11ea-9f60-f4d35422f3b7.png)
除了底层传输没有TLS选项之外，其它相同。
我想知道这样的配置在GFW看来和没有nginx、仅仅ws走80端口有没有区别？还是说能起到一定的伪装作用？
tcp有http伪装，可惜ws没有，我目前还没有发现nginx反代tcp协议的方法，nginx只能反代websocket协议的流量吗？这个我也想询问一下

**Comment by kirin10000** [comment]
![image](https://user-images.githubusercontent.com/57820613/70850231-f4563300-1ec2-11ea-95db-3556d44efc6b.png)

**Comment by jimmygiven** [comment]
这不送人头么？

**Comment by DolorHunter** [comment]
既然都挂一个网页上去伪装了, 为什么还要开伪装.
