### ISSUE TITLE
请问vmess协议中，是怎么从“HMAC消息验证码”中获取到时间戳的？

### ISSUE THREAD

**Issue by isshe** [v2ray/discussion#470]
请问vmess协议中，是怎么从“消息验证码”中获取到时间戳的？
这部分代码没看懂？
```
// DecodeRequestHeader decodes and returns (if successful) a RequestHeader from an input stream.
func (s *ServerSession) DecodeRequestHeader(reader io.Reader) (*protocol.RequestHeader, error) {
	buffer := buf.New()
	defer buffer.Release()

	if _, err := buffer.ReadFullFrom(reader, protocol.IDBytesLen); err != nil {
		return nil, newError("failed to read request header").Base(err)
	}

	user, timestamp, valid := s.userValidator.Get(buffer.Bytes())
	if !valid {
		return nil, newError("invalid user")
	}
```
* timestamp 这个怎么就获取到了呢？什么时候存起来的？
* 麻烦讲一下这个时间戳的获取思路？感谢。

**Comment by isshe** [comment]
userValidator.userHash什么时候存了用户的信息？

**Comment by vcptr** [comment]
服务端生产存储连续每一秒的hmac，用户用当前秒。如果接收到uuid正确所生产的hmac，服务器就能找到对应hmac所产生的秒数时间戳和用户信息。

**Comment by isshe** [comment]
再请教个问题：使用时间戳，主要考虑的安全性呢（重放攻击？还是？）还是说是为了让消息验证码变起来(每秒钟都不同)不易被识别？安全性的话是哪些安全性？

**Comment by boypt** [comment]
主要为了防重放。而且还有后续机制：如果同个hmac被二次使用，连接就被马上丢弃。

应该注意hmac md5在这个机制里面既不是用来验证，也不是用来签名，不是传统意义上用哈希算法的校验作用。而是作为indexer，所以即使密码学上md5算法不是安全的，也不影响作为时间戳散列的安全性。

提供进一步的安全性的机制不在于这个时间戳机制，而在于alter id，客户端随机使用不同的密钥进行通信。

**Comment by vcptr** [comment]
主要为了防重放。而且还有后续机制：如果同个hmac被二次使用，连接就被马上丢弃。

应该注意hmac md5在这个机制里面既不是用来验证，也不是用来签名，不是传统意义上用哈希算法的校验作用。而是作为indexer，所以即使密码学上md5算法不是安全的，也不影响作为时间戳散列的安全性。

提供进一步的安全性的机制不在于这个时间戳机制，而在于alter id，客户端随机使用不同的密钥进行通信。

**Comment by isshe** [comment]
好，谢谢。
