### ISSUE TITLE
萌新问题，v2ray本身可支持科学上网，但是在上面搭载ss等带来的影响是什么

### ISSUE THREAD

**Issue by linwhitehat** [v2ray/discussion#474]
直接ss和v2ray上的ss具体差异是什么？萌新好奇的想学习

**Comment by kslr** [comment]
你这是什么意思

**Comment by kslr** [comment]
按照原协议实现的

**Comment by linwhitehat** [comment]
> 按照原协议实现的 https://v2ray.com/chapter_02/protocols/shadowsocks.html

我的意思其实就是不太明白这两者的区别，v2ray上搭的ss和不装v2ray直接搭ss有什么区别？比如v2ray能多加一层混淆之类的吗？

**Comment by linwhitehat** [comment]
> 按照原协议实现的 https://v2ray.com/chapter_02/protocols/shadowsocks.html

我看到这个教程了，实现是和原协议一样，但是在表现上被gfw针对是一样的吗？还是科学上网能力更好？直接用v2ray科学上网是不是更好？

**Comment by kslr** [comment]
给有需要的人使用
