### ISSUE TITLE
透明代理使用中一些疑问，主要与DNS有关

### ISSUE THREAD

**Issue by dalton-chiou** [v2ray/discussion#476]
新手请教。环境是openwrt 18.06.5，v2ray是最新版。

1，先从最简单的redirect方式透明代理说起。既然prerouting链里插入V2RAY链，后者有这么一条：
（-A V2RAY） -p tcp -j REDIRECT --to-ports 1234
除了v2ray自己发出的，其它所有TCP流量都进了任意门，那么，那个socks入站岂不是没了用处？

2，停用socks代理，再将任意门设置为只接受tcp，也没有在mangle表中处理udp，这时，墙内墙外网站都能正常解析。那么，这种情况下，PC应用的DNS请求是怎么进入v2ray的路由中的呢？

3，如果使用DNS出站，我发现路由dns时，入站留空也是可以的：
{"type": "field",
"port": "53",
"network": "udp",
"inboundTag": ["dokodemo_door"],
"outboundTag": "dns_out”}
inboundTag留空和写成现在这样，没有区别。port写不写也没有区别。这是为什么呢?

4, 但当我另建一个dokodemo 入站，来连接DNS出站，不论怎么设置端口、协议、转发，只要启用，就上不去网 了。比如这样：
{"port": 53,
"tag": "dns-in",
"protocol": "dokodemo-door",
"settings": {"network": "tcp,udp”} 
 }
nslookup找不到server。不知是哪里错了。

5，tproxy模式下，把53端口的UDP流量转发至任意门，这与使用dns出站的路由设置（如3中所设），功能是否重复？

**Comment by kingwilliam** [comment]
Q1：先从最简单的redirect方式透明代理说起。既然prerouting链里插入V2RAY链，后者有这么一条：
（-A V2RAY） -p tcp -j REDIRECT --to-ports 1234
除了v2ray自己发出的，其它所有TCP流量都进了任意门，那么，那个socks入站岂不是没了用处？
A1：可以这样说的，等同两个入口，看你喜欢走那个都成。


Q2：停用socks代理，再将任意门设置为只接受tcp，也没有在mangle表中处理udp，这时，墙内墙外网站都能正常解析。那么，这种情况下，PC应用的DNS请求是怎么进入v2ray的路由中的呢？


Q3：如果使用DNS出站，我发现路由dns时，入站留空也是可以的：
{"type": "field",
"port": "53",
"network": "udp",
"inboundTag": ["dokodemo_door"],
"outboundTag": "dns_out”}
inboundTag留空和写成现在这样，没有区别。port写不写也没有区别。这是为什么呢?


Q4：但当我另建一个dokodemo 入站，来连接DNS出站，不论怎么设置端口丶协议丶转发，只要启用，就上不去网 了。比如这样：
{"port": 53,
"tag": "dns-in",
"protocol": "dokodemo-door",
"settings": {"network": "tcp,udp”}
}
nslookup找不到server。不知是哪里错了。


Q5：tproxy模式下，把53端口的UDP流量转发至任意门，这与使用dns出站的路由设置（如3中所设），功能是否重复？

========================

Q1 已回答。
Q2 因不知你的config.json和iptables所以不好回答。
Q3-Q5 统一回答


先说一些前设
```
router
ip: 192.168.0.254

v2ray流桯
inbound -> routing -> outbound

v2ray dns 例

"dns": {
    "servers": [
        "8.8.8.8",
        {
            "address": "114.114.114.114",
            "port": 53,
	    "domains": {
                "geosite:cn"
            }
        }
    ]
},

"inbound: [
    "port": 53,
    "protocol":"dokodemo-door",
    "settings":{
        "address": "114.114.114.114",
        "port": 53,
        "followRedirect":true,
        "network":"tcp,udp"
    },
]

"routing": [
    {
        "type": "field",
        "port": "53",
        "network": "udp",
        "outboundTag": "dns_out
    }
],

"outbounds": [
    {
        "tag": "over-the-wall",
        "protocol": "vmess",
        ...
    },
    {
        "tag": "dns-in"
         "protoocol": "dns"
    }
]
```



客户dns大多可有2种设定.
(1) 192.168.0.254
(2) 114.114.114.114
如用(1), 可以开dokodemo-door处理
如用(2), 这时多数是透明代理,先用iptables 送tcp,udp上dokodemo-door, 再在routing内拦截udp53再送要

求到dns-out, 这就回答你Q3.
```
{
    "type": "field",
    "port": "53",
    "network": "udp",
    "outboundTag": "dns_out"
}
```

上要两种方法也可以, 这就回答Q5, 视各人喜好.

至于Q4 因不知你的config.json和iptables所以不好回答。
在上面的dns例子, dokodemo-door 要给一个dns ip, 同时可配合内置dns服务器. 视你想如何配置.
