### ISSUE TITLE
重启光猫更换IP之后才能正常翻墙？（求大神答疑解惑！）

### ISSUE THREAD

**Issue by dota2heqiuzhi** [v2ray/discussion#477]
我家是中国移动网络，每次使用v2ray正常翻墙一段时间之后就无法翻墙了（v2ray服务器端没问题，手机4G可以翻墙但是连上家里的wifi就不行）。
重启路由器还是一样。
重启光猫重新分配一个IP之后就又可以正常翻墙了。
自己Google没有搜索到相关的原理。我的v2ray服务器没问题，而是移动网络给我分配的IP被封了？这是怎么做到的啊？意思GFW还能限制国内的某个IP无法访问国外的IP地址？？？
请大神答疑解惑！

**Comment by iochen** [comment]
Try to use other ISP.
Same issue on me :)

**Comment by dota2heqiuzhi** [comment]
那究竟是什么原理呢？ 想学习一哈

Richard Chen <notifications@github.com> 于2020年1月5日周日 上午8:02写道：

**Comment by xin344** [comment]
我最近也遇到了这个问题 联通宽带
