### ISSUE TITLE
有大神知道这图片是怎么回事？该如何解决？

### ISSUE THREAD

**Issue by lgy330335** [v2ray/discussion#480]
[
![IMG_20191228_223407](https://user-images.githubusercontent.com/51503868/71545125-33f04500-29c2-11ea-802d-ce999f3691bf.jpg)
](url)

**Comment by HamJin** [comment]
Privoxy 不能监听那个端口(win10的锅)
重启电脑或者用win7

**Comment by lgy330335** [comment]
之前重启了，还是那样，今天突然好了，不知道为什么
