### ISSUE TITLE
关于动态端口链接加密的问题

### ISSUE THREAD

**Issue by Apitue** [v2ray/discussion#481]
tls+h2+dynamic port，按我的理解：主链接（domain:443/path）用tls的加密，因此我把客户端配置里面的vmess加密关了（security: none）。有两个问题不太确定，望解答：
1. 打开tls后，能否关掉内层vmess的加密？对安全性是否有影响？性能是否会提升？
2. 之后客户端和服务器在动态端口上建立的链接用的是什么加密？是和主链接一样的tls？还是vmess协议加密？如果是后者，关掉客户端配置的vmess加密是否会造成动态端口链接的数据明文传输？

**Comment by iochen** [comment]
1. 可以，几乎无，会 （可见 #513 ）
2. 动态端口只是端口变了
