### ISSUE TITLE
貌似最近主动probe有点升级，acceess.log里面一堆来自国内replay attack，时不时断

### ISSUE THREAD

**Issue by univert** [v2ray/discussion#482]
好像和SS的probe原理是一样的， 
https://webcache.googleusercontent.com/search?q=cache:W5SHK9gvhmUJ:https://gfw.report/blog/gfw_shadowsocks/
就是把报文存下来过一段时间回放，查看返回内容判断是否是代理

如果对于replay attack不返回一些合理的回复，可能被主动probe识别为代理，

**Comment by forever8938** [comment]
使用ws+tls几乎肯定会触发这个探测，而用浏览器访问域名则不会。这意味着墙有能力识别TLS指纹，并且怀疑此连接是v2ray。这个路径是白话文教程里的，直接用这个路径的话秒封IP。
`"GET /ray HTTP/1.1" 404 14 "-" "Go-v2ray_http-client/1.1"`
