### ISSUE TITLE
dns-out的outbound配置似乎不起作用，希望给出更详细的文档

### ISSUE THREAD

**Issue by mzz2017** [v2ray/discussion#487]
```json
{
    "network": "tcp",
    "address": "1.1.1.1",
    "port": 53
}
```
如上所示，可通过修改上述outbound.settings来修改流入dns出站协议的目的地址、目的端口以及传输层协议，但实际上，dns会直接使用顶层DNS配置进行分流，而分流填写的dns均有自己的传输层协议、地址和端口，会覆盖掉该出站settings。

而如果将dns配合proxySettings使用，也不是很起作用。

在顶层DNS配置中直接设置localhost，也不起作用。

希望如果是我使用不当，可以给出更详细的文档。

**Comment by KirbyKFC** [comment]
> 此出站协议会将 IP 查询（即 A 和 AAAA）转发给内置的 DNS 服务器。其它类型的查询流量将被转发至它们原本的目标地址。
