### ISSUE TITLE
How to build it for Swift iOS

### ISSUE THREAD

**Issue by devd77** [v2ray/discussion#489]

**Comment by Taraskibitkin** [comment]
same question...)

**Comment by QQ89932** [comment]
同求 同问

**Comment by 616115891** [comment]
同求

**Comment by javaherisaber** [comment]
Has anyone managed to integrate in iOS with Swift?

**Comment by SheheryarShahVozye** [comment]
hey is there a way to integrate v2ray in swift

**Comment by hyperswitch88** [comment]
same question?
I am programming ios app with swift language about vpn. v2ray protocols must be used in this application. None of the libraries listed on github are working or have been removed. For example, none of the following libraries work:
v2ray_mobile_lib
SwiftV2Ray-1
sing-box
SwiftV2Ray
Do you know a library or method for programming v2ray in the ios operating system in swift language that you can introduce?

**Comment by Xixi0218** [comment]
> same question? I am programming ios app with swift language about vpn. v2ray protocols must be used in this application. None of the libraries listed on github are working or have been removed. For example, none of the following libraries work: v2ray_mobile_lib SwiftV2Ray-1 sing-box SwiftV2Ray Do you know a library or method for programming v2ray in the ios operating system in swift language that you can introduce?

https://github.com/eycorsican/leaf

**Comment by hyperswitch88** [comment]
> 
Thank
But this is written in Rust programming language
