### ISSUE TITLE
v2ray做为tor的前置代理出现问题

### ISSUE THREAD

**Issue by fugu37** [v2ray/discussion#49]
配置方式为TLS + web + ws
完整配置如下：

客户端
{
  "inbound": {
    "port": 1081,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "domainOverride": ["tls","http"],
    "settings": {
      "auth": "noauth",
      "udp": false
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "example.com",
          "port": 443,
          "users": [
            {
              "id": "xxxxxxxxxxxxxxxx",
              "alterId": 64
            }
          ]
        }
      ]
    },
    "mux": {"enabled": false},
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "wsSettings": {
          "path": "/xxxxx"
          }
        }
    },
    "dns": {
        "hosts": {
            "example.com": "2001:xxxxxxxxxxxxxxx"//我的v6地址
            },
        "servers": ["192.168.2.2"]
    },
    "log": {
        "loglevel": "debug"
    }
}

**Comment by fugu37** [comment]
服务端

{
  "inbound": {
    "port": 40227,
    "listen":"127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "xxxxxxxxxxxxxxxxxxxxxxx",
          "level": 1,
          "alterId": 64
        }
      ]
    },
    "streamSettings": {
        "network": "ws",
        "wsSettings": {
        "path": "/xxxxx"
        }
    }
  },
  "outbound": {
    "sendThrough": "公网ipv4地址",
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": ["geoip:private"],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}

**Comment by fugu37** [comment]
nginx

        location /xxxxx {
            access_log off;
            proxy_redirect off;
            proxy_pass http://127.0.0.1:40227;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;
        }

**Comment by fugu37** [comment]
抱歉，经群友提醒，关闭客户端的
"domainOverride": ["tls","http"],
即可解决

**Comment by yoheRabit** [comment]
感谢你们！

**Comment by chenshaoju** [comment]
查到这个帖子，补充一下，方便后人：

如果你使用的是V2RayN，该选项叫”开启流量探测“，位于主界面的”参数设置“按钮里，对应V2Ray的`domainOverride` 选项。

关闭该选项即可恢复正常。

在最新的手册中，已经改成了 `sniffing` ，不再是 `domainOverride` 了。

https://toutyrater.github.io/basic/vmess.html#%E5%AE%A2%E6%88%B7%E7%AB%AF

**Comment by VictorAlexanderMa** [comment]
> 
> 
> 查到这个帖子，补充一下，方便后人：
> 
> 如果你使用的是V2RayN，该选项叫”开启流量探测“，位于主界面的”参数设置“按钮里，对应V2Ray的`sniffing` 选项。
> 
> 关闭该选项即可恢复正常。
> 
> 参考文档：https://toutyrater.github.io/basic/vmess.html#%E5%AE%A2%E6%88%B7%E7%AB%AF

正解！
我遇到了和题主同样的问题，题主给我的issue转了你的回答，药到病除立马解决了问题。
谢谢！

**Comment by magictomagic** [comment]
NB啊，成功了

**Comment by YunMengs** [comment]
> `sniffing`

感谢！

**Comment by DaobinZhu** [comment]
请教一下为什么可以打开duckduckgo但是暗网的网站却打不开？

**Comment by DaobinZhu** [comment]
对了，我用的是V2ray

**Comment by YunMengs** [comment]
> 请教一下为什么可以打开duckduckgo但是暗网的网站却打不开？

你的梯子和网站本身的问题有可能，有些网站从你梯子哪里访问很卡

**Comment by realDSH** [comment]
> 抱歉，经群友提醒，关闭客户端的 "domainOverride": ["tls","http"], 即可解决

请问如何关闭？在v2rayN没有关闭domainOverride的图形按钮……小白不太明白……
