### ISSUE TITLE
一进多出问题

### ISSUE THREAD

**Issue by BlackMask007** [v2ray/discussion#491]
服务器有多个ip，我想实现一个ip进，多个ip出，但使用了下面配置没有成功。
或者用其他办法，官方提供文档说明可以负载均衡，我在本机运行多个docker，docker内使用了socks入，但不知道如何在主outbound内设置socks出，请大佬指点

```json
  ....
  "outbound": {
    "protocol": "freedom",
    "settings": {},
    "vnext": [
      {
        "sendThrough": "192.168.0.100"
      },
      {
        "sendThrough": "192.168.0.101"
      },
      {
        "sendThrough": "192.168.0.102"
      }
    ]
  }
```

**Comment by ix64** [comment]
设置多个socks outbound，在路由内进行负载均衡。参考：https://toutyrater.github.io/routing/balance2.html

**Comment by BlackMask007** [comment]
谢谢

MengYX <notifications@github.com> 于2020年1月14日周二 上午12:28写道：
