### ISSUE TITLE
实现类似ssh -ND 8180 user@host的功能

### ISSUE THREAD

**Issue by rockxsj** [v2ray/discussion#492]
背景：由于公司VPN客户端过于难用，同时提供了外网可以访问的通道机，可以通过通道机访问内网资源，如内网web服务。  所以现在我都是用ssh在本地开个端口转发流量，搭配switchomega访问内网资源。   但是不想每次还要手动开一个ssh窗口，故想问下可以通过v2ray实现类似功能吗？

**Comment by kslr** [comment]
看不懂，你是说端口转发吗，可以的。

**Comment by rockxsj** [comment]
> 看不懂，你是说端口转发吗，可以的。

应该也不是，其实就是通过ssh建立一个数据通道，我本地所有的请求通过本地的8180端口请求，这些请求就会自动通过我ssh连上的这台机器转发到目的服务。 有点像是透明代理？  不过我并不需要在ssh的这台服务器上做任何特殊的配置。

**Comment by rockxsj** [comment]
> 看不懂，你是说端口转发吗，可以的。

就是动态端口转发，参看man ssh里面的说明：
![l7Gz0f.png](https://s2.ax1x.com/2020/01/13/l7Gz0f.png)

**Comment by kslr** [comment]
你可以试试frp

**Comment by rockxsj** [comment]
> 你可以试试frp

也看过了  还是没有想到用哪种配置可以实现这个？  如果服务端上装上frps应该可以。    也就是说我需要的一个东西应该可以充当ssh的客户端，与服务端的sshd通信。

**Comment by hyxxsfwy** [comment]
你需要的是 autossh
