### ISSUE TITLE
路由模块能否添加入站mark匹配

### ISSUE THREAD

**Issue by imess** [v2ray/discussion#499]
根据dokodemo-door入站mark选择不同的出站，虽然也能通过多个dokodemo-door+ip rule实现，主要是为了配置更简洁，1个mark对应一个door和一条ip rule，显然配置起来比较繁琐。

**Comment by Vigilans** [comment]
调查了一下（有问题请指正）

目前似乎不太可行，因为mark是ip/iptables用来标记IP数据包的，似乎在应用层不能直接拿到。应用层能做的是获取Socket绑定的MARK（SO_MARK），其[说明](https://man7.org/linux/man-pages/man7/socket.7.html)是：
```
       SO_MARK (since Linux 2.6.25)
              Set the mark for each packet sent through this socket (similar
              to the netfilter MARK target but socket-based).  Changing the
              mark can be used for mark-based routing without netfilter or
              for packet filtering.  Setting this option requires the
              CAP_NET_ADMIN capability.
```

这个设置只是让Socket送出的数据包被标记，仍然不能直接获取送来的数据包的Mark。

不知道Network Interface能否拿到数据包的MARK，如果可以的话也许TUN模式下可以实现入站Mark匹配。
