### ISSUE TITLE
如何使用 DoH 查询结果中的 IP 地址来向目标网站发起连接，而不是通过 Host 发起连接？

### ISSUE THREAD

**Issue by Loyalsoldier** [v2ray/discussion#502]
据了解，目前 V2Ray 的连接机制是，通过 DNS 查询出目标网站 IP 地址后，还是会向 V2Ray 服务器发起 Host 连接，而不是 IP 连接。

请问如何使用 DoH 查询结果中的 IP 地址来向目标网站发起连接，而不是通过 Host 发起连接，以避免 V2Ray 服务端服务器直接获取到用户访问的 Host（出于保护隐私的目的）？

**Comment by kslr** [comment]
如果服务端获取不到HOSTS，如果实现基本功能呢
