### ISSUE TITLE
V2Ray 疑似被侦测

### ISSUE THREAD

**Issue by KASJAK-cpu** [v2ray/discussion#504]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
`V2Ray 4.18.0 (Po) 20190228`
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
`使用 Telegram`
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
教育网：半小时后自动断线，之后无法再连。12~24小时后又可以连接。
家宽/4G：长时间无断流现象。
地址：浙江
4) 你期待看到的正确表现是怎样的？
不断流
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
客户端配置:
```
    {
      "configVersion": 2,
      "address": "example.com",
      "port": 80,
      "id": "85c04a7c-402c-425f-8ac7-35d4686f081e",
      "alterId": 0,
      "security": "auto",
      "network": "ws",
      "remarks": "香港",
      "headerType": "none",
      "requestHost": "itunes.apple.com.ajax.microsoft.com.cn.bing.com.hk.smxhx.com",
      "path": "/",
      "streamSecurity": "",
      "allowInsecure": "",
      "configType": 1,
      "testResult": "",
      "subid": "8161d1b6-c9ac-4721-951a-df150f8230b0"
    },
```
6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
客户端错误日志:

> [error.log](https://github.com/v2ray/discussion/files/4082456/error.log)

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

> [access.log](https://github.com/v2ray/discussion/files/4082457/access.log)

**Comment by kslr** [comment]
尝试关掉MUX
