### ISSUE TITLE
TCP+TLS, WS+TLS, HTTP2+TLS 對牆來說，看來是一樣的內容嗎？

### ISSUE THREAD

**Issue by kousyougi** [v2ray/discussion#505]
查了各種資訊，目前利用TLS是最不容易被識別的。
但請問這三種搭配 TCP+TLS, WS+TLS, HTTP2+TLS 
傳輸內容，對牆來說，看起來是一樣的嗎？
速度或反應上有優劣嗎？

謝謝

**Comment by kslr** [comment]
从某种意义上是的，Websocket and http2延迟会很高
