### ISSUE TITLE
2048bit key的TLS可能被识别了

### ISSUE THREAD

**Issue by okudayukiko** [v2ray/discussion#506]
测试环境：中国电信宽带+中国移动4G
测试结果：
V2Ray TCP（AES-128-GCM）：不稳定
V2Ray KCP（AES-128-GCM）：不稳定
V2Ray+WS+TLS（Let's Encrypt 4096bit Key）：OK，但在手机端使用时比较耗电
V2Ray+KCP+TLS（Let's Encrypt 4096bit Key）：有时可用，有时不可用
V2Ray+TCP+TLS（Let's Encrypt 4096bit Key）：OK，但比较耗电
AnyConnect+TLS（Let's Encrypt 4096bit Key）：OK，但比较耗电
Shadowsocks AES-256-GCM：在中国移动4G下看不了YouTube App，但可以看网页YouTube
V2Ray+WS+TLS（Lets Encrypt 2048bit key）：OK，但稳定性不如V2Ray+TLS（Let's Encrypt 4096bit），手机用比较省电
V2Ray+KCP+TLS（Let's Encrypt 2048bit key）不可用，加了header也不行
V2Ray+QUIC+TLS（Let's Encrypt 2048bit key）不可用，加了header也不行
看直播时KCP/QUIC比TCP/WS流畅很多，分辨率高很多。
V2Ray+TCP+TLS（Let's Encrypt 2048bit Key）：可用，但稳定性不如Let's Encrypt 4096bit
AnyConnect+TLS（Let's Encrypt 2048bit Key）：可用，稳定性比Let's Encrypt 4096bit差
V2Ray+WS+TLS（自签名证书4096bit Key）：中国移动4G下不稳定
V2Ray+KCP+TLS（自签名证书4096bit Key）：中国移动4G下不稳定
V2Ray+TCP+TLS（自签名证书4096bit Key）：中国移动4G下不稳定
AnyConnect+TLS（自签名证书4096bit Key）：不够Let's Encrypt 4096bit稳定。
全部V2Ray配置都采用动态端口。
想流畅看ViuTV直播。

**Comment by DolorHunter** [comment]
推荐使用 `ECC` 证书, 长度短, 强度足, 看看能不能解决耗电问题. 
>在安全性上 256 位的 ECC 证书等同于 3072 位的 RSA 证书
`RSA` 证书用的比较少, 不太了解, `ECC` 挺稳定的.

**Comment by okudayukiko** [comment]
问题已解决，2048bit证书目前可用。
自签名证书不如Let's Encrypt等证书安全。
问题是服务器端配置文件没写对。
使用KCP或QUIC时，服务器端配置文件不能写"tcpFastOpen": true，否则客户端连不上KCP/QUIC
以下是错误的：
{
     "streamsettings": {
          "network":"kcp"
          "sockopt":  {
               "tcpfastopen":true
          }
     }
}

**Comment by okudayukiko** [comment]
> 推荐使用 `ECC` 证书, 长度短, 强度足, 看看能不能解决耗电问题.
> 
> > 在安全性上 256 位的 ECC 证书等同于 3072 位的 RSA 证书
> 
> `RSA` 证书用的比较少, 不太了解, `ECC` 挺稳定的.

ECC证书能不能用KCP/Quic，看直播不用KCP/QUIC比较卡而且分辨率低。

**Comment by DolorHunter** [comment]
ECC 在不太老旧的设备上都可以使用. `KCP + TLS` 被列为不推荐的配置. 还没有用过 QUIC, 不太清楚. 据网友反馈, 移动网络好像普遍不如电信网络.

**Comment by DolorHunter** [comment]
断流现象可以尝试通过关闭 `MUX`, 或是加大 `alterID` 来解决.

**Comment by okudayukiko** [comment]
> 断流现象可以尝试通过关闭 `MUX`, 或是加大 `alterID` 来解决.

用了ECC AES512证书，KCP还是用不了。

**Comment by okudayukiko** [comment]
若服务器的config.json设为concurrency:400，
客户端看YouTube/在线视频时，服务器端打开top，服务器端会CPU 100%。
服务器端concurrency:300 则无上述Bug。

**Comment by okudayukiko** [comment]
> 断流现象可以尝试通过关闭 `MUX`, 或是加大 `alterID` 来解决.

用mKCP+TLS，提升TLS handshake error,first record does not look like a TLS handshake.

**Comment by okudayukiko** [comment]
修改服务器端配置文件config.json，将：
"settings": {
            "clients": [
                {
                    "id": "",
                    "level": 1,
                    "alterId": 500
                }
            ]
        }
改为：
"settings": {
            "clients": [
                {
                    "id": "",
                    "alterId": 750
                }
            ]
        }
看直播不卡了。

**Comment by DolorHunter** [comment]
> 
> 
> > 断流现象可以尝试通过关闭 `MUX`, 或是加大 `alterID` 来解决.
> 
> 用mKCP+TLS，提示TLS handshake error,first record does not look like a TLS handshake.

>KCP+TLS，传输层还是UDP，只不过传输的数据变成TLS的数据（相当于额外加密）https://github.com/v2ray/v2ray-core/issues/343

因此, 不建议 `KCP + TLS` 配置. 如果单纯为了加密 KCP协议 下的数据, 使用 `加密(security)` 或 `添加header` 而不是 `TLS` 可能是更好的选择.

**Comment by okudayukiko** [comment]
> > > 断流现象可以尝试通过关闭 `MUX`, 或是加大 `alterID` 来解决.
> > 
> > 
> > 用mKCP+TLS，提示TLS handshake error,first record does not look like a TLS handshake.
> 
> ref [v2ray/v2ray-core#343](https://github.com/v2ray/v2ray-core/issues/343)
> 
> > KCP+TLS，传输层还是UDP，只不过传输的数据变成TLS的数据（相当于额外加密）
> 
> 因此, 不建议 `KCP + TLS` 配置. 如果单纯为了加密 KCP协议 下的数据, 使用 `加密(security)` 或 `添加header` 而不是 `TLS` 可能是更好的选择.

用ECC 256证书的效果确实比RSA 2048好。

**Comment by okudayukiko** [comment]
> > > 断流现象可以尝试通过关闭 `MUX`, 或是加大 `alterID` 来解决.
> > 
> > 
> > 用mKCP+TLS，提示TLS handshake error,first record does not look like a TLS handshake.
> 
> ref [v2ray/v2ray-core#343](https://github.com/v2ray/v2ray-core/issues/343)
> 
> > KCP+TLS，传输层还是UDP，只不过传输的数据变成TLS的数据（相当于额外加密）
> 
> 因此, 不建议 `KCP + TLS` 配置. 如果单纯为了加密 KCP协议 下的数据, 使用 `加密(security)` 或 `添加header` 而不是 `TLS` 可能是更好的选择.

还有什么类似爱奇艺的中文视频平台？不喜欢中国大陆视频平台。

**Comment by chinanoahli** [comment]
> > > > 断流现象可以尝试通过关闭 `MUX`, 或是加大 `alterID` 来解决.
> > > 
> > > 
> > > 用mKCP+TLS，提示TLS handshake error,first record does not look like a TLS handshake.
> > 
> > 
> > ref [v2ray/v2ray-core#343](https://github.com/v2ray/v2ray-core/issues/343)
> > > KCP+TLS，传输层还是UDP，只不过传输的数据变成TLS的数据（相当于额外加密）
> > 
> > 
> > 因此, 不建议 `KCP + TLS` 配置. 如果单纯为了加密 KCP协议 下的数据, 使用 `加密(security)` 或 `添加header` 而不是 `TLS` 可能是更好的选择.
> 
> 还有什么类似爱奇艺的中文视频平台？不喜欢中国大陆视频平台。可以用Paypal氪金。

我看英语电视剧电影等等都是rarbg下bt，bt他不香吗？
新种速度快，只需要bt站偶尔翻墙一下找磁链或者种子，下载不需要翻墙流量，清晰度有保证，上班时可以家里搞个linux低功耗设备挂机下载。
bt它真的香！

**Comment by okudayukiko** [comment]
> > > > > 断流现象可以尝试通过关闭 `MUX`, 或是加大 `alterID` 来解决.
> > > > 
> > > > 
> > > > 用mKCP+TLS，提示TLS handshake error,first record does not look like a TLS handshake.
> > > 
> > > 
> > > ref [v2ray/v2ray-core#343](https://github.com/v2ray/v2ray-core/issues/343)
> > > > KCP+TLS，传输层还是UDP，只不过传输的数据变成TLS的数据（相当于额外加密）
> > > 
> > > 
> > > 因此, 不建议 `KCP + TLS` 配置. 如果单纯为了加密 KCP协议 下的数据, 使用 `加密(security)` 或 `添加header` 而不是 `TLS` 可能是更好的选择.
> > 
> > 
> > 还有什么类似爱奇艺的中文视频平台？不喜欢中国大陆视频平台。可以用Paypal氪金。
> 
> 我看英语电视剧电影等等都是rarbg下bt，bt他不香吗？
> 新种速度快，只需要bt站偶尔翻墙一下找磁链或者种子，下载不需要翻墙流量，清晰度有保证，上班时可以家里搞个linux低功耗设备挂机下载。
> bt它真的香！

听音乐和小说呢？国内网站我不想看。视频看ViuTV。

**Comment by okudayukiko** [comment]
> 推荐使用 `ECC` 证书, 长度短, 强度足, 看看能不能解决耗电问题.
> 
> > 在安全性上 256 位的 ECC 证书等同于 3072 位的 RSA 证书
> 
> `RSA` 证书用的比较少, 不太了解, `ECC` 挺稳定的.

主流的EC-256好像也能被识别，用EC-384解决。

**Comment by okudayukiko** [comment]
@DolorHunter 为什么我用acme.sh的Let's Encrypt EC-256证书反而有时速度比RSA证书更慢、更不稳定？

**Comment by DolorHunter** [comment]
我简单查了一下, 似乎确识是这样子的.

> RSA seems to be significantly faster than ECDSA in verifying signatures

但是应该只有在第一次连接域名的时候才会验证证书, 可以大概认为每次上网的时候 ECC 会多一小段的延迟. 但是除了证书的验证之外, 其他方面(加密解密运算, 带宽占用)不会受影响.

访问速度的话, 应该是 ECC 快些(密钥短加解密快)

稳定是什么意思我不太明白.. 有 ssl/tls 都挺稳的, 算法应该无所谓.

生成证书/签名的速度不太要紧, 毕竟两三个月才生成一次新的证书, 没什么感觉.

btw, 如果你想让证书的验证变快可以加一个 OCSP stapling

安装证书的时候多安装一个 `ca-file` 

```plain
acme.sh --install-cert -d mydomain.com --ecc \
        --key-file       /path/to/keyfile/in/nginx/key.pem \
        --fullchain-file /path/to/fullchain/in/nginx/cert.pem \
        --ca-file        /path/to/cafile/in/nginx/ca.pem \
        --reloadcmd     "service nginx force-reload"
```

NGINX 的配置里server段多写一段

```plain
ssl_stapling on;
ssl_stapling_verify on;
# verify chain of trust of OCSP response using Root CA and Intermediate certs
ssl_trusted_certificate /path/to/root_CA_cert_plus_intermediates;  # 对应安装证书中 ca-file 即 ca.pem
# replace with the IP address of your resolver
resolver 8.8.8.8;
```

**Comment by DolorHunter** [comment]
> 
> 
> > > > > > 断流现象可以尝试通过关闭 `MUX`, 或是加大 `alterID` 来解决.
> > > > > 
> > > > > 
> > > > > 用mKCP+TLS，提示TLS handshake error,first record does not look like a TLS handshake.
> > > > 
> > > > 
> > > > ref [v2ray/v2ray-core#343](https://github.com/v2ray/v2ray-core/issues/343)
> > > > > KCP+TLS，传输层还是UDP，只不过传输的数据变成TLS的数据（相当于额外加密）
> > > > 
> > > > 
> > > > 因此, 不建议 `KCP + TLS` 配置. 如果单纯为了加密 KCP协议 下的数据, 使用 `加密(security)` 或 `添加header` 而不是 `TLS` 可能是更好的选择.
> > > 
> > > 
> > > 还有什么类似爱奇艺的中文视频平台？不喜欢中国大陆视频平台。可以用Paypal氪金。
> > 
> > 
> > 我看英语电视剧电影等等都是rarbg下bt，bt他不香吗？
> > 新种速度快，只需要bt站偶尔翻墙一下找磁链或者种子，下载不需要翻墙流量，清晰度有保证，上班时可以家里搞个linux低功耗设备挂机下载。
> > bt它真的香！
> 
> 音乐和小说呢？我不想看国内网站。视频看ViuTV。

抱歉之前没看到. 看太久没动静就 unsubscribe 了.

视频 Youtube (中文内容其实挺多的)
电视剧/电影 [rarbg](https://proxyrarbg.org/) (质量非常好, 但是中文内容基本没有)
音乐可以看看 Spotify
小说基本还是看 Amazon
