### ISSUE TITLE
请问怎么增加mkcp的伪装效果

### ISSUE THREAD

**Issue by Etern213** [v2ray/discussion#507]
基本一到某些时候，mkcp协议的v2ray服务器必定被检测到，说明mkcp自带的那些utp，微信视频等伪装基本已经被识破，有其他增加mkcp安全性的方法吗？
感觉目前大部分伪装方法都是针对tcp的。

因为v2ray不推荐mkcp，所以我在我的服务器上试过tcp，但无奈折腾半天各种锐速bbr也都不好使，谷歌搜索都很慢，更不用说twitch和油管了，最后无奈还得用kcp协议。

所以想请问，有没有更好的mkcp协议伪装方法或者tcp协议的提速方法。

还有，即使是线路正常的时候，我的kcp协议也只是刚刚呢看油管。当时花了不少时间研究v2ray，但还是没摸到门道。。。

**Comment by okudayukiko** [comment]
BBR、动态端口、TLS（尽量用Let's Encrypt），改sysctl.conf

**Comment by DolorHunter** [comment]
KCP / mKCP 协议的设计并不是以安全为目的的, 是一种 UDP 协议, 不可靠但快速.
TCP 以数据传输的可靠为设计目的, 可靠但是通信效率低.

UDP 协议的设计初衷就不是可靠传输, 而是速度快, 所以不会也不应该有很多的 伪装 / 加密 手段.
KCP 和 mKCP 的断流问题似乎是长期存在的, 如果靠修改 header 也无法避免断流, 那似乎也没有什么更好的办法.

我觉得你的问题出在线路上, 而非配置上.

**Comment by Etern213** [comment]
> KCP / mKCP 协议的设计并不是以安全为目的的, 是一种 UDP 协议, 不可靠但快速.
> TCP 以数据传输的可靠为设计目的, 可靠但是通信效率低.
> 
> UDP 协议的设计初衷就不是可靠传输, 而是速度快, 所以不会也不应该有很多的 伪装 / 加密 手段.
> KCP 和 mKCP 的断流问题似乎是长期存在的, 如果靠修改 header 也无法避免断流, 那似乎也没有什么更好的办法.
> 
> 我觉得你的问题出在线路上, 而非配置上.

当时在v2ray介绍上就看到了mkcp的缺陷，但问题是，tcp用什么办法速度都上不来，自闭了快。

**Comment by Etern213** [comment]
> BBR、动态端口、TLS（尽量用Let's Encrypt），改sysctl.conf

请问能详细说下改sysctl.conf吗？感激不尽

**Comment by DolorHunter** [comment]
渣线路不一定能靠配置救回来, 还是建议写工单申请退款.

或者你试试用 cdn 来救? 听说有可能救回来, 但是速度上限肯定也不如好线路来的快.

**Comment by Etern213** [comment]
> 渣线路不一定能靠配置救回来, 还是建议写工单申请退款.
> 
> 或者你试试用 cdn 来救? 听说有可能救回来, 但是速度上限肯定也不如好线路来的快.

一直用的vultr线路，所有线路大概试完，硅谷是最快的。但是tcp基本就看不了油管。。。

**Comment by DolorHunter** [comment]
vultr 的线路一直不好.

**Comment by Etern213** [comment]
> vultr 的线路一直不好.

这样啊，可以推荐几个好线路吗？当时选vultr还是因为他的小时计费可以随时换ip。

**Comment by okudayukiko** [comment]
Vultr只有米国/日本线路比较快
另外建议开VPS后，VPS的SSH设置为用key登录，禁止用密码登录SSH。

**Comment by DolorHunter** [comment]
> 
> 
> > vultr 的线路一直不好.
> 
> 这样啊，可以推荐几个好线路吗？当时选vultr还是因为他的小时计费可以随时换ip。

CN2 GIA ≥ CN2 ≥ 非优化线路

**Comment by okudayukiko** [comment]
> > vultr 的线路一直不好.
> 
> 这样啊，可以推荐几个好线路吗？当时选vultr还是因为他的小时计费可以随时换ip。

有钱还是用CN2线路。

**Comment by okudayukiko** [comment]
在某些网络下，UDP比TCP流畅。
