### ISSUE TITLE
请问outbounds需要前置代理怎么解决

### ISSUE THREAD

**Issue by zhuohan** [v2ray/discussion#51]
![block_of_reverse-vmess](https://user-images.githubusercontent.com/27716434/47983792-6892a480-e10f-11e8-8262-e368ebf0f705.png)

新功能反向代理

如图所示，服务器A在公司中需要通过代理连接外网（连接服务器B），请问如何在outbound中设置前置（socks）代理。这个功能是否会在后面的版本中支持。

**Comment by VictoriaRaymond** [comment]
你是指A和B之间需要 vmess out (A1) -> socks out (A2) -> socks in (X) -> vmess in (B1) 这样的连接方式吗？其中A1和A1在你的A节点，X是公司的socks代理，B1在B节点。

你要参考这篇文章的链式代理部分：https://kirikira.moe/post/26/#2

**Comment by zhuohan** [comment]
啊原来我看过这篇，明白了，非常感谢
