### ISSUE TITLE
V2ray mac客户端可以国内直连，配置到老毛子路由器无法国内直连。

### ISSUE THREAD

**Issue by QinanWu** [v2ray/discussion#511]
服务器节点：版本：V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.)
 V2RayX： Version 1.2.1 (285)  可以国内直连，
路由器客户端节点：版本：V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.)  不能国内直连
### 路由器端配置Config如下：
{
  "log": {
    "error": "/tmp/syslog.log",
    "loglevel": "warning"
  },
  "inbounds":[
    {
      "port": 1088,
      "listen": "192.168.123.1",
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": "192.168.123.1"
      },
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      }
    },{
    //inboundDetour
      "port": "1099",
      "listen": "0.0.0.0",
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp,udp",
        "timeout": 30,
        "followRedirect": true
      }
    }
  ],
  "outbound" : {
    "sendThrough" : "0.0.0.0",
    "mux" : {
      "enabled" : false,
      "concurrency" : 8
    },
    "protocol" : "vmess",
    "settings" : {
      "vnext" : [
        {
          "address" : "my.ip.address",
          "port" : 1088,
          "users" : [
            {
              "id" : "my.uuid",
              "alterId" : 64,
              "security" : "none",
              "level" : 1
            }
          ],
          "remark" : "my.vps"
        }
      ]
    },
    "streamSettings" : {
      "wsSettings" : {
        "path" : "",
        "headers" : {
          "Host" : "server.cc"
        }
      },
      "tlsSettings" : {
        "serverName" : "server.cc",
        "allowInsecure" : false
      },
      "httpSettings" : {
        "path" : "",
        "host" : [
          ""
        ]
      },
      "tcpSettings" : {
        "header" : {
          "type" : "none"
        }
      },
      "kcpSettings" : {
        "header" : {
          "type" : "none"
        },
        "mtu" : 1350,
        "congestion" : false,
        "tti" : 20,
        "uplinkCapacity" : 5,
        "writeBufferSize" : 1,
        "readBufferSize" : 1,
        "downlinkCapacity" : 20
      },
      "network" : "tcp",
      "security" : "none"
    }
  },
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "127.0.0.0/8",
            "::1/128"
          ],
          "outboundTag": "blocked"
        },
        {
          "type": "field",
          "domain": [
            "baidu.com",
            "qq.com",
            "geosite:cn"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "geoip:private",
            "geoip:cn",
            "100.100.100.100/32",
            "188.188.188.188/32",
            "110.110.110.110/32"
          ],
          "outboundTag": "direct"
        }
      ]
    }
  }
}

### macOS端配置Config如下:
{
  "policy" : {
    "levels" : {
      "0" : {
        "uplinkOnly" : 0
      }
    }
  },
  "dns" : {
    "servers" : [
      "localhost"
    ]
  },
  "outboundDetour" : [
    {
      "tag" : "direct",
      "protocol" : "freedom",
      "settings" : {

      }
    }
  ],
  "inbound" : {
    "listen" : "127.0.0.1",
    "protocol" : "socks",
    "settings" : {
      "ip" : "127.0.0.1",
      "auth" : "noauth",
      "udp" : true
    },
    "port" : 1087
  },
  "inboundDetour" : [
    {
      "port" : 1085,
      "listen" : "127.0.0.1",
      "protocol" : "http",
      "allocate" : {
        "refresh" : 5,
        "strategy" : "always",
        "concurrency" : 3
      },
      "tag" : "httpDetour",
      "streamSettings" : {

      },
      "domainOverride" : [
        "http",
        "tls"
      ],
      "settings" : {
        "timeout" : 0
      }
    }
  ],
  "log" : {
    "error" : "\/var\/folders\/12\/8hsw5j8j5fz99dc_k8366dzw0000gn\/T\/cenmrev.v2rayx.log.B08A0C3C-ADB7-4E02-9AA8-5111CE639278\/error.log",
    "loglevel" : "info",
    "access" : "\/var\/folders\/12\/8hsw5j8j5fz99dc_k8366dzw0000gn\/T\/cenmrev.v2rayx.log.B08A0C3C-ADB7-4E02-9AA8-5111CE639278\/access.log"
  },
  "routing" : {
    "strategy" : "rules",
    "settings" : {
      "domainStrategy" : "IPIfNonMatch",
      "rules" : [
        {
          "type" : "field",
          "outboundTag" : "direct",
          "domain" : [
            "localhost",
            "geosite:cn"
          ]
        },
        {
          "type" : "field",
          "outboundTag" : "direct",
          "ip" : [
            "geoip:private",
            "geoip:cn"
          ]
        }
      ]
    }
  },
  "outbound" : {
    "sendThrough" : "0.0.0.0",
    "mux" : {
      "enabled" : false,
      "concurrency" : 8
    },
    "protocol" : "vmess",
    "settings" : {
      "vnext" : [
        {
          "address" : "my.ip.address",
          "port" : 1088,
          "users" : [
            {
              "id" : "my.uuid",
              "alterId" : 64,
              "security" : "aes-128-cfb",
              "level" : 1
            }
          ],
          "remark" : "my.vps"
        }
      ]
    },
    "streamSettings" : {
      "wsSettings" : {
        "path" : "",
        "headers" : {
          "Host" : "server.cc"
        }
      },
      "tlsSettings" : {
        "serverName" : "server.cc",
        "allowInsecure" : false
      },
      "httpSettings" : {
        "path" : "",
        "host" : [
          ""
        ]
      },
      "tcpSettings" : {
        "header" : {
          "type" : "none"
        }
      },
      "kcpSettings" : {
        "header" : {
          "type" : "none"
        },
        "mtu" : 1350,
        "congestion" : false,
        "tti" : 20,
        "uplinkCapacity" : 5,
        "writeBufferSize" : 1,
        "readBufferSize" : 1,
        "downlinkCapacity" : 20
      },
      "network" : "tcp",
      "security" : "none"
    }
  }
}
### 路由器端log：
`2020/01/29 03:42:53 [Warning] [970946128] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:42:53 [Warning] [818978374] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:42:53 [Warning] [2136858944] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:42:53 [Warning] [141347758] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:42:53 [Warning] [1815284298] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:44:27 [Warning] [673309594] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:44:52 [Warning] [995522198] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:45:26 [Warning] [2395024488] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:45:32 [Warning] [2845103375] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:45:32 [Warning] [4074107956] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:45:32 [Warning] [2729314841] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:45:33 [Warning] [1954286782] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:45:33 [Warning] [2764441186] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:45:43 [Warning] [3273371772] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:45:55 [Warning] [3022672411] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:46:27 [Warning] [4195683213] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:46:33 [Warning] [3727817119] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:46:38 [Warning] [4176025638] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:46:38 [Warning] [1084970084] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:47:04 [Warning] [2088870896] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:49:00 [Warning] [2725714104] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:49:37 [Warning] [1872178464] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:49:37 [Warning] [2270442334] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:49:41 [Warning] [813765747] v2ray.com/core/app/dispatcher: non existing tag: direct
2020/01/29 03:49:41 [Warning] [2837980103] v2ray.com/core/app/dispatcher: non existing tag: direct`

**Comment by QinanWu** [comment]
### 修改了Tag后Log：
`
Jan 29 11:56:47 dnsmasq[17887]: exiting on receipt of SIGTERM
Jan 29 11:56:47 dnsmasq[11697]: started, version 2.80 cachesize 1536
Jan 29 11:56:47 dnsmasq[11697]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset no-auth no-DNSSEC no-loop-detect no-inotify no-dumpfile
Jan 29 11:56:47 dnsmasq[11697]: warning: ignoring resolv-file flag because no-resolv is set
Jan 29 11:56:47 dnsmasq-dhcp[11697]: DHCP, IP range 192.168.123.2 -- 192.168.123.244, lease time 1d
Jan 29 11:56:47 dnsmasq-dhcp[11697]: DHCP, sockets bound exclusively to interface br0
Jan 29 11:56:47 dnsmasq[11697]: read /etc/hosts - 4 addresses
Jan 29 11:56:47 dnsmasq[11697]: read /etc/storage/dnsmasq/hosts - 0 addresses
Jan 29 11:56:47 dnsmasq-dhcp[11697]: read /etc/dnsmasq/dhcp/dhcp-hosts.rc
Jan 29 11:56:48 【mtd_storage.sh】: 保存 /etc/storage/ 内容到闪存！请勿关机
Jan 29 11:56:50 【v2ray】:  /opt/ 在内存储存
Jan 29 11:56:50 【v2ray】: 找不到 /opt/bin/v2ctl 下载程序
Jan 29 11:56:51 【mtd_storage.sh】: 保存 /etc/storage/ 内容到闪存！执行完成
Jan 29 11:57:21 【v2ray】: 找不到 /opt/bin/geoip.dat 下载程序
Jan 29 11:58:34 【v2ray】: 找不到 /opt/bin/geosite.dat 下载程序
Jan 29 11:59:00 【v2ray】: 配置文件转换 Protobuf 格式配置
Jan 29 11:59:09 【v2ray】: 找不到 /opt/bin/v2ray 下载程序
Jan 29 11:59:38 【v2ray】: 运行 v2ray_script
2020/01/29 03:59:44 [Warning] v2ray.com/core: V2Ray 4.22.1 started
Jan 29 11:59:44 dnsmasq[11697]: exiting on receipt of SIGTERM
Jan 29 11:59:44 dnsmasq[12373]: started, version 2.80 cachesize 1536
Jan 29 11:59:44 dnsmasq[12373]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset no-auth no-DNSSEC no-loop-detect no-inotify no-dumpfile
Jan 29 11:59:44 dnsmasq[12373]: warning: ignoring resolv-file flag because no-resolv is set
Jan 29 11:59:44 dnsmasq-dhcp[12373]: DHCP, IP range 192.168.123.2 -- 192.168.123.244, lease time 1d
Jan 29 11:59:44 dnsmasq-dhcp[12373]: DHCP, sockets bound exclusively to interface br0
Jan 29 11:59:44 dnsmasq[12373]: read /etc/hosts - 4 addresses
Jan 29 11:59:44 dnsmasq[12373]: read /etc/storage/dnsmasq/hosts - 0 addresses
Jan 29 11:59:44 dnsmasq-dhcp[12373]: read /etc/dnsmasq/dhcp/dhcp-hosts.rc
Jan 29 11:59:44 【v2ray】: 启动成功 V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/mipsle) 
Jan 29 11:59:44 dnsmasq[12373]: exiting on receipt of SIGTERM
Jan 29 11:59:44 dnsmasq[12412]: started, version 2.80 cachesize 1536
Jan 29 11:59:44 dnsmasq[12412]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset no-auth no-DNSSEC no-loop-detect no-inotify no-dumpfile
Jan 29 11:59:44 dnsmasq[12412]: warning: ignoring resolv-file flag because no-resolv is set
Jan 29 11:59:44 dnsmasq-dhcp[12412]: DHCP, IP range 192.168.123.2 -- 192.168.123.244, lease time 1d
Jan 29 11:59:44 dnsmasq-dhcp[12412]: DHCP, sockets bound exclusively to interface br0
Jan 29 11:59:44 dnsmasq[12412]: read /etc/hosts - 4 addresses
Jan 29 11:59:44 dnsmasq[12412]: read /etc/storage/dnsmasq/hosts - 0 addresses
Jan 29 11:59:44 dnsmasq-dhcp[12412]: read /etc/dnsmasq/dhcp/dhcp-hosts.rc
Jan 29 11:59:44 【v2ray】: 启动 透明代理
Jan 29 11:59:44 【v2ray】: chinadns 已经启动 防止域名污染
Jan 29 11:59:44 dnsmasq[12412]: exiting on receipt of SIGTERM
Jan 29 11:59:44 dnsmasq[12419]: started, version 2.80 cachesize 1536
Jan 29 11:59:44 dnsmasq[12419]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset no-auth no-DNSSEC no-loop-detect no-inotify no-dumpfile
Jan 29 11:59:44 dnsmasq[12419]: warning: ignoring resolv-file flag because no-resolv is set
Jan 29 11:59:44 dnsmasq-dhcp[12419]: DHCP, IP range 192.168.123.2 -- 192.168.123.244, lease time 1d
Jan 29 11:59:44 dnsmasq-dhcp[12419]: DHCP, sockets bound exclusively to interface br0
Jan 29 11:59:44 dnsmasq[12419]: read /etc/hosts - 4 addresses
Jan 29 11:59:44 dnsmasq[12419]: read /etc/storage/dnsmasq/hosts - 0 addresses
Jan 29 11:59:44 dnsmasq-dhcp[12419]: read /etc/dnsmasq/dhcp/dhcp-hosts.rc
Jan 29 11:59:44 【v2ray】: 完成 透明代理 转发规则设置
Jan 29 11:59:44 【v2ray】: 守护进程启动
Jan 29 11:59:48 crond[13566]: crond (busybox 1.29.3) started, log level 8
2020/01/29 04:11:07 [Warning] [1446582933] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 34.80.193.230:1088: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed

`

**Comment by QinanWu** [comment]
### Log：
Jan 29 11:59:48 crond[13566]: crond (busybox 1.29.3) started, log level 8
2020/01/29 04:11:07 [Warning] [1446582933] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp my.ipaddress.port: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2020/01/29 04:16:37 [Warning] [1351910316] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp my.ipaddress.port: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2020/01/29 04:17:57 [Warning] [2294318302] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/01/29 04:17:58 [Warning] [4119387724] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/01/29 04:18:06 [Warning] [3774145645] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > read tcp 192.168.1.3:31804->my.ipaddress.port: read: connection timed out
2020/01/29 04:18:13 [Warning] [3959778189] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/01/29 04:18:22 [Warning] [1005037565] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > read tcp 192.168.1.3:31812->my.ipaddress.port: read: connection timed out
2020/01/29 04:18:28 [Warning] [2852898277] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > read tcp 192.168.1.3:31814->my.ipaddress.port: read: connection timed out
2020/01/29 04:18:29 [Warning] [2821260371] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp my.ipaddress.port: connect: connection timed out dial tcp my.ipaddress.port: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2020/01/29 04:18:35 [Warning] [4294763956] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/01/29 04:18:36 [Warning] [1624989691] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp my.ipaddress.port: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2020/01/29 04:18:36 [Warning] [2865844667] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp my.ipaddress.port: connect: connection timed out dial tcp my.ipaddress.port: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2020/01/29 04:26:51 [Warning] [2889004243] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp my.ipaddress.port: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2020/01/29 04:31:02 [Warning] [3390089558] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > read tcp 192.168.1.3:31953->my.ipaddress.port: read: connection timed out
2020/01/29 04:31:07 [Warning] [3996360007] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > read tcp 192.168.1.3:31954->my.ipaddress.port: read: connection timed out
2020/01/29 04:31:14 [Warning] [3015199189] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > read tcp 192.168.1.3:31955->my.ipaddress.port: read: connection timed out
2020/01/29 04:32:09 [Warning] [1684891232] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/01/29 04:32:33 [Warning] [1753562358] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > read tcp 192.168.1.3:31978->my.ipaddress.port: read: connection timed out
2020/01/29 04:32:55 [Warning] [1016115041] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > read tcp 192.168.1.3:31985->my.ipaddress.port: read: connection timed out

**Comment by kslr** [comment]
tcp 192.168.1.3:31953->my.ipaddress.port: read: connection timed out

局域网怎么也给代理了？

**Comment by QinanWu** [comment]
> tcp 192.168.1.3:31953->my.ipaddress.port: read: connection timed out
> 
> 局域网怎么也给代理了？
> 
> ===
> .3是你的电脑吗

说来就有些话长了：
我的路由器是从光纤猫上桥接的，光纤猫分给路由器的是192.168.1.3, 路由的连接类型是：IPoE: 动态 IP
而路由器本身设定的访问地址是192.168.123.1

**Comment by QinanWu** [comment]
{
  "policy": null,
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      //inboundDetour
      "port": "1099",
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp,udp",
        "timeout": 0,
        "followRedirect": true
      }
    },
    {
      "tag": "direct",
      "port": 1088,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "address": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "my.ipaddress",
            "port": 1088,
            "users": [
              {
                "id": "my.uuid",
                "alterId": 64,
                "email": "t@t.tt",
                "security": "aes-128-gcm"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "tcp",
        "security": null,
        "tlsSettings": null,
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": null,
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "stats": null,
  "api": null,
  "dns": null,
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "ip": null,
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "proxy",
        "ip": null,
        "domain": [
          "geosite:google",
          "geosite:github",
          "geosite:netflix",
          "geosite:steam",
          "geosite:telegram",
          "geosite:tumblr",
          "geosite:speedtest",
          "geosite:bbc",
          "domain:gvt1.com",
          "domain:textnow.com",
          "domain:twitch.tv",
          "domain:wikileaks.org",
          "domain:naver.com"
        ]
      },
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "proxy",
        "ip": [
          "91.108.4.0/22",
          "91.108.8.0/22",
          "91.108.12.0/22",
          "91.108.20.0/22",
          "91.108.36.0/23",
          "91.108.38.0/23",
          "91.108.56.0/22",
          "149.154.160.0/20",
          "149.154.164.0/22",
          "149.154.172.0/22",
          "74.125.0.0/16",
          "173.194.0.0/16",
          "172.217.0.0/16",
          "216.58.200.0/24",
          "216.58.220.0/24",
          "91.108.56.116",
          "91.108.56.0/24",
          "109.239.140.0/24",
          "149.154.167.0/24",
          "149.154.175.0/24"
        ],
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "direct",
        "ip": null,
        "domain": [
          "domain:12306.com",
          "domain:51ym.me",
          "domain:52pojie.cn",
          "domain:8686c.com",
          "domain:abercrombie.com",
          "domain:adobesc.com",
          "domain:air-matters.com",
          "domain:air-matters.io",
          "domain:airtable.com",
          "domain:akadns.net",
          "domain:apache.org",
          "domain:api.crisp.chat",
          "domain:api.termius.com",
          "domain:appshike.com",
          "domain:appstore.com",
          "domain:aweme.snssdk.com",
          "domain:bababian.com",
          "domain:battle.net",
          "domain:beatsbydre.com",
          "domain:bet365.com",
          "domain:bilibili.cn",
          "domain:ccgslb.com",
          "domain:ccgslb.net",
          "domain:chunbo.com",
          "domain:chunboimg.com",
          "domain:clashroyaleapp.com",
          "domain:cloudsigma.com",
          "domain:cloudxns.net",
          "domain:cmfu.com",
          "domain:culturedcode.com",
          "domain:dct-cloud.com",
          "domain:didialift.com",
          "domain:douyutv.com",
          "domain:duokan.com",
          "domain:dytt8.net",
          "domain:easou.com",
          "domain:ecitic.net",
          "domain:eclipse.org",
          "domain:eudic.net",
          "domain:ewqcxz.com",
          "domain:fir.im",
          "domain:frdic.com",
          "domain:fresh-ideas.cc",
          "domain:godic.net",
          "domain:goodread.com",
          "domain:haibian.com",
          "domain:hdslb.net",
          "domain:hollisterco.com",
          "domain:hongxiu.com",
          "domain:hxcdn.net",
          "domain:images.unsplash.com",
          "domain:img4me.com",
          "domain:ipify.org",
          "domain:ixdzs.com",
          "domain:jd.hk",
          "domain:jianshuapi.com",
          "domain:jomodns.com",
          "domain:jsboxbbs.com",
          "domain:knewone.com",
          "domain:kuaidi100.com",
          "domain:lemicp.com",
          "domain:letvcloud.com",
          "domain:lizhi.io",
          "domain:localizecdn.com",
          "domain:lucifr.com",
          "domain:luoo.net",
          "domain:mai.tn",
          "domain:maven.org",
          "domain:miwifi.com",
          "domain:moji.com",
          "domain:moke.com",
          "domain:mtalk.google.com",
          "domain:mxhichina.com",
          "domain:myqcloud.com",
          "domain:myunlu.com",
          "domain:netease.com",
          "domain:nfoservers.com",
          "domain:nssurge.com",
          "domain:nuomi.com",
          "domain:ourdvs.com",
          "domain:overcast.fm",
          "domain:paypal.com",
          "domain:paypalobjects.com",
          "domain:pgyer.com",
          "domain:qdaily.com",
          "domain:qdmm.com",
          "domain:qin.io",
          "domain:qingmang.me",
          "domain:qingmang.mobi",
          "domain:qqurl.com",
          "domain:rarbg.to",
          "domain:rrmj.tv",
          "domain:ruguoapp.com",
          "domain:sm.ms",
          "domain:snwx.com",
          "domain:soku.com",
          "domain:startssl.com",
          "domain:store.steampowered.com",
          "domain:symcd.com",
          "domain:teamviewer.com",
          "domain:tmzvps.com",
          "domain:trello.com",
          "domain:trellocdn.com",
          "domain:ttmeiju.com",
          "domain:udache.com",
          "domain:uxengine.net",
          "domain:weather.bjango.com",
          "domain:weather.com",
          "domain:webqxs.com",
          "domain:weico.cc",
          "domain:wenku8.net",
          "domain:werewolf.53site.com",
          "domain:windowsupdate.com",
          "domain:wkcdn.com",
          "domain:workflowy.com",
          "domain:xdrig.com",
          "domain:xiaojukeji.com",
          "domain:xiaomi.net",
          "domain:xiaomicp.com",
          "domain:ximalaya.com",
          "domain:xitek.com",
          "domain:xmcdn.com",
          "domain:xslb.net",
          "domain:xteko.com",
          "domain:yach.me",
          "domain:yixia.com",
          "domain:yunjiasu-cdn.net",
          "domain:zealer.com",
          "domain:zgslb.net",
          "domain:zimuzu.tv",
          "domain:zmz002.com",
          "domain:samsungdm.com"
        ]
      },
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "block",
        "ip": null,
        "domain": [
          "geosite:category-ads-all"
        ]
      },
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "direct",
        "ip": [
          "geoip:private"
        ],
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "direct",
        "ip": [
          "geoip:cn"
        ],
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "direct",
        "ip": null,
        "domain": [
          "geosite:cn"
        ]
      }
    ]
  }
}
2020-01-29 22:35:39 ### 更新： 使用了这个config后，后台无warning，可以直连了
### 使用
先打开v2ray，v2ray运行成功后，再打开chinadns，测试国内直连！

**Comment by QinanWu** [comment]
至于为什么会这样，从原理上还是不理解，还请有知道的大神给说一下？

**Comment by QinanWu** [comment]
使用了两天，还是存在一个问题，无法稳定连接微信，一些app内的视频，总是延迟很高，这个不知道有没有什么方法可解？

**Comment by kslr** [comment]
这很可能是你的透明代理策略问题，你可以试试基于DNS的策略

**Comment by fishtreesugar** [comment]
根据 #199 `outboundDetour` 这个配置项已经废弃, 所以配置里的 `outboundDetour` 并没有起作用, 因此没有 `direct` 这个 tag.  只要把它变为 其中一个 `outbound` 就可以了

**Comment by QinanWu** [comment]
v2ray老是被封端口

**Comment by byron2008rzl** [comment]
> 使用了两天，还是存在一个问题，无法稳定连接微信，一些app内的视频，总是延迟很高，这个不知道有没有什么方法可解？

我也是这个问题，楼主你后来怎么解决的呢？

**Comment by karlgitcode** [comment]
@QinanWu @byron2008rzl 
我也是这个问题，您后来解决了吗？
而且我也是从光纤猫上桥接的

**Comment by karlgitcode** [comment]
@QinanWu @byron2008rzl 
就是微信一直“连接中”，其他都还算正常，而且我发现只有iOS微信有这个问题，安卓微信倒是正常
