### ISSUE TITLE
OpenWRT上V2Ray配置Tproxy实现ws+tls+cdn不成功

### ISSUE THREAD

**Issue by configmaker** [v2ray/discussion#512]
PC和手机上已经成功实现V2Ray+ws+tls+cdn，将手机客户端配置增加透明代理。
curl -so /dev/null -w "%{http_code}" google.com -x socks5://127.0.0.1:1080 返回301，添加防火墙规则后不能上网，国内和海外都不能用FQDN访问，但是用IP可以。百思不得其解，请大神帮忙看看。

OpenWRT上的clint端配置如下：
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag":"transparent",
      "port": 12345,
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp,udp",
        "followRedirect": true
      },
      "sniffing": {
        "enabled": true,
        "destOverride": ["http","tls"]
      },
      "streamSettings": {
        "sockopt": {"tproxy": "tproxy"}
      }
    },
    {
      "port": 1080,
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http","tls"]
      },
      "settings": {
        "auth": "noauth"
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": “my server",
            "port": 443,
            "users": [
              {
                "id": "ID",
                "alterId": 64,
                "security": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": null
        },
        "wsSettings": {
          "connectionReuse": true,
          "path": "/v2ray",
          "headers": null
        },
        "sockopt": {"mark": 255}
      },
      "mux": {"enabled": true}
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      },
      "streamSettings": {
        "sockopt": {"mark": 255}
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {"type": "http"}
      }
    },
    {
      "tag": "dns-out",
      "protocol": "dns",
      "streamSettings": {
        "sockopt": {"mark": 255}
      }
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "1.1.1.1",
      {
        "address": "223.5.5.5",
        "port": 53,
        "domains": [
          "geosite:cn",
          "ntp.org",
          "my domain"
        ]
      }
    ]
  },
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "inboundTag": ["transparent"],
        "port": 53,
        "network": "udp",
        "outboundTag": "dns-out"
      },
      {
        "type": "field",
        "inboundTag": ["transparent"],
        "port": 123,
        "network": "udp",
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": [
          "223.5.5.5",
          "114.114.114.114"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": [
          "8.8.8.8",
          "1.1.1.1"
        ],
        "outboundTag": "proxy"
      },
      {
        "type": "field",
        "domain": ["geosite:category-ads-all"],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "protocol":["bittorrent"],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": [
          "geoip:private",
          "geoip:cn"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": ["geosite:cn"],
        "outboundTag": "direct"
      }
    ]
  }
}

VPS上的server端配置如下：
{
  "inbounds": [{
    "port": 10000,
    "listen": "127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "my ID",
          "level": 1,
          "alterId": 64
        }
      ]
    },
    "streamSettings": {
        "network": "ws",
        "wsSettings": {
        "path": "/v2ray"
        }
      }
  }],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      },
      {
        "type": "field",
        "outboundTag": "block",
        "protocol": [
          "bittorrent"
        ]
      }
    ]
  }
}

iptables规则同官网。

log信息：
2020/01/29 03:53:18 [Info] v2ray.com/core/app/dns: UDP:8.8.8.8:53 got answere: google.com. TypeAAAA -> [[2607:f8b0:4007:800::200e]] 913.86818ms
2020/01/29 03:53:18 [Debug] v2ray.com/core/app/dns: UDP:8.8.8.8:53 updating IP records for domain:google.com.
2020/01/29 03:53:18 [Info] [746383364] v2ray.com/core/app/dispatcher: default route for tcp:google.com:80
2020/01/29 03:53:18 [Info] [746383364] v2ray.com/core/common/mux: dispatching request to tcp:google.com:80
2020/01/29 03:53:18 [Info] v2ray.com/core/app/dns: UDP:8.8.8.8:53 got answere: google.com. TypeA -> [172.217.4.142] 922.50696ms
2020/01/29 03:53:18 [Debug] v2ray.com/core/app/dns: UDP:8.8.8.8:53 updating IP records for domain:google.com.
2020/01/29 03:53:25 [Info] v2ray.com/core/transport/internet/udp: failed to handle UDP input > EOF
2020/01/29 03:53:33 [Info] v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2020/01/29 03:53:34 [Info] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled

**Comment by kslr** [comment]
尝试取消UDP

**Comment by configmaker** [comment]
> 尝试取消UDP

请问哪里不妥?能说具体点吗？

**Comment by chen-jiao** [comment]
> > 尝试取消UDP
> 
> 请问哪里不妥?能说具体点吗？

我也有这个问题，请问你后来有搞定这个问题么？是怎么弄好的啊？

**Comment by configmaker** [comment]
问题还没有解决。哪位有解法，请帮忙说一下。谢谢！

**Comment by designer-fanfan** [comment]
我也遇到了同样的问题，ws+tls+cdn直接连接失败，我其他没有套cdn的可以连接，在梅林或者pc手机客户端都可以连接，有解决方案么？
