### ISSUE TITLE
v2ray Active: failed (Result: exit-code) 

### ISSUE THREAD

**Issue by merkillow** [v2ray/discussion#514]
v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-01-30 18:06:36 CST; 14s ago
  Process: 10745 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited, status=23)
 Main PID: 10745 (code=exited, status=23)

Jan 30 18:06:36 amazing-story-1.localdomain systemd[1]: Started V2Ray Service.
Jan 30 18:06:36 amazing-story-1.localdomain v2ray[10745]: V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64)
Jan 30 18:06:36 amazing-story-1.localdomain v2ray[10745]: A unified platform for anti-censorship.
Jan 30 18:06:36 amazing-story-1.localdomain v2ray[10745]: main: failed to read config file: /etc/v2ray/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray
Jan 30 18:06:36 amazing-story-1.localdomain v2ray[10745]:  > exit status 255
Jan 30 18:06:36 amazing-story-1.localdomain systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
Jan 30 18:06:36 amazing-story-1.localdomain systemd[1]: v2ray.service: Unit entered failed state.
Jan 30 18:06:36 amazing-story-1.localdomain systemd[1]: v2ray.service: Failed with result 'exit-code'.

**Comment by DolorHunter** [comment]
> Jan 30 18:06:36 amazing-story-1.localdomain v2ray[10745]: main: failed to read config file: /etc/v2ray/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core
