### ISSUE TITLE
access log中出现异常记录，求教如何溯源

### ISSUE THREAD

**Issue by huxuan** [v2ray/discussion#516]
家里是AC86U装的梅林系统，配置了arm版的v2ray以及redirect的透明代理，路由器本身未翻墙（用来下PT了），一直使用正常，最近发现access log中出现了一些异常的记录，怀疑是被家里网络被黑了或者某个终端中木马了，但是折腾了半天也没找到原因，能想到的搜索关键词都搜了，还望能有大神相助。

主要日志记录片段如下：
```
2020/01/30 10:12:36 tcp:114.253.233.244:40172 accepted tcp:email.163.com:80 [direct]
2020/01/30 10:12:45 tcp:114.253.233.244:40191 accepted tcp:47.245.0.3:8080 [proxy]
2020/01/30 10:13:04 tcp:114.253.233.244:40236 accepted tcp:59.110.167.13:8080 [direct]
2020/01/30 10:13:12 tcp:114.253.233.244:40254 accepted tcp:email.163.com:80 [direct]
2020/01/30 10:13:26 tcp:114.253.233.244:40297 accepted tcp:boxun.com:80 [proxy]
2020/01/30 10:13:26 tcp:114.253.233.244:40298 accepted tcp:www.ipip.net:443 [direct]
2020/01/30 10:13:27 tcp:114.253.233.244:40299 accepted tcp:www.123cha.com:80 [proxy]
2020/01/30 10:13:27 tcp:114.253.233.244:40301 accepted tcp:www.wujieliulan.com:80 [proxy]
2020/01/30 10:13:27 tcp:114.253.233.244:40308 accepted tcp:www.minghui.org:80 [proxy]
2020/01/30 10:13:27 tcp:114.253.233.244:40304 accepted tcp:cn.bing.com:443 [direct]
2020/01/30 10:13:27 tcp:114.253.233.244:40303 accepted tcp:www.baidu.com:443 [direct]
2020/01/30 10:13:27 tcp:114.253.233.244:40306 accepted tcp:www.epochtimes.com:80 [proxy]
2020/01/30 10:13:27 tcp:114.253.233.244:40318 accepted tcp:cdn.ipip.net:443 [direct]
```

这些网址应该都不是我平常访问的，而且出现了大量的篇幅，最奇怪的是前面的 IP 地址是我的（已经失效的）外网 IP，但是我试了在路由器上用代理访问显示的应该是127.0.0.1的地址，在笔记本上用路由器内网ip的代理显示的是192.168的内网地址，透明代理似乎没有access log，显示成外网 IP 我都无法判断是哪个终端被黑了。

还望求教，不胜感谢

**Comment by iochen** [comment]
路由器上有 端口转发 吗

**Comment by huxuan** [comment]
@iochen 没有，倒是开了 IPSec 的 VPN Server，但是我试了用4G连VPN通过透明代理访问也没有access记录。

**Comment by iochen** [comment]
我一时也看不出来，要不你把透明代理关掉，并且本地http和socks设置一个用户名和密码，逐个设备排除或者二分法试试

**Comment by huxuan** [comment]
@iochen 好的，非常感谢！看来也只能这么搞了，正好假期我来折腾一下，再次感谢！

**Comment by huxuan** [comment]
在家办公抽空折腾终于算是把事情搞出点眉目了，稍微整理一下方便后来人~

1. 在桥接的路由器上配置的所以有外网 IP（我还设置了 DDNS）
2. V2RAY 的 [socks](https://www.v2ray.com/chapter_02/protocols/socks.html#inboundconfigurationobject) 似乎默认绑定在了 `0.0.0.0` 上，而不是文档里说的 `127.0.0.1`
3. 透明代理使得外网的请求被转发然后显示成了 WAN IP

综上，感觉自己的路由器是被当做肉鸡扫端口了，而且日志里显示的都是 WAN IP。

我在其它机器上也能重现，直接 `curl -x socks5://<DDNS域名>:1080 google.com` 就可以了，开启透明代理会显示 WAN IP，关掉之后就会显示实际的 IP 了，我也看到一直扫的那台机器的 IP 了。

非常感谢 @iochen ，是你提醒关掉透明代理之后才找到了突破口，不过我试了在 socks 的配置中 `"ip":"127.0.0.1"` 或者 `"address":"127.0.0.1"` 都是无效的，用`netstat`查看似乎还是绑定在了 `0.0.0.0` 上，不知道是不是我的姿势有问题，或者算是一个 bug？没看过具体代码实现瞎猜的。

目前的解决方案是直接用 `iptables` 禁掉了所有`dport`为 1080 的访问

```
iptables -I INPUT -p tcp --dport 1080 -j DROP
```

应该 tcp 就够了，不放心的话把 udp 的加上也无妨，如果本地和局域网还有直接访问 socks 的需求也可以开一下

```
iptables -I INPUT -p tcp -s 127.0.0.0/8 --dport 1080 -j ACCEPT
iptables -I INPUT -p tcp -s 192.168.0.0/16 --dport 1080 -j ACCEPT
```

大概就这样了，我再观察几天，要是被打脸了就再来 update，这个 issue 就先 close 了。

**Comment by huxuan** [comment]
在网上又搜了搜发现真真的 config 关键字好像是 `listen`，那直接设置 `"listen":"127.0.0.1"`就不需要配防火墙了。目前为止日志都是干净的~
