### ISSUE TITLE
(通篇口胡，请求删除)关于ws+TLS配置下玄学断流问题的尝试性解决方案及原理猜测

### ISSUE THREAD

**Issue by NiceBowl335** [v2ray/discussion#517]
初次注册github，如有发言格式错误敬请指正。
#全文充满了不切实际的猜测
之前用了233boy前辈提供的一键脚本，成功部署了ws+tls，然而之后出现了较频繁的断流问题，情况与https://github.com/v2ray/v2ray-core/issues/2198 类似。
在讨论区闲逛时，发现在https://github.com/v2ray/discussion/issues/506 这篇帖子里有人提到过增大alterID。
我尝试性地提高alterID至五位数后，发现vps的内存和CPU占用立刻飙升（单核1G的贫民服务器）。查阅后发现，alterID是一种以空间换安全的加密方式，一般10以下足矣。
而在233boy的脚本中，alterID被默认设置为233，略大（他自己在博文里也提到过这个值偏大）。
于是，我又把alterID改低至10。
重启并连接v2ray（全局代理模式）后，在接近一个小时的使用时间内均未发生断流现象。
推测是较高的alterID严重占用vps资源导致服务挂掉。

然而，在进行了上述改动后，偶发“连接已重置”现象。
即访问墙外网站时会提示“连接已重置”，访问墙内网站（如知乎，百度，个人博客等）保持正常，不知是不是因为alterID太小导致安全性降低，被GFW注意到了...无操作情况下，几分钟后会恢复正常。（ps: 不成...不操作的话没法恢复正常...我可能是当时顺手重连之后，没记在心上）

一点愚见，抛砖引玉。

**Comment by NiceBowl335** [comment]
如果是断流的话，则是直接提示“代理服务器拒绝访问”

**Comment by NiceBowl335** [comment]
呃...刚才又出现了最初的断流问题...

**Comment by NiceBowl335** [comment]
呃...刚才又短暂地出现了断流的现象，但我没有重连，约一分钟之后恢复正常。

**Comment by NiceBowl335** [comment]
又双断流...又是片刻后恢复正常。
值得一提的是，测试时一直在用Chrome播放Youtube的视频，发生断流后，Chrome打开新的标签页，提示“代理服务器发生问题”，打开Firefox访问百度后，v2ray恢复连接...不知道是巧合还是另有隐情。

**Comment by NiceBowl335** [comment]
又是上一层的重复...同样的打开Firefox访问百度后恢复。下次试试双手离开键盘不做任何操作...

**Comment by NiceBowl335** [comment]
22:55 再次断流 无操作 彻底挂掉
Chrome提示未连接到互联网。代理服务器出现问题，或者地址有误。

Firefox提示代理服务器拒绝连接。Firefox 尝试与您指定的代理服务器连接时被拒绝。

V2RayN客户端提示v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled

**Comment by NiceBowl335** [comment]
好吧...看来断流不是alterID的问题 打扰了...

**Comment by i553041** [comment]
> 初次注册github，如有发言格式错误敬请指正。
> #全文充满了不切实际的猜测
> 之前用了233boy前辈提供的一键脚本，成功部署了ws+tls，然而之后出现了较频繁的断流问题，情况与[v2ray/v2ray-core#2198](https://github.com/v2ray/v2ray-core/issues/2198) 类似。
> 在讨论区闲逛时，发现在#506 这篇帖子里有人提到过增大alterID。
> 我尝试性地提高alterID至五位数后，发现vps的内存和CPU占用立刻飙升（单核1G的贫民服务器）。查阅后发现，alterID是一种以空间换安全的加密方式，一般10以下足矣。
> 而在233boy的脚本中，alterID被默认设置为233，略大（他自己在博文里也提到过这个值偏大）。
> 于是，我又把alterID改低至10。
> 重启并连接v2ray（全局代理模式）后，在接近一个小时的使用时间内均未发生断流现象。
> 推测是较高的alterID严重占用vps资源导致服务挂掉。
> 
> 然而，在进行了上述改动后，偶发“连接已重置”现象。
> 即访问墙外网站时会提示“连接已重置”，访问墙内网站（如知乎，百度，个人博客等）保持正常，不知是不是因为alterID太小导致安全性降低，被GFW注意到了...无操作情况下，几分钟后会恢复正常。（ps: 不成...不操作的话没法恢复正常...我可能是当时顺手重连之后，没记在心上）
> 
> 一点愚见，抛砖引玉。

請問有沒有用手機客戶端去測試一下？有沒有出現斷流問題？因為我主要㑹用手機客戶端多。

最近發現我的v2ray無故重啟，log內顯示是out of memory。

https://github.com/v2ray/v2ray-core/issues/2197

kslr君建議調低AlterID，原本是64的，我參考過網上資料後，設置為16，運行了3天，暫時還不知道結果。

資料顯示這個AlterID的選項是用檢測用的，設置得太大，㑹吃很多VPS的內存，設得太低，抗檢測方面又不知道㑹不㑹有甚麼問題。(以前是不知道的)。

**Comment by kslr** [comment]
文档中的建议值是4，默认值是0
