### ISSUE TITLE
"alterid" 有甚麽用？看完後，大家应有个数了

### ISSUE THREAD

**Issue by kingwilliam** [v2ray/discussion#518]
v2的"alterid"有甚麽用，官网说得比较含糊，我也看见不少文章都问这个用途，回覆已不着边际，在一份很旧的使用手册（大约version 2.x）有以下描述！！原文已不全在！！。

- VMess 依赖于系统时间，请确保使用 V2Ray 的系统 UTC 时间误差在 90 秒之内。
- 时间戳的取值范围只有 60 个值，当客户端产生大量数据请求时，部分请求可能会使用了相同的时间戳，进而产生相同的认证信息。在这种情况下，通讯数据有可能被模式识别。为了降低可识别性，VMess 配置中有一个 alterId 设置。如果 alterId > 0，VMess 在当前 ID 的基础上自动生成 alterId 个不同的 ID，并用于通讯。alterId 的值越大，认证信息重复的概率就越小。实际的 alterId 值可以根据你的上网情况推算出来，一般的网页浏览平均每秒打开最多一个网页，平均一个网页发起 10 个连接，那么 alterId 的值设为 10 即可。

最後補充：
- 服務端和客戶端的alterid值可以不一樣，但一定要“客戶端 <= 服務端”
- 理论上 alterId 越大越好，但越大就约占内存(只针对服务器，客户端不占内存) (出于 [白话文教程-基本篇-VMess协议-1.3.2.-服务器](https://toutyrater.github.io/basic/vmess.html))
- 因v2发展非常讯速,上文已是version 2.x时代的解说。到今天还是否可这样解说，只能由v2团队确实。

**Comment by forever8938** [comment]
alterId对客户端有性能影响吗？

**Comment by xsidc** [comment]
请问alterid如果设置0，那么会被GFW墙IP吗？

**Comment by ft0907** [comment]
问下，你们是服务器端和客户端的alterid都是设置的0还是只是修改了客户端alterid=0？

**Comment by blacktear** [comment]
[v4.28.1](https://github.com/v2fly/v2ray-core/releases/tag/v4.28.1) VMess AEAD will be used when alterId is 0. [vmess](https://www.v2raydocs.web.illinois.edu/config/protocols/vmess.html)
