### ISSUE TITLE
v2ray+mkcp已经无法使用了，各位遇到这个问题没？

### ISSUE THREAD

**Issue by cookiepool** [v2ray/discussion#523]
三个vps，全部完蛋。从昨天开始的，目前就Trojan正常，v2ray+mkcp前面一直正常，现在就不行了，客户端报错是failed read response header。

**Comment by forever8938** [comment]
要试一下kcptun能不能用，如果也不行的话就是kcp被墙

**Comment by 1329154840** [comment]
v2ray配合mkcp服务端正常启动，客户端连接后访问服务端报错

2020/02/10 01:24:47 [Warning] [4209787354] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.

**Comment by fbion** [comment]
哪家宽带 vps

**Comment by okudayukiko** [comment]
kcp确实不能用。

**Comment by OPTOPIA** [comment]
kcp不能用了，已经被ban了三个ip了。目前ws+tls+cdn 比较稳

**Comment by maddie** [comment]
@OPTOPIA CDN有哪家推荐？Cloudflare实在是慢

**Comment by OPTOPIA** [comment]
> @OPTOPIA CDN有哪家推荐？Cloudflare实在是慢
试试CloudFront？我用CloudFlare,联通还不错。电信的话出口走了北京，估计是运营商限制，很慢。

**Comment by maddie** [comment]
谢谢，回头试试

**Comment by fbion** [comment]
> > @OPTOPIA CDN有哪家推荐？Cloudflare实在是慢
> > 试试CloudFront？我用CloudFlare,联通还不错。电信的话出口走了北京，估计是运营商限制，很慢。

机场中转,有钱上iplc深港专线

**Comment by iochen** [comment]
Please stop using mKCP.

**Comment by okudayukiko** [comment]
KCP+Chacha20-Poly1305秒封IP。
有钱上CN2系列。

**Comment by maddie** [comment]
深圳电信，搞了个bandwagon的LAX CN2，发现比Linode的Fremont节点还慢

CN2 GIA全部out of stock，不过看测速感觉并没有比CN2快多少（甚至更慢的感觉）

摊手

**Comment by okudayukiko** [comment]
> 深圳电信，搞了个bandwagon的LAX CN2，发现比Linode的Fremont节点还慢
> 
> CN2 GIA全部out of stock，不过看测速感觉并没有比CN2快多少（甚至更慢的感觉）
> 
> 摊手

我试过 香港/日本/澳门的CN2 比 Vultr好很多。

**Comment by forever8938** [comment]
CN2 GIA全天秒开4k。

**Comment by fbion** [comment]
套这个
https://github.com/wangyu-/udp2raw-tunnel

**Comment by Chocofate** [comment]
使用 docker 版本，同遇到 开启 mkcp 报错 failed read response header ...
