### ISSUE TITLE
Openwrt开启v2ray、fullcone，nat类型电脑端测出来是fullcone，但PS4测出来依旧是nat3

### ISSUE THREAD

**Issue by rxf1991** [v2ray/discussion#531]
请教一下，K2P装Openwrt开启v2ray、fullcone，nat类型电脑端测出来是fullcone，但PS4测出来依旧是nat3。用SSR的话，ps4就还是nat2。请问该问题应如何解决，谢谢！

**Comment by forever8938** [comment]
v2ray不能加速游戏，不用折腾了，nat3是肯定的。如果我没记错的话，ss-redir也是nat3，不过可以加速游戏。

**Comment by rxf1991** [comment]
> v2ray不能加速游戏，不用折腾了，nat3是肯定的。如果我没记错的话，ss-redir也是nat3，不过可以加速游戏。

凉凉，谢谢解惑。
原本SSR开UDP转发可以做到NAT2，最近封锁厉害，机场都换V2RAY了，看来这下游戏加速是没的玩了。

**Comment by chinanoahli** [comment]
ps4我没怎么玩车枪球，mh最近似乎裸连也很稳定了，甚至没用加速器。
另外游戏还是老实买个加速器吧，术业有专攻系列。

**Comment by xuedong97** [comment]
是不是tcp那里填翻墙用的v2服务器，然后udp那里填游戏ss服务器 然后开启游戏模式？

**Comment by chinanoahli** [comment]
> 是不是tcp那里填翻墙用的v2服务器，然后udp那里填游戏ss服务器 然后开启游戏模式？

不是，是看看你的v2服务器的http端口（是指你电脑/浏览器连上这个端口可以翻墙的那个端口，不是你服务器的端口）是什么。

然后ps4上设置网络的时候，打开代理设置，如果v2跑在路由器上，ip就填路由器的ip，端口就填http端口，就可以了。

ssr同理，你要找到你ssr客户端监听的http端口，ps4只支持http方式的代理，不能用socks5。

**Comment by chinanoahli** [comment]
游戏不游戏模式是那种专门做游戏加速的vpn才有吧，自建的服务器没这说法，也不推荐用自建来玩游戏，毕竟延时和速度都没保障。

**Comment by chinanoahli** [comment]
> 游戏不游戏模式是那种专门做游戏加速的vpn才有吧，自建的服务器没这说法，也不推荐用自建来玩游戏，毕竟延时和速度都没保障。

另外ps4的无线网卡挺弱的，追求稳定请用有线。
