### ISSUE TITLE
请教一下一种配置方式

### ISSUE THREAD

**Issue by bleeee** [v2ray/discussion#534]
我的网络环境是：路由器pppoe拨号，下面有群晖和电脑，因为路由器运行v2ray性能不够，所以想在群晖上跑一个docker，然后通过路由器梅林固件中的“科学上网”插件中的v2ray转发到群晖，想请教在路由器和群晖之间的两个v2ray转发只有socks5方式么？
1、路由器可以通过iptables把流量转发到运行任意门的群晖上么？
2、因为担心socks5还是给路由器的负载太大了,如果群晖运行任意门，那么路由器上的v2ray客户端可以运行freedom协议或者其他协议把流量转发过去么?

**Comment by kslr** [comment]
你能再详细描述一下需求吗？

bleeee <notifications@github.com> 於 2020年2月10日週一 下午7:28寫道：

**Comment by bleeee** [comment]
> 你能再详细描述一下需求吗？ bleeee <notifications@github.com> 於 2020年2月10日週一 下午7:28寫道：
> […](#)

谢谢回复！
路由器的ip 192.168.0.1 安装了梅林科学上网插件
Nas的ip 192.168.0.2 安装了v2ray
还有同一网段的其他设备
目前是通过路由器的科学上网插件进行v2ray上网，但是性能只有120Mbps左右，而线路最高速度在600Mbps左右，所以想让Nas来处理这个任务，就是通过路由器的插件的分流功能，把需要科学上网的未加密流量转送到nas进行加解密处理然后发送接受。就是把国内外流量区分的功能放在路由器上，而运算量大的任务交给nas处理。因为nas不适宜经常动，所以没把nas作为入户的第一设备。
已经初步测试实现的一个是在Nas上运行的v2ray入端为socks5，出端为vmess直接连接服务器，而在路由器上运行入端为默认的任意门，出端为socks5连接nas入端。
我是想请教下有没有其他协议比socks5让路由器负载更低？比如nas入端为任意门，路由器出端为freedom协议redirect到nas任意门，或者抛开路由器科学上网插件，iptables可以直接转发流量到nas的任意门端口？
非常感谢！

**Comment by bleeee** [comment]
> 你能再详细描述一下需求吗？ bleeee <notifications@github.com> 於 2020年2月10日週一 下午7:28寫道：
> […](#)

其实就是相当于在路由器和外网服务器之间又插了个nas，路由器和nas通信想用负载最低的协议，而耗算力的vmess通信放在nas和外网服务器之间

**Comment by kslr** [comment]
Iptables可以，但我觉得为了这个真的没必要，麻烦又提升不了多少。你为什么不全部迁移到nas上 是因为透明代理？

**Comment by bleeee** [comment]
> Iptables可以，但我觉得为了这个真的没必要，麻烦又提升不了多少。你为什么不全部迁移到nas上 是因为透明代理？

Nas上有大量数据和做种，我想尽量避免重启校验，平时由于折腾网络，路由器重启的不少

**Comment by bleeee** [comment]
> Iptables可以，但我觉得为了这个真的没必要，麻烦又提升不了多少。你为什么不全部迁移到nas上 是因为透明代理？

请教下Freedom的出端可以连接任意门的入端么，或者两个v2ray连接有比socks5负载更低的连接当时么？
您说的iptables实现有相关文章么，我昨天试了一天都没成功，不知道是v2ray透明代理任意门入端设置有问题还是别的什么原因

**Comment by bleeee** [comment]
> Iptables可以，但我觉得为了这个真的没必要，麻烦又提升不了多少。你为什么不全部迁移到nas上 是因为透明代理？

我是直接在nat的prerouting 做了两个dnat，把有需求机器的包转到nas的任意门端口，然后吧nas任意门端端口的返回转发给有需求的机器，任意门选用folowredirect 和tproxy，对redirect和tproxy代理不太懂，不知道问题出在哪

**Comment by kslr** [comment]
那你可以试试任意门

**Comment by bleeee** [comment]
> 那你可以试试任意门

任意门跟freedom搭配还是跟iptables搭配呢

**Comment by kslr** [comment]
取决于你想怎么转发流量，具体的性能我也不清楚 你可以尝试做一些测试

**Comment by bleeee** [comment]
> 取决于你想怎么转发流量，具体的性能我也不清楚 你可以尝试做一些测试

我明天把freedom和任意门连接的配置发上来，麻烦您再看下哪出了问题，谢谢！

**Comment by forever8938** [comment]
直接把网关指向192.168.0.2就行了，路由器不用开v2ray

**Comment by bleeee** [comment]
> 直接把网关指向192.168.0.2就行了，路由器不用开v2ray

还想用路由器的分流能力，感觉插件的分流还是挺方便的

**Comment by bleeee** [comment]
> 取决于你想怎么转发流量，具体的性能我也不清楚 你可以尝试做一些测试

路由器上的配置：
{

  "inbounds": [
  {
    "listen": "0.0.0.0",
    "port": 3333,
    "protocol": "dokodemo-door",
    "settings": {
      "network": "tcp,udp",
      "followRedirect": true
    }
  }],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {
{
  "domainStrategy": "AsIs",
  "redirect": "192.168.0.2:12345",
  "userLevel": 0
}
    }
  }]
}
nas上的配置：
{
  "inbounds": [
  {
    "listen": "0.0.0.0",
    "port": 12345,
    "protocol": "dokodemo-door",
    "settings": {
      "network": "tcp,udp",
      "followRedirect": true
    }
  }],
  "outbounds": [...]
}
这个配置有什么问题么，测试下来是不行的

**Comment by bleeee** [comment]
> 取决于你想怎么转发流量，具体的性能我也不清楚 你可以尝试做一些测试

另外今天测试了vmess的不加密模式，从路由器转发到nas性能也不错

**Comment by jackjapan** [comment]
@bleeee 我也有类似的想法，但是需求比你的简单，目前路由器上安装了梅林科学上网，可以正常使用，但是跑不满，我想通过在群晖上的docker装v2ray来处理，请教一下如何实现这个想法，谢谢。
