### ISSUE TITLE
v2ray/dist为什么断更了

### ISSUE THREAD

**Issue by mzz2017** [v2ray/discussion#535]
相关 <https://github.com/mzz2017/V2RayA/issues/36>

**Comment by mzz2017** [comment]
将release放到repository中可以很好利用jsdelivr的cdn，解决目前v2ray不翻墙就很难安装的问题。

如果是维护不便而断更的话，我认为用CI工具自动release到这个仓库是比较完美的做法。

**Comment by mzz2017** [comment]
@DarienRaymond @VictoriaRaymond @kslr

**Comment by kslr** [comment]
这个仓库我都忘记了，没想到真的有人在用。

可以用githun actions简单修一下

**Comment by mzz2017** [comment]
> 这个仓库我都忘记了，没想到真的有人在用。
> 
> 可以用githun actions简单修一下

这项工作有人做吗，目前github封锁严重，一些地区无法正常安装v2ray

**Comment by kslr** [comment]
一般来说，我会将其加入公开Todo列表，等待有缘人或者有时间的时候。

**Comment by mzz2017** [comment]
`release/release-ci.sh`中的代码五脏俱全，可以看出之前是使用traivis-ci的。

随源找到<https://travis-ci.org/v2ray/v2ray-core/branches>，显示travis在一年前停用。

在相关commit可以发现，在转到azure-pipelines时漏掉了关于v2ray/dist的代码。

**Comment by kslr** [comment]
现在有一个问题，ray core的自动发布已经停用了，fly还有一个测试编译版本，那个并不合适。所以需要单独跑一个程序检查ray core是否有新的同步并更新到ray dist

比如说加一个actions 定时检查ray core是否有新的发布，然后下载到本地，这个工作就可以单独加到dist仓库里面

**Comment by mzz2017** [comment]
> 现在有一个问题，ray core的自动发布已经停用了，fly还有一个测试编译版本，那个并不合适。所以需要单独跑一个程序检查ray core是否有新的同步并更新到ray dist
> 
> 比如说加一个actions 定时检查ray core是否有新的发布，然后下载到本地，这个工作就可以单独加到dist仓库里面

轮询太不优雅了，我认为在v2ray-core加一个github actions监视release事件下载并推到dist仓库是可行的

**Comment by kslr** [comment]
目前ray core的发布是人工控制的，我不确定是否能触发

**Comment by mzz2017** [comment]
如果内容在draft里，添加附件再真正发布的话，应该是没问题的

**Comment by kslr** [comment]
严格来说并不是轮询，而是定时检查（天/周/月）
另外我刚刚给你tuta.io的邮箱发了一封邮件
