### ISSUE TITLE
ws+tls+cdn的配置速度慢真的没办法了吗

### ISSUE THREAD

**Issue by Etern213** [v2ray/discussion#537]
最近mkcp模式墙的厉害，只能换了个ws加cdn的配置，速度真的太感人了，试过bbr和锐速，不管怎么样，都是速度奇慢无比，打开个google都要加载个15-20秒。

线路可能稍差些，vultr的美国机房。基本之前用你mkcp看个油管twitch什么的没问题，现在连google都太慢了。

是只能换线路了吗？

**Comment by kslr** [comment]
不开CDN or 加钱

**Comment by forever8938** [comment]
现在cloudflare的节点全天丢包率都在20以上，速度肯定很慢。其实除了cn2 gia之外，受干扰程度都差不多，这是人为设定的。

**Comment by du5** [comment]
百度CDN

**Comment by weifong208** [comment]
套上nginx，开tls1.3会好很多

**Comment by forever8938** [comment]
7*24小时都是这个速度

<img width="487" alt="Screen Shot 2020-02-18 at 22 55 56" src="https://user-images.githubusercontent.com/44494377/74747593-278db780-52a2-11ea-8957-687cce103929.png">

**Comment by du5** [comment]
> 7*24小时都是这个速度
> 
> <img alt="Screen Shot 2020-02-18 at 22 55 56" width="487" src="https://user-images.githubusercontent.com/44494377/74747593-278db780-52a2-11ea-8957-687cce103929.png">

su.baidu.com

**Comment by Etern213** [comment]
> > 7*24小时都是这个速度
> > <img alt="Screen Shot 2020-02-18 at 22 55 56" width="487" src="https://user-images.githubusercontent.com/44494377/74747593-278db780-52a2-11ea-8957-687cce103929.png">
> 
> https://su.baidu.com

这个百度的加速是和cloudfare一个性质吗？

**Comment by forever8938** [comment]
@Etern213 这个肯定要备案+实名

**Comment by du5** [comment]
> 这个百度的加速是和cloudfare一个性质吗？

CF国内合作商，需要备案域名，可不实名

**Comment by forever8938** [comment]
电信已经彻底封锁cloudflare的免费CDN网段

**Comment by con-a** [comment]
我电信时不时封cloudflare的IP段，不封的时候还挺快

**Comment by CalmLong** [comment]
我这边用 VMess+TLS，速度比祖传三件套快，用了一整年了，没问题。搬瓦工DC9

**Comment by kslr** [comment]
电信没有GIA也要弄个CN2，加钱世界可及
移动直接换宽带更加便宜一点
然后就不用开CDN了

**Comment by sjlleo** [comment]
**再加个移动的NAT就好了**（确保NAT的移动路由是走广州出口的，一定要找anyCast到香港的IP）
下图是之前截图的高峰晚上电信走移动NAT套CloudFlare的速度，看4K也是毫无压力。
![image](https://user-images.githubusercontent.com/13616352/77839020-be0b9d80-71ab-11ea-878d-e9cc2856ba14.png)
![image](https://user-images.githubusercontent.com/13616352/77839151-daf4a080-71ac-11ea-98c7-4e2324ae1604.png)

**Comment by PeterWang-dev** [comment]
> 
> 
> **再加个移动的NAT就好了**（确保NAT的移动路由是走广州出口的，一定要找anyCast到香港的IP）
> 下图是之前截图的高峰晚上电信走移动NAT套CloudFlare的速度，看4K也是毫无压力。
> ![image](https://user-images.githubusercontent.com/13616352/77839020-be0b9d80-71ab-11ea-878d-e9cc2856ba14.png)
> ![image](https://user-images.githubusercontent.com/13616352/77839151-daf4a080-71ac-11ea-98c7-4e2324ae1604.png)

有详细教程吗

**Comment by huchanghui123** [comment]
试试Cloudflare反代理
https://github.com/siemenstutorials/better-cloudflare-ip
