### ISSUE TITLE
怎么让V2RAY像pac模式一样代理软件、游戏

### ISSUE THREAD

**Issue by x1483177351** [v2ray/discussion#539]
全局会代理电脑所有流量，想让它和PAC一样仅代理被墙的所有。
设置过路由，不过开启全局路由根本不生效，无论是（网址，网址）还是（domain:网址，domain:网址）一律不生效。预定义规则使用的也是跳过局域和大陆.
点了下一键设置默认自定义路由规则，直连里面包含的也是一律不生效，走代理

**Comment by forever8938** [comment]
你要找客户端的作者

**Comment by okudayukiko** [comment]
用Proxifier

**Comment by DolorHunter** [comment]
https://www.v2ray.com/chapter_02/03_routing.html

**Comment by okudayukiko** [comment]
用Mellow，go-tun2socks或OpenVPN over SOCKS。

**Comment by okudayukiko** [comment]
经测试以下OpenVPN配置可以OpenVPN over Socks：
server.ovpn：
push "redirect-gateway def1 bypass-dhcp"
push "redirect-gateway ipv6 def1 bypass-dhcp"
<ca>
</ca>
<cert>
</cert>
…
client.ovpn：
route 0.0.0.0/0
route-ipv6 ::/0
route "V2Ray服务器IP" 255.255.255.255 met_gateway
route "DNS服务器IP" 255.255.255.255 net_gateway
socks-proxy localhost 1080
