### ISSUE TITLE
请问v2ray在client 2 server(vps)是使用udp(kcp)还是tcp协议呢？

### ISSUE THREAD

**Issue by yakiler** [v2ray/discussion#54]
作者您好<br/>
       非常感谢这个软件的诞生，对于该软件的运行我有一些不太明白的地方（很抱歉的是网络协议一块不太毕业）。我看到v2ray的流程图是 一个配置了socks的请求 被 v2rayClient 捕获，然后v2rayClient 通过vmess 协议 向v2rayServer通信（vps的v2ray服务），v2rayServer 接收vmess请求在通过一系列的解包 发送一个tcp请求处理真正来自client的业务请求，获取到结果后由v2rayServer负责响应请求（或者说重新向v2rayClient发送数据）。
<br/>
        我的问题是vmess协议采用的是udp协议完成消息请求的吗？如果不是有办法使用udp完成消息请求吗？          <br/>
                                                                                                      忠实的用户，一个刚刚接触v2ray的小白

**Comment by winds365** [comment]
"inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1"
    }
  }
https://www.v2ray.com/chapter_02/protocols/socks.html

**Comment by Cwek** [comment]
vmess默认的底层传输协议是TCP，但是可以改变传输底层。包括改tls、mkcp（用UDP负载）等。

如果理解协议分层的话，就比较好理解每层的差异。

**Comment by yakiler** [comment]
@winds365  @Cwek  非常感谢两位，我明白了。看来有时间需要再看看vmess的手册了
