### ISSUE TITLE
请问能不能在服务端模拟客户端的ip？

### ISSUE THREAD

**Issue by romezxy** [v2ray/discussion#541]
本人新入门的小白，主要用v2ray搭梯子翻墙用，由于梯子出口在俄罗斯，google经常给我推送俄语的新闻，烦不胜烦。
    我想，v2ray能不能把客户端的ip也复制到服务端，让google之类的网站能识别出我是中国大陆的用户，推送简体中文的新闻。
    我是按照官网教程，websocket+tls+nginx，请问各位作者，能不能实现我想要的功能，如果可以应该怎样写config文件。
    谢谢！

**Comment by kslr** [comment]
你可以在google设置语言为中文

**Comment by romezxy** [comment]
不仅仅是google，还有其它网站，不能让整个互联网为我改变啊。
