### ISSUE TITLE
请问socks5中转怎么写?

### ISSUE THREAD

**Issue by linsan970809** [v2ray/discussion#542]
经过群友的帮助,我解决了这个需求,就是修改一下outbound

>    "outbound": {
        "protocol": "socks",
        "settings": {
			"servers": [{
				"address": "8.8.8.8",//ip换成代理服务器的就行
				"port": 1080
			}]
		}
    },

C(我电脑)->B(V2RAY服务器)->C(外网服务器)
由于某些原因我的电脑不能直接访问C,而C只能提供一个SOCKS5的代理端口出来,我想在B装一个V2RAY然后用C的SOCK5来访问油管,配置文件应该怎么写?谢谢

下面是我自己研究的配置,但是没有成功通过,如果把代理去掉,SS是成功的.我在B服务器的配置文件

> {
    "log": {
        "loglevel": "warning"
    },
    "inbound": {
        "protocol": "shadowsocks",
        "port": 10088,
        "settings": {
            "method": "chacha20",
            "password": "ABC123",
            "level": 1
        }
    },
    "outbound": {
        "protocol": "socks",
        "settings": {
			"servers": [{
				"address": "8.8.8.8",
				"port": 1080,
				"users": [{
					}]
			}]
}
    },
    "inboundDetour": [],
    "outboundDetour": [
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "blocked"
        }
    ],
    "routing": {
        "strategy": "rules",
        "settings": {
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag": "blocked"
                }
            ]
        }
    }
}

**Comment by doufuvpn** [comment]
大佬，成功了吗。我最近想中转socks

**Comment by doufuvpn** [comment]
大佬成功了吗，我也需要中转socks

**Comment by linsan970809** [comment]
> 大佬成功了，我也需要中转袜子
我上传了个我的配置文件,我想你能看懂,这个是我正常运行的
[v2ray_s_to_ss.zip](https://github.com/v2ray/discussion/files/9227769/v2ray_s_to_ss.zip)

**Comment by doufuvpn** [comment]
大佬，我是小白，您是直接安装的v2ray，然后直接修改config.json 文件吗？还需要修改
我用了xui面板，xui目前没有看到 config文件。也装了 xrayr 有入站和出站的两个.json 文件 。
我的socks 5 有帐号密码，格式要怎么写么users: 
                                                                   password:

**Comment by linsan970809** [comment]
> 大佬，我是小白，您是直接安装的v2ray，然后直接修改config.json 文件吗？还需要修改 我用了xui面板，xui目前没有看到 config文件。也装了 xrayr 有入站和出站的两个.json 文件 。 我的socks 5 有帐号密码，格式要怎么写么users: password:

我是手动配置的,就是下载V2RAY官方文件ZIP然后改JSON文件,你这个XUI我没用过无法给你帮助,我这个是socks 5转SS,socks 5 有账号密码我也没研究过,这个我也无法给你提供帮助

**Comment by doufuvpn** [comment]
> > 大佬，我是小白，您是直接安装的v2ray，然后直接修改config.json 文件吗？还需要修改 我用了xui面板，xui目前没有看到 config文件。也装了 xrayr 有入站和出站的两个.json 文件 。 我的socks 5 有帐号密码，格式要怎么写么users: password:
> 
> 我是手动配置的,就是下载V2RAY官方文件ZIP然后改JSON文件,你这个XUI我没用过无法给你帮助,我这个是socks 5转SS,socks 5 有账号密码我也没研究过,这个我也无法给你提供帮助

好的大佬，我自己试试，感谢...十分感谢
