### ISSUE TITLE
Why this configuration tags every requests with "direct"?

### ISSUE THREAD

**Issue by davidshen84** [v2ray/discussion#544]
- I run my v2ray from the v2ray official docker image.
- I used the default `config.json` file from my service provider.
- After I started the docker image, I can use the service to browse the Internet.

What confuses me is that it seems all requests are tag **direct**. I think the service did not send my requests to the proxy server.

I just started using v2ray, and may not understand the log correctly.

```
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64)
A unified platform for anti-censorship.
2020/02/15 06:33:53 [Warning] v2ray.com/core: V2Ray 4.22.1 started
2020/02/15 06:33:54 tcp:172.17.0.1:50116 accepted tcp:clients2.google.com:443 [direct] 
2020/02/15 06:33:55 tcp:172.17.0.1:50122 accepted tcp:ssl.gstatic.com:443 [direct] 
2020/02/15 06:33:56 tcp:172.17.0.1:50128 accepted tcp:mtalk.google.com:5228 [direct] 
2020/02/15 06:33:57 tcp:172.17.0.1:50134 accepted tcp:clients4.google.com:443 [direct] 
2020/02/15 06:33:59 tcp:172.17.0.1:50148 accepted tcp:ssl.gstatic.com:443 [direct] 
2020/02/15 06:33:59 tcp:172.17.0.1:50154 accepted tcp:portal.shadowsocks.nl:443 [direct] 
```

```json
{
    "log": {
	"loglevel": "warning"
    },
    "inbounds": [
	{
	    "listen": "0.0.0.0",
	    "port": 1080,
	    "protocol": "socks",
	    "settings": {
		"auth": "noauth",
		"udp": true,
		"ip": "0.0.0.0"
	    }
	},
	{
	    "listen": "0.0.0.0",
	    "port": 1090,
	    "protocol": "http",
	    "settings": {
		"auth": "noauth",
		"udp": true,
		"ip": "0.0.0.0"
	    }
	}
    ],
    "outbounds": [
	{
	    "protocol": "vmess",
	    "settings": {
		"vnext": [
		    {
			"address": "server.ip",
			"port": 443,
			"users": [
			    {
				// hide
			    }
			]
		    }
		]
	    }
	}
    ],
    "outboundDetour": [
	{
	    "protocol": "freedom",
	    "settings": null,
	    "tag": "direct"
	}
    ],
    "routing": {
	"strategy": "rules",
	"settings": {
	    "rules": [
		{
		    "type": "chinasites",
		    "outboundTag": "direct"
		},
		{
		    "type": "field",
		    "ip": [
			"geoip:private"
		    ],
		    "outboundTag": "direct"
		},
		{
		    "type": "chinaip",
		    "outboundTag": "direct"
		}
	    ]
	}
    }
}
```

**Comment by kingwilliam** [comment]
>     ...
>     "routing": {
> 	"strategy": "rules",
> 	"settings": {
>      ...
> ```

https://www.v2ray.com/en/configuration/routing.html
domainStrategy: "AsIs" | "IPIfNonMatch" | "IPOnDemand"

please try to modify "strategy": "rules" or delete this statement

**Comment by davidshen84** [comment]
Wait...is it **strategy** or **domainStrategy**? Is there's a miss-spell or the key name changed recently?

**Comment by davidshen84** [comment]
I think the problem is the *outboundDetour* object.

```json
    "outboundDetour": [
	{
	    "protocol": "freedom",
	    "settings": null,
	    "tag": "direct"
	}
    ],
```

It is not mentioned in **https://www.v2ray.com/en/configuration/overview.html#inboundobject** document. However, google search did show many results about how to configure a *xxDetour* object. Most interestingly, my v2ray client, *V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64)*, accepts and is affected by this configuration object.

Is the *xDetour* object deprecated?
