### ISSUE TITLE
Sniffing destoverride的作用是什么

### ISSUE THREAD

**Issue by bleeee** [v2ray/discussion#547]

**Comment by iochen** [comment]
https://www.v2ray.com/chapter_02/01_overview.html#sniffingobject

**Comment by dawncold** [comment]
其实更想知道这意味着什么而不是文档中简单描述的那样，我不看源码猜不出来作用是什么。

在这个函数中：https://github.com/v2ray/v2ray-core/blob/master/app/dispatcher/default.go#L208

如果嗅探出了流量是哪种（http、tls、bt），就会标记一下协议，如果还配置了`destOverride`并且与嗅探出的协议匹配的话，就会把outbound target的address设置成域名或者IP。

举个例子，流量过来如果没有嗅探域名，那只能根据IP地址决定走哪个outbound，但如果嗅探出了域名，那么可以做更进一步的路由选择了。

以上结论没有全看完代码，没有实验。

**Comment by KSroido** [comment]
可以去参考v2fly的白话文, v2ray内部核心成员一般都谱大 不愿意过多解释@dawncold
