### ISSUE TITLE
【问题】带认证的 http 代理无法使用 git clone？

### ISSUE THREAD

**Issue by cugxuan** [v2ray/discussion#550]
# 问题描述
我想在客户端配置带认证的 http，原本不带认证的 http 可以在 export 之后 git clone

终端先 `export ALL_PROXY=http://127.0.0.1:1087` ，然后`git clone xxx`

但是在客户端配置了 http 代理的账号密码之后就显示 `Proxy CONNECT aborted`，如下图，使用的方式是 `export ALL_PROXY=http://xx:xx@127.0.0.1:1087;`
![image](https://user-images.githubusercontent.com/23120372/74738914-c7434980-5292-11ea-9077-8f900e0a6d18.png)

**但是我在 telegram 和 Chrome 的插件 SwitchyOmega 中配置带认证的 http 代理却运行正常，不知道从什么地方找问题了，求大神指点！**

这是我客户端的配置
```
{
  "log":{},
  "dns":{},
  "stats":{},
  "inbounds":[
    {
      "port":"1087",
      "protocol":"http",
      "settings":{
        "accounts": [
		    {
		      "user": "",
		      "pass": ""
		    }
	    ],
        "allowTransparent": false,
        "userLevel": 0
      },
      "tag":"in-0"
    }
  ],
  "outbounds":[
    {
      "protocol":"vmess",
      "settings":{
        "vnext":[
          {
            //"address":"",
            //"port":,
            "users":[
              {
               // "id":"",
                "alterId":64
              }
            ]
          }
        ]
      },
      "tag":"out-0",
      "streamSettings":{
        "network":"tcp",
        "security":"none",
        "tcpSettings":{}
      }
    },
    {
      "tag":"direct",
      "protocol":"freedom",
      "settings":{}
    },
    {
      "tag":"blocked",
      "protocol":"blackhole",
      "settings":{}
    }
  ],
  "routing":{
    "domainStrategy":"IPOnDemand",
    "rules":[
      {
        "type":"field",
        "ip":[
          "geoip:private"
        ],
        "outboundTag":"direct"
      }
    ]
  },
  "policy":{},
  "reverse":{},
  "transport":{}
}
```

**Comment by kslr** [comment]
Expoer 时也要加账户啊

**Comment by cugxuan** [comment]
> Export 时也要加账户啊

您好，加了的。下面的 user 和 pass 和设置里面对应，图中我打码了，但是看得见@符号
`export ALL_PROXY=http://user:pass@127.0.0.1:1087;`

**Comment by forever8938** [comment]
ALL_PROXY一般都是用于socks5代理，http代理请用HTTP_PROXY

**Comment by cugxuan** [comment]
> ALL_PROXY一般都是用于socks5代理，http代理请用HTTP_PROXY

谢谢您的建议，我之前两种都试过了、具体情况如图，只有 `git clone` 出现问题，wget 和 curl ，软件直接写账号密码认证都没有问题

![image](https://user-images.githubusercontent.com/23120372/74995375-ac87f500-548b-11ea-9f24-8b342b007877.png)

**Comment by cugxuan** [comment]
我最近试了一下突然又好了。不知道是啥问题、就此 Close
