### ISSUE TITLE
建议增强Socks代理的通用性

### ISSUE THREAD

**Issue by StrollStars** [v2ray/discussion#552]
发现默认的Socks代理浏览网页没问题，但是直接用来代理Tor和Telegram会失败，通过搜索发现针对Tor需要取消勾选“开启流量探测”，针对Telegram需要HTTP代理中使用全局模式。
希望能够内置对这两个程序进行特别处理，既减少切换频率，也提高兼容性和可靠性。

**Comment by DolorHunter** [comment]
新版本下使用 tor 似乎不需要关闭 sniffing.
telegram 也支持 socks 代理, 配置一次后即可(跟浏览器代理的设置差不多).

**Comment by StrollStars** [comment]
@DolorHunter 感谢提醒，Telegram问题已解决，但是Tor还有点问题，停留在85%，报如下错误：
Weighted bandwidth is 0.000000 in node selection for rule weight as middle node
No available nodes when trying to choose node. Failing.
Failed to find node for hop 0 of our path. Discarding this circuit.
关闭sniffing就正常，用的是[AdvOR-0.3.1.3](https://sourceforge.net/projects/advtor/files/AdvOR-0.3.1.3/AdvOR-0.3.1.3.zip/download)。

**Comment by DolorHunter** [comment]
关于 sniffing 的部分是在 [白话 - Vmess协议下的更新历史看到的](https://toutyrater.github.io/basic/vmess.html)
> 2019-10-27 sniffing 不再影响 tor 的使用

但是, 看了下这个日期之后的反应似乎还是有很多人提关于这个的issue, 解决方案公认也是关闭 sniffing.
e.g. https://github.com/2dust/v2rayN/issues/360 https://github.com/v2ray/discussion/issues/49

我自己简单测试了一下用sniffing + obfs4 可用, sniffing + meek_azure 不可用. 你试试换个网桥, 实在不行就关闭 sniffing. 我并没有使用 tor 的习惯, 因此没法给出很好的建议.

希望能帮到你.

**Comment by StrollStars** [comment]
@DolorHunter 再次感谢你的帮助，我先取消勾选用着吧。

**Comment by StrollStars** [comment]
@DolorHunter 再次感谢你的帮助，我先取消勾选用着吧。
