### ISSUE TITLE
V2Ray 被動連接指紋检测

### ISSUE THREAD

**Issue by Mr-Sheep** [v2ray/discussion#554]
使用V2Ray进行whatleaks.com的测试时发现连接类型能够被识别：
Connection type : IPIP or SIT
是因为我使用的配置问题还是此问题和V2Ray无关
配置：WSS

**Comment by mzz2017** [comment]
![image](https://user-images.githubusercontent.com/30586220/75901649-d07b0b80-5e79-11ea-8100-7eea4da18d37.png)

WSS

**Comment by Mr-Sheep** [comment]
我也是WSS啊(Caddy)
可能有參數不對吧
