### ISSUE TITLE
使留空的规则合法.

### ISSUE THREAD

**Issue by RealXuChe** [v2ray/discussion#555]
在目前版本的v2ray中,如果一个规则不能匹配到任何流量(比如说直接留空),则v2ray会报错并退出.

> main: failed to create server > v2ray.com/core/app/router: this rule has no effective fields

我希望v2ray能够在遇到此类情况时只报警告,不强制退出.毕竟我不觉得这种情况算作"无法恢复的错误".

**Comment by kslr** [comment]
那数据不就丢失了

**Comment by RealXuChe** [comment]
> 
> 
> 那数据不就丢失了

?
什么意思?不能匹配任何流量的规则会被直接跳过啊
我的意思是使形如
```json
{
  "type": "field",
  "outboundTag": "direct"
}
```
的RuleObject合法.

**Comment by CalmLong** [comment]
这种你可以加上一句 `"network": "tcp,udp"` 就可以达到效果

**Comment by RealXuChe** [comment]
> 
> 
> 这种你可以加上一句 `"network": "tcp,udp"` 就可以达到效果

不好意思,这不是会匹配所有流量吗?我是想获得一个不匹配任何流量的规则........

**Comment by CalmLong** [comment]
没搞懂你什么意思，你要是想转发流量可以用Freedom中的redirect，阻止流量可以用Blackhole

不匹配任何流量的规则是该怎么理解?

**Comment by RealXuChe** [comment]
> 
> 
> 没搞懂你什么意思，你要是想转发流量可以用Freedom中的redirect，阻止流量可以用Blackhole
> 
> 不匹配任何流量的规则是该怎么理解?

你说得对,确实如此.

但是,虽说如此,我觉得我们没有什么必要使这种规则非法.

我认为尽管这种规则可能是没有意义的,但不代表它应该是非法的.
完全可以改成在遇到这种规则时报警告而不是panic,因为这种规则并不会导致v2ray无法继续运行.
