### ISSUE TITLE
关于移动网络耗电

### ISSUE THREAD

**Issue by mr-myq** [v2ray/discussion#556]
很感谢开发者能提供如此优秀的平台供我们使用，我是一个小白用户，之前使用SS和SSR，今年转用V2ray，这段时间里有一些困惑还望解答。
在使用过程中，我发现在无线网络环境下，使用正常，体验很好。在移动网络下，可以通过v2ray登录外网，速度也比较快，但是v2ray耗电会很高，而且Google play服务的耗电也很高，手机使用时间只能达到日常使用的三分之二，这个现象之前使用SS和SSR也没有，我是习惯于24小时挂梯子的，所以很想知道是什么原因。
我的设置是vmess+tls，打开分应用代理，设置绕过局域网及大陆，IFNOMATCH。
还望大神有时间能为我这个小白解惑！十分感谢！

**Comment by okudayukiko** [comment]
用Chacha20-Poly1305比较省电。

**Comment by mr-myq** [comment]
> 用Chacha20-Poly1305 Security比较省电。

我用的就是chacha20。

**Comment by DolorHunter** [comment]
有 tls 没必要用加密, 可以关掉减少运算量.

**Comment by mr-myq** [comment]
> 有 tls 没必要用加密, 可以关掉减少运算量.

如何解释无线网络下基本不费电，移动网络下很耗电，相同的设置，很大的差异。很想要能够从根本上解决问题的办法。

**Comment by DolorHunter** [comment]
使用 wifi 比蜂窝数据更省电. 与是否使用代理无关.

**Comment by mr-myq** [comment]
> 使用 wifi 比蜂窝数据更省电. 与是否使用代理无关.

恩，这点我知道。可是同样在蜂窝数据环境下，使用ss则没有这种情况，手机可以使用一天无压力；最近换成v2ray后，其他条件不变，手机使用半天就抗不住了。查询耗电，v2rayNG和Google play服务占比很高。

**Comment by DolorHunter** [comment]
v2ray 的 vmess 协议比 ss/ssr 的 shadowsocks 协议复杂, 需要进行更多的运算, 所以比 ss 耗电. 

具体关于 v2rayNG 软件的问题咨询 https://github.com/2dust/v2rayNG 更好一些.

**Comment by okudayukiko** [comment]
> v2ray 的 vmess 协议比 ss/ssr 的 shadowsocks 协议复杂, 需要进行更多的运算, 所以比 ss 耗电.
> 
> 具体关于 v2rayNG 软件的问题咨询 https://github.com/2dust/v2rayNG 更好一些.

VMess+TLS情况下可以用Chacha20-Poly1305。VMess+KCP情况下，用Chacha20-Poly1305直接被封IP，用AES-128-GCM看运气。

**Comment by okudayukiko** [comment]
降低AlterId也可以省电。

**Comment by okudayukiko** [comment]
V2Ray、Shadowsocks和WireGuard都试过了，只要是VPN App都耗电。
省电可以试试不代理中国大陆网站。
用x86路由作为V2Ray客户端最省电，速度也快，毕竟V2Ray的解密吃CPU。
用中国VPS做中转似乎能加快速度+省电？

**Comment by okudayukiko** [comment]
只要是VPN App都耗电。
省电可以试试不代理中国大陆网站。
用x86路由作为V2Ray客户端最省电，速度也快，毕竟V2Ray的解密吃CPU。
用中国VPS做中转似乎能加快速度+省电。

**Comment by okudayukiko** [comment]
只要是VPN App都耗电。
省电可以试试不代理中国大陆网站。
用x86路由作为V2Ray客户端最省电，速度也快，毕竟V2Ray的解密吃CPU。

**Comment by okudayukiko** [comment]
只要是VPN App都耗电。
省电可以试试不代理中国大陆网站。
用x86路由作为V2Ray客户端最省电，速度也快，毕竟V2Ray解密吃CPU。inbound为SOCKS协议（listen:0.0.0.0，udp:true），outbound为VMess协议。

**Comment by okudayukiko** [comment]
试试打开手机的省电功能。

**Comment by okudayukiko** [comment]
用软路由做V2客户端最省电、性能最好。
在软路由跑V2Ray客户端，inbound是SOCKS5协议 192.168.x.x:1080（不要直接用0.0.0.0），然后在手机V2Ray客户端新增一个192.168.x.x:1080的代理。

**Comment by okudayukiko** [comment]
用软路由做V2客户端最省电、性能最好。
在软路由跑V2Ray客户端，inbound是SOCKS协议 192.168.x.x:1080（不要直接用0.0.0.0），然后在手机V2Ray客户端新增一个192.168.x.x:1080的SOCKS代理。

**Comment by okudayukiko** [comment]
用软路由最省电、性能最好。
在软路由跑V2Ray客户端，inbound是SOCKS协议 192.168.x.x:1080（不要直接用0.0.0.0），然后在手机V2Ray客户端新增一个192.168.x.x:1080的SOCKS代理。
