### ISSUE TITLE
希望加入新功能：模拟直播流，使用Rtmp协议

### ISSUE THREAD

**Issue by kirin10000** [v2ray/discussion#557]
目前v2ray很强大，支持很多的底层传输协议，http2，ws，quic等等，能够模拟微信视频，https浏览网站的流量等等。目前完全无法识别的是https，它和浏览网站的流量一摸一样，但是还是存在一定问题，虽然没有证据证明你在科学上网，但是可以根据流量来猜测，一个人每天大量地访问一个没有什么实际内容的网站，每天都访问这么多流量，而且还是一台海外的服务器，而且只有你一个人访问，别人都不访问(这里指自己搭建梯子自己用的情况)，难免会怀疑。

但是如果能模拟直播，增加直播流协议rtmp，会不会好一点呢？我是这样想的，
第一种方案：
v2ray服务端将流量使用rtmp推流到服务器本地，然后客户端拉流，这样在gfw眼里看来，你在看直播，直播是由一台海外服务器提供的，谁在推流不知道。
第二种方案：
购买直播云服务，阿里云，腾讯云等都有，价格比cdn便宜，v2ray服务端将流量使用rtmp推流到直播云服务商，客户端拉流。这样在gfw看来(假设直播流服务商是国内的)，有一个海外服务器在对直播服务商推流。

我认为这个方案的可行性在于，直播流协议可以加密，比如rtmps，这样可以和https一样，gfw只能猜测你在科学上网，没有证据能证明你在科学上网，其次是rtmp协议貌似也是双向的，全双工，可实现客户端对服务器的通信。然后是对比https的优势，流量大显得没有那么奇怪，直播毕竟是视频，对带宽要求还挺高的。特别是第二种方案，服务端只是个推流的，再正常不过了，然后拉流端因为是在国内传输，gfw不管，就不知道有多少人在看直播，方案一只有你一个人看直播，还是有点奇怪的。
本人对直播流方面的知识了解有限，可能说出了一些非常滑稽的话，还请谅解

**Comment by okudayukiko** [comment]
单纯AES-128-GCM可能被识别。必须用TLS。

**Comment by DolorHunter** [comment]
我个人认为 gfw 并不会想那么多. 都是加密传输, 只是协议不一样. 不太可能看到某协议就直接放行. https://github.com/v2ray/discussion/issues/505

**Comment by forever8938** [comment]
连接主流VPS提供商的IP，就已经基本确定是翻墙了。

**Comment by vickunwu** [comment]
经过国内服务商时会有TLS解密吧

**Comment by garden4hu** [comment]
GFW 怀疑你就封掉你，不会出现拿到确切证据才出手的情况。V2的伪装不可能完备，更靠谱的是使用tls加密，使其看起来更普通
