### ISSUE TITLE
wv2ray.exe cpu内存占用过高导致运行异常网络不可用

### ISSUE THREAD

**Issue by 1265578519** [v2ray/discussion#558]
用作玩游戏的话wv2ray.exe有时候经常会突然占满一个CPU核心导致999延迟卡飞天，看日志没什么毛病
![3](https://user-images.githubusercontent.com/6442439/75066403-bbbb8100-5525-11ea-8cf1-56cf5b59bf49.png)
![2](https://user-images.githubusercontent.com/6442439/75066405-bcecae00-5525-11ea-8a1d-7f349506eb27.png)
![1](https://user-images.githubusercontent.com/6442439/75066406-bd854480-5525-11ea-941e-96fc20c4a258.png)
![QQ图片20200222035939](https://user-images.githubusercontent.com/6442439/75067353-c545e880-5527-11ea-946c-fb235f59aa69.png)

CPU占用的同时，内存也会越拉越高，达到七八百MB
初步判断是内存泄漏导致的一个CPU异常，这是vmmap快照
![444](https://user-images.githubusercontent.com/6442439/75066681-5025e380-5526-11ea-94e7-8d76337a1224.png)
快照下载
[wv2ray.zip](https://github.com/v2ray/v2ray-core/files/4237794/wv2ray.zip)
Windows10微软官方指定的内存调试：https://docs.microsoft.com/zh-cn/sysinternals/downloads/vmmap

**Comment by whatsappfree** [comment]
wv2ray.exe有病毒的怀疑

**Comment by yunfengwangluo** [comment]
我这里也遇到相同的问题  用于 pubg 游戏 连接 5分钟左右 cpu 占用14% 内存占用50MB  游戏延迟达到 2000+ms。  即使是局域网 server <--> client 延迟也会增加 150+ms

**Comment by 1265578519** [comment]
@yunfengwangluo 其实这个问题早两年前我提过一次，，到现在至今未解决

**Comment by 1265578519** [comment]
![1](https://user-images.githubusercontent.com/6442439/83436021-bf896880-a46f-11ea-973f-bba344ec1225.png)
这个问题没人关注的吗？

**Comment by 1265578519** [comment]
额，，，困扰我多年的问题解决了
如果要打游戏的话，那得设置ss的话，前几年我反映过NNNN次，v2ray客户端天天炸，999+延迟，cpu吃满单个核心，然后卡死在那但是就是不掉线那种，服务器和其他电脑使用不会有问题，很明显是客户端内存泄漏
设置方法很简单，可以同时支持，替换//include_ss
`                ,
        {
            "protocol": "shadowsocks",
            "port": 65535,
            "settings": {
                "method": "aes-128-gcm",
                "password": "www.itzmx.com",
                "network": "tcp,udp",
                "level": 1,
                "ota": false
            }
        }`
推荐使用aes-128-gcm，打游戏最快最稳的AEAD加密方式，包括google默认就是这个，256可以实现更高的加密复杂度。
chacha20-ietf-poly1305是google公司推出的AEAD加密方式，加密轻便更省电， 适合移动设备使用，电脑不推荐用这个。
三种AEAD加密方式
aes-128-gcm
aes-256-gcm
chacha20-ietf-poly1305
效果图！完美，没想到v2ray原生就支持ss，，，改个配置文件就能用了！
![image](https://user-images.githubusercontent.com/6442439/83440805-1bf08600-a478-11ea-8ac6-bc2114188ac5.png)

**Comment by 1265578519** [comment]
本想着，，，能解决，客户端是没毛病了，但是，，服务端，我去，炸了！
99%占用，然后延迟依旧999，，，看来得用第三方ss脚本才行。。。
![1](https://user-images.githubusercontent.com/6442439/83442156-4ba08d80-a47a-11ea-953c-208dcd5510a2.png)

**Comment by kslr** [comment]
试试netch 我平时用来打游戏

**Comment by 1265578519** [comment]
用的就是netch

**Comment by 1265578519** [comment]
![image](https://user-images.githubusercontent.com/6442439/83448465-96270780-a484-11ea-886c-0d26c3ffa148.png)
找了半天，，，终于找到个能用的ss，是libev版本的，玩了20分钟，CPU占用没有超过1.5%过，很稳。

**Comment by nicholascw** [comment]
有没有整个wireshark抓个自己的包什么的看看有没有在打环呢

**Comment by SekiBetu** [comment]
你对MUX太执着了，明明关闭MUX这些问题可以直接解决，就是不关
