### ISSUE TITLE
QUIC用不了

### ISSUE THREAD

**Issue by okudayukiko** [v2ray/discussion#559]
服务器配置：
{
	"protocol": "vmess",
	"tag": "server-udp",
	"mux": {
		"enabled": true
	},
	"port": ,
	"settings": {
		"clients": [
			{
				"id": "",
				"alterId": ,
				"security": "auto"
			}
		]
	},
	"streamSettings": {
		"network": "quic"
	},
	"detour": {
		"to": "detour"
	}
}	
{
	"protocol": "vmess",
	"mux": {
		"enabled": true
	},
	"port": "xxxx-xxxx",
	"tag": "detour",
	"streamSettings": {
		"network": "quic"
	},
	"allocate": {
		"strategy": "random",
		"concurrency": 20,
		"refresh": 5
	}
}
客户端错误日志：
2020/02/22 23:04:48 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [HandshakeTimeout: Crypto handshake did not complete in time.] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by okudayukiko** [comment]
另外V2Ray被avast报告为病毒。
![屏幕截图(84)](https://user-images.githubusercontent.com/17502357/75094715-e1e62d00-55c8-11ea-978d-51903232b508.png)

**Comment by iochen** [comment]
> 另外V2Ray被avast报告为病毒。
> ![屏幕截图(84)](https://user-images.githubusercontent.com/17502357/75094715-e1e62d00-55c8-11ea-978d-51903232b508.png)

You can review the code.
Try to update avast.
![image](https://user-images.githubusercontent.com/28243989/75094847-caf40a80-55c9-11ea-9141-d1762159ec49.png)(From Internet)

**Comment by okudayukiko** [comment]
> 
> 
> > 另外V2Ray被avast报告为病毒。
> > ![屏幕截图(84)](https://user-images.githubusercontent.com/17502357/75094715-e1e62d00-55c8-11ea-978d-51903232b508.png)
> 
> You can review the code.
> Try to update avast.
> ![image](https://user-images.githubusercontent.com/28243989/75094847-caf40a80-55c9-11ea-9141-d1762159ec49.png)(From Internet)

更新Avast也报告病毒

**Comment by okudayukiko** [comment]
尝试KCP+Chacha20-Poly1305直接封IP。

**Comment by iochen** [comment]
Please stop using mKCP
