### ISSUE TITLE
v2ray kcp导致封端口

### ISSUE THREAD

**Issue by l619534951** [v2ray/discussion#560]
**网络环境：**广东-深圳 移动宽带.
**采用配置：**vmess + kcp，端口8080.
### 
使用kcp以后，无法正常翻墙，重复尝试几次之后，端口被封，http://port.ping.pe显示在国外端口是通的. 以前曾经用过kcp，记得是正常的。
当时以为是服务没有启动，systemctl status v2ray查看是启动的，然后接收到了客户端的请求，貌似是无法解析还是什么，因为日志不在了，忘记了，客户端直接是could not read repsonse........。重试了四五次之后，端口就被封了。
### 
最后想说 ，谨慎使用kcp呀现在，tcp是正常的，都没有使用tls。

**Comment by iochen** [comment]
Please stop using mKCP.
