### ISSUE TITLE
多台服务器负载均衡下 GFW 封锁策略

### ISSUE THREAD

**Issue by DolorHunter** [v2ray/discussion#561]
场景：多台服务器共用同一域名（DNS多条解析），配合 NGINX 做二级负载均衡，且使用同一配置的V2ray 时，应该是可以按照 NGINX 负载加权的比例分散流量的。此时，客户端只要配置相当于一台服务器的规则，就可以由 DNS 和 NGINX 实现负载均衡。

问：如果此时惨遭 GFW 探测并封锁，将导致一台服务器被封还是所有服务器被封？ 
突发奇想，感谢大家的时间！！

**Comment by kingwilliam** [comment]
假定你有10个vps server, 你是以下那个场景
1. 一个nginx在前， 九个v2在後。
2. 10个v2都直接在前

前设：墙只封ip
1. 封了 nginx ip 就等同全封。
2. 封了 其一还有其九。
