### ISSUE TITLE
通过多个tag识别路由转发

### ISSUE THREAD

**Issue by fbion** [v2ray/discussion#564]
{
        "type": "field",
        "outboundTag": "notcn", // freedom 的 tag
        "domain": ["geosite:geolocation-!cn"] // 中国大陆网站
      },
      {
        "type": "field",
        "outboundTag": "google", // freedom 的 tag
        "domain": ["geosite:google"] // 中国大陆网站
      },
      {
        "type": "field",
        "outboundTag": "facebook", // freedom 的 tag
        "domain": ["geosite:facebook"] // 中国大陆网站
      },
只有一个出口outbounds
如何设置多个tag 来识别触发了哪个出口tag?

**Comment by Vigilans** [comment]
可以把需求描述地再清楚一些
