### ISSUE TITLE
请问如何用代码/命令行把代理模式设置自动代理(PAC)？

### ISSUE THREAD

**Issue by isshe** [v2ray/discussion#567]
需求：通过代码(/命令行?)把代理模式设置为自动代理(PAC)。（想了解各个平台的设置方法）
**不确定v2ray-core是否实现了这个功能？还是说由v2ray客户端侧自行实现？**
已知：
UBUNTU：可以通过命令`gsettings get org.gnome.system.proxy autoconfig-url 'xxx'`进行设置。
未知：
UBUNTU：其他方法？
MACOS：
WINDOWS：

感谢。

**Comment by kslr** [comment]
export http_proxy etc

**Comment by isshe** [comment]
好的，谢谢。
