### ISSUE TITLE
除了sstap和kkcap还有什么软件支持v2ray吗？能nat打通的那种，玩gta5用，p2p游戏严格会进不去线上掉线

### ISSUE THREAD

**Issue by 1265578519** [v2ray/discussion#568]
除了sstap和kkcap还有什么软件支持v2ray吗？能nat打通的那种，玩gta5用，p2p游戏严格会进不去线上掉线

**Comment by 1265578519** [comment]
![image](https://user-images.githubusercontent.com/6442439/75300347-8e970780-5872-11ea-8424-e48e55e3574b.png)
网上找了一大堆，，都是假的，本地端口和外部端口不一致，无法进入游戏

**Comment by ymzsdu** [comment]
v2ray不能支持udp转发吗？

**Comment by 1265578519** [comment]
@ymzsdu v2ray肯定支持udp啊

**Comment by forever8938** [comment]
v2ray的UDP转发仅限于DNS用途，不能加速游戏

**Comment by 1265578519** [comment]
@forever8938 能加速，延迟也OK，就是，，NAT没办法打通不知道怎么搞

**Comment by mzz2017** [comment]
v2ray不是full corn nat，据说社区正在着手这个问题了

**Comment by ymzsdu** [comment]
我最后还是用了专门的游戏加速器，用这种还是不行。有个鲜牛你可以试试，邀请别人就有时长，基本不用花钱，用着还不错。可以填我的邀请码UNTITIYO，淘宝貌似也可以买时长。

**Comment by 1265578519** [comment]
专门的游戏加速器不如买UU了嘛

**Comment by ymzsdu** [comment]
> 专门的游戏加速器不如买UU了嘛

用过一次uu，感觉不太好用，主要是鲜牛可以白嫖啊 XD

**Comment by okudayukiko** [comment]
用NAT网络、没有公网IP会明显影响BT、游戏速度？

**Comment by 1265578519** [comment]
@okudayukiko 对的，游戏都连不上的
