### ISSUE TITLE
关于 OpenWRT 中日志输出的时区问题

### ISSUE THREAD

**Issue by StayTherapy** [v2ray/discussion#570]
OpenWRT 中已经配置了时区，系统的日志输出时区均为 +8
v2ray 也配置了日志输出到文件
```
"log": {
    "loglevel": "warning",
    "access": "/var/logs/v2ray/access.log",
    "error": "/var/logs/v2ray/error.log"
  }
```
但是发现 v2ray 输出 access.log , error.log 的时区貌似依然为 UTC 时区
在启动脚本中加入了时区环境变量也没啥效果
```
export TZ='Asia/Shanghai'
```
又测试了直接运行 v2ray 程序，发现写的日志也是 UTC 时区
> 1. 直接运行 date ，输出当前系统时间（时区输出正确）
> 2. 直接运行 /usr/v2ray/v2ray -config /etc/config/v2ray.config.json
> 3. 检查 error.log 中启动时间，时区与第一步输出不一致

难道是需要其他什么特殊的环境变量？

**Comment by okudayukiko** [comment]
好像是/etc/timezone

**Comment by StayTherapy** [comment]
> 好像是/etc/timezone

试了下好像没效果~

**Comment by dmcdark** [comment]
我也是这个问题，看log看的头疼

**Comment by vcptr** [comment]
因为Openwrt内默认没有zoneinfo，安装好就有了：

```
opkg update
opkg install zoneinfo-asia
#确认配置openwrt时区为`Asia/Shanghai`, 见 /etc/config/system
/etc/init.d/system restart
```

**Comment by StayTherapy** [comment]
> 因为Openwrt内默认没有zoneinfo，安装好就有了：
> 
> ```
> opkg update
> opkg install zoneinfo-asia
> #确认配置openwrt时区为`Asia/Shanghai`, 见 /etc/config/system
> /etc/init.d/system restart
> ```

@vcptr 果然是酱紫，666

**Comment by dmcdark** [comment]
> /etc/init.d/system

done.
Lᵒᵛᵉᵧₒᵤ❤

**Comment by vipwuping** [comment]
进入  系统---系统--时区  更为  Asia/Shanghai  就可以了  然后进入SSH  date 就会显示标准北京时间

**Comment by ZhiboWong** [comment]
> 因为Openwrt内默认没有zoneinfo，安装好就有了：
> 
> ```
> opkg update
> opkg install zoneinfo-asia
> #确认配置openwrt时区为`Asia/Shanghai`, 见 /etc/config/system
> /etc/init.d/system restart
> ```

安装并且设置重启后，v2raya的日志时间还是照旧，咋办？
