### ISSUE TITLE
v2ray服务器地址填写问题

### ISSUE THREAD

**Issue by 228207876** [v2ray/discussion#573]
请问一下在用ws+tls时v2ray客户端地址一定要填域名么？填IP是不是https无效了

**Comment by kingwilliam** [comment]
短答:
Q1:填IP是不是https无效了
A1:填IP https一样有效

Q2:客户端地址一定要填域名么？
A2:可以是域名, 也可以是IP


长答:
1. 如要使用https, 当然要有电子证书, 向认证机构申请电子证书(或自签), 首先要有 域名(domain name).

2. 可否自签电子证书和假域名? 当然可以. 但不建议

3. 在用https传送资料是会带有一个 SNI(Server Name Indication), SNI内就是你的域名 同时没有加密.(为何用https 但SNI没加密? 历史问题,自己问谷歌或百度)

4. 但如你在v2用https但入ip, 会如何? 一样能够科学上网, 但好快会给墙发现(因特徵太明显). 结果如何? 不用说吧.

最後: 非常建意, 申请一个合法域名, 再申请合法电子证书(或自签也可以). 做齐以上 都不能保证 不被墙 但有好过没有.

**Comment by 228207876** [comment]
> 短答:
> Q1:填IP是不是https无效了
> A1:填IP https一样有效
> 
> Q2:客户端地址一定要填域名么？
> A2:可以是域名, 也可以是IP
> 
> 长答:
> 
> 1. 如要使用https, 当然要有电子证书, 向认证机构申请电子证书(或自签), 首先要有 域名(domain name).
> 2. 可否自签电子证书和假域名? 当然可以. 但不建议
> 3. 在用https传送资料是会带有一个 SNI(Server Name Indication), SNI内就是你的域名 同时没有加密.(为何用https 但SNI没加密? 历史问题,自己问谷歌或百度)
> 4. 但如你在v2用https但入ip, 会如何? 一样能够科学上网, 但好快会给墙发现(因特徵太明显). 结果如何? 不用说吧.
> 
> 最後: 非常建意, 申请一个合法域名, 再申请合法电子证书(或自签也可以). 做齐以上 都不能保证 不被墙 但有好过没有.

谢谢，直接填ip省去辣鸡免费域名解析快的多

**Comment by okudayukiko** [comment]
用TLS，尽量填服务器域名。TLS证书包含CN（域名或IP）、过期日期等信息，如果CN不对，浏览器就会提示不安全。
自签可能被MITM，不建议使用自签。

**Comment by nicholascw** [comment]
@okudayukiko 自签依然可以验证CA身份，见手册 [TLSObject](https://www.v2fly.org/chapter_02/05_transport.html#tlsobject) [CertificateObject](https://www.v2fly.org/chapter_02/05_transport.html#certificateobject)。然后把CA的私钥销毁打印下来塞到自己床板下面。这样，只要不带陌生人上床应该不会被MITM，甚至比用大厂的CA更有安全感。

**Comment by liansh2002** [comment]
> 短答:
> Q1:填IP是不是https无效了
> A1:填IP https一样有效
> 
> Q2:客户端地址一定要填域名么？
> A2:可以是域名, 也可以是IP
> 
> 长答:
> 
> 1. 如要使用https, 当然要有电子证书, 向认证机构申请电子证书(或自签), 首先要有 域名(domain name).
> 2. 可否自签电子证书和假域名? 当然可以. 但不建议
> 3. 在用https传送资料是会带有一个 SNI(Server Name Indication), SNI内就是你的域名 同时没有加密.(为何用https 但SNI没加密? 历史问题,自己问谷歌或百度)
> 4. 但如你在v2用https但入ip, 会如何? 一样能够科学上网, 但好快会给墙发现(因特徵太明显). 结果如何? 不用说吧.
> 
> 最後: 非常建意, 申请一个合法域名, 再申请合法电子证书(或自签也可以). 做齐以上 都不能保证 不被墙 但有好过没有.

搭车同请教，多台VPS做服务器，同步了相同的证书，域名也是同一个。客户端使用ws+tls。然后使用另一台线路好的VPS通过Haproxy转发来自客户端的流量，并使用Haproxy做负载均衡，这样Haproxy的Server就直接写了服务器的ip地址，会有风险吗？
是不是应该申请个泛域名证书，然后没太服务器都用不同域名更安全呢？

**Comment by kingwilliam** [comment]
因haproxy可以有两种模式
1. mode http
2. mode tcp

例如您是 https+vmess

1. 如haproxy 是 mode http, 电子证书就要放在 haproxy, 由haproxy负责unload电子证, 之後只剩下vmess,
即 haproxy --(vmess)-> backend

2. 如haproxy 是 mode tcp, 电子证书只需放在backend server, haproxy只负责看sni, 之後原封不动交给backend,
即 haproxy --(https+vmess)-> backend


还要留意 您的haproxy在 国"内" 还是在 国"外"!
如在 国"内" 最好是用 mode tcp
如在 国"外" 两个也可以

=======================

Q1:这样Haproxy的Server就直接写了服务器的ip地址，会有风险吗？
A1:如用mode tcp应不会, 如haproxy在国"内"千万不要用mode http.

Q2:是不是应该申请个泛域名证书，然后没太服务器都用不同域名更安全呢？
A2:"泛域名证书" 在这场景应用不着, 至于不同服务器用不同域名会否更安全?如haproxy在国“外”应该不会,但如在国"内"可能有点点吧.

**Comment by liansh2002** [comment]
> 因haproxy可以有两种模式
> 
> 1. mode http
> 2. mode tcp
> 
> 例如您是 https+vmess
> 
> 1. 如haproxy 是 mode http, 电子证书就要放在 haproxy, 由haproxy负责unload电子证, 之後只剩下vmess,
>    即 haproxy --(vmess)-> backend
> 2. 如haproxy 是 mode tcp, 电子证书只需放在backend server, haproxy只负责看sni, 之後原封不动交给backend,
>    即 haproxy --(https+vmess)-> backend
> 
> 还要留意 您的haproxy在 国"内" 还是在 国"外"!
> 如在 国"内" 最好是用 mode tcp
> 如在 国"外" 两个也可以
> 
> =======================
> 
> Q1:这样Haproxy的Server就直接写了服务器的ip地址，会有风险吗？
> A1:如用mode tcp应不会, 如haproxy在国"内"千万不要用mode http.
> 
> Q2:是不是应该申请个泛域名证书，然后没太服务器都用不同域名更安全呢？
> A2:"泛域名证书" 在这场景应用不着, 至于不同服务器用不同域名会否更安全?如haproxy在国“外”应该不会,但如在国"内"可能有点点吧.

感谢答疑，haproxy确实在国内，最开始用V2ray做转发，简直是此地无银三百两啊！所以国内VPS重装系统后只装haproxy，模式也确实是tcp模式。
泛域名证书确实用不到，因为用泛域名证书后，tcp模式没法使用haproxy做负载均衡。最开始想当然了，后来一动手发现根本走不通
