### ISSUE TITLE
新发现2：v2ray+tcp+tls+web

### ISSUE THREAD

**Issue by kirin10000** [v2ray/discussion#574]
服务端：
1.先用nginx搭建一个web服务，编译时加上--with-stream
2.将web服务的所有443端口改为别的端口，这里改为8888
3.配置v2ray+tcp+tls，https://guide.v2fly.org/advanced/tls.html#%E6%9C%8D%E5%8A%A1%E5%99%A8
然后将443端口改为别的端口，这里改为9999
```bash
  "inbounds": [
    {
      "port": 9999, 
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "b9fa56b4-c7b7-4698-829e-844d77fe6526",
            "alterId": 0
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls", 
        "tlsSettings": {
          "certificates": [
            {
              "certificateFile": "/etc/nginx/certs/cer",
              "keyFile": "/etc/nginx/certs/key"
            }
          ]
        }
      }
    }
  ],
```
4.nginx加上stream模块的代码
![image](https://user-images.githubusercontent.com/57820613/75457316-4fbe9a00-59b7-11ea-9dc8-029bd0ade54d.png)
```bash
stream {
        upstream aa{
                server 127.0.0.1:9999;
                server 127.0.0.1:8888;
        }
        server {
                listen 443;
                proxy_pass aa;
        }
}
```
客户端：
![image](https://user-images.githubusercontent.com/57820613/75456607-b5118b80-59b5-11ea-83c9-ac3251f1a9f2.png)

实现v2ray+tcp+tls+web，网站成功访问，v2ray也可以运行，但感觉还是有很多可以改进的地方（刚写出来）。
如果想要快一点可以把vmess换成socks：https://github.com/v2ray/discussion/issues/513
如果想稳一点可以给tcp添加http伪装，这样就更像https了。（没试过不知道行不行）

**Comment by forever8938** [comment]
TLS已经把承载的数据流加密了，再伪装也没有意义。

**Comment by okudayukiko** [comment]
> TLS已经把承载的数据流加密了，再伪装也没有意义。

客户端使用allowinsecure:false 才真正安全。自签证书不安全。

**Comment by okudayukiko** [comment]
我发现TLS+WS比TLS+TCP快很多，看视频TLS+WS比TLS+TCP清晰。

**Comment by okudayukiko** [comment]
我发现TLS+WS比TLS+TCP快，看视频TLS+WS比TLS+TCP清晰

**Comment by kirin10000** [comment]
> 我发现TLS+WS比TLS+TCP快，看视频TLS+WS比TLS+TCP清晰

我试到也是这样

**Comment by ghost** [comment]
https://github.com/v2fly/v2ray-examples/blob/master/VLESS-TCP-TLS%20(maximal%20by%20rprx)/config_server.json

**Comment by quackerd** [comment]
这个我感觉会被主动嗅探。
GFW和nginx建立TLS，然后不发HTTP流量发TCP是不是就可以直接嗅探到v2ray服务器？
相比之下websocket的path如果不对的话就是bad request, 很难直接探测到。

个人愚见，请轻喷

**Comment by kirin10000** [comment]
> 这个我感觉会被主动嗅探。
> GFW和nginx建立TLS，然后不发HTTP流量发TCP是不是就可以直接嗅探到v2ray服务器？
> 相比之下websocket的path如果不对的话就是bad request, 很难直接探测到。
> 
> 个人愚见，请轻喷

确实，用这个就好了
https://guide.v2fly.org/advanced/tcp_tls_web.html
