### ISSUE TITLE
来自于shadowsocks的避免IP被封的一个想法

### ISSUE THREAD

**Issue by siwind** [v2ray/discussion#575]
使用ss的服务器，经常在systemctl的日志中发现这样的记录：

```
ERROR: crypto: AEAD: repeat salt detected
ERROR: failed to handshake with 1xx.2xx.4x.5x: authentication error
......
```
大概意思就是某个IP(例如上述的“**1xx.2xx.4x.5x**”)，发起了重放攻击/重放探测。这种IP在日志中有很多行，并且有很多IP。
那么有个想法，就是简单写个脚本定时读取日志，然后将这些IP地址加入防火墙的黑名单，为了避免误伤，可以限制这些IP对服务器提供服务端口的访问。这样可以在一定程度上杜绝IP地址被封的风险。

这样的话，只要V2ray能提供上述的包含IP地址的重放攻击的日志，写一个阻断的脚本应该不是很困难的事情，甚至可以将需要阻断的IP收集起来，避免后续的VPS被墙~

========更新：==============
这个方法已经有了。
搜索一下“ **fail2ban** shadowsocks” 即可。

**Comment by con-a** [comment]
个人怀疑，可能这些IP只是每次随便选的，各大ISP提供的，可能是随机的一个动态IP。如果有人能试一下这些IP会不会重复探测服务器最好了

**Comment by con-a** [comment]
查了一下，有一个国外的研究：https://youtu.be/QBp6opkcxoc （这个演讲不错）里面15:00说，他们采集的16083个不同的GFW探测IP地址里面，95%的都只探测了一次，反DNS查询出来都是ISP池的IP地址。所以这样防火墙可能没用

**Comment by okudayukiko** [comment]
我用V2Ray TLS，打开log看看也有很多TLS Error，不过TLS Error的IP很多来自海外。

**Comment by con-a** [comment]
我开V2Ray TLS基本没有国内的探测，但是之前试过shadowsocks开一会就有一大堆全都是国内来的

**Comment by forever8938** [comment]
GFW控制国内所有空闲IP，数量是海量的，甚至还会走代理探测，日志显示几秒内有十几个国外IP访问的SS端口。另外，不要试图阻止墙探测，否则直接封IP。

**Comment by forever8938** [comment]
一种对抗主动探测的方法：配置NAT表，只允许白名单的IP访问SS端口，把其他IP的请求重定向到一个别的TCP服务的端口，这样墙观察到的反应就和SS无关。

**Comment by siwind** [comment]
这个方法其实是可行的，而且效果也不错。
1) 关于特征， 必须是 ss服务器报 "repeat salt", 才是这里需要防的。  对于vps多次ssh登录失败等的肉鸡扫描，那是另一回事，和这里说的不同。

2) 上述某网友说的“不要试图阻止墙探测",  更是无稽之谈。 vps开防火墙，关墙什么事情?  如果已经被探测出来早就封了， 没探测出来，只能知道这里有防火墙， 如此而已~

**Comment by forever8938** [comment]
> 这个方法应该是可行的。
> 关于特征， 必须是 ss服务器报 "repeat salt", 才是这里需要防的。 对于vps多次ssh登录失败等的肉鸡扫描，那是另一回事，和这里说的不同。
> 
> 上述某网友说的“不要试图阻止墙探测", 更是无稽之谈。 vps开防火墙，关墙什么事情? 如果已经被探测出来早就封了， 没探测出来，只能知道这里有防火墙， 如此而已~
> 
> 根据日志得到异常IP以后，重定向到另外一个端口，也是一种处理结果。


你这是掩耳盗铃，不知道怎么得来的效果不错这个结论，还编辑掉了。要是可以这样处理，我也不用想上面说的方法了。你可以访问，凭什么审查者不可以？墙是用机器学习自动评估的，每天探测的次数可以达到上百次，甚至还会用国外的IP。什么端口只有你能访问，而墙的海量国内外IP都不可以？这只会增加可疑系数。443端口理论上是不怕探测的，照你这么说把443端口也一刀切屏蔽掉岂不是效果更好？

**Comment by siwind** [comment]
举个例子，比如错误登录SSH次数过多一样， 后续输入的内容是什么都是忽略~~
（如果启用了SSH错误次数多于3次禁止登录一样）
除非墙在第一次发重放包，只用一个包就能发现你的服务是SS。 

端口和IP能不能被限制，防火墙就能做到。 简单的东西不用说了吧~~

**Comment by siwind** [comment]
> 个人怀疑，可能这些IP只是每次随便选的，各大ISP提供的，可能是随机的一个动态IP。如果有人能试一下这些IP会不会重复探测服务器最好了

确实会有各大ISP提供很多IP。但是不可能为了一个vps动用成千上万IP，猜测只使用了少数IP进行探测。这样的话，对VPS的防火墙而言，应该问题不大~

**Comment by xianren78** [comment]
墙又不是要破解你的数据还需要反复探测，它只需要知道你架设了SS就行了。这个只是其中的一个重放攻击探测手段。

**Comment by Gh0u1L5** [comment]
> 
> 
> 举个例子，比如错误登录SSH次数过多一样， 后续输入的内容是什么都是忽略~~
> （如果启用了SSH错误次数多于3次禁止登录一样）
> 除非墙在第一次发重放包，只用一个包就能发现你的服务是SS。
> 
> 端口和IP能不能被限制，防火墙就能做到， 简单的东西不用说了吧~~
> 
> 如果墙不主动探测vps， 而是对中间节点截获的数据包进行分析来判断ss服务，那就没办法~
> 
> （另外443一刀切是什么鬼？ ）
> （凭什么墙可以访问是什么鬼？ 我的vps我当然可以访问）

啊这……你们俩的对话真是驴唇不对马嘴……你之前说`vps开防火墙，关墙什么事情? 如果已经被探测出来早就封了， 没探测出来，只能知道这里有防火墙， 如此而已~`，他的意思是，墙已经检测到疑似翻墙流量了，而且走的就是这个端口，所以才会发起主动探测确认一次。结果主动探测的时候，却发现有个防火墙拦着，那这不是此地无银三百两，凭什么你的机器在走可疑流量，其他IP却什么流量都走不了？

**Comment by sgf** [comment]
伪装成微信等协议的流量.
