### ISSUE TITLE
Feature Request: Prevent sensitive info being logged into access log

### ISSUE THREAD

**Issue by AvailCat** [v2ray/discussion#583]
Hello,

Is there a way to stop write client IP and email into access log without completely disable log?
Those info should be sensitive for a proxy software and should not enabled by default or optional disable with a warning to tell user their access log will be recorded.

**Comment by kslr** [comment]
This depends on the log level, there are no default parameters

**Comment by AvailCat** [comment]
@kslr It not depends on the log level, at least in latest release 4.22.1.

The document on www.v2ray says log level is default to "warning", this is same as my configure file, but both "warning" and "error" will print access log like this:

```
Mar 01 00:01:01 access-us.srv4.internal v2ray[17527]: 2020/03/01 00:01:01 192.x.x.x:12345 accepted tcp:www.example.org:443 email:u00@internal
```
