### ISSUE TITLE
请问下如何知道v2ray是否国内直连呢？如何查看。

### ISSUE THREAD

**Issue by wkzqn** [v2ray/discussion#584]

**Comment by QinanWu** [comment]
国内国外网站分别查询ip看下。

**Comment by MikuPy2001** [comment]
![微信截图_20200306083459](https://user-images.githubusercontent.com/29778409/76038841-a0209380-5f85-11ea-9dcb-4ec550e985dd.png)
是不是这样的效果?

**Comment by wkzqn** [comment]
@MikuPy2001 可是我的config.json文件为啥我修改之后重启v2rayN的时候它被自动被重置？

**Comment by wkzqn** [comment]
@MikuPy2001 感觉你这个很炫酷

**Comment by MikuPy2001** [comment]
> @MikuPy2001 可是我的config.json文件为啥我修改之后重启v2rayN的时候它被自动被重置？

喵没有用过v2rayN外壳,喵用的是v2ray核心.
不过喵可以帮你猜测一下:
1. v2rayN全权管理了配置文件,每次都是按照v2rayN自己的方式生成的
2. 你修改的配置文件不合法,建议检测一下

> @MikuPy2001 感觉你这个很炫酷
emmm,喵正在自己写一个能代理全部流量的工具,原理是Proxifier+v2ray,所以没有用v2rayN之类的外壳,你看到的这个黑框框是v2ray运行界面来的

**Comment by wkzqn** [comment]
@MikuPy2001 好的，谢谢，我尝试寻找一下我的原因~

**Comment by CalmLong** [comment]
打开百度，输入 IP，看一下是服务器的IP还是本机宽带的IP
