### ISSUE TITLE
v2ray端口老是被封，有没有什么方法可以优化

### ISSUE THREAD

**Issue by QinanWu** [v2ray/discussion#585]
如题，请问怎样优化？

**Comment by okudayukiko** [comment]
V2Ray不要用UDP系列协议（如mKCP），用TCP系列协议（如TCP、WebSocket）

**Comment by fbion** [comment]
机场中转吧

**Comment by okudayukiko** [comment]
V2Ray的TCP、WS 我这里都用不了，只有TLS可用。可能AES-128-GCM加密已经不够。

**Comment by QinanWu** [comment]
> 机场中转吧

什么概念，可以简单说下么？

**Comment by z16166** [comment]
搜"免费CDN"这种方案

**Comment by 0CrazyGuy9** [comment]
还是用CDN+NGINX+WS方式好，至少天天看4K
