### ISSUE TITLE
请教一下window10和Debian9网络环境的差别

### ISSUE THREAD

**Issue by qingfengshi** [v2ray/discussion#586]
最近在家里做了一个Linux服务器，也使用了v2ray作为旁路代理。在配置的过程中发现，我在win10上可以使用的配置文件，在Linux上却不能使用，总是报错“x509: certificate signed by unknown authority”，经过网上搜索，问题解决了，添加“allowInsecure”就可以。我的证书是let's encrypt的免费证书，出现这样的问题也正常。可是为什么win10上没有报错，而Linux上的客户端就报错呢？

请知道的兄弟指点，多谢了。

**Comment by kingwilliam** [comment]
你要在linux v2ray .pem电子证书内加入bundle CA证书

```
-----BEGIN CERTIFICATE-----
*** 你的电子证书 ***
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
*** let's encrypt CA电子证书 ***
-----END CERTIFICATE-----
```

**Comment by qingfengshi** [comment]
谢谢，Windows里不验证ca证书可不可靠的吗？

**Comment by okudayukiko** [comment]
可能Debian 9没有自带Let's Encrypt CA证书。用dpkg-reconfigure ca-certificates或update-ca-certificates命令更新一下CA证书。
将Debian 9升级到Debian 10也很简单。
