### ISSUE TITLE
routing domainStrategy 问题

### ISSUE THREAD

**Issue by fbion** [v2ray/discussion#588]
当 domainStrategy: AsIs时
访问 view-source:http://www.oshome.com/
默认走代理:
v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.oshome.com:80
v2ray.com/core/app/dispatcher: sniffed domain: www.oshome.com
v2ray.com/core/app/dispatcher: default route for tcp:www.oshome.com:80

"AsIs": 只使用域名进行路由选择。默认值。
意思是
即使配置了 geoip:cn direct的规则也不生效？
也没有匹配到oshome domain规则 所以走default route?

当 domainStrategy: IPIfNonMatch时
v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.oshome.com:80
v2ray.com/core/app/dispatcher: sniffed domain: www.oshome.com
v2ray.com/core/transport/internet/udp: establishing new connection for udp:192.168.1.1:53
v2ray.com/core/app/dispatcher: taking detour [direct] for [udp:192.168.1.1:53]
v2ray.com/core/proxy/freedom: opening connection to udp:192.168.1.1:53
v2ray.com/core/app/dns: UDP:192.168.5.253:53 got answere: www.oshome.com. TypeA -> [123.56.138.243] 28.577318ms
v2ray.com/core/app/dispatcher: taking detour [direct] for [tcp:www.oshome.com:80]
v2ray.com/core/proxy/freedom: opening connection to tcp:www.oshome.com:80
v2ray.com/core/proxy/freedom: dialing to to tcp:123.56.138.243:80
v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:123.56.138.243:80

这里要去解析 再判断ip

所以更高效的解决方法是? 减少dns解析
自己维护 direct与proxy的域名清单?

**Comment by Loyalsoldier** [comment]
是的，可以参考 https://github.com/Loyalsoldier/v2ray-rules-dat
