### ISSUE TITLE
按照白话文教程中TProxy透明代理配置，钉钉视频会议无法使用

### ISSUE THREAD

**Issue by minotaurking** [v2ray/discussion#589]
按照白话文教程配置透明代理(TProxy)，使用钉钉视频或者语音会议，开始正常，半分钟左右视频和声音就卡住了，但是也不断开，静音等操作对端立刻能够收到．钉钉的直播功能没有问题，平时看视频或者直播也没有问题，微信视频和语音通话都没有问题．请教各位这大概是什么问题

**Comment by nicholascw** [comment]
抓个包看看有什么魔法？

**Comment by qiangliu8183** [comment]
华为welink遇到同样的问题，怀疑是UDP转发有问题
