### ISSUE TITLE
win10之前使用正常，忽然连不了外网了什么原因。ios跟ubuntu都能正常用

### ISSUE THREAD

**Issue by rayyu999** [v2ray/discussion#590]
--------------------------------info[10:35:23]--------------------------------
System.Exception: v2rayN start up v2rayN - V3.5 - 2020/01/15

 
--------------------------------info[10:35:59]--------------------------------
System.Exception: Webserver prefixes http://*:10810/pac/

 
--------------------------------拒绝访问。[10:35:59]--------------------------------
System.Net.HttpListenerException (0x80004005): 拒绝访问。
   在 System.Net.HttpListener.AddAllPrefixes()
   在 System.Net.HttpListener.Start()
   在 v2rayN.Base.HttpWebServer..ctor(String[] prefixes, Func`2 method)

 
--------------------------------info[10:35:59]--------------------------------
System.Exception: Webserver InitServer 拒绝访问。

 
--------------------------------info[10:35:59]--------------------------------
System.Exception: WebserverB at 127.0.0.1

 
--------------------------------info[10:35:59]--------------------------------
System.Exception: WebserverB running...

 
--------------------------------info[10:35:59]--------------------------------
System.Exception: WebserverB Request 127.0.0.1

**Comment by iochen** [comment]
see https://github.com/2dust/v2rayN/issues/241
