### ISSUE TITLE
nginx websocket 代理的 buffer 是否会影响性能？

### ISSUE THREAD

**Issue by zry98** [v2ray/discussion#591]
nginx 代理配置中的 `proxy_buffering` 及 `proxy_buffers`、`proxy_buffer_size` 等参数是否会影响性能？

**Comment by DolorHunter** [comment]
详见: [NGINX - Module ngx_http_proxy_module](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffer_size)
