### ISSUE TITLE
v2ray的mKCP模式有毒

### ISSUE THREAD

**Issue by dbguo** [v2ray/discussion#593]
试了无数次，v2ray的mKCP不管加不加伪装都是一用就封，改用SS+KCPTUN试用了半个月一点问题没有。希望v2ray的mKCP能有所改动。

**Comment by iochen** [comment]
stop using mKCP

**Comment by fbion** [comment]
套
https://github.com/wangyu-/udp2raw-tunnel

**Comment by huashaoli** [comment]
mKCP出国是有问题的 被Qos。 但国内好象可以。
正解是楼上
https://github.com/wangyu-/udp2raw-tunnel

**Comment by xhqpp** [comment]
你能不能别再糟蹋ip了

**Comment by forever8938** [comment]
mkcp+ss-tunnel
