### ISSUE TITLE
请问dns expectIPs 可否加入 geoip .not. countryIP 如 .not. cn

### ISSUE THREAD

**Issue by kingwilliam** [v2ray/discussion#596]
因在国外翻墙回国, 如domain有国外ip, dns可否只回覆 !cn.

```
"dns": {
   "servers": [
      {
         "address": "1.2.3.4",
         "expectIPs": [
            "geoip: !cn" <-- 可否加入 .not. countryIP 如 .not. cn
         ]
      }
   ]
}
```

**Comment by kingwilliam** [comment]
暂时用了比较愚蠢的方法,需可行但都希望v2团队可考虑加入此功能。

理谂是中国IP就是CN, 中国以外IP就是WW


首先下载 GeoLite2-Country-CSV.zip

在GeoLite2-Country-Locations-en.csv内找出china的id是1814991

```
1733045,en,AS,Asia,MY,Malaysia,0
1814991,en,AS,Asia,CN,China,0     <-----
1819730,en,AS,Asia,HK,"Hong Kong",0
```


同时在GeoLite2-Country-Locations-en.csv加入一条新record用来取代全球IP***但不包括cn***

`000000,en,WW,"World Wide",WW,"World Wide",0`


再replace 
GeoLite2-Country-Blocks-IPv4.csv 
GeoLite2-Country-Blocks-IPv6.csv
非 1814991 由 000000 取代

```
由
1.0.0.0/24,2077456,2077456,,0,0     <-----
1.0.1.0/24,1814991,1814991,,0,0
1.0.2.0/23,1814991,1814991,,0,0
1.0.4.0/22,2077456,2077456,,0,0     <-----
1.0.8.0/21,1814991,1814991,,0,0

到
1.0.0.0/24,000000,2077456,,0,0     <-----
1.0.1.0/24,1814991,1814991,,0,0
1.0.2.0/23,1814991,1814991,,0,0
1.0.4.0/22,000000,2077456,,0,0     <-----
1.0.8.0/21,1814991,1814991,,0,0
```

这样country code就只得 CN 和 WW, 之後就output到 notcn.dat

最後修改config.json dns部份
```
   "dns": {
        "tag": "dns-direct",
        "servers": [
            {
                "expectIPs": [
                    "ext:notcn.dat:ww"
                ],
                "address": "1.1.1.1"
            }
            "https+local://cloudflare-dns.com/dns-query"
        ]
    }
```

**Comment by CalmLong** [comment]
其实自行生成一下 `geoip.dat`，将 `cn` 以外的标签都改为 `ww`，这样就能实现这个效果。

但是 `geoip.dat` 里面内置的标签不光只有 `cn`，也有 `us` 等等，你在哪个国家直接加上哪个国家的代码不就好了

**Comment by kingwilliam** [comment]
因我是由 国外 翻入 国内 所以我只需要 CN走v2 和 !CN就直连.

**Comment by CalmLong** [comment]
感觉好乱，domain 中也没有国外的 IP啊，geoip 中才有

> 因在国外翻墙回国, 如domain有国外ip, dns可否只回覆 !cn.

dns 返回 !cn 的也就是返回当前国家的，那加上对应的国家代码也没问题啊

**Comment by kingwilliam** [comment]
```
   "dns": {
        "tag": "dns-direct",
        "servers": [
            {
                "expectIPs": [
                    "ext:notcn.dat:ww"
                ],
                "address": "https+local://cloudflare-dns.com/dns-query"
            }
            "https+local://cloudflare-dns.com/dns-query"
        ]
    },

    "routing": {
        "rules": [
            {
                "type": "field",
                "ip": [
                   "geosite:cn"
                ],
                "outboundTag": "vmess_to_cn"
            },
            {
                "type": "field",
                "network": "tcp,udp",
                "outboundTag": "direct"
            }
        ]
    },

```
Q1:为甚麽要这样设定?
A1:因有一些网站有可能同时有 国内IP和国外IP, 如不在dns时进行过滤, 会有机会一时取得国外IP,一时取得国内IP. 这个设定就可优先取国外IP直连,如没先再取国内IP. 可以直连当然首选直连.

Q2:为甚麽不在geoip建入你要去的国家,这样就不省功夫吗?
A2:你知你在看的网站是建在那吗? sg? de? 还有太多未知

上面config.json 可以这样理解 你要浏览那个网站, 先要问dns取得网站IP, 这时dns会有两个可能
1. expectIPs会给出 !cn IP, 之後直连
2. expectIPs过滤後发现全都是 CN IP, 所以会出现"expectIPs not match"跳出和不给IP. 所以coding为可会有两组"https+local",就是要处理这情况.
