### ISSUE TITLE
v2ray + tls +websocket 的断流很可能是第三方客户端导致的 [纯讨论，不涉及issues]

### ISSUE THREAD

**Issue by DarienRaymond** [v2ray/discussion#6]
From v2ray-core created by [choicky](https://github.com/choicky) : v2ray/v2ray-core#1085  

PC 端 和 iOS 都在使用相同服务器的 v2ray + tls +websocket 。
我的PC端没有发现明显的断流现象，而 iOS 有很明显的断流现象，尤其是看 twitter 的视频时，通常在10秒钟左右就断流了。

最近折腾了一下，发现：

1. iOS 下的 Shadowrocket 使用上述组合一定会断流
不管我是否在 `v2ray.service `设置 `/usr/bin/env v2ray.ray.buffer.size=1`

**Updated on May 03, 2018:**  
* Shadowrocket 在 `v2ray.ray.buffer.size=0`情况下依然有明显的断流。

2. iOS 下 Kitsunebi 没发现断流
不管我是否在 `v2ray.service `设置 `/usr/bin/env v2ray.ray.buffer.size=1`
btw，只测试了半个小时左右。如以后有新发现，会update在这里

3. iOS 下 Pepi 在设置了 `/usr/bin/env v2ray.ray.buffer.size=1`之后能避免断流
如没有设置，则 Pepi 跟 Shadowrocket 类似，会断流。

**Updated on May 03, 2018:**  
* Pepi在 `v2ray.ray.buffer.size=1`情况下依然有断流，只是断流现象比不设置时有所改善。
* Pepi在 `v2ray.ray.buffer.size=0`情况下暂时没发现断流

btw，设置办法如下：
`/etc/systemd/system/multi-user.target.wants/v2ray.service` 中，

```
ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
```
改为
```
ExecStart=/usr/bin/env v2ray.ray.buffer.size=1 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
```

**Comment by Shameless521** [comment]
您好，我想问下，iOS怎么实现的v2ray，能否告知一下。小弟不胜感激
