### ISSUE TITLE
移动端移植：限制Inbound最大链接数

### ISSUE THREAD

**Issue by ShadowRayEN** [v2ray/discussion#60]
背景描述：
对于V2Ray-Core移动端移植，比较大的问题是内存问题（主要是iOS的15M限制）。为了得到一个相对稳定的版本，从以下各方面入手解决：
1、通过调整bufferSize降低Heap的开销
2、通过配置Mux，减少Outbound连接数，从而降低Stack的开销
3、调整Policy中connIdle，加速Inbound连接数的关闭

再配合一些对Go运行环境的配置，现已得到一个相对稳定的版本。实际测试中发现，初始启动内存9M以下。在不加入TLS时，内存维持在12M以下。加入TLS后，内存在14M左右。可以满足一般的应用需求。但是在加入TLS的前提下，某些情况仍然会出现崩溃，主要原因是打开某些网页时并发开启的TCP链接数太大（20条以上）。为了彻底解决移动端移植的内存问题，需要限制最大开启Inbound链接数。具体算法为：每次开启新链接时，检测是否到达最大限制，如果到达最大限制，则关闭最先开启且不活跃时间最长的链接。

请问项目组是否有计划要实现这个特性？如果需要自己实现这个特性的话，请问大致的修改思路应该是怎样的？

**Comment by VictoriaRaymond** [comment]
这个你在移动端的入口做就好了，现在移动端通常不用常规的inbound，比如通过api直接dispatch连接，这种情况下没法在V2Ray的inbound上限制连接数量。

**Comment by ShadowRayEN** [comment]
是的，这边其实就http inbound会有这个需求。http现在是直接用系统的转发，不经过下面走，所以只能在V2Ray这边控制。可能是代码里tun2socks跟V2Ray的对接有问题，导致如果http从下面走会对接不上。其他的连接在tun2socks那里可以限制住。

**Comment by ShadowRayEN** [comment]
> 在编译成framework的时候把不使用的模块或者协议不编译进framework是否会对降低内存使用有效果？
> 启动服务的时候是否加载没有配置的协议，比如只配置了shadowsocks，就不启动或者使用vemess或者其他协议？

建议你先直接在Mac上进行修改调试和验证想法。当Mac上的调试结果足够满意，再转到移动端进一步优化。

**Comment by FatChou** [comment]
谢谢你的建议。
第二个问题：启动服务的时候是否加载没有配置的协议，现在的做法是这样吗？
