### ISSUE TITLE
亲戚在外国，她想用软路由做全局代理，怎么配置？

### ISSUE THREAD

**Issue by okudayukiko** [v2ray/discussion#601]
软路由用Ubuntu Linux系统，eth0是PPPoE，eth1与局域网交换机相连。eth1的IP地址是192.168.1.1，配置了DHCP。
需要做到：eth1访问中国网站、特定端口就走V2Ray outbound-cn，eth1访问台湾网站就走outbound-tw，其他流量走freedom。eth1直通ICMP流量，因为V2Ray不能代理ICMP流量。

**Comment by kingwilliam** [comment]
好想帮您, 但您的资料不详, 

(1) eth1访问中国网站
(2) 特定端口就走V2Ray outbound-cn
(3) eth1访问台湾网站就走outbound-tw
(4) 其他流量走freedom


1. (1)就是直连, 直接等同(4)freedom.
2. 我的理解是如http80, https443, ftp21, 可用routing rules处理
```
"routing": {
    "rules": [
        {
            "type": "field",
            "port": "80,443,21",
            "outboundTag": "outbound-cn"
        }   
    ]
},
```
3. v2ray的geosite.dat只包含china site, 但您可以自建taiwan site, 或可同用routing rules处理
```
"routing": {
    "rules": [
        {
            "type": "field",
            "domain": [
                "tw.yahoo.com",
                "shopee.tw"
            ],
            "outboundTag": "outbound-tw"
        }   
    ]
},
```

最後 outbound-cn, outbound-tw 是甚麽, 我想你已解决.

**Comment by okudayukiko** [comment]
> 好想帮您, 但您的资料不详,
> 
> (1) eth1访问中国网站
> (2) 特定端口就走V2Ray outbound-cn
> (3) eth1访问台湾网站就走outbound-tw
> (4) 其他流量走freedom
> 
> 1. (1)就是直连, 直接等同(4)freedom.
> 2. 我的理解是如http80, https443, ftp21, 可用routing rules处理
> 
> ```
> "routing": {
>     "rules": [
>         {
>             "type": "field",
>             "port": "80,443,21",
>             "outboundTag": "outbound-cn"
>         }   
>     ]
> },
> ```
> 
> 1. v2ray的geosite.dat只包含china site, 但您可以自建taiwan site, 或可同用routing rules处理
> 
> ```
> "routing": {
>     "rules": [
>         {
>             "type": "field",
>             "domain": [
>                 "tw.yahoo.com",
>                 "shopee.tw"
>             ],
>             "outboundTag": "outbound-tw"
>         }   
>     ]
> },
> ```
> 
> 最後 outbound-cn, outbound-tw 是甚麽, 我想你已解决.

能不能用GeoIP搞定？要求能自动代理台服游戏，对于台湾IP自动走outbound-tw。
iptables设定好象是，对于TCP和UDP就走V2Ray inbound的SOCKS，对于ICMP就直接走eth0。

**Comment by kingwilliam** [comment]
> 能不能用GeoIP搞定？要求能自动代理台服游戏，对于台湾IP自动走outbound-tw。
> iptables的NAT设定好象是，对于TCP和UDP就走V2Ray inbound的SOCKS，对于ICMP就直接走eth0。

如用 geoip 台湾IP自动走outbound-tw。
```
"routing": {
    "rules": [
        {
            "type": "field",
            "ip": [
                "geoip:tw"
            ],
            "outboundTag": "outbound-tw"
        }   
    ]
},
```

**Comment by okudayukiko** [comment]
> > 能不能用GeoIP搞定？要求能自动代理台服游戏，对于台湾IP自动走outbound-tw。
> > iptables的NAT设定好象是，对于TCP和UDP就走V2Ray inbound的SOCKS，对于ICMP就直接走eth0。
> 
> 如用 geoip 台湾IP自动走outbound-tw。
> 
> ```
> "routing": {
>     "rules": [
>         {
>             "type": "field",
>             "ip": [
>                 "geoip:tw"
>             ],
>             "outboundTag": "outbound-tw"
>         }   
>     ]
> },
> ```
> 
> geoip内是有taiwan的
> ![tw](https://user-images.githubusercontent.com/3607762/77247266-4b119c80-6c6a-11ea-87e9-f276593402ba.png)

iptables NAT怎么设置？eth1的TCP和UDP走socks 127.0.0.1:1080，eth1的ICMP走eth0。

**Comment by kingwilliam** [comment]
> iptables NAT怎么设置？eth1的TCP和UDP走socks 127.0.0.1:1080，eth1的ICMP走eth0。

1. iptables NAT怎么设置？
2. eth1的TCP和UDP走socks 127.0.0.1:1080
3. eth1的ICMP走eth0。


2. 你要的应该是 “透明代理” eth1的TCP和UDP可送到dokodemo

3. 在(2)只送tcp,udp到dokodemo, icmp就会直连出eth0.

1. 可参考"新 V2Ray 白话文指南 - 应用篇 - 透明代理"
https://guide.v2fly.org/app/transparent_proxy.html

iptables.sh
```
iptables -t nat -N V2RAY # 新建一个名为 V2RAY 的链
iptables -t nat -A V2RAY -d 192.168.0.0/16 -j RETURN # 直连 192.168.0.0/16 
iptables -t nat -A V2RAY -p tcp -j RETURN -m mark --mark 0xff # 直连 SO_MARK 为 0xff 的流量(0xff 是 16 进制数，数值上等同与上面配置的 255)，此规则目的是避免代理本机(网关)流量出现回环问题
iptables -t nat -A V2RAY -p tcp -j REDIRECT --to-ports 12345 # 其余流量转发到 12345 端口（即 V2Ray）
iptables -t nat -A PREROUTING -p tcp -j V2RAY # 对局域网其他设备进行透明代理
// iptables -t nat -A OUTPUT -p tcp -j V2RAY # 对本机进行透明代理
// iptables prerouting 可视进入系统的就送上 v2ray
// iptables output 可视由系统发出的的就送上 v2ray, 所以我给output remark起, 视你个人要求再自行决定
```

ip rule add fwmark 1 table 100
ip route add local 0.0.0.0/0 dev lo table 100
iptables -t mangle -N V2RAY_MASK
iptables -t mangle -A V2RAY_MASK -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A V2RAY_MASK -p udp -j TPROXY --on-port 12345 --tproxy-mark 1
iptables -t mangle -A PREROUTING -p udp -j V2RAY_MASK

在config.json加入dokodemo,接收iptables送来的tcp,udp
```
        // dokodemo-door:12345
        {
            "tag": "tproxy-in",
            "protocol": "dokodemo-door",
            "port": 12345,
            "sniffing": {
                "enabled": true,
                "destOverride": ["http", "tls"]
            },
            "settings": {
                "network": "tcp,udp",
                "followRedirect": true
            }
        },
```

**Comment by fbion** [comment]
mark
