### ISSUE TITLE
关于Linux 能否使用PAC的问题

### ISSUE THREAD

**Issue by metaStor** [v2ray/discussion#602]
用的是linux-64的客户端,  貌似用./v2ray --config config.json 启动后,  访问国内的网站是与服务器同样的网速....
请问师傅们Linux客户端怎么使用PAC分流???
实现国内的网站自动不转发,  国外的自动转发。

**Comment by DolorHunter** [comment]
V2ray核心中没有 PAC. 但是可以使用 V2ray内的路由功能分流.

e.g.
```javascript
"routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": ["geosite:cn"] // 中国大陆主流网站的域名
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:cn", // 中国大陆的 IP
          "geoip:private" // 私有地址 IP，如路由器等
        ]
      }
    ]
  }
```
详细请参考 [国内直连 - 新白话](https://guide.v2fly.org/basics/routing/cndirect.html)

**Comment by iochen** [comment]
use **privoxy** or https://v2ray.com/chapter_02/03_routing.html
