### ISSUE TITLE
v2ray + nginx 400 bad request

### ISSUE THREAD

**Issue by soliujing** [v2ray/discussion#607]
always hit "400 bad request"

Client log:
`v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://1.2.3.4:8888/v2ray): 400 Bad Request > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
`

Server log:
no error log update

environment: 

Server

> v2ray/4.2.2.1
> nginx/1.16.1

Client v2rayU

> v2rayCore/4.2.2.1

Config
[srv-v2ray.txt](https://github.com/v2ray/discussion/files/4341632/srv-v2ray.txt)
[srv-nginx.txt](https://github.com/v2ray/discussion/files/4341633/srv-nginx.txt)
[client-v2rayU.txt](https://github.com/v2ray/discussion/files/4341634/client-v2rayU.txt)

**Comment by soliujing** [comment]
server IP changed to 1.2.3.4 :)

**Comment by soliujing** [comment]
TLS need to be configured on client. 
Issue resolved

**Comment by protocol-AMG** [comment]
@soliujing Hi, I'm seeing this exact issue, could you please elaborate how the client needs to be configured? e.g. I'm using Firefox, the TLS version lined up with my VPN server, are there anything else that I need to check, such as ssl_ciphers?

**Comment by protocol-AMG** [comment]
Resolved. I didn't configure v2ray client side TLS x_x
