### ISSUE TITLE
想请教下开全局代理，OBS推流twitch或者mixer依然失败的原因

### ISSUE THREAD

**Issue by nidongde10086** [v2ray/discussion#608]
不清楚细节所以不知道是哪部分有问题
v2ray不支持的原因？
客户端v2rayN不支持的原因？
OBS的原因？
订阅的服务商禁止的原因？

**Comment by DolorHunter** [comment]
v2rayN 的全局并不是完全的全局代理. 如果要完全代理还是在软件内手动配置代理到 127.0.0.1:1080 比较好. 但是 OBS 好像不能设置代理, 可以使用 proxifier, sstap 之类的工具创造全局环境.

**Comment by nidongde10086** [comment]
> 
> 
> v2rayN 的全局并不是完全的全局代理. 如果要完全代理还是在软件内手动配置代理到 127.0.0.1:1080 比较好. 但是 OBS 好像不能设置代理, 可以使用 proxifier, sstap 之类的工具创造全局环境.
懂了，之前有试过proxifier，不过可能没设置对最后没成功，以为方法失效了。刚才重新试了下已经没问题了，感谢

**Comment by laitianliu** [comment]
> > v2rayN 的全局并不是完全的全局代理. 如果要完全代理还是在软件内手动配置代理到 127.0.0.1:1080 比较好. 但是 OBS 好像不能设置代理, 可以使用 proxifier, sstap 之类的工具创造全局环境.
> 
> 懂了，之前有试过proxifier，不过可能没设置对最后没成功，以为方法失效了。刚才重新试了下已经没问题了，感谢

大佬，你这个具体怎么设置的，能参考一下吗？用proxifier？？？那V2rayN怎么办

**Comment by OG-C** [comment]
tun可以解决

**Comment by chesnokovdk** [comment]
Just for those who face this problem:
1. System Proxy -> Pac Mode 
2. Enable Tun -> Switch to Right
This allows you to pass all outside connections through VPN
(my problem was ping google.com + unreachable telegram API)
