### ISSUE TITLE
[Feature Request] 为啥不整合些别的mux呢?

### ISSUE THREAD

**Issue by k79e** [v2ray/discussion#614]
现在的mux吧 就是个测试版 功能都没做好.
bug一大堆 不是变卡 就是无限打流量 我的天哪 不如自带的mux没完善之前
整合几个更成熟的 已有的mux模块不就行了!!!

**Comment by kslr** [comment]
有人做就有，没人做就没有

**Comment by liberal-boy** [comment]
现在 h2 已经比较普及了，传输层做 mux 不是太必要

**Comment by netroby** [comment]
mux 其实还好,套路差不多.   做是有人做,但是测试不够, 用户接不接受,这是个问题. 

mux 在延时高,带宽低的情况下,表现恶劣.
