### ISSUE TITLE
小白请教，为什么一直在连接google？

### ISSUE THREAD

**Issue by JiangyouTester** [v2ray/discussion#616]
看到日志里，有非常多这样的记录：
`2020/03/23 09:55:36 tcp:127.0.0.1:60603 accepted tcp:clients4.google.com:443 [proxy] 
2020/03/23 09:57:21 tcp:127.0.0.1:60653 accepted tcp:play.google.com:443 [proxy] 
2020/03/23 09:57:35 tcp:127.0.0.1:60658 accepted tcp:www.googleapis.com:443 [proxy] 
2020/03/23 09:57:35 tcp:127.0.0.1:60661 accepted tcp:passwordsleakcheck-pa.googleapis.com:443 [proxy] 
2020/03/23 09:57:39 tcp:127.0.0.1:60663 accepted tcp:mail.google.com:443 [proxy] 
2020/03/23 09:57:39 tcp:127.0.0.1:60666 accepted tcp:signaler-pa.clients6.google.com:443 [proxy] 
2020/03/23 09:58:26 tcp:127.0.0.1:60672 accepted tcp:ci3.googleusercontent.com:443 [proxy] 
2020/03/23 09:58:28 tcp:127.0.0.1:60675 accepted tcp:www.google.com:443 [proxy] 
2020/03/23 09:58:28 tcp:127.0.0.1:60676 accepted tcp:www.gstatic.com:443 [proxy] 
2020/03/23 09:58:48 tcp:127.0.0.1:60679 accepted tcp:mtalk.google.com:5228 [proxy] `

这是为什么呢？
另外，连接不上google学术（因为频繁访问被ban），是不是跟这个有关？

**Comment by huashaoli** [comment]
这是正常的，我的也是一样，如果你在linux下用其它的代理工具在输出中一样可见类似的信息。
Google有极多的子域名，在访问单一网页中也会有很多的子域名出现。
倒是Google有时验证我不是机器人。

**Comment by JiangyouTester** [comment]
> 这是正常的，我的也是一样，如果你在linux下用其它的代理工具在输出中一样可见类似的信息。
> Google有极多的子域名，在访问单一网页中也会有很多的子域名出现。
> 倒是Google有时验证我不是机器人。

谢谢解答！我就是单纯的好奇，并不是judge。好奇这么连接的作用是什么？检测网络是否是连通的？
