### ISSUE TITLE
安装脚本运行偶尔会出错

### ISSUE THREAD

**Issue by FrtHone** [v2ray/discussion#617]
使用安装脚本更新程序时大部分时候都能成功，但有些时候会出错。
根据报错的内容，是下载zip失败。我自己试着排查了下，觉得问题可能在getVersion这个函数的这一行：
`        NEW_VER="$(normalizeVersion "$(curl ${PROXY} -s "${TAG_URL}" --connect-timeout 10| grep 'tag_name' | cut -d\" -f4)")"`

运行的时候，实际执行的是这条命令：
`curl -s --connect-timeout 10 https://api.github.com/repos/v2ray/v2ray-core/releases/latest | grep 'tag_name' | cut -d \" -f4`

对于 https://api.github.com/repos/v2ray/v2ray-core/releases/latest 请求的结果，通常都是会分行的，这样一来就可以用grep提取版本号所在的那行，然后cut出版本号。但是有时候请求链接的回复会只有一行，会导致grep无法提取出正确的版本号所在的那一行，导致获取到的最新的版本号不对，进而下载出错

附件里的两个文件分别是我这边脚本运行成功和失败的bash -x的输出，可能会有点帮助
[fail_out.txt](https://github.com/v2ray/discussion/files/4376232/fail_out.txt)
[success_out.txt](https://github.com/v2ray/discussion/files/4376235/success_out.txt)

**Comment by kslr** [comment]
你的环境是什么

**Comment by FrtHone** [comment]
> 你的环境是什么

Debian 10, 内核4.19.0-8-amd64

curl
```
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

**Comment by kslr** [comment]
你可以看下320行左右，大概，我记得哪里有一个

**Comment by FrtHone** [comment]
@kslr 抱歉没太懂您的意思，是说在脚本那边已经做了相应的应对这种获取到的请求只有一行的情况的措施，需要某个参数开启的意思不？

**Comment by kslr** [comment]
fix @2374
