### ISSUE TITLE
请问service v2ray reload还有这指令吗?

### ISSUE THREAD

**Issue by kingwilliam** [v2ray/discussion#618]
因service v2ray start|stop|restart|status 都可以, 就是reload出error

~# service v2ray reload
v2ray: unrecognized service

补充:我是用 ubuntu 18.04 LTS

**Comment by kslr** [comment]
现在都是systemd server这种还能用吗

**Comment by kingwilliam** [comment]
但systemctl reload v2ray 情况也一样, restart正常, reload error

~# systemctl reload v2ray
Failed to reload v2ray.service: Job type reload is not applicable for unit v2ray.service.
See system logs and 'systemctl status v2ray.service' for details.

~# systemctl restart v2ray
~#

**Comment by iochen** [comment]
> 但systemctl reload v2ray 情况也一样, restart正常, reload error
> 
> ~# systemctl reload v2ray
> Failed to reload v2ray.service: Job type reload is not applicable for unit v2ray.service.
> See system logs and 'systemctl status v2ray.service' for details.
> 
> ~# systemctl restart v2ray
> ~#

---
support restart only
> Job type reload is not applicable for unit v2ray.service

**Comment by kingwilliam** [comment]
明白, 谢谢!

只因在 "project V - 下载安装- Linux 安装脚本" 有这一文
https://www.v2ray.com/chapter_00/install.html

可以使用 service v2ray start|stop|status|reload|restart|force-reload 控制 V2Ray 的运行。

所以才问.
