### ISSUE TITLE
Browser can access google, but ping google with cmd window does not work

### ISSUE THREAD

**Issue by laitianliu** [v2ray/discussion#622]
Browser can access google, but ping or curl  google with cmd window does not work

The proxy protocol I use is: WebSocket + TSL
Does this protocol only support browser access? Does this proxy method support the application of B / S structure?
What's wrong with TCP proxy
Hope for the answer

**Comment by kslr** [comment]
You need to use a proxy for the terminal

**Comment by laitianliu** [comment]
@kslr The agent mode I use is global mode, not PAC mode. Shouldn't the whole system have agents.Does this global proxy mean to proxy all web addresses accessed by browsers? Is there any way to perform system level proxy。Is there any problem with the client I use? The client I use is v2raynThank you very much for your help！！！
client :
![image](https://user-images.githubusercontent.com/24669671/77770475-442ac580-7080-11ea-90a7-65b82a8aa3a4.png)

terminal ping does not work
![image](https://user-images.githubusercontent.com/24669671/77769042-48ee7a00-707e-11ea-864c-833b059e071c.png)
server config:
![image](https://user-images.githubusercontent.com/24669671/77769278-936ff680-707e-11ea-908d-d584422bb9ef.png)
Visit Google:
![image](https://user-images.githubusercontent.com/24669671/77769888-6b34c780-707f-11ea-820e-70b4bb6a569d.png)

**Comment by kslr** [comment]
Use transparent proxy

**Comment by fbion** [comment]
ping个锤子
vpn才能ping
v2ray只能代理tcp udp
icmp不行

**Comment by DolorHunter** [comment]
My solution: https://github.com/v2ray/discussion/issues/608

**Comment by laitianliu** [comment]
> ping个锤子
> vpn才能ping
> v2ray只能代理tcp udp
> icmp不行

@fbion 问题是我想解决有时候某些客户端应用加载一些最新依赖包速度特别慢甚至不能获取，如果只能用浏览器，没有用。现在curl命令也不行啊？wget也不行，因为解析出来的地址是被qiang的ip。

**Comment by kslr** [comment]
这些取决于应用设计及是否读取环境变量。
（ windows 等有缘人回答

**Comment by fbion** [comment]
> > ping个锤子
> > vpn才能ping
> > v2ray只能代理tcp udp
> > icmp不行
> 
> @fbion 问题是我想解决有时候某些客户端应用加载一些最新依赖包速度特别慢甚至不能获取，如果只能用浏览器，没有用。现在curl命令也不行啊？wget也不行，因为解析出来的地址是被qiang的ip。

proxifier.com

**Comment by laitianliu** [comment]
@kslr openwrt 能用吗？
![image](https://user-images.githubusercontent.com/24669671/78543732-ae372d80-782b-11ea-9bae-d5c9a40189dd.png)
测试联通了，ping google 不通

**Comment by kslr** [comment]
你要问这个作者

**Comment by chuc2rk** [comment]
> @kslr openwrt 能用吗？ ![image](https://user-images.githubusercontent.com/24669671/78543732-ae372d80-782b-11ea-9bae-d5c9a40189dd.png) 测试联通了，ping google 不通

Do you fix this problem? I have the same issue, can not ping goole.com so mwan3 on openwrt not work.

**Comment by chesnokovdk** [comment]
Just for those who faces this problem:

System Proxy -> Pac Mode (at the bottom of application)
Enable Tun -> Switch to Right (at the bottom of application)
This allows you to pass all outside connections through VPN
(my problem was ping google.com + unreachable telegram API)

**Comment by DimuthuAro** [comment]
> Just for those who face this problem:
> 
> System Proxy -> Pac Mode (at the bottom of application) Enable Tun -> Switch to Right (at the bottom of application) This allows you to pass all outside connections through VPN (my problem was ping google.com + unreachable telegram API)

Thanks That Just Solved The Problem
CMD Ping google.com command Returned Reply from 142.251.10.138: bytes=32 time<1ms TTL=64 
again
Thanks
