### ISSUE TITLE
目前v2ray的代码有严格审核吗？有没有可能被植入后门？

### ISSUE THREAD

**Issue by woshiniming007** [v2ray/discussion#626]
从4.18.1版本开始，原作者消失，同时大量网友的commit被merge进来，已经有几百次commit，请问在merge的时候有进行严格的代码审计吗？
众所周知，NSA在大量的开源软件包括linux内核中都偷偷渗透了后门代码，不难想v2ray会不会也被zf植入后门，比如加入可检测特征与缓冲区溢出漏洞，使得在针对关键人物的审查时可被利用。

**Comment by yomnxkcs** [comment]
没有严格审核。有可能有后门。“关键人物”不建议使用。用v2ray看人玩泥巴，搭房子就好。

linux内核都有后门了，其他软件安不安全都不重要了。

**Comment by okudayukiko** [comment]
用gpg数字签名可以部分解决问题。

**Comment by kslr** [comment]
这是一个无法解决的问题，幸运的是所有人都可以看到记录。

**Comment by 0CrazyGuy9** [comment]
开源是民主式软件，大家一起看着的，没这么容易后门

**Comment by 0CrazyGuy9** [comment]
独裁的软件，没人监督，你想看后门也没办法看

**Comment by netroby** [comment]
如果需要一个没有后门的软件, 可以考虑,folk自己的分支,阉割掉一些功能组件,只保留你自己真正需要的功能模块,并且你自己来维护自己的代码仓库, 所有有问题的,要么改写,要么去掉重写. 这样能控制代码的纯洁性.

**Comment by whatsappfree** [comment]
这个软件有些代码没有开源

**Comment by kslr** [comment]
> 这个软件有些代码没有开源

请给出回复，否则我会设为虚假消息
