### ISSUE TITLE
获取订阅内容时报错：订阅内容解码失败(非BASE64码)

### ISSUE THREAD

**Issue by Xiao-tangyuan** [v2ray/discussion#636]
日志：
System.Exception: v2rayN start up
请大神帮忙看看。
另外release中的v2rayN和v2rayN-Core都下载不了，怎么办呢？

**Comment by Xiao-tangyuan** [comment]
能否麻烦帮我看一下为什么解码失败吗？

**Comment by Xiao-tangyuan** [comment]
获取到的新日志：
System.Exception: v2rayN start up

 
--------------------------------info[21:34:47]--------------------------------
System.Exception: Webserver prefixes http://*:10810/pac/

 
--------------------------------拒绝访问。[21:34:47]--------------------------------
System.Net.HttpListenerException (0x80004005): 拒绝访问。
   在 System.Net.HttpListener.AddAllPrefixes()
   在 System.Net.HttpListener.Start()
   在 v2rayN.Base.HttpWebServer..ctor(String[] prefixes, Func`2 method)

 
--------------------------------info[21:34:47]--------------------------------
System.Exception: Webserver InitServer 拒绝访问。

**Comment by kslr** [comment]
大概要用管理员运行
