### ISSUE TITLE
关于解析器和json的个人建议

### ISSUE THREAD

**Issue by comwrg** [v2ray/discussion#64]
### 第一个问题, 报错信息太少
今天尝试手写配置文件,完全靠文档和v2ray的`-test`

但是报错信息完全摸不到头脑

比如这样的报错信息
```
❯ v2ray -test config.json
V2Ray 4.3 (Po) 20181109
A unified platform for anti-censorship.
main: failed to read config file: /usr/local/etc/v2ray/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/ext/tools/conf/command: failed to parse json config > v2ray.com/ext/tools/conf/serial: failed to read config file > invalid character ':' after array element
```

个人觉得报错至少应该报第几行第几列,
因为不清楚第几行的错, 然后只能慢慢手动排除, 就比较麻烦

### 第二个问题, 关于一些不能解析的字段, 解析器跳过问题
对于一些不能解析的字段的, 解析器貌似是直接跳过了(推测, 没有看源码)
因为我有地方写字段写错位置了(一开始对文档理解有误, 或者是失误), 但是配置文件可以正常运行, 但是那些字段并不属于那里
个人觉得应该输出warning信息, 或者是报错

### 第三个问题 关于json最后一项的逗号问题
关于json的逗号问题, 按规定json最后一项的逗号是不能写上去的, 但是修改或是删除或是粘贴哪一项的时候, 逗号就可能会需要加上或者是删除, 非常的麻烦, 特别是可能需要调试配置文件的时候, 需要频繁的修改配置文件

个人觉得有两种选择
1. 修改json的语法,对最后一项的逗号支持可有可无
2. 不修改json的语法, 解析器检测最后一项的逗号, 如发现最后一项有多余的逗号, 可以删除后重新写入配置文件

**Comment by nobody3u** [comment]
一、三还是由core项目组来回复吧。
至于二，千万不要这么改啊，我很需要这个功能啊。

**Comment by young-zy** [comment]
关于2，理论上在运行（或者转换为其他配置文件）时配置直接访问键所对应的值，访问不存在的键必然报错（除非是可空），但对冗余对象不会有访问，所以不会有检查。

**Comment by comwrg** [comment]
> 关于2，理论上在运行（或者转换为其他配置文件）时配置直接访问键所对应的值，访问不存在的键必然报错（除非是可空），但对冗余对象不会有访问，所以不会有检查。

嗯, 我看了源码, json解析是用的golang官方的库, 如果想要实现冗余对象warning的话, 不太好实现


不过个人认为就是冗余对象warning的话还是比较好, 毕竟v2ray的配置太强大, 如果个人有比较稍复杂的要求的话, 便只能手写配置文件, 但是手写如果将配置项写错位置的话, 排查就不是很容易排出来

**Comment by comwrg** [comment]
> 一、三还是由core项目组来回复吧。
> 至于二，千万不要这么改啊，我很需要这个功能啊。

warning可以吗, 不清楚你具体是什么特殊要求

**Comment by hlx98007** [comment]
1的话一般都是json错误，找个jsonlint网站测一下很直观的。用jq也可以找到错误所在的附近位置。

**Comment by xyli09** [comment]
config.json > Main|Json: failed to execute v2ctl to convert config file. > Command|Platform|CtlCmd: failed to execute v2ctl: Ext|Tools|Conf|Command: failed to parse json config > Ext|Tools|Conf|Serial: failed to read config file > json: cannot unmarshal array into Go struct field Config.inbound of type conf.InboundConnectionConfig

 > exit status 4294967295

**Comment by hlx98007** [comment]
`inbound`是旧写法，新写法是`inbounds`。由于要兼容新旧两个格式所以`inbound`的行为不能改变啊

**Comment by comwrg** [comment]
了解, 感谢~
