### ISSUE TITLE
下载v2ray-core代码本地运行时遇到一个bazel的问题

### ISSUE THREAD

**Issue by 15652768278** [v2ray/discussion#641]
RT
下载了项目，想学习一下，本地编译运行，使用手工构筑是没问题的。
使用bazel自动构筑，貌似对gomod方式并不支持，看报错信息还是老式的GOPATH。
使用的指令为官方文档中的：
`bazel build --action_env=GOPATH=$GOPATH --action_env=PATH=$PATH //release:v2ray_linux_amd64_package
`
报错信息如下：
`
bazel build --action_env=GOPATH=$GOPATH --action_env=PATH=$PATH //release:v2ray_linux_amd64_package --sandbox_debug
INFO: Analyzed target //release:v2ray_linux_amd64_package (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/like/go/v2ray-core/main/BUILD:8:1: error executing shell command: '/bin/bash -c CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOROOT_FINAL=/go GOCACHE=${TMPDIR}/gocache go build -o bazel-out/darwin-fastbuild/bin/main/linux/amd64/v2ray -compiler gc -gcflags "all=-trimpath=...' failed (Exit 1) sandbox-exec failed: error executing command 
  (cd /private/var/tmp/_bazel_like/3fb6526acb2dbfccbb550dac7e0142b7/sandbox/darwin-sandbox/18/execroot/v2ray_core && \
  exec env - \
    GOPATH=/Users/like/go \
    PATH=/usr/local/Cellar/go/1.14.1/libexec/bin:/Users/like/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mongodb/bin:/usr/local/go/bin:/Users/like/go/bin:/Users/like/go/bin \
    TMPDIR=/var/folders/k4/1klnq0_n5wb59vt8w9bry11r0000gn/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_like/3fb6526acb2dbfccbb550dac7e0142b7/sandbox/darwin-sandbox/18/sandbox.sb /var/tmp/_bazel_like/install/d0c2127c621434da49af5a447f30323e/process-wrapper '--timeout=0' '--kill_delay=15' /bin/bash -c 'CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOROOT_FINAL=/go GOCACHE=${TMPDIR}/gocache go build -o bazel-out/darwin-fastbuild/bin/main/linux/amd64/v2ray -compiler gc -gcflags "all=-trimpath=${GOPATH}/src" -asmflags "all=-trimpath=${GOPATH}/src" -ldflags '\''-s -w'\'' -tags '\'''\'' v2ray.com/core/main')
can't load package: package v2ray.com/core/main: cannot find package "v2ray.com/core/main" in any of:
        /usr/local/Cellar/go/1.14.1/libexec/src/v2ray.com/core/main (from $GOROOT)
        /Users/like/go/src/v2ray.com/core/main (from $GOPATH)
Target //release:v2ray_linux_amd64_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.380s, Critical Path: 0.14s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
`
请教一下，是否可以通过参数解决，还是bazel的构建方式暂时支持GOPATH？

**Comment by kslr** [comment]
```shell
bazel build --action_env=GOPATH=$GOPATH --action_env=PATH=$PATH --action_env=GPG_PASS=${SIGN_KEY_PASS} --action_env=SPWD=$PWD --action_env=GOCACHE=$(go env GOCACHE) --spawn_strategy local //release:all
```
