### ISSUE TITLE
使用CentOS7做透明代理，国内网站正常，不能访问国外网站（google.com、youtube.com）

### ISSUE THREAD

**Issue by 0CrazyGuy9** [v2ray/discussion#643]
我是参考了：https://toutyrater.github.io/app/tproxy.html 这里进行了配置，系统是CentOS7

透明代理机器（旁路由）：192.168.33.201，根据贵方提供的文档进行了配置，192.168.33.201这台网关可以访问国外网站（google.com、youtube.com），但同一局域网里边的192.168.33.88机器（使用192.168.33.201）网关和DNS，访问国内网站正常，但是google.com、youtube.com不正常了，完全没有跑192.168.33.201进行转发

知道的朋友指点一下这是怎么回事？

**Comment by 0CrazyGuy9** [comment]
搞了一天，重复换了多次环境，还是一样，LEDE这个系统也试过，同样情况。我就是想作为透明网关，然后让电视可以开YOUTUBE，但失败告终...，请问我什么地方做得不对了。参与官方文档，除了IP和VPS用自己的数据，其他与官方一样

**Comment by dctxmei** [comment]
請確認一下是否類似於 https://github.com/v2ray/v2ray-core/issues/2402 的情況。

**Comment by dawncold** [comment]
没开ip forward？信息太少

**Comment by cnhap** [comment]
最后搞定了吗，我最近在学 也遇到了 这个问题。

**Comment by 0CrazyGuy9** [comment]
搞定了，现在怎么配置都可以
1、调试监控日志，看哪一步出问题
2、是规则和通不通问题

cnhap ***@***.***> 于2023年8月21日周一 23:30写道：
