### ISSUE TITLE
fail to connection with ws-tls-nginx

### ISSUE THREAD

**Issue by greenhand136** [v2ray/discussion#644]
Hello,

I want to config with ws-tls-nginx but failed.
And the version without ws-tls-nginx works fine on my VPS. I have tried several templates of configuration but none worked. 

Would you please help to take a check? Thank you in advance.

**Comment by greenhand136** [comment]
@kslr 请大神有空帮忙看一下，谢谢

**Comment by greenhand136** [comment]
[v2ray.txt](https://github.com/v2ray/discussion/files/4469128/v2ray.txt)
[client-errorlog.txt](https://github.com/v2ray/discussion/files/4469129/client-errorlog.txt)

**Comment by dctxmei** [comment]
既然通過 Nginx 反向代理了，在客戶端，V2Ray 的 `outbounds` 部分，應當是 `"port": 443` 才對。

**Comment by greenhand136** [comment]
2020/04/13 21:00:03 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  D:\Python\Downloads\v2rayN-Core\config.json
2020/04/13 21:00:03 [Warning] v2ray.com/core: V2Ray 4.23.1 started
2020/04/13 21:00:25 tcp:127.0.0.1:63980 accepted tcp:google.com:80 [proxy] 
2020/04/13 21:01:12 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.xxx.com:26036/normal/):  > dial tcp xxx.xxx.xxx.xxx:26036: connectex: No connection could be made because the target machine actively refused it. v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.xxx.com:26036/normal/):  > dial tcp xxx.xxx.xxx.xxx:26036: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.xxx.com:26036/normal/):  > dial tcp xxx.xxx.xxx.xxx:26036: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.xxx.com:26036/normal/):  > dial tcp xxx.xxx.xxx.xxx:26036: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by greenhand136** [comment]
@dctxmei, thank you.
但是修改之后，尝试链接google.com,仍无法成功，且在显示上面的错误日志。请帮忙再看一下，谢谢

**Comment by dctxmei** [comment]
該 Log 的內容，顯示的是 `:26036` 呀，你是不是修改錯位置了？

**Comment by i553041** [comment]
> @dctxmei, thank you.
> 但是修改之后，尝试链接google.com,仍无法成功，且在显示上面的错误日志。请帮忙再看一下，谢谢

你的客戶端是電腦用嗎？你照我這個客戶端設置試試吧，我現在這個在Mac的v2rayU裡是正常使用的：

(留意proxy端口及我打xxxx的地方填回你自己的。)

{
  "log": {
    "error": "",
    "loglevel": "none",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": false,
        "auth": "noauth"
      },
      "port": "1080"
    },
    {
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "timeout": 360
      },
      "port": "1087"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "wsSettings": {
          "path": "/xxxxx",
          "headers": {
            "host": ""
          }
        },
        "tlsSettings": {
          "allowInsecure": false
        },
        "security": "tls",
        "network": "ws"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "xx.xxxxx.com",
            "users": [
              {
                "id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
                "alterId": 64,
                "level": 0,
                "security": "none"
              }
            ],
            "port": 443
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "AsIs",
        "redirect": "",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "dns": {
    "hosts": null,
    "servers": [
      "https://1.0.0.1/dns-query",
      "https://1.1.1.1/dns-query"
    ]
  },
  "routing": {
    "settings": {
      "domainStrategy": "AsIs",
      "rules": []
    }
  },
  "transport": {}
}

**Comment by greenhand136** [comment]
我的客户端是V2rayN-V3.14

**Comment by i553041** [comment]
> 我的客户端是V2rayN-V3.14

上面的配置不能用在V2rayN嗎？

**Comment by greenhand136** [comment]
可以，成功了，多谢

**Comment by greenhand136** [comment]
多谢你们的耐心和支持，另外，目前我只是读了一下官网的介绍，如果想进一步学习各个功能配置，请问是否有推荐的参考资料？谢谢。

**Comment by greenhand136** [comment]
BTW, 当我使用systemctl status nginx 查看状态的时候，虽然显示的是active(running)，但在详细信息中
Apr 12 15:03:02 hwsrv-xxxxx.hostwindsdns.com systemd[1]: Starting A high performance web server and a reverse proxy server...
Apr 12 15:03:02 hwsrv-xxxxx.hostwindsdns.com nginx[1396]: nginx: [warn] conflicting server name "www.xxxx.com" on 0.0.0.0:443, ignored
Apr 12 15:03:02 hwsrv-xxxxx.hostwindsdns.com nginx[1396]: nginx: [warn] conflicting server name "www.xxxx.com" on [::]:443, ignored
Apr 12 15:03:02 hwsrv-xxxxx.hostwindsdns.com nginx[1410]: nginx: [warn] conflicting server name "www.xxxx.com" on 0.0.0.0:443, ignored
Apr 12 15:03:02 hwsrv-xxxxx.hostwindsdns.com nginx[1410]: nginx: [warn] conflicting server name "www.xxxx.com" on [::]:443, ignored
Apr 12 15:03:02 hwsrv-xxxxx.hostwindsdns.com systemd[1]: nginx.service: Failed to parse PID from file /run/nginx.pid: Invalid argument
Apr 12 15:03:02 hwsrv-xxxxx.hostwindsdns.com systemd[1]: Started A high performance web server and a reverse proxy server.

**Comment by i553041** [comment]
> BTW, 当我使用systemctl status nginx 查看状态的时候，虽然显示的是active(running)，但在详细信息中
> Apr 12 15:03:02 hwsrv-xxxxx.hostwindsdns.com systemd[1]: Starting A high performance web server and a reverse proxy server...
> Apr 12 15:03:02 hwsrv-xxxxx.hostwindsdns.com nginx[1396]: nginx: [warn] conflicting server name "www.xxxx.com" on 0.0.0.0:443, ignored
> Apr 12 15:03:02 hwsrv-xxxxx.hostwindsdns.com nginx[1396]: nginx: [warn] conflicting server name "www.xxxx.com" on [::]:443, ignored
> Apr 12 15:03:02 hwsrv-xxxxx.hostwindsdns.com nginx[1410]: nginx: [warn] conflicting server name "www.xxxx.com" on 0.0.0.0:443, ignored
> Apr 12 15:03:02 hwsrv-xxxxx.hostwindsdns.com nginx[1410]: nginx: [warn] conflicting server name "www.xxxx.com" on [::]:443, ignored
> Apr 12 15:03:02 hwsrv-xxxxx.hostwindsdns.com systemd[1]: nginx.service: Failed to parse PID from file /run/nginx.pid: Invalid argument
> Apr 12 15:03:02 hwsrv-xxxxx.hostwindsdns.com systemd[1]: Started A high performance web server and a reverse proxy server.

你nginx有兩個或以上的virtual host，例如www.abc.com / www1.abc.com，但你兩個virtualhost的設定檔，servername都設為www.abc.com，那就會出現上面衝突的錯誤了。

 server_name www.abc.com;

另一台virtualhost的設定檔要設為

 server_name www1.abc.com;

**Comment by greenhand136** [comment]
不太清楚这个错误是否会有很大影响？另外，我也尝试搜索关于这个错误的解决方案：
https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/1581864
但是 printf "[Service]\nExecStartPost=/bin/sleep 0.1\n" > /etc/systemd/system/nginx.service.d/override.conf
这个命令之后，提示permission denied 对/etc/systemd/system/nginx.service.d
尝试修改permission，也解决不了。

**Comment by i553041** [comment]
> 多谢你们的耐心和支持，另外，目前我只是读了一下官网的介绍，如果想进一步学习各个功能配置，请问是否有推荐的参考资料？谢谢。

其實官網是最詳盡了，另外，多些上來這裡看看高手對用家疑難上的解答可以學到很多東西，(因為涉及到很多配置上的範例，可以作為參考)。

**Comment by dctxmei** [comment]
你的 Nginx 配置其實相當糟糕，雖然不影響你的需求就是了。

你使用的是 Ubuntu，那就建議查閱 Ubuntu 的 Wiki。

我個人主要使用 FreeBSD / OpenBSD 和 Debian，皆是參考其相應的 Wiki，和 Nginx 官方的 Wiki 互相對比，來進行配置的。

比如，以 Debian 為例，首先需要查閱的就是：
https://wiki.debian.org/Nginx/DirectoryStructure

因此，我是不會修改 `/etc/nginx/nginx.conf` 這個文件的，因為 Debian Wiki 已經告知更好的方案。

**Comment by greenhand136** [comment]
@i553041,
谢谢提示，have a good night.

**Comment by greenhand136** [comment]
@dctxmei,
谢谢，我会再查看Nginx官方Wiki再尝试优化一下。
