### ISSUE TITLE
透明代理UDP直连性能不好（zoom.us卡顿问题）

### ISSUE THREAD

**Issue by dawncold** [v2ray/discussion#646]
问题：我在使用Zoom.us时遇到听对方声音断断续续问题，时好时坏，关掉v2ray透明代理使用ss透明代理没有问题（不是说ss的好）。

没有详细调查，看到zoom官方给的防火墙/代理说明，用到的端口主要是tcp：8801-8802，udp：8801-8810，在v2ray透明代理网关上看了下当时用的是udp8801，而且目标地址是国内，策略用了直连（从日志中看到），就是断断续续。

后来在iptables中加入规则，这些端口的udp流量不再进入v2ray，问题就解决了。

透明代理没啥特别配置，就是参考这里：https://guide.v2fly.org/app/tproxy.html

可能这类问题就应该这样解决？

**Comment by kslr** [comment]
你可以试试编译最新代码

**Comment by dawncold** [comment]
@kslr  试了下最新编译，比之前更差了？现在直接没有声音了（对方一直在说话，可以看到提示，但听不到），当添加上iptables规则后能听到，后来zoom断开过一次。

换回4.23.1后，再添加上iptables规则，一切正常了。

iptables规则：`iptables -t mangle -A V2RAY -p udp -m multiport --dport 3478,3479,8801:8810 -j RETURN`

**Comment by kslr** [comment]
这个问题先保留吧，近期大概会有一个udp加速工具合并进来

**Comment by yunfengwangluo** [comment]
@kslr   这个 udp 加速的 能解决 玩游戏  v2ray cpu占用高  游戏延迟严重的问题吗

**Comment by kslr** [comment]
> @kslr   这个 udp 加速的 能解决 玩游戏  v2ray cpu占用高  游戏延迟严重的问题吗

为了游戏加速设计 可以达到Nat A
而CPU和延迟则取决于很多因素

**Comment by dawncold** [comment]
试了下最新版，性能仍然不佳，只能暂时用iptables优化

**Comment by izaktan** [comment]
为什么shadowsocks不卡呢，而且我测试了一下，手机用v2ray也不是很卡，就是电脑特别卡
