### ISSUE TITLE
通过api删除用户一段时间有可能还可以使用

### ISSUE THREAD

**Issue by l42111996** [v2ray/discussion#647]
通过api删除用户一段时间有可能还可以使用，这个可能是什么问题？

**Comment by CalmLong** [comment]
>删除用户后，并不会“立刻生效”，需要等几分钟；现在 Core 的代码实现中，删除用户操作仅仅是把用户从用户列表中移除，但没有把对应的 auth session 移除，这样的话就需要等这些 session 超时后，这个用户才会无法认证


https://medium.com/@TachyonDevel/%E8%B0%83%E7%94%A8-v2ray-%E6%8F%90%E4%BE%9B%E7%9A%84-api-%E6%8E%A5%E5%8F%A3%E8%BF%9B%E8%A1%8C%E7%94%A8%E6%88%B7%E5%A2%9E%E5%88%A0%E6%93%8D%E4%BD%9C-adf9ff972973

**Comment by l42111996** [comment]
现在测试是这样子的，我看看怎么修改，感谢回复
