### ISSUE TITLE
科学上网选择什么PC宽带？

### ISSUE THREAD

**Issue by okudayukiko** [v2ray/discussion#648]
小区的共享电信网络，跑Speedtest下载速度只有16Mbps。
选择中国电信，中国移动还是中国联通？中国移动最便宜。

**Comment by fbion** [comment]
china unicom

**Comment by CalmLong** [comment]
忽略服务器网络质量的话，联通和电信都可以。

**Comment by okudayukiko** [comment]
> 忽略服务器网络质量的话，联通和电信都可以。

觉得中国移动最便宜，但似乎中国移动对科学上网屏蔽也最多？

**Comment by CalmLong** [comment]
> 觉得中国移动最便宜，

我并不觉得移动有多便宜，我们这边使用移动的网络必须要绑定移动的手机号码且有固定消费，也可以理解为“充话费送宽带”，这样一年得一千多，虽然对我个人而言是不合适的，况且移动手机流量资费也是非常贵

> 但似乎中国移动对科学上网屏蔽也最多

移动是墙中墙这点毋庸置疑，我们公司用的就是移动的固定IP的宽带，之前电子商务那边有招标的网站打不开，但是用手机流量就可以打开，后来给运营商反应这个情况，他们来了之后试了试，然后把网址记下来了说是要上报，让我们等等；看吧，一个正规的招标网站都要上报。搞不懂这是什么操作。

> 另外科学上网该用什么4G？

和电脑网络一样，手机要是不经常科学上网用哪家都无所谓

> 小区的网络是NAT的

我这边山东联通是可以打10010要来公网 IP 的，已亲测，现在中转 TG 很舒服。

> 下载BT基本没速度，必须用迅雷会员

这个和科学上网没关系。没速度 Github 上有 Bt Tracker，换上速度就快了，冷门资源无解。

关于宽带绑卡的问题，这个每个地区的制度都是不一样的，我们这里的联通可以不绑卡，但是电信必须绑卡，且卡不能销户

农村的话比较好办些，通常三家可以任选。城市小区的话需要看小区内可以安装哪家的。

总结，电信或联通都行，不要用移动就好了，不然你用再好的机房都没用

**Comment by CalmLong** [comment]
我个人现在手机联通卡，家里也是联通宽带，公司是移动的网络。后来把小老板成功带入FQ的坑，然后在公司里安装了一条家用联通宽带，用来专门FQ，哈哈哈

**Comment by kslr** [comment]
我个人的意见是，如果可以氪金就买电信，不能就买联通。
