### ISSUE TITLE
求助：PC端连接正常但无法上网

### ISSUE THREAD

**Issue by DarkEyeFindBright** [v2ray/discussion#650]
同样的服务器在手机端（Android）正常使用，但是在PC端（Windows10）连接成功后无法上外网，同时信息栏也有一些有效的TCP连接信息。很奇怪为什么用不了，求高人解答。我怀疑是PC网络配置的问题，但是也不知道怎么修改

**Comment by okudayukiko** [comment]
要修改浏览器的代理配置。

**Comment by DarkEyeFindBright** [comment]
我是用的chrome，我用edge试了一下，正常访问外网，chrome就怎么都不行。chrome也是调用了IE的代理，就很怪

**Comment by DolorHunter** [comment]
检查 Chrome 设置中的代理(proxy)是否有正常设置 Socks 代理或系统代理. Chrome 默认不使用代理.

**Comment by DarkEyeFindBright** [comment]
chrome没有单独的代理，只能调用ie代理（系统代理）

**Comment by okudayukiko** [comment]
Chrome会调用IE的Proxy Settings。建议用HTTP Proxy。

**Comment by foxwong** [comment]
5
