### ISSUE TITLE
关于v2ray的客户端前置代理HTTP：客户端config.json采用链式转发配置遇到疑似proxySettings 与 streamSettings冲突

### ISSUE THREAD

**Issue by youngerliyg** [v2ray/discussion#651]
1) 你正在使用哪个版本的 V2Ray？
V2Ray 4.23.1

2) 你的使用场景是什么？
客户端：WIN10，使用Firefox，运行V2RAYN，进行科学上网。
服务器：WS+TLS+V2RAY 

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

由于公司网络还有一个强制HTTP代理（使用用户名和密码验证），所以在应用链式转发配置期望如下：WIN10 Firefox -> 客户端V2RAYN -> HTTP 代理 ------((( INTERNET )))------> V2RAY 服务器 ->GOOGLE or YOUTUBE.

客户端应用链式转发后客户端总是说TIMEOUT，访问外网失败（不仅GOOGLE访问不了，连国内网站度娘什么的也访问不了）。具体客户端V2RAYN的config.json在下文附上。
于此同时，如果在家庭环境（无需HTTP代理）V2RAYN客户端不用配置链式转发，访问国内国外网站正常。

4) 你期待看到的正确表现是怎样的？
期望V2RAY可以支持通过HTTP代理后访问V2RAY服务器。

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
客户端链式转发的配置是参考了如下配置指南，在V2RAYN原config.json基础上做了增加和修改：
    代理转发：https://toutyrater.github.io/advanced/outboundproxy.html
    HTTP协议格式：https://www.v2ray.com/chapter_02/protocols/http.html

  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "v2ray server IP address",
            "port": v2ray server port,
            "users": [
              {
                "id": "11111-22222-33333-44444-5555",
                "alterId": 64,
                "email": "abc@cde.fgh",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": "www.myowndomainname.com"
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/superlooooooooooooooooooooooongrandom_id",
          "headers": {
            "Host": "www.myowndomainname.com"
          }
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      },	  
	  "proxySettings": {
        "tag": "http_proxy" 
      }
    },
    {
	  "tag": "http_proxy",
      "protocol": "http",
      "settings": {
        "servers": [
		  {
			"address": "192.168.8.1",
			"port": 58888,
			"users": [
				{
					"user": "myusername",
					"pass": "mypassword"
				}
			]
		  }
		]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],

服务器端配置:
服务器端已经核实过，如果没有HTTP代理的情况下，直接用WIN10 Firefox ->V2RAYN -> V2RAY服务器是成功的。

在这篇文章中https://briteming.blogspot.com/2018/08/v2ray.html，看到“当我们使用 proxySettings 的时候，streamSettings 就失效了！这会导致我们不能使用ws，tls”。 不敢确定是不是这两者冲突，所以来讨论区请教一下大家。诚挚感谢！

**Comment by youngerliyg** [comment]
这个问题是参考了#1736才做的客户端链式代理的配置，无奈还是不工作。

**Comment by youngerliyg** [comment]
通过参考高人大侠的解说，怀疑真的是有这个冲突：proxySettings 和 streamSettings有冲突：
官方文档在出站协议里面明确写明了：
“proxySettings: ProxySettingsObject 出站代理配置。当出站代理生效时，此出站协议的streamSettings将不起作用。”
也就是说，除了非TLS、无HTTP伪装的TCP协议外，其他都是不行的。 
总之一句话，WS+TLS+V2RAY的场景下，是不能使用链式代理proxySettings的。
打算把这个问题提交到v2core 的issue区，看看开发组有没有大侠可以核实以及解决这个问题。 

1. 在这篇文章中https://briteming.blogspot.com/2018/08/v2ray.html，看到“当我们使用 proxySettings 的时候，streamSettings 就失效了！这会导致我们不能使用ws，tls”。 
2. 在这篇文章“https://ailitonia.com/archives/v2ray%E5%AE%8C%E5%85%A8%E9%85%8D%E7%BD%AE%E6%8C%87%E5%8D%97/comment-page-1/#outboundproxy” 的问答中也有这个话题的讨论。

**Comment by youngerliyg** [comment]
经过测试不加streamSettings的场景是可以用链式代理的，我把服务器测配置为基础V2RAY（不经TLS和WS的处理），在客户端（Ubuntu 18.04）如下配置时工作正常的：
			{
			  "policy": null,
			  "log": {
			    "access": "/var/log/v2ray/Vaccess.log",
			    "error": "/var/log/v2ray/Verror.log",
			    "loglevel": "debug"
			  },
			  "inbounds": [
			    {
			        "port": 1080,  // SOCKS 代理端口，在浏览器中需配置代理并指向这个端口
			        "listen": "127.0.0.1",
			        "protocol": "socks",
			        "settings": {
			          "udp": true
			        }
			    }
			  ],
			  "outbounds": [
			    {
			        "protocol": "vmess",
			        "settings": {
			            "vnext": [{
			                "address": "1.1.1.1", // 服务器地址，请修改为你自己的服务器 ip 或域名
			                "port": 65535,  // 服务器端口
			                "users": [{
			                    "id": "11111-22222-333333-444444-55555" }]
			                }]
			        },
			        "proxySettings":{
			            "tag": "http_proxy"
			        },
			        "tag": "v2ray_proxy"
			    },
			    {
			        "tag": "http_proxy",
			        "protocol": "http",
			        "settings":{
			            "servers":[{
			                    "address": "http proxy server IP",
			                    "port": 8080,
			                    "users":[{
			                        "user": "username",
			                        "pass": "password"
			                    }]
			            }]
			        }
			    },
			    {
			        "tag": "direct",
			        "protocol": "freedom",
			        "settings": {}
			    }
			  ],
			  "routing": {
			    "domainStrategy": "IPOnDemand",
			    "rules": [{
			      "type": "field",
			      "ip": ["geoip:private"],
			      "outboundTag": "direct"
			    }]
			  }
			}

**Comment by youngerliyg** [comment]
官方文档已经说明这二者冲突，所以参考了@phantomedc https://github.com/v2ray/v2ray-core/issues/1736 的思路，采用dokodemo-door配合routing解决了这个问题。
经过验证的客户端配置文件附上供参考。
```diff
 {
  "policy": null,
  "log": {
        "access": "/var/log/v2ray/Vaccess.log",
        "error": "/var/log/v2ray/Verror.log",
        "loglevel": "debug"#正常运行时改为error
  },
  "inbounds": [
    {
      "tag": "plain_data",
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "address": null,
        "clients": null
      },
      "streamSettings": null
    },
    {
        "tag": "dokodemo_door_data",
        "protocol": "dokodemo-door",
        "port": 8080,
        "listen": "127.0.0.1",
        "settings": {
            "address": "真实V2RAY服务器IP地址",
            "port": 真实V2RAY服务器端口号, 
            "network": "tcp,udp"
        }
    }
  ],
  "outbounds": [
    {
      "tag": "ws_tls_v2ray",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "127.0.0.1",
            "port": 8080,
            "users": [
              {
                "id": "11111111-222222222-333333-44444444-5555555555",
                "alterId": 0,
                "email": "testtesttest@testtesttest@test.test",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": "www.自己实际的域名.com"
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/verylooooooooooooooooooooooooooooooooooograndomid",
          "headers": {
            "Host": "www.自己实际的域名.com"
          }
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "tag": "http_proxy_with_usrpwd",
      "protocol": "http",
      "settings": {
        "servers": [
                  {
                        "address": "HTTP代理服务器IP地址",
                        "port": HTTP代理服务器端口号,
                        "users": [
                                {
                                    "user": "HTTP代理服务器用户名",
                                    "pass": "HTTP代理服务器密码"
                                }
                        ]
                  }
                ]
      }
    }
  ],
  "routing": {
    "domainStrategy": "rules",
    "rules": [
                {
            "type": "field",
            "inboundTag": ["plain_data"],
            "outboundTag": "ws_tls_v2ray"
        },
        {
            "type": "field",
            "inboundTag": ["dokodemo_door_data"],
            "outboundTag": "http_proxy_with_usrpwd"
        }
    ]
  }
}
```

**Comment by arrheni** [comment]
我找到一种无脑方法，利用proxifier，设置多个代理，前置代理端口比如8000甲，，然后v2ray代理端口10088乙。上google用乙端口，骚操作是，2ray或者xry程序要使用甲代理。测试通过。

**Comment by QGB** [comment]
@arrheni  
Linux上怎么办？ 用 https://github.com/Equim-chan/h2s 吗？

**Comment by QGB** [comment]
@arrheni  
Linux上怎么办？ 用 https://github.com/Equim-chan/h2s 吗？
