### ISSUE TITLE
现在用什么比较不容易被封ip？

### ISSUE THREAD

**Issue by l42111996** [v2ray/discussion#652]
现在用什么比较不容易被封ip？或者有什么好的方案吗？  
我现在用mkcp+wechat voide  head +vmess总是被针对封ip，有什么性价比比较高的方案吗？大家推荐一下。或者讨论一下

**Comment by okudayukiko** [comment]
不要用MKCP。

**Comment by l42111996** [comment]
> 不要用MKCP。

用哪种方案比较好呢？mkcp被封是udp被针对了还是mkcp协议被分析了？

**Comment by fbion** [comment]
套https://github.com/wangyu-/udp2raw-tunnel

**Comment by CalmLong** [comment]
VMess 开启 TLS，已用两年，从未被封，速度很快。

**Comment by l42111996** [comment]
> VMess 开启 TLS，已用两年，从未被封，速度很快。

tls这个证书在哪里弄能弄到免费的呢？ 或者便宜的？

**Comment by CalmLong** [comment]
https://github.com/acmesh-official/acme.sh

**Comment by l42111996** [comment]
> https://github.com/acmesh-official/acme.sh
域名去哪里申请比较好呢？有推荐的吗？

**Comment by l42111996** [comment]
> https://github.com/acmesh-official/acme.sh

域名去哪里申请比较好呢？  求推荐一个

**Comment by CalmLong** [comment]
> > https://github.com/acmesh-official/acme.sh
> 
> 域名去哪里申请比较好呢？ 求推荐一个

这个不重要

**Comment by phlinhng** [comment]
> > https://github.com/acmesh-official/acme.sh
> 
> 域名去哪里申请比较好呢？ 求推荐一个

挂个美国代理申请Freenom就好，免费一年无限续期（相当于永久免费）

**Comment by bash99** [comment]
非要mkcp的话，udp2raw包一层。
