### ISSUE TITLE
V2ray是不是防不住TCP SYN攻击？

### ISSUE THREAD

**Issue by Robboo** [v2ray/discussion#653]
host@host:~$ /usr/bin/v2ray/v2ray -version
V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
收到syn之后就不断响应,停不下来
tcp6       0      0 10.140.0.2:443          162.248.94.195:58733    SYN_RECV    -                   
tcp6       0      0 10.140.0.2:443          162.248.94.195:59842    SYN_RECV    -                   
tcp6       0      0 10.140.0.2:443          162.248.94.195:64946    SYN_RECV    -                   
tcp6       0      0 10.140.0.2:443          162.248.94.195:8670     SYN_RECV    -                   
host@host-1:~$ sudo tcpdump -vv host 162.248.94.195
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
06:07:41.459586 IP (tos 0x0, ttl 236, id 21331, offset 0, flags [none], proto TCP (6), length 40)
    usa-wa.vpn.courvix.com.11783 > instance-1.asia-east1-c.c.caramel-logic-252205.internal.https: Flags [S], cksum 0x1b95 (correct), seq 1960758419, win 5840, length 0
06:07:41.459629 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 44)
    instance-1.asia-east1-c.c.caramel-logic-252205.internal.https > usa-wa.vpn.courvix.com.11783: Flags [S.], cksum 0x0c68 (incorrect -> 0x4509), seq 89547120, ack 1960758420, win 28400, options [mss 1420], length 0
06:07:41.476254 IP (tos 0x0, ttl 236, id 36762, offset 0, flags [none], proto TCP (6), length 40)
    usa-wa.vpn.courvix.com.15534 > instance-1.asia-east1-c.c.caramel-logic-252205.internal.https: Flags [S], cksum 0xae34 (correct), seq 153523973, win 5840, length 0
06:07:41.476273 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 44)
    instance-1.asia-east1-c.c.caramel-logic-252205.internal.https > usa-wa.vpn.courvix.com.15534: Flags [S.], cksum 0x0c68 (incorrect -> 0x1ded), seq 3304545162, ack 153523974, win 28400, options [mss 1420], length 0
06:07:41.845439 IP (tos 0x0, ttl 236, id 57403, offset 0, flags [none], proto TCP (6), length 40)
    usa-wa.vpn.courvix.com.43531 > instance-1.asia-east1-c.c.caramel-logic-252205.internal.https: Flags [S], cksum 0xd121 (correct), seq 321256635, win 5840, length 0
06:07:41.845479 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 44)
    instance-1.asia-east1-c.c.caramel-logic-252205.internal.https > usa-wa.vpn.courvix.com.43531: Flags [S.], cksum 0x0c68 (incorrect -> 0x7442), seq 1809154372, ack 321256636, win 28400, options [mss 1420], length 0
06:07:42.489158 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 44)
    instance-1.asia-east1-c.c.caramel-logic-252205.internal.https > usa-wa.vpn.courvix.com.15534: Flags [S.], cksum 0x0c68 (incorrect -> 0x1ded), seq 3304545162, ack 153523974, win 28400, options [mss 1420], length 0
06:07:42.489178 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 44)
    instance-1.asia-east1-c.c.caramel-logic-252205.internal.https > usa-wa.vpn.courvix.com.11783: Flags [S.], cksum 0x0c68 (incorrect -> 0x4509), seq 89547120, ack 1960758420, win 28400, options [mss 1420], length 0
06:07:42.607110 IP (tos 0x0, ttl 236, id 48592, offset 0, flags [none], proto TCP (6), length 40)
    usa-wa.vpn.courvix.com.29651 > instance-1.asia-east1-c.c.caramel-logic-252205.internal.https: Flags [S], cksum 0x47e8 (correct), seq 716940439, win 5840, length 0
06:07:42.607150 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 44)
    instance-1.asia-east1-c.c.caramel-logic-252205.internal.https > usa-wa.vpn.courvix.com.29651: Flags [S.], cksum 0x0c68 (incorrect -> 0x41b9), seq 1393443675, ack 716940440, win 28400, options [mss 1420], length 0
06:07:42.873135 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 44)
    instance-1.asia-east1-c.c.caramel-logic-252205.internal.https > usa-wa.vpn.courvix.com.43531: Flags [S.], cksum 0x0c68 (incorrect -> 0x7442), seq 1809154372, ack 321256636, win 28400, options [mss 1420], length 0
06:07:43.108156 IP (tos 0x0, ttl 236, id 23354, offset 0, flags [none], proto TCP (6), length 40)
    usa-wa.vpn.courvix.com.26156 > instance-1.asia-east1-c.c.caramel-logic-252205.internal.https: Flags [S], cksum 0xe6ba (correct), seq 2071380656, win 5840, length 0
06:07:43.108194 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 44)
    instance-1.asia-east1-c.c.caramel-logic-252205.internal.https > usa-wa.vpn.courvix.com.26156: Flags [S.], cksum 0x0c68 (incorrect -> 0xb707), seq 984843578, ack 2071380657, win 28400, options [mss 1420], length 0
06:07:43.609145 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 44)
    instance-1.asia-east1-c.c.caramel-logic-252205.internal.https > usa-wa.vpn.courvix.com.29651: Flags [S.], cksum 0x0c68 (incorrect -> 0x41b9), seq 1393443675, ack 716940440, win 28400, options [mss 1420], length 0
06:07:44.121111 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 44)
    instance-1.asia-east1-c.c.caramel-logic-252205.internal.https > usa-wa.vpn.courvix.com.26156: Flags [S.], cksum 0x0c68 (incorrect -> 0xb707), seq 984843578, ack 2071380657, win 28400, options [mss 1420], length 0
06:07:44.505118 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 44)
    instance-1.asia-east1-c.c.caramel-logic-252205.internal.https > usa-wa.vpn.courvix.com.11783: Flags [S.], cksum

[37.zip](https://github.com/v2ray/discussion/files/4496168/37.zip)

**Comment by garden4hu** [comment]
[refer](https://holywhite.com/archives/524) 
/etc/sysctl.conf

# TCP SYN Flood Protection
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_synack_retries = 3
