### ISSUE TITLE
我的订阅不能用来上ehentai了，别的墙外网站都正常，求大神解答

### ISSUE THREAD

**Issue by Lunarstra** [v2ray/discussion#659]
ehentai打开以后不报错，也不转圈载入，就一个什么都没有的空白页，以为是网络和计算机出毛病了，结果我把订阅给别人用了下，用这个订阅他也打不开ehentai，求解，其他墙外网站比如管子，pixiv，pornhub，scihub，谷歌什么的都好用

**Comment by kslr** [comment]
ehentai需要特殊会员，检查你的账号

**Comment by Lunarstra** [comment]
我进的是ehentai不是ex，以前一直无账号浏览

Kslr <notifications@github.com> 于2020年4月23日周四 下午3:35写道：

**Comment by kslr** [comment]
总之这个问题你要找机场，几句话我不可能知道是什么原因。

**Comment by Lunarstra** [comment]
好的，十分感谢

Kslr <notifications@github.com> 于2020年4月23日周四 下午7:00写道：
