### ISSUE TITLE
go get

### ISSUE THREAD

**Issue by FatChou** [v2ray/discussion#66]
<details><summary><code>go get github.com/v2ray/v2ray-core</code></summary><br><pre>
package v2ray.com/core/common: unrecognized import path "v2ray.com/core/common" (https fetch: Get https://v2ray.com/core/common?go-get=1: dial tcp 69.171.224.40:443: connect: connection refused)
package v2ray.com/core/common/buf: unrecognized import path "v2ray.com/core/common/buf" (https fetch: Get https://v2ray.com/core/common/buf?go-get=1: dial tcp 69.171.224.40:443: connect: connection refused)
package v2ray.com/core/common/errors: unrecognized import path "v2ray.com/core/common/errors" (https fetch: Get https://v2ray.com/core/common/errors?go-get=1: dial tcp 69.171.224.40:443: connect: connection refused)
package v2ray.com/core/common/net: unrecognized import path "v2ray.com/core/common/net" (https fetch: Get https://v2ray.com/core/common/net?go-get=1: dial tcp 69.171.224.40:443: connect: connection refused)
package v2ray.com/core/common/serial: unrecognized import path "v2ray.com/core/common/serial" (https fetch: Get https://v2ray.com/core/common/serial?go-get=1: dial tcp 69.171.224.40:443: connect: connection refused)
package v2ray.com/core/features: unrecognized import path "v2ray.com/core/features" (https fetch: Get https://v2ray.com/core/features?go-get=1: dial tcp 69.171.224.40:443: connect: connection refused)
package v2ray.com/core/features/dns: unrecognized import path "v2ray.com/core/features/dns" (https fetch: Get https://v2ray.com/core/features/dns?go-get=1: dial tcp 69.171.224.40:443: connect: connection refused)
package v2ray.com/core/features/inbound: unrecognized import path "v2ray.com/core/features/inbound" (https fetch: Get https://v2ray.com/core/features/inbound?go-get=1: dial tcp 69.171.224.40:443: connect: connection refused)
package v2ray.com/core/features/outbound: unrecognized import path "v2ray.com/core/features/outbound" (https fetch: Get https://v2ray.com/core/features/outbound?go-get=1: dial tcp 69.171.224.40:443: connect: connection refused)
package v2ray.com/core/features/policy: unrecognized import path "v2ray.com/core/features/policy" (https fetch: Get https://v2ray.com/core/features/policy?go-get=1: dial tcp 69.171.224.40:443: connect: connection refused)
package v2ray.com/core/features/routing: unrecognized import path "v2ray.com/core/features/routing" (https fetch: Get https://v2ray.com/core/features/routing?go-get=1: dial tcp 69.171.224.40:443: connect: connection refused)
package v2ray.com/core/features/stats: unrecognized import path "v2ray.com/core/features/stats" (https fetch: Get https://v2ray.com/core/features/stats?go-get=1: dial tcp 69.171.224.40:443: connect: connection refused)
package v2ray.com/core/transport: unrecognized import path "v2ray.com/core/transport" (https fetch: Get https://v2ray.com/core/transport?go-get=1: dial tcp 69.171.224.40:443: connect: connection refused)

</pre></details>
使用go get -u v2ray.com/core因为墙的问题始终下载不下来

**Comment by ShadowRayEN** [comment]
Terminal配proxy：
export all_proxy="socks5://127.0.0.1:1086"

**Comment by FatChou** [comment]
配置了后，go get -u v2ray.com/core
package v2ray.com/core: unrecognized import path "v2ray.com/core" (https fetch: Get https://v2ray.com/core?go-get=1: dial tcp 31.13.64.33:443: connect: connection refused)

**Comment by FatChou** [comment]
确实是网络问题，时好时坏
