### ISSUE TITLE
有没有ios可用的v2ray客户端？

### ISSUE THREAD

**Issue by beesuns** [v2ray/discussion#660]
在iPhone的app store中搜索了Kitsunebi ，i2Ray，Shadowrocket，Pepi，Quantumult这几个ios上可用的客户端，一个都找不到。
有没有iPhone能用的v2ray客户端呀？
在没有美区apple id，iPhone不越狱的情况下？
谢谢各位大神！

**Comment by okudayukiko** [comment]
在PC上使用VPN註冊美國Apple ID。

**Comment by youngerliyg** [comment]
还是想办法搞个美区ID才是最终的解决办法。

**Comment by forever8938** [comment]
墙国服不可能有

**Comment by chengziorange** [comment]
不可以。你需要美区Apple ID，获取方法请使用搜索引擎。有一些免费分享的账号可以用用，但要谨慎
