### ISSUE TITLE
玩游戏v2ray CPU 占用太高 游戏延迟严重  求助

### ISSUE THREAD

**Issue by yunfengwangluo** [v2ray/discussion#661]
用于 pubg 游戏 连接 5分钟左右 cpu 占用14% 内存占用50MB  游戏延迟达到 2000+ms。  即使是局域网 server <--> client 延迟也会增加 150+ms   翻看了一些咱们这里的反馈也有遇到同样问题的
有网友说 这个问题一直都有 不知道是 go 语言本身的缺陷 还是 故意为之 
我这里 现在在做一个 游戏加速器项目  希望能用 v2ray   但这个问题 很棘手 无法解决
由于咱们的作者大牛们 不好找到 我这里希望 如果 能 解决这种问题的可以联系我  可以适当补偿一些误工费

**Comment by PiedmontStream** [comment]
试试mkcp

**Comment by xqzr** [comment]
貌似暂时没办法解决，换$$了

**Comment by YFLEA** [comment]
我不是程序猿，MacBook Pro，自从下了v2ray电脑风扇就一直转，发烫也很严重，就想翻个墙而已。去看cpu显示说有个v2ray UHelper运行占了110%多。请问您知道有什么解决方法吗？（纯电脑小白，都不知道如何才能彻底删除软件的那种

**Comment by yunfengwangluo** [comment]
> 我不是程序猿，MacBook Pro，自从下了v2ray电脑风扇就一直转，发烫也很严重，就想翻个墙而已。去看cpu显示说有个v2ray UHelper运行占了110%多。请问您知道有什么解决方法吗？（纯电脑小白，都不知道如何才能彻底删除软件的那种

ss go 语言版本的没有这种问题 v2ray 出的比 ss 晚 理论上 不应该存在这种问题 但这个问题却一直存在  所以问题 要么出在 库 上面 要么就是 故意

**Comment by zhj9709** [comment]
socks udp的问题？v2ray的socks udp会有cpu占用高的情况，我反馈过
