### ISSUE TITLE
请教下这个routing为什么失败

### ISSUE THREAD

**Issue by xiaofami** [v2ray/discussion#662]
背景：有VPS A，B。A不能上telegram，B可以，遂想把A的telegram流量全部转发到B来处理。

现状：

1. A，B均已安装运行v2ray
2.  A在"outbounds"里面已经添加Vmess协议指向B，并标记"tag":"tous"
3. A在 "routing"里面已经添加

{
"type":"field",
"outboundTag":"tous",
"domain":["geosite:telegram"]
},

实际测试B的v2ray日志中没有连接记录，所以是哪里不对呢？修改配置文件后v2ray服务均已重启。

**Comment by kingwilliam** [comment]
```
            // --- domain route ---
            {
                "type": "field",
                "domain": [
                    "telegram.org",
                    "t.me"
                ],
                "outboundTag": "tous"
            },

            // --- ip route ---
            {
                "type": "field",
                "ip": [
                    // "telegram.org"
                    "91.108.4.0/22",
                    "91.108.8.0/22",
                    "91.108.12.0/22",
                    "91.108.16.0/22",
                    "91.108.56.0/22",
                    "149.154.160.0/20"
                ],
                "outboundTag": "tous"
            },

```

**Comment by xiaofami** [comment]
> ```
>             // --- domain route ---
>             {
>                 "type": "field",
>                 "domain": [
>                     "geosite:telegram"
>                 ],
>                 "outboundTag": "tous"
>             },
> 
>             // --- ip route ---
>             {
>                 "type": "field",
>                 "ip": [
>                     // "telegram.org"
>                     "91.108.4.0/22",
>                     "91.108.8.0/22",
>                     "91.108.12.0/22",
>                     "91.108.16.0/22",
>                     "91.108.56.0/22",
>                     "149.154.160.0/20"
>                 ],
>                 "outboundTag": "tous"
>             },
> ```
> 
> telegram当然可以用geosite, 但只限於网页. telegram apps是用ip上网的, 所以要用ip route.
> 
> telegram ip list, 可参考以下档案
> https://core.telegram.org/resources/cidr.txt

感谢指教，按照您的思路成功配置。

**Comment by hisune** [comment]
@xiaofami 我添加了所有ip，但是app还是无法正常连接，看日志，这些ip都有使用特定的route，但app一直显示connecting

**Comment by xiaofami** [comment]
> @xiaofami 我添加了所有ip，但是app还是无法正常连接，看日志，这些ip都有使用特定的route，但app一直显示connecting

https://github.com/v2ray/discussion/issues/679#issuecomment-626272126

这个很详细
