### ISSUE TITLE
A field in a structure is sometimes protected by Mutex, but sometimes unprotected.

### ISSUE THREAD

**Issue by BurtonQin** [v2ray/discussion#663]
**Version Information**
master branch, commit edb4fed387d27890902e7ee97aae0d97292f912b
**What happened**:
A field in a structure is sometimes protected by Mutex, but sometimes unprotected.
This may lead to data race.
There are 3 such cases. All of them are in an out-dated version of quic-go in external.
- [ ] `s.currentFrame` is not protected by `s.mutex` on L172. But for all the other 10 places, it is protected by `s.mutex`.
https://github.com/v2ray/v2ray-core/blob/edb4fed387d27890902e7ee97aae0d97292f912b/external/github.com/lucas-clemente/quic-go/receive_stream.go#L170-L172
- [ ] `c.destConnID` is not protected by `c.mutex` on L251. But for all the other 8 places, it is protected by `c.mutex`.
https://github.com/v2ray/v2ray-core/blob/edb4fed387d27890902e7ee97aae0d97292f912b/external/github.com/lucas-clemente/quic-go/client.go#L250-L251
- [ ] `c.version` is not protected by `c.mutex` on L252. But for all the other 6 places, it is protected by `c.mutex`.
https://github.com/v2ray/v2ray-core/blob/edb4fed387d27890902e7ee97aae0d97292f912b/external/github.com/lucas-clemente/quic-go/client.go#L250-L252

**What you expected to happen**:
Data race

**Comment by zergvszerg** [comment]
s.currentFrame need no mutual exclusive protection, as long as s.frameQueue.Pop() is thread safe.

**Comment by lzhfromustc** [comment]
All the calls to s.dequeueNextFrame() (which calls s.frameQueue.Pop() and writes to `s.currentFrame`) are in critical section, but since there is one read to `s.currentFrame` not in critical section, I think it may still have data race
