### ISSUE TITLE
如何只记错错误日志

### ISSUE THREAD

**Issue by normalnormalnnn** [v2ray/discussion#668]
添加log项之后日志级别设置成error仍然会记录access信息，如果删除access项，access信息会输出到stdout,这样不会影响性能吗？如何可以达到只记录error或者warning信息，不记录access信息。

**Comment by kslr** [comment]
use none

**Comment by normalnormalnnn** [comment]
你测试过吗？我使用 https://github.com/v2ray/v2ray-core V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 darwin/amd64) 在macOS 10.15.4测试如下：
none, 没有任何日志，access和error日志文件都没有生成.(不知道如何让v2ray产生错误）
warning, info, debug均有access和error的日志，越来越详细。

按照重新的理解，我需要的结果是将日志级别设置成warning,然后不记录access的日志，只需要在v2ray产生错误或者网络错误的时候记录日志，是否可以实现？

https://toutyrater.github.io/basic/log.html
根据这里的说明和英文字母意思的理解none都是不记录任何信息。

**Comment by kslr** [comment]
https://v2ray.com/chapter_02/01_overview.html#logobject

**Comment by normalnormalnnn** [comment]
感谢，是我没有看清楚，抱歉。
