### ISSUE TITLE
回国访问爱奇艺被限制；log是空白

### ISSUE THREAD

**Issue by edisonleung1** [v2ray/discussion#675]
在阿里云上搭了梯子，路由器做透明代理，当设置所有流量走梯子的时候能看爱奇艺视频，但是分流的时候会被版权限制，清空log重启service访问爱奇艺再查看log，发现所有的流量都走了梯子但还是被版权限制；
今天查log发现log是空白的，config.json没动过
谢谢大家帮忙解决一下

config.json
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
         },
  "inbounds":[
    {
      "port":"1080",
      "protocol":"socks",
      "settings":{
        "auth":"noauth",
        "udp":true
      },
      "tag":"in-0"
    },
    {
      "port":"1081",
      "protocol":"http",
      "settings":{},
      "tag":"in-1"
    },
    {
   "port": 12345, //开放的端口号
   "protocol": "dokodemo-door",
   "settings": {
   "network": "tcp,udp",
   "followRedirect": true // 这里要为 true 才能接受来自 iptables 的流量
   },
   "sniffing": {
   "enabled": true,
   "destOverride": ["http", "tls"]
   },
   "streamSettings": { //router forward
     "sockopt": {
       "tproxy": "redirect" 
     }
   } //router forward end

 }
  ],
  "outbounds": [ 
      {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
      "streamSettings": {
      "sockopt": {
       "mark": 255
      }
      }
      }
      },
      {
      "tag": "china",
      "protocol": "vmess", // 出口协议
      "settings": {
        "vnext": [
          {
            "address": "", // 服务器 IP 地址
            "port": ,  // 服务器端口
            "users": [
              {
                "id": "",  // 用户 ID，须与服务器端配置相同
                "alterId": 
              }
            ]
          }
        ]
      },
      "streamSettings": {
      "sockopt": {
       "mark": 255
       }
       },
      "mux": { "enabled": true }
    },
    {
      "protocol": "blackhole",
      "settings": {}
    }
  ],
"routing": {
  "domainStrategy": "IPOnDemand",
  "rules": [
    {
      "type": "field",
      "outboundTag": "china",
      "domain": [
      "geoip:cn",
      "domain:ipip.net",
      "domain:sohu.com",
      "domain:ipip.net",
      "domain:skk.moe",
      "domain:ip.sb",
      "domain:baidu.com",
      "domain:iqiyi.com", 
      "domamin:qy.net",
      "domain:irs01.com",
      "domain:iqiyipic.com",
      "domain:isrg.trustid.ocsp.identrust.com",
      "domain:youku.com",
      "domain:qq.com",
      "domain:qpic.cn",
      "domain:qtimg.cn",
      "domain:qlogo.cn",
      "domain:163.com",
      "domain:126.net",
      "domain:netease.com"
      ] // 中国大陆主流网站的域名s
    },
    {
    "type": "field",
    "outboundTag": "direct",
    "domain": [
    "weixin.com"
    ]
    }
  ]
},
    "dns": {
    "servers": [
      "223.5.5.5",
      "223.6.6.6",
      "localhost"
    ]
  }
}

**Comment by kingwilliam** [comment]
1. 有 client log 和 config才可帮忙
2. 我也有翻回国访问 爱奇艺 和 腾讯视频, 爱奇艺只需4个fqdn, 腾讯视频只需1个. 就可以.


```
国外 v2 routing to cn
// --- domain to cn ---
{
    "type": "field",
    "domain": [
        "cache.video.iqiyi.com", //爱奇艺
        "l-rcd.iqiyi.com", //爱奇艺
        "subscription.iqiyi.com", //爱奇艺
        "scache.node1.ts.feedback.qy.net", //爱奇艺
        "vv.video.qq.com"    // 腾讯视频
    ],
    "outboundTag": "v2-to-cn"
},
```

**Comment by edisonleung1** [comment]
> 1. 有 client log 和 config才可帮忙
> 2. 我也有翻回国访问 爱奇艺 和 腾讯视频, 爱奇艺只需4个fqdn, 腾讯视频只需1个. 就可以.
> 
> ```
> 国外 v2 routing to cn
> // --- domain to cn ---
> {
>     "type": "field",
>     "domain": [
>         "cache.video.iqiyi.com", //爱奇艺
>         "l-rcd.iqiyi.com", //爱奇艺
>         "subscription.iqiyi.com", //爱奇艺
>         "scache.node1.ts.feedback.qy.net", //爱奇艺
>         "vv.video.qq.com"    // 腾讯视频
>     ],
>     "outboundTag": "v2-to-cn"
> },
> ```

谢谢！原来之前是缺了qy.net这个
现在爱奇艺问题已解决，但是log还是空白的

**Comment by kingwilliam** [comment]
因您的 "loglevel": "warning" 所以只有出现问题才会有log, 
如"loglevel": "info" 会看见大多数连接.
最後"loglevel": "debnug" 真的到debug时才有需要.

**Comment by edisonleung1** [comment]
已解决,debian里不知道什么系统文件被我删错了。。。

**Comment by edisonleung1** [comment]
> 1. 有 client log 和 config才可帮忙
> 2. 我也有翻回国访问 爱奇艺 和 腾讯视频, 爱奇艺只需4个fqdn, 腾讯视频只需1个. 就可以.
> 
> ```
> 国外 v2 routing to cn
> // --- domain to cn ---
> {
>     "type": "field",
>     "domain": [
>         "cache.video.iqiyi.com", //爱奇艺
>         "l-rcd.iqiyi.com", //爱奇艺
>         "subscription.iqiyi.com", //爱奇艺
>         "scache.node1.ts.feedback.qy.net", //爱奇艺
>         "vv.video.qq.com"    // 腾讯视频
>     ],
>     "outboundTag": "v2-to-cn"
> },
> ```

你好，能问问您用的是哪家的云吗？
现在问题都解决了，就是看视频偶尔还会卡顿，阿里云好像国外访问很慢。。。

**Comment by kingwilliam** [comment]
我都是用阿里云 但重点不在云 重点在爱奇艺那4个fqdn, 因如所有 iqiyi.com 和qy.net全都走v2 ，只要v2 tunnel给 墙 照顾就会出现卡顿。

而爱奇艺只用那4个fqdn检测是否在国内。所以其他的可直连 就可减少卡顿。同时减少云的流量也是减少给 墙 照顾的机会。

**Comment by edisonleung1** [comment]
> 我都是用阿里云 但重点不在云 重点在爱奇艺那4个fqdn, 因如所有 iqiyi.com 和qy.net全都走v2 ，只要v2 tunnel给 墙 照顾就会出现卡顿。
> 
> 而爱奇艺只用那4个fqdn检测是否在国内。所以其他的可直连 就可减少卡顿。同时减少云的流量也是减少给 墙 照顾的机会。

感谢！已改善，请问还能分享一下国外会被墙的国内资源domain吗，感谢万分！

**Comment by kingwilliam** [comment]
出国有不少domain给特别照顾就不用说 入墙应还没有。 但要留意线路 由国外回国 您走的是 163 cn2 还是 三网直连？ 这就是为甚麽入墙都要在 国外找间vps用他们的线路入墙才会畅顺。

电信直连 CN2 GT与CN2 GIA以及163传统骨干网
https://zhuanlan.zhihu.com/p/37615352
