### ISSUE TITLE
服务器同时做服务端和客户端

### ISSUE THREAD

**Issue by edisonleung1** [v2ray/discussion#676]
现在在国外edgerouter做透明代理回国看视频听音乐，但同时又想做服务端做给国内出国外的梯子，该如何配置？这种是多用户的意思吗？
谢谢
config.json

{
"log": {
"loglevel": "warning",
"access": "/var/log/v2ray/access.log",
"error": "/var/log/v2ray/error.log"
},
"inbounds":[{
"tag": "global",
"protocol": "dokodemo-door",
"port": 12345,
"settings": {
"network": "tcp,udp",
"followRedirect": true
},
"sniffing": {
"enabled": true,
"destOverride": ["http", "tls"]
},
"streamSettings": {
"sockopt": {
"tproxy": "redirect"
}
}
},
{
"tag":"fromchina",
"port":,
"protocol": "vmess",
"settings": {
"clients": [{ "id": "",
"alterId": 233 }]
}
},
{
"tag": "socks",
"protocol":"socks",
"port":"1080",
"settings":{
"auth":"noauth",
"udp":true
}
},
{
"tag": "http",
"protocol": "http",
"port": 1081,
"settings": {
"timeout": 0
}
}
],
"outbounds": [
{
"tag": "direct",
"protocol": "freedom",
"settings": {
"streamSettings": {
"sockopt": {
"mark": 255
}
}
}
},
{
"tag": "china",
"protocol": "vmess",
"settings": {
"vnext": [
{
"address": ",
"port": ,
"users": [
{
"id": "",
"alterId": 233
}
]
}
]
},
"streamSettings": {
"sockopt": {
"mark": 255
}
},
"mux": { "enabled": true }
},
{
"protocol": "blackhole",
"settings": {}
}
],
"routing": {
"domainStrategy": "IPOnDemand",
"rules": [
{
"type": "field",
"inboundTag": [
"global",
"http",
"socks"
],
"outboundTag": "china",
"domain": [
"domain:ipip.net",
"domain:sohu.com",
"domain:ip.sb",
"domain:skk.moe",
"domain:speedtest.cn",
"cache.video.iqiyi.com", //爱奇艺
"l-rcd.iqiyi.com", //爱奇艺
"subscription.iqiyi.com", //爱奇艺
"scache.node1.ts.feedback.qy.net", //爱奇艺
"vv.video.qq.com", // 腾讯视频
"domain:youku.com",
"domain:qpic.cn",
"domain:qtimg.cn",
"domain:qlogo.cn",
"domain:163.com",
"domain:126.net",
"domain:netease.com"
] // 中国大陆主流网站的域名
},
{
"type": "field",
"inboundTag": [
"fromchina",
"global",
"http",
"socks"
],
"outboundTag": "direct",
"domain": [
"domain:ubnt.pool.ntp.org"
],
"ip":[
"",
""
]
}
]
}
},

**Comment by kingwilliam** [comment]
1. 有 client  config才可帮忙
2. 只需在inbounds加入就可

```
// inbounds
{
    "tag": "in-ws",
    "protocol": "vmess",
    "port": 43434,
    "settings": {
        "clients": [{
                "id": uuid,
                "alterId": 64,
            }
        ]
    }
}
```

**Comment by edisonleung1** [comment]
inbound已经有两个tag（http和socks），写tag的话该怎么对应呢，这种问题是不是能在哪个manual里能找到答案？
谢谢

**Comment by kingwilliam** [comment]
简单解说 tag 就是给每个 inbound/outbound object一个名号.
详细你可看官网 www.v2fly.com 或 www.v2ray.com和白话文教程
之後就後这名号在routing内做配对, 那个入 -> 那个出

例如:
```
"inbounds":[
    {
        "tag": "in-http",
        ....
    },
    {
        "tag": "in-socks",
        ....
    },
    {
        "tag": "in-vmess",
        ....
    }
],
"outbounds": [
    {
        "tag": "out-vmss-us",
    },
    {
        "tag": "out-vmss-jp",
    }
],
"routing": [
    {
        "type": "fields",
        "inboundTag": [
            "in-http",
            "in-socks"
        ],
        "outboundTag": "out-vmess-jp"
    },
    {
        "type": "fields",
        "inboundTag": "in-vmess",
        "outboundTag": "out-vmess-us"
    }
]
```

**Comment by edisonleung1** [comment]
> 简单解说 tag 就是给每个 inbound/outbound object一个名号.
> 详细你可看官网 [www.v2fly.com](http://www.v2fly.com) 或 [www.v2ray.com和白话文教程](http://www.v2ray.com%E5%92%8C%E7%99%BD%E8%AF%9D%E6%96%87%E6%95%99%E7%A8%8B)
> 之後就用这名号在routing内做配对, 那个入 -> 那个出
> 
> 例如:
> 
> ```
> "inbounds":[
>     {
>         "tag": "in-http",
>         ....
>     },
>     {
>         "tag": "in-socks",
>         ....
>     },
>     {
>         "tag": "in-vmess",
>         ....
>     }
> ],
> "outbounds": [
>     {
>         "tag": "out-vmss-us",
>         ....
>     },
>     {
>         "tag": "out-vmss-jp",
>         ....
>     }
> ],
> "routing": [
>     {
>         "type": "fields",
>         "inboundTag": [
>             "in-http",
>             "in-socks"
>         ],
>         "outboundTag": "out-vmess-jp"
>     },
>     {
>         "type": "fields",
>         "inboundTag": "in-vmess",
>         "outboundTag": "out-vmess-us"
>     }
> ]
> ```

感谢
但是现在inboundtag有http, socks,dokodemo-door, 这是翻回国的，outboundtag对应也需要两个（china, direct)；假如加入当服务器的需要，inboundtag再加一个vmess，outboundtag走direct，这么写对吗？

"routing": [
{
    "type": "field",
    "inboundTag": [
    "global",
    "http",
    "socks",//本地流量
    "as_server"//国内来的流量
    ],
    "outboundTag": "direct"//海外直连
},
{
      "type": "field",
      "inboundTag": [
      "global",
      "http",
      "socks"//本地流量
      ],
      "outboundTag": "china"//走国内VPS
},

**Comment by kingwilliam** [comment]
先处理您的routing rules现有问题
```
// 修改前
"rules": [{
        "type": "field",
        "outboundTag": "china",
        "domain": [
            "geoip:cn",  < -geoip只能放在 ip, 不能放在domain
            "domain:ipip.net",
            "domain:sohu.com",
            "domain:ipip.net",
            "domain:skk.moe",
            "domain:ip.sb",
            "domain:baidu.com",
            "domain:iqiyi.com",
            "domamin:qy.net",
            "domain:irs01.com",
            "domain:iqiyipic.com",
            "domain:isrg.trustid.ocsp.identrust.com",
            "domain:youku.com",
            "domain:qq.com",
            "domain:qpic.cn",
            "domain:qtimg.cn",
            "domain:qlogo.cn",
            "domain:163.com",
            "domain:126.net",
            "domain:netease.com"
        ]// 中国大陆主流网站的域名s
    }
]
```

```
// 修改後
"rules": [{
        "type": "field",
        "outboundTag": "china",
        "domain": [
            "ipip.net",
            "sohu.com",
            "ipip.net",
            "skk.moe",
            "ip.sb",
            "baidu.com",
            "iqiyi.com",
            "domamin:qy.net",
            "irs01.com",
            "iqiyipic.com",
            "isrg.trustid.ocsp.identrust.com",
            "youku.com",
            "qq.com",
            "qpic.cn",
            "qtimg.cn",
            "qlogo.cn",
            "163.com",
            "126.net",
            "netease.com"
        ]// 中国大陆主流网站的域名s
    }, {
        "ip": [
            "type": "field",
            "outboundTag": "china",
            "geoip:cn",  < -geoip只能放在 ip, 不能放在domain
        ]
    }
]

```

**Comment by kingwilliam** [comment]
你的情况昰否在国外有个server:
1. 会接收透明代理 国外网站就直连, 国内的就翻回国内?
2. 同时也会接收国内翻出来连接, 之後直连?

以下的routing rules已可处理您的情况.
1. 您一样要在inbounds加入vmess_from_china接收国内出来的连接.
2. 以下的routing rules已可处处您的情况
3. 如何解读以下routing rules?
- inbounds: http, socks, global, 如要去国外网站如ebay, 因rules内没有合用的routing, 所以会离开routing, 会用default outbounds(即outbounds内一个outbound, 您的情况就是direct)
- inbounds: http, socks, global, 如要去国内网站如baidu, 因rules内domain条件已附合, 所以会直接跳到 outbound china.
- inbounds: vmess_from_china, 因由国内出来的应不会有国内domain和ip, 所以一样会离开routing, 会用default outbounds(即outbounds内一个outbound, 您的情况就是direct)

```
"routing": {
    "rules": [{
            // 由國內出來的就直連
            "type": "field",
            "inboundTag": "vmess_from_china",
            "outboundTag": "direct"
        }, {
            // 如是要去國內的ip就走china
            "type": "field",
            "ip": [
                "geosite:cn",
            ],
            "outboundTag": "china"
        }, {
            // 如是要去國內的domain就走china
            "type": "field",
            "domain": [
                "ipip.net",
                "sohu.com",
                "ipip.net",
                "skk.moe",
                "ip.sb",
                "baidu.com",
                "iqiyi.com",
                "domamin:qy.net",
                "irs01.com",
                "iqiyipic.com",
                "isrg.trustid.ocsp.identrust.com",
                "youku.com",
                "qq.com",
                "qpic.cn",
                "qtimg.cn",
                "qlogo.cn",
                "163.com",
                "126.net",
                "netease.com"
            ], // 中国大陆主流网站的域名s

            "outboundTag": "china"
        }
    ]
}
```

**Comment by edisonleung1** [comment]
> 先处理您的routing rules现有问题
> 
> ```
> // 修改前
> "rules": [{
>         "type": "field",
>         "outboundTag": "china",
>         "domain": [
>             "geoip:cn",  < -geoip只能放在 ip, 不能放在domain
>             "domain:ipip.net",
>             "domain:sohu.com",
>             "domain:ipip.net",
>             "domain:skk.moe",
>             "domain:ip.sb",
>             "domain:baidu.com",
>             "domain:iqiyi.com",
>             "domamin:qy.net",
>             "domain:irs01.com",
>             "domain:iqiyipic.com",
>             "domain:isrg.trustid.ocsp.identrust.com",
>             "domain:youku.com",
>             "domain:qq.com",
>             "domain:qpic.cn",
>             "domain:qtimg.cn",
>             "domain:qlogo.cn",
>             "domain:163.com",
>             "domain:126.net",
>             "domain:netease.com"
>         ]// 中国大陆主流网站的域名s
>     }
> ]
> ```
> 
> ```
> // 修改後
> "rules": [{
>         "type": "field",
>         "outboundTag": "china",
>         "domain": [
>             "ipip.net",
>             "sohu.com",
>             "ipip.net",
>             "skk.moe",
>             "ip.sb",
>             "baidu.com",
>             "iqiyi.com",
>             "domamin:qy.net",
>             "irs01.com",
>             "iqiyipic.com",
>             "isrg.trustid.ocsp.identrust.com",
>             "youku.com",
>             "qq.com",
>             "qpic.cn",
>             "qtimg.cn",
>             "qlogo.cn",
>             "163.com",
>             "126.net",
>             "netease.com"
>         ]// 中国大陆主流网站的域名s
>     }, {
>         "ip": [
>             "type": "field",
>             "outboundTag": "china",
>             "geoip:cn"  < -geoip只能放在 ip, 不能放在domain
>         ]
>     }
> ]
> ```

这个已经在后来加tag时发现问题了直接去掉了，但还是谢谢

**Comment by edisonleung1** [comment]
> 你的情况昰否在国外有个server:
> 
> 1. 会接收透明代理 国外网站就直连, 国内的就翻回国内?
> 2. 同时也会接收国内翻出来连接, 之後直连?
> 
> 以下的routing rules已可处理您的情况.
> 
> 1. 您一样要在inbounds加入vmess_from_china接收国内出来的连接.
> 2. 以下的routing rules已可处处您的情况
> 3. 如何解读以下routing rules?
> 
> * inbounds: http, socks, global, 如要去国外网站如ebay, 因rules内没有合用的routing, 所以会离开routing, 会用default outbounds(即outbounds内一个outbound, 您的情况就是direct)
> * inbounds: http, socks, global, 如要去国内网站如baidu, 因rules内domain条件已附合, 所以会直接跳到 outbound china.
> * inbounds: vmess_from_china, 因由国内出来的应不会有国内domain和ip, 所以一样会离开routing, 会用default outbounds(即outbounds内一个outbound, 您的情况就是direct)
> 
> ```
> "routing": {
>     "rules": [{
>             // 如是要去國內的ip就走china
>             "type": "field",
>             "ip": [
>                 "geosite:cn",
>             ],
>             "outboundTag": "china"
>         }, {
>             // 如是要去國內的domain就走china
>             "type": "field",
>             "domain": [
>                 "ipip.net",
>                 "sohu.com",
>                 "ipip.net",
>                 "skk.moe",
>                 "ip.sb",
>                 "baidu.com",
>                 "iqiyi.com",
>                 "domamin:qy.net",
>                 "irs01.com",
>                 "iqiyipic.com",
>                 "isrg.trustid.ocsp.identrust.com",
>                 "youku.com",
>                 "qq.com",
>                 "qpic.cn",
>                 "qtimg.cn",
>                 "qlogo.cn",
>                 "163.com",
>                 "126.net",
>                 "netease.com"
>             ], // 中国大陆主流网站的域名s
> 
>             "outboundTag": "china"
>         }
>     ]
> }
> ```

1.1 是
1.2 是
2.1 已加入inbound fromchina
2.3 fromchina的话还是会有国内网站（因为有透明代理），是不是应该把这部分配置放在国内透明代理上达到fromchina的只有国外网站？但如果可以还是希望能在国外服务器（此服务器上配置），因为部分客户端不是全局代理例如手机在外，客户端配置相对难update。

实在是太感谢了！

**Comment by kingwilliam** [comment]
![image](https://user-images.githubusercontent.com/3607762/81513409-e0700980-935a-11ea-8097-d22cf7e07d5f.png)

先全选您的coding,就click上面 <> 就可以

**Comment by kingwilliam** [comment]
可在routing rules最上加入以下设定, 就是fromchina的就direct走.

```
{
    "type": "field",
    "inboundtag": "fromchina",
    "outboundtag": "direct"
}
```
