### ISSUE TITLE
更新路由固件后出现问题

### ISSUE THREAD

**Issue by edisonleung1** [v2ray/discussion#677]
原本能正常使用，更新了EdgeRouter ER-X/ER-X-SFP/EP-R6/ER-10X: Firmware v2.0.8-hotfix.1之后v2ray服务启动失败，重新安装一遍之后问题能暂时解决，重启之后服务又会启动失败。
status:
* v2ray.service - V2Ray - A unified platform for anti-censorship
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: en
   Active: failed (Result: exit-code) since Thu 2020-05-07 11:38:28 UTC; 7min ag
     Docs: https://v2ray.com
           https://guide.v2fly.org
  Process: 892 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (co
 Main PID: 892 (code=exited, status=23)

May 07 11:38:24 ubnt systemd[1]: Started V2Ray - A unified platform for anti-cen
May 07 11:38:26 ubnt v2ray[892]: V2Ray 4.23.1 (V2Fly, a community-driven edition
May 07 11:38:26 ubnt v2ray[892]: A unified platform for anti-censorship.
May 07 11:38:28 ubnt v2ray[892]: 2020/05/07 11:38:27 [Info] v2ray.com/core/commo
May 07 11:38:28 ubnt v2ray[892]: v2ctl> Read config:  /etc/v2ray/config.json
May 07 11:38:28 ubnt v2ray[892]: main: failed to create server > v2ray.com/core/
May 07 11:38:28 ubnt systemd[1]: v2ray.service: Main process exited, code=exited
May 07 11:38:28 ubnt systemd[1]: v2ray.service: Unit entered failed state.
May 07 11:38:28 ubnt systemd[1]: v2ray.service: Failed with result 'exit-code'.

config:
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "info"
         },
  "inbounds":[
    {
      "port":"1080",
      "protocol":"socks",
      "settings":{
        "auth":"noauth",
        "udp":true,
        "tag":"in-0"
      }
    },
    {
      "port":"1081",
      "protocol":"http",
      "settings":{},
      "tag":"in-1"
    },
    {
   "port": 12345, //开放的端口号
   "protocol": "dokodemo-door",
   "settings": {
   "network": "tcp,udp",
   "followRedirect": true // 这里要为 true 才能接受来自 iptables 的流量
   },
   "sniffing": {
   "enabled": true,
   "destOverride": ["http", "tls"]
   },
   "streamSettings": { //router forward
     "sockopt": {
       "tproxy": "redirect" 
     }
   } //router forward end

 }
  ],
  "outbounds": [ 
      {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
      "streamSettings": {
      "sockopt": {
       "mark": 255
      }
      }
      }
      },
      {
      "tag": "china",
      "protocol": "vmess", // 出口协议
      "settings": {
        "vnext": [
          {
            "address": "", // 服务器 IP 地址
            "port": ,  // 服务器端口
            "users": [
              {
                "id": "",  // 用户 ID，须与服务器端配置相同
                "alterId": 
              }
            ]
          }
        ]
      },
      "streamSettings": {
      "sockopt": {
       "mark": 255
       }
       },
      "mux": { "enabled": true }
    },
    {
      "protocol": "blackhole",
      "settings": {}
    }
  ],
"routing": {
  "domainStrategy": "IPOnDemand",
  "rules": [
    {
      "type": "field",
      "outboundTag": "china",
      "domain": [
      "geoip:cn",
      "domain:ipip.net",
      "domain:sohu.com",
      "domain:ipip.net",
      "domain:skk.moe",
      "domain:ip.sb",
      "domain:baidu.com",
      "domain:iqiyi.com", 
      "domain:qy.net",
      "domain:irs01.com",
      "domain:iqiyipic.com",
      "domain:isrg.trustid.ocsp.identrust.com",
      "domain:youku.com",
      "domain:qq.com",
      "domain:qpic.cn",
      "domain:qtimg.cn",
      "domain:qlogo.cn",
      "domain:163.com",
      "domain:126.net",
      "domain:netease.com"
      ] // 中国大陆主流网站的域名s
    },
    {
    "type": "field",
    "outboundTag": "direct",
    "domain": [
    "weixin.com"
    ]
    }
  ]
},
    "dns": {
    "servers": [
      "223.5.5.5",
      "223.6.6.6",
      "localhost"
    ]
  }
}

log的文件目录也不存在
usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json 
V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/mipsle)
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/app/log: failed to initialize access logger > open /var/log/v2ray/access.log: no such file or directory

感谢各位帮忙

**Comment by kslr** [comment]
open /var/log/v2ray/access.log: no such file or directory

**Comment by edisonleung1** [comment]
> open /var/log/v2ray/access.log: no such file or directory

不好意思还是不太懂 是的log在重启之后连目录都没了 是固件的bug的意思吗 升级之前能正常使用的
