### ISSUE TITLE
关于v2ray分流TG的问题

### ISSUE THREAD

**Issue by timmylu1980** [v2ray/discussion#679]
你好 现在是这个情况 我有一台俄罗斯vps服务器 搭建了v2ray ws tls caddy 这个组合 但是俄罗斯服务器屏蔽了TG 但是我的另一台美国服务器可以上TG(配置也是v2rayy ws tls caddy) 我现在想把俄罗斯服务器访问TG时候的流量转发到美国服务器(以便能正常使用TG)我该如何写俄罗斯这台服务器的配置文件呢(附上我现在的配置文件)非常感谢!!!
{
  "inbounds": [
    {
      "port": 33389,
      "listen":"127.0.0.1",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "6d3ae6ee-XXXX-XXXX-XXXX-7434babd187c",
            "alterId": 64
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
        "path": "/timmylu"
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}

**Comment by DolorHunter** [comment]
https://guide.v2fly.org/advanced/outboundproxy.html

**Comment by timmylu1980** [comment]
你好 非常感谢你的回复 这篇文章我也看了 但还是找不到切入点 比如我要让 149.154.160.0/20 这个ip段走美国的服务器 在上面的配置文件中该如何写如呢 有时间麻烦帮我改下我的配置文件好吗 谢谢

**Comment by kingwilliam** [comment]
// 罗斯服务器
```
    // --- TG domain to us ---
    "routing": [
        {
            "type": "field",
            "domain": [
                "geosite:telegram"
            ],
            "outboundTag": "out-us_ws"
        },

        // --- TG ip to us ---
        {
            "type": "field",
            "ip": [
                // "telegram.org"
                "91.108.4.0/22",
                "91.108.8.0/22",
                "91.108.12.0/22",
                "91.108.16.0/22",
                "91.108.56.0/22",
                "149.154.160.0/20"
            ],
            "outboundTag": "out-us_ws"
        }
    ]

    "outbounds": [
        {
            "tag": "out-us_ws",
             "protocol": "vmess",
             ....
        }
    ]
```

**Comment by timmylu1980** [comment]
感谢您的回复 我现在俄罗斯和美国服务器除了域名不一样 剩下配置都是一样的 我按照您给的重写了下俄罗斯服务器的配置 但是现在还是TG上不去 我的理解是在配置里添加美国服务器是做为客户端去连接的 不知道这样理解对吗 我把配置文件贴上 您在帮过我看下 麻烦了
{
  "inbounds": [
    {
      "port": 33389,
      "listen":"127.0.0.1",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "6d3ae6ee-XXXX-XXXX-a47f-7434babd187c",
            "alterId": 64
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
        "path": "/timmylu"
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}

    "routing": [
        {
            "type": "field",
            "domain": [
                "geosite:telegram"
            ],
            "outboundTag": "out-us_ws"
        },

        // --- TG ip to us ---
        {
            "type": "field",
            "ip": [
                // "telegram.org"
                "91.108.4.0/22",
                "91.108.8.0/22",
                "91.108.12.0/22",
                "91.108.16.0/22",
                "91.108.56.0/22",
                "149.154.160.0/20"
            ],
            "outboundTag": "out-us_ws"
        }
    ]

    "outbounds": [
        {
            "tag": "out-us_ws",
             "protocol": "vmess",
             "settings": {
        "vnext": [
          {
            "address": "www.shengshi.cf",
            "port": 443,
            "users": [
              {
                "id": "6d3ae6ee-XXXX-XXXX-a47f-7434babd187c",
                "alterId": 64,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": null
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/shenghe",
          "headers": null
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
        }
    ]

**Comment by kingwilliam** [comment]
```
{
    "inbounds": [{
            "port": 33389,
            "listen": "127.0.0.1",
            "protocol": "vmess",
            "settings": {
                "clients": [{
                        "id": uuid,
                        "alterId": 64
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "wsSettings": {
                    "path": "/timmylu"
                }
            }
        }
    ],
    "routing": {
        "rules": [{
                "type": "field",
                "domain": [
                    "geosite:telegram"
                ],
                "outboundTag": "out-us_ws"
            },

            // --- TG ip to us ---
            {
                "type": "field",
                "ip": [
                    // "telegram.org"
                    "91.108.4.0/22",
                    "91.108.8.0/22",
                    "91.108.12.0/22",
                    "91.108.16.0/22",
                    "91.108.56.0/22",
                    "149.154.160.0/20"
                ],
                "outboundTag": "out-us_ws"
            }
        ]
    },
    "outbounds": [{
            "tag": "direct",
            "protocol": "freedom",
            "settings": {}
        }, {
            "tag": "out-us_ws",
            "protocol": "vmess",
            "settings": {
                "vnext": [{
                        "address": "www.shengshi.cf",
                        "port": 443,
                        "users": [{
                                "id": uuid,
                                "alterId": 64,
                                "email": "t@t.tt",
                                "security": "auto"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "wsSettings": {
                    "connectionReuse": true,
                    "path": "/shenghe"
                },
                "security": "tls",
                "tlsSettings": {
                    "allowInsecure": false
                }
            },
            "mux": {
                "enabled": true,
                "concurrency": 8
            }
        }

    ]
}

```

**Comment by timmylu1980** [comment]
你好 非常感谢您的帮助 现在已经非常ok了 祝您一切顺利
