### ISSUE TITLE
通过api增加用户后如何将用户保存到配置文件

### ISSUE THREAD

**Issue by sylarjiang** [v2ray/discussion#68]
api 增加删除用户,流量统计都一切正常.但是程序一重启用户就丢失了.如何保存API添加的用户信息

**Comment by sylarjiang** [comment]
> 你需要在通过API修改用户的同时，维护一份更新的配置文件。

您的意思是需要手动去操作配置文件？官方并没有更新配置文件的功能？

**Comment by VictoriaRaymond** [comment]
是的，没有

**Comment by chakson** [comment]
请问这个问题现在有解决方案吗
