### ISSUE TITLE
机场主与 VPS 服务商，能看到哪些内容

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [v2ray/discussion#681]
对于 HTTP 和 HTTPS，一般情况和特意探查

机场主与 VPS 后台能看到哪些内容？（域名／链接／内容／帐密）

**Comment by okudayukiko** [comment]
DNS可以（解决办法是DNS over TLS等等）
HTTP可以
HTTPS不行
访问的IP也可以

**Comment by LakeishaKowalczyk** [comment]
@okudayukiko 
谢谢
DNS 可以这句没看懂
是说机场主能看到 DNS 服务商／DNS 数据包，还是 DNS 服务商能看到什么？

**Comment by okudayukiko** [comment]
> @okudayukiko
> 谢谢
> DNS 可以这句没看懂
> 是说机场主能看到 DNS 服务商／DNS 数据包，还是 DNS 服务商能看到什么？

可以看到DNS域名，和DNS解析的IP地址。

**Comment by nicholascw** [comment]
可以直接看到你送进SOCKS5的所有内容。

**Comment by LakeishaKowalczyk** [comment]
@nicholascw 
比如我现在对你说「你好」
机场主可以看到「你好」这两个字吗

**Comment by Lightmani** [comment]
> @nicholascw
> 比如我现在对你说「你好」
> 机场主可以看到「你好」这两个字吗

如果是明文内容，可以看到。
如果是HTTPS内容，只能看到你访问的网站。比如你上P站，他们只能看到你上了P站，但不知道你具体看了什么片。
