### ISSUE TITLE
不专业测试分享

### ISSUE THREAD

**Issue by kingwilliam** [v2ray/discussion#686]
前言：这个不是官方也不是专业测试，只是个人想了解v2各种Protocols和Transport在不同组合的表现。方便在不同硬件和环境下用不同的配置达到理想效果。以下数据和方法只是在个人测试环境下的表现，并不保证能和其他测试比较。最後 我只张我的测试数据分享出来给大家参考, 并不会提供任何结论, 至於如何解读数据 悉随尊便 不喜勿插。

便件：
host（母鸡）
cpu: intel xeon5690 6core(12 threads) 3.46GHz
mem: 48GB
os: windows 2019 hyper-v

guest（小鸡） x2
os: ubuntu 18.04.4 server
cpu: xeon5690 1core 3.46GHz
mem: 1GB

软件:
- v2fly v4.23.1
- iperf3

测试环境：
- 完全封闭环境，只有两部vm和一部virtual switch
- `[vm-client]--(hyper-v virtual switch)--[vm-server]`
- 每个测试都只会用1条连接链(single connection)
- 以下测试全都是tcp入dokodemo-door（因v2 dokodemo-door udp 转换率没tcp那麽高，所以暂不测试udp）
- 每个测试都会先restart v2ray
- vmess alterid=64（之後alterid=0再测试, 结果（全）没分别）
- 每个 protocols + transport 结果 都是测试3次再取平均值。
- TLS是用letsencrypt 2048 RSA证书（RSA-2048比对ECC-256, 在传送上和cpu使用率都没明显分别(不包括前期的握手时间）

**先做3个基准测试**
T1: iperf3 tcp 直连 (测试系统和网路表现)
R1: 9.92Gbit/s(20/20) (括号内两组数字[左是客户cpu的使用率/右是伺服器])

T2: iperf3 udp 直连 (测试系统和网路表现)
R2: 2.89Gbit/s(97/72) (同上)

T3: 伺服器只用iperf3/客户建立v2, inbound用dokodemo, 之後freedom直出连接iperf3 server.(测试v2内在消耗)
R3: 6.55Gbit/s(70/xx) (伺服器cpu使用率忘了记下)

R1和R3比较
tcp基本转换率是 ~66%(内耗 ~33%)。
udp基本转换率是 ~50%(内耗 ~50%)(早前测试)。

**以下再分两部份测试**
1. 没tls
2. 有tls

![tls_full](https://user-images.githubusercontent.com/3607762/82139411-2ac12100-985a-11ea-8d36-84c3169fb35d.png)

**导读:**

1. 格内3组数字,上行大字传送速度 单位Mbit/s, 下行小字[左是客户cpu的使用率/右是伺服器]
2. 不知原因 可能是个人不太熟悉mkcp, 多个测试都没甚麽变化。

(補充1). 为可测试 没TLS的socsk5?这个不是没安全的传输吗? 对!真的没安全可言, 但有两点可以补充
-- 就是没TLS和没加密, 可以测试全速时的表现, 取他做基准
-- 大家忘了v2支援unix-socket吗? 至於如何经unix-socket去伺服器, 这点不多说了(已离题)

**在(没)tls环境下:**

3. 又是不知原因 socks5 由tcp转ws 跌福相当大, vmess/ss大约折损70% 但socks5就有87%. 已re-test过3次, 结果还是一样,所以先放上来给大家参考.
4. vmess和ss 没甚麽分别, 已socks5最快.

**在(有)tls环境下:**
先比对 vmess

5. security aes-128-gcm/none: 设定none时 在tcp和ws有30%增益, quic 有~5%增益, kcp和h2没分别。
5.1. aes-128-gcm/none对cpu使用率没分别

vmess security none 时,

6. vmess在tcp/ws速度和socks5可说没分别, 比ss快大约20%.
6.1. 但在h2/h3就比socks5折让7%/20%
7. quic加密和不加密比较, 不加密大约有10%增益
8. quic非常吃cpu, 但又没在速度反映出来, 可能是测试环境没发挥quic长处。

**openwrt 或 树莓派:**
如使用 openwrt 或 树莓派 这类硬件请况下, 比较安全可考虑 tls+socks5+tcp / tls+vmess(none)+tcp. 如不考虑tls, vmess/ss+tcp也有不错的速度(但要注意安全)

**後话：**
以下数据已离题, 但还有点点参考价值
官网建议, 在v2前加一个 web server/反向代理 作保护, 多个流程 必定会有损耗, 那麽多一个程序会损耗多少?

haproxy 2.0 损耗33%, 这数字比个人预期大。
- tcp个人问题不会设定, 所以只得ws/h2c。
- ws/h2 速度aes>none? 没错, 我也不知为何? 有空再复检。

Caddy 2.0 加入後(vmess:aes/s5/ss)效能反而有所提升, 的确有点意外。(可能是unload tls有关)
- 为何只得ws?, 因要2.1才支援h2c, tcp个人问题不会设定。

**Comment by ju0594** [comment]
你好，有几个问题，vmess的alterid是否调为0，降低该值会降低安全性，但是我觉得在tls下，vmess降低安全性也是安全的，然后是vmess的加密方式选择none会不会更快呢？有人说none最省资源，也有人说none是软件加密不如另外两种，很疑惑…

**Comment by kingwilliam** [comment]
已更新

**Comment by ju0594** [comment]
> 已更新

感谢分享，对我很有帮助，3Q~

**Comment by lylyo** [comment]
有tls下拿vmess用none，ss用128gcm的结果比较得出了个第6条vmess比ss快大约20%的结论是什么操作？不应该是拿表格里vmess左边的数据比较吗，vmess的tcp605，ws564，ss的tcp683，ws644，难道不是这样比较吗？

**Comment by phlinhng** [comment]
> 的alterid是否调为0，降低该值会降低安全性，但是我觉得在tls下，vmess降低安全性也是安全的，然后是vmess的加密方式选择none会不会更快呢？有人说none最省资源，也有人说none是软件加密不如另外两种

https://github.com/v2ray/v2ray-core/issues/1257

**Comment by kingwilliam** [comment]
> 有tls下拿vmess用none，ss用128gcm的结果比较得出了个第6条vmess比ss快大约20%的结论是什么操作？不应该是拿表格里vmess左边的数据比较吗，vmess的tcp605，ws564，ss的tcp683，ws644，难道不是这样比较吗？

所以我在第六点上已标示
"vmess security none 时,"

不要介意我用vmess:none比对shadowsocks:aes-128-gcm, 看似不公平, 但在TLS下都算安全。

**Comment by lylyo** [comment]
> > 有tls下拿vmess用none，ss用128gcm的结果比较得出了个第6条vmess比ss快大约20%的结论是什么操作？不应该是拿表格里vmess左边的数据比较吗，vmess的tcp605，ws564，ss的tcp683，ws644，难道不是这样比较吗？
> 
> 所以我在第六点上已标示
> "vmess security none 时,"
> 
> 不要介意我用vmess:none比对shadowsocks:aes-128-gcm, 看似不公平, 但在TLS下都算安全设定。

所以你的意思是有tls的只有vmess，而socks5和ss都是无tls？不然何来在tls下都算安全设定这句话？而如果是全都有tls的话，那ss选择none难道就不算安全设定吗？

**Comment by kingwilliam** [comment]
> > > 有tls下拿vmess用none，ss用128gcm的结果比较得出了个第6条vmess比ss快大约20%的结论是什么操作？不应该是拿表格里vmess左边的数据比较吗，vmess的tcp605，ws564，ss的tcp683，ws644，难道不是这样比较吗？
> > 
> > 
> > 所以我在第六点上已标示
> > "vmess security none 时,"
> > 不要介意我用vmess:none比对shadowsocks:aes-128-gcm, 看似不公平, 但在TLS下都算安全设定。
> 
> 所以你的意思是有tls的只有vmess，而socks5和ss都是无tls？不然何来在tls下都算安全设定这句话？而如果是全都有tls的话，那ss选择none难道就不算安全设定吗？

可能我没用心在文章格式, 令大家看得眼花, 容我日後有空再重整。 先在这简单回答你的提问。

我图表分两部份

1. (没)tls环境

2. (有)tls环境
- "先比对 vmess"
- "vmess security none 时"
- - vmess在tcp/ws速度和socks5可说没分别, 比ss快大约20%. (所以这是在有TLS+vmess(none)/s5/ss(aes)下比对)


另一问题
"而如果是全都有tls的话，那ss选择none难道就不算安全设定吗？"
参考官网 https://www.v2ray.com/chapter_02/protocols/shadowsocks.html#encryption-list
shardowsocks 加密方式列表
"aes-256-cfb"
"aes-128-cfb"
"chacha20"
"chacha20-ietf"
"aes-256-gcm"
"aes-128-gcm"
因看不到ss可不加密, 所以没刻意试none.

**Comment by phlinhng** [comment]
没 TLS 时的 socks5 不算安全设定吧？测 socks5 是为了对比有 tls 的情况吗

**Comment by kingwilliam** [comment]
> 没 TLS 时的 socks5 不算安全设定吧？测 socks5 是为了对比有 tls 的情况吗

对, 只用作参考

**Comment by lylyo** [comment]
> > > > 有tls下拿vmess用none，ss用128gcm的结果比较得出了个第6条vmess比ss快大约20%的结论是什么操作？不应该是拿表格里vmess左边的数据比较吗，vmess的tcp605，ws564，ss的tcp683，ws644，难道不是这样比较吗？
> > > 
> > > 
> > > 所以我在第六点上已标示
> > > "vmess security none 时,"
> > > 不要介意我用vmess:none比对shadowsocks:aes-128-gcm, 看似不公平, 但在TLS下都算安全设定。
> > 
> > 
> > 所以你的意思是有tls的只有vmess，而socks5和ss都是无tls？不然何来在tls下都算安全设定这句话？而如果是全都有tls的话，那ss选择none难道就不算安全设定吗？
> 
> 可能我没用心在文章格式, 令大家看得眼花, 容我日後有空再整理。 先在这简单回答你的提问。
> 
> 我图表分两部份
> 
> 1. (没)tls环境
> 2. (有)tls环境
> 
> * "vmess security none 时"
> * * vmess在tcp/ws速度和socks5可说没分别, 比ss快大约20%. (所以这是在有TLS+vmess(none)/s5/ss(aes)下比对)
> 
> 另一问题
> "而如果是全都有tls的话，那ss选择none难道就不算安全设定吗？"
> 参考官网 https://www.v2ray.com/chapter_02/protocols/shadowsocks.html#encryption-list
> shardowsocks 加密方式列表
> "aes-256-cfb"
> "aes-128-cfb"
> "chacha20"
> "chacha20-ietf"
> "aes-256-gcm"
> "aes-128-gcm"
> 因看不到ss可不加密, 所以没刻意试none.

看了下ss确实不能选none，不过比较时连单一变量都没做到，结论也不指明。你高兴就好。

**Comment by flyhigao** [comment]
基础测试，T1和T2怎么差这么多？是不是写错了

**Comment by kingwilliam** [comment]
> 基础测试，T1和T2怎么差这么多？是不是写错了

T1 是 tcp 9.98Gbit/s, cpu(20/20)
T2 是 udp.2.89Gbit/s, cpu(97/97) 估计是cpu已到上限. 所以速度上不了。

**Comment by flyhigao** [comment]
o ,我也简单验证了下, 是40g网卡
用iperf3 -c 10.5.10.2 -p5201 -t 20 -i5 -u -b 10g -l1500 (可调不同包长度),的确也只能到2.xGb/s 

又用内核自带的pktgen发64字节udp包试了下:
1cpu: 3.7百万pps,  1.77Gb/s    
2cpu: 6.6百万pps,   3.1Gb/s
4cpu: 12.2百万pps, 6.4Gb/s
8cpu: 12.9百万pps, 7Gb/s    

pktgen这个性能就比较正常了.
iperf处理udp估计有问题.

**Comment by zlj88** [comment]
感谢分享
