### ISSUE TITLE
vmess的none加密是最省资源的吗？

### ISSUE THREAD

**Issue by ju0594** [v2ray/discussion#688]
最外层用的tls，已知id调为0可以节省资源，tcp也比ws省资源，那么vmess的加密方式呢？
有人说none最省资源，也有人说none是软件加密，速度实际不如另外两种，很疑惑…

心中疑惑难解 虽然测试环境不行还是测了下 仅供参考

**以下为不正经测试**

- 内网环境
- IDM单线程下载
- 服务端 vmess+tcp
- 跑满100M端口

|  客户端加密方式  |  服务端CPU占用率  |
|  ----  |  ----  |
|  none  |  3%  |
|  aes-128-gcm  |  5%  |
|  chacha20-poly1305  |  6%  |

PS:切换为1000M内网环境时
客户端加密方式为none时可以跑满1000M内网 此时客户机CPU占用率100%
另外两种加密方式虽然也跑满了客户机的CPU 但是下行只在300M-500M浮动
所以最后还是切换为100M的内网环境来测试

**Comment by phlinhng** [comment]
https://github.com/v2ray/v2ray-core/issues/1257

**Comment by pfread** [comment]
个人测试
| 并发连接数                                                   | 1    | 2    | 4    | 8    |
| ------------------------------------------------------------ | ---- | ---- | ---- | ---- |
| iperf直接对接 / 连接 数据量：iperf持续传输60s 速度（Gbits/sec） | 44.8 | 49.3 | 44.1 | 56.5 |
| v2ray直接对接 / 连接 数据量：iperf持续传输60s 速度（Gbits/sec） | 19.5 | 26.5 | 30.2 | 30.7 |
| v2ray_none / 连接 数据量：iperf持续传输60s 速度（Gbits/sec） | 10.7 | 12.4 | 15.2 | 12.9 |
| v2ray_chacha20-poly1305 / 连接 数据量：iperf持续传输60s 速度（Gbits/sec） | 4.96 | 9.38 | 11.7 | 12.2 |
| v2ray_aes-128-gcm / 连接 数据量：iperf持续传输60s 速度（Gbits/sec） | 5.81 | 10.8 | 13.4 | 11.7 |
| Shadowsocks_aes-128-gcm / 连接 数据量：iperf持续传输60s 速度（Gbits/sec） | 6.07 | 11.1 | 14.3 | 12.5 |
| Shadowsocks_chacha20-poly1305 / 连接 数据量：iperf持续传输60s 速度（Gbits/sec） | 5.02 | 9.38 | 12.5 | 11.9 |
| Shadowsocks_aes-256-gcm / 连接 数据量：iperf持续传输60s 速度（Gbits/sec） | 5.91 | 10.9 | 14.0 | 12.3 |
| Shadowsocks_chacha20-ietf-poly1305  / 连接 数据量：iperf持续传输60s 速度（Gbits/sec） | 5.04 | 9.45 | 12.6 | 12.0 |
| Shadowsocks_aes-128-cfb / 连接 数据量：iperf持续传输60s 速度（Gbits/sec） | 2.34 | 4.42 | 6.17 | 6.61 |
| Shadowsocks_chacha20 / 连接 数据量：iperf持续传输60s 速度（Gbits/sec） | 1.79 | 3.45 | 4.97 | 5.24 |
| Shadowsocks_aes-256-cfb / 连接 数据量：iperf持续传输60s 速度（Gbits/sec） | 2.23 | 4.21 | 5.92 | 6.52 |
| Shadowsocks_chacha20-ietf / 连接 数据量：iperf持续传输60s 速度（Gbits/sec） | 1.79 | 3.43 | 4.81 | 5.21 |
