### ISSUE TITLE
是否应该将中国公司控制的海外ip地址一并列入geoip：cn？

### ISSUE THREAD

**Issue by 89650021** [v2ray/discussion#689]
今天测试的时候发现即使在配置文件里设置了block访问cn的网站和ip，开启代理之后墙内一些app还能使用。查看日志发现是因为vps在海外，所以解析到了海外的ip，规则并未生效。路由的目的之一是避免翻墙时访问国内网站，从而导致vps ip地址泄露或者身份被关联。个人认为如果发生了这种情况非常危险。

**Comment by kingwilliam** [comment]
可否给 客户config 和 log 看看

**Comment by phlinhng** [comment]
这个可以直接去 https://github.com/v2ray/domain-list-community 项目提 issue

**Comment by kslr** [comment]
用geo
