### ISSUE TITLE
关于v2ray与shadowsocks一起使用的问题

### ISSUE THREAD

**Issue by FatChou** [v2ray/discussion#69]
1、如果客户端是v2ray（如iOS、Android），服务器是使用的其他的shadowsocks，是否可以转发
2、客户端和服务端都是v2ray，对各个端的v2ray版本有要求吗？

**Comment by VictoriaRaymond** [comment]
1. 可以
2. https://v2ray.com/chapter_00/faq.html#backward-compatibility
