### ISSUE TITLE
Caddy 2 怎么反代 V2ray http2 ？

### ISSUE THREAD

**Issue by Abderrian** [v2ray/discussion#693]
我按照这里（ https://github.com/veekxt/v2ray-template ）的模版
把Caddy 1的Caddyfile
```
proxy /veekxt_test https://127.0.0.1:44222  {
        header_upstream Host "veekxt.com"
        header_upstream X-Forwarded-Proto "https"
        insecure_skip_verify
    }
```
改成了Caddy 2 的Caddyfile
```
reverse_proxy /veekxt_test https://127.0.0.1:44222 {
        header_up Host veekxt.com
        header_up X-Forwarded-Proto https
        transport http {
            tls_insecure_skip_verify
        }
    }
```
但就是连不上，服务器端的v2ray连debug log都没有。我直接用浏览器访问则返回200，也就是能成功连接。
使用Caddy 1能正常连接。难道是我的Caddy 2 的Caddyfile不对吗？

**Comment by Abderrian** [comment]
难道没有人更新到Caddy 2吗？你们都能用Caddy 2反代V2ray吗？

**Comment by kingwilliam** [comment]
我都有用caddy, 但Caddy2比Caddy1真的相差太远 例如error handle，我都不知caddy2想甚样 所以现在还留在Caddy1.

**Comment by caozhengi** [comment]
@Abderrian 楼主有解决么？ 我也遇到了相同的问题

**Comment by Abderrian** [comment]
@caozhengi 没有。我试了websocket也不能被Caddy 2反代。

**Comment by kingwilliam** [comment]
```
:44343
tls /rsa_crt.pem /rsa_key.pem
reverse_proxy /path 127.0.0.1:1071
```

我做Caddy2 lab tests时, Caddyfile 是用这样的, 希望有帮助

**Comment by mixool** [comment]
> @caozhengi 没有。我试了websocket也不能被Caddy 2反代。

解决：https://github.com/v2fly/v2ray-step-by-step/issues/170

**Comment by Abderrian** [comment]
@mixool 这样不是通过path代理，为什么用path代理就不行啊？是Caddy 2的bug吗？还有http2又怎么代理？

**Comment by o0HalfLife0o** [comment]
ws其实不用任何设置就能直接反代了
`reverse_proxy /mmtls localhost:11443`

**Comment by mixool** [comment]
> @mixool 这样不是通过path代理，为什么用path代理就不行啊？是Caddy 2的bug吗？还有http2又怎么代理？

多个match应该就可以了吧

@websockets {
header Connection Upgrade
header Upgrade websocket
path /test
}

**Comment by W0n9** [comment]
> @mixool 这样不是通过path代理，为什么用path代理就不行啊？是Caddy 2的bug吗？还有http2又怎么代理？  
```
route /veekxt_test* {
        uri strip_prefix /veekxt_test
        reverse_proxy * localhost:10000 {
            header_up -Origin
        }
    }
```
主要是因为你这种情况v2ray后端识别的是```/```，Caddy2传过去的是```/veekxt_test```，用```uri strip_prefix```把```/veekxt_test```去掉就行，不是Caddy2的Bug

**Comment by proxysu** [comment]
Caddy 2在版本2.1.0就已经支持H2C。（https://github.com/caddyserver/caddy/releases/tag/v2.1.0）
但是实际使用中，并不能与V2Ray的H2C模式相适配，原因是Caddy 2存在一个Bug。
这个Bug在最新的测试版v2.2.0-rc.1中已经修复，我下载这个测试版，在测试中已经Caddy 2的H2C已经可以与V2Ray的H2C搭配使用。各个配置文件模板如下：
Caddy 2配置文件：https://github.com/proxysu/windows/blob/master/TemplateConfg/Http2Web_server_config.caddyfile
V2Ray服务端配置：https://github.com/proxysu/windows/blob/master/TemplateConfg/Http2Web_server_config.json
V2Ray客户端：https://github.com/proxysu/windows/blob/master/TemplateConfg/Http2Web_client_config.json
安装Caddy 2的测试版v2.2.0-rc.1命令如下：
wget https://github.com/caddyserver/caddy/releases/download/v2.2.0-rc.1/caddy_2.2.0-rc.1_linux_arm64.deb
apt install ./caddy_2.2.0-rc.1_linux_arm64.deb
systemctl enable caddy
系统Debian 9

不急用的，可以等Caddy 2的v2.2.0正式版出来。
