### ISSUE TITLE
配置如下，但是一台机器可以连接，另一台不行，是不是有什么限制呢

### ISSUE THREAD

**Issue by RicharDKcoder** [v2ray/discussion#695]
{
	"log": {
		"error": "",
		"loglevel": "debug",
		"access": ""
	},
	"inbounds": [{
			"listen": "127.0.0.1",
			"protocol": "socks",
			"settings": {
				"udp": false,
				"auth": "noauth"
			},
			"port": "1080"
		},
		{
			"listen": "127.0.0.1",
			"protocol": "http",
			"settings": {
				"timeout": 720
			},
			"port": "1087"
		}
	],
	"outbounds": [{
			"mux": {
				"enabled": false,
				"concurrency": 8
			},
			"protocol": "vmess",
			"streamSettings": {
				"wsSettings": {
					"path": "/×××××",
					"headers": {
						"host": "×××××"
					}
				},
				"tlsSettings": {
					"allowInsecure": true
				},
				"security": "tls",
				"network": "ws"
			},
			"tag": "proxy",
			"settings": {
				"vnext": [{
					"address": "",
					"users": [{
						"id": "******",
						"alterId": 68,
						"level": 1,
						"security": "auto"
					}],
					"port": 443
				}]
			}
		},
		{
			"tag": "direct",
			"protocol": "freedom",
			"settings": {
				"domainStrategy": "AsIs",
				"redirect": "",
				"userLevel": 0
			}
		},
		{
			"tag": "block",
			"protocol": "blackhole",
			"settings": {
				"response": {
					"type": "none"
				}
			}
		}
	],
	"dns": {},
	"routing": {
		"settings": {
			"domainStrategy": "AsIs",
			"rules": []
		}
	},
	"transport": {}
}

{ 
     "log": { 
     "loglevel": "info", 
       "access": "/var/log/v2ray/access.log", 
      "error": "/var/log/v2ray/error.log" 
      }, 
       "inbounds": [
           { 
             "port": 25160, 
             "protocol": "vmess", 
              "settings": { 
                    "clients": [
                           { "id": "×××××××", 
                          "level": 1, 
                           "alterId": 68 }
                     ] 
              }, 
              "streamSettings": { 
                   "network": "ws", 
                   "wsSettings": { 
                         "path": "/×××××", 
                         "headers": { 
                             "Host": "×××××" 
                         } 
                    } 
              }, 
              "listen": "127.0.0.1" 
            }], 
           "outbounds": [
               { "protocol": "freedom", "settings": {} }, 
              { "protocol": "blackhole", "settings": {}, 
                  "tag": "blocked" }
             ], 
            "routing": { 
                "rules": [
                     { "type": "field", 
                      "ip": ["geoip:private"], 
                      "outboundTag": "blocked" }
                 ] 
            } 
}

**Comment by RicharDKcoder** [comment]
#694 #692

**Comment by kslr** [comment]
如果你不按照要求提问，并且重复发布的话，我将设置为SPAM信息
