### ISSUE TITLE
v2ray会不凉大家快讨论讨论这是怎么回事

### ISSUE THREAD

**Issue by QZX991** [v2ray/discussion#696]
(虽然有点长，请大家耐心看完这些内容也是关乎你的利益)现在v2rayn和v2rayng已经有将近一个月未进行任何更新。电脑端还有一些客户端仍在更新维护。不过手机端已经没有任何的客户端在更新。手机只有三款，支持v2ray的客户端。两款在去年已经不更新了。如果按着v2rayNG平常的更新频率看这么久不更新已经很不正常了。v2rayn基本没有什么bug如果有的话也是界面上的一些问题和汉化。总之不影响使用。但是v2rayng有很严重的bug。连接时间一长就会网络延迟剧增而且非常卡顿。以及未来有可能不支持新的安卓系统，兼容性如果不更新就会下来。久而久之，未来手机端有可能陷入无法科/学/上/网的情况。因为没有软件可用。为什么我会这么想，也是有原因的就比如一款老的软件安卓1.0~8.0可以用9.0就用不了。未来很有可能安卓10.0用不了ng客户端。现在虽然不排除还有clash和surfboard客户端还能使用。不过这个对个人用户来说是很不友好的。因为他们都是要写订阅链接，自己搭的节点使用起来会相当困难。(软路由也可以应该还能用)不过成本也会非常高。 希望有人能再做手机客户端谢谢。

**Comment by QZX991** [comment]
这些都非常重要，请大家耐心看完，谢谢。

**Comment by QZX991** [comment]
再补充一下我上述提到的那两个clash和surfboard这两个客户端，一般个人是用不了的。因为要写订阅链

**Comment by DolorHunter** [comment]
> 
> 
> 再补充一下我上述提到的那两个clash和surfboard这两个客户端，一般个人是用不了的。因为要写订阅链

你可以自己生成订阅信息. 复制自己的配置信息, 用 BASE64 加密, 然后再放到一个公共空间就行了. 挺简单的, Google一下.

**Comment by kslr** [comment]
所有的东西都在进步，如果希望一劳永逸是不可能的，除非那天墙倒了

**Comment by DolorHunter** [comment]
V2rayNG 一直都几个月更一次新版本, 不用太担心停更(一月一更还算快的了). Bifrost 就更慢了, 上次更新都一年了. 其他安卓平台软件没有用过不清楚. 这些软件似乎都是个人或者社区利用空闲时间在维护的软件, 一个月两个月更新一个版本, 其实不能算慢了.

实在不行跳来用 iOS. shadowrocket 更的比较勤, 而且也不怎么会出现你说的那些问题.

**Comment by QZX991** [comment]
> > 再补充一下我上述提到的那两个clash和surfboard这两个客户端，一般个人是用不了的。因为要写订阅链
> 
> 你可以自己生成订阅信息. 复制自己的配置信息, 用 BASE64 加密, 然后再放到一个公共空间就行了. 挺简单的, Google一下.

可是网上搜不到clash怎么写进链接

**Comment by QZX991** [comment]
谷歌上搜不到油管上没教程。这就很尴尬。

**Comment by QZX991** [comment]
如果有教程的话，能不能给个链接？谢谢！

**Comment by phlinhng** [comment]
> 可是网上搜不到clash怎么写进链接

https://github.com/Dreamacro/clash    
https://github.com/limbopro/Profiles    

你的烦恼基本上都来自你的搜索能力与专业认知不足而产生的杞人忧天

**Comment by kslr** [comment]
如果没有教程，你用翻译软件通读一下，也能了解个大概。
还是静下心吧，把中文也好好排版一下。

**Comment by phlinhng** [comment]
> 你可以自己生成订阅信息. 复制自己的配置信息, 用 BASE64 加密, 然后再放到一个公共空间就行了. 挺简单的, Google一下.

@DolorHunter 忍不住要说一下，BASE64 是明文编码不是加密。

**Comment by DolorHunter** [comment]
> > 你可以自己生成订阅信息. 复制自己的配置信息, 用 BASE64 加密, 然后再放到一个公共空间就行了. 挺简单的, Google一下.
> 
> @DolorHunter BASE64 是明文编码不是加密。

感谢指正。看到encode就情不自禁联想到encrypt。xd

**Comment by QZX991** [comment]
如果v2ray停止更新后，还会有新的传输协议接替吗？还是像SSR那样没人更新，但是还有人用。

**Comment by QZX991** [comment]
ssr V2ray这个是主流的传输协议还有三个比较不主流。

**Comment by QZX991** [comment]
> V2rayNG 一直都几个月更一次新版本, 不用太担心停更(一月一更还算快的了). BifrostV 就更慢了, 上次更新都一年了. 其他安卓平台软件没有用过不清楚. 这些软件似乎都是个人或者社区利用空闲时间在维护的软件, 一个月两个月更新一个版本, 其实不能算慢了.
> 
> 实在不行跳来用 iOS. shadowrocket 更的比较勤, 而且也不怎么会出现你说的那些问题.

我估计BifrostV可能彻底不更新

**Comment by QZX991** [comment]
如果一个传输协议长时间不更新的话，就有可能像ssr那样特别容易被墙

**Comment by QZX991** [comment]
当然这不排除v2ray的一些高级玩法ws tls nginx cdn
