### ISSUE TITLE
求问Nginx+cloudflare+v2ray的问题

### ISSUE THREAD

**Issue by Weaxs** [v2ray/discussion#699]
我的nginx的ssl证书用的是cloudflare的。nginx的conf上定义了lacation /v2ray，v2ray的config中定义了"path": "/v2ray"，端口号什么的也没有问题。nginx服务器主界面的index.html是没有问题看可以打开的。但是客户端连接v2ray会超时，同时使用v2ray命令查看配置文件，告诉我配置文件的path是/，启动v2ray时的config.json就是我改的那个，目前不太清楚问题出在了哪里？有人知道原因吗谢谢

**Comment by DolorHunter** [comment]
Nginx 没配好吧.

**Comment by Weaxs** [comment]
location /v2ray {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:10000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
	#proxy_read_timeout 300s;
	proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

nginx有关v2ray配置如上，域名主页的Welcome to nginx!是可以显示出来的

**Comment by DolorHunter** [comment]
我猜可能是有多个 conf 相互冲突/覆盖了. 不然怎么会出现 path 不匹配. 你在这个 conf 里面换一个root 和 index 信息试试页面会不会变.

如果不变的话, 你检查看看是不是 /etc/nginx/sites-available/ 或者 /etc/nginx/sites-enabled/ 或者 /etc/nginx/conf 里面有多个配置, 某些块互相之间可能覆盖掉了.

如果不是这个情况的话, 你可能要贴出完整配置才能判断是什么问题.

**Comment by Weaxs** [comment]
AWS界面上防火墙需要开启端口，我一直用的iptables命令(
感谢解答
