### ISSUE TITLE
support go module/go mod import for 1.11 and beyond

### ISSUE THREAD

**Issue by MittWillson** [v2ray/discussion#70]
是否可以支持go module的import规则

go module 只支持名称为 `vX.X.X` 格式的 Tag 作为版本引入，所以目前v2ray-core使用的 `vX.X` 会导致go mod不认，目前只能认 `v4.1.1` 作为最新版本

虽然有 `v0.0.0-xxxxx-xxxxxxx` 的脏方法去引入最新的v2ray-core，但不是很有效的方法

关于 Go mod 相关说明: https://github.com/golang/go/wiki/Modules
关于 语义化版本 相关说明: https://semver.org/

**Comment by Rucc1** [comment]
https://twitter.com/projectv2ray/status/1050073273596297216

**Comment by MittWillson** [comment]
@Rucc1 这就太遗憾了, 我虽然并不认同go mod, 但我认为是一种可行的解决方案

**Comment by VictoriaRaymond** [comment]
Go mod目前不会给v2ray带来直接的好处:

* 主要的依赖 miekg/dns、gorilla/websocket、x/net 都没有上go mod
* 目前的双repo开发环境（v2ray.com/core 和 v2ray.com/ext）不受go mod支持

在1.12之前不会考虑这一机制
