### ISSUE TITLE
所有应用程序都打不开（附可能的log中的bug行）

### ISSUE THREAD

**Issue by LukeHXC** [v2ray/discussion#700]
先声明一下，本人是小白完全不懂程序啥的。。。
下载了github上的安装包后几个应用程序都打不开 
不是打开报错就是打开后几秒钟就自己关了。
后来自己去看log发现了可能的问题，描述如下：
System.MissingMethodException: Method not found: 'Void System.Runtime.InteropServices.Marshal.StructureToPtr(!!0, IntPtr, Boolean)'.
请教各位大佬这是什么问题...

**Comment by kslr** [comment]
你用什么工具就到那边问，这个错误帮助不了你
