### ISSUE TITLE
更新v2ray 失败 

### ISSUE THREAD

**Issue by ishaifeng** [v2ray/discussion#701]
Archive:  /tmp/v2ray/v2ray.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/v2ray/v2ray.zip or
        /tmp/v2ray/v2ray.zip.zip, and cannot find /tmp/v2ray/v2ray.zip.ZIP, period.
Failed to extract V2Ray.

**Comment by kslr** [comment]
手动替换
