### ISSUE TITLE
大概一周前开始所有自建v2ray都失效了

### ISSUE THREAD

**Issue by ryogishiki** [v2ray/discussion#703]
主机在vultr和linode上都有，试了电脑和手机上许多客户端版本，也试了新建主机，还有去其他vps上重新搭建，都一样，连接后没有数据，日志显示unable to find destination或者all attempts failed

**Comment by SekiBetu** [comment]
所有？那我们现在用的是什么

**Comment by 1265578519** [comment]
vmess全被墙了，你换个端口，同时换ws模式就行了。。我就这样复活了
vmess撑不到半天就没了，ws用快一周了都没事

**Comment by DolorHunter** [comment]
就目前情况看来 VMESS 协议可能要废弃(设计和实现缺陷), 从而更换新的协议了.

https://github.com/v2ray/v2ray-core/issues/2523

**Comment by bbhxwl** [comment]
> 主机在vultr和linode上都有，试了电脑和手机上许多客户端版本，也试了新建主机，还有去其他vps上重新搭建，都一样，连接后没有数据，日志显示unable to find destination或者all attempts failed

哪位大佬知道添加200个uuid的时候，为什么程序就不能连接了么？
