### ISSUE TITLE
既然cilent有特征问题，那么手机端的各个客户端呢？

### ISSUE THREAD

**Issue by woshiniming007** [v2ray/discussion#707]
如题，目前android端的、ios端的都存在问题吧？恐怕还要很久才能全更新修复完吧？以后一不小心用了个以前版本的，就会把服务器搞挂了

**Comment by HanadaLee** [comment]
v2rayNG已经更新（还没上架Google Play），iOS估计要等新版上架商店。

**Comment by cxy5014** [comment]
iOS的shadowrocket不受影响，使用clash的也不受影响。

**Comment by HanadaLee** [comment]
> iOS的shadowrocket不受影响，使用clash的也不受影响。

那quantumult、quantumultX、kitsunebi是否受影响（没测过不太了解）

**Comment by mischief1** [comment]
> iOS的shadowrocket不受影响，使用clash的也不受影响。

 安卓端的BifrostV 受影响吗？

**Comment by HanadaLee** [comment]
> > iOS的shadowrocket不受影响，使用clash的也不受影响。
> 
> 安卓端的BifrostV 受影响吗？

有影响，BifrostV的v2ray-core甚至停留在4.19版本，已经十分老旧了。

**Comment by 1309654031** [comment]
个人觉得ios端的kitsunebi和i2ray会有问题，因为只有这两个直接使用了v2ray的内核，shadowrocket和quantumult (x)也许不会有问题
