### ISSUE TITLE
[疑问]Server多IP情况下如何指定用户指定IP-Free-Out

### ISSUE THREAD

**Issue by PPPPPPPPz** [v2ray/discussion#71]
1. 你正在使用哪个版本的 V2Ray？
v4.3

2. 你的使用场景是什么？
Chrome ==>**socks**==> **Client** ==>**vmess**==> **Server** ==>**free**==> Internet

3. 你看到的不正常的现象是什么？
服务器有 1.1.1.1(主), 2.2.2.2, 3.3.3.3 三个公网IP地址（另外两个IP配置在同张网卡上）；
V2Ray 运行后，无法使用 2.2.2.2 与 3.3.3.3 连接 V2Ray 的业务端口；
本意是想 Client 连接 2.2.2.2 时，Free-Out 也使用 2.2.2.2 为出口。（3.3.3.3同理）

4. 你期待看到的正确表现是怎样的？
看到路由配置里，可以建立以user'(邮箱地址)为条件的判定规则并指定转发路径，但是 Free-OUT 该怎么写，以能达到使用不同的 IP 为出口的目的没有思路……
```
{
    "inbounds": [
        {
            "protocol": "vmess",
            "port": 123,
            "settings": {
                "clients": [
                    {
                        "id": "UUID-UUID-UUID-UUID-1",
                        "email": "user1@v2ray.com"
                    },
                    {
                        "id": "UUID-UUID-UUID-UUID-2",
                        "email": "user2@v2ray.com"
                    }
                ]
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {},
            "tag": "free-out"
        }
    ],
    "routing": {
        "domainStrategy": "IPOnDemand",
        "rules": [
            {
                "type": "field",
                "user": [
                    "user2@v2ray.com"
                ],
                "outboundTag": "free-out???"
            }
        ]
    }
}
```

**Comment by PPPPPPPPz** [comment]
刚才仔细阅览了下手册，不确定这样行不行？

```
{
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {}
        },
        {
            "protocol": "freedom",
            "settings": {},
            "sendThrough": "2.2.2.2",
            "tag": "free-ip2-out"
        }
    ],
    "routing": {
        "domainStrategy": "IPOnDemand",
        "rules": [
            {
                "type": "field",
                "user": [
                    "user2@v2ray.com"
                ],
                "outboundTag": "free-ip2-out"
            }
        ]
    }
}
```

**Comment by zackvv** [comment]
大神能具体指教下吗？

**Comment by PPPPPPPPz** [comment]
@zackvv 
UUID1 / UUID2 / UUID3 分别对应不同的 IP 出口 1.1.1.1 / 2.2.2.2 / 3.3.3.3

服务器端配置(WebSocket+TLS)示例如下：
```
{
    "inbounds": [
        {
            "protocol": "vmess",
            "port": "xxxx",
            "listen": "127.0.0.1",
            "settings": {
                "clients": [
                    {
                        "id": "UUID1",
                        "alterId": 4,
                        "email": "user1@v2ray.com"
                    },
                    {
                        "id": "UUID2",
                        "alterId": 4,
                        "email": "user2@v2ray.com"
                    },
                    {
                        "id": "UUID3",
                        "alterId": 4,
                        "email": "user3@v2ray.com"
                    }
                ]
            },
            "streamSettings": {
                "network": "ws"
            }
        }
    ],
    "outbounds": [
        {
            "sendThrough": "1.1.1.1",
            "protocol": "freedom",
            "settings": {},
            "tag": "ip1"
        },
        {
            "sendThrough": "2.2.2.2",
            "protocol": "freedom",
            "settings": {},
            "tag": "ip2"
        },
        {
            "sendThrough": "3.3.3.3",
            "protocol": "freedom",
            "settings": {},
            "tag": "ip3"
        }
    ],
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "type": "field",
                "user": [
                    "user1@v2ray.com"
                ],
                "outboundTag": "ip1"
            },
            {
                "type": "field",
                "user": [
                    "user2@v2ray.com"
                ],
                "outboundTag": "ip2"
            },
            {
                "type": "field",
                "user": [
                    "user3@v2ray.com"
                ],
                "outboundTag": "ip3"
            }
        ]
    },
    "transport": {
        "wsSettings": {
            "path": "/xxx"
        }
    }
}
```

**Comment by zackvv** [comment]
> @zackvv
> UUID1 / UUID2 / UUID3分别对应不同的IP出口1.1.1.1 / 2.2.2.2 / 3.3.3.3
> 
> 服务器端配置（WebSocket + TLS）示例如下：
> 
> ```
> {
>     "inbounds": [
>         {
>             "protocol": "vmess",
>             "port": "xxxx",
>             "listen": "127.0.0.1",
>             "settings": {
>                 "clients": [
>                     {
>                         "id": "UUID1",
>                         "alterId": 4,
>                         "email": "user1@v2ray.com"
>                     },
>                     {
>                         "id": "UUID2",
>                         "alterId": 4,
>                         "email": "user2@v2ray.com"
>                     },
>                     {
>                         "id": "UUID3",
>                         "alterId": 4,
>                         "email": "user3@v2ray.com"
>                     }
>                 ]
>             },
>             "streamSettings": {
>                 "network": "ws"
>             }
>         }
>     ],
>     "outbounds": [
>         {
>             "sendThrough": "1.1.1.1",
>             "protocol": "freedom",
>             "settings": {},
>             "tag": "ip1"
>         },
>         {
>             "sendThrough": "2.2.2.2",
>             "protocol": "freedom",
>             "settings": {},
>             "tag": "ip2"
>         },
>         {
>             "sendThrough": "3.3.3.3",
>             "protocol": "freedom",
>             "settings": {},
>             "tag": "ip3"
>         }
>     ],
>     "routing": {
>         "domainStrategy": "AsIs",
>         "rules": [
>             {
>                 "type": "field",
>                 "user": [
>                     "user1@v2ray.com"
>                 ],
>                 "outboundTag": "ip1"
>             },
>             {
>                 "type": "field",
>                 "user": [
>                     "user2@v2ray.com"
>                 ],
>                 "outboundTag": "ip2"
>             },
>             {
>                 "type": "field",
>                 "user": [
>                     "user3@v2ray.com"
>                 ],
>                 "outboundTag": "ip3"
>             }
>         ]
>     },
>     "transport": {
>         "wsSettings": {
>             "path": "/xxx"
>         }
>     }
> }
> ```

大神首先感谢您的回复，我测试只要加入 "listen": "127.0.0.1", 或者"listen": "111.230.263.xx",或者"listen": "10.0.0.1",就会导致链接不上了。out参数加入也不行，只加入多用户是可行的。

**Comment by 87502560** [comment]
> > @zackvv
> > UUID1 / UUID2 / UUID3分别对应不同的IP出口1.1.1.1 / 2.2.2.2 / 3.3.3.3
> > 服务器端配置（WebSocket + TLS）示例如下：
> > ```
> > {
> >     "inbounds": [
> >         {
> >             "protocol": "vmess",
> >             "port": "xxxx",
> >             "listen": "127.0.0.1",
> >             "settings": {
> >                 "clients": [
> >                     {
> >                         "id": "UUID1",
> >                         "alterId": 4,
> >                         "email": "user1@v2ray.com"
> >                     },
> >                     {
> >                         "id": "UUID2",
> >                         "alterId": 4,
> >                         "email": "user2@v2ray.com"
> >                     },
> >                     {
> >                         "id": "UUID3",
> >                         "alterId": 4,
> >                         "email": "user3@v2ray.com"
> >                     }
> >                 ]
> >             },
> >             "streamSettings": {
> >                 "network": "ws"
> >             }
> >         }
> >     ],
> >     "outbounds": [
> >         {
> >             "sendThrough": "1.1.1.1",
> >             "protocol": "freedom",
> >             "settings": {},
> >             "tag": "ip1"
> >         },
> >         {
> >             "sendThrough": "2.2.2.2",
> >             "protocol": "freedom",
> >             "settings": {},
> >             "tag": "ip2"
> >         },
> >         {
> >             "sendThrough": "3.3.3.3",
> >             "protocol": "freedom",
> >             "settings": {},
> >             "tag": "ip3"
> >         }
> >     ],
> >     "routing": {
> >         "domainStrategy": "AsIs",
> >         "rules": [
> >             {
> >                 "type": "field",
> >                 "user": [
> >                     "user1@v2ray.com"
> >                 ],
> >                 "outboundTag": "ip1"
> >             },
> >             {
> >                 "type": "field",
> >                 "user": [
> >                     "user2@v2ray.com"
> >                 ],
> >                 "outboundTag": "ip2"
> >             },
> >             {
> >                 "type": "field",
> >                 "user": [
> >                     "user3@v2ray.com"
> >                 ],
> >                 "outboundTag": "ip3"
> >             }
> >         ]
> >     },
> >     "transport": {
> >         "wsSettings": {
> >             "path": "/xxx"
> >         }
> >     }
> > }
> > ```
> 
> 大神首先感谢您的回复，我测试只要加入 "listen": "127.0.0.1", 或者"listen": "111.230.263.xx",或者"listen": "10.0.0.1",就会导致链接不上了。out参数加入也不行，只加入多用户是可行的。

大神求助啊

**Comment by 87502560** [comment]
> > @zackvv
> > UUID1 / UUID2 / UUID3分别对应不同的IP出口1.1.1.1 / 2.2.2.2 / 3.3.3.3
> > 服务器端配置（WebSocket + TLS）示例如下：
> > ```
> > {
> >     "inbounds": [
> >         {
> >             "protocol": "vmess",
> >             "port": "xxxx",
> >             "listen": "127.0.0.1",
> >             "settings": {
> >                 "clients": [
> >                     {
> >                         "id": "UUID1",
> >                         "alterId": 4,
> >                         "email": "user1@v2ray.com"
> >                     },
> >                     {
> >                         "id": "UUID2",
> >                         "alterId": 4,
> >                         "email": "user2@v2ray.com"
> >                     },
> >                     {
> >                         "id": "UUID3",
> >                         "alterId": 4,
> >                         "email": "user3@v2ray.com"
> >                     }
> >                 ]
> >             },
> >             "streamSettings": {
> >                 "network": "ws"
> >             }
> >         }
> >     ],
> >     "outbounds": [
> >         {
> >             "sendThrough": "1.1.1.1",
> >             "protocol": "freedom",
> >             "settings": {},
> >             "tag": "ip1"
> >         },
> >         {
> >             "sendThrough": "2.2.2.2",
> >             "protocol": "freedom",
> >             "settings": {},
> >             "tag": "ip2"
> >         },
> >         {
> >             "sendThrough": "3.3.3.3",
> >             "protocol": "freedom",
> >             "settings": {},
> >             "tag": "ip3"
> >         }
> >     ],
> >     "routing": {
> >         "domainStrategy": "AsIs",
> >         "rules": [
> >             {
> >                 "type": "field",
> >                 "user": [
> >                     "user1@v2ray.com"
> >                 ],
> >                 "outboundTag": "ip1"
> >             },
> >             {
> >                 "type": "field",
> >                 "user": [
> >                     "user2@v2ray.com"
> >                 ],
> >                 "outboundTag": "ip2"
> >             },
> >             {
> >                 "type": "field",
> >                 "user": [
> >                     "user3@v2ray.com"
> >                 ],
> >                 "outboundTag": "ip3"
> >             }
> >         ]
> >     },
> >     "transport": {
> >         "wsSettings": {
> >             "path": "/xxx"
> >         }
> >     }
> > }
> > ```
> 
> 大神首先感谢您的回复，我测试只要加入 "listen": "127.0.0.1", 或者"listen": "111.230.263.xx",或者"listen": "10.0.0.1",就会导致链接不上了。out参数加入也不行，只加入多用户是可行的。

大神，證書放哪裏？可配合X-UI使用嗎？
