### ISSUE TITLE
win10电脑使用v2ray后，开启热点，其他设备连接该热点，但是其他设备仍然无法连接google

### ISSUE THREAD

**Issue by youmu1998** [v2ray/discussion#712]
win10电脑使用v2ray后，开启热点，其他设备连接该热点，但是其他设备仍然无法连接google。

**Comment by bbhxwl** [comment]
让别的设备使用socks5 应该可以。

**Comment by youmu1998** [comment]
> 让别的设备使用socks5 应该可以。

我试了一下，有一点很迷就是其他设备设置代理的时候要在v2ray的监听端口基础上加一才能够成功连接google。不知道为什么

**Comment by kslr** [comment]
这和你的客户端大概有关

**Comment by bbhxwl** [comment]
> 这和你的客户端大概有关

确实，谢谢您的提醒，我用netch好像不行，别的客户端可以，太谢谢您了。

**Comment by youmu1998** [comment]
emmmm，现在是用一台电脑做代理，其他设备也连入相同的路由器，现在手机和平板都是直接通过设置proxy，并且端口加1，就可以访问google，但是ubuntu设置了http_proxy=http://ip:10809还是连不上去，都是一样的设置参数，但是ubuntu死活连不上去，求大佬指教

**Comment by kslr** [comment]
你只设置了终端下的http 应该包含
Http
Https
All

**Comment by youmu1998** [comment]
> 你只设置了终端下的http 应该包含
> Http
> Https
> All

所有这些的代理都直接设置为http://ip:10809 吗

**Comment by youmu1998** [comment]
还有就是我直接在ubuntu里面装了v2ray，之后terminal还是ping不通google，请问这里该怎么设置呢

**Comment by youmu1998** [comment]
然后我刚刚试了一下
``export all_proxy=http://ip:10809
 export http_proxy=http://ip:10809
export https_proxy=https://ip:10809``
还是ping不通

**Comment by youmu1998** [comment]
我把all改为"all_proxy=socks://ip:10808"还是不行

**Comment by kslr** [comment]
"icmp proxy"

**Comment by WulfricLee** [comment]
> 还有就是我直接在ubuntu里面装了v2ray，之后terminal还是ping不通google，请问这里该怎么设置呢
ping 是用 icmp 协议，你用 ping 测试是不会通的，你改成
```
curl www.google.com
```
