### ISSUE TITLE
V2ray透明代理不能转发UDP

### ISSUE THREAD

**Issue by yangcaixing** [v2ray/discussion#717]
我用v2ray做透明代理，目前tcp代理没问题，访问google也没问题，但我想转发udp，使DNS server能用8.8.8.8解析，目前UDP代理会有问题，有谁遇到相同的问题呢？
v2ray client配置：
{
  "inbounds": [
    {
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth",
        "udp": false
      }
    },
    {
   "port": 12345, 
   "protocol": "dokodemo-door",
   "settings": {
     "network": "tcp,udp",
     "followRedirect": true 
   },
   "sniffing": {
     "enabled": true,
     "destOverride": ["http", "tls"]
   },
   "streamSettings": {
     "sockopt": {
       "tproxy": "redirect" 
     }
   }

  }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "xxxxxx",
            "port": 443,
            "users": [
              {
                "id": "xxxxxxxx",
                "alterId": 64
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "wsSettings": {
          "path": "/xx"
        }
      },
      "mux": {
      "enabled": true,
      "concurrency": 1024
      }
    }
  ]
}
TCP代理 iptables:

iptables -t nat -N V2RAY

iptables -t nat -A V2RAY -p tcp -j REDIRECT --to-ports 12345

iptables -t nat -A PREROUTING  -p tcp -j V2RAY

UDP代理iptables:

ip rule add fwmark 1 table 100
ip route add local 0.0.0.0/0 dev lo table 100
iptables -t mangle -N V2RAY_MASK
iptables -t mangle -A V2RAY_MASK -p udp -j TPROXY --on-port 12345 --tproxy-mark 1
iptables -t mangle -A PREROUTING -p udp -j V2RAY_MASK

**Comment by zhaoyxdt** [comment]
....
"sniffing": {
"enabled": false,
....
"sockopt": {
"tproxy": "tproxy"
}
....

**Comment by BioniCosmos** [comment]
请确保网关上没有其他服务监听 UDP 53 端口。

**Comment by yunfengwangluo** [comment]
"settings": {
"auth": "noauth",
"udp": true
}

**Comment by BioniCosmos** [comment]
透明代理出问题与 Socks 协议有何关系？
