### ISSUE TITLE
使用 TCP + TLS 方案且用 HAProxy 分流的情况下，无法使用 CloudFlare 的 CDN 服务

### ISSUE THREAD

**Issue by Nick-Hopps** [v2ray/discussion#721]
参考的是 [新白话文指南](https://guide.v2fly.org/advanced/tcp_tls_web.html) 中的 TCP + TLS + Web 方案，配置好后可以正常使用

网页：https://v2ray-test.tk

![图片](https://user-images.githubusercontent.com/16911282/83591780-5434b900-a58b-11ea-9f51-51f4d03f5439.png)

在 CloudFlare 关闭 CDN 的情况下，网页和 v2ray 都可以正常访问

![图片](https://user-images.githubusercontent.com/16911282/83591891-9958eb00-a58b-11ea-909d-e6d8381d75cc.png)

一旦开启 CDN 代理，网页可以正常访问，但是 v2ray 就无法访问，测试连接情况显示如下：

![图片](https://user-images.githubusercontent.com/16911282/83592090-256b1280-a58c-11ea-85ae-737a658b22d7.png)

haproxy 和 v2ray 均无错误日志，cloudflare 仅设置 SSL/TLS 为 full，其他设置也试过都无效。我怀疑是 haproxy 配置的问题，然而刚接触这个软件不是很熟，有没有遇到同样问题的朋友？

**Comment by zhfreal** [comment]
免费版CF吧，别想了是不可以分发纯TCP流量，只能分发http和ws

**Comment by kdrx** [comment]
CloudFlare 免费的不能转发TCP

**Comment by Nick-Hopps** [comment]
原来如此。。。谢谢
