### ISSUE TITLE
Please discourage reporting security vulnerabilities publicly

### ISSUE THREAD

**Issue by Mygod** [v2ray/discussion#726]
The current security policy as-is is immensely flawed: https://github.com/v2ray/v2ray-core/blob/85633ec/SECURITY.md

For security purposes, I personally recommend not posting an issue *at all* until a fix has been issued in the future. Sometimes the fact that it is possible is already enough information for somebody else to figure out the solution. Maintainers should probably set up a security issue tracker/email to receive security reports privately.

CC commit author @nicholascw

**Comment by xiaokangwang** [comment]
Is is possible that we requires all disclosures issues contains zero details about issue in plain text and all related information and discussion encrypted. The issue submit should sign their encrypted report and V2 team's reply will be encrypted to V2's security report key and the the reporter's key. 

Once the solution is released, the encrypted discussion will be declassified.

**Comment by xiaokangwang** [comment]
This(Fully encrypted communication without any detail in plain text) can both allow user know a security issue is under developer's attention and provide a limited amount of transparency. 

This kind of limited transparency should pose little threat, since V2 team can swiftly develop and release fixes.

**Comment by Mygod** [comment]
I do not see why you need to release ciphertext of the conversation. There is no way for a third party to verify that the revealed plaintext matches the original ciphertext, unless you use some complicated encryption scheme. On the other hand, if you think that this should be the intended behavior, you can probably just open a corresponding tracking (empty) issue and fill in the details later.

Still I do not see any reason that the initial communication and end-user disclosure has to be done on GitHub. The practice of responsible disclosure is widely used in the industry, e.g. https://security.googleblog.com/2010/07/rebooting-responsible-disclosure-focus.html
