### ISSUE TITLE
V2ray配置流量统计出错

### ISSUE THREAD

**Issue by Schnappi-02** [v2ray/discussion#727]
### 参照新V2Ray白话文指南中的流量统计下的配置实例进行修改
https://guide.v2fly.org/advanced/traffic.html#%E9%85%8D%E7%BD%AE%E7%BB%9F%E8%AE%A1%E5%8A%9F%E8%83%BD
**以下是我修改后的配置**
[config.txt](https://github.com/v2ray/discussion/files/4728082/config.txt)

{
"stats": {},
    "api": {
        "tag": "api",
        "services": [
            "StatsService"
        ]
    },
"policy": {
        "levels": {
            "0": {
                "statsUserUplink": true,
                "statsUserDownlink": true
            }
        },
        "system": {
            "statsInboundUplink": true,
            "statsInboundDownlink": true
        }
    },
"inbound": [
    {
        "tag": "tcp",
        "protocol": "vmess",
	"listen": "127.0.0.1",
        "port": 2012,
        "settings": {
		    "clients": [
                {    
				     "email": "auser",
			         "id": "123456",
					 "level": 0
			    },
                {    
				     "email": "buser",
			         "id": "123456",
					 "level": 0
			    },  
                {
				     "email": "cuser",
					 "id": "123456",
					 "level": 0
				},
                {   
				     "email": "duser",
					 "id": "123456",
					 "level": 0
				},
                {
				     "email": "euser",
					 "id": "123456",
					 "level": 0
				}
            ]
		},
		"streamSettings": {
            "network": "ws",
            "wsSettings": {"path": "123456"}
        }
	},
    {   
        "listen": "127.0.0.1",
	    "port": 2012,
	    "protocol": "dokodemo-door",
	    "settings": {
	        "address": "127.0.0.1"
		},
	    "tag": "api"
    }
],
"outbound": {"protocol": "freedom"},
"routing": {
        "settings": {
            "rules": [
                {
                    "inboundTag": [
                        "api"
                    ],
                    "outboundTag": "api",
                    "type": "field"
                }
            ]
        },
        "strategy": "rules"
    }
}

**用测试命令/usr/bin/v2ray/v2ray -test -config=/etc/v2ray/config.json报错：**
V2Ray 4.23.4 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 linux/amd64)
A unified platform for anti-censorship.
main: failed to read config files: [/etc/v2ray/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: 
v2ctl> Read config:  /etc/v2ray/config.json
v2ctl> v2ray.com/core/infra/conf/serial: failed to read config file at line 21 char 12 > json: cannot unmarshal array into Go struct field Config.inbound of type conf.InboundDetourConfig > exit status 1

**无法将数组解组到Go struct字段配置中？？**
**不懂怎么修改才能正常使用，求解各位。**
**梯子是V2ray+WS+TLS+Web(Nginx)**
**安装方式为使用官方脚本安装后手动修改配置文件**

**Comment by Schnappi-02** [comment]
顶一下

**Comment by Schnappi-02** [comment]
顶一下

**Comment by rikkihamano** [comment]
> failed to execute v2ctl
