### ISSUE TITLE
v2ray下载速度慢，比下载到vps，再网页下载慢多了

### ISSUE THREAD

**Issue by jayvzh** [v2ray/discussion#730]
v2ray代理 ws+tls+nginx 模式 aes-128-gcm 加密，服务端客户端都是最新版
打开网页一般般，其实也有点慢，youtube默认720p
但是下载出奇的慢，比如下载github的文件，只有几k~十几k/s的速度

我用wget下载到vps，几秒就能下载完成，
然后用http下载回本地，能跑1M~5M/s，很快能下载完。

请问问题出在哪里？
我vps里已经有一定优化，也开了tcp fast open和魔改bbr
vps是200m带宽
这和开着udp和mux有关系吗，是不是udp被封锁了，关掉udp有用吗？

**Comment by kingwilliam** [comment]
有客户和服务器config才好讨论

**Comment by okudayukiko** [comment]
用`/etc/modules-load.d/`加载`/lib/modules/$(uname -r)/kernel/crypto`和`/lib/modules/$(uname -r)/kernel/arch/x86/crypto`的加密内核模块，比如：
`/etc/modules-load.d/encryption.conf`
`chacha20poly1305`
`chacha_generic`
`ecc`
`ecdh_generic`
`nhpoly1305`
`poly1305_generic`
`chacha-x86_64`
`poly1305-x86_64`
`aesni-intel`
`ghash-clmulni-intel`
`sha1-ssse3`
`sha256-ssse3`
`sha512-ssse3`
`nhpoly1305-sse2`
