### ISSUE TITLE
测试能连通 但是本地浏览器翻墙失败

### ISSUE THREAD

**Issue by QingFengpoor** [v2ray/discussion#732]
VPS中的操作系统是Ubuntu   
使用脚本 ** bash <(curl -s -L https://git.io/v2ray.sh) ** 安装的v2ray 
然后window10中的客户端建立了对应的Vmess服务器，并开启Pac模式。
![image](https://user-images.githubusercontent.com/24737114/83941472-2f0ba900-a81e-11ea-83ce-dd178173ac64.png)
![image](https://user-images.githubusercontent.com/24737114/83941475-3a5ed480-a81e-11ea-8e66-8745283f8d78.png)

测试服务器的真连接延迟，Ubuntu中有记录，但是Windows中的浏览器（edge 浏览器）打不开google.com
![image](https://user-images.githubusercontent.com/24737114/83941454-f966c000-a81d-11ea-8444-0ed66838ed24.png)
请大家指导一下 是哪里出了问题

**Comment by cppr** [comment]
use HTTP or SOCKS proxy and see if it works
