### ISSUE TITLE
请教一下V2ray为什么不能从数据库读取用户信息呢

### ISSUE THREAD

**Issue by HongyanShen** [v2ray/discussion#733]
为什么V2ray不能从数据库读取用户信息呢？
如果将V2ray部署到多个节点的话，用户信息如何同步呢？

**Comment by CalmLong** [comment]
可以，先把用户信息保存在数据库中，然后从数据库中读取用户信息并用 gRPC 添加用户到 V2Ray 就可以了

**Comment by HongyanShen** [comment]
@CalmLong 也就是说v2ray core 只能被动接受，不能主动读取对吧？我理想的方式是v2ray在需要的时候可以主动去读，这样就避免了在多个v2ray节点的情况下需要挨个同步的问题。

**Comment by CalmLong** [comment]
你可以在添加用户的时候同时将用户通过 gRPC 添加到 V2Ray ，这样添加用户的同步就解决了。

要是 V2Ray 需要重启的话我觉得你可以用你自己的程序控制 V2Ray 关闭和启动，这样可以在重启之后将用户再发送给 V2Ray

**Comment by smallprogram** [comment]
最简单的办法，写一个维护json服务，API操作数据库CRUD用户数据。然后编辑config.json文件。restart v2ray。gRPC调用V2ray进行用户维护一旦重启配置将会失效。没有直接操作config.json来的实在
