### ISSUE TITLE
有没有捣鼓v2ray导致无法直接访问中国地区ip和网站的？

### ISSUE THREAD

**Issue by wuzechen** [v2ray/discussion#734]
情况：人在海外，为了看版权物，用阿里云，腾讯云的服务器做梯子翻墙回来。这几天各种实验一会儿v2ray之后，忽然无法ping通国内的阿里云，腾讯云服务器，也无法ssh。同时无法访问没有海外cdn节点的中国网站。部分资源在国内IP地址的网站会显示不全或者失败。
打电话到ISP去，说没有任何问题。
有没有类似情况的？

**Comment by yunfengwangluo** [comment]
被封了吧

**Comment by cppr** [comment]
连接是双向的，很有可能是你海外 IP 被封了

**Comment by KeHuang1** [comment]
> 情况：人在海外，为了看版权物，用阿里云，腾讯云的服务器做梯子翻墙回来。这几天各种实验一会儿v2ray之后，忽然无法ping通国内的阿里云，腾讯云服务器，也无法ssh。同时无法访问没有海外cdn节点的中国网站。部分资源在国内IP地址的网站会显示不全或者失败。
> 打电话到ISP去，说没有任何问题。
> 有没有类似情况的？

后来呢，是你的ip被封了吗

**Comment by wuzechen** [comment]
的确是被封了，3到4个月之后才解封的。之间的时间上任何国内的网都需要通过服务器中转才能上。

**Comment by KeHuang1** [comment]
太特么狠了，我还说618买阿里云翻回去看小米盒里的电视呢，想不到回国也要封，唉算了

**Comment by wuzechen** [comment]
没事，可以翻回去。我那次好像是意外，不知道触发了什么检测机制导致的。我现在用qcloud中继gcp就没事。

**Comment by yunfengwangluo** [comment]
一个开源的软件 你们还指这东西 逃过 国家防火墙&nbsp; 不要被 他们的加密方法迷信了&nbsp; &nbsp;我一个做小软件的 几天就可以搞到这软件的网络特征&nbsp; 合理合法 使用隧道工具&nbsp; 国家是不反对商业自用隧道的 只是针对那些没有备案和私自搭建的人 都说自己是合法的 我也认为有一部分是合法的 但大多数都是非法的&nbsp; 有兴趣可以自己写一个&nbsp; 类似工具做学习研究用




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月28日(星期一) 晚上8:00
收件人: ***@***.***&gt;; 
抄送: "you ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [v2ray/discussion] 有没有捣鼓v2ray导致无法直接访问中国地区ip和网站的？ (#734)





 
没事，可以翻回去。我那次好像是意外，不知道触发了什么检测机制导致的。我现在用qcloud中继gcp就没事。

**Comment by KeHuang1** [comment]
> 没事，可以翻回去。我那次好像是意外，不知道触发了什么检测机制导致的。我现在用qcloud中继gcp就没事。

用腾云中继谷云？你说这个我还没概念，我刚看这些资料，只说是在云上用ssr代理请求看视频的url，然后用云的国内ip获取视频地址后,国外跟视频地址直连。本来打算买了云以后来具体研究，一查发现居然要被封，说服务商自己也在扫描啥的

**Comment by wuzechen** [comment]
写反了，gcp中继qcloud，国内就算封ip也是封gcp的一个ip，换一个就是了。现在最恶心的iqiyi的地址每天都在变

**Comment by KeHuang1** [comment]
原来是这个意思，想看个国内电视剧可真不容易。你用gcp后, 它的ip地址被封过吗

**Comment by KeHuang1** [comment]
身边有人买Malus或者快帆啥的用，这种不晓得会不会被封ip

**Comment by KeHuang1** [comment]
> 一个开源的软件 你们还指这东西 逃过 国家防火墙&nbsp; 不要被 他们的加密方法迷信了&nbsp; &nbsp;我一个做小软件的 几天就可以搞到这软件的网络特征&nbsp; 合理合法 使用隧道工具&nbsp; 国家是不反对商业自用隧道的 只是针对那些没有备案和私自搭建的人 都说自己是合法的 我也认为有一部分是合法的 但大多数都是非法的&nbsp; 有兴趣可以自己写一个&nbsp; 类似工具做学习研究用
> […](#)
为了看个电视剧，付出好大
