### ISSUE TITLE
failed to load GeoIP: cn

### ISSUE THREAD

**Issue by ameue** [v2ray/discussion#74]
core4.5编译的framework在PacketTunnel中启动时候报如下错误：

2ray.com/ext/tools/conf/serial: failed to parse json config > v2ray.com/ext/tools/conf: invalid field rule > v2ray.com/ext/tools/conf: failed to load GeoIP: cn > v2ray.com/ext/tools/conf: failed to open file: geoip.dat > open /director/geoip.dat

<details><summary>config.json</summary><pre>
{
    "log": {
        "access": "log_access",
        "error": "log_error",
        "loglevel": "warning"
    },
    "routing" : {
        "rules" : [
            {
                "domain" : [
                    "domain:doubleclick.net"
                ],
                "outboundTag" : "block",
                "type" : "field"
            },
            {
                "ip" : [
                    "geoip:cn",
                    "geoip:private"
                ],
                "outboundTag" : "direct",
                "type" : "field"
            },
            {
                "port" : "123",
                "outboundTag" : "direct",
                "type" : "field"
            },
            {
                "domain" : [
                    "domain:pstatp.com",
                    "domain:snssdk.com",
                    "domain:toutiao.com",
                    "domain:ixigua.com",
                    "domain:apple.com",
                    "domain:crashlytics.com",
                    "domain:icloud.com",
                    "cctv",
                    "umeng",
                    "geosite:cn"
                ],
                "outboundTag" : "direct",
                "type" : "field"
            },
            {
                "ip" : [
                    "149.154.167.0\/24",
                    "149.154.175.0\/24",
                    "91.108.56.0\/24",
                    "125.209.222.0\/24"
                ],
                "outboundTag" : "proxy",
                "type" : "field"
            },
            {
                "domain" : [
                    "twitter",
                    "domain:twimg.com",
                    "domain:t.co",
                    "google",
                    "domain:ggpht.com",
                    "domain:gstatic.com",
                    "domain:youtube.com",
                    "domain:ytimg.com",
                    "pixiv",
                    "domain:pximg.net",
                    "tumblr",
                    "instagram",
                    "domain:line-scdn.net",
                    "domain:line.me",
                    "domain:naver.jp",
                    "domain:facebook.com",
                    "domain:fbcdn.net",
                    "pinterest",
                    "github",
                    "dropbox",
                    "netflix",
                    "domain:medium.com",
                    "domain:fivecdm.com"
                ],
                "outboundTag" : "proxy",
                "type" : "field"
            }
        ],
        "strategy" : "rules",
        "domainStrategy" : "IPIfNonMatch"
    },
    "policy" : {
        "levels" : {
            "0" : {
                "downlinkOnly" : 0,
                "handshake" : 4,
                "connIdle" : 120,
                "uplinkOnly" : 0
            }
        }
    },
    "inbounds" : [
        {
            "listen" : "127.0.0.1",
            "settings" : {
                "allowTransparent" : true
            },
            "port" : 10800,
            "streamSettings" : {
                
            },
            "protocol" : "http"
        }
    ],
    "dns" : {
        "clientIp" : "115.239.211.92",
        "servers" : [
            "223.5.5.5",
            {
                "port" : 53,
                "address" : "114.114.114.114",
                "domains" : [
                    "geosite:cn"
                ]
            }
        ]
    },
    "outbounds" : [
        {
            "settings" : {
                "servers" : [
                    {
                        "password" : "123",
                        "port" : 123,
                        "address" : "ip",
                        "method" : "aes-256-cfb"
                    }
                ]
            },
            "mux" : {
                "enabled" : false,
                "concurrency" : 8
            },
            "tag" : "proxy",
            "protocol" : "shadowsocks"
        },
        {
            "settings" : {
                "domainStrategy" : "UseIP"
            },
            "tag" : "direct",
            "streamSettings" : {
                
            },
            "protocol" : "freedom"
        },
        {
            "settings" : {
                
            },
            "protocol" : "blackhole",
            "tag" : "block"
        }
    ]
}

</pre></details>

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
