### ISSUE TITLE
WSL能否直接使用win10代理

### ISSUE THREAD

**Issue by chaozju** [v2ray/discussion#740]
除了在WSL中配置
```bash
export http_proxy=socks5://127.0.0.1:1080
export https_proxy=socks5://127.0.0.1:1080
```
之外是否还需要其他配置操作？
谢谢

**Comment by yomnxkcs** [comment]
WSL有两个版本，不同版本的网络处理方式不同。
可以用在cmd里面输入`wsl -l -v`查看你正在用的是哪个版本。

#### WSL ver1 比较简单：

```bash
export http_proxy=http://127.0.0.1:8080
export https_proxy=http://127.0.0.1:8080
```

#### WSL ver2 有自己独立的IP而且会不断变化。

简单一点的方式是把v2ray共享到局域网，也就是把inbound的IP设成0.0.0.0，
然后在WSL里面`export http_proxy=http://(你电脑的局域网IP):（端口）`，https同理。

如果不想在局域网里共享v2ray，可以在WSL里面配置好sshd之后，主机通过putty的plink.exe把v2ray的端口反代理给WSL使用。关键命令是:
`plink.exe -P 22 -i "id.ppk" -no-antispoof -ssh -N -R 8888:localhost:8080 ubuntu@localhost
`
这个需要点网络知识所以不详细说操作步骤了，但要注意WSL和主机共用端口，所以设置端口的时候不要重复。

此外命令行工具大部分用的是http协议，不确定你写的socks5://...是否可用。
