### ISSUE TITLE
关于更新v2ray的问题

### ISSUE THREAD

**Issue by smallprogram** [v2ray/discussion#742]
如果客户端保持4.23.1。而服务端一直保持最新版本。安全吗？

**Comment by yomnxkcs** [comment]
V2Ray的首要关注点是“突破封锁”不是“安全”。你不去踩红线，就算用“不安全”的ss-rc4-md5也没什么事（服务器会不会被封另说）。反之用TOR作死上新闻的也不少。总之安不安全取决于你自己。

然后是否更新的问题，建议有重大BUG修复之后尽快更新，其他情况看心情更新。这应该属于常识了吧。
