### ISSUE TITLE
關於項目維護者安全的擔憂

### ISSUE THREAD

**Issue by wenjinlibug** [v2ray/discussion#744]
目前v2ray的維護者可以看到是Xiaokang wang地點是北京，這是個很讓人擔心的情況。
    基於眾所周知的原因，居住在北京很難避免當局的威脅恐嚇，這不但是維護者本人的人身安全問題，v2ray項目後面更新的代碼安全度也很成問題。
    畢竟誰也無法保證維護者本人及其家屬是否已經遭到當局迫害。

**Comment by galvasis193** [comment]
保證安全性靠目前的幾個維護者是不夠的。
v2ray需要有活躍的社區支撐更多開發者參與到項目中來。

**Comment by galvasis193** [comment]
此外維護者除了寫程式代碼外，還要經常要管理項目，維護文檔，甚至還有答疑等雜七雜八的事情。
如果有一個社區能夠調將非專業開發者調動起來幫助目前幾位維護者分擔一部分工作其實是很好的。
目前我覺得用戶的參與度不高，大多數人處於一種用了就走的狀態，沒有參與到項目的發展過程中來。

**Comment by wenjinlibug** [comment]
@galvasis193 同意，可是就我自己來説只是用好就已經非常困難了，畢竟沒學過編程單理解配置文件就是一件艱巨的工作。
然而，我想説的是另一個問題，希望開發者們能夠特別注意人身安全，很明顯這個項目早已被盯上，現在發佈者們的信息甚至能直接看到照片和地理位置，我只希望這些信息都是虛構的而非真實的，否則一旦發佈者們被抓可不單單是項目廢棄這麽簡單，按照共產黨的特性甚至有可能故意發佈能夠追蹤使用者的帶毒版本。

**Comment by onichandame** [comment]
作为一个普通用户，我认为参与度不高的一个原因是项目与大社区的融合度不高。我个人在工作中不使用Golang，因此对codebase不是很熟悉。如果有类似[libp2p项目](https://github.com/libp2p/)这样的设计，在保证核心protocol定义稳定的前提下为不同的社区提供不同的库和工具作为参与开发维护的入口，我个人认为用户的参与度会有提高。
