### ISSUE TITLE
如何用caddy v2 反代 h2啊

### ISSUE THREAD

**Issue by littlesum** [v2ray/discussion#749]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。
用 caddy v1 按照大家讨论的已经成功设置，手贱升级了caddy v2 怎么搞都配置不成功。有没有成功的配置文件，麻烦发一个参考下
此 Issue 会被立即关闭。

If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

This issue will be closed immediately.

**Comment by wenjinlibug** [comment]
@littlesum 

```
	transport http {
			tls_insecure_skip_verify
        }
```
改成这样了，不过仍然无法成功代理h2。
