### ISSUE TITLE
[Tutorial] Windows 下手动编译、交叉编译 v2ray 的详细方法

### ISSUE THREAD

**Issue by rprx** [v2ray/discussion#756]
代码果然还是要自己写，这两天抽空实现 VLess（#2526 v2ray/v2ray-core#2547），目前协议核心部分已经完成。看到有 [issue](https://github.com/v2ray/v2ray-core/issues/2536) 说 v2ray 的某些问题和 Golang 版本有关，现在把 Win 编译的详细方法写出来，很简洁且更完美。

**1.下载 Golang 的 Windows 版本并安装，至少 1.15.x**

官网：https://golang.org/dl
或者：https://studygolang.com/dl

安装后，打开 PowerShell 并执行：

`go env -w GO111MODULE=on GOPROXY=https://goproxy.cn,https://goproxy.io,direct`

**2.下载 v2fly 的 v2ray-core 代码并解压**

https://github.com/v2fly/v2ray-core/archive/master.zip

解压后，在文件夹内按住 Shift 同时单击右键，打开 PoweShell 并依次执行：

```
$env:CGO_ENABLED=0

go build -o v2ray.exe -trimpath -ldflags "-s -w -buildid=" ./main
go build -o wv2ray.exe -trimpath -ldflags "-s -w -H windowsgui -buildid=" ./main
go build -o v2ctl.exe -trimpath -ldflags "-s -w -buildid=" -tags confonly ./infra/control/main
```

将编译到当前目录。geoip.dat 和 geosite.dat 在 ./release/config/ 文件夹下。

第一次编译会自动下载依赖代码，也没有之前的编译缓存，所以编译速度会相对慢一些。

**3.交叉编译，这里以编译到 Linux 服务器为例**

```
$env:CGO_ENABLED=0
$env:GOOS="linux"
$env:GOARCH="amd64"

go build -o v2ray -trimpath -ldflags "-s -w" ./main
go build -o v2ctl -trimpath -ldflags "-s -w" -tags confonly ./infra/control/main
```

上传到服务器后，记得在服务器终端内执行 `chmod +x v2ray` 和 `chmod +x v2ctl`

提示：PowerShell 执行 `go tool dist list` 查看所有支持的系统与架构。

---

这里的很方便、清晰，按上面的流程一步步做即可成功编译，感兴趣的不妨试一下。

go build 加上 `-trimpath` 用于保护隐私，同时略微减小文件体积。

**Comment by wenjinlibug** [comment]
我編譯出來的任何一個都是只有233k，是什麽原因？沒有任何報錯。

**Comment by johnwigley** [comment]
@rprx  I couldn't see an issue tracker for VLESS specifically: if there is one apologies for posting here.

In v2ray-vless preview version. When using VLESS if a connection occurs to a protocol where the SERVER sends FIRST, NOT the client, such as SMTP where the client waits for the server banner message before logging in. Then current VLESS does NOT send server first message until after the client has sent data.

This means SMTP through VLESS is broken currently.

On same configuration, switching from vless -> vmess then SMTP works perfectly, so definitely an issue with vless implementation.

**Comment by RPRX** [comment]
@johnwigley 

感谢反馈，可以分别测试一下 VLESS BETA 版本和 ALPHA 版本吗

**Comment by johnwigley** [comment]
> @johnwigley
> 
> Thanks for the feedback, can you test the VLESS BETA version and ALPHA version separately

@rprx 

Tested:

Preview: NOT working
Beta: Working
Alpha: Working

So the issue is new in the preview.

To test: setup dokodemo-door port forward to SMTP server, then telnet through dokodemo-door and see if you see the SMTP server banner before you press any key to send data. You should see SMTP server banner without client sending any data,.

**Comment by RPRX** [comment]
@johnwigley 

十分感谢，我已经确定了问题所在

PREVIEW 版本中，我把原先的“客户端 100 毫秒内没发数据则只发 VLESS 头”改成了“客户端必须发数据才发送”，所以导致了问题

我将很快发布 PREVIEW 1.1 版本，再次感谢！

**Comment by johnwigley** [comment]
@rprx Thank you for fixing it so quickly :+1:

**Comment by Ygrittevictorlee** [comment]
PS D:\ChromeDownload\software\v2ray-core-master\v2ray-core-master> $env:CGO_ENABLED=0
PS D:\ChromeDownload\software\v2ray-core-master\v2ray-core-master> go build -o v2ray.exe -trimpath -ldflags "-s -w -buildid=" ./main
go: github.com/dgryski/go-metro@v0.0.0-20200812162917-85c65e2d0165: Get "https://proxy.golang.org/github.com/dgryski/go-metro/@v/v0.0.0-20200812162917-85c65e2d0165.mod": dial tcp 172.217.160.81:443: i/o timeout
PS D:\ChromeDownload\software\v2ray-core-master\v2ray-core-master> go build -o wv2ray.exe -trimpath -ldflags "-s -w -H windowsgui -buildid=" ./main
go: github.com/dgryski/go-metro@v0.0.0-20200812162917-85c65e2d0165: Get "https://proxy.golang.org/github.com/dgryski/go-metro/@v/v0.0.0-20200812162917-85c65e2d0165.mod": dial tcp 172.217.160.81:443: i/o timeout
PS D:\ChromeDownload\software\v2ray-core-master\v2ray-core-master>


这怎么一直是timeout呢？
