### ISSUE TITLE
新手求助：浏览器访问谷歌：Did Not Connect: Potential Security Issue

### ISSUE THREAD

**Issue by pedro-abundio-wang** [v2ray/discussion#757]
新手搭建了v2ray，使用火狐浏览器访问谷歌时，出现如下现象，求大神赐教，万分感恩！！！！！

![v2ray](https://user-images.githubusercontent.com/50159788/85487086-79eb3600-b5fe-11ea-84fc-d60a54d77b5f.png)

如何避免这个问题？

我是参考官网文档进行配置的，参考地址如下：https://www.v2ray.com/en/welcome/start.html

是否有其他协议模式，可以使用，以免出现此问题？

期待外网访问的自由！！！！！！
求大神赐教，万分感恩！！！！！
求大神赐教，万分感恩！！！！！
求大神赐教，万分感恩！！！！！

服务端配置：

{
  "inbounds": [{
    "port": 10086, // Port of the server. Must be the same as above.
    "protocol": "vmess",
    "settings": {
      "clients": [{ "id": "b831381d-6324-4d53-ad4f-8cda48b30811" }]
    }
  }],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  }]
}

客户端配置：

{
  "inbounds": [{
    "port": 1080,  // Port of socks5 proxy. Point your browser to use this port.
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "udp": true
    }
  }],
  "outbounds": [{
    "protocol": "vmess",
    "settings": {
      "vnext": [{
        "address": "server", // Address of your V2Ray server. May be IP or domain address.
        "port": 10086,  // Port of your V2Ray server.
        "users": [{ "id": "b831381d-6324-4d53-ad4f-8cda48b30811" }]
      }]
    }
  },{
    "protocol": "freedom",
    "tag": "direct",
    "settings": {}
  }],
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [{
      "type": "field",
      "ip": ["geoip:private"],
      "outboundTag": "direct"
    }]
  }
}

**Comment by cppr** [comment]
DNS 被污染了

**Comment by pedro-abundio-wang** [comment]
> DNS 被污染了

请教一下，如何解决呢？不胜感激！！！

**Comment by cppr** [comment]
> > DNS 被污染了
> 
> 请教一下，如何解决呢？不胜感激！！！

尝试 [https://guide.v2fly.org/basics/dns.html](https://guide.v2fly.org/basics/dns.html)，
若未解决，尝试将 本地DNS 设为 DoH/DoT 或使用 V2Ray 的 [DNS对外开放设置](https://guide.v2fly.org/basics/dns.html#%E5%AF%B9%E5%A4%96%E5%BC%80%E6%94%BE-v2ray-%E7%9A%84-dns-%E6%9C%8D%E5%8A%A1)
