### ISSUE TITLE
【求教】用的印度阿里云搭建的v2ray服务器，怎么设置配置？

### ISSUE THREAD

**Issue by quesqion** [v2ray/discussion#760]
我用的朋友给的配置，可以正常跑起来，但是用google analytics 无法检测到印度的IP地址。研发要用到印度的IP环境，请问下应该怎么配置？

**Comment by kslr** [comment]
analytics 默认DNS会解析到中国

**Comment by dadadaovo** [comment]
> analytics 默认DNS会解析到中国

。。为什么呀？我让印度同事刷 就是显示在印度的。现在这个配置 直接不显示访问了。像隐身一样的。
