### ISSUE TITLE
请问V2Ray 是将域名转发给代理，还是将解析后的 IP 转发给代理。

### ISSUE THREAD

**Issue by little-shiba** [v2ray/discussion#761]
如题

**Comment by yunfengwangluo** [comment]
把 连接信息吧 你把什么连接通过 v2rya  他就 转发什么

**Comment by BioniCosmos** [comment]
视情况而定。

比如在 Socks 代理中，如果使用代理 DNS 查询，那么就会将域名发给服务器；如果本机查询后再代理，那么就把 IP 发给服务器。

当然，V2Ray 内部的不同路由和 DNS 配置也会引起以上效果。

还有一种情况就是开启了流量探测，那么无论其他配置如何，V2Ray 都会将域名发给服务器。

这个问题的应用是使用纯 IPv6 做服务器时的局限。
