### ISSUE TITLE
V2ray iOS client implementation

### ISSUE THREAD

**Issue by bd901029** [v2ray/discussion#763]
Hi Everyone,

I'm building an iOS V2ray client with server completed. I tried to learn but I couldn't find any solution. Anyone is able to share instruction, link, guide, tutorial, or source code?

Thanks.

**Comment by 616115891** [comment]
Hi,I also need it!work together！

**Comment by bd901029** [comment]
Hi everyone, Any progress? :(

**Comment by alechangbiao** [comment]
Hi guys, any progress ? Looking for guys to work together
