### ISSUE TITLE
What if I transfer v2ray with iptables via another overseas server?

### ISSUE THREAD

**Issue by Dukewill** [v2ray/discussion#764]
Would this overseas/transfer server be easily identified by GFW or it’s just the same as I was accessing the transferred server(with websocket & tls activated)?

Thanks a ton!

**Comment by rikkihamano** [comment]
If you mean redirect traffics from an overseas server, this is not a good idea.
Almost every traffic from overseas servers would pass the "wall".

**Comment by Dukewill** [comment]
> If you mean redirect traffics from an overseas server, this is not a good idea.
> Almost every traffic from overseas servers would pass the "wall".

Thanks a ton. I understand all the traffics would go through the wall.
I mean redirect traffics from an overseas server (A) with another overseas server (B), how safe would server B be?
