### ISSUE TITLE
What will happen when mux -> concurrency = 1024

### ISSUE THREAD

**Issue by vbuterin2** [v2ray/discussion#767]

**Comment by vbuterin2** [comment]
I saw a dramatic latency decrease and network latency improvement in general, but what are the side effect of this?

**Comment by Zeyu-ZEYU** [comment]
seems it will put negative effects on video playback. Latency is reduced but throughput might be influenced due to tcp congestion control.

**Comment by darhwa** [comment]
打开多路复用，对大多数日常应用来说只有好处，尤其是高延迟线路。看视频应用并不是一定受影响，受影响前提是视频带宽接近单个TCP连接带宽上限。这个上限还可以通过内核参数调优来改善，比如增大客户端的接收窗口。
