### ISSUE TITLE
[Feature Request] 更详细的方案：非可信通路 与 可信通路（VMore and VLess），含 VLess 具体设计方案

### ISSUE THREAD

**Issue by rprx** [v2ray/discussion#768]
2020-07-17 更新：

[[New Protocol] VLESS BETA：性能至上、可扩展性空前，目标是全场景终极协议。](https://github.com/v2ray/v2ray-core/issues/2636)

2020-06-20 更新：

[[New Protocol] VLESS ALPHA](https://github.com/v2ray/v2ray-core/issues/2583)

---

经过在 v2ray/v2ray-core#2526 中的讨论，我告诉 @ActiveIce 应该重新开一个 issue，于是他在 v2ray/v2ray-core#2541 中描述了一个方案，但我觉得将 VMess 的实现解耦掉各种 HASH、加密部分并不容易，会增大难度、延长 VMess 2 的设计时间，尤其是可能会带来新的未知问题。**所以，基于种种考虑，我更倾向于下一步分为专攻两个方向的两个协议**。由于这和一个协议解决所有问题有根本区别，所以我开了这个 issue。

首先，我并不希望这是一轮大规模重构，那样太麻烦且设计周期很长。我倾向于**这两个新协议就只是两个新协议而已**，要能复用 v2ray 的现有架构、其它组件，也就是说基础架构无需做任何变动。

请允许我引入一些自己想出来的概念：

经过思考，我觉得我们对 v2ray 的使用可以分为两种情况，即 **非可信通路** 与 **可信通路**，而没有半可信通路。比如，一般来说内网可以算作可信通路，而公网则算作非可信通路，但这两种情况并不是绝对的，**通路可以互相转化**。我举个例子，公网虽然是非可信通路，但基于 TLS 后可以变为可信通路，而如果途经 CDN，则又变回非可信通路。内网若不受自己控制，则不应算作可信通路，而应算作非可信通路。

---

**那么，非可信通路 与 可信通路，各对应一种协议：VMore and VLess（就这么命名吧）**

具体而言，**专用于非可信通路的 VMore 是含 AEAD 加密和其它改进的 强化版 VMess，注重安全。**

**而专用于可信通路的 VLess 是无需任何 HASH、加密等多余计算的 阉割版 VMess，注重性能。**

同时，这两个协议都应该支持**可无限扩展的混淆方案（改变流量时序特征）**，等下我会详细描述。

对于 VMore 的具体设计，我个人并没有太多想法，只是认为这应该是一个相对整体的安全方案，而且觉得这可能是一个长期工程。建议多参考一些其它地方已有的最佳实践（而不是闭门造车），以及参考 https://github.com/v2ray/discussion/issues/711

对于 VLess 的具体想法，其实我已经在 v2ray/v2ray-core#2526 中描述过了，只是现在不是非要基于 TLS，如内网用途，这也是我想出可信通路、通路转化那些概念的原因 —— **现在的定位更明确：专用于可信通路，性能 MAX。**

**由于去掉了各种 HASH、加密等多余计算部分、支持关闭混淆，VLess 的性能将会比现在的 VMess 更强（即使后者加密选 none）。但 VLess 并非完全不 Mess，相反地，它的混淆方案更强大：支持无限扩展、随机选择、每次请求随机选择。**

---

**下面我将详细说一下 VLess 的具体设计，我想我们现在就需要它（鉴于 VMore 一时半会儿出不来）。由于主要是阉割，实现起来不难，熟悉 VMess 代码的大佬应该很快就可以完成。**

参考：https://www.v2fly.org/developer/protocols/vmess.html

但由于这个文档有些地方有歧义（如现混淆方案 Shake 的参数），我还看了 VMess 的部分代码。

因为是用于可信通路，所以是明文、去掉所有加密，也没有系统时间相差要求等。
保持无状态，保留鉴权、兼容现有的路由、统计、底层传输方式等，不另起炉灶。
为 TLS 穿墙准备了可无限扩展的混淆方案，但其它用途无需开启，也不占地方。

### 客户端：

1. 认证信息无需 HMAC，只留 UUID，不要 MD5、UTC 时间。

2. 指令部分去掉 AES-128-CFB 加密，只留响应认证、指令、端口、地址类型、地址，其它全部不要。

3. 配置文件中新增“混淆方案”选项（把现方案改成可扩展形式），默认 none 不开启，填 auto 是随机选择一种混淆方案，rand 是每次请求随机选择，shake 则是现方案（参数改为后面提到的随机值）。指令部分结尾添加一个1字节的“混淆方案名称长度”，如5，接着是混淆方案具体名称 shake。有混淆方案时，继续添加一个1字节的“附加数据长度”，如16，接着是一个16字节的随机值。

4. 数据部分为“标准格式”，且没有加密。是否混淆、混淆方案取决于配置文件。
不混淆时，数据部分不采用“标准格式”，即不分割为若干小块，同时也不需要小块校验。

### 服务端：

1. 配置文件中新增“是否必须混淆”选项，默认 false 不强制，填 true 则客户端必须选择一种混淆方案，否则断开连接。请求到达时，若服务端没有请求中的混淆方案或无法成功解除混淆，则断开连接。

2. 应答头部数据去掉 AES-128-CFB 加密，只留响应认证，不要选项、指令部分。

3. 应答头部数据结尾添加一个1字节的“混淆方案名称长度”...（结构与前文相同）

4. 实际应答数据同样为“标准格式”，且没有加密。是否混淆、混淆方案和客户端的请求一致。
不混淆时，数据部分不采用“标准格式”，即不分割为若干小块，同时也不需要小块校验。

**可能：所有混淆相关结构均移至最前，当选择了混淆方案时，后面所有数据均参与混淆（包括头部）**

---

### 这样一来和 trojan 相比有什么主要区别？

0. 理论上来说，不开混淆时，VLess + TLS 速度可以追平 trojan（那么 trojan 就很尴尬了）
[WS](https://zh.wikipedia.org/wiki/WebSocket) 的 [Base64](https://zh.wikipedia.org/wiki/Base64) 编码会使数据量膨胀 33% 左右，所以要么压缩，要么推荐其它长连接方式
1. VLess 不强制 TLS，且可以复用 v2ray 已有的其它组件（路由、DNS、统计、API等），适用范围更广。
2. **有强大的可无限扩展的混淆方案，还支持随机选择、每次请求随机选择。**
3. 可以插一层 WebSocket/H2/QUIC 等 v2ray 已有、将有的底层传输方式。
4. **服务端可以由 nginx 处理 tls 并路径分流。**（trojan 只能由 nginx 的 stream 段预读取 sni 来转发）
5. 当 v2ray 出现了新的 TLS 指纹解决方案时，可以直接拿来用。https://github.com/v2ray/discussion/issues/706
6. **如果你觉得 CDN 是可信通路，那么可以套 CDN。**
7. （并不是很重要）trojan 只支持 socks5，而 v2ray 支持多种入站方式。

欢迎提出改进意见，也希望项目组给予反馈。

**Comment by wenjinlibug** [comment]
不知各位大佬是否願意聽一下外行人的意見，我不懂什麽加密套件加密原理，也不懂怎麽混淆才能騙過墻，僅僅作爲一個使用者來説，多一個協議選擇就代表墻要多分一份資源來防堵，如果只需要投入極少的人力簡單的合并到v2ray裏何樂而不爲？誰規定VLess合并后就一定要分出大量人力來維護了？至於Vmess的混淆加密等確實不是性能瓶頸，畢竟手機、電腦、服務器、綫路帶寬都會更新換代硬件性能提升遲早會完全蓋過那點性能損失，可問題的根本不在那裏，真正的問題在於“最沒特徵的人是間諜”，沒特徵本身就是最大特徵，現在的Vmess看起來就像毫無意義的强調無特徵和強加密。

**Comment by okudayukiko** [comment]
在一些低端VPS上，用AES-256-GCM性能比AES-128-GCM、CHACHA20-POLY1305好。

**Comment by EpocheRan** [comment]
我觉得应该从普通使用者的角度来考虑这个问题，如果是用来爬墙的话加解密速率不是大问题，服务与线路的稳定才是核心。目前看评论，开发VLess在我看来很大程度上有与Trojan比较的想法。讨论的计算资源占用问题，个人认为新的加密算法或者协议集成下就可以。vmess协议或者ss协议或者其它，来个开关，想用就用，不用你就明文再套个其它加密也行。这样组合更多，有的选，大家选自己最喜欢的就好，不用吵架。

V2ray在我心中应该更像一把瑞士军刀，提供更多选择与组合的同时，不断添加新的工具可以用，而不是简单为了翻墙去设计。我也经常用v2ray做国内的代理和转发，感觉配置简单很好用。个人期望v2ray在网络可靠性上有更好的设计，无论是改良目前UDP缺点，还是提供一个较好的负载均衡功能。都可以用比较小的成本，换取更稳定的网络体验。

**Comment by wenjinlibug** [comment]
@Sanfrencon 可是根據我瞭解到的粗糙技術來説影響網絡帶寬的因素似乎分爲：每個數據包的數據量、發送包的速度、數據包丟失、延誤、錯序、擁堵等問題造成的損失（也就是綫路情況）。
        我曾經提議過用向前糾錯算法來解決綫路問題，可是大神們似乎覺得TCP自帶糾錯機制、我這是在添亂。所以現在大神們討論的問題似乎就集中在數據包的數據量上面，因爲包發太快會被當作網絡攻擊，所以數據包能夠携帶多少有效數據就決定帶寬的大小。那麽TCP數據包的大小是多少呢，我在維基查到是1522個字節，其中22個字節被用來作爲“頭部”放置目的地之類的信息，當然頭部越大後面的有用數據就越少，本來上網用的pppoe就吃掉一點了，tcp、http之類又吃一塊，ipv6、ipv4隧道轉換又吃一些，有些路由還限制數據包大小將它們切開幾塊然後每塊都加上新的“頭”，有用數據部分自然越來越少。
        現在的問題似乎就出在到底應該把這個頭部再在原來基礎上擴充多少來做驗證、加密、混淆。rprx 大神認爲TLS本身就占了一部分做加密，vmess又自己用掉一部分做加密還不給取消純屬浪費資源，而且vmess 還弄個很不專業的混淆又吃掉一部分，所以他就把協議大刀闊斧砍個乾净，然後原vmess的維護者們自然非常不樂意，畢竟花了那麽多精力好不容易做出個毫無破綻沒有特徵的強加密協議、你說砍就砍什麽意思。這就像大家好不容易組裝起一輛坦克、你突然説別用坦克了，我們只不過要通過安檢而已，輕裝便行僞造個證件騎個機車就能混過去。
以上就是我對現狀的理解，不知道是否正確，我個人是支持rprx大的，如果是普通安檢你開個坦克硬闖也就罷了，可前面要是坦克飛機航空母艦、你開個坦克硬闖豈不找死？

**Comment by RPRX** [comment]
感觉楼上几位朋友误解了。。。现在并没有什么冲突。。。

**Comment by okudayukiko** [comment]
或者支持VMess+SSH。SSH支持的算法（Host key、Keyex、Encrypt、MAC）更多，在客戶端紀錄Base64 Public key或Public key fingerprint防止攻擊。
OpenVPN（TLS tunnel mode除外）、Tinc可以調用OpenSSL Library支持的算法，不受TLS Ciphersuite限制。

**Comment by RPRX** [comment]
@okudayukiko

SSH 自带 Socks5 代理（几年前流行的翻墙方式）

**Comment by okudayukiko** [comment]
> @okudayukiko
> 
> SSH 自带 Socks5 代理（几年前流行的翻墙方式）

我說的就是SSH自帶的SOCKS5

**Comment by RPRX** [comment]
@okudayukiko 

刚刚 GitHub 崩了很长时间，没仔细看，回复也是过了好久才终于发出去

SSH 的 Socks5 是否有明显区别于 SSH 的特征还有待研究（我还没研究过

**Comment by okudayukiko** [comment]
> @okudayukiko
> 
> 刚刚 GitHub 崩了很长时间，没仔细看，回复也是过了好久才终于发出去
> 
> SSH 的 Socks5 是否有明显区别于 SSH 的特征还有待研究（我还没研究过

偽裝SSH協定進行加密，偽裝具有登入的SSH，登入密碼就是由AlterID來變化。

**Comment by okudayukiko** [comment]
在手機、Notebook PC使用科學上網真的很耗電。

**Comment by okudayukiko** [comment]
這幾天在VPS上添加了2GB的swap file，再把原來.XYZ的域名換為.COM，解決了用Trojan看視頻時VPS端CPU使用率高的問題。
Trojan伺服器端或用戶端只協商一個TLS Cipher，看視頻緩慢的問題解決。
`{`
`"run_type": "server",`（或`"run_type": "client",`）
`"ssl": {`
`"cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256",`
`"cipher_tls13": "TLS_AES_128_GCM_SHA256"`
`}`
`}`
SSH用戶端使用以下命令（手動指定一個Cipher）也可以用SSH SOCKS5代理：`ssh -D 1080 -o Ciphers=aes128-gcm@openssh.com user@host`、`ssh -D 1080 -o Ciphers=chacha20-poly1305@openssh.com user@host`、`ssh -D 1080 -o Ciphers=aes128-ctr -o MACs=hmac-sha2-256-etm@openssh.com user@host`。直接用`ssh -D 1080 user@host`會被中國防火牆阻斷（預設情況下SSH客戶端會協商多個Ciphers），應該是被降級攻擊（對`umac-xxx-etm@openssh.com`和`umac-xxx@openssh.com`進行阻斷）。
Ocserv則使用以下配置，只協商一個TLS Cipher。
`/etc/ocserv/ocserv.conf`
`tls-priorities = "NONE:+VERS-ALL:+ECDHE-RSA:+ECDHE-ECDSA:+SIGN-ALL:+AES-128-GCM:+AEAD:+GROUP-SECP256R1:+CURVE-SECP256R1"`

**Comment by okudayukiko** [comment]
部分VPS會限制UDP下載速度？在電腦上用`ssh -D 1080 user@host`看視頻比Trojan快。在手機上用Firefox看視頻比YouTube App、Niconico App快。某廉價日本VPS。
