### ISSUE TITLE
源码中 在上面位置载入的配置文件呢

### ISSUE THREAD

**Issue by yunfengwangluo** [v2ray/discussion#769]
如题 找了 两三天了  虽然有几个地方看着像 但有不确定 是不是 希望大神 能说一下 具体是 源码的什么位置 例如 哪个目录中的哪个文件  中的哪个函数  如果比较多 说个大概也可以

**Comment by kslr** [comment]
https://github.com/v2ray/v2ray-core/blob/2f12e0caf3e50e4e70f64d470e2652da1e8aa0ba/main/main.go#L116
