### ISSUE TITLE
关于V2ray的前置代理

### ISSUE THREAD

**Issue by UnusualC** [v2ray/discussion#772]
本人刚接触V2ray，已在无代理环境下实现代理成功，但在公司需要代理才可以上网，在查询相关资料后得知V2ray需要自行修改json文件才能得以实现。  
"inbounds": [
    {
      "tag": "proxy",
      "port": 8081,
      "listen": "公司代理地址,
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
照葫芦画瓢，但依然无法实现，在小飞机中可以轻易实现，请问如何在V2ray上实现呢，下面是小飞机的设置
代理使用√ 
代理类型 http 超时3s
代理地址 公司代理地址 代理端口8081

**Comment by ee-** [comment]
Forward proxy should be configured in the `outbound` section, **not** `inbound`.
