### ISSUE TITLE
如何通过V2Ray实现Full Cone NAT？

### ISSUE THREAD

**Issue by bekars** [v2ray/discussion#774]
希望实现udp的Full Cone NAT，按官方vmess配置的只能是Symmetric NAT，返回的udp报文如果源端口改变（即返回报文的目的地址和端口以及源地址不变）没有返回到客户端。

目前V2Ray能支持udp的Full Cone NAT吗？如果能支持请给出一个参考配置，特别是服务器端的配置，谢谢。

**Comment by xianren78** [comment]
目前看不能。

**Comment by bekars** [comment]
如果不能做到的话，加速某些游戏联机做不了房主。

**Comment by RPRX** [comment]
> 
> 
> 如果不能做到的话，加速某些游戏联机做不了房主。

让我猜一下，GTA 5 吗（房主可以开挂

**Comment by xqzr** [comment]
关闭服务器的防火墙

**Comment by bekars** [comment]
防火墙全关闭了，已经抓到返回的udp数据包了，从抓包看要做到NAT A有两个地方需要修改：

1. 返回到公网IP的udp报文用的是复用发出报文的目的和端口回到客户端（游戏机）的，应该保留udp报文的源地址和端口；
2. 主机发出的udp报文端口号是同一个，但是v2ray的客户端只要五元组不一样就会新开一个源端口，导致最终公网端口不固定，和symmetric nat行为是一样的，所以总是D；

**Comment by Vigilans** [comment]
目前Dokodemo-door是否是Cone NAT？做透明代理想和socks对比一下

**Comment by haodayizhia** [comment]
> 防火墙全关闭了，已经抓到返回的udp数据包了，从抓包看要做到NAT A有两个地方需要修改：
> 
> 1. 返回到公网IP的udp报文用的是复用发出报文的目的和端口回到客户端（游戏机）的，应该保留udp报文的源地址和端口；
> 2. 主机发出的udp报文端口号是同一个，但是v2ray的客户端只要五元组不一样就会新开一个源端口，导致最终公网端口不固定，和symmetric nat行为是一样的，所以总是D；

第一点没看明白，你是说服务器把收到的报文返回到客户端时，udp报文的源地址改成了服务器的ip和端口？

**Comment by Dr-Bluemond** [comment]
https://blog.akinokae.de/p/nat-behaviors-for-unicast-udp-in-v2ray/
