### ISSUE TITLE
如何在cloud function或cloud app平台上部署

### ISSUE THREAD

**Issue by onichandame** [v2ray/discussion#775]
以Google Compute Platform(GCP)为例，传统的部署v2ray的方法是租用Google Compute Engine(VPS)。
近期我在学习使用Google App Engine和Google Cloud Function，因此很好奇v2ray是否能以cloud app或cloud function的方式部署。

**Comment by phlinhng** [comment]
建议往部署在 Kubernetes Engine 的方向研究，可以参考 ibmyes 项目

**Comment by kslr** [comment]
我也支持 Kubernetes 方向的优化

**Comment by onichandame** [comment]
GKE上我成功部署过，后来发现价格比vps还高就放弃了。

从使用体验上我感觉v2ray的用配置文件的配置方式太难维护了，对弹性部署环境的支持非常差。希望能针对kubernetes或其他云部署方式进行优化

**Comment by zjplab** [comment]
cloud function: serverless云服务  http调用一次唤醒一次 不适合做vpn
google app engine: 用来部署monolithic server-side rendered websites的 理论可以

**Comment by zjplab** [comment]
我找到一个利用IBM Cloud Foundry部署vless的github项目: https://github.com/P3TERX/IBM-CF-V2, 对应的blog:https://p3terx.com/archives/how-to-use-ibm-cloud-gracefully-for-free.html

可以参考一下，IBM Cloud Foundry基本就是google app engine
