### ISSUE TITLE
v2ray现在能不能用上tls1.3

### ISSUE THREAD

**Issue by lgcde** [v2ray/discussion#78]
https://github.com/golang/go/issues/9671#issuecomment-437431164
https://github.com/mholt/caddy/issues/2080#issuecomment-439564485
https://www.hnrk.io/md/2._caddy+TLS1.3.md

试了试caddy.forwardproxy+http2+tls1.3挺快的

**Comment by Rucc1** [comment]
你可以试用 https://github.com/cloudflare/tls-tris
并且需要修改 core 在 https://github.com/v2ray/v2ray-core/blob/096bbd2c51eed2da232636dc5ef65aa30a7fe405/transport/internet/tls/config.go#L157-L172 传递给 crypto/tls 库的 tls 密钥交换方法和加密套件。

**Comment by lgcde** [comment]
> 你可以试用https://github.com/cloudflare/tls-tris
> 并且需要修改核心在[https://github.com/v2ray/v2ray-core/blob/096bbd2c51eed2da232636dc5ef65aa30a7fe405/transport/internet/tls/config.go#L157 -L172](https://github.com/v2ray/v2ray-core/blob/096bbd2c51eed2da232636dc5ef65aa30a7fe405/transport/internet/tls/config.go#L157-L172)传递给crypto / tls库的tls密钥交换方法和加密套件。

我只保留了tls1.3新的加密套件但是起初连接的时候抓包是tls1.2,过几分钟之后自动切换为tls1.3,这是为什么.有有没有办法指定tls1.3

**Comment by lgcde** [comment]
> 你可以试用https://github.com/cloudflare/tls-tris
> 并且需要修改核心在[https://github.com/v2ray/v2ray-core/blob/096bbd2c51eed2da232636dc5ef65aa30a7fe405/transport/internet/tls/config.go#L157 -L172](https://github.com/v2ray/v2ray-core/blob/096bbd2c51eed2da232636dc5ef65aa30a7fe405/transport/internet/tls/config.go#L157-L172)传递给crypto / tls库的tls密钥交换方法和加密套件。

![](https://i.loli.net/2018/11/28/5bfd78adb0df9.png)

**Comment by tufu9441** [comment]
@lgcde 我好像也发现起初连接的时候抓包是tls1.2,过一会之后又显示为tls1.3，请问您现在还有这个问题吗？现在4.18之后v2ray已经支持tls1.3了。

**Comment by atrandys** [comment]
https://www.atrandys.com/2019/1880.html
