### ISSUE TITLE
v2ctl 自签证书生成的 key 似乎有问题

### ISSUE THREAD

**Issue by zbttl** [v2ray/discussion#780]
1) 你正在使用哪个版本的 V2Ray？v4.26.0

2) 你的使用场景是什么？自签证书给 nginx 使用

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
使用命令签发一个自签证书
```
./v2ctl cert --ca --domain="127.0.0.1" --expire=87600h --file=ca
```
放入 nginx.conf 中运行报错。
使用命令
```
openssl rsa -noout -text -in ca_key.pem  
openssl x509 -noout -text -in ca_cert.pem 
```
检查后发现 key 文件报错。
![image](https://user-images.githubusercontent.com/22035093/86561948-5d52e480-bf94-11ea-99ce-6047f931ac89.png)

值得一提的是，使用旧版 v4.22.0 生成的证书并不会报错。

**Comment by zbttl** [comment]
仍旧报错
![image](https://user-images.githubusercontent.com/22035093/87921861-bac75500-caad-11ea-84d9-ab0b13d0446e.png)
另外 nginx 在开启或检查时就会报错
![image](https://user-images.githubusercontent.com/22035093/87922087-0ed23980-caae-11ea-988b-caa126ce6a0f.png)

**Comment by rikkihamano** [comment]
> 仍旧报错
> ![image](https://user-images.githubusercontent.com/22035093/87921861-bac75500-caad-11ea-84d9-ab0b13d0446e.png)
> 另外 nginx 在开启或检查时就会报错
> ![image](https://user-images.githubusercontent.com/22035093/87922087-0ed23980-caae-11ea-988b-caa126ce6a0f.png)

无法复现，抱歉
![image](https://user-images.githubusercontent.com/28243989/87923945-cbc59580-cab0-11ea-8f5a-fe1fdbc5806a.png)
![image](https://user-images.githubusercontent.com/28243989/87923845-a769b900-cab0-11ea-8dc3-b45220c3d50e.png)

**Comment by rikkihamano** [comment]
如果可以，请重新生成一套并粘贴至此

**Comment by zbttl** [comment]
我大概知道问题出在哪了。。。
为了支持 tls1.3 我自编译了最新版 openssl，对 ecc 支持有问题。

**Comment by zbttl** [comment]
补充一点详细原因吧，避免后人踩坑
我系统自带的 openssl 版本太旧无法开启 tls1.3，所以想自编译一个
但我直接 git clone 官方 openssl 项目下来编译，出来的 1.1.1h 版本没法正确支持 ecc
正确的方法应该在官网下载官方版 openssl（目前稳定版是 1.1.1g）然后编译安装，nginx 就正常工作了。

**Comment by okudayukiko** [comment]
用CentOS 8都能支援TLS 1.3。`v2ctl cert`不支援憑證類型（RSA/EC），不支援密鑰大小選擇。

**Comment by okudayukiko** [comment]
@iochen
https://www.v2ray.com/en/welcome/command.html 「Command name」正確為「Common name」。「Alternative name」正確為「Subject alternative name」。

**Comment by okudayukiko** [comment]
@iochen 
https://www.v2ray.com/en/welcome/command.html 「Command Name」正確為「Common Name」。「Alternative Name」正確為「Subject Alternative Name」。

**Comment by rikkihamano** [comment]
> @iochen
> https://www.v2ray.com/en/welcome/command.html 「Command Name」正確為「Common Name」。「Alternative Name」正確為「Subject Alternative Name」。

感謝通知，但由於 **V2Ray** 成員沒有對相應倉庫的訪問權限，我們會在 **V2Fly.com** 提供英文翻譯時注意此事。

**Comment by okudayukiko** [comment]
> > @iochen
> > https://www.v2ray.com/en/welcome/command.html 「Command Name」正確為「Common Name」。「Alternative Name」正確為「Subject Alternative Name」。
> 
> 感謝通知，但由於 **V2Ray** 成員沒有對相應倉庫的訪問權限，我們會在 **V2Fly.com** 提供英文翻譯時注意此事。

https://www.v2ray.com/chapter_00/command.html
中文版也錯

**Comment by rikkihamano** [comment]
> > > @iochen
> > > https://www.v2ray.com/en/welcome/command.html 「Command Name」正確為「Common Name」。「Alternative Name」正確為「Subject Alternative Name」。
> > 
> > 
> > 感謝通知，但由於 **V2Ray** 成員沒有對相應倉庫的訪問權限，我們會在 **V2Fly.com** 提供英文翻譯時注意此事。
> 
> https://www.v2ray.com/chapter_00/command.html
> 中文版也錯

是的，但我们同样没有权限。在 V2Fly.org 中已修改
