### ISSUE TITLE
现在 V2Ray 的 WS+TLS 能和真的 WS over TLS 区分吗？

### ISSUE THREAD

**Issue by 517030910405** [v2ray/discussion#781]
现在 V2Ray 的 WS+TLS 能和真的 WS over TLS 区分吗？
经过 Caddy/Nginx 之后，应该看不出 WS 了，那通过 TCP 包的大小/时间，有可能被区分吗？此外有其它不安全的地方吗？
谢谢！

**Comment by 517030910405** [comment]
主要是考虑给伪装的网站备案，不知道稳不稳

**Comment by genufish** [comment]
看出ws会怎么样？

**Comment by 517030910405** [comment]
> 看出ws会怎么样？

看出 Websocket 不要紧，怕的是看出不正常。如果真的除了暴力破解私钥外不可区分，才敢去备案。

**Comment by genufish** [comment]
好像看tls指纹的话，就知道有人用v2ray在连这个服务器呐。

**Comment by 517030910405** [comment]
> 好像看tls指纹的话，就知道有人用v2ray在连这个服务器呐。

原来 Client Hello 的问题还没有解决吗？
所以 [这个issue](https://github.com/v2ray/v2ray-core/issues/2542) 里面说的并不是完美解决了 Client Hello ？
