### ISSUE TITLE
能出一套走Cloudflare CDN但是不用websocket的方案吗

### ISSUE THREAD

**Issue by vbuterin2** [v2ray/discussion#785]
我们走需要cloudflare cdn但是不能用websocket，这样的话我们就可以使用fastly cdn，然后接入时使用fastly cdn，但是fastly不支持websocket。经测试http/1.1的cloudflare配置通不了?

**Comment by vbuterin2** [comment]
quic?

**Comment by ghost** [comment]
cf是免费还是付费用户？要是免费用户想开cdn只能用websocket

**Comment by vbuterin2** [comment]
> cf是免费还是付费用户？要是免费用户想开cdn只能用websocket

付费用户，另外一个事情，我想使用fastly cdn，如果能不用ws的话就能fastly，cloudflare通用了

**Comment by ghost** [comment]
> > cf是免费还是付费用户？要是免费用户想开cdn只能用websocket
> 
> 付费用户，另外一个事情，我想使用fastly cdn，如果能不用ws的话就能fastly，cloudflare通用了

如果是企业版用户，应该是可以用tcp开cdn，因为只有企业版用户可以转发tcp，不过这只是我的猜测，因为我也没试过；如果不是，只能用websocket开cdn，不然还是直接用你找的那个cdn吧。

**Comment by vbuterin2** [comment]
> > > cf是免费还是付费用户？要是免费用户想开cdn只能用websocket
> > 
> > 
> > 付费用户，另外一个事情，我想使用fastly cdn，如果能不用ws的话就能fastly，cloudflare通用了
> 
> 如果是企业版用户，应该是可以用tcp开cdn，因为只有企业版用户可以转发tcp，不过这只是我的猜测，因为我也没试过；如果不是，只能用websocket开cdn，不然还是直接用你找的那个cdn吧。

对的，但是转发TCP怎么做不通呢？

**Comment by vbuterin2** [comment]
> > > > cf是免费还是付费用户？要是免费用户想开cdn只能用websocket
> > > 
> > > 
> > > 付费用户，另外一个事情，我想使用fastly cdn，如果能不用ws的话就能fastly，cloudflare通用了
> > 
> > 
> > 如果是企业版用户，应该是可以用tcp开cdn，因为只有企业版用户可以转发tcp，不过这只是我的猜测，因为我也没试过；如果不是，只能用websocket开cdn，不然还是直接用你找的那个cdn吧。
> 
> 对的，但是转发TCP怎么做不通呢？

有没有一个你们通过的TCP配置

**Comment by ghost** [comment]
> > > > > cf是免费还是付费用户？要是免费用户想开cdn只能用websocket
> > > > 
> > > > 
> > > > 付费用户，另外一个事情，我想使用fastly cdn，如果能不用ws的话就能fastly，cloudflare通用了
> > > 
> > > 
> > > 如果是企业版用户，应该是可以用tcp开cdn，因为只有企业版用户可以转发tcp，不过这只是我的猜测，因为我也没试过；如果不是，只能用websocket开cdn，不然还是直接用你找的那个cdn吧。
> > 
> > 
> > 对的，但是转发TCP怎么做不通呢？
> 
> 有没有一个你们通过的TCP配置

爱莫能助。如果你说的是cf，企业版我没用过，所以也不清楚具体应该怎样配置，我用的是websocket开cdn；fastly cdn我也没用过，建议你问问客服是否支持纯tcp转发

**Comment by genufish** [comment]
cf访问源站只有http1.1和websocket，你想不用websocket的话，得希望开发者能考虑用两个http1.1连接（一上传一下载）来承载一个tcp连接数据
