### ISSUE TITLE
各位最近两天,websocket是否阻断及断流严重？

### ISSUE THREAD

**Issue by lxhao61** [v2ray/discussion#786]
最近两天发现vmess+websocket+tls+web，socks+websocket+tls+web等配置，阻断及断流严重，基本不能正常看视频。表现为突然无流量，延迟突出增大。若取消翻墙等待一下或切换其它websocket账号，刚开始正常，随后又反复出现之前情况。
讨论：v2ray的websocket是否被墙精准识别了？另外trojan也不好使了（降速也有点大），但不会断流。

**Comment by genufish** [comment]
有用cdn么？

**Comment by okudayukiko** [comment]
還有一種可能是VPS本來就限制了UDP下載導致看視頻緩慢。

**Comment by lxhao61** [comment]
没有用。

**Comment by mbcc2006** [comment]
你的服务器ip被定向丢包了.这是电信运营商给你的特殊照顾,期望你去买加速包.当然冠冕堂皇点就是出口带宽不够用,丢你的包,给VIP让路.你可以凌晨3-4点的时候体验下急速的快感

**Comment by lxhao61** [comment]
我也怀疑被针对了。
我当时使用VMess+WS+TLS+Caddy1，VMess+H2+Caddy1应用，临时强制仅TLS1.3使用了一天，结果就出现了上述情况。第二天改回默认TLS1.2 TLS1.3自适应，结果就回不来了。
目前有什么办法解决不？当然不买加速包。
