### ISSUE TITLE
关于服务器端与Selinux冲突问题

### ISSUE THREAD

**Issue by EL-File4138** [v2ray/discussion#787]
官方的教程均没有提到在最简单配置下与SELinux冲突的问题，网络上其他现有的教程解决方案基本均为“关闭SELinux”。
有没有什么办法能够让SELinux放行V2Ray相关，或者说可否提供一个V2Ray需要访问的资源清单以便逐个放行呢？

**Comment by okudayukiko** [comment]
一般是SELinux阻擋了nginx

**Comment by rikkihamano** [comment]
You can try to google that. 
I use apparmor and apparmor won't block that.

**Comment by mbcc2006** [comment]
selinux是个非常繁琐的鬼东西,我在公司都基本禁用,个人用户禁用selinux是常规选择.默认最简单配置一般是不可能因为selinux被ban的,因为selinux一般管理1000以下的端口,自动生成的端口都是10000以上.你是不是被忽悠了?

**Comment by EL-File4138** [comment]
我坚持se是因为1.RHCSA RHCE这些考试都要求全程在se环境下操作 2. se确实救过我司机密文件一条命
翻了翻log，应该和端口没大关系，更有可能是因为服务器的奇怪初始配置导致v2需要摸到某个受保护的文件才能运行然后被se限制了

________________________________
发件人: mbcc2006 <notifications@github.com>
发送时间: 2020年8月8日星期六 09:48
收件人: v2ray/discussion
抄送: Matrew File; Author
主题: Re: [v2ray/discussion] 关于服务器端与Selinux冲突问题 (#787)


selinux是个非常繁琐的鬼东西,我在公司都基本禁用,个人用户禁用selinux是常规选择.默认最简单配置一般是不可能因为selinux被ban的,因为selinux一般管理1000以下的端口,自动生成的端口都是10000以上.你是不是被忽悠了?

―
