### ISSUE TITLE
nftabels 配置

### ISSUE THREAD

**Issue by junknet** [v2ray/discussion#788]
透明代理的包处理是基于iptables
能否换成nftables

**Comment by ToutyRater** [comment]
可以。我去年做过这项工作，nftables的相关规则也都写得差不多，但iptables用着很好，一直没动力更换到nftables。因为我写得规则没实际长时间运行过，不好贴出来，如果你有需要可以自己研究一下

**Comment by junknet** [comment]
> 可以。我去年做过这项工作，nftables的相关规则也都写得差不多，但iptables用着很好，一直没动力更换到nftables。因为我写得规则没实际长时间运行过，不好贴出来，如果你有需要可以自己研究一下

emmmmm 我搞了一两天...搞不好.....
可以给我看看你写的实验版本吗

**Comment by ToutyRater** [comment]
我回去找找。但是我电脑清理过，不一定还在。要是这样只能发给你一些参考资料了

**Comment by ToutyRater** [comment]
https://www.dazhuanlan.com/2019/09/26/5d8ca8b9730d5/
https://wiki.nftables.org/wiki-nftables/index.php/Matching_packet_metainformation
https://owent.net/2020/2002.html

比较悲剧的是不仅我当时写的规则不知道去哪了，保存的参考网站的书签也找不到了，我又重新搜索过，上面这几个链接是我曾参考过的，希望对你有帮助

**Comment by junknet** [comment]
> https://www.dazhuanlan.com/2019/09/26/5d8ca8b9730d5/
> https://wiki.nftables.org/wiki-nftables/index.php/Matching_packet_metainformation
> https://owent.net/2020/2002.html
> 
> 比较悲剧的是不仅我当时写的规则不知道去哪了，保存的参考网站的书签也找不到了，我又重新搜索过，上面这几个链接是我曾参考过的，希望对你有帮助

谢谢你，参考你的资料 我摸索出了 ntf的配置
v2ray 核心的内容有点多....我拿v2ray做后端sock5服务, 自己写了个sock5第三方tproxy对接到v2ray上....
