### ISSUE TITLE
4.x 如何指定主出站协议的?

### ISSUE THREAD

**Issue by liximomo** [v2ray/discussion#79]
对于 4.x 的 `routing.rules`, 文档只这样说的.

> 对应一个数组，数组中每个元素是一个规则。对于每一个连接，路由将根据这些规则依次进行判断，当一个规则生效时，即将这个连接转发至它所指定的outboundTag(或balancerTag，V2Ray 4.4+)。当没有匹配到任何规则时，流量默认由**主出站协议**发出。

4.x 的输出协议是一个数组 `"outbounds": []`, 我想知道**主出站协议**要如何设置?

**Comment by nobody3u** [comment]
大概是按这个顺序：
  "outbound": {},
  "outboundDetour": [{}, ...], //这个数组的第一个
  "outbounds": [{}, ...] // 这个数组的第一个

官方文档没明确说，只是试出来的，不确定。

**Comment by sunshineplan** [comment]
outbounds: [OutboundObject]

一个数组，每个元素是一个出站连接配置。**列表中的第一个元素作为主出站协议**。当路由匹配不存在或没有匹配成功时，流量由主出站协议发出。

https://www.v2ray.com/chapter_02/01_overview.html

**Comment by liximomo** [comment]
@nobody3u @sunshineplan 感谢!
