### ISSUE TITLE
使用代理后，浏览器都可以正常访问youtube，但是代码无法访问youtube，相同的url在浏览器是可以访问的，是需要代码访问时额外配置代理吗？

### ISSUE THREAD

**Issue by chenwenqin** [v2ray/discussion#790]
使用代理后`chrome`访问 [新闻](https://www.youtube.com/watch?v=7Uv_lF-xrQA)没问题，但是使用代码访问出现 **etimedout** 问题，怀疑是代码中未使用到`v2ray`的代理服务

同时发现，使用`windows`的`power shell`的`curl`是可以访问的，但是其他的命令行工具的`curl`指令也会出现 **etimedout**错误

**Comment by rikkihamano** [comment]
请查看 log
若 log 中未出现目标地址，则说明未走代理

**Comment by usgate** [comment]
有些程序需要单独设置，并不是默认走windows系统代理的。你需要在代码中设置使用代理

**Comment by chenwenqin** [comment]
> 请查看 log
> 若 log 中未出现目标地址，则说明未走代理

@iochen  log上面没有地址，要怎么设置呢，我这边使用的是nodejs

**Comment by chenwenqin** [comment]
> 有些程序需要单独设置，并不是默认走windows系统代理的。你需要在代码中设置使用代理

请问你这边有这方面的经验吗，我尝试过在代码里面设置代理，但是不行，使用的是nodejs，axios模块

**Comment by chenwenqin** [comment]
我试在代码设置代理，但是还是无法访问

**Comment by chenwenqin** [comment]
另一个代理工具是可以的，我怀疑是跟咱们的协议有关
