### ISSUE TITLE
路由配置文件是否可以用简单的文本格式编写？

### ISSUE THREAD

**Issue by RallyQ** [v2ray/discussion#791]
想将v2配置文件中的路由域名配置用单独的文件实现，不再直接编辑v2配置文件
想照猫画虎，但是用文本编辑软件打开查看geosite.dat，很多不明字符，好像无法直接编辑？请问用什么软件能编辑路由域名配置？v2配置支不支持调用简单的文本文件格式？
想将走代理的直连的屏蔽的都写入单独文件，方便编辑添加

**Comment by yomnxkcs** [comment]
config.json里面不写"geosite:cn"之类配置就不会用到geosite.dat文件。所以如果你把所有routing的网址都直接写在配置文件里面就不需要编辑geosite.dat。然后可以用v4.23.0引入的[多文件配置](https://www.v2fly.org/chapter_02/multiple_config.html)功能把routing配置分割出来变成一个独立文件，避免每个服务器都要添加一次的问题。最后[PaPerseller/chn-iplist](https://raw.githubusercontent.com/PaPerseller/chn-iplist/master/v2ray-config_rule.txt)这个项目里有个不错的routing模子，可以考虑在他的基础上增删内容。注意在最外层多套个花括号。

补充：geosite.dat其实是把一个字典序列化成Protocol Buffers二进制格式再输出到文件得出。所以想编辑geosite.dat可以写个小脚本，把他转成文本格式，编辑后再转回protobuf。网上应该有这样的脚本，不过我没用过就不推荐了。

**Comment by RallyQ** [comment]
> 
> 
> config.json里面不写"geosite:cn"之类配置就不会用到geosite.dat文件。所以如果你把所有routing的网址都直接写在配置文件里面就不需要编辑geosite.dat。然后可以用v4.23.0引入的[多文件配置](https://www.v2fly.org/chapter_02/multiple_config.html)功能把routing配置分割出来变成一个独立文件，避免每个服务器都要添加一次的问题。最后[PaPerseller/chn-iplist](https://raw.githubusercontent.com/PaPerseller/chn-iplist/master/v2ray-config_rule.txt)这个项目里有个不错的routing模子，可以考虑在他的基础上增删内容。注意在最外层多套个花括号。
> 
> 补充：geosite.dat其实是把一个字典序列化成Protocol Buffers二进制格式再输出到文件得出。所以想编辑geosite.dat可以写个小脚本，把他转成文本格式，编辑后再转回protobuf。网上应该有这样的脚本，不过我没用过就不推荐了。

感谢回复！
仔细看了多文件配置，原来可以将路由等项单独成为一个配置同时载入，我试试。
再次感谢！

**Comment by rikkihamano** [comment]
I don't know what you want to do exactly, maybe you can refer this repo: by editing files under `data/` and in this way, you can custom your route.
https://github.com/v2fly/domain-list-community

**Comment by RallyQ** [comment]
> 
> 
> 我不知道您要确切执行的操作，也许您可​​以参考此存储库：通过编辑文件，`data/`并以此方式，您可以自定义路线。
> https://github.com/v2fly/domain-list-community

好的，谢谢回复！

**Comment by XuuKoo** [comment]
其实要是各平台、各软件的分流规则能基本通用就好了。（clash、小火箭、quanx这几个之间几乎通用，不需要大改；而v2的路由规则是单独的体系）

**Comment by makaspacex** [comment]
@yomnxkcs  protobuf文件不具备自描述性 需要外部文件来描述其结构 所以 在不通的语种之间使用并不方便 如果没有生成其他语言的meta信息，是很难在其他语言中使用的
