### ISSUE TITLE
目前是否可以实现vmess+H2C+caddy(v2)+tls不？

### ISSUE THREAD

**Issue by lxhao61** [v2ray/discussion#792]
caddy v1版官方已停止支持，目前已全部切换到v2版，从v2.1.0开始已支持H2C，目前最新版是v2.1.1。
v2ray从v4.20.0版就支持了H2C，目前最新版是v4.26.0。
那么是否可以实现vmess+H2C+caddy(v2)+tls，非之前vmess+H2+caddy(v1)。若可以实现，希望大神们告知，且提供配置模板，特别是caddy(v2)配置。谢谢！
另外若不能实现，那么是否可以实现vmess+H2+caddy(v2)，其caddy(v2)配置怎样弄？谢谢！
上述相关信息如下：
caddy官方网：https://caddyserver.com  （已无v1版）
caddy v2.1.0介绍（H2C支持）：https://github.com/caddyserver/caddy/releases/tag/v2.1.0
v2ray v4.20.0 介绍（H2C支持）： https://github.com/v2ray/v2ray-core/releases/tag/v4.20.0
vmess+H2+caddy（v1）模板：https://github.com/veekxt/v2ray-template/tree/master/H2%2Bvmess%2BCaddy

**Comment by lxhao61** [comment]
明白了。万分感谢告知及提供caddy(v2)配置！

**Comment by mixool** [comment]
昨晚憨憨的没有去编译最新的caddy，一直没成功，看了上面的回复，成功了。贴一下v2ray服务端部分配置：
```bash
        {
            "port": 48032,"listen":"127.0.0.1","protocol": "vmess",
            "settings": {"clients": [{"id": "4d1b87ab-b78a-90fc-c12e-daft8a623218"}]},
            "streamSettings": {"network": "h2","httpSettings": {"path": "/PjoGJ3Ou","host": ["xxx.com"]}}
        }
```

**Comment by lxhao61** [comment]
折腾编译最新caddy2已弄好；但刚发现不必自己编译，其实caddy2源已编译了，下载即可。
具体地址：https://github.com/caddyserver/caddy/actions?query=workflow%3ATests
选一个最新编译的目录点击进入，根据自己系统下载对应包。

**Comment by lxhao61** [comment]
目前 caddy2 的 v2.2.0-rc.1 版完美支持 v2ray 的 H2C了，可以实现 H2(HTTP/2) 应用。
