### ISSUE TITLE
Changing UUID in config breaks v2ray

### ISSUE THREAD

**Issue by nadimaj** [v2ray/discussion#797]
Sorry, noob. Whenever I change the UUID in the config file on the server, despite reboots, it completely breaks the service. Cannot even telnet to the same port anymore. Stick to the default user and it's fine. Why?

**Comment by genufish** [comment]
UUID只包含0-9和a-f，长度是8-4-4-4-12，比如66f818ca-d78d-48ec-a5fc-34ac0faecb6b，自己先检查一下？

**Comment by nadimaj** [comment]
谢谢。实际上，在我不了解uuid格式之前。我一直在阅读。现在，我得到了更好的通知
