### ISSUE TITLE
时至今日，是否推荐打开mux？

### ISSUE THREAD

**Issue by XuuKoo** [v2ray/discussion#798]
网上有很多关于mux的说法，有说会断流建议关闭的，白话教程写可以提高并发（看起来是推荐打开）。
那时至今日，是否建议打开mux？

**Comment by mbcc2006** [comment]
个人建议看丢包率,丢包率超过30%就别打开mux,mux是多个请求走一个通道,丢包率过高的话,会导致感觉上的断流,因为tcp重发包这个过程比较费力,而mux内部的多个请求都等着,体感很差,我的丢包率一向30%,所以开启mux之后能感觉到偶尔的卡顿明显

**Comment by XuuKoo** [comment]
> 
> 
> 个人建议看丢包率,丢包率超过30%就别打开mux,mux是多个请求走一个通道,丢包率过高的话,会导致感觉上的断流,因为tcp重发包这个过程比较费力,而mux内部的多个请求都等着,体感很差,我的丢包率一向30%,所以开启mux之后能感觉到偶尔的卡顿明显

感谢解答。

我不是很懂技术细节，但是之前有类似的猜想，“要丢一起丢”而导致断流。

我这边做了几个测试。

1.同样的网络环境下（美西，mtr测试回程最末节点10%左右丢包，wifi），iOS下比较容易碰到卡顿（断流），特别是使用speedtest测速后马上打开其他app，大概率会提示没有网络；而win下几乎没有感觉到卡顿（断流）。（iOS客户端：小火箭，win客户端：qv2ray）

2.win下，在chrome里，按F12，在network标签下 查看网页加载时间，对于google.com、facebook.com（登录页）、twitter.com（登录页）、duckduckgo.com等静态元素为主的网页，页面加载时间在开启mux时总比不开启mux时快1-2s（mux设置64、512则没什么区别），而对于youtube这种视频页，两者没什么差别。

3.有意思的是，联通4G连接上述同样的线路（美西，mtr测试回程最末节点12%左右丢包），在不打开多路复用时，拨打GV，明显感觉到语音卡顿（吞字），而打开多路复用后，语音变得十分流畅。（iOS客户端：小火箭）

**Comment by mbcc2006** [comment]
丢包不高,开起来的好处就是tcp建连更快,你如果愿意折腾可以再开启 tcp fast open试试.
