### ISSUE TITLE
Multiple Docker process for v2ray?

### ISSUE THREAD

**Issue by nadimaj** [v2ray/discussion#799]
I am trying to configure teddysun v2ray inside docker.

My first docker implementation for image: v2ray/teddysun works successfully and is able to read the config.json file in /etc/v2ray. /etc/v2ray is the default config file location in a non-docker implementation. So far so good...

My second implementation of the same image (targeted at /etc/v2ray**2** with a different config file) does not work as intended. The command used to create this is as follows:

sudo docker run -d -p 9001:9001 --name v2ray**2** --restart=always -v /etc/v2ray**2**:/etc/v2ray**2** teddysun/v2ray

The process is created and the port is exposed correctly (and reachable from the outside) but the second implementation does not appear to honor the settings of the config.json file in /etc/v2ray**2**.

**Comment by kslr** [comment]
`-v /etc/v2ray2:/etc/v2ray`
https://docs.docker.com/storage/volumes/
