### ISSUE TITLE
[咨询]大家都用什么"配置"玩PUBG？

### ISSUE THREAD

**Issue by DarienRaymond** [v2ray/discussion#8]
From v2ray-core created by [ghost](https://github.com/ghost) : v2ray/v2ray-core#1121  

1)  你正在使用哪个版本的 V2Ray？
v2.46

2)  你的使用场景是什么？
proxifier > socks5 > CLIENT > TCP > SERVER
proxifier > socks5 > CLIENT > mKCP > SERVER
proxifier > socks5 > CLIENT > WS+TLS > SERVER[nginx]
proxifier > socks5 > CLIENT > WS+TLS+CDN > SERVER[nginx]

3)  你看到的不正常的现象是什么？
a.) 使用TCP时，延时120ms+，偶尔卡顿（几分钟来一次），进大厅、返回大厅都比较慢；
b.) 使用mKCP时，延时60ms左右，频繁轻微卡顿（不影响游戏），偶尔大卡一下（回档），进大厅、开匹、返回大厅都很迅速。但是国际出口网络不好时会爆卡；
c.) 使用WS+TLS时，延时80~120ms波动，偶尔轻微卡顿（不影响游戏），但是每次连续玩2～3张地图后就开始各种卡顿（而且越来越卡，最后直至爆卡没法玩），必须退出游戏进程后，等一会儿再重新启动游戏才能正常。但是又只能持续玩个2张地图，然后又开始爆卡；
d.) WS+TLS 偶尔会延时会抽风，CDN套上就好了，但是延时会增加。

4)  你期待看到的正确表现是怎样的？
a.) 准备再试下 TLS 不要 webserver 中转；
b.) 想问下用 V2Ray 流畅吃鸡的朋友，你们用的什么配置？（ 比如mux设置、缓存设置什么的）

**Comment by r0achnnan9p** [comment]
延迟最低的应该是mKCP吧？
