### ISSUE TITLE
TLS 1.3可能被防火墙完全阻断，不知道是否对v2ray造成潜在影响

### ISSUE THREAD

**Issue by ghost** [v2ray/discussion#800]
https://www.iyouport.org/报告：中国的防火长城已经封锁加密服务器名称指/

**Comment by genufish** [comment]
TLS1.3不会被阻断，加密了TLS服务器名称（esni）的TLS1.3目前会被阻断。
esni只是tls 1.3的一个扩展。当前好象只有cloudflare和firefox可用，v2ray当前本身就不支持esni所以也没有影响。
未来的话，除非大多数网站强制要求esni，不然防火墙对于阻断esni带来的损害是可以接受的。

如果一个网站同时支持http和https，那防火墙可能会选择屏蔽https。
如果一个网站同时支持sni和esni，那防火墙可能会选择屏蔽esni。

**Comment by rikkihamano** [comment]
esni 如果将来有的话会是可选功能
