### ISSUE TITLE
透明代理下看版权视频 ip收集

### ISSUE THREAD

**Issue by edisonleung1** [v2ray/discussion#804]
问题更新
尽管已经找到了hbo所使用的域名，但还是无法在网关有v2的客户端上看hbo，网关只做了tcp的iptables规则，https://toutyrater.github.io/app/transparent_proxy.html 的udp设置好像有问题，请问视频会走udp吗？
谢谢

---------------------------------
这个问题并不是v2ray的问题其实，但是也不知道哪里问好了请大家帮忙看看

希望通过v2ray透明代理（v2ray在网关上）来看美国hbo/netfilx等美剧（有AirPlay/chromcast之类的所以只能做全局代理）

v2ray在网关上配合iptables，使用了
          "geosite:hbo",
          "ext:h2y.dat:hbo",
等的数据库来决定走不走代理，但是感觉不够全，经常会出现错误，而如果在手机上用SR全部数据走代理的时候则不会出错。
请问有没有额外的数据库，或者简易点的爬相关视频网站ip的工具？
谢谢！

**Comment by rikkihamano** [comment]
loglevel 调到 warning 及以下，看 log

**Comment by edisonleung1** [comment]
iOS用小火箭查看日志，发现hbo app会使用以下几个域名
          "geosite:hbo",
          "domain:hbo.com",
          "domain:hbomax.com",
          "domain:conviva.com",
          "domain:googleapis.com",
          "domain:appboy.com",
          "domain:itunes.apple.com",
