### ISSUE TITLE
请问allowInsecure到底要不要开？

### ISSUE THREAD

**Issue by jcyuan** [v2ray/discussion#805]
allowInsecure这个选项应该选true还是false?
我查了下。这个选项貌似是用于是否验证服务器发来的TLS安全性对吗？那选false应该才更安全是吧？但是我选了false就没法连接了，选true就能连接。请问是怎么回事并且如何解决？
谢谢。

**Comment by usgate** [comment]
你的证书有问题吧

**Comment by jcyuan** [comment]
> 你的证书有问题吧

其实我主要是一直有个疑问，服务端在用http服务器反代后，v2ray服务端还需要配置tls吗？应该不需要了吧？http服务器已经开了tls了。那么v2ray服务端是不会回发证书的，客户端开了要验证服务器的话，反倒会连不上了吧？

**Comment by usgate** [comment]
> 其实我主要是一直有个疑问，服务端在用http服务器反代后，v2ray服务端还需要配置tls吗？应该不需要了吧？http服务器已经开了tls了。那么v2ray服务端是不会回发证书的，客户端开了要验证服务器的话，反倒会连不上了吧？

这个验证应该是在客户端验证的，http服务器配置的证书，客户端来验证

**Comment by jcyuan** [comment]
> > 其实我主要是一直有个疑问，服务端在用http服务器反代后，v2ray服务端还需要配置tls吗？应该不需要了吧？http服务器已经开了tls了。那么v2ray服务端是不会回发证书的，客户端开了要验证服务器的话，反倒会连不上了吧？
> 
> 这个验证应该是在客户端验证的，http服务器配置的证书，客户端来验证

所以客户端验证这个东西作用是什么？防嗅探？不开不是更能省CPU吗。

**Comment by 517030910405** [comment]
> > > 其实我主要是一直有个疑问，服务端在用http服务器反代后，v2ray服务端还需要配置tls吗？应该不需要了吧？http服务器已经开了tls了。那么v2ray服务端是不会回发证书的，客户端开了要验证服务器的话，反倒会连不上了吧？
> > 
> > 
> > 这个验证应该是在客户端验证的，http服务器配置的证书，客户端来验证
> 
> 所以客户端验证这个东西作用是什么？防嗅探？不开不是更能省CPU吗。

客户端验证证书是为了防止中间人攻击。有可能真的客户端和攻击者建立了一个自签名证书的连接，攻击者冒充真的服务器，然后真的服务器和攻击者建立了一个自签名证书的连接，攻击者冒充真的客户端，这个时候攻击者可以随意读取客户端和服务器之间的通信，甚至可以篡改。

**Comment by jcyuan** [comment]
> > > > 其实我主要是一直有个疑问，服务端在用http服务器反代后，v2ray服务端还需要配置tls吗？应该不需要了吧？http服务器已经开了tls了。那么v2ray服务端是不会回发证书的，客户端开了要验证服务器的话，反倒会连不上了吧？
> > > 
> > > 
> > > 这个验证应该是在客户端验证的，http服务器配置的证书，客户端来验证
> > 
> > 
> > 所以客户端验证这个东西作用是什么？防嗅探？不开不是更能省CPU吗。
> 
> 客户端验证证书是为了防止中间人攻击。有可能真的客户端和攻击者建立了一个自签名证书的连接，攻击者冒充真的服务器，然后真的服务器和攻击者建立了一个自签名证书的连接，攻击者冒充真的客户端，这个时候攻击者可以随意读取客户端和服务器之间的通信，甚至可以篡改。

是的，我也觉得应该是这样。谢谢。
个人的话感觉开不开也无所谓了。
