### ISSUE TITLE
请教一个 v2ray 中 api 接口的问题

### ISSUE THREAD

**Issue by chakson** [v2ray/discussion#807]
我参考这篇文章：[调用 V2Ray 提供的 API 接口进行用户增删及流量统计查询操作](https://medium.com/@TachyonDevel/%E8%B0%83%E7%94%A8-v2ray-%E6%8F%90%E4%BE%9B%E7%9A%84-api-%E6%8E%A5%E5%8F%A3%E8%BF%9B%E8%A1%8C%E7%94%A8%E6%88%B7%E5%A2%9E%E5%88%A0%E6%93%8D%E4%BD%9C-adf9ff972973)

调用 v2ray 开放的一些 api 接口，例如，通过接口调用，添加了一个用户，接口调用也提示成功，但是查看 /etc/v2ray/config.json，发现配置并没有改变。

请问这个 api 接口调用是什么原理，要怎么样才能使它永久生效。

**Comment by rikkihamano** [comment]
Duplicate of https://github.com/v2ray/discussion/issues/68
