### ISSUE TITLE
help to setup v2ray as gateway!!! please

### ISSUE THREAD

**Issue by evadogstar** [v2ray/discussion#809]
I'm give up, I am completely upset.

Second day I'm trying to setup any solution to redirect traffic system-wide or at least redirect external traffic to opened socks5 (dokodemo-door) by v2ray. It not work under my linux :-(

No success with socks5 and redirect traffic to it with marks or without marks to run only like gataway for external devices.

> sudo iptables -t nat -A PREROUTING -p tcp -j REDIRECT --to-ports 1080

The next thing that I tried https://github.com/eycorsican/go-tun2socks this tun2socks script and it almost run fine... I see that v2ray received messages by `curl` exits with empty response 
Log:
> 2020/08/12 16:43:40 tcp:127.0.0.1:33724 accepted tcp:1.1.1.1:80 [proxy] 

Maybe I must use this https://github.com/eycorsican/go-tun2socks
but it's not per-compiled :-( And lack of tutorials :-((

Please, help!!! 
I only want to use v2ray as gateway for my other devices! If it will redirect traffic system-wide it's also ok!

**Comment by kslr** [comment]
https://github.com/springzfx/cgproxy

evadogstar <notifications@github.com> 于2020年8月13日周四 上午1:00写道：

**Comment by evadogstar** [comment]
@kslr Thank you very much, looks encouraging  ! I will try this :-)
