### ISSUE TITLE
你们这么大张旗鼓的开源分发……

### ISSUE THREAD

**Issue by CocosGames** [v2ray/discussion#81]
就不怕别有用心的人拿去研究制定对策？

**Comment by Cwek** [comment]
ss不也是一样？而且两者都有公开协议设计文件的。

现在使用AEAD的ss和vmess，宣称上传输特征不明显，传输流都是由加密IV或密钥和加密数据，无明显明文传输的特征值，暂时没有公开的主动探测问题或者实现，唯一能入手的只有流量分析，但是这本身也是一个靠猜的手段。

基本上这类公开发布的对抗分析技术，肯定会被关注，但至少老鼠还是有点看头，而且v2包含更多通用手段，可以灵活调整应对。
