### ISSUE TITLE
Caddy 2的最新测试版v2.2.0-rc.1已经可以完美支持V2Ray的H2C模式，经测试可以使用。

### ISSUE THREAD

**Issue by proxysu** [v2ray/discussion#810]
Caddy 2在版本2.1.0就已经支持H2C。（https://github.com/caddyserver/caddy/releases/tag/v2.1.0）
但是实际使用中，并不能与V2Ray的H2C模式相适配，原因是Caddy 2存在一个Bug。
这个Bug在最新的测试版v2.2.0-rc.1中已经修复，我下载这个测试版，在测试中Caddy 2的H2C已经可以与V2Ray的H2C搭配使用。各个配置文件模板如下：
Caddy 2配置文件：https://github.com/proxysu/windows/blob/master/TemplateConfg/Http2Web_server_config.caddyfile
V2Ray服务端配置：https://github.com/proxysu/windows/blob/master/TemplateConfg/Http2Web_server_config.json
V2Ray客户端：https://github.com/proxysu/windows/blob/master/TemplateConfg/Http2Web_client_config.json
安装Caddy 2的测试版v2.2.0-rc.1命令如下：
wget https://github.com/caddyserver/caddy/releases/download/v2.2.0-rc.1/caddy_2.2.0-rc.1_linux_arm64.deb
apt install ./caddy_2.2.0-rc.1_linux_arm64.deb
systemctl enable caddy
系统Debian 9

不急用的，可以等Caddy 2的v2.2.0正式版出来。

**Comment by fbion** [comment]
mark

**Comment by bilibilistack** [comment]
transport http {
            versions h2c 2
caddyfile这里最后面的参数2是什么作用？
