### ISSUE TITLE
能不能将tcp拆成2个http连接

### ISSUE THREAD

**Issue by genufish** [v2ray/discussion#815]
服务器ip更改比较困难，cdn在保护ip方面还是很好用的。
但cf连接源服务器只有websocket和http1.1，所以目前在cf上只能使用ws来实现长连接通信。
那能不能将一个tcp连接拆成一个http1.1的上传连接和一个http1.1的下载连接来适应cdn？

**Comment by rikkihamano** [comment]
那两个都得有公网IP，而且效果可能还没有ws好

**Comment by genufish** [comment]
> 那两个都得有公网IP，而且效果可能还没有ws好

为啥两个都要公网ip？网站上传和下载也没要求客户端要公网ip吖。客户端发起两个http请求，一个上传请求，一个下载请求，然后http头设置个标志位让服务器认可两个连接关系。最后上行数据走上传请求，下行数据走下载请求不行吗？

**Comment by genufish** [comment]
或者客户端先发起一个http1.1下载请求，服务器先返回一个随机路径。然后客户端再向随机路径发起一个上传请求。接下来上行全部走上传，下行全部走下载。ws是不错，但可能有的cdn不支持。

**Comment by kslr** [comment]
如果进行一些取舍是可以做到的，你可以试试做一个

**Comment by ghost** [comment]
Web 开发者们在还没有 WebSocket 的时候，曾经使用一种叫做长连接的技巧实现服务器主动推送消息，你可能需要复活这种技巧以达到比较好的全双工效果

**Comment by RPRX** [comment]
利用 http/1.1 的特性，我觉得完全可行，说不定比 ws 效率更高。

你描述的是同一个 TCP 连接内，这里还有另一个方向：https://github.com/v2ray/v2ray-core/issues/2696

**Comment by RPRX** [comment]
具体实现应该是 0-RTT 的，无需协商路径，服务端通过某种方式来自动判断 http/1.1 请求是下载还是上传：

0. 协议本身支持（兼容性差，不建议
1. 预分配不同的 path（若非同一个 TCP 连接内，则区分不了多个连接，不可行。若确定是同一个 TCP 连接内，则不如直接 3
2. **随机的 header 或参数，第一次是下载，第二次是上传（无论是否同一个 TCP 连接内，都可以区分多个连接，十分可行**
3. 直接认定同一个 TCP 连接内第一个请求是下载、第二个请求是上传（但 CDN 回源可能会分成两个 TCP 连接，所以有局限性

**Comment by rprx** [comment]
ws 和 h2 都对传输的数据进行了一定程度的封装，而 http/1.1 似乎没有，所以这个方案的效果应该更好（相较于 ws，还少了一次握手

**Comment by RPRX** [comment]
ws 和 h2 对传输的数据进行了相对复杂的封装，而 http/1.1 的很简单，所以这个方案的效果应该更好（相较于 ws，还少了一次握手

**Comment by RPRX** [comment]
如果是两个 TCP 连接，则可以第一次是上传，第二次是下载，且可以采用 http/1.0，省掉 `transfer-encoding: chunked`。

（不过不确定 CDN 回源 http/1.0 的行为，还是用 http/1.1 吧，无论一个还是两个 TCP 连接

**Comment by BlueSedDragon** [comment]
之前寫過一個類似的項目，但是不知道怎麼回事，數據傳輸時會損壞，所以就棄用了，這個可以作為一個參考：
https://gist.github.com/BlueSedDragon/a0daf2c785fc4af43292f8a34f6c4007

**Comment by genufish** [comment]
> 如果是两个 TCP 连接，则可以第一次是上传，第二次是下载，且可以采用 http/1.0，省掉 `transfer-encoding: chunked`。
> 
> （不过不确定 CDN 回源 http/1.0 的行为，还是用 http/1.1 吧，无论一个还是两个 TCP 连接

感觉tcp on http连接的话，甚至可以套用phproxy之类的网页代理进行连接。而且上下流可以分别选择不同代理，第三方看来甚至可以是a到b和c到d的两个完全无关连接
