### ISSUE TITLE
'Auto' system wide proxy

### ISSUE THREAD

**Issue by aboka2k** [v2ray/discussion#817]
hi, would like to ask is there anyway to make v2ray to support system wide proxy like SS? all the guide i found online for v2ray needs manual proxy setup for each browser, program.

thank you,

**Comment by Neverends4** [comment]
3rd party programs like v2rayng/qv2ray can do this. However from my experinence you still need apps like Proxifier for some programs.

**Comment by chromer030** [comment]
Use V2ray + Redsocks
