### ISSUE TITLE
安装脚本更新时是否会覆盖service配置文件

### ISSUE THREAD

**Issue by XuuKoo** [v2ray/discussion#823]
为了使用uds传输，修改了 /etc/systemd/system/v2ray.service，不知道使用install-release.sh来更新的时候是否会覆盖该文件？

**Comment by xqzr** [comment]
亲测不会

**Comment by XuuKoo** [comment]
> 亲测不会

谢谢

**Comment by XuuKoo** [comment]
> 亲测不会

昨天更新到4.28.1 实测会覆盖。
因为 是计划任务自动更新，被覆盖后弄的我断网，排查了半天才发现这个问题。

**Comment by xqzr** [comment]
> > 亲测不会
> 
> 昨天更新到4.28.1 实测会覆盖。
> 因为 是计划任务自动更新，被覆盖后弄的我断网，排查了半天才发现这个问题。

版本问题吧 4.28没试过
