### ISSUE TITLE
vless 回落能否到指定网页或档案

### ISSUE THREAD

**Issue by delphinuz** [v2ray/discussion#831]
目前fallback 可到指定的port，如caddy/nginx的port 80，有无机会改成某网页，像是 dest: "https://github.com"？
或指定的档案，像是 dest: "files://home/website/index.html"？

这样 caddy/nginx 也不用安装了。

**Comment by RPRX** [comment]
有计划，目前不是重点。

**Comment by shenlijun** [comment]
可以在nginx上一个端口反代一个档案或者网页吧
