### ISSUE TITLE
所以如果想使用xTLS就不能用Caddy吗？

### ISSUE THREAD

**Issue by mervynsword** [v2ray/discussion#832]
这可能是个很傻的问题，但是作者表示需要使用VLESS over TCP with TLS，由VLESS 需要直接处理 TLS

VLESS+Caddy的使用环境下，服务器端配置应使用
```
"network": "h2",
"security": "none",
```
且Caddy的配置中要设置将h2转换成未加密的h2c。

所以xTLS是否能配合Caddy使用？是否有大佬测试过？

**Comment by RPRX** [comment]
不可以，VLESS 需要直接操作 XTLS。

**Comment by RPRX** [comment]
但是你可以设置 VLESS 回落到 Caddy。

**Comment by mervynsword** [comment]
关于回落机制我现在还没能很好的理解，看了examples中的示例，目前是参考https://github.com/v2fly/v2ray-examples/tree/master/VLESS-H2C-Caddy2
的例子部署的，如果要使用xtls的话，相关配置要如何进一步修改呢？

**Comment by RPRX** [comment]
简单来说，回落就是把 TLS 解密后不属于 VLESS 的流量转发给 Web 服务器，由后者来处理。请参考：

https://github.com/v2fly/v2ray-examples/tree/master/VLESS-TCP-TLS%20(minimal%20by%20rprx)

**Comment by RPRX** [comment]
“不属于 VLESS” 指的是首包长度 < 18 或协议版本无效、身份认证失败。

**Comment by mervynsword** [comment]
嗯，明白了，如果使用回落或者xTLS的话，向服务器发起的https数据连接是先由VLESS接手并进行解密，符合特征的就代理，不符合的就发送至本地的web服务器，比如nginx或者Caddy。是这样的吗？

但是目前我参考的配置，依然是由Caddy做分流，不管是否符合特征，只要path满足条件就统统扔给VLESS。所以要放弃这种思路，443端口应该由VLESS监听而不是Caddy。这样理解对吗？

如果是这样的话，对于我这样的Caddy用户来说其实相当于放弃了Caddy最重要的特性：全自动https。因为Ｖ2版本的Caddy如果不监听443端口就不会自动申请证书了…额…还挺矛盾的😅

**Comment by RPRX** [comment]
可以使用 crontab 来定时申请证书与重启 v2ray，v2ray 以后也可能会加入自动申请、更新证书的功能。

**Comment by mervynsword** [comment]
感谢

**Comment by sandianyue** [comment]
> “不属于 VLESS” 指的是首包长度 < 18 或协议版本无效、身份认证失败。

事实上我我对此一直也有个疑问 如果“首包长度 < 18 或协议版本无效、身份认证失败”即“不属于443的VLESS+TCP+TLS inbound"就要参与回落 这时匹配了回落中的VLESS（VMess）+WSS的path尝试转发过去 如果又不符合 会再次参与回落从而转发到默认项 比如 dest:80 吗？

**Comment by RPRX** [comment]
@sandianyue 

不会，但这个前提就不存在，因为 path 也相当于密码，只有你自己知道。

**Comment by littlef0x** [comment]
> 如果是这样的话，对于我这样的Caddy用户来说其实相当于放弃了Caddy最重要的特性：全自动https。因为Ｖ2版本的Caddy如果不监听443端口就不会自动申请证书了…额…还挺矛盾的😅

That's not correct. Caddy uses port 80 for certificate rather than 443. If you do not have other websites on port 443, you can simply run the https one on other ports without losing the feature of automatic https.

Caddy can also be used to [manage certificate without running a https server](https://caddy.community/t/using-caddy-to-keep-certificates-renewed/7525).

**Comment by littlef0x** [comment]
> 
> 
> 不可以，VLESS 需要直接操作 XTLS。

@rprx 
I wonder whether there is observable negative impact on the performance of website if I use v2fly as frontend and caddy/nginx as fallback. If yes, is it possible to add path feature to xtls? Thanks.

**Comment by RPRX** [comment]
@littlef0x 

回落到 Caddy 时 TLS 表现是完全一致的（因为都是 Go），Nginx 不确定。

**Comment by littlef0x** [comment]
@rprx 
OK, thanks. BTW, there's such statement in Trojan-Go doc:

> 事实上，你甚至可以将Trojan-Go当作你的HTTPS服务器，用来给你的网站提供HTTPS服务。访客可以正常地通过Trojan-Go浏览你的网站，而和代理流量互不影响。但是注意，不要在remote_port和fallback_port搭建有高实时性需求的服务，Trojan-Go识别到非Trojan协议流量时会**有意增加少许延迟**以抵抗GFW基于时间的检测。

I just wonder whether v2fly has similar design. If not, is it necessary to add this feature?

**Comment by rprx** [comment]
@littlef0x 

不，VLESS 的 fallbacks 更先进，详见文档。

**Comment by RPRX** [comment]
@littlef0x 

不，VLESS 的 fallbacks 防探测原理更先进，详见文档。

另外 VLESS 的 fallbacks 支持 h2、ds、PROXY protocol，更适合建站。

**Comment by aptx17** [comment]
> 可以使用 crontab 来定时申请证书与重启 v2ray，v2ray 以后也可能会加入自动申请、更新证书的功能。

哥，我想问个问题，如果证书到期是不是会立即连接失败。还有如果使用acme.sh定期更新证书，那么运行中的v2ray是否会自动识别新的证书，还是需要自己手动restart v2ray才能重载？我看网上好像没说到这个。

**Comment by phoenixxie0** [comment]
@rprx vless的xtls是否能够设置fallbacks到v2ray的http/2接口。我的v2ray上的h2c接口配置如下
`{
            "listen": "/dev/shm/v2ray/vlessws.socket",
            "protocol": "vless", 
            "settings": {
                "clients": [
                    {
                        "id": "UUID"
                    }
                ],
                "decryption": "none"
            }, 
            "streamSettings": {
                "network": "http", 
                "httpSettings": {
                    "host": [
                        "domain.domain"
                    ],
                    "acceptProxyProtocol": true,
                    "path": "/websocket"
                }
            }, 
            "disableInsecureEncryption": true
        }`
fallbacks 的配置如下：
`{
                        "path": "/websocket",
                        "dest": "/dev/shm/v2ray/vlessws.socket",
                        "xver": 1
                    },`

**Comment by mervynsword** [comment]
已实验过相关配置，参见https://github.com/XTLS/Xray-core/issues/278
