### ISSUE TITLE
ws+tls走443端口能免流吗

### ISSUE THREAD

**Issue by zqs125** [v2ray/discussion#836]
为了搞ws+tls免流折腾了好多天，就是不能免，普通的ws+80端口是可以免的，群友说不走tls不安全，走ws+tls也是可以免的，可我就是弄不成功，跪请大神指点一下，ws+tls到底能不能免流，要怎么搞也可以成功？

**Comment by 1265578519** [comment]
打开https sni试一下，应该可以免流。

**Comment by zqs125** [comment]
> 打开https sni试一下，应该可以免流。

试过了，免不了

**Comment by xqzr** [comment]
也许运营商只能80端口免 可以试试拿80端口跑ws+tls

**Comment by Sucre888** [comment]
能不能发我一下教程 我也想弄一下免流

**Comment by polarxy** [comment]
> 为了搞ws+tls免流折腾了好多天，就是不能免，普通的ws+80端口是可以免的，群友说不走tls不安全，走ws+tls也是可以免的，可我就是弄不成功，跪请大神指点一下，ws+tls到底能不能免流，要怎么搞也可以成功？

443能不能免呀

**Comment by Element-Square** [comment]
tcp 呀
