### ISSUE TITLE
[VLESS][XTLS]如何显示日志

### ISSUE THREAD

**Issue by ghost** [v2ray/discussion#837]
设置环境变量`V2RAY_VLESS_XTLS_SHOW = true`后在哪里看XTLS的输出。
我在服务端运行
```export V2RAY_VLESS_XTLS_SHOW=true```
后重启了V2Ray服务，在access.log和error.log中均没有发现XTLS的日志输出

**Comment by RPRX** [comment]
（可能只能在 CLI 看）

**Comment by RPRX** [comment]
fmt.Println

**Comment by ghost** [comment]
> （可能只能在 CLI 看）

好吧
