### ISSUE TITLE
DNS：是否有可能加入dnscrypt或者类似的机制

### ISSUE THREAD

**Issue by i2Ray** [v2ray/discussion#84]
昨天有用户提议在客户端加入DNSCrypt的支持。想了下，这个功能是否也可以直接添加到V2Ray-Core之中。刚才浏览了下issue列表，其他用户确实也有类似的需求：
https://github.com/v2ray/discussion/issues/24#issue-356071626
https://github.com/v2ray/discussion/issues/67#issuecomment-439251711

关于DNSCrypt的部分资料：
https://dnscrypt.info/faq
https://github.com/jedisct1/dnscrypt-proxy
https://www.rubyfish.cn/

PS：其实不一定是遵循DNSCrypt，只需要类似的机制即可，让本地客户端的dns请求，交由服务端来处理。

**Comment by i2Ray** [comment]
仔细想了下，当前阶段不太适合添加至V2Ray-Core中，属于另外一大块的东西。

**Comment by i2Ray** [comment]
应该把UDP也扔给V2Ray-Core处理就好了

**Comment by goldencorvus** [comment]
确实目前DNS走本地是个大问题，特别是在大陆上国外的网站的话肯定不希望暴露DNS服务器位置。如果这个问题不解决怎么放心使用呢。

**Comment by i2Ray** [comment]
> 确实目前DNS走本地是个大问题，特别是在大陆上国外的网站的话肯定不希望暴露DNS服务器位置。如果这个问题不解决怎么放心使用呢。

应该项目组也有考虑这个问题的，看官方Twitter最新一篇就是讲DNS over TCP的。
