### ISSUE TITLE
VLESS 的目的是不是跑偏了，不是为了TLS协议吗，现在xtls有什么作用？

### ISSUE THREAD

**Issue by 1265578519** [v2ray/discussion#840]
VLESS 的目的是不是跑偏了，不是为了TLS协议吗，现在xtls有什么作用？

**Comment by RPRX** [comment]
1. VLESS 的目标早就是全场景了。

2. XTLS 可以理解为是增强版 ECH，即支持代理转发、明文加密、UDP over TCP（VLESS），并且顺便解决了一些 TLS in TLS 的特征问题。

3. https://www.v2fly.org/config/protocols/vless.html#xtls-%E9%BB%91%E7%A7%91%E6%8A%80

**Comment by k79e** [comment]
@rprx 那个xtls是 xmpp tls么?? 还是另一个名字一样的东西?

**Comment by RPRX** [comment]
> 
> 
> @rprx 那个xtls是 xmpp tls么?? 还是另一个名字一样的东西?

文档有链接，建议仔细看。

**Comment by k79e** [comment]
`XTLS 作为一个特殊的实用性技术，实际测试及模拟测试应当符合它的实用场景，即代理大流量 TLS 数据（16k data record），且最好是独立机器以便观察。若测试方式有误，甚至有可能不如普通 TLS，比如使用 XTLS 且开启它的特殊功能（flow）后只跑非 TLS 数据，会不断产生尝试识别 TLS data record 的开销（v4.31.0+ 已解决此问题）。`

看起来应该是2个不同的项目 xmpp那边自称要设计个新的tls 叫xmpp tls 简称就是xtls
而且rfc草案都有 里面好像也提到了性能什么的 :D

这个还是注明一下比较好吧 别哪天那边的xtls真搞出来了 到时候让人看的更疑惑了.

**Comment by kslr** [comment]
如果你指的是 rfc7590 那是不同的东西，为什么要标注？

**Comment by k79e** [comment]
记错了 不是rfc的 是个memo 我晕啊...
但是他们那个也叫xtls

https://xmpp.org/extensions/inbox/xtls.html


**XTLS**: End-to-End Encryption for the Extensible Messaging and Presence
          Protocol (XMPP) Using Transport Layer Security (TLS)
                   draft-meyer-xmpp-e2e-encryption-02
https://tools.ietf.org/html/draft-meyer-xmpp-e2e-encryption-02
