### ISSUE TITLE
使用 v2ray + vmess 协议  有些网站打不开 怎么回事chrome报 攻击者可能会试图从 www.reddit.com 窃取您的信息

### ISSUE THREAD

**Issue by waxnssg** [v2ray/discussion#842]
您的连接不是私密连接
攻击者可能会试图从 www.reddit.com 窃取您的信息（例如：密码、通讯内容或信用卡信息）。了解详情
NET::ERR_CERT_COMMON_NAME_INVALID
Subject: *.facebook.com

Issuer: DigiCert SHA2 High Assurance Server CA

Expires on: 2020年12月10日

Current date: 2020年10月10日

www.reddit.com 通常会使用加密技术来保护您的信息。Google Chrome 此次尝试连接到 www.reddit.com 时，此网站发回了异常的错误凭据。这可能是因为有攻击者在试图冒充 www.reddit.com，或 Wi-Fi 登录屏幕中断了此次连接。请放心，您的信息仍然是安全的，因为 Google Chrome 尚未进行任何数据交换便停止了连接。

您目前无法访问 www.reddit.com，因为此网站使用了 HSTS。网络错误和攻击通常是暂时的，因此，此网页稍后可能会恢复正常。

**Comment by xqzr** [comment]
DNS污染

**Comment by waxnssg** [comment]
我买了个其他的vpn 就能上
但是我自己搭的 就不行
这样 怎么处理呢

**Comment by 1265578519** [comment]
Subject: *.facebook.com dns污染很明显了，pac列表中加一下这个域名，或者使用全局模式

**Comment by waxnssg** [comment]
多谢  大佬 解决了

**Comment by yangfan2008** [comment]
waxnssg  如何解决的，我目前采用vmess+websocket+tls+nginx 遇到HSTS 类的如www.reddit.com,无法访问，其它都正常
