### ISSUE TITLE
VLESS + mKCP + XTLS 如果可以回落到 QUIC 是否有一定的意义？

### ISSUE THREAD

**Issue by tsanie** [v2ray/discussion#843]
目前我的服务器入口是 `VLESS` + `TCP` + `XTLS`，监听在 `443` 端口，回落到 `nginx server`。
但是由于我这里连接服务器丢包率实在有点高，现在看到个新增的 `mKCP` + `XTLS` 组合，就增加了一个入口，监听在 `UDP 443` 端口上。

那么问题出现了，有没有方法可以让这个 `UDP 443` 在外部链接进来没有鉴权成功时回落到例如 `nginx` 的 `QUIC` 服务上。（文档上写的 `fallbacks` 目前仅能用于 `TCP` + `TLS` 组合）

---

我不敢确定，或许 `mKCP` + `XTLS` 的流量特征与 `QUIC` 差异巨大，这样做没有任何意义。
希望有人可以帮我解惑。

**Comment by RPRX** [comment]
VLESS over XTLS over mKCP over UDP，在这里 mKCP 和 QUIC 是同级的，目前 fallbacks 只能回落到与 VLESS 同级的应用上。

所以实现方式需要是 mKCP 回落到 QUIC，不好操作，且他们都基于 UDP 包，不确定能否完美实现（而无可探测的明显特征）。

流量特征方面，的确差异巨大，所以加个回落没有意义。

但可以把 QUIC 改得暴力一些。
