### ISSUE TITLE
最新版本security字段服务端与客户端不匹配也都能连上

### ISSUE THREAD

**Issue by Paris0-0** [v2ray/discussion#844]
如题，security不管填什么好像都能连得上，alterID0和非0都试过了，貌似已经完全不关security的事了？

**Comment by kslr** [comment]
自适应

**Comment by Paris0-0** [comment]
> 自适应

服务端不是auto也自适应了吗，我客户端服务端都没填auto啊😂

**Comment by kslr** [comment]
默认auto从来没有变过

**Comment by Paris0-0** [comment]
> 默认auto从来没有变过

哦哦才发现现在服务端已经没有security字段了。。我的配置文件这块几年没改了，，打扰了，谢谢😂
