### ISSUE TITLE
Vless回落nginx，二级目录访问失败

### ISSUE THREAD

**Issue by edisonleung1** [v2ray/discussion#847]
现有问题，v2ray功能正常，访问网站正常，但是访问网站的二级目录会出现错误：
because the server unexpectedly dropped the connection

不知道是v2ray的fallback问题，还是我的配置出问题了？
谢谢！

v2ray configure类似https://github.com/v2fly/v2ray-examples/blob/master/VLESS-TCP-XTLS-WHATEVER/config_server.json
，只有默认fallback到xxx端口。

Nginx config

server {
    server_name domain.com;
    listen 80;
    return 301 https://$server_name$request_uri;
    charset utf-8;

    location /{
        root /domain.com;
        index index.html;
    }
    
    location /dir {
        root /domain.com;
        index index.html;
        auth_basic        "Please enter you user name and password";
        auth_basic_user_file    /domain.com/.htpasswd;
    }
}
server {
    server_name domain.com;
    listen xxx http2;
    charset utf-8;

    location /{
        root /domain.com;
        index index.html;
    }
    
    location /dir {
        root /domain.com;
        index index.html;
        auth_basic        "Please enter you user name and password";
        auth_basic_user_file    /domain.com/.htpasswd;
    }
}

**Comment by shenlijun** [comment]
抄这个

**Comment by shenlijun** [comment]
https://github.com/v2fly/v2ray-examples/tree/master/VLESS-TCP-TLS%20(maximal%20by%20rprx)
