### ISSUE TITLE
现在有支持HTTP2回源的CDN么？

### ISSUE THREAD

**Issue by frank-pian** [v2ray/discussion#853]
在nodecache上搞了半天H2套CDN，一直不成功，后来看讨论大部分CDN都是HTTP2访问，回源依然是HTTP。
所以H2套CDN基本做不到？

**Comment by ghost** [comment]
现在没有能支持http2回源的cdn啦。因为市面上绝大多数服务都是基于开源软件二次开发的，如果它们服务的上游（例如nginx、caddy、haproxy等）不加入正式化支持的话短期内肯定是不要想的啦。
不过呢，如果是自建中转站那还好，直接转发tcp连接就行了。
