### ISSUE TITLE
配置 git config --global http.proxy 没效果  求大佬 帮看

### ISSUE THREAD

**Issue by waxnssg** [v2ray/discussion#854]
是有socks5  代理上网 全局模式 可以上google  但是git clone 非常慢
git config --global http.proxy socks5://127.0.0.1:1086
git config --global https.proxy socks5://127.0.0.1:1086
以后 依然没变化 感觉没生效 什么原因呢
检查了本地 socks5 监听端口 正确的
.gitconfig 里面的配置如下:
[http]
        lowSpeedLimit = 0
        lowSpeedTime = 999999
        proxy = socks5://127.0.0.1:1086
[https]
        proxy = socks5://127.0.0.1:1086

执行 这个 就非常慢 git clone https://github.com/googlefonts/sfntly.git

**Comment by kslr** [comment]
http(s).proxy  为什么使用socks5 ?

**Comment by waxnssg** [comment]
> http(s).proxy 为什么使用socks5 ?
因为我用的代理方式是socks5
使用的是ShadowSocksNG  全局模式 上网
之前设置成这样 结果也是一样的
git config --global http.proxy http://127.0.0.1:1081
git config --global https.proxy https://127.0.0.1:1081

**Comment by kslr** [comment]
基础使用问题帮不了 （ 你还可以去ng那里问问
