### ISSUE TITLE
dokodemo-door问题

### ISSUE THREAD

**Issue by edisonleung1** [v2ray/discussion#856]
1.类似的情况https://github.com/v2ray/v2ray-core/issues/1926 ，access log出现了未知的外知的ip，而且使用了未知的端口。
inbound只有dokodemo-door和vless两个，删除vless之后情况依旧。
网络结构：
Isp router-my router，my router既是内网的网关，v2所在的机器，也是被dmz到外网的服务器，现在猜测是不是外网能通过dokodemo-door的端口来连接？
如果是，有什么设置来禁止外网连接的dokodemo-door的端口呢？

2.
在iptables设置prerouting之后，微信图片经常加载缓慢或者失败（direct outbound)，现在怀疑是这部分设置（如下）有关，sniffing关闭之后，微信图片就能加载正常了。请问大家dokodemo都是怎么设置sniffing和streamsetting的？

  
inbound:

    "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "streamSettings": {
        "sockopt": {
          "tproxy": "redirect"
        }
      }

outbound:

  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "streamSettings": {
          "sockopt": {
            "mark": 255
          }
        }
      }
    },

谢谢！

**Comment by nJhEqnvK** [comment]
遇到过类似的情况，v2ray直接部署在openwrt（网关，有公网ip）上，然后被弄成了肉鸡发垃圾邮件和做攻击跳板，bwh VPS也被封了。

目前的解决方案是通过v2ray部署在旁路由实现，直接藏在NAT后就很安全了

**Comment by edisonleung1** [comment]
> 遇到过类似的情况，v2ray直接部署在openwrt（网关，有公网ip）上，然后被弄成了肉鸡发垃圾邮件和做攻击跳板，bwh VPS也被封了。
> 
> 
> 
> 目前的解决方案是通过v2ray部署在旁路由实现，直接藏在NAT后就很安全了

准备用多个listen来凑合，要是listen能listen ip段就好了。。。
