### ISSUE TITLE
A Proposal on the Usage of ZEXE blockchain

### ISSUE THREAD

**Issue by analytic-bias** [v2ray/discussion#859]
The ZEXE paper: [https://eprint.iacr.org/2018/962.pdf](https://eprint.iacr.org/2018/962.pdf)

If a ZEXE blockchain is built, it will serve as a solution to the well-known Airport-Manager (机场主) leak, and potentially pose a solution to the GFW problem.

As the author of this post does not have the professionality and stamina to read and comprehend the loc. cit., I appeal to the V2Ray community to verify this concept and, if it's possible, produce a prototype.

In order to proclaim progression, and to maintain impartiality, this is also a post for the GFW builders (建墙者): I urge you to find a counter-solution to my proposal and implement it if possible so that humankind's understanding of cryptography would further.

Please reach out to me at [https://t.me/cute_girl_sayako](https://t.me/cute_girl_sayako), should a clarification is in order.

**Comment by xiaokangwang** [comment]
I had a talk with the author of this post, and here is a summary:

Improvement compared to current design ( *claim not verified* ) : 

1. The connection will appear to be a blockchain synchronizing connection to evade DPI
2. The proxy connection will be automatically chained to protect the privacy of user. The operator provably do not hold the activity of user it collected payment from.
3. The network will have a common currency and payment system to protect user's prepaid credit from bad operator
4. It will not allow the unconditional enumeration of node, and instead, the user will need to pay in the network's currency to get more peers (effectiveness contested)

However:

Point 1 can accomplished by a blockchain synchronizing connection proxy/transport, without the need of a full cryptocurrency network.
Point 2 can accomplished by using tor.
