### ISSUE TITLE
中转的协议不能是http吗？

### ISSUE THREAD

**Issue by jo-bili** [v2ray/discussion#861]
"inbounds": [
        {
            "port": 12312,
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "my-uid",
                        "level": 1,
                        "alterId": 64
                    }
                ]
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {}
        },
        {
            "tag": "p1",
            "protocol": "http",
            "settings": {
                "servers": [
                    {
                        "address": "1.1.1.1",
                        "port": 23423,
                        "users": [
                            {
                                "Username": "myusername",
                                "Password": "mypassword"
                            }
                        ]
                    }
                ]
            }
        }
    ],
    "routing": {
        "rules": [
            {
                "type": "field",
                "outboundTag": "p1",
                "domain": [
                    "domain:whoer.net"
                ]
            }
        ]
    }
}

确认http代理有效的情况下，其他外网都能正常访问，唯独whoer.net打不开，，求助，，，，，，，

**Comment by Tiamisu** [comment]
http代理没法代理包括传统dns查询在内的udp服务,routing时的你的domain很可能没法解析
