### ISSUE TITLE
proxySettings could be able to used as a pre-proxy? 

### ISSUE THREAD

**Issue by mygodccl** [v2ray/discussion#865]
my question is I have to through the compay's proxy to connect the Internet, then connect to the vmess proxy, below is my guess:
![image](https://user-images.githubusercontent.com/15084961/107192145-35df6100-6a28-11eb-83b8-26519c28ea2d.png)

like the ssr:
![image](https://user-images.githubusercontent.com/15084961/107191845-c2d5ea80-6a27-11eb-8470-834f2e43e1c9.png)

but the result is ssr can success to connect the remote socks proxy, but v2ray can't connect to the remote vmess proxy.

**Comment by rikkihamano** [comment]
```
{
	"outbounds":[
		{
			"protocol":"...",
			"settings":{
				...
			},
			"tag":"OUT-1",
			"proxySettings":{
				"tag":"OUT-2"
			}
		},
		{
			"protocol":"socks",
			"settings":{
				...
			},
			"tag":"OUT-2"
		}
	]
}
```

**Comment by rikkihamano** [comment]
I didn't view your question carefully, sorry.

**Comment by mygodccl** [comment]
I have successed in compay env, the 'proxySettings' is the right way to break through compay firewall.
1. the company used http protocol, so the tag 'company' should use a http protocol.
2. the window10 use the http protocol to connect the v2ray, so the inbounds should have a http protocol inbounds.
