### ISSUE TITLE
客户端频繁切换远端服务器的需求

### ISSUE THREAD

**Issue by ghost** [v2ray/discussion#866]
你好，我是个应用开发者，我在一个应用中集成 V2Ray 程序以支持广泛的联网能力。了解到 V2Ray 读取配置文件来获取远端服务器的相关配置，而我的使用场景需要经常切换远端服务器，_目前的做法是修改配置文件然后重启 V2Ray 程序_。

但是这样总感觉不好，对于经常切换远端服务器的场景有没有什么推荐的做法？需要你们的帮助，谢谢！

**Comment by rikkihamano** [comment]
https://www.v2fly.org/config/api.html#apiobject

**Comment by ghost** [comment]
我的客户端软件有一个远端服务器列表，点一下就切换到那个远端服务器。流程是大概这样：
1. 关闭当前的 V2Ray 进程
2. 把远端服务器信息更新到 config 文件
3. 启动 V2Ray 进程重新读取 config

这样就切换到新的远端服务器了，但是整个流程有点耗时（有一两秒吧），而且感觉有点低效。如果客户端程序能和 V2Ray 进程通信（IPC），更新配置啥的，我觉得就省事很多。

**Comment by rikkihamano** [comment]
用 API 删除现有的出站代理，并添加新的出站代理
详细见：https://www.v2fly.org/config/api.html#apiobject

**Comment by ghost** [comment]
好的，谢谢

Mail sent from Android
mail: xinlake@outlook.com
https://xinlake.dev

________________________________
