### ISSUE TITLE
配置文件内的地址填写为域名时，每次开始连接v2，都会重新解析域名吗，用的dns是否是系统自带的？

### ISSUE THREAD

**Issue by sujoshua** [v2ray/discussion#867]
v2是每次开始连接的时候都会主动获取ip吗？连接成功后都是靠本地缓存了吗？若使用的是系统自带有无方法修改为自定义？

**Comment by 20NE** [comment]
用的DNS是你配置文件設置的，但你說的對，會一直解析域名。
