### ISSUE TITLE
mismatching end group marker

### ISSUE THREAD

**Issue by movila** [v2ray/discussion#869]
Hi, 

I received following error `github.com/v2fly/v2ray-core/v4/infra/conf: invalid field rule > github.com/v2fly/v2ray-core/v4/infra/conf: failed to load geoip: private > proto: mismatching end group marker`

Please help.

**Comment by kslr** [comment]
check geoip sha256

**Comment by movila** [comment]
I ran command `sha256sum -c geoip.dat.sha256sum` and the sha256 is ok

**Comment by movila** [comment]
Generate a new `geoip.dat` manually fixed this issue. Thanks for help.
