### ISSUE TITLE
DNS解析的疑问

### ISSUE THREAD

**Issue by a13547** [v2ray/discussion#87]
V2ray在路由器中做透明代理，并且用iptables只转发全部TCP流量时，dns解析是在什么地方完成的呢？是局域网中的设备先根据自身设置解析出ip，再转发相应的TCP流量到V2ray，还是先全部转发到V2ray，然后根据V2ray中的设置解析出ip并匹配代理规则呢？如果是第一种情况的话，是不是说，v2ray中的dns设置和域名路由设置都无效了呢？

**Comment by Cwek** [comment]
第一个情况。理论上，是。
