### ISSUE TITLE
怎么设置代理http流量，直连https流量

### ISSUE THREAD

**Issue by 7980963** [v2ray/discussion#873]
当前配置文件：/var/etc/v2ray/v2ray.main.json

{
	"log": {
		"access": "/dev/null",
		"loglevel": "warning",
		"error": "/var/log/v2ray-error.log"
	},
	"dns": {
		"hosts": {
			"example.com": "127.0.0.1"
		},
		"servers": [
			"1.1.1.1",
			"8.8.8.8",
			{
				"address": "114.114.114.114",
				"port": 53,
				"domains": [
					"geosite:cn"
				]
			},
			{
				"address": "223.5.5.5",
				"port": 53,
				"domains": [
					"geosite:cn"
				]
			}
		]
	},
	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
			{
				"type": "field",
				"ip": [
					"geoip:private",
					"geoip:cn"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"domain": [
					"geosite:cn"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"protocol": [
					"bittorrent"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"port": "53",
				"network": "udp",
				"inboundTag": [
					"transparent"
				],
				"outboundTag": "dns_out"
			},
			{
				"type": "field",
				"ip": [
					"114.114.114.114",
					"223.5.5.5"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"ip": [
					"1.1.1.1",
					"8.8.8.8",
					"208.67.222.222"
				],
				"outboundTag": "proxy"
			},
			{
				"type": "field",
				"port": "123",
				"network": "udp",
				"outboundTag": "direct"
			}
		]
	},
	"policy": {
		"system": {
			"statsInboundUplink": true,
			"statsInboundDownlink": true
		}
	},
	"inbounds": [
		{
			"listen": "0.0.0.0",
			"port": 1081,
			"protocol": "dokodemo-door",
			"settings": {
				"followRedirect": true,
				"network": "tcp"
			},
			"streamSettings": {
				"sockopt": {
					"tproxy": "redirect"
				}
			},
			"tag": "transparent",
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http"
				]
			}
		}
	],
	"outbounds": [
		{
			"sendThrough": "192.168.1.1",
			"protocol": "vmess",
			"settings": {
				"vnext": [
					{
						"address": "",
						"port": ,
						"users": [
							{
								"id": "",
								"alterId": 64
							}
						]
					}
				]
			},
			"streamSettings": {
				"network": "kcp",
				"kcpSettings": {
					"congestion": false,
					"header": {
						"type": "none"
					}
				},
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "proxy"
		}
	]
}

**Comment by kslr** [comment]
Try source port

**Comment by 7980963** [comment]
> Try source port

Thanks bro，its work :)
