### ISSUE TITLE
utorrent走代理下载六维的东西 无法下载

### ISSUE THREAD

**Issue by Kinco4TC** [v2ray/discussion#874]
原本是使用ss来实现下载的
在阅读完指引手册后  我将utorrent的代理端口改成了v2rayN的sock5端口，在v2rayN能看到utorrent发送的请求，但是utorrent依旧无法下载
目前猜测是vmess协议无法支持下载ipv6的资源？ 或者需要怎么修改配置呢？
请懂的或者搞过的大佬们赐教。

**Comment by abcdpm** [comment]
六维空间需要教育网的IPv6地址才可以访问下载
