### ISSUE TITLE
v2rayN-Core.zip和v2rayN.zip，这两个有什么区别？

### ISSUE THREAD

**Issue by tauyyy** [v2ray/discussion#875]
请问一下大佬：
刚接触这个软件，有两个版本供下载v2rayN-Core.zip和v2rayN.zip，这两个有什么区别？我应该下载哪一个？
刚才安装了v2rayN.zip，发现测试服务器真连接延迟显示操作失败，请检查重试，下面提示找不到Core。
2，右下角托盘的“清除系统代理”意思是直接连接？如果是改成“直接连接”是不是更通俗一些？清除系统代理感觉怪怪的
  是应该设置为“自动配置系统代理”还是“不改变系统代理”？

**Comment by kslr** [comment]
1. 到对应软件社区
2.

**Comment by tauyyy** [comment]
> 1. 到对应软件社区

你的回答就这几个字?
