### ISSUE TITLE
v2rayN客户端解压到D盘服务器数据无法保存

### ISSUE THREAD

**Issue by tauyyy** [v2ray/discussion#877]
win10系统
4.20最新版
把客户端v2rayN解压到D盘，退出重启后导入的服务器数据无法保存也不能翻墙，界面变成空白。解压到C盘也一样。

**Comment by tauyyy** [comment]
[](url)https://i.imgur.com/pDet5dE.png

**Comment by kslr** [comment]
这边是 core
