### ISSUE TITLE
使用官方一件脚本安装报错

### ISSUE THREAD

**Issue by gegehennb** [v2ray/discussion#88]
使用bash <(curl -L -s https://install.direct/go.sh)
进行安装

报错提示：
/dev/fd/63: line 1: syntax error near unexpected token `newline'

/dev/fd/63: line 1: `<!DOCTYPE html>'

root@mci:~# (23) Failed writing body

其他服务器都可以，就这一台vps这样，请大佬们帮忙看看

**Comment by iochen** [comment]
执行`curl -L -s https://install.direct/go.sh` 看输出结果
