### ISSUE TITLE
windows下的v2ray.exe出错时的退出行为

### ISSUE THREAD

**Issue by veekxt** [v2ray/discussion#89]
windows下多数人习惯双击运行v2ray，如果能直接看到错误信息可以减少很多麻烦。

**Comment by nobody3u** [comment]
二楼所提的其实是程序定位问题，v2ray.exe的定位是命令行，wv2ray.exe的定位是后台服务，所以有这些行为。而且托盘图标则是GUI的功能，显然v2ray的定位不是GUI。

这也回答了1楼提的问题。一个命令行程序正确使用方式是在cmd/bash中通过命令调用。当这个程序出错或者运行结束时都应该返回错误码，让调用它的程序知道他的运行情况，然后作出相应的后续处理。觉得打命令麻烦，可以把v2ray.exe拖到cmd窗口然后回车，双击操作一般用在GUI上。

**Comment by youwei5683** [comment]
如果想用gui 建议使用 v2rayN。 v2ray本身就没有gui
