### ISSUE TITLE
On browser work well but windows cmd or other terminals dont work

### ISSUE THREAD

**Issue by Feruz00** [v2ray/discussion#891]
On browser work well. When I to install npm packages dont work. when I run command ping www.npmjs.com I get lost-100%.
I use global routing. How do this work at windows terminals?

**Comment by sunsunfish** [comment]
> 

did you other vpn plug-in？Maybe it conflict

**Comment by sunsunfish** [comment]
> On browser work well. When I to install npm packages dont work. when I run command ping [www.npmjs.com](http://www.npmjs.com) I get lost-100%. I use global routing. How do this work at windows terminals?


did you openning other vpn plug-in？Maybe it conflict
