### ISSUE TITLE
double-hop v2ray server

### ISSUE THREAD

**Issue by NimaEagle** [v2ray/discussion#892]
hi
i don't want anybody detect the main vpn server ip address so i thought it would be good if user connect through a middle vpn-server to main vpn-server.
in this way when user google for its ip he sees the main ip (last one in the chain). am i wrong ?
please help

**Comment by sunsunfish** [comment]
> hi i don't want anybody detect the main vpn server ip address so i thought it would be good if user connect through a middle vpn-server to main vpn-server. in this way when user google for its ip he sees the main ip (last one in the chain). am i wrong ? please help

I think，when user  google for its ip，it mean use the main vpn server to do it，I have no idea to ban it if you no ban user to google
