### ISSUE TITLE
Tor blocked in my area. How can i use proxychians + tor(service not browser) on kali??Tor 被墙， 怎么在kali上用ProXYCHIANS + TOR??

### ISSUE THREAD

**Issue by bujidewuji** [v2ray/discussion#912]
I tried tunnel tor packets though my v2ray(vmess + ws) , but it did not work..
The proxychains config file:
socks4 127.0.0.1 9050 (tor)
socks5 127.0.0.1 10800(v2ray core)

我试着把Tor的流量通过v2ray代理，但是没用

**Comment by highlander0test** [comment]
刚用v2ray搭建的，大家可以体验一下
欢迎体验
本网站处于推广阶段，联系群主，注册后提供邮箱，提供免费1个月体验机会
官网：https://www.bzg.life/
官群：https://t.me/BZG_group
