### ISSUE TITLE
服务器有多个ipv4和ipv6，如何让freedom使用指定的一组？

### ISSUE THREAD

**Issue by KyonLi** [v2ray/discussion#94]
尝试了设置`OutboundObject`中的`sendThrough`
```json
{
    "sendThrough": "0.0.0.0",
    "protocol": "freedom",
    "settings": {}
}
```
当设置为0.0.0.0时，ipv4、ipv6网站都能访问，但无法指定分别是哪个ip
当设置为ipv4地址时，只能访问ipv4网站
当设置成ipv6地址时，只能访问ipv6网站
要怎么设置才能ipv4、ipv6网站都能访问，并且出口ip是可以自定义的呢？

**Comment by Cwek** [comment]
"sendThrough": "0.0.0.0",
然后配置domainStrategy:  "UseIPv4" | "UseIPv6" （4.7+）
或者用路由，2000::/3全部走v6的出口，其他走v4。

**Comment by KyonLi** [comment]
@Cwek 感谢解答，使用路由方法成功解决了该问题。
